### ISSUE TITLE
Style of day in Month view. 

### ISSUE THREAD

**Issue by dmoskovsov** [intljusticemission/react-big-calendar#100]
Hey guys, thanks for amazing work here! 

I'm currently working on feature which requires to have days to have different background : 

<img width="1016" alt="screen shot 2016-05-25 at 4 02 44 pm" src="https://cloud.githubusercontent.com/assets/1140765/15532407/3e8df33a-2292-11e6-9fac-8df8d829429e.png">

I've tweaked library to accept 'days' collection and added 'dayPropGetter' which accept 'day object' and returns style object back: 

<img width="842" alt="screen shot 2016-05-25 at 3 36 04 pm" src="https://cloud.githubusercontent.com/assets/1140765/15532460/8d7b8ca0-2292-11e6-841d-f726cca96690.png">

Do you guys think this use case might be useful for the rest? If so I can clean-up the code a bit and submit a pull request. 

Thanks

**Comment by jquense** [comment]
sure sounds goods to me!

**Comment by bsjaffer** [comment]
@dmoskovsov can u share the code or let me know what you changed.

**Comment by isseu** [comment]
@dmoskovsov can you upload your code to a repo?
