### ISSUE TITLE
Readme on NPM is outdated

### ISSUE THREAD

**Issue by fsoikin** [intljusticemission/react-big-calendar#1000]
#### Do you want to request a _feature_ or report a _bug_?
A bug.

#### What's the current behavior?
[The NPM page](https://www.npmjs.com/package/react-big-calendar) for this component suggests using the `setLocalizer` method, which is no longer a thing. 

`Readme.md` in this repo [has been updated](https://github.com/intljusticemission/react-big-calendar/commit/edb36eec78b8a4fefce85aebcb60dd4033ea36fc), but this update hasn't made it to NPM.

#### What's the expected behavior?
NPM page should have the correct docs.

**Comment by jquense** [comment]
Npm don't let you update package docs unless you push a new version, so it'll update next release
