### ISSUE TITLE
No events are shown in Week/Day views if resourceId accessors are presented in event data

### ISSUE THREAD

**Issue by dmitrykrylov** [intljusticemission/react-big-calendar#1006]
#### Do you want to request a _feature_ or report a _bug_?
Bug (v 0.20.1)
#### What's the current behavior?

In the [example](https://codesandbox.io/s/04x04zw91p) I added an event with resourceId value set. It actually isn't shown in Day and Week views if resources prop isn't set.

#### What's the expected behavior?
If resources prop isn't set for Calendar component, it should not care if events data contains resourceIdAccessor

**Comment by klinskyc** [comment]
Bump - This is preventing us from updating. If anyone can point me to the right file to look at, I'm happy to check this on our end

**Comment by dmitrykrylov** [comment]
@klinskyc probably you should firstly check TimeGrid.js. It contains logic for week/work-week/day views. It would be great if you find any lead.

**Comment by dmitrykrylov** [comment]
@klinskyc @jquense added a pull request fixing this issue
