### ISSUE TITLE
Event resizing

### ISSUE THREAD

**Issue by McDoyen** [intljusticemission/react-big-calendar#1007]
#### Do you want to request a _feature_ or report a _bug_?
_bug_

#### What's the current behavior?
Once an event has been resized form one slot event to cover more than two slots, its not possible to resize it back to one slot.

![3](https://user-images.githubusercontent.com/19818344/46015651-7d752480-c0db-11e8-985c-c38a01349a4d.gif)

react big calendar v 0.20.1

**Comment by jquense** [comment]
what are the date values of the event starting, after resize, and as you try and set it back. I believe this is a sort of unfortunate quirk of date math (the worst)

**Comment by McDoyen** [comment]
@jquense After resizing back to 12th, some how the end date is 14th 

![3](https://user-images.githubusercontent.com/19818344/46061966-fecac680-c170-11e8-8b3e-15e2cce13bf9.jpeg)

**Comment by jquense** [comment]
Can you post a codesandbox with the one event? I really need to see the exact dates, it'll be easier if I can run something :thumbsup:

**Comment by McDoyen** [comment]
Was unable able to create the codesandbox, but I have just realized the same bug exists on the demo project http://intljusticemission.github.io/react-big-calendar/examples/index.html#dnd

**Comment by liben96** [comment]
Any updates on this bug?

**Comment by morrisgwilliam** [comment]
has this issue been resolved? I am having the same bug. Cannot shrink tthe event to one day unless the start date (left drag) has been modified. then the event is allowed to reduce to one day.
