### ISSUE TITLE
Styling appointments in the 'show more' popover

### ISSUE THREAD

**Issue by TMUND** [intljusticemission/react-big-calendar#101]
Thank you for the awesome calendar! 

I have different styling for appointments based on whether an appointment was confirmed or not, however, when there are multiple appointments for a single day in month view and I bring up the 'show more' popover, I only get one style for appointments (confirmed). How can I propagate the different (unconfirmed) style class to the appointments in the popover as well? They work great in day and week views, just not in the popover

Thanks!

**Comment by TMUND** [comment]
+1

**Comment by jquense** [comment]
I think this has been fixed?

**Comment by TMUND** [comment]
Hmm I did indeed find a workaround that I am having a hard time remembering the details of right now. If anyone runs across this in the future and needs help I can look :)
