### ISSUE TITLE
Is it possible to remove a time slot?

### ISSUE THREAD

**Issue by henriqueweiand** [intljusticemission/react-big-calendar#1013]
Contextualizing a little, I only need to display the schedules between:

7:30 a.m. - 12 p.m.
1:00 p.m. to 7:30 p.m

with the props I can put the min and max, but not this interval in half.

**Comment by jquense** [comment]
There isn't any way to render a disconnected range like that no, but you can control which slots are selectable by returning `false` from the onSelecting handler (I think thats the one)
