### ISSUE TITLE
Warning when click on show more button - Invalid prop `slotStart` of type `date` supplied to `Popup`, expected `number`

### ISSUE THREAD

**Issue by cis-ankity** [intljusticemission/react-big-calendar#1016]
#### Do you want to request a _feature_ or report a _bug_?
Bug
#### What's the current behavior?
When I click on the show more button it is showing the following warning in the console - 

**checkPropTypes.js:19 Warning: Failed prop type: Invalid prop `slotStart` of type `date` supplied to `Popup`, expected `number`.**

Here is the screenshot for the warning - 
![screenshot from 2018-10-01 14-11-53](https://user-images.githubusercontent.com/24387112/46278524-fcf36f80-c583-11e8-8045-2e9abd68d715.png)

#### What's the expected behavior?
It should not have to produce such type of warning.

**Comment by arjunkomath** [comment]
I'm facing the issue on React 16.4.0 and `react-big-calendar` 0.20.1 version.

```
Warning: Failed prop type: Invalid prop `slotStart` of type `date` supplied to `Popup`, expected `number`.
```

**Comment by Juldays** [comment]
I am also facing the same issue, React 16.4.2, react-big-calendar version 0.20.1.
![2018-10-01 09_52_45-react app](https://user-images.githubusercontent.com/31859207/46303108-d0c5f780-c55f-11e8-85b0-fc34e6cb6561.png)

**Comment by Pingvi** [comment]
Bug (
React 16.5.2, react-big-calendar version 0.20.1.
