### ISSUE TITLE
Current time indicator disappears at midnight

### ISSUE THREAD

**Issue by rojobuffalo** [intljusticemission/react-big-calendar#1017]
#### Do you want to request a _feature_ or report a _bug_?
bug

#### What's the current behavior?
The current time indicator disappears at midnight.

The condition in `positionTimeIndicator()` that checks `if (timeGutter && current >= min && current <= max)` is `false` and so `timeIndicator.style.display = 'none'` gets set. This happens if you load a page with RBC before midnight and then let it sit open until midnight and later. The default `max` is set to "today at local time 23:59:59". But the max doesn't get updated when the day ends. so `current <= max` is `false`.

Confirmed in Chrome and Firefox.

#### What's the expected behavior?
1) is this the expected behavior? this is relying on the default value for `max`.
2) should we add something that updates/refreshes `max` when `current` is midnight?

**Comment by rojobuffalo** [comment]
I goofed and thought this feature was already part of this repo. I'm using this fork https://github.com/sudoplz/react-big-calendar/ . So maybe put this on hold or ignore it until the time indicator in PR #950 gets added.

**Comment by SudoPlz** [comment]
I'm on it.

**Comment by SudoPlz** [comment]
https://github.com/intljusticemission/react-big-calendar/pull/1018 is ready to be merged

**Comment by SudoPlz** [comment]
Fix ^

**Comment by jquense** [comment]
Thanks for the issue @rojobuffalo we've decided not to fix this right now, you can see the justification in  The time indicator interval is now handled by TimeGrid #1023
