### ISSUE TITLE
Demo page has "Webpack App" title

### ISSUE THREAD

**Issue by Dyasik** [intljusticemission/react-big-calendar#1022]
#### Do you want to request a _feature_ or report a _bug_?

_bug_

#### What's the current behavior?
 
As you can see on the screenshot below, [page](http://intljusticemission.github.io/react-big-calendar/examples/index.html) title is "Webpack App", which I suppose is not the desired one.

![image](https://user-images.githubusercontent.com/12381295/46341889-75246880-c64a-11e8-98c9-9d122e6b40c6.png)

#### What's the expected behavior?

An informative title for the demo page.

**Comment by Georift** [comment]
This will be fixed once #997 is merged.
