### ISSUE TITLE
Day/Week View Event Tile doesn't show time on tile outside of Range

### ISSUE THREAD

**Issue by scottvincent** [intljusticemission/react-big-calendar#1024]
#### Do you want to request a _feature_ or report a _bug_?
Report a bug

#### What's the current behavior?
When there is an event where the start time is before the date min/max range of the view the start time isn't shown on the tile. 

### No min with a 3am start
![image](https://user-images.githubusercontent.com/4621427/46366610-85881380-c649-11e8-91d2-b5185045931e.png)

### 6am min with a 3am start
![image](https://user-images.githubusercontent.com/4621427/46366588-7012e980-c649-11e8-9b8c-20738812fb0a.png)

#### What's the expected behavior?

I would expect the time to still display on the tile even when that tile's start time is off the grid.

**Comment by jquense** [comment]
is this a case where the start time is in the day but before the min? or it starts on another day?

**Comment by sbusch** [comment]
I can't confirm this, works for me (at least in week view)

@scottvincent A working minimum example could be helpful.

**Comment by scottvincent** [comment]
@sbusch Just to be clear you are testing the same problem:

The view of the week is restricted to 6am to 11pm, The event starts at 3am that day. (outside of the range of the view) the 3am start is not showing on the card, and it only shows the end time.

even though there is custom styling in this screenshot, the functionality that isn't working would be the same. like this:
![image](https://user-images.githubusercontent.com/4621427/51131565-20be8680-17fe-11e9-8345-3110be9f4d05.png)

The expectation is to see "3:00am - 5:00pm"
