### ISSUE TITLE
Bug render last week rows in October 2018 

### ISSUE THREAD

**Issue by lucasdu4rte** [intljusticemission/react-big-calendar#1028]
#### When rendering the month of October 2018, it adds the second line of the next month one with only one day, with more days on the same line.
Strange because in other months it is correct.
Could it be CSS interference? I do not use another type of calendar in this project.

<img width="1006" alt="captura de tela 2018-10-03 as 00 45 55" src="https://user-images.githubusercontent.com/22087517/46389596-396cbb80-c6a9-11e8-9c33-bdca9caee5f7.png">

#### What's the expected behavior?
Big Calendar is expected to complete the last line of the month with the dates

Thanks!

**Comment by pjkp** [comment]
The problem occurs each year, the last day of october.
An example with a different displaying : 
![image](https://user-images.githubusercontent.com/24681759/46535925-2fb3a580-c8ad-11e8-81e7-cdd38bf3a739.png)

**Comment by anna-kartynnik** [comment]
Hi, I was just wondering in which timezone you render your calendar? Maybe your issue is connected with #1044 and DST changes? Some of the countries have DST end date on 28th of October. Maybe, that's why you have the problem only for October...

**Comment by pjkp** [comment]
Hi Anna, you 're right, it must be the DST !!! 
Look at this good but too late news :) https://www.independent.co.uk/news/world/europe/eu-end-daylight-savings-time-zones-member-states-europe-a8203446.html

**Comment by gacra** [comment]
I don't know if is related to this issue, but in the week view, the 4th of November is appearing incorrectly in the week of 28th of October  to 3th of November.
The same occur with the 1th of November in the week of 4th of November to 10th of November.

![week_wrong](https://user-images.githubusercontent.com/12484906/47430290-45f7a780-d76f-11e8-8527-a25744840b36.png)

**Comment by quyphan** [comment]
I also am having similar issue.  I am in California where we do daylight savings on November 4th (Sunday).

![screen shot 2018-11-02 at 10 17 02 am](https://user-images.githubusercontent.com/24657232/47930842-62d85d00-de8a-11e8-9253-8cf012693e24.png)
