### ISSUE TITLE
Event with no end date not showing up

### ISSUE THREAD

**Issue by adamsythe** [intljusticemission/react-big-calendar#1030]
I have everything up and working however when I have events that have no data for end date the event doesnt show up in the calendar at all.  Is their a way to make events with just a start date show up in the calendar?

**Comment by cis-ankity** [comment]
without end date, you can not show an event on react-big-calendar  and If you want to show the event which does not contain an end date, you need to add a condition through which if there is no end date then event will take start date as end date and then you can show that event on calendar.

**Comment by adamsythe** [comment]
This feels like a bug as it is reasonable for api to not force users to enter an end date if they dont know how long an event will take

**Comment by adamsythe** [comment]
the same way google calendar does reminders, but i guess since google calendar enforces end dates to events it makes sense that this repo would do the same

**Comment by arecvlohe** [comment]
@adamsythe Although this library mimics google calendar it is not an exact replica. It would probably be good to enforce end dates but that is probably something you could do on your end for when users create events. I think for now, it's sound to provide a default end date for the event to remove your issue.
