### ISSUE TITLE
Cannot read property 'momentLocalizer' of undefined

### ISSUE THREAD

**Issue by raptor1989** [intljusticemission/react-big-calendar#1035]
In my project I am trying to initialize react-big-calendar but it's saying that it doesn't exist. 
my package versions: "react-dom": "16.2.0", "react-big-calendar": "^0.20.1", "moment": "^2.22.2",
Why I can't use the solution below? Something was changed in version 0.20?
`BigCalendar.setLocalizer(BigCalendar.momentLocalizer(moment));`
Because:
`Property 'setLocalizer' does not exist on type 'typeof BigCalendar'.`
And
`Property 'localizer' is missing in type '{ events: any[]; }'.`
Does anyone have any solutions to these problems?

**Comment by KartikShankhavaram** [comment]
You should just use 
```javascript 
BigCalendar.momentLocalizer(moment)
```
instead of 
```javascript
BigCalendar.setLocalizer(BigCalendar.momentLocalizer(moment));
```

**Comment by raptor1989** [comment]
Ok, but but then I just got the error:
`Cannot read property 'momentLocalizer' of undefined `

**Comment by dmitrykrylov** [comment]
@raptor1989 how do you import BigCalendar?

**Comment by PzYon** [comment]
I get the same error using following dependencies:
- `"react-big-calendar": "0.20.2"`
- `"@types/react-big-calendar": "0.20.1"`

 I import BigCalendar as follows:
`import BigCalendar from "react-big-calendar";`

And then use it like this:
`const momentLocalizer = BigCalendar.momentLocalizer(moment);`

Error: 
`Uncaught (in promise) TypeError: Cannot read property 'momentLocalizer' of undefined`

**Comment by seblondono** [comment]
Did anyone actually find a solution to this issue? I just ran into the same problem.

**Comment by moghammed** [comment]
This seems to be a mismatch in versions between the types and the code. You can get it working by importing with: 
`import * as BigCalendar from 'react-big-calendar'`

and then just use it like normally
`BigCalendar.setLocalizer(BigCalendar.momentLocalizer(moment));`

But typescript will complain about everything and the only solution I can currently provide for that is removing react-big-calendar from your @types.

**Comment by Hiroki111** [comment]
@moghammed 

    import * as BigCalendar from 'react-big-calendar'
   
    BigCalendar.setLocalizer(BigCalendar.momentLocalizer(moment));



That approach resulted in "`Could not find a declaration file for module 'react-big-calendar'.`" :(

**Comment by Hiroki111** [comment]
I see the `wontfix` lable, so will this bug not be fixed?

**Comment by TrySound** [comment]
@Hiroki111 
1. There is not setLocalizer anymore. You should pass localizer to Calendar prop
2. It's typescript issue. This project does not provide types.

**Comment by Hiroki111** [comment]
@TrySound 

Thank you for your comment, but...

"It's typescript issue. This project does not provide types."

I'm not sure what you exactly meant, because I can see the types of `react-big-calendar` provided in its  `index.ds.ts`.

![Screenshot from 2019-06-22 12-27-00](https://user-images.githubusercontent.com/9676341/59962739-81f33000-94e9-11e9-9a62-87514941d7f5.png)

Also, as the OP reported, calling `momentLocalizer` still results in the error even though it's compiled.

i.e. "Cannot read property 'momentLocalizer' of undefined"

This function ("momentLocalizer") exists as per the attached image above, so I don't see how it happens

**Comment by TrySound** [comment]
@Hiroki111 This project does not maintain external typings. `@types/react-big-calendar` is not official part of this project.
https://github.com/Hiroki111/bigcalendar-test/blob/master/package.json#L9

This project does not distribute any index.d.ts
https://unpkg.com/react-big-calendar@0.22.0/

**Comment by arcticmouse** [comment]
I am getting the same error "TypeError: Cannot read property 'momentLocalizer' of undefined" while not using TypeScript, if anyone has insights. 

Using the create-react-app, I have:
`
import React, {Component} from 'react'
import BigCalendar from 'react-big-calendar'
import moment from 'moment'
import 'react-big-calendar/lib/css/react-big-calendar.css'
import axios from 'axios'
import logo from './logo.svg'
import './App.css'

BigCalendar.momentLocalizer(moment)
`

and dependencies as:
`
  "dependencies": {
    "axios": "^0.19.0",
    "moment": "^2.24.0",
    "react": "^16.8.6",
    "react-big-calendar": "^0.22.0",
    "react-dom": "^16.8.6",
    "react-scripts": "3.0.1"
  },
`

**Comment by raoufswe** [comment]
changing my import from 

`import BigCalendar from "react-big-calendar";
`
To 

`import { Calendar, momentLocalizer } from "react-big-calendar";
`
has fixed the problem for me.
