### ISSUE TITLE
Add click handler to a month view cell or ability to override render of individual cells

### ISSUE THREAD

**Issue by JesusTSeger** [intljusticemission/react-big-calendar#1038]
#### Do you want to request a _feature_ or report a _bug_?
Feature
#### What's the current behavior?
Currently the only clickable items in a month view cell are the date and the individual events.  There is no way to add a click handler to individuals cells in the month view grid. I would like to add click handler to the cell itself or have a way to pass in a `RenderMonthCell` Component which receives the date and activities for a given cell as props.  If you have a good idea on how to implement, I would be happy to dig in and create a PR.

**Comment by PiotrKujawa** [comment]
I agree, this calendar should handle something like onSelectDay or onSelectCell. Or selectable prop should accept value of "single" which wouldn't allow to select more than one slot and then onSelectSlot would be enough.

**Comment by JesusTSeger** [comment]
@PiotrKujawa Thank you! I will give that a try.  Did you have any issues styling the cell to make sure it doesn't throw off the sizing/positioning of the calendar as a whole?

**Comment by PiotrKujawa** [comment]
@JesusTSeger No problems at all. In my example <Cell> is an emotion (react-emotion) but by destructuring {...props.children.props} I'm passing default class names and any props of original cell. Then in <Cell> I can overwrite some styles to make custom appearance - any hover, active, pending states etc.

Here's an example how it looks .
https://www.screencast.com/t/izvgeFjY39O

**Comment by PatrissolJuns** [comment]
> I agree, this calendar should handle something like onSelectDay or onSelectCell. Or selectable prop should accept value of "single" which wouldn't allow to select more than one slot and then onSelectSlot would be enough.
> 
> edit:
> 
> @JesusTSeger I just found something which may be useful for you components={{ dateCellWrapper: this.renderCell }}
> 
> renderCell is my custom function to return a react component which contains onClick listener
> 
> ```
> renderCell = props => (
>         <Cell
>             {...props.children.props}
>             onClick={() => {
>                 this.handleSelect(props.value);
>             }}
>         >
>             {props.children}
>         </Cell>
>     );
> ```

Very good idea. I combined it with a style on DateCellWrapper to completely control all events on cells with:
````
  flex: 1 1;
  height: 100%;
  width: 100%;
  border: 1px solid #EFF1F2;
  background: transparent;
  z-index: 999;
  cursor: pointer;
````
