### ISSUE TITLE
IE11 support issue

### ISSUE THREAD

**Issue by snehalkale41995** [intljusticemission/react-big-calendar#1039]
I am using react-big-calendar version 0.19 . IE 11 does not support this version. I am getting this error : 
Array length must be a finite positive integer(Timeslots.js). any one facing  the same issue ? I tried every possible solution related to this issue... please help

Please refer the following code 

import React from "react";
import BigCalendar from "react-big-calendar";
import moment from "moment";
import "react-big-calendar/lib/css/react-big-calendar.css";
BigCalendar.setLocalizer(BigCalendar.momentLocalizer(moment));

const Calendar = props => {
  return (
    <div style={{ height: "100vh" }}>
      <BigCalendar
        events={props.events}
        defaultView="week"
        selectable="ignoreEvents"
        onSelectEvent={props.selectSession}
        onSelectSlot={props.onSelectSlot}
        defaultDate={new Date()}
        min={new Date("2018, 1, 1, 08:00")}
        max={new Date("2018, 1, 1, 20:00")}
        eventPropGetter={props.eventStyleGetter}
        dayPropGetter={props.eventDaysStyleGetter}
        step={30}
        timeslots={2}
        date={props.eventDate}
        onNavigate={props.navigateEventDate}
      />
    </div>
  );
};

export default Calendar;

**Comment by dmitrykrylov** [comment]
@snehalkale41995 
- does it work in other browsers?
- could you create a minimal, complete, and verifiable example on CodeSandBox?
