### ISSUE TITLE
When I imort styles of: react-big-calendar/lib/css/react-big-calendar.css, it can not work?

### ISSUE THREAD

**Issue by Shinepans** [intljusticemission/react-big-calendar#104]
I import styles to my canlendar component, but it can not work, Can you tell me how can I solve it?

the codes like:
```
import React from 'react';
import MuiThemeProvider from 'material-ui/styles/MuiThemeProvider';
import getMuiTheme from 'material-ui/styles/getMuiTheme';
import BigCalendar from 'react-big-calendar';
import events from './events';
const muiTheme = getMuiTheme({});  
import moment from 'moment';
BigCalendar.momentLocalizer(moment);
```

I am using material-ui for my website, I need to use calendar for my website, can you help me ?

**Comment by Shinepans** [comment]
Hellow, can you tell me how to import css style for component? : ) 
My component can display, but it didn't load styles

**Comment by Shinepans** [comment]
I have solved, By import it at head, but this is another proplem:
month can not display, week dan day can display

**Comment by Shinepans** [comment]
all solved, thank you! I used materialcss flex, and the big-calendar flex has conlict with materialcss flex. I changed the styles, it done! thank you.

**Comment by jquense** [comment]
glad you got it working :)

**Comment by nene96** [comment]
@Shinepans I have the same problem, can you tell me how to fix it?

**Comment by Shinepans** [comment]
@nene96 Hellow  : ) , what problem did you meet?

**Comment by nwabdou85** [comment]
@Shinepans the same issue here, how did you do to import it in the head ?

**Comment by nwabdou85** [comment]
@Shinepans  my problem , it does  not show anything in month and agenda, but olny grid on week and day, thank's for help.

**Comment by joselegitan** [comment]
@Shinepans Hello ! 
I have the same issue using material and big calendar.
How did you manage the styles to get the big calendar css ?

**Comment by nene96** [comment]
I worked with this calendar last year so now I cannot remember anything about, sorry...
The project is in the hands of the company where I worked so I cannot check anything.

Sent from my iPhone

On 10 Aug 2017, at 12:30, joselegitan <notifications@github.com<mailto:notifications@github.com>> wrote:


@Shinepans<https://github.com/shinepans> Hello !
I have the same issue using material and big calendar.
How did you manage the styles to get the big calendar css ?

**Comment by StasToken** [comment]
The question is not closed, I have the same problem and I can not help it.
