### ISSUE TITLE
BigCalendar is not re-rendering on resource list update

### ISSUE THREAD

**Issue by swarnimsuman** [intljusticemission/react-big-calendar#1040]
#### Do you want to request a _feature_ or report a _bug_?
Bug
#### What's the current behavior?
I'm able to render the calendar for first time and after that if there is any resource state update, it doesn't re-render the page to show new list of resources.
I'm not sure whether it's expected behavior or there is some error in my code.

My Code:
render() {
        let eventList = [];
        if (this.props.eventList && this.props.eventList instanceof Array) {
            eventList = this.props.eventList
        }

        let viewableResourceList = [];
        let completeResourceList = this.props.resourceList;
        if (completeResourceList && completeResourceList instanceof Array) {
            let j = 0;
            completeResourceList.map((resource, i) => {
                if (resource.active) {
                    viewableResourceList[j++] = resource;
                }
            }
            );
        }
        console.log(2, "EventList : ", eventList, viewableResourceList)
        let output = null;
        if (viewableResourceList.length > 0) {
            let currentDateTime = new Date();
            output = <div>
                <p>{viewableResourceList.length}</p>
                <BigCalendar
                    scrollToTime={currentDateTime}
                    defaultDate={currentDateTime}
                    localizer={localizer}
                    defaultView={BigCalendar.Views.DAY}
                    events={eventList}
                    components={{
                        event: CustomEvent,
                        toolbar: CustomCalendarToolbar
                    }}
                    views={['day']}
                    resources={viewableResourceList}
                    resourceIdAccessor="resourceId"
                    resourceTitleAccessor="resourceTitle"
                    startAccessor="start"
                    endAccessor="end"
                    onSelectEvent={(event) => console.log("it is working", event)}

                />
            </div>
        }
        else {
            output = <div></div>
        }

        return (
            <div>
                {output}
            </div>
        );
}

![login](https://user-images.githubusercontent.com/36529263/46714970-9f45de00-cc7b-11e8-86b5-12288c801fcd.png)
![filter_update](https://user-images.githubusercontent.com/36529263/46714969-9f45de00-cc7b-11e8-96db-ff6557e6ca18.png)

#### What's the expected behavior?
It should update the resource list to display the latest list of resources.

**Comment by aaronnuu** [comment]
Not a great solution but what I have done is just make they key of the calendar some value that only changes whenever the resource changes. This causes a full tear-down and remounting of the whole component so not the best but it does "work"

**Comment by aaronnuu** [comment]
The computed resources needs to be in state, since changing the resources array will _almost_ always lead to something new being rendered.

The fix should be as simple as storing resources in state and updating that state in `componentDidUpdate`.

**Comment by dmitrykrylov** [comment]
@aaronnuu no, computed resources shouldn't be in state, please, read [this](https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#anti-pattern-erasing-state-when-props-change)

I added a pull request, fixing this issue moving this computation to a separate class method and adding some `memoize` stuff
