### ISSUE TITLE
want to disable the next/back button

### ISSUE THREAD

**Issue by cis-ankity** [intljusticemission/react-big-calendar#1043]
#### Do you want to request a _feature_ or report a _bug_?
request a feature
#### What's the current behavior?
I want to disable the next / back button when we click on it, as I'm calling request on button click to get the events and sometimes it takes time to respond and for that duration, I want to disable that clicked button.
Could you please tell me the way to achieve this.

**Comment by dmitrykrylov** [comment]
@cis-ankity as far as I know, you can implement a custom toolbar:
http://intljusticemission.github.io/react-big-calendar/examples/index.html#prop-components
