### ISSUE TITLE
Redundant calendar slots for day when DST ends

### ISSUE THREAD

**Issue by anna-kartynnik** [intljusticemission/react-big-calendar#1044]
Hi guys, first of all I wanted to thank you for your hard work with this amazing calendar.

#### Do you want to request a _feature_ or report a _bug_?
report a bug

#### What's the current behavior?

I tried the [demo page](http://intljusticemission.github.io/react-big-calendar/examples/index.html#intro) and you can find a screenshot below how I see the calendar there:

![screen shot 2018-10-10 at 18 15 42](https://user-images.githubusercontent.com/15210801/46775588-beb12b00-ccbc-11e8-95c0-df0e498ee4f1.png)

My current local timezone is **America/Los_Angeles (UTC-7:00)**. The problem is that I can see additional two hours in the calendar, so I have two `12 AM` and `1 AM` slots at the top and at the bottom. Also slot lines for Sunday are not aligned with other days. Note that this problem is reproducible only for week and day view and only for the week (or day) when Daylight Saving Time ends. Here DST ends on the 4th of November, so to reproduce the bug you need to navigate to the view with that date.

#### What's the expected behavior?

Calendar should be rendered with 24 hours max within a day.

#### Possible solution

I think the problem is in [this line of code](https://github.com/intljusticemission/react-big-calendar/blob/master/src/utils/TimeSlots.js#L4). I think instead of

    Math.abs(start.getTimezoneOffset() - end.getTimezoneOffset())

we should have

    start.getTimezoneOffset() - end.getTimezoneOffset()

I don't think we need to get absolute value here because as far as I understand [here](https://github.com/intljusticemission/react-big-calendar/blob/master/src/utils/TimeSlots.js#L15) we use it for calculating the number of slots and we need to adjust difference accordingly: add 1 hour when DST starts and subtract 1 hour when DST ends.

What do you think? I'll be happy to create a PR if you agree with the solution.

**Comment by jquense** [comment]
I'm never sure what the right answer is with DST but we're happy to take a PR! As long as it seems to work for both the start and end of day I'm happy to merge it
