### ISSUE TITLE
When ```showMultiDayTimes: true``` events ending next day are showing as all-day events

### ISSUE THREAD

**Issue by tibor-kulcar** [intljusticemission/react-big-calendar#1045]
![image](https://user-images.githubusercontent.com/5356434/33702064-28269fda-db22-11e7-9e8d-b02e4a66ff33.png)

Which is not what I want.

I just want what fullCalendar.js does:

![image](https://user-images.githubusercontent.com/5356434/33702292-32641b20-db23-11e7-8bdc-74be522cf66a.png)
![image](https://user-images.githubusercontent.com/5356434/33702323-48ac0f46-db23-11e7-884d-9cb8e4296077.png)

I don't think there is anything currently like that, am I wrong?

_Originally posted by @decoursin in https://github.com/intljusticemission/react-big-calendar/issues/363#issuecomment-349879731_

**Comment by Georift** [comment]
I just tested this in 0.19.0 and it seems to be working. Can you confirm this is still an issue?

**Comment by tibor-kulcar** [comment]
If 0.20.1 is the version installed on demo page than yes, it is still an issue 
<img width="482" alt="screen shot 2018-10-22 at 09 29 16" src="https://user-images.githubusercontent.com/3975660/47281863-419b8500-d5dd-11e8-829c-dda2a10d1597.png">

**Comment by Georift** [comment]
In that example photo I believe the 7:30pm - 2am is displaying correctly. Can you describe how you would expect it to be displayed?

**Comment by Georift** [comment]
Oh ok, so you are saying you would expect to see the text '7:30pm - 2:00am' in both days event blocks, instead of '7:30pm -' and '- 2:00am'?

**Comment by tibor-kulcar** [comment]
Exactly :) I've checked it now on google calendar an they have also like this.

**Comment by Georift** [comment]
Looking at the code, this functionality seems very much intentional. It doesn't look like there is any kind of label accessor that would allow you to override it. Perhaps @jquense would have a better idea.

**Comment by Kurshith** [comment]
Any update on this issue?

**Comment by Kurshith** [comment]
Any update on this issue?

**Comment by Satherial** [comment]
I'd like to have this too, thanks

**Comment by statusunknown418** [comment]
this seems to work now in `1.11.x`
