### ISSUE TITLE
new gutter component for month view showing the week of year

### ISSUE THREAD

**Issue by eschreiner** [intljusticemission/react-big-calendar#1049]
#### Do you want to request a _feature_ or report a _bug_?

new feature

#### What's the current behavior?

no gutter in month view

#### What's the desired behavior?

I would like to display the 'week of year' at the left border of the month view. What is the best way to go about this?

- header 'KW' = calendar week in german
- content e.g. '42' for today's row

**Comment by dmitrykrylov** [comment]
@eschreiner you can specify custom value for `dayRangeHeaderFormat`
