### ISSUE TITLE
calendar doesn't display on webpage

### ISSUE THREAD

**Issue by brw31415** [intljusticemission/react-big-calendar#105]
calendar doesn't display on webpage
i everything else works as i've tested other reusable components in this instance
Uncaught TypeError: Cannot read property 'filter' of undefined

this is my component file (Counter.js):

 React, { Component } from 'react';
 // import BigCalendar from './BigCalendar'  ;
 import BigCalendar from 'react-big-calendar';
 
 
 import moment from 'moment';

 BigCalendar.momentLocalizer(moment);

export class Counter extends React.Component {
  constructor(props) {
    super(props);
    this.state = {count: props.initialCount};
  }
  tick() {
    this.setState({count: this.state.count + 1});
  }
  
  
  render() {
    
    
    return (
      <div>
     <BigCalendar
        
        defaultDate={new Date(2015, 3, 1)}
      />
      </div>
    );
  }
}

export default Counter;

------------------------this is my index.js file--------------------------------

import React from 'react';
import ReactDOM from 'react-dom';
import Counter from './Counter';

ReactDOM.render(
  React.createElement(Counter),
  document.getElementById('mount')
);

---------------webpack.config.js-------------

 path = require('path');
var projectRoot = __dirname;

var config = {
  // Must be an absolute path or watching feature will fail
  context: path.join(projectRoot, 'js'),
  entry: './index.js',
  output: {
    path: path.join(projectRoot, 'html'),
    filename: 'bundle.js',
  },
  module: {
    loaders: [
      { test: /\.js$/, exclude: /node_modules/, loader: 'babel-loader'},
    ],
  },
  resolveLoader: {
    root: [
      path.join(projectRoot, 'node_modules'),
    ],
  },
  resolve: {
    root: [
      path.join(projectRoot, 'node_modules'),
    ],
  },
};
module.exports = config;

**Comment by brw31415** [comment]
its actually import React, { Component } from 'react'; at top of Component.js

**Comment by tpmh31292** [comment]
You need to give the BigCalendar `events` prop even if there are no events
For example:
```
<BigCalendar
    events={[]}
    // other props...
/>
```

**Comment by brw31415** [comment]
ok thks

**Comment by dvkndn** [comment]
Hi @jquense , do you think we should mark events as a required prop? I've just tried this today, and if I don't provide events nothing appear, even other part of my app, and no error is logged in console too.

**Comment by mehranabi** [comment]
Hi, I have a similar problem, `events` not marked as _required_ in docs, But when you don't pass it, You will get an error. So I think it should be marked as _required_

**Comment by poongkabilan229** [comment]
> You need to give the BigCalendar `events` prop even if there are no events
> For example:
> 
> ```
> <BigCalendar
>     events={[]}
>     // other props...
> />
> ```

Great! Solved the issue.Thanks
