### ISSUE TITLE
current time highlighted is reset onNavigate 

### ISSUE THREAD

**Issue by CodeXtinction** [intljusticemission/react-big-calendar#1050]
#### Do you want to request a _feature_ or report a _bug_?
Bug
#### What's the current behavior?
current time highlighted is reset on navigation

got to the app demo 
- http://intljusticemission.github.io/react-big-calendar/examples/index.html
- go today
- change to week view
- press next
- press back

Correct highlighted
![screenshot-20181016174546-1366x832](https://user-images.githubusercontent.com/24515096/47046562-d3ce0400-d16b-11e8-89d0-5d1e0cd7b1fb.png)

wrong highlighted
![screenshot-20181016174604-1385x820](https://user-images.githubusercontent.com/24515096/47046599-e8aa9780-d16b-11e8-9b4d-cf9f954dbf23.png)

#### What's the expected behavior?
time highlighted should not change

**Comment by willisplummer** [comment]
I'm running into this too. Is there a workaround?

**Comment by shvgongh** [comment]
add this line to DayColumn.js componentWillReceiveProps function:
this.props.isNow && this.positionTimeIndicator()

**Comment by vivpan24** [comment]
Hi Community,

On clicking the Month, Week, Day, Agenda buttons the rbc-active class is applied to the clicked buttons and the button remains hightlighted. But on clicking Today, Back, Next the button gets hightlighted but when we click outside the button the style gets lost. How can we achieve the same style behaviour for TODAY,NEXT,BACK as it is going for MONTH,WEEK,DAY,AGENDA.

![Screenshot ](https://github.com/jquense/react-big-calendar/assets/43695304/ed6931fe-8f0e-4513-bb03-8edc3153567d)
https://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/props--drilldown-view
