### ISSUE TITLE
Support for multi-day event rectangle flowing to next row during drag-and-drop???

### ISSUE THREAD

**Issue by callagga** [intljusticemission/react-big-calendar#1052]
Can I ask a couple of questions re what is supported please:

Q1 - I want a month view calendar that supports the following visually when a multiday event is undergoing drag-and-drop.  When you drag the event (e.g. say a 4 day event) to the right, then rather than the event rectangle extending to the right of the last day in week, it start appearing on the next line (next week) row.   Does the library currently support this?

Q2 - If not, but I wanted to pursue, any feedback/thoughts/advice on whether what I am after would be better trying to implement in canvas as opposed to the DOM? 

Notes: So what I’m after would mean tracking position of the drag, computations to realise it crossed over to the next week/line, and then create another rectangle. Plus as you drag backwards/forwards during this process the width of both rectangles (current week & next week) would be changing. Hope this makes sense.

[can’t quite see how to add the “help-wanted” label]

**Comment by jquense** [comment]
It should already work like this, you can try it out on the docs site

**Comment by callagga** [comment]
> It should already work like this, you can try it out on the docs site
@jquense  - when I try on the http://intljusticemission.github.io/react-big-calendar/examples/index.html#dnd site it doesn't do this...

In indication re what I was after below if this helps clarify:

![Image](https://i.postimg.cc/MTNxwQBC/drag.png)

**Comment by decimoseptimo** [comment]
@jquense can you provide guidance to implement this
