### ISSUE TITLE
The current time indicator is initially misplaced

### ISSUE THREAD

**Issue by jdaberkow** [intljusticemission/react-big-calendar#1055]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

After switching the weekly calendar towards the current week, the current time indicator is initially misplaced. This can be noticed on the default examples page:
http://intljusticemission.github.io/react-big-calendar/examples/index.html

![tempsnip](https://user-images.githubusercontent.com/13017916/47224419-c3ac6380-d3bb-11e8-89ad-688a8314d40c.png)

#### What's the expected behavior?

It is expected that the current time indicator is always on the current position from that moment on, when user switches to a view that displays the current day.

I proposed a pull request to address this issue in #1054

**Comment by dmitrykrylov** [comment]
@jdaberkow I didn't check your pr. However, on the screenshot there is also a misplaced event. Have it been fixed? If yes, we could probably close #999 and #1051

**Comment by dmitrykrylov** [comment]
I made another pr that also fixes position of events
