### ISSUE TITLE
rbc-time-content doesn't display. Wrong label and allDay event doesn't show up in "day" view

### ISSUE THREAD

**Issue by tpmh31292** [intljusticemission/react-big-calendar#106]
Hi,
I am new to this component so maybe there are something that needs to be defined that I missed?

As in the picture, the rbc-time-content part only displays when I disable the "flex" style. Otherwise, the calendar only shows the rbc-time-header, which is the "all day" row.
The second thing is the label, shouldn't it be "Wednesday Jun 01"?
![temp](https://cloud.githubusercontent.com/assets/9924519/15697280/0c36e026-27fc-11e6-88b7-e9012ae7d915.PNG)

And there is an all day event on this date but it doesn't show up. However, it does when we changed to "week" view as in the picture below.
![temp1](https://cloud.githubusercontent.com/assets/9924519/15697348/95a642f2-27fc-11e6-95c6-e6204e97e44b.PNG)

Any ideas?

Thanks

**Comment by gazab** [comment]
Are you using Chrome? I've also had problems in Chrome with the CSS  rule "flex: 1 1 0". Somehow the CSS on the example pages instead uses "flex: 1 1 0%" which works but the compiled version doesn't.

**Comment by tpmh31292** [comment]
@gazab Yes, I use Chrome. But I just tried on Firefox and it's also "Flex: 1 1 0px" as well.
It works if I change "px" to "%".
I guess the compiled version was mistakenly edited?

**Comment by gazab** [comment]
@tpmh31292 not sure what's wrong. The source (https://github.com/intljusticemission/react-big-calendar/blob/master/src/less/time-grid.less#L77) uses percentage. Maybe it's some webpack loader that optimizes away the percentage sign?

Maybe @jquense knows?

**Comment by tpmh31292** [comment]
@gazab I use webpack css-loader
