### ISSUE TITLE
Add option to make events not overlapped when they are in the same timeslot?

### ISSUE THREAD

**Issue by MinhNguyen41092** [intljusticemission/react-big-calendar#1060]
Hi everyone.

#### Do you want to request a _feature_ or report a _bug_?
A feature
#### What's the current behavior?
Currently when events are in the same timeslot they are overlapped each other.

So my client wants the layout to look somewhat like this.
![events](https://user-images.githubusercontent.com/23077631/47406201-64fe3580-d77f-11e8-9abb-1f901d0df954.png)

As I searched there is no option to change layout to make events not overlapped like in FullCalendar. Do you guys have any plan to add this feature in the future? I think it looks a lot better like that.

**Comment by jquense** [comment]
Hi there, we've no immediate plans to add it, the current layout algo works well for a wide variety of use cases and situations so it makes sense as a general default. We've definitely talked about making this section pluggable but there isn't a real need for it by maintainers so if you'd like to see it the best way would be to send a PR adding it :)

**Comment by MinhNguyen41092** [comment]
Thank for your answer jquense. I'll search for other options then :)

**Comment by WhoseSomebody** [comment]
Hello @MinhNguyen41092!
Have you found any ways to do what you need? Or at least maybe you made a research... I have the very similar situation.. Could you please share your experience?

**Comment by MinhNguyen41092** [comment]
@WhoseSomebody My team decided to keep using the default layout. We couldn't find any solution :)

**Comment by sgraham3311** [comment]
@jquense Any chance this PR https://github.com/intljusticemission/react-big-calendar/pull/1279 can be approved to fix this issue?
