### ISSUE TITLE
Move @babel/cli into devDependencies

### ISSUE THREAD

**Issue by drewtonynguyen** [intljusticemission/react-big-calendar#1061]
Can @babel/cli be moved into the devDependencies section of the package.json instead of dependencies? I am seeing `warning "react-big-calendar > @babel/cli@7.1.2" has unmet peer dependency "@babel/core@^7.0.0-0".` when running yarn in my app when upgrading from release 0.19.2 to 0.20.1.

Thanks!

**Comment by jquense** [comment]
Sure, can you to send a PR?
