### ISSUE TITLE
dayWrapper is broken in the new RBC

### ISSUE THREAD

**Issue by ooade** [intljusticemission/react-big-calendar#1064]
#### Do you want to request a _feature_ or report a _bug_?
Bug
#### What's the current behavior?
Nothing gets returned in dayWrapper.

**Comment by ooade** [comment]
Here is it: https://codesandbox.io/s/pk37nmyp0x

**Comment by kilroy05** [comment]
Seems this still isn't fixed?
Just spent 1 hour thinking I am using this wrong...
