### ISSUE TITLE
Remove show more and show all event on month view

### ISSUE THREAD

**Issue by rebirthtobi** [intljusticemission/react-big-calendar#1067]
#### Do you want to request a _feature_ or report a _bug_?
Feature

#### What's the current behavior?
There is a show more based on the height on the cell if there is space, it will automatically show all events and if there is not space, it will show `4 more...`

#### What's the expected behavior?
There should be a feature such that the height of the cell row will adjust based on the highest number of event in any cell or wrap around the event.

This means that there won't be a uniform row on the month view but each row height will be based on the highest number of event in any cell in the row

**Comment by jquense** [comment]
hey there, this has been discussed a few times and a few paths forward to achieving it have been noted. I'm gonna close this since it's a duplicate, thanks!

**Comment by rebirthtobi** [comment]
so is there a way to always show all event event without a fluid container? like disabling the `show more` feature
