### ISSUE TITLE
DnD: draggableAccessor is ignored

### ISSUE THREAD

**Issue by xtursky** [intljusticemission/react-big-calendar#1068]
#### Do you want to request a _feature_ or report a _bug_?

bug

#### What's the current behavior?

`draggableAccesor` which is used to resolve if event is draggable or not is ignored. Referencing wasn't fixed after recent wrapping into `draggable` object.

```
const { draggableAccessor, resizableAccessor, draggable } = this.context
```

https://github.com/intljusticemission/react-big-calendar/blob/master/src/addons/dragAndDrop/EventWrapper.js#L80

#### What's the expected behavior?

I know PR, but I don't have much time now.
```
const { draggable } = this.context;
const { draggableAccessor, resizableAccessor } = draggable;
```

**Comment by arecvlohe** [comment]
Fixed in #1070

**Comment by artooras** [comment]
Would you be able to provide an example on how to disable draggability on some events when this feature is enabled on the entire calendar? I cannot understand how to do that looking at documentation and src. Thanks!

**Comment by artooras** [comment]
Thank you!
