### ISSUE TITLE
Multiple day event creation by dragging and selecting time slots form multiple columns in week view

### ISSUE THREAD

**Issue by codeVerine** [intljusticemission/react-big-calendar#1075]
#### Do you want to request a _feature_ or report a _bug_?
Feature Request
#### What's the current behavior?
In week view, you can only drag and select time slots inside a single day to create an event. It is not possible to create an event spanning multiple days by dragging and selecting time slots.

#### What's the expected behavior?
User should be able to create events that span over multiple days by dragging and selecting time slots from multiple columns in week view. Please let me know if this feature is already supported by the component and I missed to notice it.

**Comment by paulhan221** [comment]
bump

**Comment by zsh1313** [comment]
This feature is really a 'MUST HAVE'

**Comment by TuxxyDOS** [comment]
I request that as well

**Comment by MateuszBochen** [comment]
+1

**Comment by roymas100** [comment]
+1

**Comment by sambbaahh** [comment]
+1

**Comment by RRamirez1414** [comment]
+1
