### ISSUE TITLE
event is in wrong cell if min-max date specified

### ISSUE THREAD

**Issue by akoidan** [intljusticemission/react-big-calendar#1076]
#### Do you want to request a _feature_ or report a _bug_?
BUG
#### What's the current behavior?

If I specify min/max date, event is located in wrong cell, (usually 1-3 hours more, than it should be)

```
<BigCalendar
        localizer={localizer}
        min={new Date(0,0,0,8,0,0)}
        max={new Date(0,0,0,18,0,0)}
    events={[{title: 'sdf', start: new Date(), end: new Date()}]}s/>
```
https://codesandbox.io/s/7z95lom9qq
![image](https://user-images.githubusercontent.com/1336703/47783902-a86f1b80-dd0c-11e8-9de2-7c1be1eb834b.png)

#### What's the expected behavior?

Event is located in right cell, like it does w/o min/max date

**Comment by dmitrykrylov** [comment]
Duplicated issue #999
