### ISSUE TITLE
How to integrate custom tooltip

### ISSUE THREAD

**Issue by adityay-perpetualny** [intljusticemission/react-big-calendar#1077]

**Comment by dmitrykrylov** [comment]
@adityay-perpetualny you can do it with customizing your Event component

https://github.com/intljusticemission/react-big-calendar/blob/master/examples/demos/rendering.js#L51

**Comment by adityay-perpetualny** [comment]
Thanks for the help

**Comment by adityay-perpetualny** [comment]
When I am using the above code , I am not ablt to get the "+2 more " link , do you have any suggestions for  it.

Thanks

**Comment by adityay-perpetualny** [comment]
I analyzed and found that the issue is the event title in my case is of 2 lines for eg,
![issue](https://user-images.githubusercontent.com/44191071/48940398-6ddc5580-ef3d-11e8-927e-5d62acd112a9.png)

Because of this I guess some calculation is going wrong.

If I add title of only one line its working fine

Thanks
