### ISSUE TITLE
Timezone Issue: DST cause items on calendar to not show in correct time slot

### ISSUE THREAD

**Issue by quyphan** [intljusticemission/react-big-calendar#1083]
#### Do you want to request a _feature_ or report a _bug_?
Bug
#### What's the current behavior?
If you are going to create an event via the `onSelectSlot` functionality on Sunday November 4th, 2018 you are going to see a **2 hour offset error**.  The reason for this is because on November 4th the timezone will change from PDT to PST (daylight savings).

#### What's the expected behavior?
What is expected is that BigCalendar should automatically detect that on November 4th it should know to adjust from PDT to PST so it does not have a **2 hour offset**.

Image:

![screen shot 2018-11-02 at 10 17 02 am](https://user-images.githubusercontent.com/24657232/47930652-c44bfc00-de89-11e8-92d3-c0905fcb4383.png)

As you can see from the example as I am creating an event right now on Sunday November 4th it will have a 2 hour offset.  The calendar is showing my 7AM - 9AM event on the 9AM - 11AM grid.

**Comment by quyphan** [comment]
Seems like this is related to #1028

**Comment by anna-kartynnik** [comment]
@quyphan have you seen #1044 and corresponding PR #1046? I tried to run examples with that fix and event time is the same as slot time on the left.
![screen shot 2018-11-02 at 11 45 18](https://user-images.githubusercontent.com/15210801/47934591-e5661a00-de94-11e8-8b95-7f9d247390f1.png)

**Comment by quyphan** [comment]
@anna-kartynnik Thanks for fixing this! I showed the before and after in your PR #1046
