### ISSUE TITLE
Docs for all custom components

### ISSUE THREAD

**Issue by Auchindoun** [intljusticemission/react-big-calendar#1089]
#### Do you want to request a _feature_ or report a _bug_?
Docs missing info

#### What's the current behavior?
Looking at the docs, it only shows 3 options for custom components that can be passed through to the `components` prop:
- event
- toolbar
- agenda: event

#### What's the expected behavior?
The docs should show all possible properties for components that can be overridden. For instance, digging through the source code I was able to find out that I can pass through `eventWrapper` as a component, though I am unaware of what other options I have available to me.

It looks as if `eventCell` should be a valid option since it is one of the main components that creates the button wrapping the event, but nothing happens when setting it.

**Comment by arecvlohe** [comment]
Merged in #1092
