### ISSUE TITLE
The "current time" green line shows time incorrectly after clicking Back and Next buttons

### ISSUE THREAD

**Issue by ihar-lapitski** [intljusticemission/react-big-calendar#1091]
Hi guys! 
I have found a bug.
This is related to the "current time" green line.

You can reproduce it in Demo app here:
http://intljusticemission.github.io/react-big-calendar/examples/index.html

Green line shows time correctly:
![screenshot from 2018-11-06 12-48-20](https://user-images.githubusercontent.com/21954103/48056526-08f5d100-e1c3-11e8-8c61-75da3b917da2.png)

But if you click Back button and after that click Next button then green line shows current time incorrectly:
![screenshot from 2018-11-06 12-48-33](https://user-images.githubusercontent.com/21954103/48056636-3e022380-e1c3-11e8-802c-64dbd1ebf03f.png)

**Comment by ihar-lapitski** [comment]
Or may be can somebody suggest a workaround?

**Comment by MBach** [comment]
See the following issue https://github.com/intljusticemission/react-big-calendar/issues/1081 and the PR https://github.com/intljusticemission/react-big-calendar/pull/1082
