### ISSUE TITLE
Make selectable true for custom time only

### ISSUE THREAD

**Issue by bansundar** [intljusticemission/react-big-calendar#1093]
#### Do you want to request a _feature_ or report a _bug_?
I want to request a new feature. Is there a feature to make selectable true only for custom give time ranges or not? As well change the background color of that time range.
Thanks

**Comment by jquense** [comment]
you can control what times are selectable by returning true/false from `onSelecting`. For background coloring You may be able to provide a TimeSlotWrapper component, but the feature generally isn't there, we've got a few issues asking for it in the backlog
