### ISSUE TITLE
How to Make only custom time selectable by using onSelecting?

### ISSUE THREAD

**Issue by bansundar** [intljusticemission/react-big-calendar#1094]
#### Do you want to request a _feature_ or report a _bug_?
I am not sure if its a new feature or it already exist. I just wanted to know that How can we make calendar selectable for custom time only.

For example I have time range of
//this date is today from 10am to 12pm
  {
    id: 0,
    title: 'event0',
   start: new Date(2018, 3, 12, 12, 0, 0, 0),
    end: new Date(2018, 3, 12, 13, 0, 0, 0)
  },
//this date is today from 1pm to 2pm
  {
    id: 1,
    title: 'event1',
   start: new Date(2018, 3, 12, 12, 0, 0, 0),
    end: new Date(2018, 3, 12, 13, 0, 0, 0),
  },
//this date is today from 4pm to 5pm
  {
    id: 2,
    title: 'event2',
   start: new Date(2018, 3, 12, 12, 0, 0, 0),
    end: new Date(2018, 3, 12, 13, 0, 0, 0),
  },

Well this is my code. That I am using for the 

**const SeekerCalendar = props => (

    <div id="seeker-calendar" style={calendarStyle}>
        <Calendar
            popup
            defaultDate={new Date()}
            defaultView="week"
            views={['month', 'week']}
            events={props.allEvents}
            style={{height: 600, width: 700}}
            selectable={true}
            onSelectSlot={props.slotSelected}
            onSelectEvent={props.eventSelected}
            onSelecting={props.onSelecting} // 
        />

    </div>
);**

if selectable is true than whole calendar is dragable to create event by default but how can I make selectable true only for those time range that I had provided and create an event.

Thanks

**Comment by jquense** [comment]
You can return `false` for any time slot you don't want to allow in the onSelecting callback which is passed time slot info.

**Comment by bansundar** [comment]
Hi @jquense thanks for your response. I tried different type of coding . It would be really great can you help with with sample code. thanks
