### ISSUE TITLE
When date and defaultDate props are omitted onRangeChange will not receive correct arguments

### ISSUE THREAD

**Issue by newsiberian** [intljusticemission/react-big-calendar#1095]
#### Do you want to request a _feature_ or report a _bug_?
A bug

#### What's the current behavior?
When Calendar initialized w/o `date` and `defaultDate`, `onRangeChange` handler will receive date arguments w/o values. It will be empty array for `week`, `day` views and `date: IncorrectDate` for rest.

react-big-calendar@0.20.2

#### What's the expected behavior?
I expect to see correct arguments even when I skip these two props, which is unnecessary when I need to have a default date as current day

**Comment by fh-jashmore** [comment]
We could add docs to the onRangeChange property to be sure to add a defaultDate or something like that.

**Comment by antoinerousseau** [comment]
still an issue I guess
