### ISSUE TITLE
DnD: dropping an event outside calendar area leaves cal in odd state

### ISSUE THREAD

**Issue by rickstricker** [intljusticemission/react-big-calendar#1097]
#### Do you want to request a _feature_ or report a _bug_?
bug

#### What's the current behavior?

Using the drag and drop demo, drag an event above the month name and drop it.  Notice that the calendar is left in the dragging state with the event being dragged missing from calendar.  Clicking in the calendar appears to reset the drag and brings the event back to its original location.  

This also happens dragging and dropping to the left or right sides of the calendars.  Try dropping an item into the time gutter on week or day view.  

The month view also has the problem dragging and dropping out of the the bottom.  However, the week and day views appear to handle drags out of the bottom ok.

#### What's the expected behavior?

In cases where the drop is leaving the calendar in the drag state, I would expect that a drop outside of the calendar should simply cancel the drag.

**Comment by bs85** [comment]
Fixed by #1119

**Comment by thinhle-agilityio** [comment]
@bs85  @jquense can you help publish new npm version for this patch? this feature is not published yet
