### ISSUE TITLE
scrollToTime doesn't work on initial load

### ISSUE THREAD

**Issue by mekkah** [intljusticemission/react-big-calendar#1102]
#### Do you want to request a _feature_ or report a _bug_?
bug
#### What's the current behavior?

The scrollToTime feature doesn't work when the calendar loads the first time.
In a week view for instance, the time shows 00:00:00 instead of 09:00:00 that was set. However, if the user navigates to the next week, it works as expected.

The applyScroll method below in the TimeGrid.js class is being called to perform the scroll. 
`applyScroll() {`
    `if (this._scrollRatio) {`
      `const { content } = this.refs`
       `content.scrollTop = content.scrollHeight * this._scrollRatio`
      `// Only do this once`
      `this._scrollRatio = null`
    `}`
  `}`

It works fine when called from the componentDidUpdate method but doesn't work when called from componentDidMount.

 On debugging the method after it was called from componentDidMount, I noticed that content.scrollTop still retains a value of 0 event after being set.

When I set a timeout as seen below, it works for both cases
![image](https://user-images.githubusercontent.com/5188594/48301378-f4784800-e4e4-11e8-8c32-e207eaed23b8.png)

#### What's the expected behavior?
Calendar should scroll to the set time defined with the scrollToTime property

**Comment by janine-zhu** [comment]
Please re-consider on opening this as a feature.
