### ISSUE TITLE
Performance Issue with DnD and onSelectEvent

### ISSUE THREAD

**Issue by dbuchet** [intljusticemission/react-big-calendar#1103]
#### Do you want to request a _feature_ or report a _bug_?
Performance issue

#### What's the current behavior?
Hi there.
I've just updated from 0.19.2 to 0.20.2 and I have a performance issue when using `onSelectEvent` with DnD activated
![prtscr_capture](https://user-images.githubusercontent.com/28299515/48342358-bce9d700-e66f-11e8-8018-b7a63e08af25.jpg)

No problem with 0.19.2 (i'm using the same code) or if set event `draggable` to false.
So I assume there is a leak when detecting `click` event vs `startDrag` /  `endDrag`

I've launched DnD example and added an `onSelectEvent` with a `console.log`, and I have 1.5s delay before the `console.log` is triggered, so I assume it's not from my code :)

Thanks !

**Comment by jquense** [comment]
We may have addressed this partly in a recent PR, can you try and use the current master and see if it still occurs? If so there could definately be some performance low hanging fruit to be picked, we switched from react-dnd which is pretty tuned and optimized (but not a great solution for us) to something more custom so we haven't had a chance to stress test it in lots of different places. More than happy to take PR's on this front as well if you're up for it

**Comment by dbuchet-bandc** [comment]
Hello jquense,
Yes I've tried with current `master` branch, and even if it's a bit faster, I still have 1s~1.5s delay when I select an event.

I'll look if I found something!

**Comment by RusinovAnton** [comment]
I have problems with performance using dnd and onSelectEvent too
Here is results of React Profiler

![image](https://user-images.githubusercontent.com/13165540/48612882-e453e300-e992-11e8-9a47-38d81f4fd357.png)

**Comment by RusinovAnton** [comment]
I forked rbc and tried to build it locally and link via npm but I still run into the issue with multiple copies of React. I've tried to install react and react-dom globally and link them too but still get an error. 

What the best approach to debug library?

**Comment by RusinovAnton** [comment]
Commenting these two lines from `addons/dragAndDrop/EventWrapper.js` makes it work much faster but breaks the drag n drop obviously.

https://github.com/intljusticemission/react-big-calendar/blob/master/src/addons/dragAndDrop/EventWrapper.js#L125-L126

**Comment by RusinovAnton** [comment]
It is a bit better but still there is a visible lag on drag start:  
![image](https://user-images.githubusercontent.com/13165540/48698600-29288580-ebf0-11e8-91ff-7b1af96b0741.png)

**Comment by bs85** [comment]
There are still a bunch of setState calls in there, can you see where they are originating from?

**Comment by amazingmarvin** [comment]
Possibly this is the same issue I was having.  `componentDidUpdate` calls `TimeGrid.measureGutter` which calls `setState` and it repeats forever.  See [this commit](https://github.com/amazingmarvin/react-big-calendar/commit/3196138840f2681b2fadff6340b6fdc3ca569c36) for fix.  After that it felt much snappier.  I suspect some of my custom styling is giving the gutter a different width than `state.gutterWidth`.

**Comment by RusinovAnton** [comment]
> There are still a bunch of setState calls in there, can you see where they are originating from?

Actually, I do not have performance issues with DnD now.   
Maybe that was a cache or something. I don't use `onSelectEvent` tho, just plain on click within event component.
