### ISSUE TITLE
React.createRef() requires React 16.3 but the peerDependency allows for older versions

### ISSUE THREAD

**Issue by akandels** [intljusticemission/react-big-calendar#1107]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

Line 67 of TimeGrid.js currently uses `React.createRef()` which is only supported in React 16.3+. The package.json specifies the peerDependency of React as ` "react": "^15.3.0 || ^16.0.0"` which includes loads of versions that simply cannot run the library.

#### What's the expected behavior?

It appears that file is the only place using the new `createRef` behavior. I would recommend either refactoring that to support a wider array of React versions or upgrading the peerDependency to `^16.3` to more accurately communicate the requirements for new installs. If one of these of preferred over the other, I'm happy to create a PR for it. Let me know. Thanks!

**Comment by iPhatty** [comment]
I also came across this issue, and made a PR with some changes. It may never be approved, but at least you guys can see where I found it was using React v16. This now works on my app which uses React v15.6.2.
#1134
