### ISSUE TITLE
How to make custom eventWrapper component to be in the correct hour location 

### ISSUE THREAD

**Issue by vetmust** [intljusticemission/react-big-calendar#1111]
I have an event with start hour : 7:00 and end hour 10:30
when i set the default event wrapper component
the event is in the right location in the week calendar 

<img width="785" alt="screen shot 2018-11-15 at 9 59 12" src="https://user-images.githubusercontent.com/44277333/48538437-21e63c80-e8bd-11e8-9d46-25aeb8420e25.png">

but when i am changing the eventWrapper to be a custom component the event is all ways showing on 00:00 hour location

<img width="785" alt="screen shot 2018-11-15 at 10 00 00" src="https://user-images.githubusercontent.com/44277333/48538471-3c201a80-e8bd-11e8-9bc1-a2d6f29fdbdc.png">

Calendar Component : 

```javascript 

  <Calendar
                selectable
                defaultDate={new Date()}
                defaultView="week"
                style={{height: "100vh"}}
                localizer={localizer}
                events={events}
                showMultiDayTimes
                onSelectEvent={event => alert(event.title)}
                onSelectSlot={this.handleSelectEvent}
                components={{
                    eventWrapper: AppCalendarEventWrapper,
                    toolbar: AppCalendarToolBar
                }}
            />

```
and my custom eventWrapper component : 

```javascript

class AppCalendarEventWrapper extends Component {

    handleEventClick = ()=>{
        const {event} = this.props;
        this.props.onSelect(event);
        console.log('event clicked',event)
    };
    render() {
        const {event, theme,components} = this.props;
        const backgroundColor = event.status === "done" ? theme.palette.success.light : theme.palette.info.main;
        const startDate = moment(event.start).format('hh:mm');
        const endDate = moment(event.end).format('hh:mm');

        return (
                <div onClick={this.handleEventClick} style={{zIndex:999, marginTop: 2, backgroundColor, borderRadius: 10}}>
                    <div style={{paddingRight: 10,paddingLeft:10}}>
                        <div style={{flex:1,display:'flex',justifyContent:'space-between',alignItems:'center',flexDirection:'row-reverse'}}>
                            <AppText variant='body2' color='default'>
                                <strong>{event.title}</strong>
                            </AppText>
                            <AppText variant='body2' color='default'>
                                {`${startDate}-${endDate}`}
                            </AppText>
                        </div>
                    </div>
                </div>
        )
    }
}
```
i know i need to apply some style or prop to my custom component but i didn't find one

**Comment by jquense** [comment]
You can't use `eventWrapper` like this, the event passed into the wrapper is the thing that's positioned. Wrapper components are for addons to augment the existing event not replace it. IF you must use it please see how the drag and drop plugin makes use of it

**Comment by moefawazz** [comment]
how can i style it ? ineed the event to be styled by certain way

**Comment by MarianCN** [comment]
same question, how to restyle it

**Comment by no-more-coffee** [comment]
This bug is seen in the documentation also. Those 2 red empty borders on top were meant to wrap the 2 events below.
https://jquense.github.io/react-big-calendar/examples/index.html?path=/story/additional-examples--custom-event-wrapper

<img width="929" alt="Image" src="https://github.com/user-attachments/assets/b8613b6d-3487-41ef-b8a1-4dddb6a6e8b1" />

**Comment by no-more-coffee** [comment]
So the bug was just in the documentation. The working solution would be something like:
```typescript
components={{
  eventWrapper: (eventWrapperProps: EventWrapperProps<itemType>) => {
    const {event, children} = eventWrapperProps;
    return cloneElement(children, {
      style: {
        ...children.props.style,
        border: !!event.needHighlight ? "red" : "green",
      },
    });
  },
}}
```
