### ISSUE TITLE
Cannot read property title when passing values for views prop.

### ISSUE THREAD

**Issue by vigneshr23** [intljusticemission/react-big-calendar#1116]
#### Do you want to request a _feature_ or report a _bug_?
Bug
#### What's the current behavior?
Passing an array of required *views* to views prop results in an error as show in screenshot.
![image](https://user-images.githubusercontent.com/10495874/48690890-609a3080-ebf6-11e8-98c0-8d7a2a20d6e7.png)

The code reference is shown below:
![image](https://user-images.githubusercontent.com/10495874/48690933-8cb5b180-ebf6-11e8-9805-d5000928d5d9.png)

#### What's the expected behavior?
Passing an array of required *views* to views prop should render the requested views.

I'm referring to the demo code, but I get the error. Please let me know if there is a different way of using this.

**Comment by jquense** [comment]
the defaultView is `month` which isn't allowed on your calendar, set `defaultView` to 'day'
