### ISSUE TITLE
Initial rendering looks not nice

### ISSUE THREAD

**Issue by newsiberian** [intljusticemission/react-big-calendar#1124]
#### Do you want to request a _feature_ or report a _bug_?
a _bug_
#### What's the current behavior?
Then we enter the calendar page, we can see this (see screenshot) for a few miliseconds. It looks like blinking. When we have a lot of initial data that comes via SSR, we can see it for a second or even longer.

![screenshot_20181123_101431](https://user-images.githubusercontent.com/11130487/48927763-70be5280-ef0b-11e8-8077-1d81f16e4910.png)

#### What's the expected behavior?
Calendar should be rendered in its final state at the first rendering with all sizes, positioned correctly etc...

**Comment by jquense** [comment]
what you are seeing is the css not being loaded by the time the calendar renders, commonly refered to in web dev as a Flash Of Unstyled Content. You should defer rendering your app until all the required styles are loaded
