### ISSUE TITLE
scrollToTime with min does not work

### ISSUE THREAD

**Issue by POANG1** [intljusticemission/react-big-calendar#1128]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?
When using scrollToTime with "min" property, scrollToTime does not work.

My code:

<BigCalendar
//Other properties here -- removed									
scrollToTime={new Date()}
min={moment(284018400000).toDate()}
/>

**Comment by simonstead** [comment]
For me, the scrollToTime works, but it's actually number of hours you want to offset by.
To start at 9am, but can scroll back to 6am:
```min={new Date(1970, 1, 1, 6)}
scrollToTime={new Date(1970, 1, 1, 3)}```

**Comment by soozie** [comment]
this should be reopened as it is not fixed

**Comment by amhunt** [comment]
I believe this only works if a. your `min` and `scrollToDate` are on the same day and b. you let `react-big-calendar` manage the scroll. Since I created my own scroll container higher up in the DOM tree than the `react-big-calendar`, this prop didn't work for me (but I was able to do what I needed at the level of my scrolling container).

**Comment by Malarkey-Jhu** [comment]
same problem here, if the min prop is removed, then scollToTime work again

**Comment by Malarkey-Jhu** [comment]
![image](https://user-images.githubusercontent.com/36290564/81790486-0e5e7500-9538-11ea-8701-df0f490172a3.png)

I just peek the source code and implement my own scroll function. Here I hardcoded the max value, since I just want the hours and minutes value, it doesn't matter which date it is.

**Comment by dionysis9901** [comment]
Very quick and hacky fix which gives the desired result is this.

My case is to scroll in the first event.

I also have a specific time range for min and max which is 

```
  const calendarMin = new Date(today.getFullYear(), today.getMonth(), today.getDate(), 8, 0, 0);
  const calendarMax = new Date(today.getFullYear(), today.getMonth(), today.getDate(), 23, 0, 0);
```

So i did a little hacky stuff right here :P

I sorted all my events
`const sortByDate = customDates?.sort((a, b) => new Date(a.start) - new Date(b.start));`

And then i added this prop

` scrollToTime={moment(sortByDate[0]?.start).subtract(9, "hour")}`

I know its a very specific case , but maybe someone find it helpful.

**Comment by samuthekid** [comment]
this is still an issue... if you add the min prop, the scroll doesn't even work at all
