### ISSUE TITLE
Ability to add an image to events

### ISSUE THREAD

**Issue by LukeXF** [intljusticemission/react-big-calendar#1132]
We would like to be able to display an image (user's avatar) alongside a string `event.title`. Perhaps it could be `event.image`?

**Comment by ryanimpey** [comment]
Or event.title would be able to have the type string or JSX to allow multiple use cases?

**Comment by jquense** [comment]
you can use `titleAccessor` to return more than a string i believe. the calendar should render whatever you return

**Comment by JessyAngel07** [comment]
> you can use `titleAccessor` to return more than a string i believe. the calendar should render whatever you return

@jquense        {
                   
                    titleAccessor: <Image
                        source={require('../../assets/images/png/dashBoard.png')}
                        style={[styles.image,  ]}
                        resizeMode='contain'
                    />,
                    start: new Date(),
                    end: new Date(),
                },is this a right way to implement image??
