### ISSUE TITLE
Bug: events need to 100% absolutely, fully, relentlessly, exclusively occupy slots

### ISSUE THREAD

**Issue by vilmes21** [intljusticemission/react-big-calendar#1133]
A practical feature request: allow dynamically adjusting event width.

![image](https://user-images.githubusercontent.com/20174382/49334921-5b45ca00-f596-11e8-9c14-f9f0dec7805c.png)

Current behavior: events don't take up 100%, when more events are booked in non-overlapping slots, some events suddenly take up even less widths.

Why it will be nice: Think about the use case of appointment booking, where we want one event (aka slot, or appointment) per slot. There will be no other appointments if this slot is booked. In fact, the calendar would look much nicer if all slots are 100% width. Once booked, it doesn't allow other users to select the slot to propose new appointment over the same slot.

Desired behavior: allow developers to set the width of events. At least allow 100% full width of the event. Visually it will fully occupy the slot box.

Thank you.

**Comment by jquense** [comment]
events that aren't overlapping _should_ be 100%, if your seeing the above there is a bug. If you can send over a reproduction we can get it fixed

**Comment by jquense** [comment]
A combination of events that causing this bug. I would upgrade to latest tho first to make sure it hasn't already been fixed

**Comment by jquense** [comment]
adding that api is fairly complicated, allowing "full control" will only break the calendar in most cases since the component needs to know what the dimensions of the elements are in order to lay them out. In the last we've talked about making the event layout logic pluggable, but no one has wanted it enoguh to contribute the feature :) If you're up for it glad to chat more about it.

**Comment by mkaramuk** [comment]
> @vilmes21 In a hacky way you can try to set `.rbc-events-container` margin-right to 0px. It'll take 100% slot width.

![image](https://github.com/jquense/react-big-calendar/assets/39464118/fd4c310a-5ef5-452b-9f82-46d7abc58e18)

When I set the container's `margin-right` to 0px, it appears twice when I move the event from the right slot to the left one at the border.
