### ISSUE TITLE
change the background of weekends and holidays in months view

### ISSUE THREAD

**Issue by WaysToGo** [intljusticemission/react-big-calendar#1137]
#### Do you want to request a _feature_ or report a _bug_?
feature
#### What's the current behavior?
displayed normally

#### What's the expected behavior?

Is there a way to change the background colour of weekend to gray or apply class "rbc-off-range-bg" 
 (Months view),And also same for the holidays list
in general is there a way to change add a class to particular dates 
Thanks

**Comment by jquense** [comment]
You should be able to use https://intljusticemission.github.io/react-big-calendar/examples/index.html#prop-dayPropGetter

**Comment by madanbajagai3** [comment]
link is broken

**Comment by cutterbl** [comment]
@madanbajagai3 The repository moved to a new owner some time back. This is the new link to the [dayPropGetter](https://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/props--day-prop-getter) documentation.
