### ISSUE TITLE
IE 11 issue for Day view 

### ISSUE THREAD

**Issue by cis-ankity** [intljusticemission/react-big-calendar#1142]
#### Do you want to request a _feature_ or report a _bug_?
Bug
#### What's the current behavior?
I've added the React Calendar to my application and when I've open it on IE11 browser, all the views are working fine but when I've moved to day view, it shows a blank page and when I've checked on the other browser it shows the lines for time slots available in day view.

for more information,  you can see the screenshots available -
In IE browser - 
![ie 1](https://user-images.githubusercontent.com/24387112/49582194-324c7d00-f97a-11e8-9247-06c2a6043f5d.png) 

In Chrome, it is showimng proper view-
![chrome](https://user-images.githubusercontent.com/24387112/49582244-5b6d0d80-f97a-11e8-9db8-358738327a9f.png)

#### What's the expected behavior?
It should show lines on day view for IE11 browser too.

**Comment by dmitrykrylov** [comment]
@cis-ankity is there any error message in console?

**Comment by cis-ankity** [comment]
@dmitrykrylov, there is no error message in console.

**Comment by WaysToGo** [comment]
@dmitrykrylov, even I am facing the same issue in week view in IE 11.
After  5-10 sec, it loads properly

**Comment by adam-26** [comment]
I am experiencing the same issue in IE 11. @dmitrykrylov, if you resize the browser it re-draws to render correctly. It may require that the calendar is forced to re-draw in IE 11 after initial render. Is there a hook or callback available on the client side that we can do this with?

**Comment by adam-26** [comment]
In my case, I had the calendar rendering in a div that used the css `calc()` function to determine the height of the calendars parent `div`. Removing the `calc()` function resolved this problem for me.

If you're having rendering issues in IE11, it may be wise to look at the CSS you've used in parent elements to position or size the calendar.

**Comment by adam-26** [comment]
Adding this CSS will probably fix your rendering problem.

```css
.rbc-time-column:not(.rbc-time-gutter) {
  flex: 1 0 0 !important;
}
```

This could _probably_ safely be added to the react-big-calendar css (without the `!important` of course).
