### ISSUE TITLE
Event doesn't remove from popup after drop on another date in month view

### ISSUE THREAD

**Issue by nikunjmavani** [intljusticemission/react-big-calendar#1143]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?
If we drag any event from ( + more ) popup and drop on another date, It moves but still shows in popup.

#### What's the expected behavior?
If we drag any event from ( + more ) popup and drop on another date, It should remove from popup.

**Comment by dhyegocalota** [comment]
@nikunjmavani how did you solve this matter?

**Comment by dhyegocalota** [comment]
Does someone know about it?

**Comment by nikunjmavani** [comment]
Hi @dhyegocalota, 

It's been long ago and today is exact one year; later I didn't get time to look into this. Now I forgot the functionality also.

But I'll take a look in this and will update you with my findings.

Best.
