### ISSUE TITLE
Popup events are not updated

### ISSUE THREAD

**Issue by alexeymolchan** [intljusticemission/react-big-calendar#1145]
Hi, in basic scenario i have 3 events for 1 day in month. I click show more button and popup appears, then i remove 1 event from that day and popup doesn't get this update of events count. 

As i investigated you store popup events in state.overlay.events of month view, but don't update them when events prop changes. 

Thanks for great library !

**Comment by sbmaggarwal** [comment]
I am also facing this issue. The popup events are not refreshed.
