### ISSUE TITLE
Support background events

### ISSUE THREAD

**Issue by dgouldin** [intljusticemission/react-big-calendar#115]
Full Calendar has support for forcing events to render in the background:

http://fullcalendar.io/docs/event_rendering/Background_Events/

It would be useful to support this option, either explicitly or via a css class applied through `eventPropGetter`.

Something to note: Full Calendar doesn't gracefully handle the scenario where 2 background events overlap.

**Comment by jquense** [comment]
hmm interesting, some thing like background sections would work fine? I'd be open to a PR for something like this. I do think that making them proper events seems a bit odd though, instead it seems cleaner to have a seperate prop for "segments" or something to define ranges of styled area...iI'm not sure if overlapping ones make sense. what is the use case for that and how would you handle it?

**Comment by dgouldin** [comment]
Background sections would probably work. Today, we use recurring events to contextualize other events which occur within the same range of time. Some example are explicitly noting availability or indicating travel location for a period of time. Because the contextualizations can overlap, we do need a way to visualize multiple "sections". Overlapping events already have an affordance for this with their indentation level. I'd assume whatever background rendering solution we end up with would use a similar indentation strategy for overlapping background sections and would also affect the default indentation level of events which overlap sections.

**Comment by jquense** [comment]
I think in the case of the TimeGrid views (week, day) handling the overlapping bits would be fairly straight forward, and so to would layout, , you'd just need to add another "layer" so to speak. It may be a bit harder to handle the Month view where stuff isn't really absolutely positioned...then again BackgroundCells may be able to handle it with not much tweaking..

**Comment by dgouldin** [comment]
What if we solved it using the idea of a "layer" number on an event which is akin to z-index: lower numbers render below higher numbers? The collision detection to determine indentation level would need to be refactored, but I think everything else would "just work". Default behavior in the absence of a layer value is a design decision. Default to layer 1? Default to always on bottom?

**Comment by jquense** [comment]
I was thinking about that, ultimately though I don't think things like "Busy" or "Work Hours" are really events, and I don't think it makes sense to mix those sorts of things together. I also i'd think that the styling concerns for those ranges would be fairly different from the "normal" events yeah? for instance perhaps handling overlap for background sections is better down via color and opacity vs indentation.

**Comment by dgouldin** [comment]
Yeah that sounds right, or visually splitting the background blocks horizontally to make room for overlaps. But you're right: rendering them as events conflates their concerns.

**Comment by lorinkoz** [comment]
Any progress here? This is kind of a dealbreaker for me in order to use this component.
Notice that it is indeed a very desirable feature to allow "background events" to use identation and not just opacity overlapping. They are great as means of contextualizing "foreground events" as @dgouldin has well explained.

**Comment by jquense** [comment]
nope no progress. Happy to take a PR adding support.
