### ISSUE TITLE
Drag and Drop delay

### ISSUE THREAD

**Issue by RusinovAnton** [intljusticemission/react-big-calendar#1151]
#### Do you want to request a _feature_ or report a _bug_?
_feature_
#### What's the current behavior?

Since drag'n'drop works on `mouseDown` event it often happens that drag'n'drop feature being unnecessary triggered on Event click.

#### What's the expected behavior?

Would be nice to have an option that set delay between `mouseDown` and actual drag start to prevent unnecessary drags on click

**Comment by TeaBough** [comment]
My calendar gets so slow when I have multiple resources/days/events due to this problem !

**Comment by paulhan221** [comment]
bump
