### ISSUE TITLE
Uncaught Error: NoopWrapper(...): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.

### ISSUE THREAD

**Issue by tachang** [intljusticemission/react-big-calendar#1153]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

<img width="1417" alt="screen shot 2018-12-12 at 7 50 15 am" src="https://user-images.githubusercontent.com/85011/49881198-a192f880-fde2-11e8-81b6-07fba2b6900b.png">

**Comment by tachang** [comment]
Using:

    "react": "15.6.2",
    "react-big-calendar": "0.20.2",

**Comment by grantga** [comment]
I'm seeing the same thing--is React 16 required?

**Comment by jondoesntgit** [comment]
Seeing the same thing.

**Comment by grantga** [comment]
@jondoesntgit you need to move to React 16--the control doesn't work with React 15.x I've found. Moving to React 16.x fixed this for me.
