### ISSUE TITLE
Events show up duplicated

### ISSUE THREAD

**Issue by bs85** [intljusticemission/react-big-calendar#1155]
If ressources are not provided, all events appear duplicated, probably because of this change:

https://github.com/intljusticemission/react-big-calendar/commit/91c6ec0adb7f2840e9439de1cf4690ef832f078e#diff-b9c459c0a0aa864418e73af96ebbe99eR15

The function should probably return after line 17.

**Comment by jquense** [comment]
sounds good 👍
