### ISSUE TITLE
Is there a way to create an event through external DnD event?

### ISSUE THREAD

**Issue by vigneshr23** [intljusticemission/react-big-calendar#1157]
More of a question:
Is there a way to create an event by dropping external list of event?
Suppose, I have a list of events draggable next to calendar component and i want to DnD this list into Calendar view and that should create an event.

PS: I read [#1090](https://github.com/intljusticemission/react-big-calendar/issues/1090) but sorry to say I didn't understand most of it. Can anyone please provide more detailed examples or docs to achieve the said functionality.
Thanks in advance :)

**Comment by jquense** [comment]
There isn't a built in way to do this but we'd be open to adding one!
