### ISSUE TITLE
custom header for day view

### ISSUE THREAD

**Issue by adirzoari** [intljusticemission/react-big-calendar#1166]
I'm looking to make a custom header for a day view.
for example to count how many events per day and to make header like that:
`01-03-2019 (8 events)`

how I can make it?

**Comment by josh-g3** [comment]
This isn't working for me.

**Comment by mehrdad-shokri** [comment]
Example  

```
components={{
										week: {
											header: ({ date, localizer }) =>
												localizer.format(date, 'dddd')
										}
									}}
```

**Comment by blz-ea** [comment]
If someone stumbled upon this problem:
```
components={{
  resourceHeader:  ({label, resoure, index}) => {}
}}
```

**Comment by itsalb3rt** [comment]
> Example
> 
> ```
> components={{
> 		week: {
> 			header: ({ date, localizer }) => localizer.format(date, 'dddd')
> 		}
> }}
> ```

Thanks! work perfect, in my case use `work_week` for remove days of the day.

**Comment by vasanthkumar258** [comment]
I am still facing this issue. Is there a fix for this?

**Comment by Razakhan45** [comment]
The problem to that solution lies in the CSS . They making the display none when calendar shift to single day view , just override that css , and the Header will show on Day Calendar :
 .rbc-time-header-cell-single-day{
          display: unset;
        }
