### ISSUE TITLE
Show more popup in week view

### ISSUE THREAD

**Issue by boukmi** [intljusticemission/react-big-calendar#1168]
Hi everybody,

I'd like to use a "show more" popup in week view. I tried adding `popup` prop to the calendar but it works with month view only. Yes there is different day sections that can contain overlapping events but what if I have a lot of events that starts at the same time?

- Week view
<img width="1324" alt="week" src="https://user-images.githubusercontent.com/2116866/50701862-b2671080-1014-11e9-9933-43b92f58802a.png">

- Month view
<img width="1318" alt="month" src="https://user-images.githubusercontent.com/2116866/50701911-d9254700-1014-11e9-9b91-01ed7bdc1d33.png">

So if you have any idea that would be great thanks!

**Comment by kiminohero** [comment]
@boukmi Were you able to solve the above issue ?

**Comment by boukmi** [comment]
@kiminohero unfortunately no, I just used it as it is for now!

**Comment by Joisar** [comment]
@jquense Hey, thanks a lot for the great library. I want to have +more in week view and day view. Can you please share your suggestion about possible workaround?
Regards,
Mehul.

**Comment by prashanthrepo** [comment]
@jquense any update on this? we really need a workaround for this! Week and Day needs a "More" popup.

**Comment by Lordenil** [comment]
Any update on the subject?
I would love to have the functionality to group after a specified number of records

* In our case we use the weekly view without timeline
![image](https://github.com/jquense/react-big-calendar/assets/123997255/165c4bc0-3380-4f93-a840-300753b4e8cf)

![image](https://github.com/jquense/react-big-calendar/assets/123997255/e4d90468-1ae0-4ef0-a6b2-c420f2e1a3ae)

**Comment by vagabondhoang** [comment]
@Joisar any update, bro?
