### ISSUE TITLE
We can't click on events on Firefox

### ISSUE THREAD

**Issue by Kerumen** [intljusticemission/react-big-calendar#1173]
#### Do you want to request a _feature_ or report a _bug_?

Report a _bug_.

#### What's the current behavior?

Recently, `div` in `EventCell` was changed to `button` (https://github.com/intljusticemission/react-big-calendar/pull/987).
This causes issues because we can't add clickable elements in a button on Firefox (https://stackoverflow.com/questions/50173408/clickable-div-inside-a-button-doesnt-work-on-firefox).

In our case, we have the `Event` which is a `div` with a custom `onMouseClick` attached to it but this callback doesn't get fired because of the surrounding `button`.

Moreover, this is syntactically incorrect to put interactive content in `button`, they are reserved for phrasing content ([source](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button)).

What I suggest, to keep the accessibility and to be compliant, it's to change the `button` to a `div` and to add a `tabindex={0}` to it. It will add it to the list of tappable elements ([source](https://www.w3.org/TR/wai-aria-practices/#kbd_general_between)) so the behavior will be unchanged. 

#### What's the expected behavior?

We should be able to add a custom logic to click on events.

**Comment by jaygeeken** [comment]
This is something that is causing me problems as well. Though it appears to also be affecting me in chrome also.

**Comment by jquense** [comment]
happy to take a PR fixing this!

**Comment by olegbakhirev** [comment]
Also having this issue with firefox and my custom event component, hope to have a fix! Thanks!
