### ISSUE TITLE
[Feature Request] Custom Resource Header

### ISSUE THREAD

**Issue by healthycola** [intljusticemission/react-big-calendar#1174]
I'm looking to add custom header for resources. I found that it's pretty much hard coded in [here](https://github.com/intljusticemission/react-big-calendar/blob/5857d8fb44d614047d43838be8c52bbbe2dbff55/src/TimeGridHeader.js#L172). I'm not sure if anyone is already working on this, if not, would it be okay if I created a PR to enable custom headers for resources?

Thanks!

**Comment by lksilva** [comment]
This feature has already added in last version but don't exists in @types.

"@types/react-big-calendar": "^0.20.10",
"react-big-calendar": "^0.20.4",

```
export interface Components<TEvent extends Event = Event> {
    event?: React.ComponentType<EventProps<TEvent>>;
    eventWrapper?: React.ComponentType<EventWrapperProps<TEvent>>;
    eventContainerWrapper?: React.SFC | React.Component | React.ComponentClass | JSX.Element;
    dayWrapper?: React.SFC | React.Component | React.ComponentClass | JSX.Element;
    dateCellWrapper?: React.SFC | React.Component | React.ComponentClass | JSX.Element;
    timeSlotWrapper?: React.SFC | React.Component | React.ComponentClass | JSX.Element;
    timeGutterHeader?: React.SFC | React.Component | React.ComponentClass | JSX.Element;
    timeGutterWrapper?: React.SFC | React.Component | React.ComponentClass | JSX.Element;
    toolbar?: React.ComponentType<ToolbarProps>;
    agenda?: {
        date?: React.SFC | React.Component | React.ComponentClass | JSX.Element;
        time?: React.SFC | React.Component | React.ComponentClass | JSX.Element;
        event?: React.SFC | React.Component | React.ComponentClass | JSX.Element;
    };
    day?: {
        header?: React.SFC | React.Component | React.ComponentClass | JSX.Element;
        event?: React.SFC | React.Component | React.ComponentClass | JSX.Element;
    };
    week?: {
        header?: React.SFC | React.Component | React.ComponentClass | JSX.Element;
        event?: React.SFC | React.Component | React.ComponentClass | JSX.Element;
    };
    month?: {
        header?: React.SFC | React.Component | React.ComponentClass | JSX.Element;
        dateHeader?: React.SFC | React.Component | React.ComponentClass | JSX.Element;
        event?: React.SFC | React.Component | React.ComponentClass | JSX.Element;
    };
    /**
     * component used as a header for each column in the TimeGridHeader
     */
    header?: React.ComponentType<HeaderProps>;
}
```

**Comment by Muskos** [comment]
@healthycola could you create an example?

**Comment by healthycola** [comment]
it was actually added in commit #1202 . It just didn't make the cut last release unfortunately :(

**Comment by lksilva** [comment]
Try this

```ts
<DragAndDropCalendar
  onEventDrop={this.moveEvent}
  resizable={true}
  resources={resources}
  resourceIdAccessor="resourceId"
  resourceTitleAccessor="name"
  onEventResize={this.resizeEvent}
  defaultView={BigCalendar.Views.DAY}
  defaultDate={date}
  min={min}
  max={max}
  views={["day"]}
  step={interval}
  resourceHeader: (props: any) => {
      return (
        <CustomHeader
          name={props.resource.name}
          photo={props.resource.photo}
        />
      );
    },
    timeGutterHeader: () => null,
    toolbar: () => null
  }}
/>;

```

For me work add a custom header from resourceHeader property of DragAndDropCalendar

**Comment by eeefg650** [comment]
> Try this
> 
> ```ts
> <DragAndDropCalendar
>   onEventDrop={this.moveEvent}
>   resizable={true}
>   resources={resources}
>   resourceIdAccessor="resourceId"
>   resourceTitleAccessor="name"
>   onEventResize={this.resizeEvent}
>   defaultView={BigCalendar.Views.DAY}
>   defaultDate={date}
>   min={min}
>   max={max}
>   views={["day"]}
>   step={interval}
>   resourceHeader: (props: any) => {
>       return (
>         <CustomHeader
>           name={props.resource.name}
>           photo={props.resource.photo}
>         />
>       );
>     },
>     timeGutterHeader: () => null,
>     toolbar: () => null
>   }}
> />;
> ```
> 
> For me work add a custom header from resourceHeader property of DragAndDropCalendar
> 
> The result...
> 
> > ![](https://camo.githubusercontent.com/05ad9221078b72196012b7a7735120d115fa720216df354acfe1c8e4a5b3b066/68747470733a2f2f692e696d6775722e636f6d2f485737745756532e706e67)

Hey bro maybe you can share it on github the result of custom style code ?
it could help me a lot !!!
