### ISSUE TITLE
Material ui error

### ISSUE THREAD

**Issue by isaac-a** [intljusticemission/react-big-calendar#1176]
#### Do you want to request a _feature_ or report a _bug_?
report a bug
#### What's the current behavior?
when I render the component without any custom styles, I get this error:
'Warning: Material-UI: missing color argument in fade(undefined, 0.08).'
in my app I'm using material-ui/core 3.0.1
<!--
For bugs, please include the following if possible:

**Comment by jquense** [comment]
O think you have the wrong repo. That looks like a material UI error
