### ISSUE TITLE
`Element type is invalid` error using most recent version

### ISSUE THREAD

**Issue by KenneyE** [intljusticemission/react-big-calendar#1179]
#### Do you want to request a _feature_ or report a _bug_?
Report a bug

#### What's the current behavior?
I am running into an error when using the most recent version of `react-big-calendar` (`^0.20.2`), but not seeing the error on older versions (`^0.19.2`).

I am getting the following error:
`Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object`

This sandbox has the code that reproduces the issue, but CodeSandbox's error handling shows a cross-origin error rather than the real one: https://codesandbox.io/s/5z60jx4p3x

You can see though that reducing the `react-big-calendar` version resolves the issue. Using this code locally should allow you to reproduce with the actual error.

Package Versions:
- react: `^16.4.2`
- react-big-calendar: `^0.20.2` (works with `^0.19.2`)
- moment: `^2.19.2`

#### What's the expected behavior?

No error when rendering.

![react-big-calendar-error](https://user-images.githubusercontent.com/5776842/51201833-57f26d80-18ba-11e9-862e-0d3ab359da27.png)

**Comment by benjamincharity** [comment]
I don't believe this is stale.
