### ISSUE TITLE
failed for yarn build command in 0.20.3 release

### ISSUE THREAD

**Issue by liuguoguo** [intljusticemission/react-big-calendar#1188]
#### Do you want to request a _feature_ or report a _bug_?

report a bug

#### What's the current behavior?
For 0.20.3 release version, failed to do the 'yarn build'. 'yarn build' is ok for the previous release build.
D:\download\react-big-calendar-0.20.3>yarn build
yarn run v1.12.3
$ yarn clean && yarn build:cjs && yarn build:umd && yarn assets && yarn less
$ rimraf lib
$ babel src --out-dir lib
Successfully compiled 52 files with Babel.
$ BABEL_ENV=esm yarn rollup -c
'BABEL_ENV' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by dkniffin** [comment]
I ran into this too. `yarn install` fixed it.
