### ISSUE TITLE
resizable prop doesn't work 

### ISSUE THREAD

**Issue by mvgeo** [intljusticemission/react-big-calendar#1189]
#### Do you want to request a _feature_ or report a _bug_?
Bug
#### What's the current behavior?
In `dragAndDrop/withDragAndDrop.js`, the comment documentation says to set `resizable` to `true` to make events resizable. Correct me if I'm wrong but it _looks_ like setting this prop does nothing (unless some magic is done where I can't find it)? 

Reading through the code in `withDragAndDrop.js` it doesn't look like the `resizable` variable is used anywhere at all. Assuming it gets passed directly to the `Calendar` component, `resizable` is not defined in the props as a valid prop anyway.

To replicate this run the dnd example and set `resizable = {false}` as mentioned in the `withDragAndDrop.js`. The events are still resizable.

Version: `0.20.3`

Diving into `dragAndDrop/EventWrapper.js` it looks like the `resizableAccessor` prop is used to determine whether or not an event can be resized or not. Thus setting the `resizableAccessor` prop on the `Calendar` component to return false makes events **not** resizable. 

#### What's the expected behavior?
I'm not sure which is the correct method is to set events to **not** be resizable is due to conflicting documentation in `dragAndDrop/withDragAndDrop.js`. Furthermore none of it is on the official documentation.

Thus my only suggestion is a clearer documentation around which prop should be set to disable resizing of events.

**Comment by eHallberg** [comment]
I have the same question, with resizable={false} i would expect the resize handles to be hidden and resize events should not fire. Any updates here?

**Comment by tai2** [comment]
Yes, `resizable` prop is nothing to do with resize anchor. It seems a documentation bug.

**Comment by liben96** [comment]
Any updates on this?

**Comment by sagark1510** [comment]
It is possible to disable resizing but not by the `resizable` prop.
Please add this prop to your DnD calendar and it should disable it.
 `resizableAccessor={() => false}`
