### ISSUE TITLE
Can't select slots on allDay

### ISSUE THREAD

**Issue by manutenfruits** [intljusticemission/react-big-calendar#119]
While in the week view it's impossible to create events by dragging on the "allDay" section, even when `selectable` and `onSelectSlot` are passed. The bug can be reproduced in the demo/docs page. Just go to http://intljusticemission.github.io/react-big-calendar/examples/index.html, select the "Selectable" demo, switch to "week" or "agenda" view and drag on the "all day" row. It highlights as you drag, but doesn't do anything after you release the mouse.

**Comment by jquense** [comment]
fixed in v0.11!
