### ISSUE TITLE
Overlapping 15mins events that shouldn't overlap

### ISSUE THREAD

**Issue by samlll42-github** [intljusticemission/react-big-calendar#1192]
Hi everyone

Our calendar shows contiguous events that are displayed with an offset as if they overlap (although they do not overlap). This happens when we have contiguous event and one of them is 15 mins long.

We use step=5 and timeslots=12

I've seen a couple of ticket address this issue on previous versions but not clear what is the recommendation on this.

We've applied the following patch to workaround the issue for now. Did we miss something? is there a better way to address this issue? If not what do you guys think about making this configurable?

Thanks 

```
diff --git a/src/DayColumn.js b/src/DayColumn.js
index 8771f3c..cd3c97e 100644
--- a/src/DayColumn.js
+++ b/src/DayColumn.js
@@ -177,7 +177,7 @@ class DayColumn extends React.Component {
       events,
       accessors,
       slotMetrics,
-      minimumStartDifference: Math.ceil((step * timeslots) / 2),
+      minimumStartDifference: Math.ceil((step * timeslots) / 4),
     })
```

     return styledEvents.map(({ event, style }, idx) => {

**Comment by uar-alin-vetian** [comment]
Hello to all, I am having the same issues. 
If I have 3 events starting one after the other, they are drawn like they overlap if the first one is less then 30 minutes.

I use `step={5} timeslots={3}`
