### ISSUE TITLE
Is there a way to customize the TimeGridHeader?

### ISSUE THREAD

**Issue by nsb** [intljusticemission/react-big-calendar#1194]
Is there a way to customize the TimeGridHeader? I could not find any in the docs or code.

**Comment by healthycola** [comment]
Which part of the header? props.components.header should handle most header customizations. If you're looking for resource header customizations, that just went in last week, so next release?

**Comment by nsb** [comment]
I'm trying to show the count of events per day at the top of the all day date column. Sort of like this screeshot
![screenshot from 2019-01-29 19-01-21](https://user-images.githubusercontent.com/16436/51929388-65e6d900-23f8-11e9-9569-9d34b2e482ee.png)

**Comment by nsb** [comment]
Closing as it's better to take this else where.

**Comment by usersina** [comment]
> Closing as it's better to take this else where.

So where was this taken? ^^'
