### ISSUE TITLE
Start day resize anchor disappears

### ISSUE THREAD

**Issue by kelsey93** [intljusticemission/react-big-calendar#1198]
For events spanning multiple weeks, if you resize the end date (even just by a day) and go to resize the start date the resize anchor is not displayed and you cannot resize the start date. It seems the end date resize anchor is still available though. This is present on the demo site under the drag and drop example. 

To reproduce: 
1 - Go to the drag and drop example located at : https://intljusticemission.github.io/react-big-calendar/examples/index.html#dnd
2 - Move the end date of the multiday event from 22nd to the 30th
3 - Go to move the start date from the 20th to the 19th. Notice there is no resize anchor.

**Comment by ZakRabe** [comment]
bumping so this issue doesn't get closed
