### ISSUE TITLE
Unable to resize start or end time of event spanning multiple days

### ISSUE THREAD

**Issue by kelsey93** [intljusticemission/react-big-calendar#1199]
It would be nice to be able to have the ability to resize the start and end time of events that span over multiple days on the calendar. For example: an event that starts at 3pm on the 27th and ends at 5am on the 28th. Currently if you try to resize these times the resizeEvent returns either an invalid start date or an invalid end date and the event disappears from the calendar. Behaves similarly for events that span more than 2 days.

**Comment by ZakRabe** [comment]
bumping so this issue doesn't get closed

**Comment by anlijiu** [comment]
why won't fix ?
