### ISSUE TITLE
0.9.4 broken? Validation checks for the firstOfWeek in localizer

### ISSUE THREAD

**Issue by joewood** [intljusticemission/react-big-calendar#12]
I'm using the 0.9.4 release and I'm seeing an assertion error that I wasn't seeing in 0.9.2.
The failure is around finding the function `firstOfWeek` in the localizer.
I'm using `moment` to initialize:

```javascript
BigCalendar.setLocalizer(
  BigCalendar.momentLocalizer(moment)
);
```

**Comment by jquense** [comment]
not broken for me, can you be a bit more specific about the error?

**Comment by joewood** [comment]
This invariant is failing: https://github.com/intljusticemission/react-big-calendar/blob/master/src/localizer.js#L27

This is running with Moment 2.10.6.  Moment has `startOf("week")` - I think `startOfWeek` is deprecated.

**Comment by joewood** [comment]
Just checking through the code in more detail, and I see it's using the locale.firstDayOfWeek. I think this must just be a initialization problem and the momentLocalizer isn't being returned properly. I'll keep investigating.  Thanks.

**Comment by jquense** [comment]
Ahh I think the problem is I made a change to the API but didn't document it.

you don't need `setLocalizer` just use `BigCalendar.momentLocalizer(moment)` it will set itself

**Comment by joewood** [comment]
Ah! That's fixed it. Thanks!
