### ISSUE TITLE
Work in Strict Mode to avoid hitting a wall in upcoming React versions

### ISSUE THREAD

**Issue by tdd** [intljusticemission/react-big-calendar#1200]
#### Do you want to request a _feature_ or report a _bug_?

It's a feature of sorts, more like making sure we can still use this by the end of 2019…

#### What's the current behavior?

Rendering a calendar inside React’s `<StrictMode>` wrappers yields a ton of deprecation / unsafe pattern warnings in the console:

- [Deprecated `findDOMNode()` usage](https://reactjs.org/docs/strict-mode.html#warning-about-deprecated-finddomnode-usage) (the modern Refs API should be used instead)
- [Unsafe lifecyle methods](https://reactjs.org/docs/strict-mode.html#identifying-unsafe-lifecycles) (typically `componentWillMount()` and `componentWillUpdate()`)

#### What's the expected behavior?

The codebase should try and move to the newer, cleaner, safer accepted ways to achieve the same results, in order not to find itself stonewalled when some upcoming React 16.x version finally strips these, some of which have long been deprecated.

My OSS/PR queue is already quite full for the next few weeks but I might try and give it a go around late Feb / March if the regular maintainers can't.

**Comment by justingrant** [comment]
Shouldn't be closed. This should be fixed before `findDOMNode` is removed from React.

**Comment by bboyjacks** [comment]
Yea, is it possible to update? Otherwise it will only be usable for people with some version of react and below.

**Comment by niccai** [comment]
Yes, please reopen this issue.

**Comment by jquense** [comment]
Happy to take a PR!

**Comment by avindra** [comment]
Please re-open this issue.

This will become a major blocker with a new React release. Probably 17.

https://reactjs.org/docs/concurrent-mode-adoption.html#feature-comparison

**Comment by justingrant** [comment]
FWIW, I've moved away from using react-big-calendar, partially for this reason.

**Comment by avindra** [comment]
@justingrant is there another open source project that you've moved towards? For those of us who also want to be proactive instead of waiting indefinitely for removal of `findDOMNode` and other hacks that were clearly documented as things to avoid.

**Comment by justingrant** [comment]
Hi @avindra - Nope, I ended up rolling my own plain-JSX solution.  My own implementation is limited and lacks most RBC features, but my app has pretty limited needs so it's good enough for now. I may consider switching back to RBC later but for now I've moved on.
