### ISSUE TITLE
Callbacks for starting drag/resize events?

### ISSUE THREAD

**Issue by kamry-bowman** [intljusticemission/react-big-calendar#1205]
Currently, the drag and drop calendar has props for callbacks when a resize or drop event occurs, but I have a use case for performing activities at the beginning of a resize or drop event, when the user starts resizing or dragging an event but hasn't yet finished. I don't believe this is a feature currently, but I wanted to double-check if I'm mistaken, or if there is another approach that could achieve the same end with the current API.

Thanks for any feedback/discussion!

**Comment by jquense** [comment]
there isn't an y callbacks but happy to add them if you wanna send over a PR

**Comment by kamry-bowman** [comment]
Thanks! I've opened a PR implementing this feature, welcome any feedback! #1206
