### ISSUE TITLE
Issues on DST start - Week of March 10th

### ISSUE THREAD

**Issue by coder-guy22296** [intljusticemission/react-big-calendar#1207]
**Do you want to request a feature or report a bug?**
Bug

**What's the current behavior?**
- if time range includes 2am(March 10):  3am shows up twice (probably tricky to solve, not a high priority form me)
![screenshot from 2019-02-02 17-10-06](https://user-images.githubusercontent.com/5077206/52171341-2aa61c00-2710-11e9-9c34-5537d7e1714f.png)
- if range starts at 2am: 3am shows twice, and the event on march 10th is in the wrong spot (probably tricky to solve, not a high priority form me)
![screenshot from 2019-02-02 17-10-34](https://user-images.githubusercontent.com/5077206/52171393-26c6c980-2711-11e9-8183-9aa55409e5bc.png)
-time range does not include 2am: events for the whole week are not aligned with the time gutter(e.g. 4:30 event shown at 3:30) **especially problematic because most users probably show somthing like 9am to 5pm, not time ranges that include 2am**
![screenshot from 2019-02-02 17-10-50](https://user-images.githubusercontent.com/5077206/52171405-6d1c2880-2711-11e9-9b0d-fd20306c6ce8.png)

**storybook stories**
```javascript
storiesOf('Big Calendar', module)
  .add('range includes dst start', () => (
    <Calendar
      defaultView={Calendar.Views.WEEK}
      popup
      events={demoEvents}
      min={moment('1:00am', 'h:mma').toDate()}
      max={moment('5:00pm', 'h:mma').toDate()}
      onSelectEvent={action('event selected')}
      defaultDate={new Date(2019, 2, 10)}
    />
  ))
  .add('range starts at dst start', () => (
    <Calendar
      defaultView={Calendar.Views.WEEK}
      popup
      events={demoEvents}
      min={moment('2:00am', 'h:mma').toDate()}
      max={moment('6:00pm', 'h:mma').toDate()}
      onSelectEvent={action('event selected')}
      defaultDate={new Date(2019, 2, 10)}
    />
  ))
  .add('dst change not in range', () => (
    <Calendar
      defaultView={Calendar.Views.WEEK}
      popup
      events={demoEvents}
      min={moment('3:00am', 'h:mma').toDate()}
      max={moment('7:00pm', 'h:mma').toDate()}
      onSelectEvent={action('event selected')}
      defaultDate={new Date(2019, 2, 10)}
    />
  ))
  .add('dst change at end of range', () => (
    <Calendar
      defaultView={Calendar.Views.WEEK}
      popup
      events={demoEvents}
      min={moment('7:00pm', 'h:mma').toDate()}
      max={moment('2:00am', 'h:mma').toDate()}
      onSelectEvent={action('event selected')}
      defaultDate={new Date(2019, 2, 10)}
    />
  ))
```

**What's the expected behavior?**
I would expect the timeslot labels to have the correct time label based on whether you are currently in or out of Daylight Savings Time (DST). At least when the time range does not include the DST shift time, all the timeslot labels should line up with the events at their respective time

Has anyone attempted to fix this issue or has any suggestions on how or where to start, I would really appreciate it. I would be happy to contribute and submit a PR

**Comment by tfuqua** [comment]
I'm facing the same issue right now and would if anyone has found a fix to this!

**Comment by devendrapandey333** [comment]
I am also facing the same issue.
