### ISSUE TITLE
Event is not passed down to children in Month view

### ISSUE THREAD

**Issue by kayandrewj** [intljusticemission/react-big-calendar#1209]
I'm currently using Using 0.20.2, and am trying to show time in the Monthly calendar view. Currently, Event is passed from EventWrapper as part of an array (including Event at 0 and the other data at 1), but it does not seem that Event is passed in Month view. Is it possible to display times in Month view?

**Comment by GodGreg** [comment]
> I'm currently using Using 0.20.2, and am trying to show time in the Monthly calendar view. Currently, Event is passed from EventWrapper as part of an array (including Event at 0 and the other data at 1), but it does not seem that Event is passed in Month view. Is it possible to display times in Month view?

I'm using the same version and can't seem to get anything to show for the Monthly Calendar View
