### ISSUE TITLE
Header day columns loose alignment in resource view

### ISSUE THREAD

**Issue by NathanBP** [intljusticemission/react-big-calendar#1212]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?
When in resource view the header day columns can become unaligned to the body day columns below. This can easily be reproduce by going to the resource calendar example and scrolling all the way to the right, the columns will eventually start to loose alignment.

![image](https://user-images.githubusercontent.com/37284011/52391228-e5a33080-2ae7-11e9-8a3d-a00fd6dbb82e.png)

#### What's the expected behavior?
The day columns in the header should stay aligned with the day columns in the body of the calendar

**Comment by limzb** [comment]
I encountered the same issue. Any fix so far?
