### ISSUE TITLE
Getting a blank calendar.. just text.. 

### ISSUE THREAD

**Issue by rchancey** [intljusticemission/react-big-calendar#1215]
I am doing the  basic.. and  after 2  hours of trying.. just get  text no  graphics.. 

I literally just  copied  the basic  code and pasted. .. I  even copied the dates class.

any ideas?
<img width="1175" alt="screen shot 2019-02-07 at 3 44 34 pm" src="https://user-images.githubusercontent.com/29101431/52444913-4a15be00-2aef-11e9-9ce8-4e7b864a105a.png">

import React, { Component } from "react";
import PropTypes from 'prop-types';
import { withStyles } from '@material-ui/core/';
import BigCalendar from 'react-big-calendar'
import moment from 'moment'
import dates from '../utils/dates'
const localizer = BigCalendar.momentLocalizer(moment)
let allViews = Object.keys(BigCalendar.Views).map(k => BigCalendar.Views[k])

class ScheduleView extends Component {
    constructor(props) {
        super(props);
        this.state = {
            type: 'month',
        };

    }
  
    render() {
        const events = [
            {
                id: 0,
                title: 'All Day Event very long title',
                allDay: true,
                start: new Date(2015, 3, 0),
                end: new Date(2015, 3, 1),
            },
            {
                id: 1,
                title: 'Long Event',
                start: new Date(2015, 3, 7),
                end: new Date(2015, 3, 10),
            },

            {
                id: 2,
                title: 'DTS STARTS',
                start: new Date(2016, 2, 13, 0, 0, 0),
                end: new Date(2016, 2, 20, 0, 0, 0),
            },

            {
                id: 3,
                title: 'DTS ENDS',
                start: new Date(2016, 10, 6, 0, 0, 0),
                end: new Date(2016, 10, 13, 0, 0, 0),
            },

            {
                id: 4,
                title: 'Some Event',
                start: new Date(2015, 3, 9, 0, 0, 0),
                end: new Date(2015, 3, 10, 0, 0, 0),
            },
            {
                id: 5,
                title: 'Conference',
                start: new Date(2015, 3, 11),
                end: new Date(2015, 3, 13),
                desc: 'Big conference for important people',
            },
            {
                id: 6,
                title: 'Meeting',
                start: new Date(2015, 3, 12, 10, 30, 0, 0),
                end: new Date(2015, 3, 12, 12, 30, 0, 0),
                desc: 'Pre-meeting meeting, to prepare for the meeting',
            },
            {
                id: 7,
                title: 'Lunch',
                start: new Date(2015, 3, 12, 12, 0, 0, 0),
                end: new Date(2015, 3, 12, 13, 0, 0, 0),
                desc: 'Power lunch',
            },
            {
                id: 8,
                title: 'Meeting',
                start: new Date(2015, 3, 12, 14, 0, 0, 0),
                end: new Date(2015, 3, 12, 15, 0, 0, 0),
            },
            {
                id: 9,
                title: 'Happy Hour',
                start: new Date(2015, 3, 12, 17, 0, 0, 0),
                end: new Date(2015, 3, 12, 17, 30, 0, 0),
                desc: 'Most important meal of the day',
            },
            {
                id: 10,
                title: 'Dinner',
                start: new Date(2015, 3, 12, 20, 0, 0, 0),
                end: new Date(2015, 3, 12, 21, 0, 0, 0),
            },
            {
                id: 11,
                title: 'Birthday Party',
                start: new Date(2015, 3, 13, 7, 0, 0),
                end: new Date(2015, 3, 13, 10, 30, 0),
            },
            {
                id: 12,
                title: 'Late Night Event',
                start: new Date(2015, 3, 17, 19, 30, 0),
                end: new Date(2015, 3, 18, 2, 0, 0),
            },
            {
                id: 12.5,
                title: 'Late Same Night Event',
                start: new Date(2015, 3, 17, 19, 30, 0),
                end: new Date(2015, 3, 17, 23, 30, 0),
            },
            {
                id: 13,
                title: 'Multi-day Event',
                start: new Date(2015, 3, 20, 19, 30, 0),
                end: new Date(2015, 3, 22, 2, 0, 0),
            },
            {
                id: 14,
                title: 'Today',
                start: new Date(new Date().setHours(new Date().getHours() - 3)),
                end: new Date(new Date().setHours(new Date().getHours() + 3)),
            },
        ];
        return (
            <div style={{ height: '75vh', minHeight: "580px", minWidth: "650px", background: "#FE6B8B", padding: "15px" }}>
              <BigCalendar
              events={events}
              views={allViews}
              step={60}
              showMultiDayTimes
              max={dates.add(dates.endOf(new Date(2015, 17, 1), 'day'), -1, 'hours')}
              defaultDate={new Date(2015, 3, 1)}
              localizer={localizer}
            />
            </div>

        )
    }
}

const styles = {
    div: {
        margin: 10
    }
};

ScheduleView.propTypes = {
    children: PropTypes.node,
    classes: PropTypes.object.isRequired
};

export default withStyles(styles)(ScheduleView);

**Comment by rchancey** [comment]
Never  mind..  had to include the css.. DOH!

**Comment by gmazzo** [comment]
> Never mind.. had to include the css.. DOH!

Hi @rchancey, how have you included the CSS? I'm kind of newbie on React, and I'm giving a try to React-Kotlin. I've included some @material components without any issue, but with this one the CSS are missing the the result is pretty much like your issue.

**Comment by YashTotale** [comment]
Yep, having the same issue
