### ISSUE TITLE
Should you create a custom event wrapper component?

### ISSUE THREAD

**Issue by drydenwilliams** [intljusticemission/react-big-calendar#1217]
There is no documentation for adding a `eventWrapper` and I've seen a few comments saying it's not meant to be overwritten. Should we be using this or trying to create custom `eventWrapper` component to override this exsisting one?

For me I don't want the `.rbc-event-label` also want to dynamically in JS change the styling. Or should I be just changing things in the CSS?

**Comment by wootwoot1234** [comment]
Did you ever figure this out?  I'm in the same boat, would love a push in the right direction.

**Comment by adityaloshali** [comment]
@drydenwilliams so, is it that you don't want the blue wrapper around the event and default time range that it shows when shrinking down on week view ? or you just want to change the colors ?

**Comment by PHCCorso** [comment]
I've worked out a way to make a proper `eventWrapper` for the DnD plugin (one that doesn't break DnD):

```js
function eventWrapper(props) {
  // Some data that you might have inserted into the event object
  const data = props.event;
  const customDiv = (
    <div className="yourClass">
      <span>{data.someField}</span>
      <span>{data.anotherField}</span>
    </div>
  );
  const eventDiv = React.cloneElement(props.children.props.children, {}, customDiv);
  const wrapper = React.cloneElement(props.children, {}, eventDiv);
  return (<div>
    {wrapper}
  </div>
  );
}
```

It isn't perfect because the `eventWrapper` comes back to what it was before when you're dragging the event, only returning to your custom `eventWrapper` when you drop it. I still don't know how to fix that.

**Comment by Canopix** [comment]
Thanks so much for this!! @salao-na-mao-developer
