### ISSUE TITLE
Consider date-io for libraries interoperability

### ISSUE THREAD

**Issue by TrySound** [intljusticemission/react-big-calendar#1219]
#### Do you want to request a _feature_ or report a _bug_?

Feature

#### What's the current behavior?

Currently this library implement own localisation adopters. Their maintenance is quite difficult and time wasting. 

#### What's the expected behavior?

I suggest to consider reusing existing library for interoperability with date utils libs.
https://github.com/dmtrKovalenko/date-io

It supports the following libs
- moment
- date-fns
- luxon
- dayjs

Globalize wasn't considered but can be added it you want.

**Comment by jquense** [comment]
that would be awesome to get rid of all this code, we'd probably need a globalize version and need to verify it covers all the required bases. We still probably need to keep implementation specific formats it looks like? I guess its easy to work around that as well

**Comment by TrySound** [comment]
Yeah, sure. We are open for changes and improvements in date-io.

**Comment by jquense** [comment]
happy to help out maybe as well. I've a few projects that would benefit from this sort of thing. really nice to see !

**Comment by dmtrKovalenko** [comment]
Hi, I am the maintainer of date-io. I can help with new methods or integration as well :)

**Comment by bernardobgam** [comment]
Any progress on this? Date-io would be great

**Comment by pierre-H** [comment]
any news ?
