### ISSUE TITLE
onClick for single date or disable drag to select

### ISSUE THREAD

**Issue by connercms** [intljusticemission/react-big-calendar#1222]
#### Do you want to request a _feature_ or report a _bug_?
Feature
#### What's the current behavior?
Unless mistaken, there is no api for when a user clicks on a single date in the calendar. You can set selectable={true} and use onSelectSlot, but this allows the user to select multiple days, and I also don't see a way to limit selection to just one day. Returning false in onSelection only disables drag selection in the Time views (week, day, agenda). Am I missing this feature in the documentation?

**Comment by KoichiSakamoto** [comment]
It's true, there's no API for this (that I could find, atleast.) One way I got around this is by disregarding the 'end' parameter in onSelectSlot. This simulates a simple click, and allows you to operate on 'selects' as a click, as you don't operate on the 'end' date whatsoever. Unfortunately, this causes some issues when using the calendar on mobile, and I had to further tinker with the eventHandlers in the Selection.js file in an attempt to make touchscreen clicks operate similarly to mouse clicks.

**Comment by LFTroya** [comment]
any update on this? I am looking for this same feature. On mobile, I cannot scroll down without the calendar trying to select a range of dates

**Comment by BrianMa788** [comment]
i am facing this issue too, even in 2021...

**Comment by shikelong** [comment]
the same issue

**Comment by aashu0148** [comment]
same issue even in Nov 2022 🖐️

**Comment by fstivicic** [comment]
Still needing this. 'onSelecting' not to be ignored in a 'month' view and decoupling click select and drag select, so we can disable either one.

**Comment by ivan-tecadi** [comment]
draggableAccessor={event => false}

**Comment by abuayaan01** [comment]
const handleSelectSlot = (e) => {
    if (e.action == "select") return;

    //Your code ...
  }
