### ISSUE TITLE
custom event accessors do not work well for multi day events on a week view

### ISSUE THREAD

**Issue by persil** [intljusticemission/react-big-calendar#1226]
I had an issue with the size of the multi day event element. To make long story short,  I traced the issue down to the following:
1. the endAccessor was set to something else than "end"
2. in file dayViewLayout.js for a particular day (column on week view) if event crosses the column limits the new ewent is being created with function constructEvent <<<=== this is where in my opinion the bug lies - it creates event object with fields "start" and "end" and not taking into account what the user has chosen.
3. later with newly created event object, the getYStyles function calculates its box limits by looking at the dates stored in fields named by startAccessor and endAccessor.

**Comment by jquense** [comment]
thanks for the issue. I'm sure i see the bug you're talking about here. The Event that is created here is an abstraction and not passed back to the component. It pulls the start and end dates from your event using the accessors and gives them a generic name internally so it doesn't have to call the accessors over and over again.

can you point specifically to a the lines you think are wrong, or if you'r up for it send over a PR

**Comment by persil** [comment]
Hi Jason, 
Mate, I am terribly sorry. I just miss-googled the react-big-calendar. Now when I pulled your code it turned out to work great. The component which is probably bugged is the one which was forked from your code - https://github.com/onursimsek94/react-big-calendar
Apologies.
