### ISSUE TITLE
Does not show Events on EI 

### ISSUE THREAD

**Issue by Antibioticvz** [intljusticemission/react-big-calendar#123]
Events in day slots does not work on Internet Explorer.

**Comment by kevinjcliao** [comment]
I'm having this issue too on Chrome. To debug this, I've already removed any sort of backend code pushing events towards the calendar and replaced the events to dummy data provided in the repository. 
`
const CalendarContainer = React.createClass({
  getInitialState: function() {
    return {
      loading: true,
      events: null
    }
  },
  componentWillMount: function() {
    firebase.database().ref('requests/').on('value', (events) => {
      this.props.setCalendarEvents(events.val());
    });
  },
  render: function() {
    console.log("Header is being rendered.");
    console.log("Rendering a calendar with events: ", this.props.calendar.events);
    return (
      <div className="calendar-container">
        <h1>Calendar</h1>
        <BigCalendar
          events={[
            {
              'title': 'Long Event',
              'start': new Date(),
              'end': new Date()
            },
          ]}
          startAccessor='startDate'
          endAccessor='endDate'
        />
      </div>
    );
  }
});
`

**Comment by kevinjcliao** [comment]
Could you provide the code of your component? Maybe we can do a little exploring together.

**Comment by kevinjcliao** [comment]
Nevermind, I removed the startDate and endDate props and my events are displaying. Thanks!

**Comment by Antibioticvz** [comment]
My code is
`import React, { Component, PropTypes } from 'react';
import moment from 'moment';
import MyEvent from './MyEvent';
import BigCalendar from 'react-big-calendar';
BigCalendar.momentLocalizer(moment);

import {Button, Modal} from 'react-bootstrap';

import Loader from 'react-loader';

class CoreCalendar extends Component {
constructor(...args) {

    super(...args);

    this.state = {
        culture: 'en-GB',
        eventsRecords:[],
        showModal: false,
        modEve: '',
        loader:true
    };
}

    componentEvents(){

        var eveRecords = [];
        var that = this;
        
        that.setState({loader:false});
        
        jQuery.post(
            MyAjax.ajaxurl,
            {
                dataType: 'json', // jQuery will parse the response as JSON
                'action': 'search_events',
                'nonce' : MyAjax.nonce,
                async: false
            }
        ).success(function(response){

            var resp =JSON.parse(response);

            $.each( resp, function( i, res )
            {
                eveRecords.push(
                    {
                        "allDay": true,
                        'event_id'  :  res.event_id ,
                        'title' : res.event_name ,
                        'event_other' : res.event_other ,
                        'start' : res.event_start ,
                        'end' : res.event_finish ,
                        'event_budget' : res.event_budget ,
                        'event_facility' : res.event_facility ,
                        'event_regos' : res.event_regos ,
                        'event_promoscreensaver' : res.event_promoscreensaver ,
                        'event_promonewsletter' : res.event_promonewsletter ,
                        'event_promobrochures' : res.event_promobrochures ,
                        'event_promoposter' : res.event_promoposter ,
                        'event_promoother' : res.event_promoother ,
                        desc : res.event_promootherdesc ,
                        'event_num' : res.event_num ,
                        'event_cost' : res.event_cost ,
                        'event_feedback' : res.event_feedback
                    }
                );
            });
            that.setState({eventsRecords : eveRecords})
        }).done(
            ()=>that.setState({loader:true})
        );
    }

    componentDidMount(){
        if (process.env.NODE_ENV === 'production') {
            this.componentEvents();
        }
    }

    render() {

    return (
        <div>
            <Loader loaded={this.state.loader} lines={13} length={20} width={10} radius={30}
                    corners={1} rotate={0} direction={1} color="#000" speed={1}
                    trail={60} shadow={false} hwaccel={false} className="spinner"
                    zIndex={2e9} top="50%" left="50%" scale={1.00}
                    loadedClassName="loadedContent" />
            
            <Modal show={this.state.showModal} bsSize="large" onHide={()=> this.setState({showModal: false})}>
                <Modal.Body>
                    {this.state.modEve}
                </Modal.Body>
                <Modal.Footer>
                    <Button onClick={()=> this.setState({showModal: false}) }>Close</Button>
                </Modal.Footer>
            </Modal>

            <Button onClick={()=> {
                this.setState({
                    modEve: <MyEvent
                        resetCalendar={this.props.resetCalendar}
                        calendarMode="true"
                    />});
                this.setState({showModal: true});
            }
            } bsStyle="danger" block>Create new Event</Button>
            <p><br/></p>

            <BigCalendar selectable
                         onSelectEvent={(e) => {
                this.setState({modEve: <MyEvent
                        //Calendar mode to create reset method when event id set
                        calendarMode={true}
                        resetCalendar={this.props.resetCalendar}
                        event_id={e.event_id}
                        event_name={e.title}
                        event_other={e.event_other}
                        event_start={e.start}
                        event_finish={e.end}
                        event_budget={e.event_budget}
                        event_facility={e.event_facility}
                        event_regos={e.event_regos}
                        event_promoscreensaver={e.event_promoscreensaver}
                        event_promonewsletter={e.event_promonewsletter}
                        event_promobrochures={e.event_promobrochures}
                        event_promoposter={e.event_promoposter}
                        event_promoother={e.event_promoother}
                        event_promootherdesc={e.desc}
                        event_num={e.event_num}
                        event_cost={e.event_cost}
                        event_feedback={e.event_feedback}
                    />});
                this.setState({showModal: true});
            }}

                         culture={this.state.culture}
                         popupOffset={{x: 30, y: 20}}
                         views={['month', 'day', 'agenda']}
                         onSelectSlot={()=>{ this.setState({ modEve: <MyEvent resetCalendar={this.props.resetCalendar} calendarMode="true"/>});
                                             this.setState({showModal: true});
                                            }
                                       }

                         events={this.state.eventsRecords}
            />
        </div>
    );
}
}

export class Calendar extends Component {

    constructor(...props) {
        super(...props);
        this.state = {
            key: 0
        };
    }

    render() {
        return (
            <div>
                <CoreCalendar {...this.props}
                    resetCalendar={() => this.setState({key: this.state.key + 1})}
                    key={this.state.key}
                />
            </div>
        );
    }
}

export default Calendar;`

**Comment by jquense** [comment]
@Antibioticvz  waht do you mean by "day slots" care to share a screenshot?

**Comment by Antibioticvz** [comment]
@jquense [Screenshot](https://s32.postimg.org/8xphxz1et/Effort_Tracker_v2_0.png)
and on IE you will see blanked slots. no errors on console

**Comment by jquense** [comment]
@Antibioticvz I don't see a problem with anything in IE on the examples page for the Month view...It might be something you've done in your styling

**Comment by Antibioticvz** [comment]
@jquense [Screenshot](https://postimg.org/image/n1qtzhyuv/)
Here you can see example without css at all

**Comment by jquense** [comment]
Sorry what version of IE are you running... like I said I just tested it in IE and events were showing up correctly

**Comment by Antibioticvz** [comment]
@jquense 11 Edge

**Comment by Antibioticvz** [comment]
Now I know what it was. For EI Events date should be 
```
'start' : new Date(2016, 6, 1) ,
'end' : new Date(2016, 7, 1) ,
```
NOT

> "2016-07-1 00:00:00"
But it works for Chrome

**Comment by jquense** [comment]
I believe that's because chrome will parse that fine. interesting edge case!

**Comment by prathimapilli** [comment]
> Now I know what it was. For EI Events date should be
> 
> ```
> 'start' : new Date(2016, 6, 1) ,
> 'end' : new Date(2016, 7, 1) ,
> ```
> 
> NOT
> 
> > "2016-07-1 00:00:00"
> > But it works for Chrome

Hi Im also getting the same issue. it is working in chrome but events are not working in ie11. Is there any code change? Kindly suggest

**Comment by prathimapilli** [comment]
> Now I know what it was. For EI Events date should be
> 
> ```
> 'start' : new Date(2016, 6, 1) ,
> 'end' : new Date(2016, 7, 1) ,
> ```
> 
> NOT
> 
> > "2016-07-1 00:00:00"
> > But it works for Chrome

Hi, 
React calendar events are not working in IE, it is working properly in chrome. any idea pls suggest

thanks,
