### ISSUE TITLE
Current time line does not display correctly when switch from week view to day view

### ISSUE THREAD

**Issue by NathanBP** [intljusticemission/react-big-calendar#1232]
#### Do you want to request a _feature_ or report a _bug_?
Report a bug

#### What's the current behavior?
Replicate this bug by doing the following:

- Open calendar in day view
- Set date to today
- Change to week view
- Change the date to another day
- Go back to day view
- Change date to today
- Current time line will appear at the top of the calendar rather than at the current time

![image](https://user-images.githubusercontent.com/37284011/53218514-21252980-36a8-11e9-8c92-3047b39c12a6.png)

#### What's the expected behavior?
Timeline should appear at current time no matter how the user navigated to the current date.

**Comment by linainvers** [comment]
confirm this, I think this is due to the untimely update of the date for indicator

**Comment by NathanBP** [comment]
This is still an issue, posting a message to keep it open

**Comment by RoBYCoNTe** [comment]
I'm having the same problem too.

**Comment by RoBYCoNTe** [comment]
Hi guys, after looking inside code I discovered what causes my problem using agenda.
Inside the root component, BigCalendar, we can set another prop called "getNow", this is a functional prop that return "current date". I was facing an issue related to the "Today" press on Agenda. I was able to display only events greather then current date **and time**.

To fix it I've used this code:
`<BigCalendar 
  ...props
  getNow={() => moment().startOf('day').toDate()} />`

Hope this can help you too! :)

**Comment by NathanBP** [comment]
@RoBYCoNTe Thanks for that, I had to modify it slightly for my use case as I still require the timeline to load at the current time and not at the start of the day. The below code was what fixed my current issue. Thanks again @RoBYCoNTe 

`<BigCalendar ...props getNow={() => moment().toDate()} />`
