### ISSUE TITLE
Browserify: Error: Cannot find module 'react-big-calendar' from 'C:\Users\ernest\PhpstormProjects\reactcalendar'

### ISSUE THREAD

**Issue by nene96** [intljusticemission/react-big-calendar#124]
Hi, I'm new on react and i'd like to install you component on my project. I installed you component, run the command `browserify -t babelify index.js -o bundle.js` but it gave me this error: `Error: Cannot find module 'react-big-calendar' from 'C:\Users\ernest\PhpstormProjects\reactcalendar'`. My `.babelrc` file look like this: 
`{
  "presets": ["es2015", "react"]
}`
Can you help me to resolve the problem?

**Comment by jquense** [comment]
the error looks like it's in your code or build step... there isn't much for me to work on though here. make sure you installed the component from npm correctly and That your index. js kid requiring it correctly

**Comment by nene96** [comment]
I deleted the `node_modules` folder, reinstalled all the components with `npm install` and now it works!
