### ISSUE TITLE
Bug: Drag and Drop: Drag Preview not shown

### ISSUE THREAD

**Issue by bminer** [intljusticemission/react-big-calendar#1240]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?

As you *very slowly* drag a calendar entry (i.e. directly down), it will enter the `interacted` state and hide itself (opacity: 0 CSS rule), but the drag preview (rendered by EventContainerWrapper) will not display until you drag the event a bit farther.  This causes an undesirable effect from a UI perspective, but it can also cause the drag and drop code to enter an unexpected state.

It is possible if you drag very little and very quickly (i.e. double click a lot while slightly dragging) that the event will disappear even though you don't have the left mouse button down anymore.  This is because the DnD addon thinks we are still in "drag mode", but we're actually not anymore.

My hunch is that the event handlers on the `selector` in the `_selectable` function in `EventContainerWrapper` need to consider this edge case somehow.

I'm running Chromium Version 71

Sample of broken behavior: http://intljusticemission.github.io/react-big-calendar/examples/index.html#dnd (go to weekly view and drag and drop as described above)

#### What's the expected behavior?

It would be nice if the drag preview was shown immediately (i.e. as soon as the `interacting` state is entered by the `EventWrapper`) using the event start/end date of the event currently being dragged... *before* the `selector`'s `selecting` event calls `handleMove` or `handleResize` in `EventContainerWrapper`.  See here: https://github.com/intljusticemission/react-big-calendar/blob/master/src/addons/dragAndDrop/EventContainerWrapper.js#L136-L142

My hunch is that the event handler for 'selectStart` needs to be updated.

https://github.com/intljusticemission/react-big-calendar/blob/master/src/addons/dragAndDrop/EventContainerWrapper.js#L144

This is just one implementation idea... there are probably others, perhaps far better ones.

Thanks in advance for a really cool calendar component!  Fixing this bug will help everyone using DnD.  If you need any help from me, I'd be happy to submit a PR.  I just need some pointers on how I should go about fixing it.

**Comment by TomasHubelbauer** [comment]
You described the calendar entering an unexpected state here. I have not exactly a similar issue but maybe a related issue nonetheless in #1227.

**Comment by bminer** [comment]
Anyone have any ideas why this might happen?  This is still an issue, and I can make a video to prove it if needed.

**Comment by bminer** [comment]
Apparently no one cares... oh well... the bug doesn't happen often anyway. I'd love to help fix, but I'm not exactly sure where to start.
