### ISSUE TITLE
onSelectSlot not called when slot ends at 11:59pm

### ISSUE THREAD

**Issue by pjkp** [intljusticemission/react-big-calendar#1242]
#### Do you want to request a _feature_ or report a _bug_?
A bug
#### What's the current behavior?
Since version 0.20.3, we can not create a slot whose end is last of the day (i.e. 11.59 pm)
In previous version 0.20.2, it worked !
The "onSelectSlot" method from BigCalendar component is not launched.

![image](https://user-images.githubusercontent.com/24681759/53746122-d32ad580-3ea0-11e9-84f4-9c3c9f8f562b.png)

#### What's the expected behavior?
The slot should be created, even if it end at 11:59 pm

**Comment by soulclown** [comment]
Same here. Hope somebody will answer.

**Comment by amanmibra** [comment]
I am having this issue as well. Any solutions?
