### ISSUE TITLE
On Click for day (including for mobile)

### ISSUE THREAD

**Issue by cbichis** [intljusticemission/react-big-calendar#1243]
Hello,

I think react-big-calendar is missing an event for clicking (mouse click or touchscreen click) or double clicking on day background, usable for mobile. So a click on: rbc-day-bg.

selectable={true}
onSelectSlot={this.onSlotSelect}
onDrillDown={this.onDrillDownClick}
`
Currently onSelectSlot work at click just for desktop use, not for mobile. For mobile to work you need to actually do a selection.

onDrillDown is useful because does this on mobile, but just for the area of day number... We need something for all the day box...

This is similar with https://github.com/intljusticemission/react-big-calendar/issues/1222

**Comment by ktmn** [comment]
It seems this line is preventing the click from working on mobile:

https://github.com/intljusticemission/react-big-calendar/blob/473d886f34e561f25bec516360a373af39840150/src/Selection.js#L175

I commented it out and now both `click` and `select` actions trigger for `onSelectSlot` (in `week` mode).
Not sure what side effects it causes though.

**Comment by ParthPatel-DA** [comment]
> It seems this line is preventing the click from working on mobile:
> 
> [react-big-calendar/src/Selection.js](https://github.com/intljusticemission/react-big-calendar/blob/473d886f34e561f25bec516360a373af39840150/src/Selection.js#L175)
> Line 175 in [473d886](/intljusticemission/react-big-calendar/commit/473d886f34e561f25bec516360a373af39840150)
>  this._onInitialEventListener.remove() 
> I commented it out and now both `click` and `select` actions trigger for `onSelectSlot` (in `week` mode).
> Not sure what side effects it causes though.

@ktmn I have already commented this line. It's works fine in Android devices, but it's not worked in IOS devices. Please give suggestion, if any.

**Comment by sahar922** [comment]
@ParthPatel-DA happen also for me..
any suggestions?
