### ISSUE TITLE
Add ability to remove link in the month day's date number

### ISSUE THREAD

**Issue by manutenfruits** [intljusticemission/react-big-calendar#125]
So I'm using this calendar but don't have a `day` view, only `month` and `week`. The link in the date number in the month view (namely [this `<a>` guy](https://github.com/intljusticemission/react-big-calendar/blob/master/src/Month.jsx#L251)) doesn't make sense if there's no day view, so I'd like to add an option to remove it. I'm happy to post a PR, but can't think of a good prop name or type to add.

**Comment by s-taylor** [comment]
I'm having an issue with this at present as well, we have no use for the day view and have restyled the calendar to make the day large and in the centre of the cell. But this then means the onSelectSlot event doesn't fire when you click on the numbers. Ideally I'd like to be able to specify an event for this like `onSelectDay` or something similar, I could then just set it to the same function.

**Comment by Pandakls** [comment]
You can fix it with : 
```javascript
.rbc-date-cell > a{
  pointer-events: none;
}
```

This will disable the onclik on the days!

**Comment by s-taylor** [comment]
Thanks, we were able to work around using z-index to push the a tag behind the cell so the cell was always clicked. I still think it would be great if you could control the event fired by clicking the `<a>` tag specifically though.
