### ISSUE TITLE
We are stuck on 0.19.2 can you run a release with your changes?

### ISSUE THREAD

**Issue by GearoidCollins** [intljusticemission/react-big-calendar#1253]
We really want to update to the latest V, is it possible to release a version with this fix in it?
https://github.com/intljusticemission/react-big-calendar/blob/473d886f34e561f25bec516360a373af39840150/src/utils/Resources.js#L13

**Comment by WarpSpade** [comment]
We need this too

**Comment by dmitrykrylov** [comment]
@GearoidCollins @WarpSpade the new version has been released

**Comment by GearoidCollins** [comment]
@dmitrykrylov awesome, thank you 👍
