### ISSUE TITLE
showMultiDayTimes not working if start and end date are at 0:00 o`clock

### ISSUE THREAD

**Issue by Phibedy** [intljusticemission/react-big-calendar#1257]
version: 0.20.2

It shows the event in the headline like if `showMultiDayTimes` is disabled. If start or end are not at 0:00 o`clock it works like expected.

**Comment by Navaie** [comment]
This should not have the "wontfix" label :( I think having this properly working is especially important for all-day events from 0:00 to 0:00 on another day. Can I help to fix this?

**Comment by tmnrp** [comment]
Any workaround for this yet ?

**Comment by Navaie** [comment]
I think I added a millisecond to the time, to change it to not be exactly 0:00. Not great, but worked back then. Not using it anymore now.
