### ISSUE TITLE
handleRangeChange not triggered when out-of-range date is selected

### ISSUE THREAD

**Issue by sprietNathanael** [intljusticemission/react-big-calendar#1258]
#### Do you want to request a _feature_ or report a _bug_?

Bug (I think).

#### What's the current behavior?

In the month view, when the `date` is changed and it is out-of-range, the month is changed, but `handleRangeChange` is not triggered.

I'm trying to make a month calendar with selectable date. I use `onSelectSlot` callback to catch the day click and make some custom process. Then, it calls `calendarDayChange_handler` to change the date to the one selected.

When the date is out-of-range, the month is automatically changed but `handleRangeChange` is not called.

Here is a working example : https://codesandbox.io/s/7y5y31wrrq?fontsize=14 .

The wanted behaviour is acheived by clicking both `PREV` or `NEXT` buttons, which calls `handleNavigate`, that calls `handleRangeChange`.

I opened a StackOverflow question [here](https://stackoverflow.com/questions/55158552/big-calendar-calling-handlerangechange-when-selected-date-is-out-of-range).

**Comment by logicz** [comment]
For Day view there is similar issue, when you drag begining up to allDay slot it just stick up, but not fire the rangeChange event.

**Comment by logicz** [comment]
up
