### ISSUE TITLE
Importing style throws Unexpected token error

### ISSUE THREAD

**Issue by saravanannnallasamy** [intljusticemission/react-big-calendar#1263]
#### What's the current behavior?
when I import styles as import "react-big-calendar/lib/css/react-big-calendar.css"; it throws error 'unexpected token' pointing to '.' in first line ('.rbc-btn{' ) in react-big-calendar.css

![image](https://user-images.githubusercontent.com/25293768/54734770-fc997000-4bc7-11e9-9bfc-911879dab4eb.png)

var BigCalendar = require('react-big-calendar');
import "react-big-calendar/lib/css/react-big-calendar.css";
var moment = require('moment');
var localizer = BigCalendar.momentLocalizer(moment);

this.setState({events:[{
          id: 0,
          title: 'Today',
          start: new Date(new Date().setHours(new Date().getHours() - 3)),
          end: new Date(new Date().setHours(new Date().getHours() + 3)),
        }]
    });
              <BigCalendar
                localizer={localizer}
                events={this.state.events}
                defaultDate={new Date()}
                defaultView="month"
                onSelectEvent={event => alert(event.title)}
                views={['month']}
              />
"react": "^15.0.0"
"react-big-calendar": "^0.20.3"

**Comment by jquense** [comment]
I don't really no anything about your build system but the problem seems to be there. The css file isn't malformed, it works when used normally

**Comment by saravanannnallasamy** [comment]
Its related to importing css file in my jsx file. I have fixed it again there is error and the calendar is not completely loaded

![image](https://user-images.githubusercontent.com/25293768/54805642-9252ff00-4c9d-11e9-953d-0d3c068ddd49.png)
