### ISSUE TITLE
custom min and max to each day of the week

### ISSUE THREAD

**Issue by timmyfrade** [intljusticemission/react-big-calendar#1266]
Hey guys! 

At the moment, min and max prop are supported to everyday of the week to have the same schedule, from 9am to 5pm for example. Is there any way to customize this for each day of the week? (eg. monday: 09am - 5pm, tuesday: 07am - 11pm, wednesday: 06am - 6pm, etc)

Thanks!

**Comment by dmitrykrylov** [comment]
@timmyfrade how you imagine it has to look like? If you want to have different scales for different days, it's just doesn't look nice. You should better set the widest period for min/max props (in your case it's 6am-11pm) and play with appearance and behavior of your "non-working" timeslots using `slotPropGetter` prop

**Comment by timmyfrade** [comment]
Yeah, i was thinking something like you said, like working with the appearance for non-working slots. Thanks!
