### ISSUE TITLE
.rbc-off-range and .rbc-off-range-bg don't allow styling of .rbc-event 

### ISSUE THREAD

**Issue by josh-g3** [intljusticemission/react-big-calendar#1269]
#### Do you want to request a _feature_ or report a _bug_?
I'm not sure which one this falls under

#### What's the current behavior?
.rbc-off-range/.rbc-off-range-bg don't have a parallel class inside of .rbc-row-content. This keeps me from de-emphasizing events that are in the view but fall outside of the current month so that they look similar to their grayed-out containers.

#### What's the expected behavior?
There should be a way to style these events.

**Comment by deep1man3** [comment]
Upd: i need this feature
