### ISSUE TITLE
Not able to load style

### ISSUE THREAD

**Issue by rodrimaqui** [intljusticemission/react-big-calendar#1272]
Hi guys i  have this problem. I import the syles but doesnt work:
![show](https://user-images.githubusercontent.com/13734394/55262154-b25d6200-524b-11e9-9804-67a90ee2c764.png)

my code is this:

![component](https://user-images.githubusercontent.com/13734394/55262169-be492400-524b-11e9-9f61-d7430f0b2133.png)

thanks

**Comment by rfrabasile** [comment]
If using webpack, do you have proper css webpack loaders? 
i.e.: {
            test: /\.(css|less)$/,
            use: ['style-loader', 'css-loader']
        }

**Comment by rodrimaqui** [comment]
> If using webpack, do you have proper css webpack loaders?
> i.e.: {
> test: /.(css|less)$/,
> use: ['style-loader', 'css-loader']
> }

I dont use webpack, i really need to use it?

**Comment by rfrabasile** [comment]
Not really. But it seems like a problem loading the react-big-calendar.css.
Make sure you are loading it right, maybe check for errors in the logs or use "inspect element" on your browser to see console and styles.

**Comment by rodrimaqui** [comment]
> Not really. But it seems like a problem loading the react-big-calendar.css.
> Make sure you are loading it right, maybe check for errors in the logs or use "inspect element" on your browser to see console and styles.

I gonna try with webpack.

Gracias!!

**Comment by arecvlohe** [comment]
@rodrimaqui This does seem like a webpack/import issue and not one related to react-big-calendar. Closing.

**Comment by HasanYousef** [comment]
I have the same issue, do you use Next.js like me?
