### ISSUE TITLE
onRangeChange is called twice from handleDrillDown

### ISSUE THREAD

**Issue by chachora** [intljusticemission/react-big-calendar#1275]
#### Do you want to request a _feature_ or report a _bug_?
bug
#### What's the current behavior?
`handleDrillDown` calls `onRangeChange` twice when you click on day header in Month View, first with `'day'`" as view argument and secondly with `undefined`.
It happens because `onRangeChange` will be called firstly from this line

 `if (view) this.handleViewChange(view)`

Secondly from this line 

`this.handleNavigate(navigate.DATE, date)`

Full method source code [here](https://github.com/intljusticemission/react-big-calendar/blob/4c369617fe6e26470cbf67de5e4f83830eb1036d/src/Calendar.js#L985)
#### What's the expected behavior?
`onRangeChange` should be called only once with correct view argument

**Comment by seblaz** [comment]
Hi,
I've come across this issue as well. Is there any workaround?

**Comment by ZakRabe** [comment]
Hey, came across this bug in 2020. The solution I ended up choosing was to use the calendar in a controlled manner, and using the onDrillDown prop. to change the view/date manually in my component scope.

this exits the handleDrillDown method early, and avoids hitting the code below that causes the duplicate calls to onRangeChange

```
handleDrillDown = (date, view) => {
    const { onDrillDown } = this.props
    if (onDrillDown) {
      onDrillDown(date, view, this.drilldownView)
      return
    }
    if (view) this.handleViewChange(view)

    this.handleNavigate(navigate.DATE, date)
  }
```
