### ISSUE TITLE
TimeColumn takes all the screen space

### ISSUE THREAD

**Issue by pedrolcalderon** [intljusticemission/react-big-calendar#128]
Hi,

First of all, amazing library!

When I open my page directly to the week or day views I have all columns collapsed and the component TimeColumn takes almost all the available space. Like the image bellow.

<img width="1280" alt="screen shot 2016-07-01 at 00 29 29" src="https://cloud.githubusercontent.com/assets/8545587/16511122/3682adae-3f23-11e6-9fdd-ab7aa63e879e.png">

If I change views this is fixed. For exemple if I start with the week view and then change to day view, the day one is correctly displayed.

The screenshot was taken from a dummy experiment, without any styling, just the calendar. But this behavior is reproduced independent from the styling.

I found that the code causing my problem was introduced as a fix to [issue 16](https://github.com/intljusticemission/react-big-calendar/issues/16).

I could not find a solution in any previous issue nor in the docs.

**Comment by Joramt** [comment]
Simply wrap it in a container and style this container ?

**Comment by pedrolcalderon** [comment]
@Joramt it was initially inside a [Paper element, from Material-UI](http://www.material-ui.com/#/components/paper). It had the same problem.

I tried to wrap it with a div but it didn't work for me. I tried setting the width, display and position, but could not fix the problem. Is there a specific configuration that my parent div need to have?

**Comment by jquense** [comment]
can you reproduce the issue somewhere I can look at it?

**Comment by pedrolcalderon** [comment]
Hi @jquense,

I've created a minimal example and uploaded to [this repo](https://github.com/pedrocalderon/react-big-calendar-bug-exemple) with the exact same behavior.

But if you don't want to have the trouble to clone the repo, this is all 'non boilerplate code':

```
import React, { Component } from 'react';
import BigCalendar from 'react-big-calendar'
import moment from 'moment'

BigCalendar.momentLocalizer(moment)

const style = {
  position: 'absolute',
  right: 0,
  left: 0,
  top: 0,
  bottom: 0,
}

export default class App extends Component {
  state = {
    view: 'week'
  }
  render() {
    return (
      <div style={style}>
        <h1>Change view to 'day' than back to 'week'</h1>
        <BigCalendar
          events={[]}
          defaultView="week"
        />
      </div>
    );
  }
}
```

Entering this page results in a broken calendar view, changing the view and going back to 'week' fix the problems.

For what I could tell is a problem with the logic in the measureGutter function from the TimeGrid in the first render.

**Comment by jquense** [comment]
that looks like it would render a zero dimension calendar...which may be the problem.

**Comment by pedrocalderon** [comment]
The calendar is full screen in the example I pasted here.

How do I fix the 'zero dimension calendar' problem?

**Comment by arthurvi** [comment]
Any solution yet for this bug? I'm having it as well.

**Comment by mawek** [comment]
is there some workaround for this issue? I'm experiencing it too.

**Comment by pedrocalderon** [comment]
I'm sorry by I didn't find a solution.

**Comment by abury** [comment]
I'm getting this as well. Happens every time on the first render.

**Comment by SunnySs** [comment]
![image](https://cloud.githubusercontent.com/assets/11607625/22397272/00a81ce6-e5a9-11e6-9adb-1d21bbac796c.png)
I am also getting this kind of problem too.

`import React from 'react';
import BigCalendar from 'react-big-calendar';
import events from '../../utils/event';

let Basic = React.createClass({
  render(){
    return (
      <div >
        <BigCalendar
          {...this.props}
          events={events}
          defaultDate={new Date(2015, 3, 1)}
          />
      </div>
    )
  }
})

export default Basic;
`

**Comment by jquense** [comment]
@SunnySs your problem is that you don't have the css included.

Everyone for this usse, see my comment here: https://github.com/intljusticemission/react-big-calendar/issues/278#issuecomment-274095048 for the cause of the problem and workaround. 

I'm not sure there is anything we can do here to address it
