### ISSUE TITLE
Fix DnD for multiday events to not cut end date

### ISSUE THREAD

**Issue by xtursky** [intljusticemission/react-big-calendar#1285]
#### Do you want to request a _feature_ or report a _bug_?

Bug / Question

#### What's the current behavior?

Currently it's not possible to DnD multiday event (in case of showMultiDayTimes=true). When dragging starts, end time is limited to end of current day by this line of code https://github.com/intljusticemission/react-big-calendar/blob/475674c6167391bd6212c1247fa29c1aea4c1b00/src/utils/TimeSlots.js#L129

@jquense question, is this just some safety done before DnD was introduced, or does it have it's meaning?

If this line is ignored, DnD seems to work for both one day and multiday events. End time is correctly calculated. Only small issue is, that only first day is visualized while dragging, but that I can live without.

#### What's the expected behavior?
To be able to DnD multiday event (in case of showMultiDayTimes=true) correctly. So the start and end time are not limited to the current day.

**Comment by arecvlohe** [comment]
@xtursky This seems like it would be an easy fix if your solution above works. Mind submitting a PR?

**Comment by xtursky** [comment]
@arecvlohe thanks for info. No problem to create a PR.
As I asked above, not sure if this is needed when DnD is not used.
So I wasn't sure if to change this generally or just for DnD addon. I'll prepare PR, test it and we will see.

**Comment by felgeekpe** [comment]
@xtursky hi, any updates on the fix? Thanks!

**Comment by xtursky** [comment]
@felgeekpe yeap, there is already PR waiting for review, just didn't reference it correctly. Thanks for asking.
