### ISSUE TITLE
How can I get current target?

### ISSUE THREAD

**Issue by hojihun5516** [intljusticemission/react-big-calendar#1286]
#### Do you want to request a _feature_ or report a _bug_?
request a _feature

#### What's the current behavior?
I want to get a current target when I press the date td to use popper.

#### What's the expected behavior?
I couldn't find current target

Can you help me if it's a light problem?

**Comment by arecvlohe** [comment]
@hojihun5516 I think if you wanted to do this you would need to fork the library and add in this special functionality.

**Comment by jquense** [comment]
attach a onClick to the container and check `target`

**Comment by kauly** [comment]
@jquense  this really work, thanks. 
`elementProps={{ onClick: e => console.log(e.target) }}`
