### ISSUE TITLE
Timezone change week/day view bug

### ISSUE THREAD

**Issue by Grosscorp** [intljusticemission/react-big-calendar#1287]
#### Do you want to request a _feature_ or report a _bug_?
bug

#### What's the current behavior?
The current behavior is that if you change the timezone on your machine, week/days hour rows will be collapsed.

The bug can be tracked on Big Calendar [DEMO and Docs](http://intljusticemission.github.io/react-big-calendar/examples/index.html).

A bug screencast added.
![big-calendar](https://user-images.githubusercontent.com/33066126/56189635-18f6c400-6031-11e9-8e62-475aa88a0a1d.gif)

#### What's the expected behavior?
The expected behavior is that week/days hour rows won't be collapsed.

**Comment by arecvlohe** [comment]
@Grosscorp Is this a bug or an issue with implementation? Seems like it would not be common for someone using the app to change their timezone in the middle of using it. Does it work on refresh?

**Comment by Grosscorp** [comment]
@arecvlohe I'm sorry, I'm not sure whether it is a bug or issue with implementation, but I think its a bug. Yes, I agree it's not a common case of usage, and this bug is hard to catch and test, but we can think of it like timezone can change automatically in the middle of usage, and then this bug can occur. Yes, it's work on refresh, but we creating SPA with react, and we want to avoid update in our web application, maybe some other solution can be found and it can improve this great project. Thank you.

**Comment by arecvlohe** [comment]
@Grosscorp Thanks for the feedback. Because of the narrowness of the issue it probably won't be something library authors can address any time soon. We are open to accepting a PR if you want to give it a try! Closing the issue for now.
