### ISSUE TITLE
Agenda Custom Table Rows

### ISSUE THREAD

**Issue by nicolasriccardi** [intljusticemission/react-big-calendar#1288]
Hi to all,

I searched a lot and couldnt find nothing about this. Found out about customs headers or date range, but not much more than that.
Actually what im trying is to modify agenda table. I realized that I can pass to 

```
components={{
                agenda: {
                  event: CardAgendaCalendarSession
                 }
              }}
```

a custom component for the event row, also, I can change event to time or date, and those rows would render my custom component. 
My question if it is possible to add a custom row, like 

```
components={{
                agenda: {
                  myCustomRowName: myCustomComponent
                 }
              }}
```

Thanks for reading.

**Comment by jquense** [comment]
its not possible to add a custom Row, you can add a custom Agenda view but you'd have to write most of it over

**Comment by paulhuisman** [comment]
@jquense Do you have an example of how to add a custom Agenda view?

**Comment by ChrisLanks** [comment]
For future reference:
https://github.com/jquense/react-big-calendar/blob/master/examples/demos/customView.js

**Comment by MightyVivekKolkatta** [comment]
> For future reference: https://github.com/jquense/react-big-calendar/blob/master/examples/demos/customView.js

page not found

**Comment by cutterbl** [comment]
@MightyVivekKolkatta You're right, the documentation has been updated. See [this guide to Custom Views](http://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/guides-creating-custom-views--page) which links to the example. The example has links to source code.
