### ISSUE TITLE
Bug: Delayed CSS loading

### ISSUE THREAD

**Issue by moyamanuel** [intljusticemission/react-big-calendar#1291]
Hey y'all, I seemed to run across a bug.

For reference, I am using GatsbyJS v2 as the framework for the web application I am building, so the issue may lie in there. 

Browser: Firefox 66.0.3 (64-bit)
React-Big-Calendar: v20.4

#### What's the current behavior?

Link to current behavior: [here](https://manuelmoya.me/si)

When deploying the production build to Netlify, the CSS for React-Big-Calendar seems to load _**after**_ page load. I've tried a number of things to mitigate the issue, which you can view over at [here](https://github.com/moyamanuel/cs11-si-website/pull/2). Initially, I thought it was due to not having a componentDidMount() method, but I've added one since then and it still produced the same result.

#### What's the expected behavior?

The CSS should load smoothly, along with the rest of the page.

**Comment by perrypelletier** [comment]
Actually experiencing a similar problem where the page loads in an un-styled manner and then quickly updates to the correct layout. You can see this when you reload the sample on the react-big-calendar demo/docs page. Anyone have a way to correct/mitigate?

**Comment by arecvlohe** [comment]
@moyamanuel @perrypelletier Have you thought about preloading that CSS instead of having it load as the page loads?

**Comment by moyamanuel** [comment]
No, I have not, @arecvlohe. It seems like GatsbyJS already does that according to the [docs](https://www.gatsbyjs.org/docs/how-code-splitting-works/). Is there an explicit way to preload the CSS?

**Comment by arecvlohe** [comment]
What about using link plus preload? https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content

**Comment by arecvlohe** [comment]
Closing since this is a loading/bundling issue and not a calendar issue.
