### ISSUE TITLE
Wrong widths of events in some cases

### ISSUE THREAD

**Issue by kashesandr** [intljusticemission/react-big-calendar#1295]
#### What's the current behavior?

If events are:
```
[
  {
    title: "Event 1 title",
    start: new Date(2019, 0, 0, 8, 0),
    end: new Date(2019, 0, 0, 8, 25)
  },
  {
    title: "Event 2 title",
    start: new Date(2019, 0, 0, 8, 25),
    end: new Date(2019, 0, 0, 8, 55)
  }
]
```

I see wrong widths of events:

![image](https://user-images.githubusercontent.com/1232754/56665120-1db31c00-66b2-11e9-8a84-3f3f87945d48.png)

Example:
https://codesandbox.io/s/0pw408l7rl

react 16.5.2
react-dom 16.5.2
moment 2.22.1
react-big-calendar 0.20.3

#### What's the expected behavior?

Events should have 100% width of the relevant cell. 

If events are:
```
[
  {
    title: "Event 1 title",
    start: new Date(2019, 0, 0, 8, 0),
    end: new Date(2019, 0, 0, 8, 30)
  },
  {
    title: "Event 2 title",
    start: new Date(2019, 0, 0, 8, 30),
    end: new Date(2019, 0, 0, 9, 0)
  }
]
```

everything works fine:

![image](https://user-images.githubusercontent.com/1232754/56666754-21946d80-66b5-11e9-8ce5-c8678d13baf2.png)

**Comment by jquense** [comment]
@arecvlohe do you know if this is still an issue, I think this has something to do with how events are chunked up when laid out? I thought it was fixed tho

**Comment by arecvlohe** [comment]
@jquense I just checked out the code sandbox and updated the rbc dep to the latest and it was still laying out incorrectly. That's weird. I adjusted the times slightly and it still doesn't go away.

**Comment by schester44** [comment]
I have this same issue. Events that are 2 minutes apart are considered to be on the same line which causes 'incorrect' rendering.

example:
<img width="456" alt="Screen Shot 2019-08-04 at 11 22 14 PM" src="https://user-images.githubusercontent.com/15207595/62436824-dc012b00-b70e-11e9-86c2-14fdfd5597bc.png">


I've gotten around it by overriding the `left` and `width` properties of `.rbc-event` but it's not an ideal solution.
