### ISSUE TITLE
Add prop to show/hide weekend day columns

### ISSUE THREAD

**Issue by jgautsch** [intljusticemission/react-big-calendar#130]

**Comment by krokofant** [comment]
A workaround could be to hide the content via formatters like so
```
formats={{
  dayFormat: () => "",
  weekdayFormat: () => ""
}}
```

**Comment by oskareke** [comment]
+1

**Comment by panzupa** [comment]
This request is over one year old, however, it would be nice to have such option. Is it possible to hide weekends columns (on month and week view)?
