### ISSUE TITLE
event bug after resize

### ISSUE THREAD

**Issue by gustavomo** [intljusticemission/react-big-calendar#1300]
#### current behavior
When you change the size of a reminder, it duplicates the selected reminder in the interface

before resize
![Screen Shot 2019-05-03 at 8 12 43 AM](https://user-images.githubusercontent.com/30153075/57139593-4eaee300-6d7b-11e9-90e0-627725af3f12.png)

after resize
![Screen Shot 2019-05-03 at 8 13 00 AM](https://user-images.githubusercontent.com/30153075/57139610-55d5f100-6d7b-11e9-9288-b1d212e75740.png)

#### expected behavior
that not have duplicates

react: 16.3.0
react-big-calendar: 0.20.4
browser: chrome

**Comment by tuancaraballo** [comment]
Thank you guys for the great work. I'm also running into the same bug

**Comment by tuancaraballo** [comment]
I'm running into the same issue, but in the week view. For me, no events are duplicated in the this.state.events, but the UI shows several copies.

**Comment by Lakshit-Singhal** [comment]
@gustavomo  Can you help me out with rendering events with different colors as you have in your application ? , As i want something similar to that in my application.

**Comment by gustavomo** [comment]
@Lakshit-Singhal

1. shoudl add the prop

```eventPropGetter={this.eventStyle}```

2. define a function for get the events datas
```
eventStyle(event, start,end,isSelected, ) {
    return {
      style: {
        backgroundColor: event.color
      }
    }
}
```

3. and in the events add the styles that you wanna customize

```
  {
    id: 14,
    title: 'Today',
    start: new Date(new Date().setHours(new Date().getHours() - 3)),
    end: new Date(new Date().setHours(new Date().getHours() + 3)),
    color: 'red'
  }
```

**Comment by schester44** [comment]
you can style the original event via the `.rbc-addons-dnd-dragged-event` class. You can hide it all together using opacity, display, or any other similar CSS property.
