### ISSUE TITLE
expose default components

### ISSUE THREAD

**Issue by yanglin5689446** [intljusticemission/react-big-calendar#1304]
#### Do you want to request a _feature_ or report a _bug_?
feature request

#### What's the current behavior?
The default components are not exported.

#### What's the expected behavior?

Is it possible to export the default components?

It would be really helpful when there's a need to override the UI,
just extends the components class and overrides the render function without knowing the internal API such as the static methods inside the view components.

**Comment by arecvlohe** [comment]
@yanglin5689446 I don't think this will be supported but also it's easy enough to copy the components from the library and use them as custom components. Closing for now.

**Comment by yanglin5689446** [comment]
First, copy the whole component just to modify the render function seems a little bit dumb, it reproduces many duplicate code.

Second, the default components can't be copied and run painlessly, it couple with many internal used import (`utils` and `constants`, for example). it's a pity that you expose an API to override UI components but actually we can't use it because these internal coupling, so I suggest that either expose the components or those utils/constants. I believe that exposing the component should be easier.

**Comment by fyodore82** [comment]
First of all, thank you for React Big Calendar! It is very powerful library
I would also support this feature request.
One of the primary design concept of React is composition. We create components that represent UI elements and then compose them, i.e. call child components from parents. This allows to easily reuse components and develop very sophisticated UI w/o loosing code clarity.
I think React Big Calendar will win if it export all internals. Users will be able to reuse smaller parts of the Big Calendar to create non-standard calendars, and even commit additional 'building blocks' to the library.

For example, I faced a requirement to display calendar weekly view with resources. But events should be first grouped by date and then by resource, like below
```
|        03/21/2023       |        03/22/2023       |       03/23/2023        |
| resource 1 | resource 2 | resource 1 | resource 2 | resource 1 | resource 2 |
|  event1    |  event 2   |            |            |            |            | 
```
From the [source ](https://github.com/jquense/react-big-calendar/blob/76be38e0c575830c2998648571716b665cd0733c/src/TimeGrid.js#L100)I see that Big Calendar always group first by resource and then by day.

If React Big Calendar will export it internals, it will be more like React itself. React developers do not answer how to build that form or table, they just expose building blocks (hooks, rendering engine, etc) and best practices of how to use them. So anyone can build whatever he/she wants.

**Comment by coopbri** [comment]
@yanglin5689446 @fyodore82 did either of you figure out a clean way to implement this? Or is brute force "backfilling" the default components the way to go?

**Comment by fyodore82** [comment]
The idea is to use composition as much as possible.
So usage of the calendar component should be somewhat like this (I have omitted props for bravery and assumed that all components below are exported from React Big Calendars, so user will not have to write them manually)
```
<CalendarLayout>
  <CalendarToolbar />
  {headers.map(header => (
    <TimeGridHeader />
    {header.timeslots.map(timeslot => (
      <TimeGutterWrapper>
        {timeslot.groups.map(group => (<RenderSlot />))}
      </TimeGutterWrapper>
    ))}
  ))}
</CalendarLayout>
```
As a result it will be possible to either use standard components that come with calendar or replace components with there own. Additionally it will be possible to compose not standard calendars using provided standard components.
This approach most probably require use of custom hooks or helpers to extract business logic out of the calendar.
