### ISSUE TITLE
How to send the date of calendar to another calendar with Reactjs?

### ISSUE THREAD

**Issue by IchrakMansour** [intljusticemission/react-big-calendar#1305]
I have two calendars, such as the Agenda, have an icon calendar button, when I click on it, it will be redirected to another calendar (Planning), these calendars are developed with react-big-calendar, I want when I navigate for example on the week of `juin 17 - 23` of Agenda and I click on the icon calendar, it will be redirected to `juin 17 - 23` of the Planning.

My code is : https://codesandbox.io/s/m7k904y3o8

I try to send the date with `getWeek()`, but it doesn't work.

How can I fix it ?

**Comment by jquense** [comment]
pass a **date** in the week you want to the calendar's `date` prop
