### ISSUE TITLE
onDragStart missing from withDragAndDrop

### ISSUE THREAD

**Issue by bassplayerch** [intljusticemission/react-big-calendar#1306]
After installing the latest version of react-big-calendar I noticed that onDragStart is missing from the dnd addon. If I manually copy the latest version from github (the addons/withDragAndDrop.js file) it works.

Maybe you need to update the version on npm?

**Comment by arecvlohe** [comment]
@bassplayerch Releases can happen infrequently so best to pull the latest from the GitHub repo is necessary. Closing for now.
