### ISSUE TITLE
Also Provide SASS Files For Theming

### ISSUE THREAD

**Issue by cutterbl** [intljusticemission/react-big-calendar#1312]
#### What's the current behavior?

Currently, a developer seeking to 'theme' react-big-calendar can only do so using LESS.

#### What's the expected behavior?

Developers should be able to 'theme' react-big-calendar using whichever style compiler their application prefers, be it LESS or SASS.

#### Solution

I've submitted PR #1235 for this. It provides source SASS files, with style parity to the LESS implementations, additional `script` entries for building from SASS, plus adjustments to the `assets` scripts to also copy over SASS source to the `lib` folder at build time.

**Comment by stunaz** [comment]
must be closed?
