### ISSUE TITLE
Allow Multiple events at the same time side by side like the picture below

### ISSUE THREAD

**Issue by khuramdogar** [intljusticemission/react-big-calendar#1314]
#### Do you want to request a _feature_ or report a _bug_?
Both
#### What's the current behavior?
events are overlapping with each other.

![image](https://user-images.githubusercontent.com/15875273/57450119-132e8000-7277-11e9-9a4a-8e642ffb0a25.png)

#### What's the expected behavior?

I am basically copying the calendar below and I want to show multiple appointments at the same time side by side no matter how thin they become. 
### Day View

![image](https://user-images.githubusercontent.com/15875273/57450264-77e9da80-7277-11e9-84ca-33745136eefd.png)

### Week View

![image](https://user-images.githubusercontent.com/15875273/57450367-bbdcdf80-7277-11e9-996b-fa8501716f50.png)

### App Link

https://apps.shedul.com/

### Note

 I have override almost every component in this amazing package `reac-big-calender`. I need this one last piece ASAP.

**Comment by jquense** [comment]
There is some previous discussion on this you can search back for, **tl;dr;** we find the current approach best for most use cases, and are open to making the event layout system configurable, for folks that want very specific layout. 

that said i don't think anyone has the time or desire to implement the api hooks at the moment, so if you need it ASAP the fastest path forward would be to contribute the api's need 👍, feel free to open up a draft PR and folks can talk it through as you work. Alternatively posting a monetary bounty for a feature might get some interest as well.

**Comment by adenta** [comment]
@khuramdogar were you ever able to patch this functionality in yourself?
