### ISSUE TITLE
Run Examples Browser

### ISSUE THREAD

**Issue by cutterbl** [intljusticemission/react-big-calendar#1316]
#### What's the current behavior?

When running the `examples` script, the webpack-dev-server console output tells you that:

- The site is running on 'http://localhost:3000', and
- Content is served from the '/examples' directory

This then requires a user to manually open a browser and navigate to `http://localhost:3000/examples` to actually view the content.

#### What's the expected behavior?

When running the `examples` script, the Examples 'site' should automatically open in the user's default browser.

#### Solution

I submitted PR #1315 to address this issue

**Comment by jquense** [comment]
the current setup is a quick hack to deal with publishing to gh-pages. where the site is served from `/examples` and i never really fixed it

**Comment by cutterbl** [comment]
@jquense Is it possible to change the gh-pages config to serve from `/examples/static`? That keeps the 'built' resources separate from the examples source. If not, I can change it to serve direct from `examples` (gh-pages didn't somehow use that server.js, right?)

**Comment by cutterbl** [comment]
@jquense Second question: When contributing, does the developer have to run the `build:examples` script? Or does CI handle that for you?
