### ISSUE TITLE
How can i  get if a slot/day has an event or not ?

### ISSUE THREAD

**Issue by Lakshit-Singhal** [intljusticemission/react-big-calendar#1318]
Hi, it would be really helpful if anyone could help me out with this !

I wanted to have a functionality in my application where i could know that which dates/slots in the current VIew have an event created and which days/slots have no events created as of now so that custom styling could be applied on those slots.

**Comment by jquense** [comment]
There isn't an API for this, the simplest way to check is to look at your events array and see if there is anything that overlaps
