### ISSUE TITLE
Bug: Examples don't work in Internet Explorer

### ISSUE THREAD

**Issue by PzYon** [intljusticemission/react-big-calendar#1320]
I am encountering issue #1284 in Internet Explorer. I would like to try and fix it. 

When running the examples I get an exception related to the usage of `Object.entries` in `App.js`. Even when i fix that by using `Object.map` I still get errors:

![image](https://user-images.githubusercontent.com/9199378/57600969-9132a580-755b-11e9-936f-950461083bb9.png)

Question is am I doing something wrong? I.e. do I need to build differently in order for the examples to work on IE or is this also a real issue? The examples work in Chrome for example. I am running the examples using `yarn run examples`.

**Comment by jquense** [comment]
The examples site isn't built to support IE at the moment,so that makes sense that you're hitting issues on the site specifically.

**Comment by PzYon** [comment]
Ok, I understand. But then I guess it would make sense to make the examples work in IE too in order to make it easier to fix IE problems. I will have a look at this if I find the time. Thanks for you answer.

**Comment by PzYon** [comment]
@jquense, I obviously got some of the examples to work in IE by adding some polyfills (`import '@babel/polyfill';`) as the first line in `App.js`.  Not sure if this is what is actually desired, but at least it works for me at the moment.

Anyway, I'm just wondering who loads these polyfills when not using the examples? Or does this need to be done by the dev using react-big-calendar and not by react-big-calendar itself. Or is it done by babel that transpiles the code to ES5 or something..?

You mentioned that the examples site isn't built to work in IE. Why not? I mean what's the restriction? Is it simply the usage of JS functionalities that aren't supported in IE in the examples themselves or is it the way the app is bundled (webpack vs rollup) or what's the precise reason for this?

Sorry for these maybe stupid questions, but I'm trying to get an understanding of how all of this works.

**Comment by jquense** [comment]
> Anyway, I'm just wondering who loads these polyfills when not using the examples?

Polyfills, as a best practice, are always loaded by the app dev, libraries shouldn't include them, since they pollute the global scope and my not be relevant depending on the users browser support needs.

> You mentioned that the examples site isn't built to work in IE. Why not? I mean what's the restriction? 

There is no technical restriction, I just didn't want to maintain and test the docs site on IE11 since most devs aren't using ie11 day to day
