### ISSUE TITLE
Unable to give custom time slots array.

### ISSUE THREAD

**Issue by ashishcreolestudios** [intljusticemission/react-big-calendar#1328]
As per the custom client requirements, i need to render time slots manually in an array like, 

`
customSlots =['0:00','0:15','1:00','1:30']
`

and i think this library isn't allowing to set the slots like this. any way to overcome this?

**Comment by jquense** [comment]
you can sontrol the `step` which is the distance between tick marks as well as `timeslots` which is the amount of slots per tick. You can't have disconnected or irregular slots tho.

**Comment by ashishcreolestudios** [comment]
Hey @jquense,

 thanks for the reply. the problem here is the interval is not always the same. it should be :

`['0:01','1:15','2:21','4:50']`

**Comment by jquense** [comment]
yes unfortunately that's not possible right now
