### ISSUE TITLE
Expose more functionality when extending components

### ISSUE THREAD

**Issue by krokofant** [intljusticemission/react-big-calendar#133]
Features desired:
* Be able to format the entire event-container including the date ranges
  * Be able to include or exclude the date ranges. The date range on the week could for example be excluded
* Be able to provide classes which will attach on the event-container
  * This would enable one to color format the events differently

I could try to implement this but then I'd need some guidelines

**Comment by jquense** [comment]
Hi there, thanks for the offer to help that's really appreciated, I think we might already have the hooks you want though!

> Be able to format the entire event-container including the date ranges

Sorry not quite sure what you mean here...could you describe what you want a bit more, it might already be possible :) 

> Be able to provide classes which will attach on the event-container
This would enable one to color format the events differently

you want the `eventPropGetter` prop

**Comment by krokofant** [comment]
The eventPropGetter was partly what I was after, thanks.

> Sorry not quite sure what you mean here...could you describe what you want a bit more, it might already be possible :)

<img width="251" alt="calendar_week" src="https://cloud.githubusercontent.com/assets/5908498/16546299/5a5422e2-4146-11e6-91a9-97f7f51d04f2.png">

The above event in the week view I could format by providing my own WeekEvent to the components prop. My code is like the following
```
import React, { Component, PropTypes } from "react";

export default class WeekEvent extends Component {

  static propTypes = {
    event: PropTypes.object.isRequired
  }

  constructor(props) {
    super(props);
  }

  render() {
    return (
      <span>
        {this.props.event.title}
      </span>
    )
  }
}

```

This does seem to give me control over the entire event which includes the portion shown in the image *8:00am — 9:30*. That is something I could like control over :)

**Comment by jquense** [comment]
So you can control that bit, via the `eventTimeRangeFormat`...which seems to be undocumented. But it functions like the other formats,

```
eventTimeRangeFormat={({ start, end }, culture, localizer) => {
  return <span>{localizer.format(start, 'lt') + '-'+localizer.format(end, 'lt')}</span>
})
```

You can return a string or a ReactElement, which gives you pretty good control over it.

**Comment by krokofant** [comment]
@jquense Woho! 😃 I got it to work but I had to change something. I tried to do this which works
```
eventTimeRangeFormat: ({ start, end }, culture, localizer) => {
  return ""
},
```

But then I tried to supply a ReactElement which does not seem to work
```
eventTimeRangeFormat: ({ start, end }, culture, localizer) => {
  return ""
},
```
It produces 
> Uncaught Invariant Violation: `localizer format(..)` must return a string, null, or undefined

When I removed [this line](https://github.com/intljusticemission/react-big-calendar/blob/b67ace34558b6d1c02c927f59dbc2866baba7f8c/src/localizer.js#L14) it started working.

Is this a bug?
