### ISSUE TITLE
Dynamic interval time in timslots

### ISSUE THREAD

**Issue by bhargavcreolestudios** [intljusticemission/react-big-calendar#1331]
#### Timeslots with not same(dynamic) interval time:

As I have found library is providing support for equal timeslots using timeslots and steps feature
like that 

> step={15}
  timeslots={1}

and output will be like :

![time](https://user-images.githubusercontent.com/11331396/58020073-bc516200-7b24-11e9-99ba-1b9cdadbed87.png)

But my requirement is that interval with unequal timeslots
I want to pass array in span of 24 hours duration would be like:

` [0,0.15,0.45,1,1.15,1.45,2,2.15,2.45, … 23.45]
`

It should be render in sidebar where timeslots are visible 
Is it possible ?

**Comment by jquense** [comment]
unfortunately it's not currently possible. tho, you might be able to create something with a custom view yourself

**Comment by regirock365** [comment]
> unfortunately it's not currently possible. tho, you might be able to create something with a custom view yourself

How would one go about creating something like this? @bhargavcreolestudios did you manage to implement this?
