### ISSUE TITLE
Docs for custom components still missing (not detailed)

### ISSUE THREAD

**Issue by pixelass** [intljusticemission/react-big-calendar#1335]
#### Do you want to request a _feature_ or report a _bug_?

documentation

#### What's the current behavior?
 
The documentation does not describe the `components` property.

http://intljusticemission.github.io/react-big-calendar/examples/index.html#prop-components

#### What's the expected behavior?

The documentation should include precise information on components that can be customised.

Instead of just declaring the properties of the `components` object, I'd love to see a more precise documentation.

**This doesn't give a lot of information about the components:**

```
const components = {
    event: MyEvent,
    eventWrapper: MyEventWrapper,
    // ...
}
```

#### linked issues

Some work  seems to have been done here: https://github.com/intljusticemission/react-big-calendar/pull/1092

There was an issue for this: https://github.com/intljusticemission/react-big-calendar/issues/1089

**Comment by jquense** [comment]
Happy to take a PR adding more detailed props 👍

**Comment by pixelass** [comment]
I'll try to create a PR for it.
