### ISSUE TITLE
Duplicated events show up on the ui when an event is created by click and drag, ( duplicated events are not in the events array).

### ISSUE THREAD

**Issue by tuancaraballo** [intljusticemission/react-big-calendar#1336]
#### Do you want to request a _feature_ or report a _bug_?
a _bug_
#### What's the current behavior?
When adding a new event to the calendar by click and dragging, only one event is created, but the UI reflects different copies.

RBC version : 0.21
Browser: chrome 74.0
<img width="1404" alt="Screen Shot 2019-05-21 at 11 41 26 PM" src="https://user-images.githubusercontent.com/16768578/58153563-3583ae80-7c24-11e9-85a6-6225a92e9186.png">
#### What's the expected behavior?
The UI should reflect the current number of events in the state.

**Comment by jquense** [comment]
please provide a working repro

**Comment by tuancaraballo** [comment]
I stopped using this library, but my intuition was that it was triggering two events simultaneously. The most common time I got this bug, was when I was dragging an event over an existing one. Let's say there was an event on Wednesday and I was dragging and dropping an event from Thursday to Tuesday and going over the event on Wednesday. Thank you for reaching out.
