### ISSUE TITLE
How to arrange two type of event 

### ISSUE THREAD

**Issue by datnt1997** [intljusticemission/react-big-calendar#1337]
I want to make two types of all day events. I expect if there isn't any Course event, there will be a hidden event on that space and above Units event

#### What's the current behavior?
![current](https://user-images.githubusercontent.com/14542223/58243232-77266d80-7d7a-11e9-994c-45af43b0537e.PNG)

https://codesandbox.io/s/cevo2

#### What's the expected behavior?
![Capture](https://user-images.githubusercontent.com/14542223/58243121-46decf00-7d7a-11e9-8dd0-4874055a47f8.PNG)

**Comment by jquense** [comment]
Hi, There isn't a way to do that, all day events aren't grouped or categorized, they reuse the component as the Month view week
