### ISSUE TITLE
Week view mode, half hour rows

### ISSUE THREAD

**Issue by LuigiLazzari** [intljusticemission/react-big-calendar#134]
Hi, I'm in need of a feature that I don't think is there out of the box, I need the week view to have times of half an hour instead of only whole hours, is this that something that I can configure or I'll have to alter the source code?

**Comment by jquense** [comment]
I assume you mean that you want each half hour labeled, since the default is half hour sections?

recently we made some changes that aren't documented that should handle this. Try setting `timeslots` prop to 1

**Comment by LuigiLazzari** [comment]
Yeah that's what I meant. By setting timeslots to 1 I get 48 rows, which is what I want, but all of them are blank
