### ISSUE TITLE
Event on Saturday repeating on sunday

### ISSUE THREAD

**Issue by patilrevansidh** [intljusticemission/react-big-calendar#1345]
Versions: 
`"react-big-calendar": "~0.14.4",`
`  "react": "~15.4.2"`

Description:
My events on Saturday repeating on sunday. 
Data:

>  {
> start: {dateTime: "2019-05-04T00:00:00.0000000", timeZone: "UTC"},
> end: {dateTime: "2019-05-05T00:00:00.0000000", timeZone: "UTC"},
> isAllDay: true,subject: "ABC Birthday",
> type: "occurrence" isCancelled: false,
> isOrganizer: true,
> isReminderOn: false,
> }

Events on other days with similar data working properly.

**Comment by jquense** [comment]
please provide a runnable example using the codesandbox template thanks

**Comment by patilrevansidh** [comment]
@jquense 
yes please check this codesanbox : https://codesandbox.io/s/magical-shadow-u5joc
react-big-calendar 0.14.4

**Comment by jquense** [comment]
You are using a very old version. if you upgrade it works: https://codesandbox.io/s/epic-goldstine-yz10u

**Comment by patilrevansidh** [comment]
yeah, I tried this. Problem to switch to new version is I'm using React 15. So it will throw error
