### ISSUE TITLE
Override Today,Next and Prev button

### ISSUE THREAD

**Issue by nibiru2O12** [intljusticemission/react-big-calendar#1346]
#### Do you want to request a _feature_ or report a _bug_?
Feature

#### What's the current behavior?

Navigation to next or previous month is by clicking the  "Next" or "Back" button.

#### What's the expected behavior?

Can the button "Today","Next" and "Back" button be override?.
I want to control the navigation using mouse wheel.

** what i'm currently doing right now is hiding the toolbar through css styling then add my custom toolbar

**Comment by jquense** [comment]
you can add a custom toolbar by setting toolbar to a component in `components` prop

**Comment by rjworks** [comment]
> `components`

Thanks! Where can I find the props?
