### ISSUE TITLE
Possible to create custom view

### ISSUE THREAD

**Issue by nirchernia** [intljusticemission/react-big-calendar#135]
Currently you can specify a range of views:

> 
> views
> An array of built-in view names to allow the calendar to display.
> 
> type: Calendar.views
> 
> default: ['month', 'week', 'day', 'agenda']

Is it possible to create your own view tab? Say I wanted to have `['month', 'week', 'day', 'agenda',  status ]` where `status `was able to render its own component. 

Thanks again

**Comment by jquense** [comment]
yup, though its a bit undocumented at the moment. you can provide an object with a view name as the key and the component as the value. check out how the built in views do it

**Comment by davincho** [comment]
@jquense I am having troubles to include my custom view.
I tried to do what you suggested:

```jsx
<BigCalendar defaultView="foo" views={{month: true, foo: CalendarFoo}} />
```

But I am getting an error saying `Cannot read property 'range' of undefined`.

**Comment by AgamlaRage** [comment]
Same issue for me.
How can I handle this without disabling the toolbar ?

**Comment by tairy-potter** [comment]
@jquense How I passing a function/parameter to custom view?
I have tried many ways but it's not working.

**Comment by niladrimahato96** [comment]
Is it possible to change the name of agenda to another like List View

**Comment by whallz** [comment]
@niladrimahato96 you simply change the label name use:

<BigCalendar
  messages={{
    agenda: 'List View'
  }}
.....
/>

should work!

**Comment by stephanieland352** [comment]
I finally got it like this:

First like @davincho said you add a custom view to the calendar component like so: 
`<BigCalendar defaultView="foo" views={{month: true, myList: MyList}} />`

Then in the file that returns the calendar component in the render section add 
`render(){
const MyList =  function(props, events) {
// this is where your data is displayed
return()
        }
        MyList.range = function (date, _ref) {
// sets the range values - in this case 1 week
            let start = dates.startOf(date, 'week');
            let end = dates.endOf(date, 'week');
            return dates.range(start, end);
        };
 MyList.navigate = (date, action) => {
            switch (action) {
                case _constants.navigate.PREVIOUS:
                    return dates.add(date, -1, 'week');
                case _constants.navigate.NEXT:
                    return dates.add(date, 1, 'week');
                default:
                    return date
            }
        }
MyList.title = date => {
            return `My awesome week: ${date.toLocaleDateString()}`
        }
return(
<BigCalendar defaultView="foo" views={{month: true, myList: MyList}} />
);
}`

**Comment by noahehall** [comment]
the messages worked perfectly, but begs to question, are we forced to hack through the codebase to add additional view names in addition to the existing.. 

e.g. what if i run out of default view names to rename via the messages api?

**Comment by noahehall** [comment]
nvm  didnt have to hack through anything.

the file here: https://github.com/intljusticemission/react-big-calendar/blob/06e08e228afbba3d46e8086bc646ac670430e0ba/src/utils/messages.js#L22


you can send messages a list of object keys whose value are renderable strings..


e.g. 

```js
views={{
          timespan: ActivityTimespan,
}},
messages={{
          timespan: 'poop'
}}
```
