### ISSUE TITLE
How do I modify the button font on the left, as marked above

### ISSUE THREAD

**Issue by SkyWblack** [intljusticemission/react-big-calendar#1355]
![image](https://user-images.githubusercontent.com/29719686/59495798-aab06f80-8ec2-11e9-9703-1c4e5623fcf8.png)

**Comment by SkyWblack** [comment]
I am a Chinese developer.How to set the font of the button to Chinese?I didn't find the configuration instructions in the documentation.Please answer it.thank you

**Comment by Zach-Lu** [comment]
same problem!
