### ISSUE TITLE
Drop area highlight

### ISSUE THREAD

**Issue by asakalou-exadel** [intljusticemission/react-big-calendar#1359]
#### Do you want to request a _feature_ or report a _bug_?
Feature
#### What's the current behavior?
While dragging items inside the calendar or outside the calendar we would like to see drop zone highlight. Currently cells are not highlighted and it's not clear whether we can drop an item or not.

I don't see usage of `rbc-addons-dnd-over` class in the code. Which might be a solution.

Example of drop zone highlighting in airtable:
<img width="1244" alt="airtable-dnd" src="https://user-images.githubusercontent.com/43654788/59752784-85897b80-928b-11e9-8c0c-6fb736752cae.png">

#### What's the expected behavior?
While dragging an item under cell, highlight cell - will help to determine it as a drop zone.

Please let us know if this feature is supported now.
Thanks!

**Comment by asakalou** [comment]
Hello Team, any updates?

**Comment by egorkavin** [comment]
Any updates?

**Comment by manjotsk** [comment]
I figured out, the Drag and Drop add on is using the Wrapper components to inject it's DnD related props, discarding the actual Manipulation of the `rbc-timeslot-group` `div`, which might be affecting the application of the `rbc-addons-dnd-over` in some manner. I maybe wrong, but, I am still trying to figure this out somehow. I'll update if i get anything further

**Comment by manjotsk** [comment]
`node_modules/react-big-calendar/lib/addons/dragAndDrop/EventContainerWrapper.js:268`

If by any chance you are trying to clone the element in your implementation, make sure these props are being passed to the parent, and are not getting overridden!

```    return _react.default.cloneElement(children, {
      children: _react.default.createElement(_react.default.Fragment, null, events, event && _react.default.createElement(_TimeGridEvent.default, {
        event: event,
        label: label,
        className: "rbc-addons-dnd-drag-preview",
        style: {
          top: top,
          height: height,
          width: 100
        },
        getters: getters,
        components: (0, _extends2.default)({}, components, {
          eventWrapper: _NoopWrapper.default
        }),
        accessors: (0, _extends2.default)({}, accessors, _common.dragAccessors),
        continuesEarlier: startsBeforeDay,
        continuesLater: startsAfterDay
      }))
    });```
    
    I'll try to produce a Sandbox for this!
