### ISSUE TITLE
IE9 Support

### ISSUE THREAD

**Issue by bluespore** [intljusticemission/react-big-calendar#136]
What's the exact reason the browser support is IE10+?

I have a project that needs to support IE9+ and I'm asking because if it's just a matter of ES5/6, Promise, and Flexbox - It's likely I could patch this with the relevant polyfills.

**Comment by jquense** [comment]
flexbox mostly, to which there isn't really good options for polyfilling (last i checked), even if there is managing cross-browser flexbox issues even for  ie10+, FF, and Chrome is _hard_ and I don't want to have have to also manage the supporting the idiosyncrasies of someones polyfill.

That said if there is a polyfill then it _should_ be something you can add yourself yeah?

**Comment by bluespore** [comment]
@jquense Yep. It certainly wasn't a request for you to take on, more looking for insight. 
If the only concern is flexbox then I'd be looking at using something like [Flexibility.js](https://github.com/jonathantneal/flexibility) to polyfill and see how that goes.

Thanks for the response.

**Comment by vikalpgupta-birdeye** [comment]
@bluespore Any luck using flexibility.js to handle ie9 issues?

**Comment by bluespore** [comment]
@vikalpgupta-birdeye I had another user contact me directly asking about this. I'll post here for a paper trail for the benefit of others in the future.

We just rewrote the CSS that used flexbox. Surprising how simple it turned out to be!
There might be some JS polyfill required as well from memory, but right now I can't recall. Mind you it wouldn't be anything specific and most products that are targeting legacy IE usually have the polyfill injected to the project already!

You can achieve a lot of flex with basic CSS using display table, and / or 2D transforms. Flexbox is just easier, for modern browsers. Which doesn't help if you're targeting legacy ;) 

Hope this helps you!

**Comment by kairi1227** [comment]
add style {height: 100vh} to parent dom
