### ISSUE TITLE
Fix: Attempted import error: does not contain a default export

### ISSUE THREAD

**Issue by EduardoCaseros** [intljusticemission/react-big-calendar#1363]
hi, I'm working with react typescript and mi code is this:
import React from 'react';
import BigCalendar  from 'react-big-calendar';
import Moment from 'moment';
import Eventos from '../calendario/Evento';
import 'react-big-calendar/lib/sass/styles.scss';

Moment.locale('es');
const Localizador  = BigCalendar.momentLocalizer(Moment);

function ComponenteCalendario() { 

  return (    
    <div>
      <BigCalendar
        events = {Eventos}
        localizer = {Localizador}             
        defaultView = {BigCalendar.Views.MONTH}    
        defaultDate = {new Date(2015,3,1)}
        views = {{month:true, week:true}}        
      />
      
    </div>
    
  );
}

export default ComponenteCalendario;

but this give me the next error: 

Failed to compile.

./src/calendario/ComponenteCalendario.tsx
Attempted import error: 'react-big-calendar' does not contain a default export (imported as 'BigCalendar').

**Comment by TrySound** [comment]
Api is changed in the latest version
https://github.com/intljusticemission/react-big-calendar/blob/master/CHANGELOG.md#breaking-change

**Comment by Hiroki111** [comment]
I encountered the same issue.

@TrySound 

I checked the link, but...

    import {
      Calendar,
      DateLocalizer,
      momentLocalizer,
      globalizeLocalizer,
      move,
      Views,
      Navigate,
      components,
    } from 'react-big-calendar'

...there is no `BigCalendar` in the list.
Does that mean we should use `Calendar` instead?

If so, however, importing `Calendar` results in "`Attempted import error: 'react-big-calendar' does not contain a default export (imported as 'Calendar').`";

This is caused by 
`import {Calendar} from 'react-big-calendar'`
or
`import Calendar from 'react-big-calendar'`.

I'm using **Typescript**, which might have something to do this error

**Comment by Hiroki111** [comment]
@TrySound 

I've made a runnable, minimum example for this issue with `create-react-app`.

https://github.com/Hiroki111/bigcalendar-test

I don't know if this helpful, but the error should be confirmed by downloading and running it by `yarn install` and `yarn start`.

**Comment by TrySound** [comment]
Perhaps you have old typescript typings (0.20.20) while this project is (^0.22.0). As I said this project does not provide types.

**Comment by Hiroki111** [comment]
@TrySound 

Thank you for your comment, but...

![Screenshot from 2019-06-23 08-02-40](https://user-images.githubusercontent.com/9676341/59972326-6d687380-958d-11e9-931e-7ffc98352851.png)

>Perhaps you have old typescript typings (0.20.20) while this project is (^0.22.0)

Is 0.20.20 an old version?
I'm not sure if  we have version 0.22.0 of @types

**Comment by TrySound** [comment]
Submit PR to definitely typed or copy to your project and change them. We do not support these types.

**Comment by shahzeb1** [comment]
**If there has been such an important update to the underlying API that `BigCalendar` isn't even a default entity that is exported, then this needs to be made pretty clear in the documentation and examples.**

**Comment by TrySound** [comment]
How this can be cleaner? Information that it was default previously has a place in changelog.
![image](https://user-images.githubusercontent.com/5635476/60463141-da49d080-9c53-11e9-9002-39c385b78f6d.png)

**Comment by shahzeb1** [comment]
Well at least in my example, the `<Calendar>` needed to be wrapped in a `<div>` of height 300pt. Without a declared height, the month view breaks.

And I know that there is updated code that is trickled throughout this repo, but maybe it would be higher priority to update the front page of the website as it still shows dated code:

![image](https://user-images.githubusercontent.com/1383831/60463515-0d16a900-9c01-11e9-8514-46e3ee486d91.png)

**Comment by TrySound** [comment]
I think I confused your highlighted message with blaming module exports.
> If there has been such an important update to the underlying API that BigCalendar isn't even a default entity that is exported, then this needs to be made pretty clear in the documentation and examples.

**Comment by TrySound** [comment]
And sure all fixes are appreciated.

**Comment by shahzeb1** [comment]
I see. I could've been more clear. I think since place here / on the demo site are still using `BigCalendar`, this was the only issue I stumbled across on Google which pointed me to the new change.

Will help note locations that could be updated and then create a PR.

**Comment by TrySound** [comment]
Ah, I probably missed this when I did this change.

**Comment by buidhui** [comment]
> @TrySound
> 
> I've made a runnable, minimum example for this issue with `create-react-app`.
> 
> https://github.com/Hiroki111/bigcalendar-test
> 
> I don't know if this helpful, but the error should be confirmed by downloading and running it by `yarn install` and `yarn start`.

your app test have same error about  (imported as 'BigCalendar').
