### ISSUE TITLE
Month View bottom row overflow in Chrome

### ISSUE THREAD

**Issue by RoslerWS** [intljusticemission/react-big-calendar#1367]
In the latest version of Chrome, the month view for the calendar is now overflowing out of its container. See the month view of the official example for React Big Calendar. One fix is to set the css for ".rbc-month-view" to a height of "auto" instead of "100%",

**Comment by TrySound** [comment]
Hi @RoslerWS do you want to send PR?

**Comment by abrahamtorres10** [comment]
I don't think setting the value to auto will fix the issue, unless you add a validation only for chrome because that breaks other browsers, like edge.

**Comment by chaczyk113** [comment]
@TrySound  Found the same problem with Chrome, also in your main page:
https://youtu.be/krqqMj4BkZ4
How to fix that in my own project, to make month view do not exceed the set height?
