### ISSUE TITLE
Any plans to add support for FullCalendar's Scheduler?

### ISSUE THREAD

**Issue by jasonleibowitz** [intljusticemission/react-big-calendar#137]
Hey, awesome project - thanks for all of the work. 

In your readme you mentioned that this was inspired by [FullCalendar](http://fullcalendar.io/). Out of curiosity, do you have any plans to extend this library to include something similar to FullCalendar's [scheduler feature](http://fullcalendar.io/scheduler/)?

**Comment by jquense** [comment]
Probably not, I don't have much of a need for it. But i'll accept PR's adding in something like Resource views, see: #13
