### ISSUE TITLE
Month view renders faulty when month starts on a wednesday

### ISSUE THREAD

**Issue by apelsinapa** [intljusticemission/react-big-calendar#1370]
#### Do you want to request a _feature_ or report a _bug_?
 bug

#### What's the current behavior?

When the month starts on a wednesday, days from the previous month is renderd inside the current view. This applies to v 0.22.0. 

#### What's the expected behavior?

Only days from current month should be rendered. I rolled back to 0.20.4 - It works as expected there.

**Comment by RoslerWS** [comment]
Works as expected in 0.21.0 also

**Comment by tresdev** [comment]
For me this happens when the month starts on a Tuesday.

**Comment by apelsinapa** [comment]
My week is localized to start on a Monday. tresdev; perhaps yours is meant to start on a Sunday?

**Comment by tresdev** [comment]
> My week is localized to start on a Monday. tresdev; perhaps yours is meant to start on a Sunday?

Yes it is. However, specifying moment.js locale solved the problem.

```
import 'moment/locale/es'
moment.locale('es')
```

**Comment by apelsinapa** [comment]
I had the sv moment locale specified, running latest version of moment. Even tried with globalise, and still had this issue.

**Comment by hesyifei** [comment]
Happens to me as well for `^0.22.0` (it was working as expected when using `^0.21.0`).

<img width="1259" alt="May 1894" src="https://user-images.githubusercontent.com/4939421/60389191-54226400-9a72-11e9-8a51-f74cbb5d8dfe.png">

**Comment by nicolasletoublon** [comment]
Same issue here using 0.22 
Reverting for now, waiting for it to be fixed.

**Comment by nicolasletoublon** [comment]
Why not fix this issue :(

**Comment by epicfaace** [comment]
can we reopen this issue?
