### ISSUE TITLE
Create event range is corruped

### ISSUE THREAD

**Issue by ffjanhoeck** [intljusticemission/react-big-calendar#1371]
#### Do you want to request a _feature_ or report a _bug_?
I want to request a bug

#### What's the current behavior?
1. Go to http://intljusticemission.github.io/react-big-calendar/examples/index.html#selectable
2. Create a new event (3 days long) using the mouse
3. enter a title
4. See that the event is just 2 days long but the user selected 3 days.

Here is a gif which describs it better
![2019-06-27_14-03-28](https://user-images.githubusercontent.com/9037364/60265014-dc72fe80-98e4-11e9-805f-82ef85fbbafb.gif)

Thanks :)

**Comment by jquense** [comment]
Looks like the example is probably encoding the wrong thing?

**Comment by ffjanhoeck** [comment]
@jquense I don't think this is an issue of the example. I have the same issue in my project. I justed verified it with the example. The callback function is returning the wrong value so I think this issue has to be fixed in the core project.

**Comment by natac13** [comment]
Does this have anything to due with **date light savings**? I did a little test and found that a date `Jun 04 2019 00:00:00 GMT-0400` shows up as June 3 for my local, which is EST; however upon changing to `GMT-0500` I was able to get the date on June 4th! Since the clocks are ahead artificially right now could this be the cause? I will be testing this in the fall if no other solution emerges. :smile:

**Comment by ffjanhoeck** [comment]
I fixed it in my project with a if clause. I just checked if the endDate has hours = 0, minutes = 0 and seconds = 0. If this condition matchs, I set the endDate to hours = 23, minutes = 59.
Its completly ok for now but I don't like workarounds :)

**Comment by ffjanhoeck** [comment]
@natac13 What is date light savings?

**Comment by natac13** [comment]
Oh sorry I meant Day Light Saving Time, not *date* :flushed:

**Comment by ffjanhoeck** [comment]
I understand :D But I don't think that is the problem :/

**Comment by mtowercamp** [comment]
> I fixed it in my project with a if clause. I just checked if the endDate has hours = 0, minutes = 0 and seconds = 0. If this condition matchs, I set the endDate to hours = 23, minutes = 59.
> Its completly ok for now but I don't like workarounds :)

it works perfectly even if you add 1 sec on the end date.
