### ISSUE TITLE
How can I restrict the time ranges when a user can create an event?

### ISSUE THREAD

**Issue by moshebeeri** [intljusticemission/react-big-calendar#1373]
I think it is a feature unless there is a documentation bug
Missing feature of restricting the event selection to certain time ranges
The expected behavior is to create a calendar with a list of allow ranges to select from
`   
    <Calendar
       selectRanges = [ {start:{...}, end:{...}}  {start:{...}, end:{...}}, {start:{...}, end:{...}} ] 
    />
`
If this feature is not supported I'll be happy if you can share some high level instructions of how to implement it.
Thanks,

**Comment by KhaledMohamedP** [comment]
@moshebeeri I don't think this is supported at the moment. I would actually like something like this too 👍  

My current solution for this is to add an event with custom styling (grey background) & hide the text.

If you want to avoid users from selecting in top of those events, you can use the 
`onSelecting` callback [doc](http://intljusticemission.github.io/react-big-calendar/examples/index.html#prop-onSelecting)

**Comment by moshebeeri** [comment]
@KhaledMohamedP  Thanks for sharing - Your solution will work, but its not elegant as I expect the calendar to support it directly.
