### ISSUE TITLE
any way to display only certain time in weekly and daily view?

### ISSUE THREAD

**Issue by kakariko-village** [intljusticemission/react-big-calendar#1375]
Hi, i only want the calendar to display time from 9 a.m to 6 p.m in Weekly and Daily view (don't need to change anything to monthly view). I tried css to display none to rows from 0:00 a.m to 8:30 a.m and 18:30 p.m to 12:00 p.m but those events stay in incorrect position. Is there anyway to do this?

**Comment by yourivdlans** [comment]
You might be looking for the [min](https://intljusticemission.github.io/react-big-calendar/examples/index.html#prop-min) and [max](https://intljusticemission.github.io/react-big-calendar/examples/index.html#prop-max) properties.

The following would set the calendar to only display times from 9 am to 6 pm.

```js
<BigCalendar
  min={new Date(2000, 1, 1, 9)}
  max={new Date(2000, 1, 1, 18)}
/>
```
