### ISSUE TITLE
DrillDown ("+<number> more") No Being Displayed Properly

### ISSUE THREAD

**Issue by jay-ohh-ee** [intljusticemission/react-big-calendar#1378]
#### Do you want to request a _feature_ or report a _bug_?
Report A Bug
#### What's the current behavior?
Based on the algorithm to decide when an event should appear, there are some events that occur on multiple days that don't get displayed.  However there is no notification at the bottom that communicates that there are more events for that day that aren't being displayed.  The expected behavior is present for other days and works appropriately but on other days it does not.

On another side note, I saw that the "all day" label was removed from the day/week views but I was wondering how I can insert that again.  

Thanks.

#### What's the expected behavior?
Expected behavior is it will show the amount of extra events not being displayed on that day at the bottom of the day in the form of +8 More or however many extra events are not being shown on that day in the month view.
![Screenshot (141)_LI](https://user-images.githubusercontent.com/47905912/60681467-2bb8b200-9e44-11e9-9a54-12d4a6d89b60.jpg)
![Screenshot (142)_LI](https://user-images.githubusercontent.com/47905912/60681473-2fe4cf80-9e44-11e9-8deb-348e9ce6c937.jpg)

**Comment by jquense** [comment]
please provide a runnable repro using the codesandbox template

**Comment by jay-ohh-ee** [comment]
Here is the link that reproduces what I was discussing.  https://codesandbox.io/s/young-monad-8ru45
What I did notice is that for July 3, 4, 5, 6 in the sandbox it shows the proper amount of extra events not being displayed.  I am not getting this though in my code as seen above.  However the issue still exists with respect to July 2.  Here only one event is displayed but there are 9 events for that day.  The events that exist on that day are event numbers 3, 4, 6, 8, 13, 14, 16, 17, 20. If you look at the events.js file in the sandbox you can confirm that all of these dates are all accurate for July 2.

**Comment by jay-ohh-ee** [comment]
Just curious if there has been any update on this or if you have been able to understand my issue with the provided link.  If anything else is needed please let me know.
