### ISSUE TITLE
Week and Day views misaligned in Firefox

### ISSUE THREAD

**Issue by nddejong** [intljusticemission/react-big-calendar#138]
In Firefox on the week and day views, the events are showing up in the wrong time slot.  A 7 am event is showing up in the 3:30 am time slot.  

<img width="894" alt="screen shot 2016-07-15 at 1 55 30 am" src="https://cloud.githubusercontent.com/assets/812789/16864968/4f590c58-4a2f-11e6-9f89-d1fc4e1c59af.png">

**Comment by jquense** [comment]
that may just be a bug in the docs, can you try with the latest version?I beleive I fixed this issue already

**Comment by jgautsch** [comment]
I experienced this issue in the latest version- it was only when I forked the repo to use unreleased code that it was fixed

**Comment by nddejong** [comment]
On my local I am using 0.10.2 and am getting the problem on the project I am working on.  I tested different browsers and the problem is showing up on Firefox, Edge, and IE11.  The calendar is showing up correctly on Chrome, Safari, Vivaldi, and Opera.

**Comment by jquense** [comment]
sorry folks thought I released, will do that right now

**Comment by nddejong** [comment]
Thanks for the quick turnaround.

**Comment by chunky123** [comment]
Getting the same issue with latest version 0.10.3 - Has the fix been released yet?

**Comment by nddejong** [comment]
The fix in 0.10.3 fixed for me the issue of the event bubbles being the wrong heights and thus up higher that they were supposed to be.

Thanks,
Nathan
