### ISSUE TITLE
Ability to book multiple events in same slot on mobile

### ISSUE THREAD

**Issue by pitops** [intljusticemission/react-big-calendar#1380]
Apologies if this was asked before and I am not sure if its a feature. 

Basically what I am struggling with is the ability to add multiple events on the same slot on mobile.

I understand on desktop there is a small space on the right side of the events so that you can click on the slot. But what about on mobile? is there any other workaround?

**Comment by jquense** [comment]
I believe there is an event passthrough option that changes the selecting behavior to ignore events, you have to poke through the source tho

**Comment by pitops** [comment]
@jquense the thing is I want to be able to do both
