### ISSUE TITLE
Last slot of day event rendered incorrectly (takes up 2 slots instead of 1)

### ISSUE THREAD

**Issue by dkenul** [intljusticemission/react-big-calendar#1381]
#### Do you want to request a _feature_ or report a _bug_?

bug

#### What's the current behavior?

When rendering an event at the end of the day, 2 slots will appear to be taken up instead of one even though the underlying event `start` and `end` are correct. Furthermore, if you try to use midnight as an `end` instead of 23:59:59, the event will appear outside (above) the day. 

Here is a CodeSandbox that demonstrates the issue:
https://codesandbox.io/s/peaceful-fermi-2ww08

And pics of the behavior:
https://imgur.com/a/qYIMKXO

I've tried to reproduce this example (and dependencies) as a model:
https://github.com/intljusticemission/react-big-calendar/blob/master/examples/demos/selectable.js

but interestingly the live demo doesn't appear to have this problem:
http://intljusticemission.github.io/react-big-calendar/examples/index.html#selectable

**Update**
It appears this bug did not exist in version 0.17.0 as per this sandbox (I assume the live demo is also using this or another version prior to this bug being introduced):
https://codesandbox.io/s/frosty-moser-q8hd1

**Update 2**
Regression is caused by: https://github.com/intljusticemission/react-big-calendar/commit/9689b7d112dd9dba4a5424808de08fdd5738db79#diff-0f5fda8a0fc3ee4c6e348a7804c7c141R133

#### What's the expected behavior?

Last slot of the day rendering (styles) match underlying event `start` and `end`. 

--- 
I would be happy to look into this issue if I can have some confirmation that this isn't intended behavior that can be worked around in some way that I'm missing (since the live example appears to not have this bug)

**Comment by ffjanhoeck** [comment]
I think its the same issue or same bug as https://github.com/intljusticemission/react-big-calendar/issues/1371

**Comment by dkenul** [comment]
@ffjanhoeck your bug appears to be a different issue (on the surface). Have you experienced this behavior as well and/or found a common source of this behavior in the code?

**Comment by ffjanhoeck** [comment]
I didn't checked the code for this issue. But I implemented a workaround for me
