### ISSUE TITLE
Agenda does not work as expected

### ISSUE THREAD

**Issue by ffjanhoeck** [intljusticemission/react-big-calendar#1382]
#### Do you want to request a _feature_ or report a _bug_?
I think it is a bug.

#### What's the current behavior?
The current behavior is that a event for today won't be showed in the agenda.
I checked the code of the Agenda component (Agenda.js) and I saw, that the library removes events which should not be showed in the agenda view. Thats totally ok for now!

The code looks like this:
```
export function inRange(e, start, end, accessors) {
  let eStart = dates.startOf(accessors.start(e), 'day')
  let eEnd = accessors.end(e)

  let startsBeforeEnd = dates.lte(eStart, end, 'day')
  // when the event is zero duration we need to handle a bit differently
  let endsAfterStart = !dates.eq(eStart, eEnd, 'minutes')
    ? dates.gt(eEnd, start, 'minutes')
    : dates.gte(eEnd, start, 'minutes')

  return startsBeforeEnd && endsAfterStart
}
```

Please take a look into the eEnd variable. Why is this different from the eStart variable?
I tought the code should look like this: `dates.endOf(accessors.end(e), 'day')` ? 

As you can see in the following image, my event starts at 5:30am and ends 10am.
![image](https://user-images.githubusercontent.com/9037364/60796945-aba98980-a16e-11e9-996f-2d7f7c4e7714.png)

If I continue the debugger to the end, you can see that the endsAfterStart returns false. But thats not true! The event definitely ends after the start date. 
![image](https://user-images.githubusercontent.com/9037364/60797280-46a26380-a16f-11e9-9344-af1d2522a0df.png)

The end and start property from the arguments always have to same value for the agenda view, because this value is the current time.

Hopefully anyone can help me out if I do something wrong :x

**Comment by ffjanhoeck** [comment]
Is there anyone who can help?

**Comment by davidhan527** [comment]
I'm seeing a similar issue. I have an all-day event for today, and it doesn't show on the Agenda view unless I hit the back button. The default Agenda view which includes today should show today's all-day event.

**Comment by paulhan221** [comment]
I am also having this issue, can someone please help?

**Comment by rahrang** [comment]
same problem!

**Comment by ffjanhoeck** [comment]
Please reopen this issue!

**Comment by ffjanhoeck** [comment]
> same problem!

@rahrang @paulhan221 Did you find a solution for this ?
