### ISSUE TITLE
Can't resolve @babel/assertThisInitialized

### ISSUE THREAD

**Issue by peter-sorbo** [intljusticemission/react-big-calendar#1383]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

RBC can't resolve @babel/assertThisInitialized. No idea why this is happening, although I think it's due to a conflict with one of my other dependancies. 

A similar issue (#971) appears to have a similar problem and doesn't offer a solution. Other people have experienced this with other libraries (Material UI and redux) and solved it with npm install --save-exact @babel/runtime@7.0.0-beta.55, deleting & reinstalling node modules, as well as changing the version of the affected library. I've tried these methods and none have worked.

#### Any idea how to fix this, or any other info I could provide to help debug?

Your help is very much appreciated.

The exact error message:
./node_modules/react-big-calendar/dist/react-big-calendar.esm.js
Module not found: Can't resolve '@babel/runtime/helpers/esm/assertThisInitialized' in '/EnsoConnect/Enso_React/material/node_modules/react-big-calendar/dist'

My package.json

{
  "name": "material",
  "private": true,
  "version": "4.0.0",
  "main": "",
  "homepage": "",
  "scripts": {
    "start": "react-app-rewired start",
    "build": "react-app-rewired build",
    "test": "react-app-rewired test --env=jsdom",
    "eject": "react-scripts eject",
    "prettier": "prettier --write ./src/**/**/**/*"
  },
  "dependencies": {
    "@babel/runtime": "7.0.0-beta.55",
    "@material-ui/core": "^1.5.0",
    "@material-ui/icons": "^2.0.2",
    "@material-ui/lab": "^1.0.0-alpha.10",
    "aws-amplify": "^1.1.29",
    "axios": "^0.18.0",
    "classnames": "^2.2.6",
    "core-js": "^2.5.7",
    "date-fns": "^2.0.0-alpha.31",
    "downshift": "^2.1.1",
    "echarts": "^4.1.0",
    "echarts-for-react": "^2.0.14",
    "element-resize-event": "^2.0.9",
    "font-awesome": "~4.7.0",
    "history": "^4.6.1",
    "jquery": "^3.3.1",
    "jquery-slimscroll": "~1.3.8",
    "material-ui-pickers": "1.0.0-rc.11",
    "moment": "^2.24.0",
    "prop-types": "^15.6.2",
    "rc-queue-anim": "^1.6.5",
    "react": "^16.8.6",
    "react-big-calendar": "^0.21.0",
    "react-chat-elements": "^10.5.0",
    "react-dom": "^16.8.6",
    "react-hot-loader": "^4.3.4",
    "react-loadable": "^5.5.0",
    "react-redux": "^5.0.7",
    "react-render-html": "^0.6.0",
    "react-router": "^4.3.1",
    "react-routaer-dom": "^4.3.1",
    "react-router-redux": "5.0.0-alpha.6",
    "react-scripts": "2.0.0-next.3e165448",
    "react-spinners-kit": "^1.9.0",
    "react-timer-mixin": "^0.13.4",
    "react-verification-code-input": "^1.2.0",
    "redux-immutable-state-invariant": "^2.1.0",
    "redux-thunk": "^2.3.0",
    "socket.io": "^2.2.0",
    "styled-components": "^4.2.1"
  },
  "browserslist": {
    "development": [
      "last 2 chrome versions",
      "last 2 firefox versions",
      "last 2 edge versions"
    ],
    "production": [
      ">0.25%",
      "not op_mini all",
      "ie 11"
    ]
  },
  "devDependencies": {
    "bootstrap": "^4.1.3",
    "node-sass": "^4.9.3",
    "prettier": "^1.14.2",
    "react-app-rewire-provide-plugin": "^1.0.0",
    "react-app-rewired": "^1.5.2",
    "redux": "^4.0.1",
  }
}

**Comment by TrySound** [comment]
You have quite old setup. From what I remember react-scripts somehow enforced specific babel runtime version. I think upgrade should fix the problem. If it still will not work You will have to upgrade material-ui and babel runtime too.

Also which package manager do you use?
