### ISSUE TITLE
weekNumber is not showing in react-big-calendar. Please let me know how can I show it

### ISSUE THREAD

**Issue by amansehgalg** [intljusticemission/react-big-calendar#1384]
![4a0b6bca-dcc3-11e6-8d32-7e599f4474ba](https://user-images.githubusercontent.com/33564377/60949236-658d2b00-a312-11e9-9803-42d8b9a51ddc.jpg)
Please let me know that How can we show the week number in Calendar?

**Comment by jquense** [comment]
We don't have this feature but you could probably extend the built-in month component and use the custom API API to replace the existing one
