### ISSUE TITLE
How to hide events only in month view?

### ISSUE THREAD

**Issue by MarcDAFrame** [intljusticemission/react-big-calendar#1385]
I want people to be able to see and select from the month view, but I don't want events to show on it.

is there any way to do this?

**Comment by MarcDAFrame** [comment]
I figured out a way of doing it, I have a custom tool bar that keeps track of the navigation between the month / week / day views and I conditionally pass the events in depending on which one is selected

**Comment by AndresFSalcedo** [comment]
Hi Marc,

How did you do that?

**Comment by cutterbl** [comment]
@AndresFSalcedo If you control the `view` prop, then you could conditionally apply your `events`

```js
const [events, setEvents] = useState(() => initialEvents);
const [view, setView] = useState(views.MONTH);

<Calendar
  view={view}
  events={view !== views.MONTH ? events : []}
  {...otherProps}
/>
```
