### ISSUE TITLE
For some months the calendar is showing the complete previous month and the complete selected month

### ISSUE THREAD

**Issue by Sparragus** [intljusticemission/react-big-calendar#1388]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?
For some months the calendar is showing the complete previous month, the selected month. Also, the last days of the months are incorrectly rendered.

I noticed that this will happen for all the months that start on a certain weekday. For example, in the CodeSandbox linked below, go to October 2019. That month starts on a Tuesday. If you go to another month that starts on a Tuesday, you'll see the same issue.

Furthermore, if you use a different locale, the issue will still happen, but it will happen on different months.

CodeSandbox: https://codesandbox.io/s/react-big-calendar-example-2m1df
Screenshot:
![image](https://user-images.githubusercontent.com/80982/61262963-db4b2980-a74c-11e9-955d-0a52a7101a68.png)

Browser:
Chrome 75
react-big-calendar 0.22.0

#### What's the expected behavior?
It should only show the currently selected month.

#### Additional notes
This issue does not happen on `0.21.0`. See: https://codesandbox.io/s/react-big-calendar-example-osvhu

**Comment by Sparragus** [comment]
Thank you for making this project. I'm very grateful for it and for any help you can provide to resolve this issue. 🙏

**Comment by TomaszRej** [comment]
I'm having the same issue.
