### ISSUE TITLE
Contribution guide

### ISSUE THREAD

**Issue by khendrikse** [intljusticemission/react-big-calendar#1393]
#### Do you want to request a _feature_ or report a _bug_?
Feature

#### What's the current behavior?

Right now there is no contribution guide which could make it difficult for people who want to contribute to know if they actually can, and if they can, what the expected way of contributing would be.

#### What's the expected behavior?

It would be nice to have a contribution guide so people know if they can help out and if so, how they could best do this.

Maybe some inspiration:
https://help.github.com/en/articles/setting-guidelines-for-repository-contributors

**Comment by ffjanhoeck** [comment]
I like the your idea :)

**Comment by khendrikse** [comment]
Hey! I wonder if there is any way to make this happen? :)
