### ISSUE TITLE
Show more missing in month view after resize

### ISSUE THREAD

**Issue by alexeymolchan** [intljusticemission/react-big-calendar#1394]
Hi, after window height resize show more link disappear.
Video of the behavior: https://monosnap.com/file/ywFs8eLS0IGzlEEwL7lf3fKz9Yx0R7. (Look at Saturday 20th)

```
class EventEndingRow extends React.Component {
  render() {
    let {
      segments,
      slotMetrics: { slots },
    } = this.props
    let rowSegments = eventLevels(segments).levels[0] <---- why we get eventLevels and use only the first level ?!

    let current = 1,
      lastEnd = 1,
      row = []

    while (current <= slots) {
      let key = '_lvl_' + current

      let { event, left, right, span } =
        rowSegments.filter(seg => isSegmentInSlot(seg, current))[0] || {} //eslint-disable-line

      if (!event) {
        current++
        continue
      }
```
I think the problem is that we filter rowSegments array instead of of segments.

Version: 0.22.0

**Comment by homejames203** [comment]
We're having the same issue. After a resize on month view, the more button is missing. Has anyone else seen this?

**Comment by arturoribessanz** [comment]
Yes, same here. Looks like the logic for showing the show more button is only applied on first render. There is a state bool flag which controlls that behavior in MonthView, but no idea how to get to that.
