### ISSUE TITLE
Error on custom component for the calendar with tooltip

### ISSUE THREAD

**Issue by jechazelle** [intljusticemission/react-big-calendar#1395]
Hi,
thank you so much for ract-big-calendar : nice job 👍 

I would like to create a custom component for the calendar with tooltip ()

```
import { Calendar } from 'react-big-calendar';
import { Tooltip, OverlayTrigger } from 'react-bootstrap';

event({ event }) {
        return (
            <span className="event-title">
                <OverlayTrigger overlay={<Tooltip id="tooltip-disabled">Tooltip Message</Tooltip>}>
                    {event.title}
                </OverlayTrigger>
            </span>)
    }

<Calendar
   ...
   components={{
      event: this.event
   }}
/>
```

But I have an error when I use OverlayTrigger in the custom component : 

> Uncaught Invariant Violation: React.Children.only expected to receive a single React element child.
> Uncaught Invariant Violation: React.Children.only expected to receive a single React element child.
> index.js:1446 The above error occurred in the <OverlayTrigger> component:
>     in OverlayTrigger (at Home.js:24)

Home.js: line 24 is : 
`<OverlayTrigger overlay={<Tooltip id="tooltip-disabled">Tooltip Message</Tooltip>}>
`

I use the tooltip in my project and it's ok, but if I include the tooltip in the custom component in Calendar : crash.

I use react-bit-calendar (0.22.0) and react-bootstrap (1.0.0-beta.9)

**Comment by TrySound** [comment]
Hi @jechazelle Is this still  a problem for you? The new version uses new react-overlays.

**Comment by TrySound** [comment]
Ah, I see. You use react-bootstrap here. Not sure how this can be related to react-big-calendar package.

**Comment by TrySound** [comment]
Could you provide codesandbox example?
