### ISSUE TITLE
drop and drag support ?

### ISSUE THREAD

**Issue by mydearxym** [intljusticemission/react-big-calendar#14]
amazing work!
is this repo support drop / dray events like [this](http://fullcalendar.io/js/fullcalendar-2.5.0/demos/selectable.html)  ?

**Comment by jquense** [comment]
it does not! It might in the future though, its on the eventual roadmap, however we don't have a strong need for DnD support so its less of a priority

**Comment by mydearxym** [comment]
Get it , thanks @jquense
