### ISSUE TITLE
Switch columns and rows

### ISSUE THREAD

**Issue by rado-lalaniaina** [intljusticemission/react-big-calendar#1407]
Greetings,

Sorry guy but, my client want to switch place of rows (hours) to column and column (date) to row. Can anyone give me a track or how to do it ?

Thank a lot

**Comment by sebastianpsf** [comment]
Any idea how to do it?

**Comment by PaoloDiBello** [comment]
@sebastianpsf how did you end up solving the issue?

**Comment by PaoloDiBello** [comment]
> Any idea how to do it?

@sebastianpsf  were you able to solve your issue?

**Comment by rado-lalaniaina** [comment]
Hi, 
You can code it with timeline (event ressource) and put correct option https://fullcalendar.io/docs/timeline-view. Unfortunately, i found no plugin

**Comment by sebastianpsf** [comment]
> > Any idea how to do it?
> 
> @sebastianpsf were you able to solve your issue?

Nope, I had to use react-selectable-fast
