### ISSUE TITLE
Event Not Showing on Android's Chrome

### ISSUE THREAD

**Issue by Hndry** [intljusticemission/react-big-calendar#1413]
Hello,
i don't know if this is a bug or not.
But, with my current code, i can get all the event showing, except for the Android Chrome.

Here's my code for the calendar : 

 //<BigCalendar
                    events={eventArray}
                    view={editedData.view}
                    startAccessor="start"
                    titleAccessor="title"
                    endAccessor="end"
                    onView={this.onView}
                    onSelectEvent={this.onSelectDate}
                    onNavigateMonth={this.onNavigateMonth}
  ///>

and this is my event :
const eventArray = {
              title: data.name,
              start: data.startTime,
              end: data.endTime
            };

**Comment by shhivam** [comment]
Can you attach some screenshots or give us more information regarding how your `BigCalendar` Component is getting used?
