### ISSUE TITLE
Website is showing old syntax

### ISSUE THREAD

**Issue by zomars** [intljusticemission/react-big-calendar#1414]
<img width="663" alt="image" src="https://user-images.githubusercontent.com/3504472/62824137-fa27ba80-bb56-11e9-9515-a6116b3500f4.png">

**Comment by shhivam** [comment]
Yup, working on updating the documentation [here](https://intljusticemission.github.io/react-big-calendar/examples/index.html#prop-formats.eventTimeRangeStartFormat)
