### ISSUE TITLE
Is defaultDate a valid prop?

### ISSUE THREAD

**Issue by jbschrades** [intljusticemission/react-big-calendar#1418]
#### Do you want to request a _feature_ or report a _bug_?
bug

#### What's the current behavior?
defaultDate prop is not hooked up

#### What's the expected behavior?
defaultDate should be a prop

I see references to the `defaultDate` prop in some examples (ie, https://github.com/intljusticemission/react-big-calendar/blob/master/examples/demos/basic.js#L22), but it's not actually present in the code.  Is this intentional? Was it removed for some reason?

**Comment by shhivam** [comment]
I am using version 0.22.o  & AFAIK, `defaultDate` prop is working & is hooked up.

**Comment by jbschrades** [comment]
@shhivam how are you using it?  I'm storing the current date in the URL and want to use `defaultDate` to load that date when the page is refreshed.  But again, searching the code, I don't see that it's actually being used.

**Comment by shhivam** [comment]
You have to somehow extract the date from the url, convert it into a Date Object & then pass it in `defaultDate` Prop
