### ISSUE TITLE
Multiple resources doesn't support in Month View

### ISSUE THREAD

**Issue by wenjoy** [intljusticemission/react-big-calendar#1423]
Does anyone know how to display multiple resources in Month View?
#### Do you want to request a _feature_ or report a _bug_?
feature
#### What's the current behavior?
I implement multiple resources as example ["resource schedule"](http://intljusticemission.github.io/react-big-calendar/examples/index.html#resource).

#### What's the expected behavior?
I expected it display multiple resources in Month View just as it does in Day View and week View. Bit it doesn't. In Month View,it seems ignore resources I passed in.

**Comment by sovcik** [comment]
DayView shows multiple day columns if multiple resources are selected. Would you like to show multiple month views? That might be quite unusable...
