### ISSUE TITLE
click on the edge of show more popup triggers onSelectSlot event

### ISSUE THREAD

**Issue by zheyujie** [intljusticemission/react-big-calendar#1424]
#### Do you want to request a _feature_ or report a _bug_?
I believe this is a bug
#### What's the current behavior?

When one has a selectable calendar with onSelectSlot AND popup=true, clicking on the edge of the popup (e.g. the date header of the popup) triggers onSelectSlot.

I've created a sample below, please open the browser console and you will see onSelectSlot being fired when clicking on the edge of the show more popup

Sample: https://codesandbox.io/embed/kind-poincare-ietkd

#### What's the expected behavior?
Is it possible to prevent this from happening? I'm planning to add a <Close> button on the top right corner of the show more popup so that I will be able to close the popup without having to click outside of the popup. But the current behavior blocks me from doing so and I'm not sure how to overcome it.

Thanks

**Comment by shhivam** [comment]
This is indeed a bug according to me. Thanks for pointing it out.

I will see what I can do to fix it

**Comment by zheyujie** [comment]
Any help on this?
I had a look the code but I couldn't understand why this happens.
