### ISSUE TITLE
+X more not showing when event is slightly bigger than default (className or custom component)

### ISSUE THREAD

**Issue by matatablack** [intljusticemission/react-big-calendar#1427]
Hi there, thank you all for this awesome work!

#### Do you want to request a _feature_ or report a _bug_?
Report  a bug

#### What's the current behavior?
When the events are overflowing the date cell the show more link do not appear until it reaches some kind of fixed height? I say fixed height because it works but always like if the rbc-event item were the default height. I will update if I find something in the source code. 

Try to resize and check when the "+2 more" link appears. If you comment the "custom-event" class in  "events.scss" and check the behavior with the default event heigth, it seems to show the link at the same time / overflow ammount. Sorry for my english i hope you can understand what im referring to. 

https://codesandbox.io/s/aged-frost-2o474

Chrome 75
Mac OS Mojave
create-react-app
RBC 0.22.0

![image](https://user-images.githubusercontent.com/40765450/63459800-97be9c00-c42b-11e9-865a-df13ba4e4dc5.png)

Thank you so much!

**Comment by matatablack** [comment]
I know it seems like a duplicate of many others but i think it's not. No one mention the height in relation to the trigger of the "+2 more", and i just want my events a little bigger, nothing else ☹️

**Comment by matatablack** [comment]
The issue lays in `DateContentRow.js` 
The measures are taken from the default markup at `renderDummy()`method. 
I don't know why a dummy render is needed for measures, maybe performance. 

Meanwhile, if you have fixed event heights,  it can be solved by css giving min-height to any class of the following structure: 

`<div className="rbc-row" ref={this.createEventRef}>
    <div className="rbc-row-segment">
          <div className="rbc-event">
                <div className="rbc-event-content">&nbsp;</div>
        </div>
   </div>
</div>`

**Comment by mdobroggg** [comment]
@matatablack I'm having this same issue and setting min-height doesn't seem to be helping. Did you end up solving this a different way?

**Comment by bennyfink** [comment]
For others, I've posted a quick workaround here #1213

**Comment by Kamronbekdevoloper** [comment]
hello bro. i had a same problem but now problem solved.  
.rbc-row {
   padding-top: 8px !important;
}
i change margin to padding and padding has worked. if you write with margin just change to padding
