### ISSUE TITLE
npm run examples is broken

### ISSUE THREAD

**Issue by frontenddeveloping** [intljusticemission/react-big-calendar#143]
![image](https://cloud.githubusercontent.com/assets/2063415/16928989/48a5e810-4d3e-11e6-92fb-29f1ab1f332d.png)

Work for me next steps:
1) `npm run clean:examples`
2) `webpack  --config  webpack/examples.config.es6.js`
3) `python -m http.server` or `python -m SimpleHTTPSever` in _examples_ folder
4) Open 0.0.0.0:8000 in your browser

**Comment by jquense** [comment]
why are you starting a python server...

**Comment by frontenddeveloping** [comment]
@jquense because npm command is broken

**Comment by jquense** [comment]
works on the few computers I tried. Looks like you might have a bad install or something in your node env is messed up, maybe an old version of npm. Not sure, but the error isn't in my code so i'm not sure what it might be.

**Comment by jquense** [comment]
o I see the problem is you are running the command with a nonexistent option`"3000"`, just run `npm run examples`
