### ISSUE TITLE
react-big-calendar navigate to specific day

### ISSUE THREAD

**Issue by fawadshahdev** [intljusticemission/react-big-calendar#1432]
it might be silly question to ask but trust me I am new to react . Actually , current React-big-calendar support navigate to specific date which are selected from Month view . I want same thing when user click on day from Month view I want to navigate user to specific day . please help me

`<MyCalendar
          popup
          selectable
          timeslots={1}
          localizer={localizer}
          view={this.state.viewing}
          views={[this.state.viewing]}
          components={{ toolbar: CustomToolbar }}
          style={{ height: 600 }}
          startAccessor="start"
          endAccessor="end"
          min={new Date(2019, 10, 0, 7, 0, 0)}
          max={new Date(2019, 10, 0, 22, 0, 0)}
          events={this.props.events}
          eventPropGetter={this.eventStyleGetter}
          onSelectEvent={slotInfo => this.onSelectEventHandler(slotInfo)}
          onSelectSlot={slotInfo => this.onSelectEventSlotHandler(slotInfo)}
        />`

**Comment by eightshone** [comment]
Here's an idea that should work:
add a date picker to your interface, this picker should control change your state. finally pass that state element to this prop `defaultDate`
http://intljusticemission.github.io/react-big-calendar/examples/index.html#prop-date

**Comment by doantientai** [comment]
@eightshone This is exactly what I am doing! I have a small question. Do you have any idea how I could I replace the rbc-toolbar-label by the datepicker?
I don't want to replace the whole toolbar but only the rbc-toolbar-label where the viewed date is displayed.

**Comment by eightshone** [comment]
@doantientai I don't know if that's possible. Couldn't find something that replaces the toolbar partially. I guess you'll have to recreate the toolbar.
