### ISSUE TITLE
React Big Calendar onSelect event on mobile not working properly

### ISSUE THREAD

**Issue by nabhdeepsingh** [intljusticemission/react-big-calendar#1434]
Hi,

I am using React big calendar.n Desktop it is working fine but on mobile I have to click and hold to select a day.I want to select a day on click.

Can anyone please help me.

**Comment by eightshone** [comment]
It makes senes to me as it should be a way to distinguish scrolling from selecting

**Comment by tayloraleach** [comment]
Is there a solution to this? I am facing the same issue. 

The functionality I am after is that users cannot select multiple days, only one day at a time which them becomes 'active' (in month view) and so I use `onSelectEvent` as well as `onSelectSlot` with the same function to then add a class to that cell the user clicked on based on the date. But having `onSelectSlot` allows the selection of multi-day which I am just overriding and selecting the first day.

But this has the added side effect of not allowing the user to scroll over the calendar on mobile...

**Comment by paradyo** [comment]
still waiting for solution
