### ISSUE TITLE
TypeError: Bind must be called on a function

### ISSUE THREAD

**Issue by MatthewHerbst** [intljusticemission/react-big-calendar#1438]
#### Do you want to request a _feature_ or report a _bug_?
Bug
#### What's the current behavior?
Unfortunately I am not able to reproduce this because I do not know what the user was doing at the time that they caused this error to occur.

We received the following error and stack trace through our error monitoring tool:

```
TypeError: Bind must be called on a function
File (native) line (unknown) in bind
File webpack:///./~/react-big-calendar/~/dom-helpers/query/querySelectorAll.js line 9 col 1 in Object.<anonymous>
  var toArray = Function.prototype.bind.call(Function.prototype.call, [].slice);
File webpack:///webpack/bootstrap 2c6af6a309eca3e1a9e0 line 52 col 1 in __webpack_require__
  modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
File webpack:///./~/react-big-calendar/lib/DateContentRow.js line 20 col 1 in Object.<anonymous>
  var _querySelectorAll = _interopRequireDefault(require("dom-helpers/query/querySelectorAll"));
File webpack:///webpack/bootstrap 2c6af6a309eca3e1a9e0 line 52 col 1 in __webpack_require__
  modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
File webpack:///./~/react-big-calendar/lib/Month.js line 40 col 1 in Object.<anonymous>
  var _DateContentRow = _interopRequireDefault(require("./DateContentRow"));
File webpack:///webpack/bootstrap 2c6af6a309eca3e1a9e0 line 52 col 1 in __webpack_require__
  modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
File webpack:///./~/react-big-calendar/lib/Views.js line 10 col 1 in Object.<anonymous>
  var _Month = _interopRequireDefault(require("./Month"));
File webpack:///webpack/bootstrap 2c6af6a309eca3e1a9e0 line 52 col 1 in __webpack_require__
  modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
File webpack:///./~/react-big-calendar/lib/utils/move.js line 14 col 1 in Object.<anonymous>
  var _Views = _interopRequireDefault(require("../Views"));
```

#### What's the expected behavior?

There should be no error.

I looked at where this library calls `.bind` and didn't see anything that immediately stood out.

**Comment by MatthewHerbst** [comment]
I continue to receive error reports from our monitor about this issue. Are there any thoughts about it?

**Comment by jquense** [comment]
seems like some user's environment is very old or unusual? I've not seen this before but looks like it's specific to some browser and version where Function.prototype.call, isn't considered a function

**Comment by MatthewHerbst** [comment]
Rollbar (our error reporter) shows me that all the errors on on Chrome 73+ on a Windows machine, coming from a few different users. It's possible that it's misreporting the browsers, but I can't think of any environment where `Array.prototype.slice`, `Function.prototype.bind`, or `Function.prototype.call` wouldn't be a function. Our customers are government users and their contractors, so while they might be using old software, there aren't using anything arcane.

I'll keep digging to see if I can find more information, though I'm somewhat stumped at this point.

**Comment by jquense** [comment]
The only other guess is they've got some plugin/extension or similar from their employer that is messing with their browers global environment?

**Comment by MatthewHerbst** [comment]
Possible, though I've seen the error from users of two different governments so I'm not sure.

**Comment by jquense** [comment]
Happy to remove the overly clever line in dom-helpers if would fix it. If you want to send over a PR there
