### ISSUE TITLE
How to show full event description

### ISSUE THREAD

**Issue by puruzio** [intljusticemission/react-big-calendar#144]
The event descriptions are abbreviated (eg., "All Day....") and multiple events are collapsed into "+x more".

What is the best way to remove these abbreviation and collapsing? If it involves custom coding, please provide some pointers. Thanks!!

**Comment by jquense** [comment]
there isn't any way to show them all, the dimension calculations are dependant on them being single lines. The event truncation is required right now, because there is no way for the month view to expand to fit the events, you can follow #147 for more info
