### ISSUE TITLE
Alignment issues with short events!

### ISSUE THREAD

**Issue by KhaledMohamedP** [intljusticemission/react-big-calendar#1440]
#### What's the current behavior?
If you book a 20 mins slot appointment back to back for one hour the alignment of these appointments doesn't align in top of each other (see screenshot below)

![Screen Shot 2019-08-29 at 2 55 58 PM](https://user-images.githubusercontent.com/5921853/63968247-45096380-ca6d-11e9-83ec-4be3f3c63f21.png)

Styling the library applies:

![Screen Shot 2019-08-29 at 2 56 23 PM](https://user-images.githubusercontent.com/5921853/63968245-433fa000-ca6d-11e9-8111-5703560810d3.png)

> Note this happens for 15 mins slots too* 😢 

#### What's the expected behavior?
Each event should stack in top of each other based on the start and end time. 

_I will add codesandbox tomorrow for anyone to test, for now I just wanted to get the discussion going and to see if anyone else is encountering this issue yet?_

**Comment by beaugunderson** [comment]
hey, i'm Khaled's coworker--Canvas (where we work) will sponsor $100 for a fix to this issue :)

**Comment by manhnguyenba** [comment]
I have the same issue. Is this an intended behavior or a bug?

**Comment by manhnguyenba** [comment]
@KhaledMohamedP @beaugunderson I try to detect the issue and found that. The bug didn't happen with version 0.18.0. You can check the changelog, if your app no need to use latest version you can downgrade to 0.18.0 to fix this. Is that $100 for me? :))

**Comment by KhaledMohamedP** [comment]
@manhnguyenba thanks for looking into this issue 🙏  

Someone needs to investigate what were the changes made between 0.18 and the current version that caused this behavior, and possibly try to opening a PR with a fix. 

We want to ensure this fix gets to everyone else using this library without using an older version of this library or forking it 😉 

Good luck 😃
