### ISSUE TITLE
Component typing fails with props in typescript

### ISSUE THREAD

**Issue by blakeglucas** [intljusticemission/react-big-calendar#1449]
#### Do you want to request a _feature_ or report a _bug_?

Report a _bug_

#### What's the current behavior?

Typing for custom Component rendering is broken.

```typescript
<Calendar
    components={{
         day: {
             event: CalendarDayEvent,
         }
    }}
    defaultView="day"
    events={this.props.events}
    localizer={calendarLocalizer}
/>
```
The Day Event element:
```typescript
export const CalendarDayEvent: React.FunctionComponent<EventProps> = (props: EventProps) => (
    // Component
)
```

The error:

`
Type '{ event: FunctionComponent<EventProps<Event>>; }' is not assignable to type '{ header?: Element | FunctionComponent<{}> | Component<{}, {}, any> | ComponentClass<{}, any> | undefined; event?: Element | FunctionComponent<{}> | Component<{}, {}, any> | ComponentClass<...> | undefined; }'.
`

Environment info: migrating a working implementation from Javascript to Typescript (Webpack 4.39.3, Babel 7.6.0 (ES6), react-big-calendar 0.22.0, typescript 3.6.2).

#### What's the expected behavior?

For the component to work correctly given the correct props.

If I change the `Components` interface defined in the index.d.ts file from

`event?: React.SFC | React.Component | React.ComponentClass | JSX.Element;`

to

`event?: React.FunctionComponent<EventProps<TEvent>> | React.Component | React.ComponentClass | JSX.Element;`

my code works as expected. Am I doing something wrong with my types, or is this just an issue with the declared types?

**Comment by golinmarq** [comment]
Somebody else experienced this?

**Comment by edellucien** [comment]
I do
