### ISSUE TITLE
onSelectEvent, how to get a time slot?

### ISSUE THREAD

**Issue by mayacode** [intljusticemission/react-big-calendar#145]
I try to align this very nice component for some specific needs. The story is quite simple. `onSelectEvent` I would like to take event data and clicked slot time (like 9:00 am, start time is enough)

Is this somehow possible to achieve?

**Comment by jquense** [comment]
hi there, the event select doesn't have the time slot. I'm not sure it makes sense there to have that info as you already have the even and so know what timeslots it's in. There are, however,  events that fire when selecting time slots (if the selectable prop is set) that gives this info
