### ISSUE TITLE
Unknown Props error

### ISSUE THREAD

**Issue by chaimaech** [intljusticemission/react-big-calendar#146]
Hello ! 

I've read through the documentation (or at least, I tried to debug by myself with it 😅 ) but I can't resolve my problem : I have this warning and I think this is the reason I can't see my calendar table :)

`Warning: Unknown props `startAccessor`, `endAccessor`, `onView`, `onNavigate`, `views`, `titleAccessor`, `allDayAccessor`, `dayFormat`, `selectRangeFormat`, `eventTimeRangeFormat`, `timeGutterFormat`, `monthHeaderFormat`, `dayHeaderFormat`, `dayRangeHeaderFormat`, `agendaHeaderFormat`, `agendaDateFormat`, `agendaTimeFormat`, `agendaTimeRangeFormat`, `formats`, `events`, `components`, `onHeaderClick`, `onShowMore` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
`

Pleaaaase, help me ! And sorry if it's an obvious matter ^^
(and sorry for my english)

**Comment by mayacode** [comment]
This is only the warning, I also see it. It is not preventing you calendar to appear on the page, so the reason why you cannot see it is somewhere else. Also mentioned #142

**Comment by chaimaech** [comment]
Okay, my bad, it was just some import issue so it's fixed ! I'm trying to figure out how to display my events now :)

Thanks for this quick response !
