### ISSUE TITLE
Wrong dates on pressing next week

### ISSUE THREAD

**Issue by idiglove** [intljusticemission/react-big-calendar#1460]
`<Calendar
                    style={style}
                    localizer={localizer}
                    defaultView={'week'}
                    views={['week']}
                    events={this.props.profileReducer.therapistSchedule}
                    defaultDate={new Date()}
                    selectable={'ignoreEvents'}
                    startAccessor="start"
                    endAccessor="end"
                    onSelectSlot={(e) => {this.handleSelectSlot(e)}}
                />`

Here is my calendar, im at a week in september and when I wanna go next, it goes back to August.

Please help

Thanks

**Comment by jansvantner** [comment]
I have a same issue

**Comment by idiglove** [comment]
> I have the same issue - it happened on the first week of October (30.9. - 6.10. 2019). react-big-calendar has shown August 29 - September 04. 2019.

This is same for me

No one is looking at this? It's almost a month. We need answers for this please

Thanks
