### ISSUE TITLE
Events not starting at correct date

### ISSUE THREAD

**Issue by flolege** [intljusticemission/react-big-calendar#1466]
#### Do you want to request a _feature_ or report a _bug_?
Bug
#### What's the current behavior?
Events start at 13:00 and ends at 14:30:

![image](https://user-images.githubusercontent.com/42407173/65525627-1bb6e880-def0-11e9-96a3-f9378d944979.png)

#### What's the expected behavior?

Events start at 14:00 and ends at 14:30

**Comment by KrallXZ** [comment]
I think #1408 is the same.
