### ISSUE TITLE
Monthly View not working in IE11 browser (using latest 0.22.1v) 

### ISSUE THREAD

**Issue by narechowdary** [intljusticemission/react-big-calendar#1469]
#### Do you want to request a _feature_ or report a _bug_?
bug
#### What's the current behavior?
Monthly view not working in IE11 showing blank calendar

![image](https://user-images.githubusercontent.com/17018025/65724204-80e81680-e075-11e9-96a8-03da4c23ec6e.png)

My Code:
<Calendar
	localizer={localizer}
	onView={onView}
	onNavigate={onNavigate}
	events={calEvents}
	startAccessor={'start'}
	endAccessor={'end'}
	defaultView={DEFAULT_VIEW}
/>

#### What's the expected behavior?

it should show monthly events with days. I'm using latest 0.22.1

**Comment by rafaelcorradini** [comment]
Set a min-height solved to me:
`
.rbc-calendar {
  min-height: 500px;
}
`

**Comment by narechowdary** [comment]
Still i don't see any changes after setting min-height like above..:(

**Comment by narechowdary** [comment]
I figured out the issue. Issue with styles, flex is not setting correctly in IE. i have applied below styles and it's working fine.

.rbc-calendar .rbc-month-view .rbc-month-row,
.rbc-calendar .rbc-month-view .rbc-month-row .rbc-row-content,
.rbc-calendar .rbc-month-view .rbc-month-row .rbc-row-content .rbc-date-cell
{
  flex: 1;
}

**Comment by rittikiert1138** [comment]
> I figured out the issue. Issue with styles, flex is not setting correctly in IE. i have applied below styles and it's working fine.
> 
> .rbc-calendar .rbc-month-view .rbc-month-row,
> .rbc-calendar .rbc-month-view .rbc-month-row .rbc-row-content,
> .rbc-calendar .rbc-month-view .rbc-month-row .rbc-row-content .rbc-date-cell
> {
> flex: 1;
> }

This code safe my day  Thank !
