### ISSUE TITLE
BUG: scrollToTime 00h:00m doesn't work

### ISSUE THREAD

**Issue by amok** [intljusticemission/react-big-calendar#1474]
#### Do you want to request a _feature_ or report a _bug_?
Report a bug

#### What's the current behavior?

scrollToTime prop does not work if the value's date has `00h 00m`

demo: https://codesandbox.io/embed/react-big-calendar-issue-scrolltotime-dp9zy
video: https://monosnap.com/file/dP5aEOh73L2K7Z7IfU2XJQtNnxdtJS

It mostly likely happens because of this check https://github.com/intljusticemission/react-big-calendar/blob/master/src/TimeGrid.js#L261 - scrollToTime is not being applied because `this._scrollRatio` is zero (false) (calculated at line https://github.com/intljusticemission/react-big-calendar/blob/master/src/TimeGrid.js#L275)

#### What's the expected behavior?

view scrolls to top when scrollToTime has been set to `00h:00m`

**Comment by Dragomir-Ivanov** [comment]
Used your `codesandbox` as a template, and tried your issue. It seems to work fine with:
```
const stt00 = new Date(new Date().setHours(0, 0));
const stt10 = new Date(new Date().setHours(10, 0));
```
Not that in your code `stt00` was  `new Date(new Date().setHours(0, 0, 0, 0));`

**Comment by amok** [comment]
@Dragomir-Ivanov that's true
as I understand it happens because "shouldUpdate" is being calculated basing on milliseconds https://github.com/intljusticemission/react-big-calendar/blob/master/src/TimeGrid.js#L261

```
this._scrollRatio = diffMillis / totalMillis
```

when you `setHours(hours, minutes)` milliseconds value is not `zero` (with a high enough level of probability :) )
but when you `setHours(hours, minutes, seconds, milliseconds)` the value of `milliseconds` is always `0` so the bug exist.

**Comment by Dragomir-Ivanov** [comment]
@amok I didn't looked at the code, however your advice seems reasonable. In any case, explicit check for 0 will be needed. Perhaps you can make a PR?

**Comment by amok** [comment]
@Dragomir-Ivanov done. pls take a look at #1501

**Comment by Dragomir-Ivanov** [comment]
@amok Good work, mate!
