### ISSUE TITLE
onScroll event callback [FEATURE REQUEST]

### ISSUE THREAD

**Issue by strongui** [intljusticemission/react-big-calendar#1476]
#### Do you want to request a _feature_ or report a _bug_?
New Feature

#### What's the current behavior?
Right now, when you are scrolling inside the week, day or agenda view, there is no way to hook into this scroll event

#### What's the expected behavior?

Ideally it's just a callback such as on `onSelectEvent`, so that I can respond to the scroll event.

In the global view, why I'm needing this is, that I've added a wrapper onto the Calendar, so that when the user clicks an event, I show a popup (popper) with the event info. I'm using the onSelectEvent callback event, to find the clicked DOM element, then using getBoundingClientRect() I position my popper above the event. _As of now I don't know of any better way to do this._

However, since the popper is positioned FIXED, when the user scrolls the popover is stuck in place. I'd just need a scroll event callback so that I can reposition the popper event

**Comment by strongui** [comment]
Ok, I found a better way around this. Using the `eventWrapper`. It's still a bit convoluted but it does work.

**Comment by nmolenaar** [comment]
@strongui Could you perhaps share your solution?

**Comment by strongui** [comment]
@nmolenaar 

There are a couple of parts to make this work. I'll try to outline them to get you in the right direction, because I can't just paste the code, it's too much in different files.

1. In your calendar component, in the components property you can pass a `eventWrapper` property.

```
// This is passed as a prop to my Calendar component, so the event wrapper can wrap the whole event if needed
const MyEventWrapper = !EventWrapper
  ? null
  : (eWrapperProps: EventWrapperProps<Event>) => (
      <EventWrapper originalProps={eventWrapperProps} {...eWrapperProps} />
    );

<Calendar
  ...HTMLElement,
  components={{
    ....,
    eventWrapper: MyEventWrapper,
    ...
  }}
/>
```

2. Now your `EventWrapper` can have any event hooks you want. Your event wrapper can be whatever you want, mine for example shows a popup on click with parameters passed into it. Basically the sky is the limit at this point. The `EventWrapper `will get the event object, PLUS `eWrapperProps `that you pass into your Calendar component. Does that make sense?
