### ISSUE TITLE
Is it possible to change the resource view to have the resources one the left side instead of the of the calendar.

### ISSUE THREAD

**Issue by hbellala** [intljusticemission/react-big-calendar#1479]
#### Do you want to request a _feature_ or report a _bug_?
Yes, is it possible to change the resource view to something like this?

<img width="541" alt="Screen Shot 2019-10-03 at 10 08 13 PM" src="https://user-images.githubusercontent.com/31451368/66176155-c59e1f80-e62a-11e9-827f-21faca282037.png">
#### What's the current behavior?
<img width="1081" alt="Screen Shot 2019-10-03 at 10 12 15 PM" src="https://user-images.githubusercontent.com/31451368/66176190-dcdd0d00-e62a-11e9-8b5c-2cadc5a8b7fe.png">

I can make it like this (ignore the padding was debugging my styling) but I have been stuck on changing it any further: all suggestions are welcomed:
<img width="557" alt="Screen Shot 2019-10-03 at 10 13 22 PM" src="https://user-images.githubusercontent.com/31451368/66176248-04cc7080-e62b-11e9-926f-80973ed29b03.png">

**Comment by alundberg1** [comment]
Were you able to figure this out? I'm trying to do something similar

**Comment by BagchiMB** [comment]
@hbellala 
Were you ale to do this ??
I have a requirement for this
