### ISSUE TITLE
How to change view?

### ISSUE THREAD

**Issue by peterzanetti** [intljusticemission/react-big-calendar#1482]
How can I programmatically change view?

This is not working:

 this.setState({ view: 'agenda' });

**Comment by eightshone** [comment]
http://intljusticemission.github.io/react-big-calendar/examples/index.html#prop-defaultView

**Comment by peterzanetti** [comment]
Thanks, defaultView works just fine for me, what I'm trying to do is change the view state from a custom function after the Calendar is rendered. Example being a custom button to change view, or another event that triggers a function to change the calendar view state.

That's where I'm trying to access the view state but it is not working.

**Comment by eightshone** [comment]
You can use state. Make the `defaultView` take its value from the state (you can always use the `useState` hook if you don't want to use a class) and make your function change the state value because changing state will re-render the component.

**Comment by peterzanetti** [comment]
I have tried this:

<Calendar
defaultView={myDefaultView}

^ this is getting set by constructor on initial render without issue.

But if I later call a function like this:

handleChangeView(){
this.setState({myDefaultView: 'agenda'})
}

...this changes the defaultView value, but does not re-render the component, or change the view.

**Comment by cutterbl** [comment]
I do this by using [view](http://intljusticemission.github.io/react-big-calendar/examples/index.html#prop-view) and [onView](http://intljusticemission.github.io/react-big-calendar/examples/index.html#prop-onView) together, which sorta tells RBC that it's controlled. Internally, when a `view` is to change, it calls the method you apply through `onView` to change your state variable. If you change `view` programmatically elsewhere (like some external nav), it'll rerender the calendar view.

**Comment by ajoslin103** [comment]
```
handleChangeView(){
   this.setState({myDefaultView: 'agenda'})
}
```

should be

```
handleChangeView(){
    this.setState({defaultView: 'agenda'})
}
```
you were inserting a new state value using the name of your variable?

**Comment by peterzanetti** [comment]
> ```
> handleChangeView(){
>    this.setState({myDefaultView: 'agenda'})
> }
> ```
> 
> 
> should be
> 
> 
> ```
> handleChangeView(){
>     this.setState({defaultView: 'agenda'})
> }
> ```
> 
> 
> you were inserting a new state value using the name of your variable?

No, this doesn't work either. I truly wish it did, like every other React component on the planet, but no, this does not work.

**Comment by cutterbl** [comment]
I can't see how it wouldn't. This [CodeboxSandbox Example](https://codesandbox.io/embed/rbc-external-view-control-jwccs?fontsize=14&hidenavigation=1&theme=dark) shows the exact same principle in use, just using the `useState` hook and a function component, instead of a class component with `setState`. It's a quick example, but you'll see you can control the view state using the 'External View Changer' controls at the top of the interface.

**Comment by peterzanetti** [comment]
>, just using the `useState` hook and a function component, instead of a class component with `setState`. 

And therein lies the difference. Hooks and functional components are not a direct replacement for class components and setState. They are completely different worlds. So, I remain unsurprised and very disappointed that this doesn't work. I've invested months into this calendar (and there is no going back now) and despite the very advanced calendar we've built for our app, we are lacking the ability to do the simplest of simple React things, because someone was obsessed with Hooks.

**Comment by peterzanetti** [comment]
On a hunch I decided to try this one more time:

THIS finally worked:

1. default state for both:
this.state = {view: 'month', defaultView: 'month'}

2. function to change:

handleChangingView = (view) => {this.setState({view: view, defaultView: view})}

3. additional callback function for OnView event:

handleOnViewChange = e => {this.setState:({view: e, defaultView: e})}

4. <Calender view={view} defaultView={defaultView} />

What a mess.

**Comment by RedNoo** [comment]
> http://intljusticemission.github.io/react-big-calendar/examples/index.html#prop-defaultView

404 NOt found

**Comment by cutterbl** [comment]
@RedNoo the repo changed ownership very recently, and these pasted links don't auto update. Here's the new link http://jquense.github.io/react-big-calendar/examples/index.html#prop-defaultView

**Comment by suhailvs** [comment]
> http://intljusticemission.github.io/react-big-calendar/examples/index.html#prop-defaultView

https://jquense.github.io/react-big-calendar/examples/index.html#prop-defaultView
