### ISSUE TITLE
Calendar Displaying All Days on Left Hand Side.

### ISSUE THREAD

**Issue by Newman2393** [intljusticemission/react-big-calendar#1483]
#### What's the current behavior?
Hello, I'm having a strange issue where all of the days and events in the calendar are pushed to the left side of my window.

I thought the issue may be related to the need for a defined height on the container of the Calendar, but even after giving the container both a height and width value the issue persists.

This is what my code looks like:

```
const localizer = momentLocalizer(moment);

export const Hello: CcAppComponent = () => (
    <Segment style={{height: '1000px', width: '1000px'}}>
    <Calendar
        height={100}
        localizer={localizer}
        events={events}
        step={60}
        showMultiDayTimes
        startAccessor="start"
        endAccessor="end"
      />
      </Segment>
);
```
And this is how it renders.

<img width="342" alt="Bad Calendar" src="https://user-images.githubusercontent.com/36941037/66260959-96ef8880-e793-11e9-99aa-2c22edfdb47d.PNG">

I was not able to find a similar report, so if there is another similar post that has a solution, a link would be greatly appreciated.

Thank you for any assistance on this.

**Comment by eightshone** [comment]
import the css

**Comment by eightshone** [comment]
https://github.com/intljusticemission/react-big-calendar#custom-styling

**Comment by Newman2393** [comment]
This did it. Thank you for the quick response. Feel silly for not realizing I was missing this.
