### ISSUE TITLE
Request a new feature: event card view background color

### ISSUE THREAD

**Issue by np2010** [intljusticemission/react-big-calendar#1487]
Request a new feature.

1. Event background color: 
   Calendar renders all events with the same background-color, it would be nice to allow the user to define the color based on event type or something. 
2. Allow users to take the complete control of Event Card View, so the user can add more components on it instead of just Title.

**Comment by eightshone** [comment]
http://intljusticemission.github.io/react-big-calendar/examples/index.html#prop-eventPropGetter
I think the `eventPropGetter` will do the job as it passes classnames and styles. Try to use that and let me know.

**Comment by marciok** [comment]
It does work! 
Example:
```
<Calendar
   ...
    eventPropGetter={(event, start, end, isSelected) => {
        return { className: "foobares", style: { backgroundColor: 'red' } }
      }}
/>
```
