### ISSUE TITLE
how to customized some days's style in the month view?

### ISSUE THREAD

**Issue by shikelong** [intljusticemission/react-big-calendar#149]
Now I know I can customized some event label style by `eventPropGetter`. 
**But now I want custom some days's cell style . not the event.**, And I want to select a day cell in the month view. But Seem no api support select a day cell in the month view.

Regards.

**Comment by bsjaffer** [comment]
following..

**Comment by andreacab** [comment]
got something but is a bit hacky, let me know @shikelong if you are interested
