### ISSUE TITLE
ReactBigCalendar is not importing

### ISSUE THREAD

**Issue by Anjali99fusion** [intljusticemission/react-big-calendar#1491]
Tried everything, the package is shownig in node modules.
Added this code at the top
**import BigCalendar from 'react-big-calendar';**
But still, it is showing error on BigCalendar in my webpack
[http://prntscr.com/phxop4](url)

But the line to import this is already added. Please tell me what I am doing wrong

**Comment by jquense** [comment]
link doesn't go anywhere! This sounds like a problem with your webpack config or local environment. Not sure what else we can do here. Suggest asking on the webpack support channels
