### ISSUE TITLE
How to ignore DST with momentjs

### ISSUE THREAD

**Issue by cassio-nuke** [intljusticemission/react-big-calendar#1492]
Hi,

I'm using moment.js with this library and I have to ignore Summer Time. How can I do that?

**Comment by cutterbl** [comment]
React-Big-Calendar always uses your browser local Date by default, so if you're in one timezone that uses DST, and need to display a calendar that's using a timezone that does not, you'll have to configure RBC to switch. I have a [repo with an example of TZ switching](https://github.com/cutterbl/react-big-calendar-with-timezones).
