### ISSUE TITLE
Calendar initialization fails on Safar due to RangeError

### ISSUE THREAD

**Issue by jcquinlan** [intljusticemission/react-big-calendar#1502]
#### Do you want to request a _feature_ or report a _bug_?
Bug report

#### What's the current behavior?
Calendar initialization fails in Safari due to `RangeError: Array size is not a small enough positive integer.`

<img width="1046" alt="Screen Shot 2019-10-21 at 10 52 02 PM" src="https://user-images.githubusercontent.com/5533834/67259859-6aa35f80-f455-11e9-8944-8691706e6343.png">

Reproducible on Safari, at version 0.22.1, 0.21.0, and 0.19.1

Works fine on Chrome at all the above versions.

#### What's the expected behavior?
The calendar inits without this error.

**Comment by jcquinlan** [comment]
Long story short, the issue was caused by Safari and Chrome parsing Date objects different, Safari was considering my Date objects for the `min` and `max` props to be invalid, and prop type validation didn't catch it because they were both still instances of Date.

**Comment by Poky85** [comment]
Happens when invalid date is passed in `min` or `max` prop. Safari considers dates as invalid in different manner than Chrome, so error occurs more often in Safari.

E.g. those dates are invalid in Safari but not in Chrome

```javascript
<Calendar
            min={new Date('2020, 1, 1, 07:00')}
            max={new Date('2020, 1, 1, 23:00')}
          />
```
