### ISSUE TITLE
Any example for fetching events from remote api

### ISSUE THREAD

**Issue by AMHZR** [intljusticemission/react-big-calendar#1508]
I tried to link the Big Calendar with our remote API for resources planning were we get data from remote API's and the data looks like 

> [{
>       'id': 0,
>       'tile': '55487_300951_SPECIAL 95',
>       'start': '2019-10-27T00:00:27',
>       'end': '2019-10-27T00:00:27',
>       'resourceId': 1,
>     },
>     {
>       'id': 1,
>       'tile': 'TG_HQ_SPECIAL 95',
>       'start': '2019-10-26T23:57:31',
>       'end': '2019-10-26T23:57:31',
>       'resourceId': 1,
>     },
>     {
>       'id': 2,
>       'tile': 'AUTO_P_DIESEL',
>       'start': '2019-10-26T23:42:14',
>       'end': '2019-10-26T23:42:14',
>       'resourceId': 2,
>     },]

when we pass this data to  <Calendar
      events={events} it throws an error stating that 

### `Uncaught TypeError: d[("get" + method)] is not a function
`

**Comment by MadjidSahki** [comment]
Your endpoint should return a Date type proprety for end and start, not a string and it should work

`[{
      'id': 0,
      'title': '55487_300951_SPECIAL 95',
      'start': new Date('2019-10-27T00:00:27'),
      'end': new Date('2019-10-27T00:00:27'),
      'resourceId': 1
    },
    {
      'id': 1,
      'title': 'TG_HQ_SPECIAL 95',
      'start': new Date('2019-10-26T23:57:31'),
      'end': new Date('2019-10-26T23:57:31'),
      'resourceId': 1
    },
    {
      'id': 2,
      'title': 'AUTO_P_DIESEL',
      'start': new Date('2019-10-26T23:42:14'),
      'end': new Date('2019-10-26T23:42:14'),
      'resourceId': 2
    }]`
