### ISSUE TITLE
Request api for onMouseOver event

### ISSUE THREAD

**Issue by rockcs1992** [intljusticemission/react-big-calendar#1511]
#### Do you want to request a _feature_ or report a _bug_?
request a feature
#### What's the current behavior?
when use the mouse to hover over an event, there is no api interface for adding a `onMouseEnter` or `onMouseOut` event

#### What's the expected behavior?
Expose an API used for firing callback function when the mouse enters and leaves an event. Just like `onSelectEvent`, might be called something like `onMouseOverEvent`, `onMouseLeaveEvent`.

**Comment by rockcs1992** [comment]
https://github.com/intljusticemission/react-big-calendar/pull/1512

I created a small PR for the features, please let me know how you think about this 😊

**Comment by AlbertoFardin** [comment]
I also need these events.
Please approve his PR

**Comment by mikeyyyzhao** [comment]
+1 need these events. Please approve this PR

**Comment by bvanhou** [comment]
+1
