### ISSUE TITLE
Enable semantic-cli for releasing to npm

### ISSUE THREAD

**Issue by KhaledMohamedP** [intljusticemission/react-big-calendar#1519]
New Feature
---
Type: `Build setup`

### What's the current behavior?
The author has merged a bunch of small bug fixes and a giant new feature (ref #1473) to master, but users are patiently waiting for the new version to get released.

### Solution
Each PR that gets merged should be released automatically to npm & updating git release tags statment, relying on the git messages committed by the contributor. 

I will recommend using something like https://github.com/semantic-release/semantic-release

but open to alternative solutions!

**Comment by jquense** [comment]
I don't probably have the time to set this up, but if you wanna work on a PR to add (probably via github actions) I'm open to it 👍
