### ISSUE TITLE
 Component life cycle update

### ISSUE THREAD

**Issue by Hector26** [intljusticemission/react-big-calendar#1526]
Hi guys, I want to know if you are currently working on the life cycle update of the component.

I am using the most recent version of the calendar component "0.23.0" and my version of react is "16.11.0". and the following warning appears in several internal components of it.

![image](https://user-images.githubusercontent.com/23046310/68793657-141fe000-0613-11ea-9954-0596b11ea632.png)

This does not affect the expected operation, but I want to solve the issue of warnings in my project

Can you help me, please.

Thanks guys

**Comment by jeonghoheo** [comment]
Hello I have the same problem
I always see that warning...

I want to know to solve that

**Comment by antondomratchev** [comment]
@jeonghoheo This would require updating the lifecycle hook names to be updated with UNSAFE_ prefix. To get rid of the warning. This should  be a pretty simple change.

The better solution would be to transition to the newest lifecycle hooks or abandon Class based components and transition to hooks API. That would be a much bigger undertaking though.

**Comment by jacksonrayhamilton** [comment]
Looks like this is solved in https://github.com/intljusticemission/react-big-calendar/pull/1515.

@jquense does that look good to merge/publish?
