### ISSUE TITLE
"+more" is not displaying in Custom Event when navigate from/to Week/Day/Agenda or Back/Next clicks from initally rendered month view

### ISSUE THREAD

**Issue by subbaraovnrt** [intljusticemission/react-big-calendar#1531]
#### Do you want to request a _feature_ or report a _bug_?
bug
#### What's the current behavior?
As per use case event is required to display in multi line, this is good in month view when initial load/rendered. But when I navigate from/to Week/Day/Agenda or Back/Next buttons clicks then "+more" is not displaying any more noticed events are fully occupied date cell.

Initial page load or when page refresh displays +more:
![InitialRenderedMonthView](https://user-images.githubusercontent.com/36386733/69252095-184e7f00-0b78-11ea-8041-badb0d525156.PNG)

After navigation not displaying +more:
![NavigatedMonthView](https://user-images.githubusercontent.com/36386733/69252619-f0135000-0b78-11ea-9ec5-b49ba6a53f49.PNG)

Project used below calendar version:
"react-big-calendar": "^0.22.1"

https://codesandbox.io/s/flamboyant-hill-zfrqr?from-embed

#### What's the expected behavior?
'+more' should display when navigate from/to 'Week/Day/Agenda' or 'Back/Next' clicks

**Comment by subbaraovnrt** [comment]
https://codesandbox.io/s/flamboyant-hill-zfrqr?from-embed

**Comment by panda6412** [comment]
have same issue
