### ISSUE TITLE
update docs

### ISSUE THREAD

**Issue by noahehall** [intljusticemission/react-big-calendar#1534]
should be import 
```import * as BigCalendar from 'react-big-calendar';```

in the basic calendar source in the docs i just spent 30 minutes on figuring out wtf is wrong with my copy paste skillz

**Comment by ajoslin103** [comment]
that will only work if you rename the Component to <BigCalendar> in the source... 

in my case I was trying out multiple Calendar plugins all of which wanted to use the same <Calendar> component  -- so I used: import { Calendar as BigCalendar, momentLocalizer } from 'react-big-calendar';   Then I could use <BigCalendar> in my source.

you do have to include the bit: const localizer = momentLocalizer(moment); or nothing shows up (at least it didn't for me)

+1 for BC - it's the best one I've found yet !!

**Comment by bubbleswap** [comment]
> that will only work if you rename the Component to in the source...
> 
> in my case I was trying out multiple Calendar plugins all of which wanted to use the same component -- so I used: import { Calendar as BigCalendar, momentLocalizer } from 'react-big-calendar'; Then I could use in my source.
> 
> you do have to include the bit: const localizer = momentLocalizer(moment); or nothing shows up (at least it didn't for me)
> 
> +1 for BC - it's the best one I've found yet !!

Thank you for sharing this....I was going crazy for hours swapping 'BigCalendar' out with 'Calendar' to no avail!
