### ISSUE TITLE
are there docs for the layout algorithms?

### ISSUE THREAD

**Issue by noahehall** [intljusticemission/react-big-calendar#1545]
any help on this? 
I noticed it first here: https://github.com/intljusticemission/react-big-calendar/blob/master/examples/demos/createEventWithNoOverlap.js#L15

I'm pretty sure im just missing it somewhere, 

but where the fish are the layout algorithms in the docs

thx

**Comment by mikeyyyzhao** [comment]
@noahehall were you able to find any documentation on this?
