### ISSUE TITLE
Give the possibility to change the buttons Today, Back and Next

### ISSUE THREAD

**Issue by Angelk90** [intljusticemission/react-big-calendar#1547]
#### Do you want to request a _feature_ or report a _bug_?
Feature

#### What's the current behavior?

At the moment in the calendar on the left there are the following buttons arranged in the following way:
Today, Back and Next.

#### What's the expected behavior?

I need to be able to change the arrangement of the following buttons in the following way:
Back, Today and Next.

**Comment by jquense** [comment]
You can do that that a custom toolbar, or can get fancy with css and `order`

**Comment by Angelk90** [comment]
@jquense :  you can give me an example, I'm not able to understand.

**Comment by Webtransformer** [comment]
> 
> 
> @jquense : you can give me an example, I'm not able to understand.

You can do something like this (flexbox):

`
.rbc-btn-group {
    display: flex;
}

.rbc-btn-group button:nth-child(1) {
    order: 3
}

.rbc-btn-group button:nth-child(2) {
    order: 1
}

.rbc-btn-group button:nth-child(3) {
    order: 2
}
`
