### ISSUE TITLE
Calendar Month view issues

### ISSUE THREAD

**Issue by lriken** [intljusticemission/react-big-calendar#1550]
#### Do you want to request a _feature_ or report a _bug_?
feature
#### What's the current behavior?
Please provide me the solution for below
1. I want to make the month view events to be clickable. 
2. the placeholders on a particular day on Month view like '+2' and '+5' are not expanding. How to solve that?
3. On Agenda and Today button the events are shown from tomorrow not today. How to fix  the same.

**Comment by jquense** [comment]
Hi I see you didn't follow our issue template, making it extremely hard to provide any meaningful help. The best way to get help would be to provide actionable details and code examples of what is not working or what you want to do thanks
