### ISSUE TITLE
'dateFnsLocalizer' is not exported from 'react-big-calendar'.

### ISSUE THREAD

**Issue by makis-spy** [intljusticemission/react-big-calendar#1566]
#### Do you want to request a _feature_ or report a _bug_?
BUG
#### What's the current behavior?

Attempted import error: 'dateFnsLocalizer' is not exported from 'react-big-calendar'.

"react-big-calendar": "^0.23.0",
"react": "^16.9.0",

#### What's the expected behavior?

Export dateFnsLocalizer

**Comment by joaobsantos** [comment]
Change dateFnsLocalizer to DateLocalizer, its in the breaking changes

**Comment by TrySound** [comment]
@makis-spy It was not published yet.

**Comment by makis-spy** [comment]
Oh thanks guys!
Sorry :)
