### ISSUE TITLE
react-big-calendar does not display anything but grid

### ISSUE THREAD

**Issue by nwabdou85** [intljusticemission/react-big-calendar#157]
In my case, react-big-calendar does not display antthing on month and agenda, but displays some empty grids on week and day and without styles.

here is my code :+1: 

```

import React, { Component, PropTypes } from 'react';
import {render} from 'react-dom';
import {Meteor} from 'meteor/meteor';
import NavPro from '/imports/ui/components/NavPro.jsx';
import FooterPro from '/imports/ui/components/FooterPro.jsx';
import  'react-big-calendar/lib/css/react-big-calendar.css'
import BigCalendar from 'react-big-calendar';
import moment from 'moment';
import Events from './Events.jsx'; // https://github.com/jquense/react-big-calendar/blob/master/examples/events.js 



const styled={
    agenda:{
    	backgroundColor: '#af4a68',
    },
    calendar:{
      marginTop:'5vh',
    },
  };


BigCalendar.momentLocalizer(moment);




export default class Agenda extends Component {


 constructor(props, context)
    {

  super(props, context);
        this.context = context;
        this.state = {
          events: Events,
          culture: 'fr',
        };
        BigCalendar.setLocalizer(
        BigCalendar.momentLocalizer(moment)
        );
          this.handleSelectSlot = this.handleSelectSlot.bind(this);
          this.handleSelectEvent = this.handleSelectEvent.bind(this);
    }

    handleSelectSlot({start, end})
    {
        //create an event with title "Test"
        console.log("handleSelectSlot: " + start + " - " + end);
        this.state.events.push({start: start, end: end, title: "Test"});
        this.setState({});

    }

    handleSelectEvent()
    {
        //just for example
        console.log("handleSelectEvent: " + JSON.stringify(arguments));
    }

    EventWeek(props)
    {
        return <strong>{props.event.title}</strong>
    }

    EventAgenda(props)
    {
        return <em>{props.event.title}</em>
    }




  render() {
  console.log('this.state.events',this.state.events);

    return (
    	<div style = {styled.agenda} id="agenda">
	      <div className="row">
	        <div className="col-xs-12  col-sm-12 col-md-12 col-lg-12">
	          <NavPro />
	        </div>
	       </div>
            

            <div className="row">
              <div className="col-xs-1 col-sm-1 col-md-1 col-lg-1">
              </div>
              <div className="col-xs-10 col-sm-10 col-md-10 col-lg-10">
                <BigCalendar
                  selectable
                  popup
                  events={this.state.events}
                  onSelectSlot={this.handleSelectSlot}
                  onSelectEvent={this.handleSelectEvent}
                  defaultDate={new Date()}
                  style={styled.calendar}
                  eventPropGetter={e => ({ className: 'test-class'})} /* Here you can define a style for the element */
                  components={{
                  event: this.EventWeek,
                  agenda: {
                  event: this.EventAgenda
                   }
                   }}/>
             </div>
             <div className="col-xs-1 col-sm-1 col-md-1 col-lg-1">
             </div> 
            </div>  




	         <div className="row">
	           <div className="col-xs-12  col-sm-12 col-md-12 col-lg-12">
	             <FooterPro />
	           </div>
	         </div>
	    </div>
    );
  }
}
```

Can you help, please ??

**Comment by jquense** [comment]
you probably need to use the startAccessor and endAccessor to point the calendar to the right properties on your events. I don't know what they look like so I can't really help with that

**Comment by nwabdou85** [comment]
@jquense Thank's for your help, I fixe it by setting an explicit height on the calendar.

But it still in english, any idea on how to make it in french??

**Comment by jquense** [comment]
looks like you are using Moment, follow their documentation for globally setting cultures

**Comment by nwabdou85** [comment]
ok

**Comment by nwabdou85** [comment]
@jquense event this example [https://github.com/intljusticemission/react-big-calendar/blob/master/examples/demos/cultures.js](url) , in the documentation, does not work, at least, for me;  it throws an error: Error: Cannot find module 'globalize/lib/cultures/globalize.culture.en-GB' and other languages. Can you help please??

**Comment by jquense** [comment]
that exmaple uses globalize not moment. check out the internationalization documention for setting cultures in moment: http://momentjs.com/docs/#/i18n/

**Comment by nwabdou85** [comment]
@jquense me too I'm using globalize

**Comment by jquense** [comment]
oof sorry, i'm really not an expert on setting up globalize 1.x.x, we use the older 0.1.x which is WAAAY simpler to setup

**Comment by jquense** [comment]
you can maybe use this as a starting point tho: https://github.com/jquense/react-widgets/blob/v4/.storybook/configure-globalize-new.js

**Comment by nwabdou85** [comment]
@jquense does not resolve my problem; thank's for your effort.

**Comment by Paelsis** [comment]
Have same problem.
Cannot get it work. I use style={style} with the proper .css file but only grid displayed, no hours, no days just today in the week calendar. Could it be that I use it together with material-ui ?

**Comment by hoanghiep106** [comment]
When you push 
this.state.events.push({start: start, end: end, title: "Test"});
try 
this.state.events.push({start: moment(start), end: moment(end), title: "Test"});
or change the events in example file start and end to moment()
Because Safari somehow doesn't recognize new Date() in your example file.

**Comment by f-ricci** [comment]
@hoanghiep106 thanks for clarifying this. I was using

`new Date(eventDate)` 
instead of 
`moment(eventDate)`

when creating my events objects causing Safari to not recognise any event.

**Comment by KrishnaPayyavula** [comment]
@

> [](url)

> ### 

> [`__`](

- 

- [ ] @ #

- [ ] 

- [url](`

> _url_

`)

)
