### ISSUE TITLE
Event not rendering on week start date

### ISSUE THREAD

**Issue by bsjaffer** [intljusticemission/react-big-calendar#159]
When there is an event on Week start of the date (sunday) , then event is not filtered from to render it. 

It seems there is a bug in eventLevels.inrange method as it not check greater than or equal to .

Is this an issue or any other way to render event on weekstart date and ends on same day.

**Comment by jquense** [comment]
you can see from the demo in the documenting that plenty of events start and end on the same day, the first day of the week. Your start and end dates may be have no duration  which would be a problem

**Comment by bsjaffer** [comment]
In the basic example please change the first event like below and you will get the issue 

```
 {
                'title': 'All Day Event',
                'allDay': true,
                'start': new Date(2015, 3, 19),
                'end': new Date(2015, 3, 19)
            },

```

**Comment by jquense** [comment]
that event has no length which is why it doesn't display. the end date should be `new Date(2015, 3, 20)`. The behavior you are seeing is correct, events should not have the same start and end time

**Comment by bsjaffer** [comment]
if its an all day event and starts and ends at the same day then why i should increment a new date. 
Also this is not working only for the week start and working fine for other days. 

```
// working one
{
	  'title': 'All Day Event',
	  'allDay': true,
	  'start': new Date(2015, 3, 6),
	  'end': new Date(2015, 3, 6)
	}

// not working one
{
	  'title': 'All Day Event',
	  'allDay': true,
	  'start': new Date(2015, 3, 5),
	  'end': new Date(2015, 3, 5)
	}]
```

**Comment by jquense** [comment]
> if its an all day event and starts and ends at the same day then why i should increment a new date. 

because that's how the math works

**Comment by bsjaffer** [comment]
sorry for asking it again. I completely understand what you are trying to tell, but as you see my earlier comment, its working for monday but only for sunday(weekstart date)  its not working .

**Comment by tc0087** [comment]
Anyone have a solution for this? I am encountering the same problem. BUMP

**Comment by jquense** [comment]
The solution, as noted above, is to make sure all events aren't zero milliseconds long. I'd also accept a PR that handles the inconsistency.
