### ISSUE TITLE
Can never get calendar grid to display: Unknown props

### ISSUE THREAD

**Issue by zeneben** [intljusticemission/react-big-calendar#160]
I've copied and pasted the code in the basic demo and the 'Getting Started' doc exactly, and I keep getting the message:

> warning.js:44 Warning: Unknown props `startAccessor`, `endAccessor`, `onView`, `onNavigate`, `views`, `titleAccessor`, `allDayAccessor`, `dayFormat`, `selectRangeFormat`, `eventTimeRangeFormat`, `timeGutterFormat`, `monthHeaderFormat`, `dayHeaderFormat`, `dayRangeHeaderFormat`, `agendaHeaderFormat`, `agendaDateFormat`, `agendaTimeFormat`, `agendaTimeRangeFormat`, `formats`, `events`, `components`, `onHeaderClick`, `onShowMore` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
>     in div (created by MonthView)
>     in MonthView (created by Calendar)
>     in div (created by Calendar)
>     in Calendar (created by Uncontrolled(Calendar))
>     in Uncontrolled(Calendar) (created by MyCalendar)
>     in div (created by MyCalendar)
>     in MyCalendar (created by App)
>     in div (created by App)
>     in div (created by App)
>     in App

My App.js is very basic:

```
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import BigCalendar from 'react-big-calendar';
import moment from 'moment';
import '../node_modules/react-big-calendar/lib/css/react-big-calendar.css'


// Setup the localizer by providing the moment (or globalize) Object
// to the correct localizer.
BigCalendar.momentLocalizer(moment); // or globalizeLocalizer

const myEventsList = [];

const MyCalendar = props => (
  <div>
    <BigCalendar
      events={myEventsList}
      startAccessor='startDate'
      endAccessor='endDate'
    />
  </div>
);


class App extends Component {
  render() {
    return (
      <div className="App">
        <div className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h2>Welcome to React</h2>
        </div>
        <div>
          <MyCalendar />
        </div>
      </div>
    );
  }
}

export default App;

```

**Comment by zeneben** [comment]
Here is what is rendered: 
![screen shot 2016-08-16 at 12 20 44 pm](https://cloud.githubusercontent.com/assets/18199191/17712695/f4bfb1de-63ab-11e6-98a9-4bcc6d5b6b2c.png)

**Comment by jquense** [comment]
you have to set an explicit height on the calendar

**Comment by zeneben** [comment]
Ah, the warnings in the console made me think it was broken. Would be nice to get rid of those, but this solved the issue. Thanks!
