### ISSUE TITLE
Calendar not selectable in new window

### ISSUE THREAD

**Issue by jlin816** [intljusticemission/react-big-calendar#161]
```
       <Popout>
          <div style={{height: '100vh', padding: 25}}>
            <BigCalendar
              selectable
              events={eventData}
              defaultView='week'
              defaultDate={new Date(2016, 3, 1)}
              onSelectEvent={() => this.selectBigCalendarEvent()}
              onSelectSlot={() => this.selectBigCalendarSlot()}
            />
          </div>
        </Popout>
```
When I select an event, this.selectBigCalendarEvent() is called, but when I try to select a slot this.selectBigCalendarSlot() is not called and nothing (no gray selection, no event) appears on the calendar itself. 

Not sure if this is related, but I'm using react-popout (which just wraps window.open in a component) to render the calendar in a new window.

**Comment by jquense** [comment]
I'm not actually sure what might be the cause there, presumably because the component is calculating selection stuff from the wrong `window`?

**Comment by fergyfresh** [comment]
Selectable is a Boolean. I'm assuming you will have to set `selectable=true`, where you only have `selectable`. Also, if you look at the docs it is more clear. The function onSelectSlot requires the Boolean `selectable` to be true, where onSelectEvent does not. The bug is that you don't have selectable set to anything and is false by default.

**Comment by jlin816** [comment]
Is there any solution/workaround you can think of, given how selection works in the big calendar?

**Comment by jlin816** [comment]
I've resolved the issue. In case anyone is trying to do a similar task: it turns out that this is essentially a compatibility issue with react-popout -- it renders the actual BigCalendar component in a div on the originating window and simply injects the HTML into the new popout window, so all the selectable interactivity still lives in the original window. Not really any good way to make these two work together well, AFAIK.
