### ISSUE TITLE
step

### ISSUE THREAD

**Issue by dkunzman1** [intljusticemission/react-big-calendar#167]
How do you initialize the step interval for every 15 minutes?

step={new Number(15)}  

This is returning an object, so it might be a more general jsx question but have searched the web and can't find a solution.

Thanks, D

**Comment by jquense** [comment]
just: `step={15}` 

in Javascript you almost never ever ever want to use the Object versions of the primitives (`Number`, `String`, `Boolean`)

**Comment by dkunzman1** [comment]
It has no affect on the outcome of the calendar var Scheduling = React.createClass({
  render() {
    return (
      <div className="pageBorder bigcalendar">
      <BigCalendar
        events={events}
        min={new Date(new Date(new Date().setHours(8)).setMinutes(0))}
        max={new Date(new Date().setHours(19))}
        scrollToTime={new Date(new Date().setHours(19))}
        startAccessor='startDate'
        endAccessor='endDate'
        defaultView='day'
        view='day'

        onView = {alert("onView")}
        defaultDate={new Date()}
        selectable
        step={15}
        onSelectSlot={(slotInfo) => alert(
          `selected slot: \n\nstart ${slotInfo.start.toLocaleString()} ` +
          `\nend: ${slotInfo.end.toLocaleString()}`
        )}
      />
    </div>
    )
  }
