### ISSUE TITLE
[BUG] Selecting a Timeslot gives wrong dates (at least Week and Day view)

### ISSUE THREAD

**Issue by rafsoaken** [intljusticemission/react-big-calendar#17]
Just go to the demo http://intljusticemission.github.io/react-big-calendar/examples/index.html
and select the "Selectable" demo calendar. 

Dates displayed in the popup once you click in week/day views are incorrect. Month view popups sometimes show the correct date (in a MM/DD/YYYY format).

Same issue with my npm calendar library, where I have no min/max props set on the calendar.

**Comment by jquense** [comment]
thanks for the heads up. should be resolved quickly!

**Comment by rafsoaken** [comment]
Thanks!
