### ISSUE TITLE
[Styling] Vertical cells have different widths in time view

### ISSUE THREAD

**Issue by mattbilbow** [intljusticemission/react-big-calendar#170]
First up, thanks for the amazing module. It's saving me a LOT of time.

Just wanted to point a styling issue that causes the calendar to look a little wonky in time view mode. I'll have a got at patching this myself, but you might get around to is sooner.

As you can see in the screenshots below, 'cells' within the a single column end up having different widths, which causes the border align incorrectly. In most cases only by a pixel but it's enough to play with my OCD ;D

![screen shot 2016-09-08 at 12 05 15](https://cloud.githubusercontent.com/assets/1419220/18347268/a1355d16-75bc-11e6-8619-b9bc16ab5e39.png)

![screen shot 2016-09-08 at 12 04 57](https://cloud.githubusercontent.com/assets/1419220/18347269/a1361f8a-75bc-11e6-83c9-4c17b5eebacc.png)

![screen shot 2016-09-08 at 12 04 38](https://cloud.githubusercontent.com/assets/1419220/18347270/a15dfbe0-75bc-11e6-9398-d574b42438df.png)

**Comment by jquense** [comment]
yeaaah this is seems to be a Chrome issue with subpixels and rounding. I don't know why it happens, I've tried to fix it before but sometimes it just renders some percentage differently. I sort of stopped trying to fix it when I noticed that Google calendar suffers the same problem at certain widths :P

**Comment by mattbilbow** [comment]
Fair enough, I can see now that they're suffering from the safe thing. Very odd. I'll close the issue :)
