### ISSUE TITLE
MWD Tabs floating outside of container. 

### ISSUE THREAD

**Issue by adjavaherian** [intljusticemission/react-big-calendar#174]
MWD Tabs floating outside of container on Safari only, 1024px and higher.

![screen shot 2016-09-19 at 3 23 21 pm](https://cloud.githubusercontent.com/assets/3650448/18645880/0da2312c-7e7d-11e6-818d-95382f25b954.png)

Safari Version 9.1.1 (11601.6.17)

react-big-calendar@0.10.2

**Comment by jquense** [comment]
just did a few tests, can't reproduce on safari or other browsers, so you may have something in your own styles causing the issue
