### ISSUE TITLE
No Calendar for Month View

### ISSUE THREAD

**Issue by caguilar1921** [intljusticemission/react-big-calendar#175]
Upon rendering the calendar, I cannot see the monthly view. I only see the header:
Month, Year and button on left and right side and the Days. Below that is already empty, no cells displaying the days of the months. Please bear with me because I'm really a newbie... Here's my code:

import React, { PropTypes } from 'react';
import BigCalendarCSS from 'react-big-calendar/lib/css/react-big-calendar.css';
import BigCalendar from 'react-big-calendar';
import moment from 'moment';
import events from './events';

class MyCalendar extends React.Component {
	constructor (props, context)
	{
		super(props, context);
		this.context = context;
		this.state = {events: events};
		BigCalendar.setLocalizer(BigCalendar.momentLocalizer(moment));
	}

	render(){
		return (
				<BigCalendar
			        culture='en'
			        events={this.state.events}
					defaultDate={new Date()}/>
		);
	}
}

export default MyCalendar;

**Comment by caguilar1921** [comment]
found the solution, for some reason some lines in the css is not rendering it properly for me. I just changed   -ms-flex and flex to 100px. Previous code is 100 for both.

.rbc-month-row {
  display: -ms-flexbox;
  display: flex;
  position: relative;
  -ms-flex-direction: column;
      flex-direction: column;
  -ms-flex: 100px;
      flex: 100px;
  overflow: hidden;
  height: 100%;
}

**Comment by jquense** [comment]
you need to provide an explicit height to the calendar per the documentation
