### ISSUE TITLE
Events not displaying correctly

### ISSUE THREAD

**Issue by caguilar1921** [intljusticemission/react-big-calendar#176]
I noticed that my events are displaying on the wrong month. It's usually month + 1. For example, I specified a meeting for Sept 1, instead it's displayed on Oct 1.

xport default [
  {
    'title': 'All Day Event',
    'allDay': true,
    'start': new Date(2016, 9, 1),
    'end': new Date(2016, 9, 1)
  },
  {
    'title': 'Long Event',
    'start': new Date(2016, 9, 7),
    'end': new Date(2016, 9, 10)
  },
.................

class MyCalendar extends React.Component {
	constructor (props, context)
	{
		super(props, context);
		this.context = context;
		this.state = {events: events};
		BigCalendar.setLocalizer(BigCalendar.momentLocalizer(moment));
	}

	render(){

		return (
				<BigCalendar
			        culture='en'
			        events={this.state.events}
			        views={['month', 'week', 'day']}
			        defaultView='month'
			        style={{height: 800}}
					defaultDate={new Date()}/>
		);
	}
}

**Comment by jquense** [comment]
months are 0 indexed in javascript so 0 is January. that looks like it might be your issue here

**Comment by caguilar1921** [comment]
That's it exactly.. I'm expecting 9 to be September and my event displayed on October. Thanks a lot!

**Comment by minolie-surge** [comment]
Hey @caguilar1921 were you able to resolve this issue? I'm facing the same one right now.

**Comment by cutterbl** [comment]
@minolie-surge Big Calendar uses the JavaScript Date object under the hood (even, ultimately, when using any `localizer`). The JavaScript Date object uses 0 index months, so '0' is January and '9' is October.
