### ISSUE TITLE
How do I use this library in my project?

### ISSUE THREAD

**Issue by pcompassion** [intljusticemission/react-big-calendar#177]
I've asked in Stackoverflow but didn't get much attention. 

http://stackoverflow.com/questions/39636918/editable-npm-package-in-my-project

I'd like to modify & use this wonderful library.  
Being relatively new to npm, I'm not sure how I can do that.  

npm-link is what I'm after? 
I guess since many people would like to fork and modify it, hope there's some guideline on how to.

**Comment by jquense** [comment]
there isn't really any guidelines on it, you can fork it on github but if you want to install it via npm you'll need to publish (with the appropriate license) under a different name, or install directly from github.
