### ISSUE TITLE
require('./demos/basic') vs import Basic from './demos/basic'

### ISSUE THREAD

**Issue by pcompassion** [intljusticemission/react-big-calendar#178]
I'm testing the App.js in the examples

vendor-08b7333….js:21655 Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `Example`.

the offending line is
basic: `require('./demos/basic')`

if I change it to 

```
import Basic from './demos/basic'
basic: Basic

```
works fine. not a big deal, but curious why that is

**Comment by jquense** [comment]
thanks for the heads up

**Comment by TeaBough** [comment]
Same thing for me
