### ISSUE TITLE
[BUG] Date selection issue with min/max props on calendar

### ISSUE THREAD

**Issue by rafsoaken** [intljusticemission/react-big-calendar#18]
While min/max props on the calendar set the displayed time ranges correctly, the selected dates seem to  be confined to the dates given in min/max as well (at least in Week/Day view).

This makes no sense as the dates in the calendar are not confined. Probably related to https://github.com/intljusticemission/react-big-calendar/issues/17
 
From the docs it seems that the date part in min/max should have no effect.

**Comment by rafsoaken** [comment]
There is also a performance problem when the dates in min/max props are separated by more than a couple months. The calendar becomes unusable due to lag, sometimes the script execution stops in Chrome Version 47.0.2526.80 (64-bit).

Of course, if dates in min/max props are ignored, this becomes a non-issue.

**Comment by jquense** [comment]
yeah this is related to #17 as well, the min/max times are used, but the date parts are also blowing away the correct date.
