### ISSUE TITLE
Existing Feature for Day View?

### ISSUE THREAD

**Issue by caguilar1921** [intljusticemission/react-big-calendar#180]
Hello again, 

Sorry for my questions.. Is there an existing feature which allows the day (and week) view so that if there are multiple events on a certain time, it will be displayed vertically? It will look like the events happening at the same time will have their own column. In the attached screenshots, there are only 2 events happening at the same time. User's example is if there are 5 events happening at the same time, there would be 5 columns for easy viewing.

Thanks in advance!

![dailyview](https://cloud.githubusercontent.com/assets/9547178/18824248/f289a606-83f2-11e6-963b-ad8f9085b8b5.png)

**Comment by caguilar1921** [comment]
Saw this other topic, unless there's another way to divide the events equally per row... I guess this solution is the closest I can get:

https://github.com/intljusticemission/react-big-calendar/issues/131...

**Comment by jquense** [comment]
judging from the screens hits it looks like you want something like Resource views, which isn't supported right now.

**Comment by caguilar1921** [comment]
I'm not sure about Resource view. But it's more of diving the row into equal columns. Example for booking an appointment. If there are 4 services booked for 8AM, then there would be 4 columns. Anyway, I'll just try the z-index. Thanks.
