### ISSUE TITLE
Week View

### ISSUE THREAD

**Issue by caguilar1921** [intljusticemission/react-big-calendar#181]
Is there any way to view the events properly when you hover? An example below is that there are multiple events/booking at the same time. When you hover, you the bottom of the cell is already cut. Thanks.

![untitled](https://cloud.githubusercontent.com/assets/9547178/18902222/1793c264-8584-11e6-9ee7-7ebff3eb6562.png)

**Comment by jquense** [comment]
there is nothing besides the normal title attribute for hover, but you can use the event select events to show more details such as in a modal popup

**Comment by jamelene** [comment]
is there a way to customize the color of the event blocks? if for example, 3 events belonging to the same name on the same day appear, it will all appear as green, others will be blue, others will be yellow. etc.

**Comment by jquense** [comment]
use the eventPropGetter prop to customer styles and classes on events
