### ISSUE TITLE
Change the background color of off range date

### ISSUE THREAD

**Issue by dncdrn** [intljusticemission/react-big-calendar#182]
Hi! How will I change the background color of off range date in calendar?
For example this one, I want to change the background color of July 31, Sept 1 - 4.
Thanks in advance!
![offrange](https://cloud.githubusercontent.com/assets/21171473/18981592/5a6c6f5c-8712-11e6-9369-df5f97153ad9.PNG)

**Comment by jquense** [comment]
There isn't any hook for changing or styling individual background cells, but I'd accept a PR adding something similar to eventPropGetter
