### ISSUE TITLE
Custom toolbar

### ISSUE THREAD

**Issue by dncdrn** [intljusticemission/react-big-calendar#183]
Hi again! Im just new to react so Im kinda confuse how to work it around, anyway I read the documentation of react-big-calendar and it says that you can make custom components. In my case I need to customize the toolbar and make it like this
![toolbar](https://cloud.githubusercontent.com/assets/21171473/18982438/b4d0f5ac-8718-11e6-894e-beb0e0851e53.PNG)

and my custom calendar toolbar code look like this:

```
import React from 'react';
import {BackIcon, NextIcon} from '../Icons/Icons';
import {ButtonGroup, Button} from 'react-bootstrap';

const CalendarToolbar = () => {
    return (
        <div className="toolbar-container">

            <div className="back-next-buttons">
                <button className="btn btn-back">
                    <BackIcon/>
                    <NextIcon/>
                </button>
                <label className='label-date'>Aug-Sept 2016</label>
            </div>

            <div className="filter-container">
                <ButtonGroup>
                    <Button className="bg-filter-off"><span className="label-filter-off">Day</span></Button>
                    <Button className="bg-filter-off"><span className="label-filter-off">Week</span></Button>
                    <Button className="bg-filter-off"><span className="label-filter-off">Month</span></Button>
                    <Button className="bg-filter-off"><span className="label-filter-off">Year</span></Button>
                </ButtonGroup>
                

            </div>
        </div >
    );
}

export default CalendarToolbar;

```

Thanks in advance!

**Comment by dncdrn** [comment]
Hiiii!!! I have an update it worked already!!! :)))))))

These are my changes 

```
import React, { PropTypes } from 'react';
import BigCalendar from 'react-big-calendar';
import Toolbar from 'react-big-calendar';
import events from './Events';
import moment from 'moment';
import CalendarToolbar from './CalendarToolbar';
import {BackIcon} from '../Icons/Icons';
import {ButtonGroup, Button} from 'react-bootstrap';

BigCalendar.setLocalizer(
  BigCalendar.momentLocalizer(moment)
);
function Event({ event }) {
  return (
    <span>
      <strong>
        {event.title}
      </strong>
      { event.desc && (':  ' + event.desc) }
    </span>
  )
}
function CustomToolbar() {
  return (
    <div className="toolbar-container">

      <div className="back-next-buttons">
        <button className="btn btn-back">
          <BackIcon/>
        </button>
        <label className='label-date'>Aug-Sept 2016</label>
      </div>

      <div className="filter-container">
        <ButtonGroup>
          <Button className="bg-filter-off"><span className="label-filter-off">Day</span></Button>
          <Button className="bg-filter-off"><span className="label-filter-off">Week</span></Button>
          <Button className="bg-filter-off"><span className="label-filter-off">Month</span></Button>
          <Button className="bg-filter-off"><span className="label-filter-off">Year</span></Button>
        </ButtonGroup>


      </div>
    </div >
  )
}



let Calendar = React.createClass({
  render() {
    return (
      <BigCalendar

        culture='en-GB'
        {...this.props}
        events={events}
        defaultDate={new Date() }
        components={{
          event: Event,
          toolbar: CustomToolbar
        }}
        />
    )
  }
})
export default Calendar;
```

now my problem is how will I use the function/methods of your original toolbar e.g. next, back, today buttons, label of month, day, week, agenda button?
Thanks in advance!

**Comment by jquense** [comment]
Take a look at the code for the included Toolbar, the Calendar injects props that you need to wire up to your buttons appropriately. thanks!

**Comment by dncdrn** [comment]
Thank you I already resolve this last night! :)

**Comment by alansutherland** [comment]
In case anyone else needs help creating their own toolbar and found there way here, this is my code for creating custom toolbar and event components:

`import React from "react"
import BigCalendar from 'react-big-calendar'
import '!style-loader!css-loader!react-big-calendar/lib/css/react-big-calendar.css'
import moment from 'moment'

export let navigate = {
    PREVIOUS: 'PREV',
    NEXT: 'NEXT',
    TODAY: 'TODAY',
    DATE: 'DATE',
}
let events = [
  {
    id: 14,
    title: 'Maths',
    start: new Date(new Date().setHours(new Date().getHours() - 3)),
    end: new Date(new Date().setHours(new Date().getHours() + 3)),
  },
  {
    id: 15,
    title: 'English',
    start: new Date(new Date().setHours(new Date().getHours() - 2)),
    end: new Date(new Date().setHours(new Date().getHours() + 2)),
  },
  {
    id: 16,
    title: 'Biology',
    start: new Date(new Date().setHours(new Date().getHours() - 3)),
    end: new Date(new Date().setHours(new Date().getHours() + 3)),
  },
  {
    id: 17,
    title: 'Robotics',
    start: new Date(new Date().setHours(new Date().getHours() - 4)),
    end: new Date(new Date().setHours(new Date().getHours() + 2)),
  },
  {
    id: 19,
    title: 'Japanese',
    start: new Date(new Date().setHours(new Date().getHours() - 2)),
    end: new Date(new Date().setHours(new Date().getHours() + 2)),
  },
]

const localizer = BigCalendar.momentLocalizer(moment) 

function Event({ event }) {
    return (
        <span>
            <strong>{event.title}</strong>
            {event.desc && ':  ' + event.desc}
        </span>
    )
}

function Book({ event }) {
    return (
        <div className="rbc-day-bg">
            <button>Book Class</button>
        </div>
    )
}

class CustomToolbar extends React.Component {
    render() {
        let { localizer: { messages }, label } = this.props
        return(
            <div className="rbc-toolbar">
                <span className="rbc-btn-group">
                    <button type="button" onClick={this.navigate.bind(null, navigate.PREVIOUS)}>Prev</button>
                </span>
                <span className="rbc-toolbar-label">{label}</span>
                <span className="rbc-btn-group">
                    <button type="button" onClick={this.navigate.bind(null, navigate.NEXT)}>Next</button>
                </span>
            </div>
        )
    }
    navigate = action => {
        this.props.onNavigate(action)
    }
}

const Calendar = props => (
  <div>
    <BigCalendar
      localizer={localizer}
      events={events}
      popup
      startAccessor="start"
      endAccessor="end"
      className={ props.calendarIsOpen ? 'open' : '' } 
      components={{
        event: Event,
        toolbar: CustomToolbar,
        dateCellWrapper: Book
      }}
    />
  </div>
)

export default Calendar;`

**Comment by adityay-perpetualny** [comment]
![image](https://user-images.githubusercontent.com/44191071/72619770-087acd80-3964-11ea-94a8-435d0feb1fdc.png)

**Comment by ZeeshanAhmadKhalil** [comment]
That would be great if they mention the above solution somewhere in the [doc](https://jquense.github.io/react-big-calendar/examples/?path=/docs/props--on-navigate). Because it takes time to find the solution every time using `react-big-calendar`.

**Comment by cutterbl** [comment]
@ZeeshanAhmadKhalil I will add a link to the [components prop](https://jquense.github.io/react-big-calendar/examples/?path=/docs/props--components) documentation that will point to the custom toolbar example code in the repository.
