### ISSUE TITLE
Styling the current day/time indicator

### ISSUE THREAD

**Issue by ejowers** [intljusticemission/react-big-calendar#185]
I need to be able to shade in the current day on month view and the current time on the day and week view. Being able to restyle this as we want would be helpful. Also, on your demos, the current time on day and week view is bolded. It does not show up that way for me.

**Comment by jquense** [comment]
you can use css to style stuff, the current day/time cells have a `rbc-now` class

**Comment by esseswann** [comment]
I'm kind of stuck with this also. The thing is that the cell `rbc-day-bg` doesn't receive rbc-now class, only `rbc-date-cell` does. I actually don't know why cell and date label are separated into different DOM branches, I would suggest putting date label into the cell's div and having 'rbc-now' on the cell.

**Comment by CatherinePoon** [comment]
You can make the `rbc-now` cell to have a background color and make it position absolute.
