### ISSUE TITLE
disable specific days && time slots available  

### ISSUE THREAD

**Issue by nwabdou85** [intljusticemission/react-big-calendar#186]
Hi every one,

How you can disable specific days with react big calendar ? like disable all sundays and saturdays; or any other day.

Antoher question: How to show customers only the time slots available of a professional ( used react big react) ??

Thank's for your help

**Comment by nwabdou85** [comment]
Or, how can I use a min and max to hide some days and time from calendar?

**Comment by uvaldez** [comment]
Hello @nwabdou85 were you able to resolve this?

**Comment by alveflo** [comment]
@nwabdou85 @uvaldez I'm also interested in this one, did any of you guys find any solution?

**Comment by jquense** [comment]
not really sure what the question is here...what does "disabling" mean in this context

**Comment by alveflo** [comment]
@jquense specify business hours is at lease what I mean 😄 

https://fullcalendar.io/docs/display/businessHours/

**Comment by jquense** [comment]
you can set `min`/`max` to limit times on the week/day views

**Comment by alveflo** [comment]
@jquense all right, great. Thanks 👍

**Comment by jquense** [comment]
you can also more minutely control waht is selectable by returning `false` form the onSelecting callback (I think thats the name)

**Comment by nwabdou85** [comment]
Hy guys, sorry to be late, yeah I fixe it but by using directly fullcalendar not react-big-calendar

**Comment by DonovanCharpin** [comment]
New pull request for business hours https://github.com/intljusticemission/react-big-calendar/pull/309, you can test it, I added some doc in the API page.

**Comment by Shibu-N** [comment]
Looking for the solution on disabling past dates in the big calendar, any suggestion guys....?

**Comment by vilmes21** [comment]
Looking for solution on disabling ranges - ideally data should be passed in as if they are event data. Anyone?

**Comment by ammoradi** [comment]
> past dates in the big

**Comment by TomasHubelbauer** [comment]
I've managed to do this using the `timeSlotWrapper` component:

`<ReactBigCalendar components={{ timeSlotWrapper: TimeSlotWrapper }} />`

`TimeSlotWrapper`:
```typescript
function (props: { children: React.ReactNode, resource: null /* grid */ | undefined /* gutter */, value: Date }) {
  if (!isBanned(value)) {
    return props.children;
  }

  const child = React.Children.only(props.children);
  return React.cloneElement(child, { className: child.props.className + ' rbc-off-range-bg' });
}
```
