### ISSUE TITLE
Change language from buttons

### ISSUE THREAD

**Issue by costaoeste** [intljusticemission/react-big-calendar#190]
Is it possible to change the language from the buttons next. back and today?
Thanks

**Comment by jquense** [comment]
yup,  the messages prop

**Comment by costaoeste** [comment]
Thanks!               
` messages={{next:"Siguiente",previous:"Atrás",today:"Ahora"}}
`

**Comment by emersonsiega** [comment]
Sorry for comment on a closed issue, but I lost some time to found the solution commented above. 

Maybe the documentation can have some simple examples of internationalization. This config it's very simple, but for someone like me, that are using ReactBigCalendar for the first time (and liking a lot), will be very good to have simple examples of internationalization of all the Calendar.

**Comment by AndDiSan** [comment]
I was looking for the same thing, and found this answer. Sorry for commenting a closed issue but here you can find the defaultMessages var: you can override it passing your localization in `messages={{...}}`
```
var defaultMessages = {
    date: 'Date',
    time: 'Time',
    event: 'Event',
    allDay: 'All Day',
    week: 'Week',
    work_week: 'Work Week',
    day: 'Day',
    month: 'Month',
    previous: 'Back',
    next: 'Next',
    yesterday: 'Yesterday',
    tomorrow: 'Tomorrow',
    today: 'Today',
    agenda: 'Agenda',
    noEventsInRange: 'There are no events in this range.',
    showMore: function showMore(total) {
      return "+" + total + " more";
    }
  };
```
