### ISSUE TITLE
Demo for custom toolbar

### ISSUE THREAD

**Issue by welcoMattic** [intljusticemission/react-big-calendar#191]
May you publish a demo tab with custom toolbar?

**Comment by dncdrn** [comment]
Hi i've done this in my code you might want to check it 

` getCustomToolbar = (toolbar) => {
    this.toolbarDate = toolbar.date;
    const goToDayView = () => {
      toolbar.onViewChange('day');
    }
    const goToWeekView = () => {
      toolbar.onViewChange('week');
    }
    const goToMonthView = () => {
      toolbar.onViewChange('month');

      setTimeout(() => {
        this.setOffRangeDateStyle();
      }, 100)

    }
    const goToBack = () => {
      let mDate = toolbar.date;
      let newDate = new Date(
        mDate.getFullYear(),
        mDate.getMonth() - 1,
        1);
      toolbar.onNavigate('prev', newDate);
      this.getCalendarEvents(newDate);

    }
    const goToNext = () => {
      let mDate = toolbar.date;
      let newDate = new Date(
        mDate.getFullYear(),
        mDate.getMonth() + 1,
        1);
      toolbar.onNavigate('next', newDate);
      this.getCalendarEvents(newDate);

    }
    return (
      <div className="toolbar-container">
        <div className="navigation-buttons">
          <button className="btn btn-back" onClick={goToBack}>
            <BackIcon className='prev-icon' />
          </button>
          <button className="btn btn-next" onClick={goToNext}>
            <NextIcon className='next-icon' />
          </button>
          <label className='label-date'>{this.state.monthLabel}</label>
        </div>
        <div className="filter-container">
          <button className="bg-filter-off" onClick={goToDayView}><span className="label-filter-off">Day</span></button>
          <button className="bg-filter-off" onClick={goToWeekView}><span className="label-filter-off">Week</span></button>
          <button className="bg-filter-off" onClick={goToMonthView}><span className="label-filter-off">Month</span></button>
        </div>
      </div >
    )
  }

<BigCalendar
        popup
        dayFormat={'ddd d/MM'}
        ref={c => { this.bigCalendar = c } }
        culture="en-GB"
        events={calendarEvents}
        defaultDate={new Date()}
        components={{
          event: this.getCustomEvent,
          toolbar: this.getCustomToolbar
        }}
        />
        </div>`

**Comment by costaoeste** [comment]
thanks Danica, I will try your code

**Comment by dncdrn** [comment]
`  getCalendarEvents = (date) => {
    const {project} = this;
    const startDate = moment(date).add(-1, 'month').toDate();
    const endDate = moment(date).endOf('month').toDate();
    const currentMonth = moment(date).endOf('month').format('MMMM YYYY');
    const monthToday = moment(date).endOf('month').format('MMM');
    let nextCurrentMonth = moment(date).add(1, 'month').format('MMM');

    this.setState({
      monthLabel: currentMonth,
      currentMonth: monthToday,
      nextMonth: nextCurrentMonth
    });

    if (project) {
      ProjectActions.getEvents(project.id, startDate, endDate, (err, res) => {
        if (err) {
          throw err;
        }
        this.setState({
          events: res.body
        });

      });
    }
  }`

**Comment by Artexoid** [comment]
it's correct work and current date not lost.

```
const CustomToolbar = (toolbar) => {
  const goToBack = () => {
    toolbar.date.setMonth(toolbar.date.getMonth() - 1);
    toolbar.onNavigate('prev');
  };

  const goToNext = () => {
    toolbar.date.setMonth(toolbar.date.getMonth() + 1);
    toolbar.onNavigate('next');
  };

  const goToCurrent = () => {
    const now = new Date();
    toolbar.date.setMonth(now.getMonth());
    toolbar.date.setYear(now.getFullYear());
    toolbar.onNavigate('current');
  };

  const label = () => {
    const date = moment(toolbar.date);
    return (
      <span><b>{date.format('MMMM')}</b><span> {date.format('YYYY')}</span></span>
    );
  };

  return (
    <div className={sCalendar['toolbar-container']}>
      <label className={sCalendar['label-date']}>{label()}</label>

      <div className={sCalendar['back-next-buttons']}>
        <button className={sCalendar['btn-back']} onClick={goToBack}>&#8249;</button>
        <button className={sCalendar['btn-current']} onClick={goToCurrent}>today</button>
        <button className={sCalendar['btn-next']} onClick={goToNext}>&#8250;</button>
      </div>
    </div >
  );
};

moment.locale('en');
BigCalendar.momentLocalizer(moment);

const Calendar = (props) => {
  return (
    <div className={sCalendar['layout']}>
      <BigCalendar
        events={props.events}
        timeslots={4}
        components={{
          toolbar: CustomToolbar
        }}
        onSelectEvent={props.onSelectEvent}
      />
    </div>
  );
};
```

**Comment by WaldoJeffers** [comment]
Thanks @dncdrn and @Artexoid for the great examples. I think this should be integrated in the docs, because the only example where the developer provides custom components are render-only components. It does not show how to interact with the calendar.

**Comment by tairy-potter** [comment]
Love it! Thank you @dncdrn @Artexoid for your awesome code. Btw, I just updated navigation's function to work correctly with calendar's view.
`  const goToBack = () => {
    toolbar.onNavigate('PREV');
  };
  const goToNext = () => {
    debugger;
    toolbar.onNavigate('NEXT');
  };
  const goToCurrent = () => {
    toolbar.onNavigate('TODAY');
  };`

**Comment by Chathumini** [comment]
@dncdrn on 18 Oct 2016  is worked for me when use,
toolbar.onView('day');


insted of this,  
toolbar.onViewChange('day');

**Comment by Chathumini** [comment]
Following code is work for me


import React, { Component } from "react";
import BigCalendar from "react-big-calendar";
import moment from "moment";
import "react-big-calendar/lib/css/react-big-calendar.css";

class App extends Component {
  state = {
    events: [
      {
        title: "My event 1",
        allDay: false,
        start: new Date(2019, 2, 6, 10, 0), // 10.00 AM
        end: new Date(2019, 2, 6, 13, 0), // 2.00 PM
        col: "#ee3559"
      },
      {
        title: "My event 2",
        allDay: false,
        start: new Date(2019, 2, 6, 13, 0), // 10.00 AM
        end: new Date(2019, 2, 6, 15, 0), // 2.00 PM6
        col: "#ee3559"
      }
    ],
    viewState: "month"
  };

  getCustomToolbar = toolbar => {
    this.toolbarDate = toolbar.date;
    const goToDayView = () => {
      toolbar.onView("day");
      this.setState({ viewState: "day" });
    };
    const goToWeekView = () => {
      toolbar.onView("week");
      this.setState({ viewState: "week" });
    };
    const goToMonthView = () => {
      toolbar.onView("month");
      this.setState({ viewState: "month" });
    };
    const goToBack = () => {
      let view = this.state.viewState;
      let mDate = toolbar.date;
      let newDate;
      if (view === "month") {
        newDate = new Date(mDate.getFullYear(), mDate.getMonth() - 1, 1);
      } else if (view === "week") {
        newDate = new Date(
          mDate.getFullYear(),
          mDate.getMonth(),
          mDate.getDate() - 7,
          1
        );
      } else {
        newDate = new Date(
          mDate.getFullYear(),
          mDate.getMonth(),
          mDate.getDate() - 1,
          1
        );
      }
      toolbar.onNavigate("prev", newDate);
    };
    const goToNext = () => {
      let view = this.state.viewState;
      let mDate = toolbar.date;
      let newDate;
      if (view === "month") {
        newDate = new Date(mDate.getFullYear(), mDate.getMonth() + 1, 1);
      } else if (view === "week") {
        newDate = new Date(
          mDate.getFullYear(),
          mDate.getMonth(),
          mDate.getDate() + 7,
          1
        );
      } else {
        newDate = new Date(
          mDate.getFullYear(),
          mDate.getMonth(),
          mDate.getDate() + 1,
          1
        );
      }
      toolbar.onNavigate("next", newDate);
    };

    const goToToday = () => {
      const now = new Date();
      toolbar.date.setMonth(now.getMonth());
      toolbar.date.setYear(now.getFullYear());
      toolbar.onNavigate("current");
    };

    const goToBackYear = () => {
      let mDate = toolbar.date;
      let newDate = new Date(mDate.getFullYear() - 1, 1);
      toolbar.onNavigate("prev", newDate);
    };

    const goToNextYear = () => {
      let mDate = toolbar.date;
      let newDate = new Date(mDate.getFullYear() + 1, 1);
      toolbar.onNavigate("next", newDate);
    };

    const month = () => {
      const date = moment(toolbar.date);
      let month = date.format("MMMM");

      return <span className="rbc-toolbar-label">{month}</span>;
    };
    const year = () => {
      const date = moment(toolbar.date);
      let year = date.format("YYYY");

      return (
        <span className="rbc-btn-group">
          {this.state.viewState === "month" && (
            <button type="button" onClick={goToBackYear}>
              <span className="prev-icon">&#8249;&#8249;</span>
            </button>
          )}
          <span className="rbc-toolbar-label">{year}</span>
          {this.state.viewState === "month" && (
            <button type="button" onClick={goToNextYear}>
              <span className="prev-icon">&#8250;&#8250;</span>
            </button>
          )}
        </span>
      );
    };

    const day = () => {
      let view = this.state.viewState;
      const date = moment(toolbar.date);
      let day;
      if (view === "day") {
        day = date.format("ddd") + " " + date.format("Do");
      }
      return <span className="rbc-toolbar-label">{day}</span>;
    };

    return (
      <div className="rbc-toolbar">
        {month()}
        {year()}
        {day()}
        <span className="rbc-btn-group">
          <button type="button" onClick={goToBack}>
            <span className="prev-icon">&#8249;</span>
          </button>
          <button type="button" onClick={goToToday}>
            <span className="next-icon">Today</span>
          </button>
          <button type="button" onClick={goToNext}>
            <span className="next-icon">&#8250;</span>
          </button>
        </span>
        <span className="rbc-btn-group">
          <button className="" onClick={goToMonthView}>
            <span className="label-filter-off">Month</span>
          </button>
          <button className="rbc-active" onClick={goToDayView}>
            <span className="label-filter-off">Day</span>
          </button>
          <button className="" onClick={goToWeekView}>
            <span className="label-filter-off">Week</span>
          </button>
        </span>
      </div>
    );
  };

  render() {
    const localizer = BigCalendar.momentLocalizer(moment); // or globalizeLocalizer
    return (
      <div style={{ height: "100vh", width: "100vw" }}>
        <div style={{ height: "100%", width: "100%" }}>
          <BigCalendar
            localizer={localizer}
            selectable
            events={this.state.events}
            components={{
              toolbar: this.getCustomToolbar
            }}
          />
        </div>
      </div>
    );
  }
}

export default App;

**Comment by join2nidhi** [comment]
code is nt working for me can you share code again

**Comment by Chathumini** [comment]
I think BigCalender has change a little bit now it's working

import React, { Component } from "react";
import { Calendar, momentLocalizer } from "react-big-calendar";
import moment from "moment";
import "react-big-calendar/lib/css/react-big-calendar.css";

class App extends Component {
  state = {
    events: [
      {
        title: "My event 1",
        allDay: false,
        start: new Date(2020, 6, 6, 10, 0), // 10.00 AM
        end: new Date(2020, 8, 6, 13, 0), // 2.00 PM
        col: "#ee3559",
      },
      {
        title: "My event 2",
        allDay: false,
        start: new Date(2020, 7, 6, 13, 0), // 10.00 AM
        end: new Date(2020, 10, 6, 15, 0), // 2.00 PM6
        col: "#ee3559",
      },
    ],
    viewState: "month",
  };

  getCustomToolbar = (toolbar) => {
    this.toolbarDate = toolbar.date;
    const goToDayView = () => {
      toolbar.onView("day");
      this.setState({ viewState: "day" });
    };
    const goToWeekView = () => {
      toolbar.onView("week");
      this.setState({ viewState: "week" });
    };
    const goToMonthView = () => {
      toolbar.onView("month");
      this.setState({ viewState: "month" });
    };
    const goToBack = () => {
      let view = this.state.viewState;
      let mDate = toolbar.date;
      let newDate;
      if (view === "month") {
        newDate = new Date(mDate.getFullYear(), mDate.getMonth() - 1, 1);
      } else if (view === "week") {
        newDate = new Date(
          mDate.getFullYear(),
          mDate.getMonth(),
          mDate.getDate() - 7,
          1
        );
      } else {
        newDate = new Date(
          mDate.getFullYear(),
          mDate.getMonth(),
          mDate.getDate() - 1,
          1
        );
      }
      toolbar.onNavigate("prev", newDate);
    };
    const goToNext = () => {
      let view = this.state.viewState;
      let mDate = toolbar.date;
      let newDate;
      if (view === "month") {
        newDate = new Date(mDate.getFullYear(), mDate.getMonth() + 1, 1);
      } else if (view === "week") {
        newDate = new Date(
          mDate.getFullYear(),
          mDate.getMonth(),
          mDate.getDate() + 7,
          1
        );
      } else {
        newDate = new Date(
          mDate.getFullYear(),
          mDate.getMonth(),
          mDate.getDate() + 1,
          1
        );
      }
      toolbar.onNavigate("next", newDate);
    };

    const goToToday = () => {
      const now = new Date();
      toolbar.date.setMonth(now.getMonth());
      toolbar.date.setYear(now.getFullYear());
      toolbar.onNavigate("current");
    };

    const goToBackYear = () => {
      let mDate = toolbar.date;
      let newDate = new Date(mDate.getFullYear() - 1, 1);
      toolbar.onNavigate("prev", newDate);
    };

    const goToNextYear = () => {
      let mDate = toolbar.date;
      let newDate = new Date(mDate.getFullYear() + 1, 1);
      toolbar.onNavigate("next", newDate);
    };

    const month = () => {
      const date = moment(toolbar.date);
      let month = date.format("MMMM");

      return <span className="rbc-toolbar-label">{month}</span>;
    };
    const year = () => {
      const date = moment(toolbar.date);
      let year = date.format("YYYY");

      return (
        <span className="rbc-btn-group">
          {this.state.viewState === "month" && (
            <button type="button" onClick={goToBackYear}>
              <span className="prev-icon">&#8249;&#8249;</span>
            </button>
          )}
          <span className="rbc-toolbar-label">{year}</span>
          {this.state.viewState === "month" && (
            <button type="button" onClick={goToNextYear}>
              <span className="prev-icon">&#8250;&#8250;</span>
            </button>
          )}
        </span>
      );
    };

    const day = () => {
      let view = this.state.viewState;
      const date = moment(toolbar.date);
      let day;
      if (view === "day") {
        day = date.format("ddd") + " " + date.format("Do");
      }
      return <span className="rbc-toolbar-label">{day}</span>;
    };

    return (
      <div className="rbc-toolbar">
        {month()}
        {year()}
        {day()}
        <span className="rbc-btn-group">
          <button type="button" onClick={goToBack}>
            <span className="prev-icon">&#8249;</span>
          </button>
          <button type="button" onClick={goToToday}>
            <span className="next-icon">Today</span>
          </button>
          <button type="button" onClick={goToNext}>
            <span className="next-icon">&#8250;</span>
          </button>
        </span>
        <span className="rbc-btn-group">
          <button className="" onClick={goToMonthView}>
            <span className="label-filter-off">Month</span>
          </button>
          <button className="rbc-active" onClick={goToDayView}>
            <span className="label-filter-off">Day</span>
          </button>
          <button className="" onClick={goToWeekView}>
            <span className="label-filter-off">Week</span>
          </button>
        </span>
      </div>
    );
  };
  render() {
    const localizer = momentLocalizer(moment); // or globalizeLocalizer
    return (
      <div style={{ height: "100vh", width: "100vw" }}>
        <div style={{ height: "100%", width: "100%" }}>
          <Calendar
            localizer={localizer}
            selectable
            events={this.state.events}
            components={{
              toolbar: this.getCustomToolbar,
            }}
          />
        </div>
      </div>
    );
  }
}

export default App;

**Comment by Professor833** [comment]
Just in Case any one Looking for Functional Component of what @Chathumini Shared. Here it is;
`CustomToolbar.js`
```javascript
import moment from "moment";
import React, { useState } from "react";
import SwitchCheckbox from "../../GlobalComponents/SwitchCheckbox";

function RBCToolbar(props) {
  const [viewState, setViewState] = useState("month");
  const [StudyTimechecked, setStudyTimechecked] = useState(false)
  const getCustomToolbar = () => {
    // const toolbarDate = props.date;
    const goToDayView = () => {
      props.onView("day");
      setViewState("day");
    };
    const goToWeekView = () => {
      props.onView("week");
      setViewState("week");
    };
    const goToMonthView = () => {
      props.onView("month");
      setViewState("month");
    };
    const goToAgendaView = () => {
      props.onView("agenda");
      setViewState("agenda");
    };
    const goToBack = () => {
      let view = viewState;
      let mDate = props.date;
      let newDate;
      if (view === "month") {
        newDate = new Date(mDate.getFullYear(), mDate.getMonth() - 1, 1);
      } else if (view === "week") {
        newDate = new Date(
          mDate.getFullYear(),
          mDate.getMonth(),
          mDate.getDate() - 7,
          1
        );
      } else {
        newDate = new Date(
          mDate.getFullYear(),
          mDate.getMonth(),
          mDate.getDate() - 1,
          1
        );
      }
      props.onNavigate("prev", newDate);
    };
    const goToNext = () => {
      let view = viewState;
      let mDate = props.date;
      let newDate;
      if (view === "month") {
        newDate = new Date(mDate.getFullYear(), mDate.getMonth() + 1, 1);
      } else if (view === "week") {
        newDate = new Date(
          mDate.getFullYear(),
          mDate.getMonth(),
          mDate.getDate() + 7,
          1
        );
      } else {
        newDate = new Date(
          mDate.getFullYear(),
          mDate.getMonth(),
          mDate.getDate() + 1,
          1
        );
      }
      props.onNavigate("next", newDate);
    };

    const goToToday = () => {
      const now = new Date();
      props.date.setMonth(now.getMonth());
      props.date.setYear(now.getFullYear());
      props.date.setDate(now.getDate());
      props.onNavigate("current");
    };

    const goToBackYear = () => {
      let mDate = props.date;
      let newDate = new Date(mDate.getFullYear() - 1, 1);
      props.onNavigate("prev", newDate);
    };

    const goToNextYear = () => {
      let mDate = props.date;
      let newDate = new Date(mDate.getFullYear() + 1, 1);
      props.onNavigate("next", newDate);
    };

    const month = () => {
      const date = moment(props.date);
      let month = date.format("MMMM");
      let day = date.format("D");

      return (
        <span className="rbc-toolbar-label rbc-date">
          <i className="far fa-calendar"></i> <span>{`${month} ${day}`}</span>
        </span>
      );
    };
    const year = () => {
      const date = moment(props.date);
      let year = date.format("YYYY");

      return (
        <span className="rbc-btn-group">
          {viewState === "month" && (
            <button type="button" onClick={goToBackYear}>
              <span className="prev-icon">&#8249;&#8249;</span>
            </button>
          )}
          <span className="rbc-toolbar-label">{year}</span>
          {viewState === "month" && (
            <button type="button" onClick={goToNextYear}>
              <span className="prev-icon">&#8250;&#8250;</span>
            </button>
          )}
        </span>
      );
    };

    const day = () => {
      let view = viewState;
      const date = moment(props.date);
      let day;
      if (view === "day") {
        day = date.format("ddd") + " " + date.format("Do");
      }
      return <span className="rbc-toolbar-label">{day}</span>;
    };

    return (
      <div className="rbc-toolbar">
        <div className="rbc-toolbar-item-1">
          <div className="flex-row">
            <SwitchCheckbox checked={StudyTimechecked} onChange={setStudyTimechecked} id="study-time-checkbox" />
            <p className="text-muted" style={{ margin: "0" }}>              
              Study Time
            </p>
          </div>
        </div>
        <div className="rbc-toolbar-item-2">
          <span className="rbc-btn-group">
            <span className="next-icon today" onClick={goToToday}>
              Today
            </span>

            <span className="prev-icon" id="prev-btn-icon" onClick={goToBack}>
              &#8249;
            </span>

            <span className="next-icon" id="next-btn-icon" onClick={goToNext}>
              &#8250;
            </span>
          </span>
          {month()}        
          <span className="rbc-btn-group">
            <button className="" onClick={goToMonthView}>
              <span className="label-filter-off">Month</span>
            </button>
            <button className="" onClick={goToDayView}>
              <span className="label-filter-off">Day</span>
            </button>
            <button className="" onClick={goToWeekView}>
              <span className="label-filter-off">Week</span>
            </button>
            <button className="" onClick={goToAgendaView}>
              <span className="label-filter-off">Agenda</span>
            </button>
          </span>
        </div>
      </div>
    );
  };

  return <>{getCustomToolbar()}</>;
}

export default RBCToolbar;
```
`RBCalendar.js`
```javascript
import React, { Component, useState } from "react";
import moment from "moment";
import moment_timezone from "moment-timezone";
import { Calendar, momentLocalizer } from "react-big-calendar";
import withDragAndDrop from "react-big-calendar/lib/addons/dragAndDrop";
import RBCToolbar from "./TopToolbar/RBCToolbar";
import events from "../../utils/events";
import "react-big-calendar/lib/css/react-big-calendar.css";
import "react-big-calendar/lib/addons/dragAndDrop/styles.css";

const localizer = momentLocalizer(moment_timezone);
const DnDCalendar = withDragAndDrop(Calendar);


function RBCalender() {
  const [viewState, setViewState] = useState("month");
  const [customEventList, setEvents] = useState(events);

  const onEventResize = (data) => {
    // changing events on Resize
    const { start, end } = data;

    // Filter the event from customEventList and change the start and end time
    customEventList.map((event) => {
      if (event.id === data.event.id) {
        event.start = start;
        event.end = end;
        setEvents(customEventList);
      }
    });
  };

  const onEventDrop = (data) => {
    console.log(data);
    // console.log("eventdaa >> ", events);
  };


  return (
    <DnDCalendar
      defaultDate={moment().toDate()}
      defaultView="week"
      events={customEventList}
      localizer={localizer}
      onEventDrop={onEventDrop}
      onEventResize={onEventResize}
      resizable
      selectable
      // step={90} // default step is 30
      // timeslots={2}
      components={{
        toolbar: RBCToolbar
      }}
      style={{ height: "100vh", width: "100%", backgroundColor: "white" }}
    />
  );
}

export default RBCalender;
```

**Comment by lehaiquantb** [comment]
my solution for now
https://github.com/jquense/react-big-calendar/issues/818#issuecomment-908453799

**Comment by SaimumIslam** [comment]
```
import React, { useState, useEffect } from "react";
import clsx from "clsx";
import moment from "moment";

function RBCToolbar(props) {
  const { label, date, view, views, onView, onNavigate } = props;
  const [month, setMonth] = useState("January");
  const mMonth = moment(date).format("MMMM");
  const months = moment.months();

  useEffect(() => {
    setMonth(mMonth);
  }, [mMonth]);

  const onChange = (event) => {
    const current = event.target.value;
    onNavigate("DATE", moment().month(current).toDate());
    setMonth(current);
  };

  const goToView = (view) => {
    onView(view);
  };

  const goToBack = () => {
    onNavigate("PREV");
  };
  const goToNext = () => {
    onNavigate("NEXT");
  };

  const goToToday = () => {
    onNavigate("TODAY");
  };

  return (
    <div className="rbc-toolbar">
      <div className="rbc-btn-group">
        <button onClick={goToToday}>Today</button>
        <button onClick={goToBack}>Back</button>
        <button onClick={goToNext}>Next</button>
      </div>
      <div className="rbc-toolbar-label">
        {view === "month" ? (
          <>
            <select className="rbc-dropdown" value={month} onChange={onChange}>
              {months?.map((month) => (
                <option
                  value={month}
                  className="rbc-dropdown-option" //custom class
                  key={month}
                >
                  {month}
                </option>
              ))}
            </select>
            <span className="rbc-year"> {moment(date).format("YYYY")}</span>
          </>
        ) : (
          label
        )}
      </div>
      <div className="rbc-btn-group">
        {views?.map((item) => (
          <button
            onClick={() => goToView(item)}
            key={item}
            className={clsx({ "rbc-active": view === item })}
          >
            {item}
          </button>
        ))}
      </div>
    </div>
  );
}

export default RBCToolbar;

```

**Comment by cutterbl** [comment]
The `Toolbar` receives the following props
- `date`
- `view`
- `views`
- `label`
- `onView (view: String) => props.onView(view)`
- `onNavigate (action: String, newDate?: Date) => props.onNavigate(date: Date, view: String, action: String)`
- `localizer`
It is important to understand that the `localizer` handles all internal date math, regardless of which `localizer` you use. Controlling navigation is easy, when using some utilities provided by Big Calendar.
```js
import { Navigate as navigate } from 'react-big-calendar';
// ...
  const today = () => onNavigate(navigate.TODAY);
  const next = () => onNavigate(navigate.NEXT);
  const prev = () => onNavigate(navigate.PREVIOUS);
```
I am working on some new documentation that, if approved, will include an example of using a custom toolbar.

**Comment by jdboris** [comment]
FYI if you just want to customize the default toolbar a little bit, you can import the default component and pass in your own props. The props aren't documented but you can figure them out looking at the [source code](https://github.com/jquense/react-big-calendar/blob/master/src/Toolbar.js). For example, you could change the default text of the "Month" button to "M" like this...

```jsx
import { Calendar } from "react-big-calendar";
import Toolbar from "react-big-calendar/lib/Toolbar";

...

<Calendar
  components={{
    toolbar: ({ localizer, ...props }, children) => {
      return (
        <Toolbar
          {...props}
          localizer={{
            label: localizer.label,
            messages: {
              ...localizer.messages,
              month: "M",
            },
          }}
        >
          {children}
        </Toolbar>
      );
    },
  }}
  ...
/>
```

**Comment by cutterbl** [comment]
@jdboris Actually, if all you wanted to do was change the button text you could just pass a [messages](http://jquense.github.io/react-big-calendar/examples/index.html#prop-messages) prop to the Calendar, to override any of the existing values. It isn't currently well documented, but you can pass in an object to override any of the default `messages`. Here's a list:

```js
let defaultMessages = {
  date: 'Date',
  time: 'Time',
  event: 'Event',
  allDay: 'All Day',
  week: 'Week',
  work_week: 'Work Week',
  day: 'Day',
  month: 'Month',
  previous: 'Back',
  next: 'Next',
  yesterday: 'Yesterday',
  tomorrow: 'Tomorrow',
  today: 'Today',
  agenda: 'Agenda',

  noEventsInRange: 'There are no events in this range.',

  showMore: total => `+${total} more`,
}
```

**Comment by jdboris** [comment]
@cutterbl 

Oh, thanks! That's much easier

**Comment by jomefavourite** [comment]
I really wished everyone used a sandbox 😑

**Comment by cutterbl** [comment]
There is the [source for the 'components' prop story](https://github.com/jquense/react-big-calendar/blob/master/stories/props/components.stories.js) from the [documentation](http://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/props--components), and the [toolbar it uses](https://github.com/jquense/react-big-calendar/blob/master/stories/props/customComponents/CustomToolbar.component.js).

**Comment by jomefavourite** [comment]
> @jomefavourite There is the [source for the 'components' prop story](https://github.com/jquense/react-big-calendar/blob/master/stories/props/components.stories.js) from the [documentation](http://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/props--components), and the [toolbar it uses](https://github.com/jquense/react-big-calendar/blob/master/stories/props/customComponents/CustomToolbar.component.js).

Okay thanks, I found what I needed and it works

**Comment by jomefavourite** [comment]
@cutterbl Please I need your help if it's not much trouble.

I'm trying to change the view, from a month view to a custom agenda view when a button is clicked.

https://codesandbox.io/s/jolly-http-v7pyov?file=/src/Event.jsx:1138-1144

**Comment by jereloh** [comment]
> @jomefavourite There is the [source for the 'components' prop story](https://github.com/jquense/react-big-calendar/blob/master/stories/props/components.stories.js) from the [documentation](http://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/props--components), and the [toolbar it uses](https://github.com/jquense/react-big-calendar/blob/master/stories/props/customComponents/CustomToolbar.component.js).

Thanks for this summary, i had success customising my own toolbar with mui5. 
Just sharing in case anyone else is looking to customize.. i installed clsx and import navigate. ` import { Navigate as navigate } from 'react-big-calendar'`' which is `import { Navigate as navigate } from '../../../src'` from [original example](https://github.com/jquense/react-big-calendar/blob/master/stories/props/customComponents/CustomToolbar.component.js)

```
import { Navigate as navigate } from 'react-big-calendar'
import ChevronLeftIcon from '@mui/icons-material/ChevronLeft'
import CalendarViewDayIcon from '@mui/icons-material/CalendarViewDay'
import ChevronRightIcon from '@mui/icons-material/ChevronRight'

const ViewNamesGroup = ({ views: viewNames, view, messages, onView }) => {
    return viewNames.map((name) => (
      <Button
        type="button"
        key={name}
        className={clsx({ 'rbc-active': view === name })}
        onClick={() => onView(name)}
      >
        <Typography>{messages[name]}</Typography>
      </Button>
    ))
  }
  const CustomToolbar = ({
    label,
    localizer: { messages },
    onNavigate,
    onView,
    view,
    views,
  }) => {
    return (
      <Box className="rbc-toolbar">
        <span className="rbc-btn-group">
          <ViewNamesGroup
            view={view}
            views={views}
            messages={messages}
            onView={onView}
          />
        </span>

        <span className="rbc-toolbar-label">{label}</span>

        <span className="rbc-btn-group">
          <Button
            type="button"
            onClick={() => onNavigate(navigate.PREVIOUS)}
            aria-label={messages.previous}
          >
            <ChevronLeftIcon />
          </Button>
          <Button
            type="button"
            onClick={() => onNavigate(navigate.TODAY)}
            aria-label={messages.today}
          >
            <CalendarViewDayIcon />
          </Button>
          <Button
            type="button"
            onClick={() => onNavigate(navigate.NEXT)}
            aria-label={messages.next}
          >
            <ChevronRightIcon />
          </Button>
        </span>
      </Box>
    )
  }
```
Then in Calendar component just 
```
<DnDCalendar
...
        components={{
          toolbar: CustomToolbar,
        
        }}
...
      />
```

**Comment by jereloh** [comment]
> 

Hi from [custom example toolbar](https://github.com/jquense/react-big-calendar/blob/master/stories/props/customComponents/CustomToolbar.component.js) there is a `onView` function props 

see.. 
```
export default function CustomToolbar({
  // date, // available, but not used here
  label,
  localizer: { messages },
  onNavigate,
  onView,
  view,
  views,
})
...
```

To change view based on your codesandbox, you dont have to create your own function, simply use onView function           
In line 54 of RBCToolbar.js from your [codesandbox](https://codesandbox.io/s/jolly-http-v7pyov?file=/src/RBCToolbar.js:1526-1588) change changeView to props.onView
`<Button key={i} onClick={() => changeView(name)}>`
to
` <Button key={i} onClick={() => props.onView(name)}>`

**Comment by Marceloasf** [comment]
For anyone looking for other demos on this thread, a simple and functional implementation (uses MUI):

    import {
      CalendarViewMonth,
      ChevronLeft,
      ChevronRight,
      Today,
      ViewDay,
      ViewWeek
    } from '@mui/icons-material';
    import { Box, Button } from '@mui/material';
    import dayjs from 'dayjs';
    import { Navigate as navigate } from 'react-big-calendar';
    import { useScreenSize } from '../../hooks';

    const CustomToolbar = ({ onView, onNavigate, label }) => {
      const screenSize = useScreenSize();

      const goToDayView = () => onView('day');

      const goToWeekView = () => onView('week');

      const goToMonthView = () => onView('month');

      const goToBack = () => onNavigate(navigate.PREVIOUS);

      const goToNext = () => onNavigate(navigate.NEXT);

      const goToToday = () => onNavigate(navigate.TODAY, dayjs());

      return (
        <>
          <Box className="rbc-toolbar">
            <Box
              className="rbc-toolbar-item-1"
              display="flex"
              flexDirection={screenSize.width < 992 ? 'column' : 'row'}
            >
              <Box className="rbc-btn-group">
                <Button
                  className="prev-icon"
                  id="prev-btn-icon"
                  onClick={goToBack}
                  startIcon={<ChevronLeft />}
                >
                  Back
                </Button>
                <Button
                  className="next-icon today"
                  onClick={goToToday}
                  endIcon={<Today />}
                >
                  Today
                </Button>
                <Button
                  className="next-icon"
                  id="next-btn-icon"
                  onClick={goToNext}
                  endIcon={<ChevronRight />}
                >
                  Next
                </Button>
              </Box>
              <Box
                sx={{ marginTop: 1, marginBottom: 0.5, justifyContent: 'center' }}
                className="rbc-toolbar-label rbc-date"
              >
                {label}
              </Box>
              <Box className="rbc-btn-group">
                <Button onClick={goToMonthView} endIcon={<CalendarViewMonth />}>
                  Month
                </Button>
                <Button onClick={goToWeekView} endIcon={<ViewWeek />}>
                  Week
                </Button>
                <Button onClick={goToDayView} endIcon={<ViewDay />}>
                  Day
                </Button>
              </Box>
            </Box>
          </Box>
        </>
      );
    };

    export { CustomToolbar };

Thanks for the other comments above that inspired this implementation.

**Comment by Hamjaster** [comment]
I've an issue ! I saw all the above comments, but how can I change toolbar info, as the date of calendar is clicked?? when the date is clicked, it opens the calendar for that specific date, but the toolbar isn't updated, and remains same, how can i update it ? please anyone help :(
