### ISSUE TITLE
Allow `formats` to return a renderable instead of a string

### ISSUE THREAD

**Issue by ffdead** [intljusticemission/react-big-calendar#194]
I need to inject some extra markup into the day header but it seems like the format can only handle a string.

I would need to return a couple of nested react elements in order to support the following design:

![screen shot 2016-10-17 at 15 09 21](https://cloud.githubusercontent.com/assets/420472/19438761/bb09ce74-947b-11e6-8516-4cc9bcc308b0.png)

Something like this would have been good:

```
const formats = {
    dayFormat: (date, culture, localizer) => {
      return (
        <div>
          <span>{localizer.format(date, 'dddd', culture)}</span>
          <span>{localizer.format(date, 'DD', culture)}</span>
          <TaskCountLabel date={date} />
        </div>
      )
    }
  }
```

Any ideas on how to solve this? Big thanks!

**Comment by jquense** [comment]
the `format` is the wrong place for that, its not a really a rendering API but a hook into the serializing and deserializing logic of i18n libraries. Generally we want to solve your case with specific `component` props, that are dedicated (and distinct from) localization.

we'd happily take a PR for that :)
