### ISSUE TITLE
Draggable pop up event

### ISSUE THREAD

**Issue by dncdrn** [intljusticemission/react-big-calendar#195]
Hi! Is it possible to make the event pop up draggable? 

![nnn](https://cloud.githubusercontent.com/assets/21171473/19462431/3992b38e-951f-11e6-9c1f-100f2404a226.PNG)

or is it possible to access that popup and attach it to draggable component? If then, how can i make custom event pop up?

Thanks in advance!

**Comment by dhyegocalota** [comment]
@jquense do we have an answer for that?
