### ISSUE TITLE
Rotate the calendar

### ISSUE THREAD

**Issue by thientran1707** [intljusticemission/react-big-calendar#197]
Is it possible to modify the calendar so that the events are horizontally? For example, the events of a day is not in column but row.

**Comment by jquense** [comment]
it is not currently possible, and there aren't any immediate plans to allow this.

**Comment by thientran1707** [comment]
is it possible to do that if i modify the source code? :(

**Comment by jquense** [comment]
it might be possible with css... its certainly not too bad to do if you fork (i'm guessing)
