### ISSUE TITLE
Customize order of time in Week view

### ISSUE THREAD

**Issue by thientran1707** [intljusticemission/react-big-calendar#198]
Hi, I need to customize the start of timeslots in Week view. Now, the first timeslot is 12am, however, if I want to start from 8 am, how can I do that?

**Comment by jquense** [comment]
you can use the `min` and `max` props.

**Comment by thientran1707** [comment]
thanks :) your library is so awesome

**Comment by critdhenz** [comment]
how to use that ( min and max)? sorry, I am just new in calendar

**Comment by AverageZ** [comment]
@critdhenz I was able to set min/max like so:
```
render() {
  const min = new Date();
        min.setHours(8);
        min.setMinutes(0, 0, 0);

  const max = new Date();
        max.setHours(22);
        max.setMinutes(0, 0, 0);

  return (
    <BigCalendar
      ...other props
      min={min}
      max={max}
    />
  );
}
```
This gives me start and end at 8am and 9pm
