### ISSUE TITLE
Display same time events side by side. 

### ISSUE THREAD

**Issue by Golczi** [intljusticemission/react-big-calendar#199]
Is there a way to display events that take place in same time next to each other?  I see that default way is showing that they overlap but I want to display them side by side.

**Comment by jquense** [comment]
there isn't an option for this, mostly because it would make events in the week view so thin as to be unreadable

**Comment by Golczi** [comment]
OK! Thank you for quick reply.

**Comment by mcpDeveloper** [comment]
I don't mind that they get really thin, What would i need to change so i could display events next to each other?
