### ISSUE TITLE
Month View: No "Selected Date" available

### ISSUE THREAD

**Issue by MattWilliamsDev** [intljusticemission/react-big-calendar#20]
Would like to add the ability to have the `.rbc-selected` class added to the month view to allow for styling on the selected day separately from today's date with `.rbc-now`.

**Comment by MattWilliamsDev** [comment]
I actually implemented this in our app, so I could submit a PR if you would like.

**Comment by jquense** [comment]
I'm generally open to PR's :) though I am not quite sure I understand what you are looking for here. just the ability to arbitrarily mark dates as "selected" ?

**Comment by MattWilliamsDev** [comment]
Yeah...as if using the calendar as navigation through datasets by date.

**Comment by jquense** [comment]
well I'm open to a PR I might use a different term/class that selected though just to avoid confusion with selecting dates with the mouse

**Comment by MattWilliamsDev** [comment]
As far as I know and can tell, that is the use case for this class as well.  The idea being that you click on a new date, and the new date has the `.rbc-selected` class added to it.
