### ISSUE TITLE
Error timeslots

### ISSUE THREAD

**Issue by ShintaroNippon** [intljusticemission/react-big-calendar#200]
I'm using this line of code

```
import React from 'react';
import ReactDOM from 'react-dom';

import BigCalendar from 'react-big-calendar';
import moment from 'moment';

// Setup the localizer by providing the moment (or globalize) Object
// to the correct localizer.
BigCalendar.momentLocalizer(moment); // or globalizeLocalizer



export default class Calendar extends React.Component {
    constructor(props, context) {
      super(props, context);
    }
  render() {
    return (
     <div>
         <BigCalendar
            events={[]}
        />
        </div>
    );
  }
}
```

But i'm getting this error console

Warning: Failed propType: Required prop timeslots was not specified in Calendar. Check the render method of Uncontrolled(Calendar).

And i'm getting no style on calendar... What i have missed ?

Thanks in advance. Carlos Vieira

**Comment by HriBB** [comment]
Just define `timeslots` prop on calendar component:

```
<BigCalendar
    timeslots={4}
    events={[]}
/>
```

And read the the [docs](http://intljusticemission.github.io/react-big-calendar/examples/index.html#prop-timeslots)!

**Comment by jquense** [comment]
the warning isn't so much a problem, but I should fix that

you aren't seeing any styles mostly likely because you didn't include the stylesheet check out the getting started guide: http://intljusticemission.github.io/react-big-calendar/examples/index.html#intro

**Comment by ShintaroNippon** [comment]
Thanks, i have missed the include of css style

**Comment by antoinerousseau** [comment]
this prop shouldn't be required, the default value is 2 anyway.
https://github.com/intljusticemission/react-big-calendar/blob/master/src/TimeColumn.jsx#L22

**Comment by brianrc** [comment]
I got this too. The timeslots prop isn't in any of the examples so it's confusing. The warning also shows up on the official demo pages.
