### ISSUE TITLE
Warning: You are manually calling a React.PropTypes validation function for the `view` prop 

### ISSUE THREAD

**Issue by HriBB** [intljusticemission/react-big-calendar#201]
I'm getting this warning when I pass `view` and `date` props to Calendar:

```
Warning: You are manually calling a React.PropTypes validation function for the `view` prop on `Calendar`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
```

Is this normal, or am I doing something wrong? Do you accept PRs for the fix?

**Comment by danqing** [comment]
Getting the same warning.

For one, I understand that `view` and `date` should be initialized by their default values. On the other hand, I think there should be a proper way to update the view and date of the calendar from the outside.

**Comment by AverageZ** [comment]
@danqing Switching from `date` to `defaultDate` did the trick. I second the idea of being able to update the view from outside

**Comment by jquense** [comment]
The `view` and `date` props _are_ how you control the view and date from the outside

**Comment by aforaudrey** [comment]
@jquense right, but that results in the warning @HriBB posted above. (although it's only a warning)

**Comment by jquense** [comment]
yup, just a warning, will be fixed in the next release

**Comment by aforaudrey** [comment]
Thanks @jquense !

**Comment by stefyrosca** [comment]
How about the "Unknown prop `allDayAccessor` on <div> tag. Remove this prop from the element. For details" warning?
