### ISSUE TITLE
disable "All day"  row

### ISSUE THREAD

**Issue by KnockNow** [intljusticemission/react-big-calendar#203]
Hi,
thank you for this library !
i want disable the display of the line "all day", how can i do pls ? 
And i have a problem with the view. I can't disable two view (day and aganda)...

**Comment by mawek** [comment]
you can pass ```views``` property to the ```BigCalendar``` component
```
<BigCalendar
                        events={events}
                        views={['week', 'day']}
                        defaultView={'week'}
...
```

**Comment by KnockNow** [comment]
Thank you but i want disable the row "All day", is that possible ?

**Comment by jquense** [comment]
its not currently possible to disable the all day view, in part because there would be no way of showing events that span multiple days (even if they aren't marked all day), as @mawek points out you can adjust the vies you want with the `views` prop

**Comment by mcmatan** [comment]
Is there a way of currently removing this line? Maybe with css?

**Comment by KnockNow** [comment]
Yes, I have sucessfully done it but not with css (it's not possible because that line have a dependency). You can fork this lib and just comment the code that does this. (And why not create a parameter for enable/disable that line). Good luck !

**Comment by mcmatan** [comment]
Yeah that's what I had in mind, thanks! (:

**Comment by mcmatan** [comment]
Did it with CSS! Boom!
```

.rbc-time-view .rbc-row {
    min-height: 0px;
}

.rbc-time-view .rbc-row div:nth-child(1) {
    height: 0px !important;
}
```

**Comment by Maxincredible52** [comment]
@mcmatan you the real mvp

**Comment by tkporter** [comment]
For anyone else looking to use @mcmatan's solution, you can use that and set the `allDay` message to `''`: http://intljusticemission.github.io/react-big-calendar/examples/index.html#prop-messages

**Comment by darrenklein** [comment]
I went with

    .rbc-row:nth-of-type(2) {
	    display: none !important;
    }

Anything wrong with that?

**Comment by darrenklein** [comment]
Using version `0.16.1`, I found this worked:

    .rbc-time-header > .rbc-row:nth-of-type(2) {
	    display: none !important;
    }

This got rid of the 'all day' row in week and day views. Anything wrong with this fix?

**Comment by drewandrew** [comment]
I used
```css
.rbc-allday-cell {
  display: none;
}
.rbc-time-view .rbc-header {
  border-bottom: none;
}
```
anything wrong with this (as far as CSS hacks go)?

It would still be nice to disable the allday row altogether. I wonder if a PR that added an option for disabling the allday row, instead opting to display multi-day events with a note (i.e. "cont'd on next day) or an arrow pointing into the next/previous day, would be accepted? Maybe that's a more complex solution than most people need, but currently I have data that will just not be shown because the event would technically be an All Day event.

**Comment by jquense** [comment]
ya'll you can disable the allday row by setting http://intljusticemission.github.io/react-big-calendar/examples/index.html#prop-showMultiDayTimes

**Comment by sedenardi** [comment]
@jquense Hi Jason, I'm trying to disable the allday row using `showMultiDayTimes` and not getting it. Here's a basic example where specifying `showMultiDayTimes` is expected to make the allday row disappear. Can you let me know where I'm going wrong?

https://codesandbox.io/s/3q8mrk9l7q

**Comment by flolege** [comment]
Is there any new development? @jquense suggested solution does not work for me either. 
It basically seems feasible, the first Basic example shows that.

**Comment by sedenardi** [comment]
I ended up doing it via CSS mentioned by @drewandrew.

**Comment by nickcarnival** [comment]
I'm using  @drewandrew's CSS and noticed that when using the `resourceGroupingLayout` there was some extra space underneath the resource titles.

I've added this style to remove it:

```css
.rbc-time-view .rbc-row {
    min-height: unset;
}
```

|Default Min Height|Unset Min Height|
|-|-|
|<img width="964" alt="Screenshot 2024-12-27 at 10 45 24 PM" src="https://github.com/user-attachments/assets/541e6ba0-7daf-4faf-b391-8b497e81ed1b" />|<img width="964" alt="Screenshot 2024-12-27 at 10 45 39 PM" src="https://github.com/user-attachments/assets/7eb6758f-5d11-4e37-9033-ca9622deae1f" />|
