### ISSUE TITLE
No Calendar for Month View

### ISSUE THREAD

**Issue by Aviglik91** [intljusticemission/react-big-calendar#204]
Upon rendering the calendar, I cannot see the monthly view. I only see the header:
Month, Year and button on left and right side and the Days. Below that is already empty, no cells displaying the days of the months.  

Note: when i use **inspect elements** i can see tables,row etc object.. i guess its a problem with the css ?

 let Popup = React.createClass({
  render(){
    return (
      <div {...this.props}>
        <BigCalendar
          popup
          step={15}
          timeslots={8}
          events={events}
          defaultDate={new Date(2016, 10, 27)}
        />
      </div> 
  )}
})

ReactDOM.render(
<Popup/>,
  document.getElementById('app')
);

**Comment by jquense** [comment]
you need to make sure your calendar has an explicit height set. either its container or the calendar itself

**Comment by KnockNow** [comment]
+1 
i have the sample problem. Do you have resolve ?

**Comment by jquense** [comment]
> you need to make sure your calendar has an explicit height set. either its container or the calendar itself

**Comment by KnockNow** [comment]
it's perfect thank you !
