### ISSUE TITLE
Edit event title

### ISSUE THREAD

**Issue by Aviglik91** [intljusticemission/react-big-calendar#205]
Hey, i'm trying to edit the previewed event title with not success  

event:[ {
     'title': 'Lesson with miki',
     'start':new Date(2016, 9, 28, 16, 0, 0, 0),
     'end': new Date(2016, 9, 28, 18, 0, 0, 0),
   },]

Code :
let Popup = React.createClass({
  render(){
    return (
      <div {...this.props}           >

```
    <BigCalendar

      timeslots={4}
      events={events}
      defaultView='week'
      titleAccessor={function(e){console.log(e);return e.title;}}
      views={['week','day']}
    />
  </div>
)
```

  }
})
![github-issue](https://cloud.githubusercontent.com/assets/22911125/19830246/72631c3a-9da8-11e6-87d6-0178ab7ee04d.png)

i'm trying to remove the start/end time out of the event

**Comment by Itayazolay** [comment]
+1

**Comment by jquense** [comment]
you can return an empty string form the eventTimeRangeFormat if you want to not show anything for the event times

**Comment by vanderstel** [comment]
You can use CSS as a last resort. The class you want is `.rbc-event-label`:

```css
.rbc-event-label {
  display: none;
}
```

**Comment by techaijaz** [comment]
const { formats } = useMemo(
    () => ({
      formats: {
        eventTimeRangeFormat: ({ start, end }, culture, localizer) => {},
      },
    }),
    []
  );
  
  <Calendar
   formats={formats}
   />

**Comment by email-templates5** [comment]
https://supermanwiry1.github.io/egnqY0BjR75SW9U4B2uSyvW3SX2B1Sx36U6ZjY3V5apraZ3JgY94Rg0nJqrb0aN/



I found the missing piece
