### ISSUE TITLE
React error : react 15.3.1

### ISSUE THREAD

**Issue by KnockNow** [intljusticemission/react-big-calendar#206]
Hi, 

when i install (npm install react-big-calendar --save) i have a error with Peer Dependency.

├── UNMET PEER DEPENDENCY react@^0.14.0 || ^15.0.0
├─┬ react-big-calendar@0.11.0 
│ ├── UNMET PEER DEPENDENCY react@>=0.14.0
│ └── UNMET PEER DEPENDENCY react-dom@>=0.14.0
└── UNMET PEER DEPENDENCY react-dom@^0.14.0 || ^15.0.0

Do you have a idea for resolve pls ?

**Comment by jquense** [comment]
hi there, this isn't an issue with RBC, it looks like you have an invalid setup of packages that require incompatible versions of react
