### ISSUE TITLE
Bug of cell

### ISSUE THREAD

**Issue by KnockNow** [intljusticemission/react-big-calendar#211]
Hi,

i want 1 hours for 1 cell. So enter on the param : 
step={1}
timeslots={60}
 
But the cell is offbeat...

**Comment by jquense** [comment]
flip the values with the props atound

**Comment by KnockNow** [comment]
i don't have understand sorry, what's atound ? 

<BigCalendar
	            events="{this.events}"
	            views="{['month', 'week']}"
	            step={1}
	            timeslots={30}
	            min="{new Date(2016, 10, 3, 7, 0, 0)}"
	            max="{new Date(2016, 10, 3, 23, 0, 0)}"
	            defaultView='week'
	          />

**Comment by jquense** [comment]
do: step={60} timeslots={1}

**Comment by KnockNow** [comment]
Awesome ! Thank u :)
