### ISSUE TITLE
Running integration tests with enzyme

### ISSUE THREAD

**Issue by TeaBough** [intljusticemission/react-big-calendar#218]
I'm trying to run integration tests. I'd like to simulate the selection of a slot using enzyme. I can't find a way to do that using the simulate function of enzyme : https://github.com/airbnb/enzyme/blob/master/docs/api/ShallowWrapper/simulate.md
```
.simulate('click') will actually get the onClick prop and call it.
```
But there are no `onClick` method on `DayColumn`, it's all handled in the `Selection.jsx` file. Does anyone have any ideas how to simulate the selection of a slot using enzyme ?

**Comment by jquense** [comment]
simulate the event that a slot selection fires instead. e.g. `onSelectSlot`

**Comment by TeaBough** [comment]
I tried but `simulate` allows only "regular" synthetic event : https://github.com/airbnb/enzyme/blob/1880850d260ac159cf92c3a839f39592d3afa67f/src/Utils.js#L318

**Comment by TeaBough** [comment]
I've managed to fix my problem using this : http://stackoverflow.com/questions/39767177/using-enzyme-simulate-on-custom-events
