### ISSUE TITLE
Customize event color

### ISSUE THREAD

**Issue by guddenxd** [intljusticemission/react-big-calendar#219]
Would be really nice if you can add a event color in the json maybe, so each event can have their own color.

**Comment by jquense** [comment]
you can handle that yourself with the `eventPropGetter` prop 👍

**Comment by jayakar723** [comment]
When i'm using eventPropGetter it is showing error like, event.hexColor is not defined.


 
eventStyleGetter({event, start, end, isSelected}) {
  var backgroundColor = '#' + event.hexColor;
  var style = {
      backgroundColor: 'green',
      borderRadius: '0px',
      opacity: 0.8,
      color: 'black',
      border: '0px',
      display: 'block'
  };
  return {
      style: style
  };
}

**Comment by AlexAndrei98** [comment]
that is because your event object needs to have an `hexColor` attribute to it.
