### ISSUE TITLE
Any plans of a React Native equivalent?

### ISSUE THREAD

**Issue by sanketsahusoft** [intljusticemission/react-big-calendar#220]
Awesome library! Any plans of having a React Native version of the same?

**Comment by jquense** [comment]
probably not. There is a ton of DOM specific code here, that would be difficult or impossible to port to RN, also we don't do any RN development at the moment so there isn't much of a need.

**Comment by acro5piano** [comment]
@sanketsahusoft 

Hi, I am creating react-native-big-calendar, inspired by this library.

https://github.com/llotheo/react-native-big-calendar

The functionality has not been equivalent to react-big-calendar yet, but basic features such as rendering cell components, weekly schedules, and listing events are implemented. And it runs on Web/Android/iOS. 

Please take a loot! Thanks.
