### ISSUE TITLE
Week and Daily View, Daylight Savings Display Issue

### ISSUE THREAD

**Issue by dan-diaz** [intljusticemission/react-big-calendar#221]
With the calendar in weekly view, look at at the start or end of daylight savings
2016-3-13 or 2016-11-6

Scroll your calendar down to the last hour. 
Your day is either long or short by 1 hour.
This mostly makes sense if we're looking at all 24 hours of the day.
<img width="324" alt="2016-3-13" src="https://cloud.githubusercontent.com/assets/753113/20570292/12fd9478-b171-11e6-9acc-0d6008640219.png">

But if we restrict this view to show less than 24 hours, by setting the max property to 3am for example, the missing/extra hours are still affecting the display.
<img width="278" alt="" src="https://cloud.githubusercontent.com/assets/753113/20570652/78c485cc-b172-11e6-8958-0b18a64e62b3.png">

Strange, but setting the max to 2am or less does not reveal the same issue.

1. Should there be a boolean property to show/hide these DST hour differences?
2. If the max hour is earlier than the switch to or from DST, there should not be a missing/extra hour displayed.

**Comment by leesalminen** [comment]
Also experiencing the same issue.

**Comment by dan-diaz** [comment]
Among my project team, this issue has been de-prioritized. Granted it only makes two appearances each year, but I'm still curious if there is a solution. Good luck @leesalminen

**Comment by mtt87** [comment]
Found this today as well...

**Comment by jquense** [comment]
no solution at the moment but that is due more to not having time then anything else. If someone wants to jump in and tackle it please go ahead. The problem is always needing to handle this in a culture agnostic way.
