### ISSUE TITLE
Day View - All Day Event

### ISSUE THREAD

**Issue by AshworthHub** [intljusticemission/react-big-calendar#222]
I see at the top of the Day view there is a placement for All Day events.  However, from the example, the all day event setup on March 31 doesn't show up in the Day view.

**Comment by Vitall** [comment]
+1

**Comment by tonyarkles** [comment]
👍

**Comment by tonyarkles** [comment]
@jquense much appreciated, thanks!

**Comment by critdhenz** [comment]
is that fix already? ty
