### ISSUE TITLE
Event title tooltip should stringify

### ISSUE THREAD

**Issue by NullDivision** [intljusticemission/react-big-calendar#226]
It would appear that in case where we want to stylize (bold, italic, etc) some parts of an event title, it shows up properly on the page but the tooltip contains `[object Object]` as values.

A solution would be to use the `jsx-to-string` library to stringify the value or better yet add a tooltipAccessor method.

**Comment by aray12** [comment]
On a similar note, how would you feel about removing the string literal here

https://github.com/intljusticemission/react-big-calendar/blob/aecb5da3f0e2915f06b9062d71bc5aa844e518a5/src/DayColumn.js#L172

We actually don't want a tooltip (don't have good use-case for it). But this code makes it impossible to remove and ends up with `: null` instead

**Comment by nguyenanduong** [comment]
Any plan to fix this?
Thanks
