### ISSUE TITLE
Disable to select cells under an event

### ISSUE THREAD

**Issue by thientran1707** [intljusticemission/react-big-calendar#227]
How can I disable cells under a event in week view?  For example, if I have an event on Monday from 3pm to 4pm, I should not be able to select slots from 3pm to 4pm anymore, since I find it is annoying when I click on the event, the cells under it are selected

**Comment by jquense** [comment]
check out: http://intljusticemission.github.io/react-big-calendar/examples/index.html#prop-onSelecting You can return `false` from this and it will prevent selection from continuing or beginning
