### ISSUE TITLE
Examples don't work out of the box

### ISSUE THREAD

**Issue by harel** [intljusticemission/react-big-calendar#23]
When running `npm run examples` the following errors come up: 
```
ERROR in ./examples/App.js
Module not found: Error: Cannot resolve module 'markdown-jsx-loader' in /home/harel/dev/tmp/bigcal/react-big-calendar/examples
 @ ./examples/App.js 13:15-36

ERROR in /home/harel/dev/tmp/bigcal/react-big-calendar/node_modules/component-metadata-loader/lib/index.js:12
    let prism = require('./prism-jsx');
    ^^^
Unexpected strict mode reserved word
 @ ./examples/Api.js 11:49-106
```

I'm trying to get a baseline example in order to report another display issue when using big cal with semantic ui (at least that's my suspicion) but for now I can't even get the examples to work.

**Comment by jquense** [comment]
the example build code is written on node 4 so it's using es6 features (in this case 'let') that it has. you can use node 4+ to run them for now. I might also get around to refactoring for older node versions. 

note: there is no need to have modern node to use the lib, just to get the examples to build and run

**Comment by harel** [comment]
I didn't notice I was using an older version of NodeJS. However, after upgrading, I still have one error remaining when i `run examples`:

```
ERROR in ./examples/App.js
Module not found: Error: Cannot resolve module 'markdown-jsx-loader' in /home/harel/dev/tmp/bigcal/react-big-calendar/examples
 @ ./examples/App.js 13:15-36
```

**Comment by harel** [comment]
After trying to reinstall that module i gave up and removed that bit of code from the examples.
I guess I can close this one now, and focus on trying to replicate my real problem where the month calendar's cells are 0 height in my app.

**Comment by mrdrozdov** [comment]
Getting the same error using most recent Node.
