### ISSUE TITLE
Loading react-big-calendar.css example

### ISSUE THREAD

**Issue by brianrc** [intljusticemission/react-big-calendar#234]
Thank you for this calendar.

The docs say I need to load react-big-calendar.css, but there is no example provide and I don't see it in the repo. I'm a bit confused. How do I load the css?

Thanks!

**Comment by marcmoy** [comment]
@brianrc I came across this issue too. I went to my `node_modules/` folder and copied & pasted the `react-big-calendar/lib/css/react-big-calendar.css` file into my project.

Not sure if this is the best way to handle this.

If anyone knows a less hackier way, I'm all ears.

**Comment by VadimuZz** [comment]
@marcmoy import 'react-big-calendar/lib/css/react-big-calendar.css';

**Comment by brianrc** [comment]
Thanks pointing me in the right direction! I got it to work, although it does seem hacky. Is there any better way? 

I also had to adjust the calendar height before things would display properly. 

And their was a warning without a timeslots prop.

**Comment by jquense** [comment]
not sure why it seems hacky? the css is included in package... what would you like to see?

**Comment by brianrc** [comment]
I don't know. I'm still very new to the node/react world. I'm learning how things are done. As a newbie, it was not immediately evident I had to pull a file out of the node_modules folder and include it manually.

If the documentation could be updated to include the specific steps, with code examples, that would be helpful for other newbies.

Playing with and loving the calendar so far!

**Comment by erickzhao** [comment]
Note: If you're using style-loader and css-loader and you have `modules:true` enabled on css-loader, make sure to import it as global CSS like such: `import '!style-loader!css-loader!react-big-calendar/lib/css/react-big-calendar.css'`.

**Comment by alansutherland** [comment]
@erickzhao thank you, this should be in the docs!!!

**Comment by ANANDKNIT** [comment]
> Note: If you're using style-loader and css-loader and you have `modules:true` enabled on css-loader, make sure to import it as global CSS like such: `import '!style-loader!css-loader!react-big-calendar/lib/css/react-big-calendar.css'`.

great It solved the issue
