### ISSUE TITLE
Error: Cannot find module 'react-big-calendar/utils/constants

### ISSUE THREAD

**Issue by elmorenocivitas** [intljusticemission/react-big-calendar#235]
I'm using browserify  on my project and when trying yo use the example [code](https://github.com/intljusticemission/react-big-calendar/blob/master/examples/demos/customView.js#L4):

```javascript
import { navigate } from 'react-big-calendar/utils/constants';
import Week from 'react-big-calendar/Week';
import dates from 'react-big-calendar/utils/dates';
import localizer from 'react-big-calendar/localizer';
import TimeGrid from 'react-big-calendar/TimeGrid';
```
I get the following of error:
```
Error: Cannot find module 'react-big-calendar/TimeGrid'
Error: Cannot find module 'react-big-calendar/Week'
Error: Cannot find module 'react-big-calendar/localizer'
Error: Cannot find module 'react-big-calendar/utils/dates'
Error: Cannot find module 'react-big-calendar/utils/constants'
```

Is there a special setup I need in order to reach those constants/components?
What am I missing here?  :suspect:

**Comment by jquense** [comment]
you probably shouldn't be requiring the constants and components individually, but if you do need to the path to them is: `'react-big-calendar/lib/utils/constants'`, the example site has a bespoke webpack config that makes those other requires work

**Comment by elmorenocivitas** [comment]
So what's the preferred method to reach those instead of importing them directly?
I'm doing it in order to code my custom components so I can:
`<Calendar components={components} />`

Thanks for the fast answer btw!
