### ISSUE TITLE
Examples in production

### ISSUE THREAD

**Issue by brianrc** [intljusticemission/react-big-calendar#237]
Are there any examples of this library in production? I would love to see them!

I listened to [a fantastic talk](https://www.youtube.com/watch?v=mVVNJKv9esE) recently about the levels of abstraction in programming and ways to minimize it so users have an easier time understanding new libraries (which increases adoption). One of the simple ways suggested was providing more examples! This library has some great ones. I'd love to see more production examples. 👍

**Comment by jquense** [comment]
hi there. I'd love to post some links to production examples, but I don't know of any 😬 that are publicly accessible! This sort of library tends to be used more in apps behind a login, so its tougher to know where folks are using it. If you have any examples i'll be happy to link em here

**Comment by fxfactorial** [comment]
I'm using it here: http://silicondzor.com

**Comment by josephcureton** [comment]
I completely agree! There are great examples on other libraries like [materializecss](http://materializecss.com/showcase.html). I am working on a small project now using the library and will publish a link here when it is completed.

**Comment by brianrc** [comment]
My site using it is now up. https://www.acrowithbrian.com/events/
