### ISSUE TITLE
Event Categories

### ISSUE THREAD

**Issue by brianrc** [intljusticemission/react-big-calendar#238]
Is there a way to change the color of event title based on its category (.e.g. classes vs workshops etc)?

Right now all the event titles are the same color with the class name _rbc-event_ applied to every one. 

I would love to be able to pass a category in with the event which would then put a category class on the event div so I could style it based on category.

**Comment by jquense** [comment]
yup, you can provide any class or style you want via the eventPropGetter prop

**Comment by brianrc** [comment]
Can you provide an example? I don't understand how to use that.

**Comment by jquense** [comment]
it's a function that is passed the event and returns an object with a className abd/or style prop. the API docs describe the prop , you  can poke through the source for more info

**Comment by brianrc** [comment]
Thank you. 

For those that come after me and in the spirit of open source, I figured it out.

```
<BigCalendar
          eventPropGetter={event => ({className: 'category-' + event.category.toLowerCase()})}
          events={events}
/>
```
Make sure category is defined in the events you pass in.

**Comment by critdhenz** [comment]
Hi, I need help, it gives me error
eventPropGetter={event => {
				if (event.finished_at !== null) {
							({ className: 'event-done' });
						}
					}}

**Comment by critdhenz** [comment]
Thanks for this :)

**Comment by Bentopi** [comment]
This was really helpful! Maybe add an example to the docs?

**Comment by jquense** [comment]
let me know if you have any questions. docs are generated from the comments in `Calendar.js`
