### ISSUE TITLE
Custom Agenda date range?

### ISSUE THREAD

**Issue by zpeterg** [intljusticemission/react-big-calendar#240]
I have searched the docs, issues, and Google, but have not been able to find a solution to this:

How do I change the Agenda time range? Currently it is defaulting to 1 month. Can I make this 1 day?

**Comment by jquense** [comment]
oops missing some documentation. the prop is `length` (in days) which controls the range of the Agenda view

**Comment by zpeterg** [comment]
Great, thank you!

**Comment by zpeterg** [comment]
For reference for people with the same question: Pass the prop like so `<BigCalendar` ... length={0.5} ... />`  to get one day in the Agenda.

And note that, while this will change of events displayed, the range at the top of the page evidently is not controlled by this prop. If showing 1 day, you can do a custom agendaHeaderFormat to cut it down to the "start" portion of the date.

**Comment by vilmes21** [comment]
`http://intljusticemission.github.io/react-big-calendar/examples/index.html` here is the official doc. So `length` prop has been deprecated?

**Comment by jquense** [comment]
no it's just mistakenly undocumented

**Comment by tobiasandersen** [comment]
It's been added (and merged), so on next build it'll be there!
