### ISSUE TITLE
npm install from github doesn't seem to work?

### ISSUE THREAD

**Issue by IanLondon** [intljusticemission/react-big-calendar#243]
I'm new to installing from GitHub directly with npm and can't seem to get this to work. I'm trying to get the new drag-and-drop stuff to work in my own project -- it's not in the npm module yet. But I can't get react-big-calendar's `lib/` to show up.

Here's my most minimal setup, starting from empty directory:

```bash
npm init -y
npm install --save react react-dom
```

I then tried `npm install --save intljusticemission/react-big-calendar` and `npm install --save https://github.com/intljusticemission/react-big-calendar`.

All I get is: 

```bash
ls node_modules/react-big-calendar/
# CHANGELOG.md  LICENSE  package.json  README.md`
```

`lib/` is missing!

I tried `rm -rf node_modules` and reinstalling but got the same result. Even tried cleaning the npm cache.

Am I doing something wrong, or is `package.json` not set up for npm install from GitHub?

Thanks!

**Comment by jquense** [comment]
the package isn't immediately installable from github, you'd need to build it once you install it
