### ISSUE TITLE
BackgroundCells.jsx `selectable` PropTypes should include 'ignoreEvents' string

### ISSUE THREAD

**Issue by IanLondon** [intljusticemission/react-big-calendar#244]
it seems the `selectable` prop of BackgroundCells ought to be `selectable: React.PropTypes.oneOf([true, false, 'ignoreEvents'])`, just like DayColumn. 

BackgroundCells uses this logic on line 102: `if (this.props.selectable !== 'ignoreEvents') return`

Right now, it's `selectable: React.PropTypes.bool` only.

**Comment by jquense** [comment]
yup, PR welcome!
