### ISSUE TITLE
Events outside of the min/max times are rendering in random slots.

### ISSUE THREAD

**Issue by mikemerritt** [intljusticemission/react-big-calendar#249]
I have a min and max value set (9am and 5pm respectively) but I have an event being sent from the server that has a start time of 4am. This event appears at the 2pm timeslot but says 4am on it's label. Am I wrong in having the expectation that events outside of the min and max times should not render on the calendar?

**Comment by schester44** [comment]
Was there a fix for this? I'm still seeing this same issue.
