### ISSUE TITLE
Filter events in Agenda

### ISSUE THREAD

**Issue by mlp73** [intljusticemission/react-big-calendar#251]
Hey, 
I'm following this pattern to customize the Agenda:
agenda: {
    date: Component,
    time: Component,
    event: Component
  }
It is per now possible to style it, but I can't find any way to actually filter a component.
F.eks if(event.status === 'draft'){...}
In the case I don't want to display an event, it will always output at least an empty cell.

Is there any way to filter an event at a higher level?
Is there as well any way to display range events on a single line, instead of having to ouput 'from day XX', to 'day XX'

Could not fint more in the documentation. Thank you.

**Comment by jquense** [comment]
you can filter the events when you pass then to the calendar, or in response to calendar callbacks. in other words, if you dont want to see an event then dont pass it to the calendar

**Comment by mlp73** [comment]
Well, I meant an event I want to see in the Calendar, but not in the Agenda.

That makes sense to me in a way that I have events from different categories.
Consider for example: f eks. 'Event location A', 'Event location B', 'Event location C'.
And on the Agenda: 'See events from my location'.

Which explains why I wish to filter out some events.

**Comment by mlp73** [comment]
Any answer when it comes to the range?

Is there any way at least to access the event object from the date so I could do something with it? Any possibility to add a class to target it or something?

**Comment by raullarosa** [comment]
To display specific events on your agenda view, filter your events by location when your active view is 'agenda'. You can gain control of this prop using the props available to you.

**Comment by vilmes21** [comment]
@raullarosa , could you write some code to demo your way please?

**Comment by vilmes21** [comment]
One prop `onView` can be used like `handleOnView = viewNameString => {
if (viewNameString === "agenda") //then change the event state data in your way...
}
`
