### ISSUE TITLE
Using AllDay should default to inclusive ranges

### ISSUE THREAD

**Issue by brianrc** [intljusticemission/react-big-calendar#254]
I agree with the calendar's default use of exclusive ranges. If an event ends on April 8th 12:00:00 AM it shouldn't show up on April 8th, but in the case of using the AllDay option it doesn't make much sense.

I just ran into the issue of an event with the following settings only displaying for January 6th and 7th.
start: January 6, 2017
end: January 8, 2017
allDay: true

All day should default to inclusive ranges.

**Comment by brianrc** [comment]
Testing the latest version (12.1) my use case was fixed, but it's still a bit buggy.

The following will highlight 3 days on month view:
```
start: January 6, 2017
end: January 8, 2017
allDay: true

```
While this will highlight only 1 day:
```
start: January 6, 2017
end: January 7, 2017
allDay: true
```

**Comment by WaldoJeffers** [comment]
The monthly view still uses exclusive ranges with `allDay` set to true. I'm using `v12.3`.

**Comment by jquense** [comment]
Hi folks, the recent updates only tangentially touch this issue. I'm not switching to inclusive ranges for just all day events if I can help it. It adds an unnecessary inconsistent behavior. What I am trying to do is fix all the small edge inconsistencies that already exist in how are displayed. namely making sure zero dimension events show up on the first and last of the month. Still working at it tho. so any examples of where it's doing odd things is helpful

**Comment by epitts** [comment]
Using version `12.3`, running into an inconsistency between `'week'` and `'day'` view treatment of `allDay=true` events. `'day'` view appears to treat all day events as inclusive ranges, `'week'` view treats them as exclusive.

For example event:
```
start: March 21, 2017
end: March 22, 2017
allDay: true
```
On the week view, event is only rendered on the 21st.
But if I open a day view on the 22nd with the same set of events, the event is rendered on the 22nd.

Easy enough to work around, but I would expect day view to also treat the date range as exclusive and not display the event on the 22nd.

**Comment by peterdivvito** [comment]
+1 for getting this fixed.

@epitts you said 'easy enough to work around'. Could you elaborate?

**Comment by rdalfonso** [comment]
I'm having a similar issue. 

Start date: **Fri May 25** 2018 00:00:00 GMT-0500 (Central Daylight Time)
End date: **Tue May 29** 2018 00:00:00 GMT-0500 (Central Daylight Time)

The calendar only highlights May 25 - May 28th.
How can I get the calendar to highlight the day of my end date May29th?

**Comment by croustibat222** [comment]
> I'm having a similar issue.
> 
> Start date: **Fri May 25** 2018 00:00:00 GMT-0500 (Central Daylight Time)
> End date: **Tue May 29** 2018 00:00:00 GMT-0500 (Central Daylight Time)
> 
> The calendar only highlights May 25 - May 28th.
> How can I get the calendar to highlight the day of my end date May29th?

Hello, have you found a workaround finally? I am googling for 2 hours but can't find how to solve this..
I've seen something with the endAccessor changing the date but can't have it work yet.
Thank you in advance.
