### ISSUE TITLE
Expose constants for navigation

### ISSUE THREAD

**Issue by tobiasandersen** [intljusticemission/react-big-calendar#257]
Hi! Really enjoying this library so far, great work!

I'm currently using the `views` constants to change view:
`onViewChange(views.DAY)`

It'd be nice to do the same for navigation: 
`onNavigate(navigate.NEXT)`

But they aren't exposed, so I'm currently using strings in various places. This is obviously not the end of the world, but still, is there a reason you haven't exposed the [navigate constants](https://github.com/intljusticemission/react-big-calendar/blob/master/src/utils/constants.js#L2-L7)? Or would you be okay with a PR for this?

**Comment by jquense** [comment]
i'm happy to take a PR for that thanks
