### ISSUE TITLE
Disable to select cells under All Day in week or day view

### ISSUE THREAD

**Issue by critdhenz** [intljusticemission/react-big-calendar#259]
How can i disable cells under All day in week or day view? When I click event in All day, the select slot will be selected too.

**Comment by jquense** [comment]
you already made this issue

**Comment by critdhenz** [comment]
Hi sir, thank you for your response. But do you have the solution for that? 

Sent from Yahoo Mail on Android 
 
  On Sat, Jan 7, 2017 at 3:37 AM, Jason Quense<notifications@github.com> wrote:   
you already made this issue
