### ISSUE TITLE
Improve day view layout

### ISSUE THREAD

**Issue by tobiasandersen** [intljusticemission/react-big-calendar#263]
The day view isn't very good at showing many events at the same time:

![screen shot 2017-01-11 at 13 48 34](https://cloud.githubusercontent.com/assets/3599069/21849240/065a0fde-d805-11e6-940a-15cb18cccb6d.png)
![screen shot 2017-01-11 at 13 48 54](https://cloud.githubusercontent.com/assets/3599069/21849244/08e37a4c-d805-11e6-9773-d07cc4dc1f15.png)

I much prefer the way e.g. Apple handles it in their Calendar app in OS X:

![screen shot 2017-01-11 at 13 49 57](https://cloud.githubusercontent.com/assets/3599069/21849255/13d86124-d805-11e6-9aae-e7418126ede0.png)

Would you be interested in a PR for something similar to the image above?

**Comment by jquense** [comment]
The calendar events shouldn't overflow past their column, thats definitely a bug. In terms how to display them, I prefer the approach it takes now (more like google calendar) vs the the mac calendar app (which also is showing less events?). I'd be open seeing the PR if it does make situations better _without making the other common situtations any worse_, which is always the concern with layout algorithms, especially in css.

**Comment by tobiasandersen** [comment]
Oh I see. That bug threw me off a bit, I didn't even realise it was a Google-like approach. I don't think Apple shows less events (I just failed at creating the same number of events in my example). 

I just took a look at the differences between the two (Apple and Google):

Google:

![screen shot 2017-01-11 at 14 24 04](https://cloud.githubusercontent.com/assets/3599069/21850289/2e93fe92-d80a-11e6-87b9-16c286ac1c5e.png)

Apple:

![screen shot 2017-01-11 at 14 24 11](https://cloud.githubusercontent.com/assets/3599069/21850293/32b05b9c-d80a-11e6-942e-288e1bc416c7.png)

Here I personally prefer Apple's approach. I'm not a fan of having different widths for events on the same row. However, when there are events that "contain" other events, I prefer the way Google handles it:

Google:

![screen shot 2017-01-11 at 14 34 57](https://cloud.githubusercontent.com/assets/3599069/21850515/4132071e-d80b-11e6-9d46-1b1dc979a344.png)

Apple:

![screen shot 2017-01-11 at 14 35 04](https://cloud.githubusercontent.com/assets/3599069/21850520/4667d038-d80b-11e6-8d17-1bd6cdb58da1.png)

I don't believe we have any special cases, some days have **lots** of events, others don't, so we need all cases covered. In the end I don't really care that much about which layout to pick, but I think both would be an improvement over the current one. 

If you don't feel too strongly about one or the other, I'll just create something that works well for us, and then turn that into a PR for you to look at. Then we can take it from there and hopefully reach something that works for everyone.

**Comment by jquense** [comment]
I'd definitely appreciate a PR to improve this :) I think it may be harder then it first seems tho (especially apples approach). Your example has a neat symmetry to it, in that, there are no large overlapping blocks of events, which is a bit mroe straightforward to imagine the algorithm to implement it. 

![image](https://cloud.githubusercontent.com/assets/339286/21852298/843195be-d7e0-11e6-8f42-420722ac2c9e.png)

Is a bit more complex, in terms of figuring out how to order, and arrange. That said the current code already does some work to understand the contiguous sections of events that "overlap" in order to figure out how far to offset them to the right. That with some ordering might be all you need to get a neater layout.

btw the reason I like the google approach is that in cases with fewer events you get larger--more readable--event blocks, vs non-overlapping ones.

![image](https://cloud.githubusercontent.com/assets/339286/21852412/e75955a0-d7e0-11e6-9437-abcecc3f9e0f.png)

**Comment by tobiasandersen** [comment]
Yeah I've already started experimenting some and it's definitely a bit tricky. That's a good argument for having overlapping blocks. But I feel like it will be harder to get right. I'll keep you updated!

**Comment by tobiasandersen** [comment]
I think I have something working now. I'll test it a bit more and do some clean up, then we'll start using it internally. If you want, I can create a PR at the same time.

I'll post some screenshots below, comparing a few data sets with the current layout. 

Example 1 (the 1 picture you posted):
--

**Current (note that 4 events are clipped):** 

![screen shot 2017-01-14 at 01 15 35](https://cloud.githubusercontent.com/assets/3599069/21950129/49ae6f38-d9f8-11e6-9ca5-77635540423d.png)

**New:** 

![screen shot 2017-01-14 at 01 20 37](https://cloud.githubusercontent.com/assets/3599069/21950173/b5998a66-d9f8-11e6-87ee-29ee55cc8459.png)

Example 2:
--
**Current:**

![screen shot 2017-01-14 at 01 16 19](https://cloud.githubusercontent.com/assets/3599069/21950237/1cf71174-d9f9-11e6-8d01-4bb5596cdb68.png)

**New:**
![screen shot 2017-01-14 at 01 21 10](https://cloud.githubusercontent.com/assets/3599069/21950255/3cecb9ca-d9f9-11e6-981a-5c41b77deb52.png)


Example 3 (the 2 picture you posted):
--
**Current:**

![screen shot 2017-01-14 at 01 36 23](https://cloud.githubusercontent.com/assets/3599069/21950331/f0fd742c-d9f9-11e6-8ce7-596630652bf8.png)

**New:**

![screen shot 2017-01-14 at 01 24 11](https://cloud.githubusercontent.com/assets/3599069/21950307/c96e7276-d9f9-11e6-9c47-6bc3b8485cad.png)

**Comment by jquense** [comment]
that looks great! big improvement :thumbsup: I'm happy to take a PR any time you think it's gtg

**Comment by tobiasandersen** [comment]
Thanks! I'll have it ready early next week.

**Comment by MarshallOfSound** [comment]
@tobiasandersen Can you push your current code to a branch somewhere, keen to see if this fixes an issue I am having

**Comment by tobiasandersen** [comment]
@MarshallOfSound They're in a PR now:  https://github.com/intljusticemission/react-big-calendar/pull/269

**Comment by mikemerritt** [comment]
Any ETA on this being released?
