### ISSUE TITLE
Highlighting a slot over an event? (Week and Day view)

### ISSUE THREAD

**Issue by critdhenz** [intljusticemission/react-big-calendar#264]
When highlighting a slot over an event, two alert modal shows, how to prevent highlighting a slot without triggering the event? Thanks
Thanks

**Comment by AverageZ** [comment]
It seems to work fine in the demo [here](http://intljusticemission.github.io/react-big-calendar/examples/index.html), also working fine using v0.11.1 on my machine. Maybe go back and check to make sure your code is similar to the example code?
