### ISSUE TITLE
Month view displays collapsed unless position: absolute

### ISSUE THREAD

**Issue by jforaker** [intljusticemission/react-big-calendar#27]
Month view displays collapsed unless `position: absolute` 

Before:  
![image](https://cloud.githubusercontent.com/assets/2042031/12331450/9270576a-bab7-11e5-9c3a-a3a72d71f204.png)

I added `position: absolute` here:
```
.rbc-calendar {
    box-sizing: border-box;
    height: 100%;
    display: flex;
    flex-direction: column;
    align-items: stretch;
    position: absolute;
}
```

After:
![image](https://cloud.githubusercontent.com/assets/2042031/12331529/f0cdb514-bab7-11e5-9c15-aaa76cc4724c.png)

**Comment by jquense** [comment]
what browser are you viewing it in?

**Comment by jforaker** [comment]
Chrome

**Comment by jquense** [comment]
more context would be helpful...the docs work jsut fine in Chrome for me (and others)

**Comment by jforaker** [comment]
I just have it on a plain page with no styling (bootstrap css loaded), inside one div that is: 

```
    height: 400px;
    width: 50%;
    margin: 0 auto;
    outline: 1px solid gray;
```

And it renders like this without absolute pos on the `.rbc-calendar` element:

![image](https://cloud.githubusercontent.com/assets/2042031/12333099/3e38e942-bac0-11e5-9507-400eda36537d.png)

**Comment by jquense** [comment]
Sorry, I tried to recreate your example and everything works fine for me.

The calendar is styled to `height: 100%` so it's parent need an explicit height. You just want to set the height of the Calendar, then go ahead and adjust the rbc-calendar to be whatever your app needs.

`position: 'absolute'` is definitely not the right approach tho because that is just causing hte calendar to overflow and expand to the height of the entire window, but it will overflow everything around it.

In general you may want to use flexbox since it makes styling and 100% heights much more intuitive than plain ol css

**Comment by nottombrown** [comment]
I had this same issue. Using current Chrome.

**Comment by jacktrades** [comment]
I just ran into this too.  Setting a fixed height on the parent works.  Perhaps this is something that should be pointed out in the example/readme/docs?

**Comment by okcompute** [comment]
I faced the same issue (Chrome). @jquense is right, by setting the *height* it fixes the issue. I used the `style` component props to set it up:

      <BigCalendar
        events={events}
        defaultDate={new Date(2015, 3, 1)}
        style={{height: 800}}
      />

**Comment by RejinR** [comment]
@okcompute Thanks a lot.. This fixed the problem for me as well.. Only the month tab was not displaying

**Comment by eseakin** [comment]
Wow this took me hours to solve. I kept seeing 'need to set an explicit height' but didn't understand that I needed to add a parent div with a height. The examples don't show this at all. Didn't know I could pass a style prop, tried to pass a height prop, didn't want to tweak the css in the node modules. It's so obvious in hindsight... 20/20 right?

Works perfectly now!
