### ISSUE TITLE
Feature request: year view

### ISSUE THREAD

**Issue by isaachinman** [intljusticemission/react-big-calendar#270]
So after looking around for a few days, it's become clear to me that this is the most well-developed, well-supported _full functionality_ calendar for React in existence. The only view it's missing is a year view, which is quite helpful in jumping around whilst doing long-term scheduling.

There are two possibilities in doing this: (1) an actual, functional yearly view that fires events with individual dates etc, and (2) a more view-only year overview which jumps into month view whenever a specific date is selected.

Option (2) is how AirBnb does it, and I think it's the wiser of the two options - a yearly view is more of a fast overview to jump into months themselves:

![screen shot 2017-01-17 at 13 37 14](https://cloud.githubusercontent.com/assets/10575782/22020751/3b2f4742-dcba-11e6-8673-b7a2ae17f504.png)

Seeing as a yearly view is nothing more than a combination of elements in this project which already exist, I think this is a pretty reasonable feature request. What do you all think?

**Comment by tobiasandersen** [comment]
I think we'll need this in the future as well! It's not urgent however, so I personally don't have any plans on creating one any time soon. But, as you say, I don't think it would be too hard to do.

**Comment by jquense** [comment]
I didn't personally have a need for this here.  but it definitely shouldn't be too hard to do. I'd happily take a pull request adding this if anyone is up for it

**Comment by isaachinman** [comment]
@tobiasandersen @jquense Would you guys have any preference as to the two possible options for implementation? I don't have a tonne of time for a PR but Option 2 seems quite simple.

**Comment by tobiasandersen** [comment]
I think both options are fine. Is it really harder to create the first option? 

FWIW, Apple seems to go with option 2 as well...

**Comment by isaachinman** [comment]
It might not be any harder, but I tend to think it's wiser to go with Option 2; a monthly calendar is always going to perform better and feel nicer than 12 monthly calendars crammed into the same space. I suppose the only advantage to a fully-functional year view is datepicking a range that spans across months..?

**Comment by jquense** [comment]
i'm definately for option 2, I think you'll run into to many issues and perf concerns with trying to show full calendars for 12 months

**Comment by isaachinman** [comment]
@jquense Okay then, any preference between the "AirBnb" way, vs the "React Widgets" way below?

![screen shot 2017-01-17 at 16 11 04](https://cloud.githubusercontent.com/assets/10575782/22025952/a08fbb84-dccf-11e6-84ac-3020efad4c54.png)

**Comment by jquense** [comment]
I like the airbnb way for this component, but it's up to you since your the one with the use case :)

**Comment by TrejGun** [comment]
I'd like to help with this

**Comment by isaachinman** [comment]
@TrejGun Be my guest, I haven't even had time to get started yet.

**Comment by isaachinman** [comment]
@TrejGun Are you going to start on this? If I do it, I'd prefer to just work on my own fork and not have to worry about too many merges.

**Comment by TrejGun** [comment]
@isaachinman please do it, I will help you to test

**Comment by dmitriyK1** [comment]
+1

Would be a nice feature to have

**Comment by jssisodiyaPG** [comment]
+1

**Comment by buddythumbs** [comment]
+1

**Comment by wktq** [comment]
+1
