### ISSUE TITLE
Feature request: weekNumber

### ISSUE THREAD

**Issue by WaldoJeffers** [intljusticemission/react-big-calendar#271]
Hello, first of all, thanks for the good work, `react-big-calendar` is probably the best React calendar today, and it's very easy to use. 
I think it would be interesting to display each week's number in the monthly view, like this :
![weeknumber](https://cloud.githubusercontent.com/assets/7644970/22022690/4a0b6bca-dcc3-11e6-8d32-7e599f4474ba.jpg)
Many people in businesses identify weeks by their number. Fullcalendar has a [weekNumbers option](https://fullcalendar.io/docs/display/weekNumbers/). What do you think ?

**Comment by pungggi** [comment]
I would also appriciate this ,🙋

**Comment by pungggi** [comment]
https://github.com/jquense are you open for PR for this?

**Comment by pungggi** [comment]
@jquense are you open for a PR for this?

**Comment by jquense** [comment]
sure 👍

**Comment by psamariya** [comment]
Is this feature "weekNumber" implemented in react-big-calendar?

**Comment by pixelass** [comment]
why was this closed? Any news here?

**Comment by deusexmachina892** [comment]
Has this feature been implemented?

**Comment by amansehgalg** [comment]
Hello @jquense, Please let us that weekNumber is showing in react-big-calendar or not?

**Comment by jquense** [comment]
It's not implemented. the issue is closed because maintainers don't plan on adding it. Anyone is welcome to contribute the feature of they do want to

**Comment by bartvanandel** [comment]
I was looking for the same thing. After some consideration, we've come up with the following code, which does the job for us. Note that this code uses moment, suit to your needs if you are using a different date wrapper. Also you will likely need to add some styling, hence the `className={styles.weekNumber}` (we're using SCSS modules, again, suit to your needs).

```jsx
import { Calendar as BigCalendar } from 'react-big-calendar';
import DefaultDateHeader from 'react-big-calendar/lib/DateHeader';

const WeekNumber = ({ week, weekYear }) => (
  <span className={styles.weekNumber} title={`Week ${week}-${weekYear}`}>
    {week}
  </span>
);

const DateHeader = (props) => {
  const m = moment(props.date);

  return (
    <>
      {
        // Display week number on leftmost day in calendar view
        m.weekday() === 0 && <WeekNumber week={m.week()} weekYear={m.weekYear()} />
      }
      <DefaultDateHeader {...props} />
    </>
  );
};

// rendering the calendar:
const cal = (
  <BigCalendar
    components={{
      dateHeader: DateHeader,
    }}
    ... // other props
  />
); 
```

I'd advise against using the ISO week, as this is not locale-aware. But if you really want ISO weeks, you can use `m.isoWeekday()`, `m.isoWeek()` and `m.isoWeekYear()` in the above example.

**Comment by ysbakker** [comment]
I was looking for a solution for adding week numbers to the calendar, but this proved difficult as I wanted to add the week number to the date in the toolbar, unlike @bartvanandel 's suggestion which is a nicer workaround. So initially I just put the week number somewhere else on the page.

But I did some digging and for me the best solution was creating a custom toolbar component. I committed some typescript warcrimes here (`as any` 🤮) and also rewrote it to a functional component. This gives the following result:

<img width="1205" alt="image" src="https://github.com/jquense/react-big-calendar/assets/24809068/1abe8e8f-c5a7-4884-b847-ec23a9d9c483">

`CustomToolbar.tsx`:

```tsx
const CustomToolbar = ({
  onNavigate,
  onView,
  localizer: { messages },
  label,
  views,
  view,
  date,
}: ToolbarProps) => {
  const ViewNamesGroup = () => {
    let viewNames = views as string[]

    if (viewNames.length > 1) {
      return viewNames.map(name => (
        <button
          type="button"
          key={name}
          className={clsx({ 'rbc-active': view === name })}
          onClick={() => onView(name as View)}
        >
          {(messages as any)[name]}
        </button>
      ))
    }
  }

  const week = getWeek(date, {
    locale: nl,
    weekStartsOn: 1,
  })

  return (
    <div className="rbc-toolbar">
      <span className="rbc-btn-group">
        <button type="button" onClick={() => onNavigate('TODAY')}>
          {messages.today}
        </button>
        <button type="button" onClick={() => onNavigate('PREV')}>
          {messages.previous}
        </button>
        <button type="button" onClick={() => onNavigate('NEXT')}>
          {messages.next}
        </button>
      </span>

      <span className="rbc-toolbar-label">
        {label} - week {week}
      </span>

      <span className="rbc-btn-group">
        <ViewNamesGroup />
      </span>
    </div>
  )
}
```

Using in react big calendar:

```tsx
<ReactBigCalendar
    components={{ toolbar: CustomToolbar }}
/>
```

This issue is quite old, but I'd be happy to contribute a similar implementation. Perhaps so an option to enable week number gets exposed in the calendar?
