### ISSUE TITLE
Disable, or at least add custom class, to dates in the past (month view)

### ISSUE THREAD

**Issue by isaachinman** [intljusticemission/react-big-calendar#272]
So I guess it's pretty clear that I am putting this project to use by all the issue tickets I'm opening. Sorry for that! I understand that "disabling" is really only possible out-of-the-box in week and agenda views, and has to do with actual times, not days.

However, in my application, I am only as granular as full days, and I need to prevent users from selecting days in the past, as it's a booking/accommodation utility. A lot of similar calendars have `min` dates, even in month view. 

**I don't mind much if it isn't supported by default here, but I'd at least need a way to provide a different css class to the `rbc-day-bg` nodes which represent days in the past, so that I can apply a not-allowed cursor and ignore pointer actions.**

To your knowledge, is there any way this is possible?

**Comment by isaachinman** [comment]
@jquense I think this would have to be done via a custom component passed into BigCalendar, right? Do you know if that'd be either `dayWrapper` or `dateCellWrapper`?

**Comment by isaachinman** [comment]
I see you are conditionally setting a class if a date `isToday` on [this line](https://github.com/intljusticemission/react-big-calendar/blob/master/src/BackgroundCells.js#L70). Would you accept a PR to include a class of `rbc-past` on past days?

**Comment by tobiasandersen** [comment]
I also like the idea of having the possibility to style backgrounds differently.  But couldn't we instead use something similar to the `eventPropGetter`? I think I remember seeing someone who wanted to style the backgrounds of weekends differently. I'm sure there're even more use cases that could be covered by making this more flexible.

**Comment by isaachinman** [comment]
@tobiasandersen Sorry, doesn't that function only process events?

**Comment by jquense** [comment]
see my comment here: https://github.com/intljusticemission/react-big-calendar/pull/210#issuecomment-260126514 for bg cell styling. always open to PR's

**Comment by tobiasandersen** [comment]
@isaachinman yes exactly, and calling it `backgroundPropGetter` (like @jquense suggested in that PR) sounds reasonable!

**Comment by jquense** [comment]
btw you _can_ do this now, by providing a backgroundCellWrapper component if you really want too. those are more a hook for doing stuff like drag and drop but they are there.

**Comment by isaachinman** [comment]
@tobiasandersen Sure, that sounds good. Still, I'd keep it to a simple util function that can return additional css classes if desired instead of manipulating the grid itself.

@jquense I just did a ctrl+f for `backgroundCellWrapper` in the entire repo and found nothing. Do you have any idea where I can find out more about this?

Cheers for being so responsive guys. Seriously makes me happy to see a well-supported open source project with good contributors.

**Comment by jquense** [comment]
sorry it's called `dateCellWrapper` oops: https://github.com/intljusticemission/react-big-calendar/blob/master/src/Calendar.js#L360
