### ISSUE TITLE
Monthly Calendar Grid Visible Behind Modal

### ISSUE THREAD

**Issue by mcverter** [intljusticemission/react-big-calendar#273]
In Monthly Calendar View only, the Calendar Grid is completely visible behind a modal (here I am using react-modal).  Note that the other items in the view respond appropriately to the modal overlay 
![calendarwmodal](https://cloud.githubusercontent.com/assets/1453956/22092210/0e4a12fa-ddca-11e6-81d5-4f99dd22fa19.PNG)

**Comment by jquense** [comment]
you probably need to increase the z-index of the modal.  not really familiar with react-modal

**Comment by mcverter** [comment]
I have adjusted the zIndex, the rgba, the opacity, and the positioning.  I will send a new screen shot to demonstrate.  It is a problem only with the monthly calendar grid.

**Comment by jquense** [comment]
there really isn't anything I can do here unfortunately. you'll have to figure out style for the modal that works. from the screenshot tho it's clear the modal is below the calendar event layer.

**Comment by mcverter** [comment]
Okay.  Got it. It was the zIndex of the overlay that needed to be adjusted rather than the zIndex of the modal content. Not sure why it was an issue only for this part of the calendar.

**Comment by mcverter** [comment]
Thanks

**Comment by jquense** [comment]
:thumbsup:

**Comment by Anujjaglan9423** [comment]
![image](https://github.com/user-attachments/assets/b8c1b5a5-b95d-4552-a985-12f5c8aa01fc)
when the modal open date also shows above the modal please suggest any solution.
React-big-calender

**Comment by cutterbl** [comment]
You can use a `<dialog>` element for your modal, ensuring it's always on top-layer. If you portal your modal to the document.body then it may also automatically manage the z-index. Or you just manually set your z-index to something higher than these other bits.
