### ISSUE TITLE
showMore message dont work

### ISSUE THREAD

**Issue by lfirek** [intljusticemission/react-big-calendar#274]
Hello,

I have message prop
```
let msg = {
  showMore: total => `+${total} ...`
}
```
and BigCalendar component
```
           <BigCalendar
                events={this.props.events}
                views={['month', 'agenda']}
                popup={true}
                messages={msg}
                defaultDate={new Date()}
            />
```

but showMore looks like "+[0-9] more" but i want "+[0-9] ..."

It's bug or I do something wrong?

**Comment by tobiasandersen** [comment]
You're right, that's a bug, thanks for reporting! I'll create a fix for it.

**Comment by gsavvid** [comment]
@tobiasandersen actually this still doesn't work for me. I can change all the other messages, except for `showMore`. I'm using react-big-calendar v0.12.3.

**Comment by lfirek** [comment]
@gsavvid last release was "15 days ago" so still doesn't work :) You need wait for new release :)

**Comment by ofekinger** [comment]
I saw that the fix for this bug was merged with the master branch, but when I used the code from GitHub, I still couldn't modify the showMore message...

**Comment by diegomura** [comment]
I can't modify the text either. Is there any progress on this?

**Comment by lfirek** [comment]
Yep, for me it works great :)

2017-06-01 14:42 GMT+02:00 Diego Muracciole <notifications@github.com>:

**Comment by paulhuisman** [comment]
Is it also possible to fetch the `events hidden after click` number instead of `total rows` ?
