### ISSUE TITLE
Custom ranges for views

### ISSUE THREAD

**Issue by bkniffler** [intljusticemission/react-big-calendar#277]
Hey, 
Would it be possible to pass custom ranges to agenda and some kind of week view, to not display a range of days that follow each another, but to have total control about which days exactly, possibly with gaps?

**Comment by tobiasandersen** [comment]
Hi! I'm not sure I understand what you're trying to achieve, so this might be totally off, but if you want to hide certain days in the agenda view, it'd probably be easiest not to pass events from those days in the first place. 

In the week view however, I'm not really sure what you mean by "not displaying" some days? Do you want the whole day (i.e. the column) to be removed entirely from the calendar? Or should they just be styled differently?

**Comment by bkniffler** [comment]
Yes, something like the week view but instead of displaying say 
- ['2015-01-01', '2015-01-02', '2015-01-03', '2015-01-04', '2015-01-05', '2015-01-06', '2015-01-07']
I'd like to show
- ['2015-01-01', '2015-01-05', '2015-01-14', '2015-01-20', '2015-02-01', '2015-02-02', '2015-02-03']

So a view that just gets an array of dates that it shall show.

**Comment by jquense** [comment]
you can take a look at how the Week and Day components are built on TimeGrid and provide a custom View component to the calendar. I _believe_ the api is general enough to allow your situation I've never tried it with non contiguous ranges but I don't think that should be a problem. You'll need to provide custom `navigate` static methods to your view.

**Comment by bkniffler** [comment]
I looked into it, but the TimeGrid would only accept a start/end date in its current state. Why not calculate the array of displayed dates  from within the view instead of inside the TimeGrid. So instead of providing start/end to let TimeGrid calculate the range, you'd always provide an array of dates.

**Comment by jquense** [comment]
I'd be fine with that change. feel tree to send a PR over :)

**Comment by jquense** [comment]
Closing to keep the tracker neat. Please feel free to PR anything back if you implement this :)
