### ISSUE TITLE
React warning when using custom view

### ISSUE THREAD

**Issue by manlao** [intljusticemission/react-big-calendar#279]
![qq20170122-1](https://cloud.githubusercontent.com/assets/1523671/22180568/9d8d9c16-e0ae-11e6-9538-2a01f028ae62.png)

**Comment by tobiasandersen** [comment]
Can you post the code that produces this error?

**Comment by olekst** [comment]
Basically this code here: https://github.com/intljusticemission/react-big-calendar/blob/master/examples/demos/customView.js used with https://github.com/intljusticemission/react-big-calendar/blob/master/examples/App.js

**Comment by manlao** [comment]
@tobiasandersen , as @olekst said, I just uncommented line 80 to 84 in https://github.com/intljusticemission/react-big-calendar/blob/master/examples/App.js

**Comment by jquense** [comment]
that example is commented out b/c it is not accurate :P

**Comment by manlao** [comment]
@jquense , and how can I use custom view? Please help!
