### ISSUE TITLE
Surfacing events from agenda view

### ISSUE THREAD

**Issue by hlindley-ccssi** [intljusticemission/react-big-calendar#280]
Hi,

I'd like to know if it is possible for the component that instantiates the calendar to receive events from a button in a custom agenda view?  I have an agenda view with an "add to my schedule" button and I would like to be able to determine that an agenda item has been clicked on in order to manage state in the parent component.

I can't seem to pass props or callback functions to the agenda view and it appears that onSelectSlot and onSelectEvent only apply to calendar cells and not agenda items.

Thanks in advance for any help or pointers to example code.

**Comment by jquense** [comment]
see this comment: https://github.com/intljusticemission/react-big-calendar/issues/261#issuecomment-273487073
