### ISSUE TITLE
Big calendar doesn't show events

### ISSUE THREAD

**Issue by AgoraWebFR** [intljusticemission/react-big-calendar#281]
Hello, first i'll try to write it in a good english but i'm french so ... sorry.

My ReactClass is very simple but the component BigCalendar  doesn't show any event.
This is the component :

> `let BigCalendar = require('react-big-calendar');
> let moment = require('moment');
> BigCalendar.momentLocalizer(moment);
> import "react-big-calendar/lib/css/react-big-calendar.css";
> 
> let CalendarBlock = React.createClass({
> 
>     componentDidMount: function () {
>         // Mount
>         console.log("Mount")
>     },
> 
>     handleSelectSlot: function ({start, end}) {
>         console.log(start);
>         console.log(end);
>     },
> 
>     handleSelectEvent: function (event) {
>         console.log("Select event:");
>         console.log(event);
>     },
> 
>     render: function () {
> 
>         let events = [
>             {
>                 'start' : new Date(2017, 1, 1) ,
>                 'end' : new Date(2017, 2, 1) ,
>                 'title': "Hello"
>             }
>         ];
> 
>         return <BigCalendar
>             culture="fr-FR"
>             events={events}
>             startAccessor='startDate'
>             endAccessor='endDate'
>             selectable={true}
>             style={{height: 800}}
> 
>             onSelectSlot={this.handleSelectSlot}
>             onSelectEvent={this.handleSelectEvent}
>             defaultDate={new Date()}
>             eventPropGetter={e => ({className: 'test-class'})}
>         />
>     }
> 
> });`
> 

The component is Mount, the calendar is in the Webpage but no event on this one. I've try to remove CSS but nothing more. The calendar is here (without css) but no event display. 
Can anyone help me ? :)

**Comment by tobiasandersen** [comment]
Hi! The calendar component will use the `startAccessor` and `endAccessor` props to find the start and end time of your events. Given the data you've provided here, they should be set to `'start'` and `'end'`, rather than `'startDate'` and `'endDate'`, so this should work:

```
<BigCalendar
  culture="fr-FR"
  events={events}
  startAccessor='start'
  endAccessor='end'
  selectable={true}
  style={{height: 800}}

  onSelectSlot={this.handleSelectSlot}
  onSelectEvent={this.handleSelectEvent}
  defaultDate={new Date()}
  eventPropGetter={e => ({className: 'test-class'})}
/>
```

**Comment by AgoraWebFR** [comment]
I love you my friend !!! :) :+1: 
This work perfeclty now !!
I've just change this :
`startAccessor='startDate'
  endAccessor='endDate'`

to this:
`startAccessor='start'
  endAccessor='end'`

**Comment by tobiasandersen** [comment]
Great! 👍
