### ISSUE TITLE
Vertical scheduler view

### ISSUE THREAD

**Issue by padsbanger** [intljusticemission/react-big-calendar#282]
Greetings,

I am building an appointment scheduling application. I have list of employees, each with their own array of events.

I am aiming to have a view like this:

https://fullcalendar.io/js/fullcalendar-scheduler-1.5.0/demos/vertical-resource-view.html

Each employee has a vertical column displayed with its own events, so that they dont overlap. 

Is it doable with `react-big-calendar` ?

**Comment by tobiasandersen** [comment]
Hi! I this the same as #13?

**Comment by jquense** [comment]
I think so. This isn't possible right now, unless you want to create a custom view (which you can!)
