### ISSUE TITLE
Uncaught TypeError: Cannot read property 'matches' of null

### ISSUE THREAD

**Issue by BrianTatum** [intljusticemission/react-big-calendar#283]
I am trying to use this component in a Rails project using the React On Rails gem. I believe the competent is causing the above error as everything was working before I included it. Any help would be greatly appreciated.

**Comment by tobiasandersen** [comment]
Can you show how you use it? It's really hard suggesting anything with this info alone.

**Comment by BrianTatum** [comment]
Below is a copy of my component file. It was working when I included the JS at the bottom of the HTML file, but that threw an error with two copies of babel-pollyfill. When it is included in the HEAD then the above error is thrown.

import React, { PropTypes } from 'react';
import {Modal} from 'react-bootstrap';
import moment from 'moment';
import BigCalendar from 'react-big-calendar';

BigCalendar.setLocalizer(
  BigCalendar.momentLocalizer(moment)
);

export default class EventCal extends React.Component {

  constructor() {
    super();
    this.state = {
      openModel: false,
      openPath: '',
      groupName: '',
      creatModel: false,
      startDate: new Date(),
      endDate: new Date(),
      newpath: ''
    }
  }

  render() {
    return (
    <div>    	
  		<div className='row row-spacing'>
  			<div className='col-xs-12'>
  				<h1>Calendar View</h1>
          <BigCalendar
            selectable
            style={{height: '800px'}}
            events={this.props.event_list}
            eventPropGetter={(this._eventStyleGetter)}
            views={['month']}
            onSelectEvent={event => this._openEvent(event)}
            onSelectSlot={slotInfo => this._creatNewEvent(slotInfo)}
          />
  			</div>
  		</div>
      <div className='row'>
        <div className='col-md-2'>
          <p>Status Key:</p>
        </div>
        <div className='col-md-2'>
          <p className='text-center' style={{color: 'white', backgroundColor: '#3174ad'}}>Requested</p>
        </div>
        <div className='col-md-2'>
          <p className='text-center' style={{color: 'white', backgroundColor: '#ff9900'}}>Pending</p>
        </div>
        <div className='col-md-2'>
          <p className='text-center' style={{color: 'white', backgroundColor: '#ff0000'}}>Confirmed</p>
        </div>
        <div className='col-md-2'>
          <p className='text-center' style={{color: 'white', backgroundColor: '#006600'}}>Completed</p>
        </div>
        <div className='col-md-2'>
          <p className='text-center' style={{color: 'white', backgroundColor: '#b3b3b3'}}>Canceled</p>
        </div>
      </div>
      <Modal show={this.state.openModel} onHide={this._closeModel.bind(this)}>
        <Modal.Header closeButton className='main-color'>
          <Modal.Title>Open Retreat Confirmation</Modal.Title>
        </Modal.Header>
        <Modal.Body>
          <div className='row row-spacing'>
            <div className='col-xs-12'>
              <h2 className='text-center'>Do you want to open {this.state.groupName}?</h2>
            </div>
          </div>
          <div className='row'>
            <div className='col-sm-6'>
              <a href={this.state.openPath} className="btn btn-lg btn-success btn-block">Open</a>
            </div>
            <div className='col-sm-6'>
              <button type="button" className="btn btn-lg btn-success btn-block" onClick={this._closeModel.bind(this)}>Close</button>
            </div>
          </div>
        </Modal.Body>
      </Modal>
      <Modal show={this.state.creatModel} onHide={this._closeModel.bind(this)}>
        <Modal.Header closeButton className='main-color'>
          <Modal.Title>Creat New Request</Modal.Title>
        </Modal.Header>
        <Modal.Body>
          <div className='row'>
            <div className='col-xs-12'>
              <h2 className='text-center'>Do you want to creat a new request for the dates below?</h2>
            </div>
          </div>
          <div className='row row-spacing'>
            <div className='col-sm-6'>
              <h3 className='text-center'>Begining Date</h3>
              <p className='text-center'>{this.state.startDate.toLocaleString('en-US',{ weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' })}</p>
            </div>
            <div className='col-sm-6'>
              <h3 className='text-center'>End Date</h3>
              <p className='text-center'>{this.state.endDate.toLocaleString('en-US',{ weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' })}</p>
            </div>
          </div>
          <div className='row'>
            <div className='col-sm-6'>
              <a href={this.state.newPath} className="btn btn-lg btn-success btn-block">Open</a>
            </div>
            <div className='col-sm-6'>
              <button type="button" className="btn btn-lg btn-success btn-block" onClick={this._closeModel.bind(this)}>Close</button>
            </div>
          </div>
        </Modal.Body>
      </Modal>
    </div>
    )
  }

  _eventStyleGetter (event, start, end, isSelected) {
    let backColor='';
    switch (event.status) {
      case 1:    //Status: Requested
        backColor = '#3174ad'
        break
      case 2:    //Status: Pending
        backColor = '#ff9900'
        break
      case 3:    //Status: Confirmed
        backColor = '#ff0000'
        break
      case 4:    //Status: Completed
        backColor = '#006600'
        break
      case 5:    //Status: Canceled
        backColor = '#b3b3b3'
    }
    const style = {backgroundColor: backColor}    
    return { style: style };
  }

  _openEvent(event) {
    this.setState({
      openModel: true,
      openPath: event.openPath,
      groupName: event.title
    })
  }

  _creatNewEvent(slotInfo) {
    const newPath = this.props.newPath + `?startDate=${slotInfo.start}&endDate=${slotInfo.end}`;
    this.setState({
      creatModel: true,
      startDate: slotInfo.start,
      endDate: slotInfo.end,
      newPath: newPath
    })
  }

  _closeModel() {
    this.setState({
      openModel: false,
      creatModel: false})
  }
}

**Comment by jquense** [comment]
do you have the rest of the stack trace? I don't think this is due to RBC, it seems like there is a regex match attempt somewhere on something that isn't a string

**Comment by BrianTatum** [comment]
Below is a copy of my component code as a text file. I had the component working by including it at the bottom of the HTML file, but then I found that it was throwing an error with bable-pollyfill (more that one). When it is included in the HEAD I get the above error.

[comp.txt](https://github.com/intljusticemission/react-big-calendar/files/735970/comp.txt)

Full copy of error from my console:
Uncaught TypeError: Cannot read property 'matches' of null
    at eval (eval at <anonymous> (webpack-bundle.js:5798), <anonymous>:21:27)
    at eval (eval at <anonymous> (webpack-bundle.js:5798), <anonymous>:26:5)
    at Object.<anonymous> (webpack-bundle.js:5798)
    at __webpack_require__ (webpack-bundle.js:21)
    at eval (eval at <anonymous> (webpack-bundle.js:5792), <anonymous>:8:16)
    at Object.<anonymous> (webpack-bundle.js:5792)
    at __webpack_require__ (webpack-bundle.js:21)
    at eval (eval at <anonymous> (webpack-bundle.js:5786), <anonymous>:15:16)
    at Object.<anonymous> (webpack-bundle.js:5786)
    at __webpack_require__ (webpack-bundle.js:21)

**Comment by jquense** [comment]
this component doesn't use babel-polyfill so that error isn't likely to be related here.

Sorry your stack trace isn't helpful, I'd really consider enabling source maps on your app, so you can see where the error actually happens in the source files instead of a giant compiled bundle.

**Comment by BrianTatum** [comment]
I have traced the error to: ./~/dom-helpers/query/matches.js. Is this a dependancy of RBC. Looks like the JS is running before the DOM is loading.

**Comment by jquense** [comment]
that's on you then :P you shouldn't be loading these in the head, and if you insist on that not without an onReady check

**Comment by BrianTatum** [comment]
I am trying to use this in a Ruby on Rails app using the React_On_Rails gem. I thought the gem  was going to transpile all the React.js code, add it into the Rails assets pipeline and then run is after the DOM loads, but something it is allowing that dom-helper to run before everything is ready. I am moving my issue over to React_On_Rails. 

BTW: I have gotten a mock up done with this component. It is a great calendar, looks great on the page, and has some wonderful features.

Thanks for your help!! @jquense

**Comment by shadysayed** [comment]
I've faced the same thing. It is not related to react-big-calendar. you need to move your javascript_include_tag into the body (remove it from the head and put it in the body)

**Comment by BrianTatum** [comment]
I have tried that as well and then I get babel-polyfill error (more than one loading). I have talked to the creator of React-on-Rails gem and they say to leave it in the head. I do not think anything is wrong with RBC.. It is the integration of react.js into a rails app using this gem. Still have not worked it out at this point, but that is were I am working at this point. Had to take a break from it for a while and work on other areas of my app for now. I will re-post back here if I get it working. Would appreciate any help and input anyone can offer.

**Comment by RKushnir** [comment]
@BrianTatum I made a PR to address this issue in the dom-helpers.
To keep JS tag in the document head is a default in Rails. I don't think it's ok for a library to force you to move it.

**Comment by spherop** [comment]
I had a similar issue attempting to use this component with [react-webpack-rails](https://github.com/netguru/react_webpack_rails). `Cannot read property 'matches' of null` errors when deploying to Heroku - but not locally.

**Comment by Sihui** [comment]
Suggestion from @shadysayed  works for me!
Thanks!
> you need to move your javascript_include_tag into the body (remove it from the head and put it in the body)
