### ISSUE TITLE
Drag and Drop Events to Next Month

### ISSUE THREAD

**Issue by doshisunny** [intljusticemission/react-big-calendar#285]
I want to move events between months. Is there current support for this?
When I tried to move to next month and select next month. It does not show moved event.
If not does it support double click event ?

**Comment by jquense** [comment]
its not supported right now, and we aren't likely to work on it as the addons are outside the scope of general maintenance. We happily accept PR's though

**Comment by doshisunny** [comment]
Thanks @jquense . We will create double click and will create PR.
