### ISSUE TITLE
Previous & Next Callback

### ISSUE THREAD

**Issue by AgoraWebFR** [intljusticemission/react-big-calendar#288]
Hi everyone,
I don't find it on Google ... and i don't think i'm the only one to need it.
I want to load only event's of the current month view (or week, or day ...). So when i click on the button Previous or Next, or today (or month / week / day / agenda) i want to call a function Ajax to get events.
But impossible to understand / found the callback of the button.
Does it possible ? And how ?

**Comment by jquense** [comment]
you can use the [`onNavigate`](http://intljusticemission.github.io/react-big-calendar/examples/index.html#prop-onNavigate) callback fro that

**Comment by AgoraWebFR** [comment]
OnNavigate give only 1 date ? Not the begining and the end of the month(date, week)view ?

**Comment by jquense** [comment]
yup one date. You can pretty easily pick a range from that to fetch events. If you want to PR something that adds the start/end of the current view as well I'd happily accept it

**Comment by AgoraWebFR** [comment]
I will watch it when i've minutes. Thx for your help

**Comment by crystal1990** [comment]
I meet the same question, I can not get start and end time when I change the view. I need to get data when I change the view.
