### ISSUE TITLE
issue while using dnd and popup together

### ISSUE THREAD

**Issue by rrameshkumar76** [intljusticemission/react-big-calendar#289]
When dragging and dropping a event from a popup(more option) the dragged event does not clear from the popup overlay, even after render to calendar has been triggered. 

If this cannot be fixed is there a way to programmatically close the popup as the popup does refresh after a outside click and when reopened. I can just close the popup after drag is completed.

**Comment by rrameshkumar76** [comment]
One way i could handle the above issue was to trigger click on a different element on drag complete to close the popup.

**Comment by jquense** [comment]
Hi there, thanks for the issue. The Drag and Drop functionality is an addon to react-big-calendar. We include it in the main package for ease of use for users, but it's not maintained at the same level as the calendar itself. As such improvements/bug fixes are going to be slow coming, and we encourage users to contribute back those fixes themselves.

thanks!
