### ISSUE TITLE
How to handle multi column day ?

### ISSUE THREAD

**Issue by TeaBough** [intljusticemission/react-big-calendar#290]
I'd like to be able to distinguish 2 sub-columns in my week and day view, like this : 

![screenshot_20170207_165857](https://cloud.githubusercontent.com/assets/2129896/22699153/f496b8ee-ed56-11e6-8519-5e7ad118ef8c.png)

I've managed to exactly do that some times ago by forking the project. But I've diverged too much from the upstream. I've noticed that you've introducted new ways to personalized the calendar (customs components ...), that I could maybe use to realize that same thing.
Is there a way to have multicolumn days without changing too much internals of react-big-calendar ?

**Comment by jquense** [comment]
So essentially i think the "feature" here is groupable `TimeGrid`s. I _think_ the only thing you'd need to change is `TimeGrid`, you can reuse all the subcomponents (Gutter, DayColumn, etc). There is still a bunch of logic in `TimeGrid` tho so it's not super simple. I'd be happy to take a PR that adds Grouping to `TimeGrid`

**Comment by jquense** [comment]
Gonna close since there I don't think there is anything actionable here. Feel free to PR anything back if you implement it :)
