### ISSUE TITLE
react-big-calendar navigate to specific day / month

### ISSUE THREAD

**Issue by DeanKamali** [intljusticemission/react-big-calendar#291]
I'm trying to find an example on how to navigate to specific day / month when defaultDate state value changes.

My use case, I have a date picker, and I would like the calendar to render specific date / month when  date value changes changes. 

I have created new tag on Stackoverflow called `react-big-calendar ` and also a question [here](http://stackoverflow.com/questions/42119581/react-big-calendar-navigate-to-specific-day-month)
Thanks

**Comment by jquense** [comment]
answered on the SO question

**Comment by DeanKamali** [comment]
Thanks very much!
