### ISSUE TITLE
Date Picker when clicking month at top

### ISSUE THREAD

**Issue by th3fallen** [intljusticemission/react-big-calendar#292]
Not sure if this is possible but doing some research for an upcoming project. but would it be possible to do a date picker when clicking this.. http://th3fallen.d.pr/ok9j.jpg

mockup example http://th3fallen.d.pr/nz55.jpg

**Comment by jquense** [comment]
We don't do that out of the box. but the entire toolbar is customizable, so it'd be pretty easy to do that in your app if you want. In the past i've done something similar and it pairs nicely with http://jquense.github.io/react-widgets/docs/#/calendar?_k=68s62a

**Comment by th3fallen** [comment]
@jquense thanks that's exactly what i wanted to hear! thanks

**Comment by th3fallen** [comment]
So, one more question, i've gotten a datepicker in the toolbar just fine but im not seeing a method passed to toolbar or a way to add new props to it to change the calendars date? am i just missing something in the docs?
