### ISSUE TITLE
"+ X more" doesn't appear 

### ISSUE THREAD

**Issue by AlvaroIHS** [intljusticemission/react-big-calendar#294]
Hi, I have a problem when I try to show several events on the same day. The message "+ X more" doesn't appear. In the next image must be appearing this message on 13th February because I'm using the list of events from the file events.js

![sketch](https://cloud.githubusercontent.com/assets/10597575/22825045/c517aeb0-ef82-11e6-96ed-3a826d1f4b70.png)

My code to initialize the component it's this:

`<BigCalendar
                    popup
                    events={events}
                    defaultDate={new Date(2015, 3, 1)}/>`

**Comment by AlvaroIHS** [comment]
I have installed the latest version 0.12.3

**Comment by tobiasandersen** [comment]
Hi. Something seems off with how the dates are handled. It's a bit hard to suggest anything without seeing any code though, especially since it's working on the example site with the same events. Are you using the lib as is or are you running your own fork? If you can link to a repo/fiddle where this is reproducible I don't mind taking a look.

**Comment by AlvaroIHS** [comment]
Hi @tobiasandersen thanks for your answer. This is my test file with react-big-calendar component.

[calendar.txt](https://github.com/intljusticemission/react-big-calendar/files/770865/calendar.txt)

**Comment by AlvaroIHS** [comment]
@tobiasandersen I miss a file called "dayViewLayout.js" in "src/utils" when you download the project from releases (https://github.com/intljusticemission/react-big-calendar/releases/tag/v0.12.3). Could be this a reason of the problem that I have?. I think that it is possible because if you download or clone repo into your desktop, you can find this file in "src/utils" and works fine but if you download from releases does not appear.

**Comment by tobiasandersen** [comment]
While that file is definitely not the issue/fix (it's only used in the day view), there could be something else on master fixing your problem (in which case I think @jquense knows more about it). It seems a bit weird though, since that version is running on the examples site, which works perfectly fine.

**Comment by jquense** [comment]
yeah, i'm not sure honestly. Can you try installing it from npm instead of github and seeing if it works?

**Comment by AlvaroIHS** [comment]
I installed from npm into my project and it doesn't work. After that, I tried to download from Github, install it and run examples locally but it works fine. :(

**Comment by AlvaroIHS** [comment]
@jquense  If this can help you. The problem is only in month view. The rest of views work fine, I can see all events in the same day.

**Comment by jquense** [comment]
I'm sorry I cant reproduce your issue. can you put together a simple project that has the problem, so I can debug it. 

otherwise I'd pop open the devtools and see what's going on in the DateContentRow component where this logic lives

**Comment by AlvaroIHS** [comment]
@jquense I found the problem. Is an incompatibility between React and Preact. I use preact and preact-compat. I updated to the latest version of preact-compat and now I can see the message "+ X more" on the same day, but the overlay effect when clicked it does not work. If you want try with preactjs and test it. Thanks a lot.

**Comment by jquense** [comment]
glad you have it figured out. I don't use Preact so I'm not gonna have time to try it out (we don't really support anything but react). But if it's not working with the compat version I'd suggest opening an issue there since it's a problem with their compat shim
