### ISSUE TITLE
Formatting the calendar header

### ISSUE THREAD

**Issue by ofekinger** [intljusticemission/react-big-calendar#296]
Hello.
I'd like to edit the month header label, so that the month is in bold, and the year displays as usual.

What's the best way to do so?

Thanks in advance!

**Comment by tobiasandersen** [comment]
One way would be to provide your own Toolbar component, which would give you total control. From what I can see there's no easier way.

**Comment by jquense** [comment]
I guess technically you could provide a custom header format that returns jsx instead of a string, but that's not _strictly_ speaking supported. Otherwise a custom toolbar is the way to go

**Comment by ofekinger** [comment]
[monthHeaderFormat.txt](https://github.com/intljusticemission/react-big-calendar/files/772319/monthHeaderFormat.txt)
When using this function in the formats prop I get this error:
<code>Uncaught Error: `localizer format(..)` must return a string, null, or undefined</code>
And also:
<code>Uncaught (in promise) TypeError: Cannot read property '_currentElement' of null</code>

Am I missing something or is it not possible?

**Comment by jquense** [comment]
oops yeah, sorry it's not possible to do that. Was thinking of my other project :P

**Comment by VrajSolanki** [comment]
Any new updates on this one??
