### ISSUE TITLE
How to setup default time in Big Calendar

### ISSUE THREAD

**Issue by Sandeep3005** [intljusticemission/react-big-calendar#297]
Want initial time to 9 AM when the page first renders, but later if user scroll to say 4 PM and when user changes the date, prevent scrolling again to 9 AM.

code for big calendar reside inside render function

is there any way to set up default time like default date

**Comment by jquense** [comment]
try `scrollToTime`: http://intljusticemission.github.io/react-big-calendar/examples/index.html#prop-scrollToTime

I think that's the only thing that might com close. thanks!

**Comment by Sandeep3005** [comment]
@jquense Hi,
I have implemented using scrollToTime, but as I change date, it scroll back up to 9AM

**Comment by Sandeep3005** [comment]
Code is 

`
      let initTime = calendarDate.clone().set({hour: 9, minute: 0, second: 0});
      <BigCalendar
          events={this.getBookings()}
          defaultDate={calendarDate.toDate()}
          date={calendarDate.toDate()}
          onNavigate={() => {}}
          view={this.props.calendarType || CalendarTypes.DAY}
          onView={()=> {}}
          toolbar={false}
          selectable={true}
          popup={true}
          scrollToTime={initTime}
          formats={{dateFormat: 'D', weekdayFormat: 'dddd'}}
        />`

**Comment by jquense** [comment]
yeah it looks like it applies the `scrollToTime` when you navigate as well...that seems wrong, maybe a bug

**Comment by Sandeep3005** [comment]
@jquense 
I don't think it's a bug, coz I am not using toolbar provided by component and hence onNavigate method is not firing, I am passing date from outer component and which re-renders Big Calendar on date change

is there way to prevent this behaviour

**Comment by jquense** [comment]
no, the scrollToTime code specifically runs again when the view navigates back and forward. Your custom toolbar doesn't affect that here, the same behavior you are seeing is present with the included toolbar
