### ISSUE TITLE
possible to add class for "now" day?

### ISSUE THREAD

**Issue by th3fallen** [intljusticemission/react-big-calendar#298]
When the `now` prop is passed i notice there is no class added to the ui is there a way to do that?

after looking at the source im not seeing any use of it but i hope im just missing something?

**Comment by jquense** [comment]
Hi there, the class is `rbc-now` you can see how we style the current date on the example site

**Comment by th3fallen** [comment]
Will `now` not work in conjunction with the `date` prop? because the class you reference is set to the today cell but will not change regardless what i set the `now` prop to?

**Comment by jquense** [comment]
not sure what you mean there. The `now` prop represents the current date/time, its different from the `date` prop which is the current "selected" date, it determines which month, week, day, etc is currently visible

**Comment by th3fallen** [comment]
so i have now set to the 17th, yet the class persists on the current date as you can see in this picture http://th3fallen.d.pr/1Du5.jpg i've set the background color of rbc-now to red to illustrate more.

**Comment by th3fallen** [comment]
worth noting that both date and now are set to the same date but still shouldnt cause issues

**Comment by jquense** [comment]
ah yes there is even a FIXME: https://github.com/intljusticemission/react-big-calendar/blob/fa73913d8f1198359aa06256f4e5dd88557d8ef1/src/DateContentRow.js#L107

**Comment by th3fallen** [comment]
for once im not crazy :) thanks for the help btw, awesome lib!

**Comment by th3fallen** [comment]
Actually im wrong there is a class added, it's called rbc-current which is slightly misleading but i was looking in the day cell itself not at its header

**Comment by BOTOOM** [comment]
Try using

```typescript
<Calendar
getNow={() => {
	return new Date('2021-12-24T11:30:20') // custom date
	} }
/>
```
