### ISSUE TITLE
Question: Disable week and agenda views?

### ISSUE THREAD

**Issue by jforaker** [intljusticemission/react-big-calendar#30]
First off thanks for the great lib.

Second, is there any way to disable certain views? 
For example, I only want the month view. I know I can hide the day/week/month selector with css, but if you click on the date in the month view, it opens the agenda view automatically. Any way to disable that functionality? Or have _only_ the month view?

**Comment by jquense** [comment]
glad you like it :) You disable builtin views by setting the `views` prop to `['month', 'day']` 

http://intljusticemission.github.io/react-big-calendar/examples/index.html#prop-views

**Comment by jforaker** [comment]
Amazing thanks :+1:!

**Comment by uday-pop** [comment]
:+1:

**Comment by enacirruh** [comment]
Indeed, a great library!

But the way you turn off the views is not working a 100% as you would expect it.

When I add the following to the props to turn off all views but the month view, the day number remains a link and it navigates out from the page. 

`views:{
            month: true,
            week: false,
            day: false,
            agenda: false,
          }`

Is this the right behaviour? I would think if there is no other view than the current one it should not be a link any more. 

Thanks

**Comment by jquense** [comment]
You can directly control that via drilldownView but we also accept auto turning it off when there is no other view as you suggest

**Comment by enacirruh** [comment]
Great! Thank you very much for your instant help! This level of support is highly appreciated.
I must have skipped this part of the docs, my bad. Thanks again!
