### ISSUE TITLE
Changing background color of events per basis

### ISSUE THREAD

**Issue by fxfactorial** [intljusticemission/react-big-calendar#300]
Great component. 

I'm using it again on http://hye.life and I want to add a legend to color code events by type. Now I see that the color is controlled by `rbc-event`'s background-color. However I don't really see the right way color events differently since the components hook provided only gives me a chance to give a child and children components can't CSS affect their parents.

**Comment by jquense** [comment]
check out the eventPropGetter prop (and past issues on this). thanks!

**Comment by fxfactorial** [comment]
Ah, my bad, sorry about noise then.
