### ISSUE TITLE
Replace text toolbar

### ISSUE THREAD

**Issue by fxfactorial** [intljusticemission/react-big-calendar#302]
I'm looking for the least painful way of changing the default of 'next' and 'back' with '>' and '<' respectively. 

I have though many some CSS hackery or doing the custom toolbar but former is hacky and latter is too much code. 

Any easy way?

**Comment by jquense** [comment]
change the relevant messages prop?

**Comment by fxfactorial** [comment]
@jquense ah, perfect, great as well. 

Thanks! This calendar is providing a lot of usage to the Armenian people writ large. Much appreciated.

**Comment by shanejdonnelly** [comment]
While @jquense answer points in the right direction, the messages prop isn't detailed in the docs. Here is the relevant code area for anyone else looking for an answer to this issue:

https://github.com/jquense/react-big-calendar/blob/master/src/utils/messages.js
