### ISSUE TITLE
Adjusting time indicator position horizontally?

### ISSUE THREAD

**Issue by dmitriyK1** [intljusticemission/react-big-calendar#304]
Hi!
Is it possible to change horizontal position of current time indicator?
![image](https://cloud.githubusercontent.com/assets/3366893/23167160/f5045818-f84b-11e6-8375-f458e5f602dc.png)
Thanks in advance.

**Comment by jquense** [comment]
there is not!

**Comment by rebirthtobi** [comment]
@dmitriyK1 i achieve this by making the `.rbc indicator` width: unset, margin: 0 -10000% , i don't know if this is right css but it gives me the correct result
