### ISSUE TITLE
100% customizable event

### ISSUE THREAD

**Issue by tiaaaa123** [intljusticemission/react-big-calendar#305]
Great calendar! 

However, i would like to be able to make my own styled events in this style :
<img width="173" alt="wireframe_mee_6c_-_copie_pdf__1_page_" src="https://cloud.githubusercontent.com/assets/9055082/23175962/252a54e2-f82f-11e6-8a4d-435635a97fa4.png">

All 3 element (pink, teal, grey) are event which will be render the proper way depending of their type (not the concern here). The problem is that it seems you can only style the interior of the event like this example
<img width="224" alt="horaire___mee_" src="https://cloud.githubusercontent.com/assets/9055082/23176075/9359279a-f82f-11e6-8e41-508def62f222.png">

Is that the expected behavior of the component? Or is there a way to override the weekly component style to make our own from scratch?

**Comment by jquense** [comment]
use the `eventPropGetter` prop to add any style or className you want to the event element

**Comment by tiaaaa123** [comment]
How is it suppose to work? I'm giving the props to my component in the components object passed to BigCalendar and it doesn't car about that props

```
const components = {
    week: {
      event: eventProps =>
        <CalendarWeeklyEvent
          eventPropGetter={e => ({ style: { zIndex: 20, height: 4000, backgroundColor: 'red' }, className: 'hello' })}
          end={eventProps.event.end}
          event={eventProps.event.event}
          start={eventProps.event.start}
        />
    }
  };

  return (
    <BigCalendar
      components={components}
      date={date.toDate()}
      events={calendarEvents}
      .....
    />
  );
```

**Comment by jquense** [comment]
it goes on the calendar component not sub components

**Comment by mtt87** [comment]
How is it possible to increase the event `height`?
I wanna do this for the entire calendar, not just an event.

I tried with `eventPropGetter` but `height` attribute doesn't work as it seems to be rendered automatically.
`eventPropGetter={e => ({ style: { height: '100px', backgroundColor: 'red' }, className: 'hello' })}`
