### ISSUE TITLE
Event width is not 100%

### ISSUE THREAD

**Issue by tuanngominh** [intljusticemission/react-big-calendar#306]
in my big calendar setup, the event's width is not 100%, only 85%. Please check attached image
![2017-02-22 13_32_45-react storybook](https://cloud.githubusercontent.com/assets/2210733/23199864/a250b09a-f903-11e6-9e36-b1745d28155a.png)

A live preview is [here](https://tuanngominh.github.io/ureka-job-portal/?selectedKind=Calendar&selectedStory=Big%20Calendar&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel)

**Comment by jquense** [comment]
yes this is intentional it leave s space for the user to select time slots without selecting the event
