### ISSUE TITLE
css file error

### ISSUE THREAD

**Issue by Georgette** [intljusticemission/react-big-calendar#31]
I'm trying to load the react-big-calendar.css file via cssify/lessify/ tried another library, and they are all throwing a parse error when trying to load this file. 

 However, since I use less anyway, I required the less file, and all is well in the world. However, other non-less users might have issue with it :) 

By the way, love this project --- HUUUUGE lifesaver.

**Comment by jquense** [comment]
Any chance you could toss the parse error my way? I can double check it (we may also just use the less) but I'm not sure why the less would compile but the css file wouldn't work...

**Comment by Georgette** [comment]
[CalError.txt](https://github.com/intljusticemission/react-big-calendar/files/104353/CalError.txt)

It is really strange! I can copy the file to my assets dir and insert the stylesheet into the header of my html without having styling issues (I know browsers are rather complacent about css errors)...but I really don't want to manage post_install script. Yet trying to import them css via any one of these gives the exact error:

browserify-css
cssify
lessify

but less file compile fine :)

**Comment by antoinerousseau** [comment]
how do you compile your React project? with Webpack? If so, make sure the file is not loaded by a Webpack loader (more than `css!style`)

**Comment by gp3gp3gp3** [comment]
I'm having the same issue.  I'm using browserify with gulp and it's throwing the same error.

**Comment by abury** [comment]
Has anyone else encountered this? I'm getting the same issue and I have no idea what the cause is. I'm using webpack + babel and it's not being loaded by a loader (from what I can see)

```
in ./~/react-big-calendar/lib/css/react-big-calendar.css
Module parse failed: /Users/aron/Documents/Apps/React/trainer_webapp_whitelabel/node_modules/react-big-calendar/lib/css/react-big-calendar.css Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:0)
```

I'm wondering if it's related to this at all? https://github.com/webpack/webpack/issues/1754 I can't really dicipher much of what's going on as I'm quite new to the javascript scene. It's a shame as I was really excited to find this library, but I can't for the life of me get it to work. :(

**Comment by zivelai** [comment]
I resolved with
`import '!style-loader!css-loader!react-big-calendar/lib/css/react-big-calendar.css';`

credit to https://github.com/intljusticemission/react-big-calendar/issues/234#issuecomment-323241822
