### ISSUE TITLE
How to add new event by dragging the slots?

### ISSUE THREAD

**Issue by stivencyj92** [intljusticemission/react-big-calendar#312]
How to add new event by dragging the slots?
I don't see any API for creating the new event.

**Comment by tobiasandersen** [comment]
Have you looked at http://intljusticemission.github.io/react-big-calendar/examples/index.html#prop-selectable?

**Comment by jquense** [comment]
Like the example linked, you respond to the events and add a new event to the `events` prop on the calendar. How you do that is all up to you
