### ISSUE TITLE
Month and Agenda Views Empty

### ISSUE THREAD

**Issue by tamitutor** [intljusticemission/react-big-calendar#314]
Greetings,

I'm not sure what is going on but both the month and agenda views are empty.  (See attached screen shots to see month not showing compared to week and day showing--as stated agenda is the same as month.)

I've looked and compared the examples page CSS with my page's CSS...and their is no "gotcha" or "a-hah" that I've been able to find.

Any idea why it isn't working?

Thanks,

Tami

<img width="1293" alt="month-screenshot" src="https://cloud.githubusercontent.com/assets/54854/23572040/58413d56-0021-11e7-913b-9e3578433035.png">
<img width="1300" alt="week-screenshot" src="https://cloud.githubusercontent.com/assets/54854/23572047/5e8890b0-0021-11e7-9b44-0933d5c8a138.png">
<img width="1301" alt="day-screenshot" src="https://cloud.githubusercontent.com/assets/54854/23572058/70e7e454-0021-11e7-8560-7765f98fca24.png">

**Comment by jquense** [comment]
you need to set an explicit height on the calendar

**Comment by RKushnir** [comment]
From the example http://intljusticemission.github.io/react-big-calendar/examples/index.html, it seems the appropriate way is to set `min-height`, not `height`, otherwise the calendar may overflow in the week and day view.

**Comment by tamitutor** [comment]
Thanks guys!  Appreciate the help.

**Comment by christopher-caldwell** [comment]
Is this in the docs anywhere? Not the example, but the docs?
