### ISSUE TITLE
All day events wrapping only at end of week

### ISSUE THREAD

**Issue by akofke** [intljusticemission/react-big-calendar#315]
I am getting two all-day events created identically from the Google calendar api, but the one which is on Saturday wraps over to Sunday on the month view:

![calendar display bug](https://cloud.githubusercontent.com/assets/6622795/23584321/19272ad4-012c-11e7-8e9d-276ddb0f0eb5.png)

Their start and end dates follow the same pattern, as taken directly from the event prop:

test1
<img width="268" alt="screen shot 2017-03-04 at 10 35 39 pm" src="https://cloud.githubusercontent.com/assets/6622795/23584331/94dab7d6-012c-11e7-9dfe-8fdfd41848be.png">

vs test2
<img width="262" alt="screen shot 2017-03-04 at 10 36 18 pm" src="https://cloud.githubusercontent.com/assets/6622795/23584336/acf43176-012c-11e7-9634-ba338749d2af.png">

I realize the 12th happens to be daylight savings time but I've tried putting it on Saturdays both before and after DST and it still occurs so I don't think it's related to that.

I'm not sure if this is a bug or some configuration that I'm missing but I can't think of what the difference between them could be.

**Comment by jquense** [comment]
what are the dates. ranges are inclusive so if it spans from midnight to midnight the next day it is counted as two days

**Comment by akofke** [comment]
For test 1:
start is `Fri Mar 10 2017 00:00:00 GMT-0500 (EST)`  
end is `Sat Mar 11 2017 00:00:00 GMT-0500 (EST)`

And for test 2:
start is `Sat Mar 11 2017 00:00:00 GMT-0500 (EST)`  
end is `Sun Mar 12 2017 00:00:00 GMT-0500 (EST)`

They *both* start on midnight the first day and end on midnight the second day, yet test 1 spans one day while test 2 spans two days as shown in the screenshot above. So my question is why is there an inconsistency between the appearance? Which is the correct behavior?

**Comment by dpkg** [comment]
https://github.com/intljusticemission/react-big-calendar/issues/357 is a duplicate of this one. But that's the one that has the recent conversations, so maybe we can close this as duplicate?

**Comment by akofke** [comment]
Closing as duplicate, see #357 for further discussion.
