### ISSUE TITLE
changing timeGutterFormat -> props validation errors for TimeColumn and TimeSlotGroup

### ISSUE THREAD

**Issue by mtt87** [intljusticemission/react-big-calendar#316]
My calendar seems to work correctly but I get 2 warnings in the console.

This is my component:
```js
        <BigCalendar
          events={this.state.events}
          defaultView='week'
          views={['week', 'day']}
          step={30}
          timeslots={1}
          min={moment().minute(0).hour(7).toDate()}
          components={components}
          scrollToTime={new Date()}
          formats={{
            timeGutterFormat: (date, culture, localizer) => 
              localizer.format(date, 'H:mm', culture),
          }}
        />
```

2 errors:  

Warning: Failed prop type: Invalid prop `timeGutterFormat` of type `function` supplied to `TimeColumn`, expected `string`.  

Warning: Failed prop type: Invalid prop `timeGutterFormat` of type `function` supplied to `TimeSlotGroup`, expected `string`.

**Comment by jquense** [comment]
definately supported, just a bad propType declaration. PR? :)

**Comment by rrcobb** [comment]
Saw this same error, opened #530
