### ISSUE TITLE
Drag And Drop outside the calendar

### ISSUE THREAD

**Issue by martinnov92** [intljusticemission/react-big-calendar#318]
Hello, 

is it possible to drag and drop something to calendar from the outside (let say that I create a draggable div and want that div to be able to DnD to calendar)? Or is it only working inside the calendar?

Thank you very much.

**Comment by spacedust** [comment]
How did you solve this?

**Comment by martinnov92** [comment]
@spacedust Hello,

I created a drop target component, where I passing a function as a prop and call it on a React DND prop() method. Hope it makes sense, here is an example:

```
drop(props, monitor) {
    // call the function from parent element and pass there 'event' from the React Big Calendar
    return props.onDropTarget(monitor.getItem());
 },
```

I am not so sure if calling a function from `drop()` is the proper way how to do it.

**Comment by jupiterkenji** [comment]
@martinnov92 how do you pass the location of the event to the droppable? could you elaborate on "where I strip the date off the event and in the drop zone component I filter the events without dates". Thank you

**Comment by martinnov92** [comment]
Hello, I can't remember now, might have a look on it on Monday. By strip the date off I mean that I removed date from event to not to display it in the calendar. And no, the big calendar is already drop target I think. If I don't forget I will add example on Monday.

**Comment by martinnov92** [comment]
Oh and you have to set the correct name for drop target (the name you set when you are adding connectDropTarget(name,...)). I think the name should be "Event"...

**Comment by jupiterkenji** [comment]
Thank you @martinnov92 I'll check it out =)

**Comment by SagiSan** [comment]
Can anyone post a working example of outside drag n drop to calendar please?

**Comment by Tim1023** [comment]
@SagiSan  Here is an example on my repo [https://github.com/Tim1023/react-scheduler-firebase](https://github.com/Tim1023/react-scheduler-firebase). Hope it can help you

**Comment by MinhNguyen41092** [comment]
@Abenezer have you found any way to make it work? Also you @ the wrong person.

**Comment by mikailbayram** [comment]
@Abenezer have you found a way to make it work ono v 20. and up?

**Comment by milkysingh** [comment]
@Abenezer Is there any way I can make it work with v20 and up? It will be a great help.

**Comment by tommyspot** [comment]
@Tim1023 Do you have any update example with v20. The above example doesn't work with v20 and up.
