### ISSUE TITLE
Event Hover informations

### ISSUE THREAD

**Issue by tiaaaa123** [intljusticemission/react-big-calendar#320]
Hi,

Is there a way to change the informations (or the format) showing when you put the mouse over an event. Right now, it shows: `12:34 - 56:57: title`, but I would like to display different informations... Or juste change the format. Is it possible^

**Comment by jquense** [comment]
There isn't any way to customize it a the moment, but i'd be open to a PR allowing it.

**Comment by dsinghvi** [comment]
@jquense is there any update on this? Would be interested in this as well

**Comment by experionarjun** [comment]
I want to show some content on the mouse over event. Is there any update on this?
