### ISSUE TITLE
Week view: Events with start/end in different days not working

### ISSUE THREAD

**Issue by mtt87** [intljusticemission/react-big-calendar#321]
Example `event`:
```
{
  start: Sat Mar 18 2017 23:00:00 GMT+0100 (CET),
  end: Sun Mar 19 2017 02:00:00 GMT+0100 (CET)
}
```
Only the start portion is rendered but not the end in the next day, is this a known bug or limitation?  

<img width="701" alt="screen shot 2017-03-17 at 01 36 56" src="https://cloud.githubusercontent.com/assets/2150927/24024273/70793478-0ab2-11e7-8736-a37e1f6e488c.png">
<img width="828" alt="screen shot 2017-03-17 at 01 37 11" src="https://cloud.githubusercontent.com/assets/2150927/24024277/760afe80-0ab2-11e7-84bf-c6f9bdb86bcf.png">

**Comment by jquense** [comment]
looks like a bug.

**Comment by mtt87** [comment]
I'm happy to help if I can! 😄 
Any hint on the part of the code where this is being rendered / where should I look at?

**Comment by mtt87** [comment]
Any hint? If you point me in the right direction I won't have to read the entire codebase 👍

**Comment by jquense** [comment]
not sure honestly. maybe look in time grid where the dates are partitoned?

**Comment by mtt87** [comment]
I went back to this issue and tried with the latest version `0.14.4`

Now it seems like if an event starts one day and finishes on the next day, it's not even shown.

Is it possible nobody using this calendar has ever had an event lasting for more than one day?

**Comment by jquense** [comment]
not shown where?

**Comment by mtt87** [comment]
Sorry I probably didn't explain it correctly.
I see on the examples that there is an event spanning between multiple days but it's considered an **all day** event and it appears in the all day header when you are using the week view.

This means that in the week view it's not possible to determinate when that event it's exactly starting/ending.

To help you understand, take the drag&drop example from the website and take this event in the week view, then move it towards the end of the day, if the end it's still in that day you'll see this:
<img width="469" alt="screen shot 2017-08-28 at 19 15 06" src="https://user-images.githubusercontent.com/2150927/29787082-731bc214-8c25-11e7-9525-b48cc1e4bf54.png">

Then drag it +1h later, this will make it end in the next day and suddenly you can't see the event anymore in the grid but you can only see it in the "all day events" header.
<img width="435" alt="screen shot 2017-08-28 at 19 15 19" src="https://user-images.githubusercontent.com/2150927/29787118-96568bec-8c25-11e7-983a-fcc7062fba3c.png">
<img width="523" alt="screen shot 2017-08-28 at 19 15 27" src="https://user-images.githubusercontent.com/2150927/29787121-99ec3054-8c25-11e7-8b50-a58c77634612.png">

I'd like to see the event spanning between 2 days in the time grid, am I the only one ever requesting this?

I think from a UX point of view, it's not ideal to move it to "all day events" header because you are going to lose an important information about when the event it's starting/ending.

In this scenario 
A] event with start 9:00, end 15:00 of the day after
B] event with start at 23:00 end 15:00 of the day after
they will look exactly the same "all day events" in the header.

**Comment by jquense** [comment]
Yes the behavior you are seeing is intended, you aren't the only one who would like it to be different: https://github.com/intljusticemission/react-big-calendar/pull/496 feel free to jump in there 👍
