### ISSUE TITLE
How To Get A Click Event To Show A Bootstrap Popover

### ISSUE THREAD

**Issue by tamitutor** [intljusticemission/react-big-calendar#322]
Hi there,

I'm attempting to use react-bootstrap's Popover within a custom Event component.  It's not showing up.  Is there something I'm missing in getting custom popups working with an event click?

Thanks,

Tami

**Comment by jquense** [comment]
there shouldn't be anything special, but make sure your popover and overlay are positioned to the right elements. The default popup for truncated events uses the same underlying overlay as react-bootstrap so it should work

**Comment by naveenreddyin** [comment]
Any proper code solution to this please? I am struggling to implement this feature too.

**Comment by Amir-61** [comment]
Can I see an example of how it is integrated with Bootstrap Popover? I appreciate it
