### ISSUE TITLE
onSelectSlot firing when clicking on the calendar

### ISSUE THREAD

**Issue by frankjwu** [intljusticemission/react-big-calendar#323]
In the [selectable example](http://intljusticemission.github.io/react-big-calendar/examples/index.html), clicking on the calendar triggers the onSelectSlot callback. Is there a supported way to *only* do so when selecting spots via click-and-drag?

**Comment by frankjwu** [comment]
I just saw #225 -- I am considering creating a fork for our specific use-case, do you think this is a setting that would be useful upstream?

**Comment by jquense** [comment]
the problem is you really can't distinguish between a "click" and a drag with the implementation since everything is in terms of mouse down/move. there is already a 5px tolerance for clicks but if you want to expose it up so that it's configurable I'd probably merge it if it's not too messy

**Comment by frankjwu** [comment]
Let's say tolerance is configurable: the way to disable the 'click' event from being emitted would then involve setting tolerance to a really large number (ie. Infinity) such that the `isClick` function would always return `false`?

An alternate approach could be to prevent the emission of the 'click' event from ever happening in the mouseUp. Thoughts?

**Comment by jquense** [comment]
ahh yeah you just want to disable clicks? That would make it harder to select a single slot. We have the same behavior as google calendar so I know it's not necessarily odd behavior :P what is the reason why you'd want to disable clicks?

**Comment by frankjwu** [comment]
My calendar is similar to Google Calendar's: clicking on an existing event opens a little tooltip with event details. Clicking outside of the tooltip closes it.

Right now, clicking outside of the tooltip to close it also triggers the `onSelectSlot` callback. Google Calendar has the same behavior, but I don't really like that it happens that way 😛

**Comment by frankjwu** [comment]
Proposed solution -- update the object passed to the `onSelectSlot` callback:
```javascript
function(
  slotInfo: object {
    start: Date,
    end: Date,
    slots: array<Date>,
    action: String,
  }
)
```

where `action` is one of `click` or `select`. The user can then handle the two cases as desired. In my case, my `onSelectSlot` function would ignore all cases where `action === 'click'`.

Thoughts? Will put together the PR if you agree!

**Comment by jquense** [comment]
perfect, nice and simple and really minimal change. I'd be happy to merge that
