### ISSUE TITLE
Week Grid render

### ISSUE THREAD

**Issue by spacedust** [intljusticemission/react-big-calendar#325]
Hi,
The week view sometime renders incorrectly you can also see this on the basic example on your website. Select the week view and go to Oct 25 - 31. Here you can see that Sunday is not in line with the other days...
![screen shot 2017-03-22 at 15 44 42](https://cloud.githubusercontent.com/assets/139375/24203826/106eeff0-0f17-11e7-9490-68bc1c05ce9a.png)

**Comment by tophsic** [comment]
I do not observe this.

Ubuntu 16.04
Chrome 56

**Comment by spacedust** [comment]
I see this in safari 10.0.3, chrome  56 on macos 10.12.3

**Comment by adamlachmann** [comment]
It's most likely something timezone related - results of basic debugging of `TimeColumn.js`:

![selection_224](https://cloud.githubusercontent.com/assets/6628220/24326083/e1764c74-11a6-11e7-8e0f-8e159452c336.png)

Days are either one hour longer or one hour shorter.

**Comment by WhoseSomebody** [comment]
Hello, guys, @adamlachmann  @spacedust, now I faced the issue.

It starts behave like that from USA, but is fine in Ukraine..

Have you found the reason and the way to prevent this double render?
