### ISSUE TITLE
Week view: unnecessary left margin of events

### ISSUE THREAD

**Issue by jtomaszewski** [intljusticemission/react-big-calendar#326]
If we have multiple events on the same day, week view can show them incorrectly, by increasing their `left` offset to the moment when the events are no longer visible, for example:

![image](https://cloud.githubusercontent.com/assets/1862580/24204093/bc46ff48-0f17-11e7-813e-ee715b9984c2.png)

Is it planned behaviour or is it just me?

Propably to fix it we would set the margin left back to 0 after x events, or some other solution.

**Comment by jquense** [comment]
@tobiasandersen addressed this recently but i just realized i never released it 😱  

new version "0.13.0" is out now, give that a try
