### ISSUE TITLE
Question on Altering Layout

### ISSUE THREAD

**Issue by Georgette** [intljusticemission/react-big-calendar#33]
Hi, Again --- Love, love, love this project. Amazing work!

I want to change the layout of the today/back/next toolbar so that back and next are arrows before and after the date. Then Today becomes its own button. The goal is to free up some real estate for custom addition of filters. 

Part of me wants to leave the calendar as is and just add filters at top, but the OCD part wants it all to align together in a nice flow. 

Anyway, if I wanted to redo the layout of the toolbar, what would you suggest I do? Should I fork your code and alter it, or is there an open avenue for me to hide the tool bar, and just create a custom toolbar that calls the same events your toolbar does? Is that feasible?

**Comment by jquense** [comment]
Hi, thanks for the kinds words :)

Probably the correct API is to allow the Toolbar to be properly pluggable, but right now the best ou can set `toolbar={false}` on the calendar to not render the built-in one. Then you can hook up your own toolbar fairly easily. 

you will need to hook into `onNavigate` and `onView` and have your buttons set the `view` and `date` props on the calendar. There is also `BigCalendar.label()` for generating the same date label on the built in toolbar.

**Comment by Georgette** [comment]
Thanks, I'll give it a whirl! :)

**Comment by VrajSolanki** [comment]
Hi @Georgette were you able to achieve a specific toolbar, and is there a better way now to do it, like hide the previous and next buttons and style today button?

**Comment by Georgette** [comment]
Yes, I ended up with the approach of hiding theirs and using their set of functions to hook into my own. That project I was working on that I used this module in has been completed and handed off about a year ago so -- I haven't visited this module since, I'm afraid.
