### ISSUE TITLE
Day/Week view bug on 3/12/2017 & 3/11/2018

### ISSUE THREAD

**Issue by soulostar** [intljusticemission/react-big-calendar#330]
Hey, been using this component for a while and it's pretty awesome. I just wanted to bring up a really obscure bug I found - on Sunday 3/12/2017 and Sunday 3/11/2018 (maybe more days too, but I only checked about a year's worth of days), the day/week view is missing the last hour block (`TimeSlotGroup` component, I think) in the calendar, 11:00PM - 12:00AM. In addition, if the calendar is selectable and you click 2:00 AM on one of those days, the event will pass the clicked time as 3:00 AM. The same goes for all times between 2:00AM and 2:59AM inclusive; it'll add on an extra hour to what you actually clicked. You can see the missing hour block & the selectable click issue on the demo site itself - for example in the "Selectable" example in the week view - by looking at one of the days I mentioned.

**Comment by spacedust** [comment]
I also mentioned this #325
