### ISSUE TITLE
Disable 'all day events' header panel.

### ISSUE THREAD

**Issue by mattrick** [intljusticemission/react-big-calendar#331]
Hello, i've added option (mainly for myself) to hide all day events + quick fix in measuring gutter, when there's no such panel (it get's rid of non-numeric values in gutters array and then selects max ).

**Comment by IanLondon** [comment]
@mattrick  how do I do this?

**Comment by Noitidart** [comment]
Can you please share @mattrick I also want to hide all day as do people here - https://github.com/jquense/react-big-calendar/issues/481
