### ISSUE TITLE
multiple columns per day view

### ISSUE THREAD

**Issue by tylerzika** [intljusticemission/react-big-calendar#333]
Is there a way to produce multiple columns on the day view? I'd like to compare events associated with multiple users, side by side.

I checked the docs and didn't see how this could be implemented.

**Comment by jquense** [comment]
see #13, #290 nothing exists right now but it'd not be to hard to implement the idea in #290 if you want to give it a shot

**Comment by tylerzika** [comment]
Thanks for the reference! Shoot I have no idea where the start. Can you point me in the right direction?

**Comment by jquense** [comment]
Check out TimeGrid, it renders an arbitrary range of days (Week and Day are implemented in terms of it). What (probably) needs to happen is that that component should support "grouping" e.g. by resource or by year, etc.

**Comment by sabarasaba** [comment]
I guess this is good timing, I have to implement the same feature for the project my company is working on. If you already start it I can certainly give you a hand to get this out, if not I guess I'll go solo 💃

**Comment by tylerzika** [comment]
@sabarasaba I believe the multiple column day view is beyond my current skill set.

**Comment by rchanou** [comment]
I'm also working on this functionality in my own fork for a project that needs it. (Would've tried @sabarasaba's but it doesn't look like he has a public fork.) You can check out the key changes I made in TimeGrid.js [here](https://github.com/rchanou/react-big-calendar/blob/master/src/TimeGrid.js#L180).

**Comment by tylerzika** [comment]
@rchanou care to share a screen shot on how it looks? Also, how many columns can the day view support? What determines which column an event displays in?

**Comment by rchanou** [comment]
I only added very basic grouping so far, I still have to add in headers:

![capture](https://cloud.githubusercontent.com/assets/4177601/24786676/31a4b7b0-1b18-11e7-827f-ef4400a159cb.JPG)


I added the prop `groups`, and each event can have a `group`. No column limit.
<details>
<summary>Expand to see the props for the screenshot calendar.</summary>

```javascript
<Calendar
  defaultView={Calendar.Views.DAY}
  defaultDate={new Date()}
  groups={["Group A", "Group B"]}
  events={[
    {
      title: "Event 1",
      start: new Date(y, m, d, 9, 30, 0, 0),
      end: new Date(y, m, d, 15, 30, 0, 0),
      group: "Group A"
    },
    {
      title: "Event 2",
      start: new Date(y, m, d, 11, 0, 0, 0),
      end: new Date(y, m, d, 13, 0, 0, 0),
      group: "Group A"
    },
    {
      title: "Event 3",
      start: new Date(y, m, d, 9, 30, 0, 0),
      end: new Date(y, m, d, 11, 30, 0, 0),
      group: "Group A"
    },
    {
      title: "Event 4",
      start: new Date(y, m, d, 9, 30, 0, 0),
      end: new Date(y, m, d, 10, 30, 0, 0),
      group: "Group A"
    },
    {
      title: "Event 5",
      start: new Date(y, m, d, 10, 0, 0, 0),
      end: new Date(y, m, d, 11, 0, 0, 0),
      group: "Group A"
    },
    {
      title: "Event 6",
      start: new Date(y, m, d, 10, 0, 0, 0),
      end: new Date(y, m, d, 11, 0, 0, 0),
      group: "Group B"
    },
    {
      title: "Event 7",
      start: new Date(y, m, d, 9, 30, 0, 0),
      end: new Date(y, m, d, 10, 30, 0, 0),
      group: "Group B"
    },
    {
      title: "Event 8",
      start: new Date(y, m, d, 9, 30, 0, 0),
      end: new Date(y, m, d, 10, 30, 0, 0),
      group: "Group C"
    },
    {
      title: "Event 9",
      start: new Date(y, m, d, 9, 30, 0, 0),
      end: new Date(y, m, d, 10, 30, 0, 0),
      group: "Group C"
    },
    {
      title: "Event 10",
      start: new Date(y, m, d, 10, 30, 0, 0),
      end: new Date(y, m, d, 12, 30, 0, 0),
      group: "Group B"
    },
    {
      title: "Event 11",
      start: new Date(y, m, d, 12, 0, 0, 0),
      end: new Date(y, m, d, 13, 0, 0, 0),
      group: "Group B"
    },
    {
      title: "Event 12",
      start: new Date(y, m, d, 12, 0, 0, 0),
      end: new Date(y, m, d, 13, 0, 0, 0),
      group: "Group B"
    },
    {
      title: "Event 13",
      start: new Date(y, m, d, 12, 0, 0, 0),
      end: new Date(y, m, d, 13, 0, 0, 0),
      group: "Group B"
    },
    {
      title: "Event 14",
      start: new Date(y, m, d, 12, 0, 0, 0),
      end: new Date(y, m, d, 13, 0, 0, 0),
      group: "Group C"
    },
    {
      title: "Event 15",
      start: new Date(y, m, d, 6, 30, 0, 0),
      end: new Date(y, m, d, 8, 0, 0, 0),
      group: "Group C"
    }
  ]}
/>
```

</details><br/>

Works for my purposes, not sure if I'll have time to make it merge-worthy. It looks like @sabarasaba [might make a PR soon](https://github.com/intljusticemission/react-big-calendar/issues/13#issuecomment-162223521), and @jquense isn't too keen on the [approach I took ](https://github.com/intljusticemission/react-big-calendar/issues/13#issuecomment-162223521) 😅

**Comment by sabarasaba** [comment]
@rchanou Yes, I'm getting close! 

<details>
  <summary>Example props</summary>
  <p>

```javascript
const events = [{
  'title': 'Muffin fiesta',
  'resourceId': 'a',
  'start': new Date(2015, 3, 1, 5, 30, 0, 0),
  'end': new Date(2015, 3, 1, 10, 30, 0, 0)
}, {
  'title': 'Cake fiesta',
  'resourceId': 'b',
  'start': new Date(2015, 3, 1, 2, 30, 0, 0),
  'end': new Date(2015, 3, 1, 4, 30, 0, 0)
}]

const resources = [{
  id: 'a',
  title: 'Room A'
}, {
  id: 'b',
  title: 'Room B'
}, {
  id: 'c',
  title: 'Room C'
}]

return (
  <Calendar
    events={events}
    resources={resources}
    defaultDate={new Date(2015, 3, 1)}
  />
)
```
  </p>
</details>

<br/>

PS: I can share my branch if it would be helpful for anyone, but its not merge-ready and still stuff I need to clean up/refactor :)

**Comment by tylerzika** [comment]
@sabarasaba this looks great!

@rchanou a worthy try!! Way more than what I could have done with my limited react knowledge.

**Comment by bkniffler** [comment]
It looks great @sabarasaba, slightly offtopic: I also like the status lines on your events. Any chance you could do a PR on these? If not, maybe I'd give it a try sometime.

**Comment by sabarasaba** [comment]
@bkniffler yeah thats exactly how I've done it, just appends a custom class and then using a `:before` selector you can easily achieve that :)

**Comment by connorbode** [comment]
@jquense why was this closed?  was it merged?

**Comment by jquense** [comment]
The issue was stale. Please feel free to pick up on the work in one of the open PRs
