### ISSUE TITLE
Use datefns instead

### ISSUE THREAD

**Issue by fxfactorial** [intljusticemission/react-big-calendar#336]
Is it possible to have RBC use datefns instead of moment or globalizer?

**Comment by jquense** [comment]
localizers are pluggable so you could write one that uses dateFns theoretically. practically though that would probably be a bad choice. dateFns is a date manipulation utility library not an internationalization one. the use of moment or globalize is to handle i18n concerns not simply to format or parse dates. 

that said, if you only want to support one lang/culture it'll probably work, check out how the localizers are written to write your own.

**Comment by fxfactorial** [comment]
@jquense yea, I just need my own home country and I don't need the bloat of moment or global.

I will take a look.

**Comment by jquense** [comment]
oops small correction, it does look like dateFns has some support for i18n, I probably still wouldn't use it for serious things (I wouldn't use moment either for that tho).

**Comment by fxfactorial** [comment]
@jquense but surely you'd agree its massive bloat? I couldn't figure out of to get rid of the other locales with webpack =/

**Comment by jquense** [comment]
I mean that's more of a moment issue with webpack. there are plenty of resources online on fixing that btw, I think even on the webpack docs site. 

like I said I use globalize.js or native  Intl generally for this. for utilities (add, substract, startOf, etc) internally it uses date-arithmetic which is like 170 LOC. 

please do feel free to use dateFns if you want, those bits are very intentionally changeable exactly to support your use case :) writing a localizer isnt to bad

**Comment by fxfactorial** [comment]
Thanks again!
