### ISSUE TITLE
Is React big calendar free to use ?

### ISSUE THREAD

**Issue by hansenk051** [intljusticemission/react-big-calendar#343]
Iam working as a .NET Developer in IT-company.

Iam looking for a React js calendar

Is this React-big-calendar, totaly FREE-to-use .. also commercially. ?

Is it possible to change calendar weekday and month names in my language.
Is it possible to change width and heigjht of it ?

I have read Lisence terme. But i dident understand them..

plz help

**Comment by jquense** [comment]
it's MIT licensed, which means you can do anything you want with it, you just can't sue me or the contributors for anything that happens as a result of using it. It is "presented as is, and without warranty" 

You can change the language of messages (by providing your own) and can adjust the size with css. Read the documentation for more detaila
