### ISSUE TITLE
Custom  (year) view

### ISSUE THREAD

**Issue by MaxBuodnik** [intljusticemission/react-big-calendar#344]
Hello,
I need to realize 'year view' on the 'React-big-calendar', where will be able to see all 12 month of year with events. Please, help me to find the way for solve this task.

**Comment by tobiasandersen** [comment]
This is not implemented, but there's been some previous discussions on it, see https://github.com/intljusticemission/react-big-calendar/issues/270.

**Comment by dmitriyK1** [comment]
Is it possible to create a custom view (like day/week/month/agenda) ?

**Comment by jquense** [comment]
yes, look at how those views are implemented. You can provide any component to the `views` prop but there is an expected interface that those components should follow. namely a few static methods. You can see how Day and Week are both implemented on top of TimeGrid
