### ISSUE TITLE
Displaying not correct dates.

### ISSUE THREAD

**Issue by khayalan-mathew** [intljusticemission/react-big-calendar#346]
Hey :)

In my case, i live in germany (locale = 'de-DE'), i set up everything and is working, except for the displaying of the dates.

The first date is correct, but the second one is always not in the 24h-format ^^ For example it displays  4:00  insted of 16:00, which is really confusing...

I hope somebody can help me :)

![error-react-calendar](https://cloud.githubusercontent.com/assets/23657891/24663568/905922b2-1958-11e7-8d9d-803200ed6d3e.PNG)

**Comment by jquense** [comment]
What localizer are you using? Moment?

**Comment by khayalan-mathew** [comment]
yes, moment

**Comment by khayalan-mathew** [comment]
Fixed it thanks :)
