### ISSUE TITLE
The problem about allday and agenda.

### ISSUE THREAD

**Issue by CoderChow1994** [intljusticemission/react-big-calendar#349]
1. I want to hidden  allday .
2. I want to change the agenda header.
3. What should I do?

![1491446948 1](https://cloud.githubusercontent.com/assets/23169397/24735775/27409e44-1ab7-11e7-9b65-573fbeeab0e7.png)

**Comment by jquense** [comment]
you can change the headers by adjusting the relevant format props, however the you cant hide all day events other than by not passing them to the calendar
