### ISSUE TITLE
Week view height issues on Chrome and Firefox

### ISSUE THREAD

**Issue by GabiAxel** [intljusticemission/react-big-calendar#35]
Greetings. I am trying to use BigCalendar with no toolbar and with absolute positioning to fill part of a flexbox layout page. Month view looks good on all browsers I tested, but week view produces the following issues:

* On Firefox there is no scrollbar. I also noticed that in the live example on Firefox week mode has no scrollbar and the calendar overlaps the docs part after it.

* On Chrome resizing the window messes the calendar - reducing the window height also reduces the height of the "all day" row, and increasing the window height does not affect the calendar, leaving blank part below it.

On Safari and Opera I encountered no issue with week view.

**Comment by GabiAxel** [comment]
Thanks. That solved the Firefox problem. Should I open a separate issue for the Chrome window resizing problem?

**Comment by jquense** [comment]
sorry missed that second one, the joys of using newer web tech...every browser disagrees

**Comment by GabiAxel** [comment]
I got a direction. Adding the following seem to fix it:
`
.rbc-time-header {
  height: 60px;
}
.rbc-time-content {
  flex: 1;
}
`

**Comment by jquense** [comment]
Thanks for the hint, that was very helpful :)

**Comment by GabiAxel** [comment]
Great, that did it, thanks.
