### ISSUE TITLE
Two HTML5 Drag and drop backends

### ISSUE THREAD

**Issue by martinnov92** [intljusticemission/react-big-calendar#350]
Hello,
does anybody have idea how to use react-big-calendar with drag and drop and my own component with drag and drop? Now when I use both of these components on the same page I get the error about two HTML5 backends, the only (wrong) solution I came with was to delete HTML5 backend from RBC drag and drop index.js...

Does anyone have some ideas? Or would be possible to publish this package with optional use of drag and drop backend? I would like to use touch backend anyway...

Thank you very much

**Comment by martinnov92** [comment]
Here you can have a look at my little project (still work in progress so it is messy) https://github.com/martinnov92/TSCalendar

**Comment by jquense** [comment]
take a look at the addon code you can provide your own backend optionally

**Comment by martinnov92** [comment]
Hello @jquense , thanks for your answer, I know about that option, but I don't want to provide anything, as I will provide backend from higher component...

**Comment by martinnov92** [comment]
when I delete this `DragDropContext(backend)` from dragAndDrop/index.js, it works perfectly and that's how I need it :D

**Comment by jquense** [comment]
I'm not an expert but why don't you share the backend with both your component and the drag and drop?

**Comment by martinnov92** [comment]
@jquense I am not expert either :D, so I am not sure what do you think to share backend. When I keep them both I get the error about 2 backends on same page, when I remove it from mine - mine is not working, when I remove it from RBC - it works. You can have a look here and see how it looks/work https://martinnov92.github.io/TSCalendar/. RBC is almost on the bottom of my component tree and I would like to share the backend from the component on very top (<App>), but I need to remove it from RBC first :/. Hope it makes sense, sorry about my english.

**Comment by martinnov92** [comment]
Hello again, I created a pull request https://github.com/intljusticemission/react-big-calendar/pull/352 with working solution. I hope this will get merge as I think it would make this component more reusable in case you want to use React DND in other components in your app...
Thank you
