### ISSUE TITLE
How do I set date format??

### ISSUE THREAD

**Issue by Yoonseonwoong** [intljusticemission/react-big-calendar#353]
```
  componentWillMount(){
    moment.locale('ko');
    BigCalendar.momentLocalizer(moment);
  }

 let formats = {
      dayFormat: (date, culture, localizer) =>
        localizer.format(date, 'ddd MM/dd', culture),
    }

<DragAndDropCalendar selectable
                             events={calendarData}
                             onEventDrop={::this.moveEvent}
                             messages={messages}
                             formats={formats}
                             onSelectSlot={::this.onSelectSlot}
                             onSelectEvent={::this.onSelectEvent} />
```

The following error occurs : 
debuggability.js:874 Unhandled rejection TypeError: Cannot read property 'filter' of undefined

**Comment by CoderChow1994** [comment]
This is my code ,they are only for your reference.
```
  let formats = {
    timeGutterFormat: 'HH:mm',
    eventTimeRangeFormat: ({
        start,
        end
      }, culture, local) =>
      local.format(start, 'HH:mm', culture) + '-' +
      local.format(end, 'HH:mm', culture),
    dayFormat: 'MM-DD' + ' ' + '星期' + 'dd',
    agendaTimeRangeFormat: ({
        start,
        end
      }, culture, local) =>
      local.format(start, 'HH:mm', culture) + '-' +
      local.format(end, 'HH:mm', culture),
    agendaDateFormat: 'MM-DD' + ' ' + '星期' + 'dd',

  }
```

**Comment by zeeforce** [comment]
> This is my code ,they are only for your reference.
> 
> ```
>   let formats = {
>     timeGutterFormat: 'HH:mm',
>     eventTimeRangeFormat: ({
>         start,
>         end
>       }, culture, local) =>
>       local.format(start, 'HH:mm', culture) + '-' +
>       local.format(end, 'HH:mm', culture),
>     dayFormat: 'MM-DD' + ' ' + '星期' + 'dd',
>     agendaTimeRangeFormat: ({
>         start,
>         end
>       }, culture, local) =>
>       local.format(start, 'HH:mm', culture) + '-' +
>       local.format(end, 'HH:mm', culture),
>     agendaDateFormat: 'MM-DD' + ' ' + '星期' + 'dd',
> 
>   }
> ```

THAKNS

**Comment by KhizerRehan** [comment]
@CoderChow1994 Hi
The calendar UI is fully customize. How can we start calender start date from 8AM to 6PM? can we achive this format?
it will be great if you could help
https://gyazo.com/d98029bc6fc46ac2d38bd921e07b887a

**Comment by ryanbuckleyca** [comment]
does anyone have a typescript version of this?
