### ISSUE TITLE
Feature proposal: recurrent events

### ISSUE THREAD

**Issue by alexkuz** [intljusticemission/react-big-calendar#355]
It would be nice to have a way to provide recurrent events. Right now I just prefill calendar with events for a year ahead, but it feels it could be done by means of this component. Maybe a callback that returns `{ start, end }` for current date if it matches the condition, like this:

```js
{
  title: 'Every monday night since 2016-01-01',
  match: date => {
    if (date > new Date('2016-01-01')) {
      if (date.getDay() === 1) {
        let start = new Date(date);
        let end = new Date(date);

        start.setHours(22);
        end.setDate(end.getDate() + 1);
        end.setHours(6);

        return { start, end };
      }
    }
  }
}
```

Thanks for a great component, it fits nice in my app :)

**Comment by jquense** [comment]
Thanks for the issue, While a common need in calendaring I don't want to provide such functionality in the library, which is more focused on rendering provided data. This feature is completely possible (and easier) to implement on top of the Calendar component, and can be tailored to suit your event data format's specific needs.

I'll consider a callback approach in the future if it's reasonably efficient to implement though thanks!

**Comment by alexkuz** [comment]
Thank you! I'm not sure it's really easier to implement externally though - at least I haven't found an appropriate solution. I guess I'd have to listen to `onNavigate` and `onView` and change events list accordingly. It needs some implementation, while internally we already know the displayed range and don't have to calculate it... But if that's out of scope, that's fine :)

**Comment by araneta** [comment]
so its not possible to provide recurrent events with the current version of react big calendar ?

**Comment by tobiasandersen** [comment]
It's not provided out of the box, But you can build it yourself on top of the Calendar.

**Comment by araneta** [comment]
@tobiasandersen Would you give some example how to do this? i can't find the example of this Calendar component. Thanks

**Comment by alexkuz** [comment]
@araneta you'll have to trace current calendar state (date and mode - month, week or day) with `onNavigate` event, calculate all the recurring events that will fit in current range and provide them to calendar just like the regular events.

**Comment by jfrux** [comment]
I've found in previous builds that Recurring Events are best handled by a RRULE generator / parser and you need to interpret / write the rules back and forth from the backend API and provide the calendar views the data in a way it understands.

**Comment by xtabbas** [comment]
With RRULE it only gives the recurring instances, for handling exceptions you'll have to write the logic to override such instances from RRULE.

**Comment by cutterbl** [comment]
As a total side note, I have recurrence events in the application I support. But we do not have the UI handle calculating the recurrences (that's a lot of client side overhead). We define recurrences using [Quartz Cron syntax](https://productresources.collibra.com/docs/collibra/latest/Content/Cron/co_quartz-cron-syntax.htm), and our server calculates recurrences based on the range sent to the server for each view. Our Api team uses some .NET nuget package with all of it. I don't personally know all the internals. I do know that, when having a user define recurrence, we require them to define an end date.
