### ISSUE TITLE
Use 'create-react-class' package instead of React.createClass

### ISSUE THREAD

**Issue by MichaelDeBoey** [intljusticemission/react-big-calendar#356]
`React.createClass` has been deprecated and extracted to it's own package since [React v15.5.0](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#new-deprecation-warnings).

The following warning is displayed if that version of React is used:
`Warning: Calendar: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.`

See [Migrating from `React.createClass`](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.createclass) to fix this.

This could be a temporary fix, but I think moving to ES6 classes is more appropriate :-)

**Comment by jquense** [comment]
PR's welcome!

**Comment by MichaelDeBoey** [comment]
Will try to look at it this evening :-)
