### ISSUE TITLE
How to run and change Calendar

### ISSUE THREAD

**Issue by JustaManpk** [intljusticemission/react-big-calendar#358]
I have downloaded and unzipped this React calendar project.

But how can I run the project. Should the project be located in localhost?

I have saved the project on my desktop. I have maked some changes in kode, but when I refresh examples / index.html, it shows not changes.

Its like all is cahed or ?

**Comment by jquense** [comment]
the instructions for running the examples locally are here: https://github.com/intljusticemission/react-big-calendar#run-examples-locally
