### ISSUE TITLE
Pass class to events

### ISSUE THREAD

**Issue by melchoir55** [intljusticemission/react-big-calendar#359]
I don't see a way to pass classes to event objects. The idea here is to be able to style the event objects using css. 

Am I just missing it, or is applying custom styling to different events not supported?

**Comment by jquense** [comment]
The prop is called `eventPropGetter` in the documentation

**Comment by melchoir55** [comment]
Thanks, I'll take a look. Maybe I'll make a pull request with an example of its usage once I figure it out.
