### ISSUE TITLE
Rendering bug in week and month views

### ISSUE THREAD

**Issue by okcompute** [intljusticemission/react-big-calendar#36]
Hi,

The row segment are rendered too short when I create an event spanning over an entire month:

![2016-02-04 14_28_29-renderingbug](https://cloud.githubusercontent.com/assets/1320283/12827068/f8fadf56-cb4b-11e5-8e05-19a21b45e6bd.png)

This behavior is also reproduced in the *week* view.

I have tried to look up the code for the possible error but I could not find it. 

I produced this bug with version 0.9.8

I use `react` 0.14.7

My browser is chrome version 48.0.2564.97

If you don't have time to look it up, I take any pointer to help out :)

Thank you for this superb react component!

**Comment by adamcharnock** [comment]
I'm also encountering this too (seen in versions 0.9.7 & 0.9.8). Any suggestions very welcome :-)

**Comment by adamcharnock** [comment]
Changing [this line](https://github.com/intljusticemission/react-big-calendar/blob/master/src/utils/eventLevels.js#L5) to the following seems to (kind of) solve the problem:

```python
let slots = dates.diff(first, last, 'day') + 1; // The '+ 1' is new
```

This is pretty hacky and I'm quite sure it isn't the correct solution. I suspect it is more to do with how the last day of the week is being specified, or something in that vague region.

**Comment by antoinerousseau** [comment]
I guess this issue should be closed?

**Comment by antoinerousseau** [comment]
I'm having the same issue when the specified `culture`'s week ends on a Sunday rather than a Saturday.

E.g. with `culture="fr"`:

<img width="532" alt="capture d ecran 2016-04-02 15 16 35" src="https://cloud.githubusercontent.com/assets/160279/14229054/0d27639c-f8e6-11e5-80d8-81e9eef9fa3c.png">

And with `culture="en"`:

<img width="532" alt="capture d ecran 2016-04-02 15 16 21" src="https://cloud.githubusercontent.com/assets/160279/14229056/12512e70-f8e6-11e5-90e2-e8d30dd7d6ff.png">

**Comment by antoinerousseau** [comment]
Actually the bug is visible on the demo pages!
http://intljusticemission.github.io/react-big-calendar/examples/index.html

**Comment by antoinerousseau** [comment]
Looks like this is trying to resolve a similar bug: https://github.com/SlavaKvak/react-big-calendar/commit/a359db3736b618ef4ed4e26ba4d59c50249b7d84

**Comment by okcompute** [comment]
Hi all, 

Thank you very much for taking the time to fix this issue. It is really appreciated. I confirm the bug is fixed in the *month* view. But, for me, it still present in the week view:

![week](https://cloud.githubusercontent.com/assets/1320283/15321456/83f840f4-1c04-11e6-8ff3-877a01fe4d83.png)
![week2](https://cloud.githubusercontent.com/assets/1320283/15321457/83f9cf6e-1c04-11e6-8f01-a9551537f19f.png)

**Comment by okcompute** [comment]
And now with the fix:

![week_fix](https://cloud.githubusercontent.com/assets/1320283/15324603/2510b7cc-1c15-11e6-9b72-94d7d7b19ca4.png)
![week2_fix](https://cloud.githubusercontent.com/assets/1320283/15324604/25151272-1c15-11e6-9236-f71be294485e.png)
