### ISSUE TITLE
Events show as "all day" when they end 00:00:00 the next day

### ISSUE THREAD

**Issue by gabek** [intljusticemission/react-big-calendar#363]
Wondering if anybody could shed any light on this.

I have events that run from 23:00 - 00:00 that only show up as "all day".  Is this expected?

Thanks!

```
{
title: "The Papa Biggs Show",
desc: "A family-orientated show with an interesting mix of music, mayhem & chat helped along by his family",
start: "Sun Apr 09 2017 23:00:00 GMT-0700 (PDT)",
end: "Mon Apr 10 2017 00:00:00 GMT-0700 (PDT)"
}
```
<img width="1475" alt="screen shot 2017-04-22 at 5 07 17 pm" src="https://cloud.githubusercontent.com/assets/414923/25309293/3aa06ca2-277e-11e7-9762-f0737a0b2977.png">

**Comment by IanLondon** [comment]
+1.

I see how 00:00:0000 means the next day, and crossing midnight is what makes an event "all day", but in my application, events are understood to be start-inclusive, end-exclusive. So I, too, want any events ending at 00:00:0000 the next day to not be "all day". How can I disable this behavior in the view? Is there any built-in way to do this, or will I need to fork and hack?

I found this: https://github.com/intljusticemission/react-big-calendar/issues/331 but I don't understand how to disable "all day".

**Comment by gabek** [comment]
I'm currently hiding the "all day" row via CSS as to not add confusion, but an obvious side effect is that those items are no longer visible on the calendar.

**Comment by jquense** [comment]
@IanLondon this isn't configurable, and hiding the ui isn't going to help, you will jsut be missing events on the calendar. I suggest using the `endAccessor` to return a end-inclusive date in the case where the events end on midnight. e.g 

```js
// subtract one millisecond from the end date putting midnight dates at 11:59:999
endAccessor={({ end }) => new Date(end.getTime() - 1)
```

**Comment by gabek** [comment]
That solution works for me!

**Comment by jedwards1211** [comment]
@jquense the docs state that:
> an event ending on Apr 8th 12:00:00 am will not appear on the 8th, whereas one ending on Apr 8th 12:01:00 am will.
This should be reopened and either the docs or behavior corrected to make them agree with each other:

**Comment by jedwards1211** [comment]
@jquense the only problem with the `endAccessor` workaround is then the event cell says `X PM - 11:59 PM` instead of `X PM - 12:00 AM`, which contradicts other areas in my app that correctly display the event end time as 12:00 AM.

**Comment by jedwards1211** [comment]
@jquense besides, I thought the "all day" gutter was only intended for events explicitly marked `allDay: true`, and `allDay: false` events that span multiple days would be shown in the main time area.

**Comment by decoursin** [comment]
This really seems like a misnomer to me. Something that starts at 23 hours, and goes until 2 hours of the following day would be marked as "all day" for both days, which is quite absurd don't you think?

I'm assuming the problems is that it's just a bit too technically difficult to split the event into two parts, one for the last hour of the first day and the other for the first two hours of the second day? Could you please confirm that this is the reason that it's not be changed or configurable?

**Comment by jquense** [comment]
@decoursin this *is* configurable. please read the docs before complaining on old closed issues thanks

**Comment by jquense** [comment]
looks like a bug! Care to send over a PR?

**Comment by decoursin** [comment]
Thanks man, but I don't think that will happen. Good luck on the project!

**Comment by issdilshod** [comment]
> 

this solved my issues, thank you so much

**Comment by NayyarNaqvi** [comment]
when i create an event on 11:45 pm to start  to 12:35am it is not displayed in 11:45 pm slot and also not shown in 12:35am slot how to display this event using react big calendar how to fix this issue

**Comment by cutterbl** [comment]
@NayyarNaqvi Are you using true [JS Dates](https://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/guides-understanding-dates--page)?
