### ISSUE TITLE
"onSelectSlot" does not work on iPad

### ISSUE THREAD

**Issue by twlai** [intljusticemission/react-big-calendar#364]
It works like a charm on my desktop browser. 
On desktop, when I click a time slot, the slot can be selected. 

However, on mobile Safari, time slot cannot be selected. 
What can I do to make it to work on iPad?

Any assistance would be appreciated.

**Comment by jquense** [comment]
The selection mostly uses mouse events so it probably doesn't work in a touch environment. It should be easy enough to fix but I haven't had any need so far. Gladly take a PR :)

**Comment by cmccann702** [comment]
Hi - did anyone get a fix for this?
