### ISSUE TITLE
titleAcessor new line for event contet

### ISSUE THREAD

**Issue by guilherme6191** [intljusticemission/react-big-calendar#366]
Hey guys, good job on React Big Calendar!

I'd like to know if there is a way to insert a newline in events content.

I tried with \n and <br> but it didn't work.

An example that I've tried:

`titleAccessor={this.handleEventContent}` in my `BigCalendar`

and 
```
handleEventContent(event) {
  if (this.state.viewType === 'day') {
    return event.title + '\n' + event.customer_address;
  } else {
    return event.title;
  }
}
```
No luck.

Thanks in advance.

**Comment by stefyrosca** [comment]
You can make a custom component for the calendar, then you can customize the style however you want.
Link to the official example:
https://github.com/intljusticemission/react-big-calendar/blob/master/examples/demos/rendering.js

**Comment by jquense** [comment]
title's can't be customized because they are just a browser `title` attribute, so the browser handles the rendering of the tooltip.

**Comment by guilherme6191** [comment]
Thanks, guys.
