### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by seiji619** [intljusticemission/react-big-calendar#367]
Right now, there is no documentation that describes the data structure of an Event object so I had to check `fullcalendar` library for that reference.

**Comment by jquense** [comment]
the data structure of the event object is completely up to you. there is no documentation to add about it. per the second paragraph http://intljusticemission.github.io/react-big-calendar/examples/index.html#api

**Comment by jedininjaster** [comment]
I'm with @seiji619, I would like better docs, for anybody finding this, to clarify, you need to implement the accessors for events. hopefully this code helps.
```
<BigCalendar
            events={[{
              'title': 'All Day Event',
              'allDay': true,
              'start': new Date(),
              'end': new Date()
            }]}
            startAccessor='startDate'
            endAccessor='endDate'
            allDayAccessor='allDay'
            titleAccessor='title'
          />
```
