### ISSUE TITLE
constants.directions

### ISSUE THREAD

**Issue by dantman** [intljusticemission/react-big-calendar#37]
I was looking into using react-big-calendar in a project (while simultaneously experimenting with rollup and seeing if react-bing-calendar could get a `jsnext:main` build to make it compatible).

During that I noticed that [src/utils/dates.js](https://github.com/intljusticemission/react-big-calendar/blob/a41c9f9/src/utils/dates.js) imports and tries to use `directions` from [src/utils/constants.js](https://github.com/intljusticemission/react-big-calendar/blob/a41c9f9/src/utils/constants.js); but `directions` doesn't even exist inside `constants.js`.

**Comment by jquense** [comment]
ya that's a copy/paste error, is it causing problems?

**Comment by dantman** [comment]
I don't know. It's being used by code which should theoretically be throwing errors if it gets reached. I haven't tested it outside of rollup yet so I don't know what UI action would trigger the error.

In rollup it causes an error because `dates.js` is trying to import something that doesn't exist. Presumably more standard ES6 modules implementations like Babel 6 or native modules may have similar errors.

**Comment by dantman** [comment]
Ok, I did a bit more digging. Inside `utils/dates.js` the only `directions` references are inside `dates.move` and doing a careful file search through `src/`, no code references/uses `dates.move`.

So the 'fix' for import cleanup would just be to remove the `dates.move` function.
