### ISSUE TITLE
Disable week-end in week view

### ISSUE THREAD

**Issue by LeaklessGfy** [intljusticemission/react-big-calendar#372]
Hello,

I was wondering if it's possible to disable week-end in week view (I mean, no column for saturday and sunday).

I've seen a ticket related to this point but the given answer doesn't actually provide a way to do. And referring to current documentation I can't see a simple way to do that ...
Mainly because week component are accessible with : "header" and "event" only. 

So, is it possible ?
Thank you :) #97

**Comment by bkniffler** [comment]
I think this can be closed due to https://github.com/intljusticemission/react-big-calendar/pull/383 been merged (work-week view introduced). Just waiting for publish.
