### ISSUE TITLE
Touch enabled?

### ISSUE THREAD

**Issue by MMRandy** [intljusticemission/react-big-calendar#38]
Nice component, any plans to make this touch enabled?  It really should have this functionality given the mobility requirements of most apps these days.  If I end up uses this, I'll make a PR if you don't have any plans to implement this yourself.

Thanks again for the work here :)

**Comment by jquense** [comment]
hey there, So I'd love touch support to be supported, but our internal use cases don't require it right now, so its less of a priority. If you did want to PR something though I'd be happy to work with you on it.    As it stands without much work, its already fairly responsive and usable on mobile. Baring the obvious fact selection doesn't work. I think most changes would be isolated to: https://github.com/intljusticemission/react-big-calendar/blob/master/src/Selection.js and may just be a matter of doubling up on touch and mouse events.

**Comment by MMRandy** [comment]
Ok, good to know @jquense.  We are building a large React mobile app (phone & tablet) and will need calendar / scheduling support and are currently reviewing the various options out there...like what you have here.  Going to be a busy next week for me (out of country) but I'd like to play around with this at some point next week and see if it can handle our use cases.  If so, I'd be happy to work with you on PRs or ideas on making this a little more mobile friendly.  Thanks for the quick response :)

**Comment by antoinerousseau** [comment]
@MMRandy any update on this?

**Comment by nwinch** [comment]
I knocked something together quickly to get touch events working.  Rough, it is.  Pretty, it is not.  But it achieved what I wanted at the time.  Perhaps this might help provide some direction for others?
https://github.com/nwinch/react-big-calendar/tree/touch

**Comment by simplenotezy** [comment]
anyone tried @nwinch?

**Comment by simplenotezy** [comment]
@nwinch did you submit a PR?

**Comment by nwinch** [comment]
@simplenotezy I didn't no.  It was super rough and really just got me limping over a deadline for a project, so I've left it there as more of a dusty road sign (good or bad) than anything else.

**Comment by lucidsif** [comment]
@MMRandy, I'm currently looking for date-time pickers like react-big-calendar that are touch-enabled. Did you ever find any other options?

**Comment by jsbranco** [comment]
@lucidsif  not sure if you are still looking for help on this, but for my use case I manage to grab user selection both desktop /mobile by simply providing a custom Component to the Calendar Component. 
`let customComponents= { dateCellWrapper:this.enrichWithSelectionCell};`

Where my function is actually: 
`   enrichWithSelection(props) {
        let selected = false;
        if (this.props.selection && this.props.selection.indexOf(props.value.getTime())>=0) {
            selected = true;
        }
        let className = selected ? `${props.children.props.className} selected` : props.children.props.className;
        return React.cloneElement(props.children, {...props.children.props, className});
    }`

It doesn't work for a range selection but in my case I am only looking for individual selection which works fine.

P.S: **this.props.selection** is a property that is essentially an array populated through the callback of "onSelectSlot"

**Comment by Adnan-961** [comment]
Any update on this ? works when i tap for a few milliseconds or when i hold and drag. but it doesnt register when i tap. i tried custom components with onTouchEnd / start but it doesnt work

**Comment by limzyishere** [comment]
@Adnan-961  I am stuck on this too.. Will let you know if I find a solution, If it helps, some folks were able to get it to work with https://codesandbox.io/s/clever-brattain-8wjh6?file=/src/CalendarMobile.js
