### ISSUE TITLE
Programmatic Event Selection

### ISSUE THREAD

**Issue by micahalcorn** [intljusticemission/react-big-calendar#385]
Hi, thanks for this great component.

Is there a way to programmatically select an event and/or set an event object as `selected` before the initial render? I tried using `eventPropGetter` but had no luck.

**Comment by jquense** [comment]
`defaultSelected={selectedEvent`...it does not appear to be documented oops

**Comment by micahalcorn** [comment]
Ah, now I see the previous issue #371. Sorry for the duplicate. I searched everything I could think of and somehow missed it. 🙈

So there is not a way to programmatically select an event after the component has rendered? Should I just make the `defaultSelected` equal to a `state` value and use it to cause a rerender? That doesn't seem to be working for me.

**Comment by jquense** [comment]
If you want to completly control the value use `selected` and the onSelectEvent callback much like a controlled input

**Comment by micahalcorn** [comment]
Well, that's just too easy. 😐
