### ISSUE TITLE
Open specific date

### ISSUE THREAD

**Issue by ErickVoodoo** [intljusticemission/react-big-calendar#386]
Hello, It's good library to manage your schedule events,
But I've got a question, can I open specific day with events by clicking some random button?

<img width="639" alt="screen shot 2017-05-10 at 2 55 58 pm" src="https://cloud.githubusercontent.com/assets/14906917/25897482/c198fc04-3590-11e7-894b-b488d7f5451e.png">

For example, clicking at 12th April(at the small calendar) I need to open 12th April in ReactBigCalendar.

Thanks

**Comment by martinnov92** [comment]
Hello @ErickVoodoo , I think I did this by saving the selected date to state and then pass it as a prop to big calendar and at the same time you need to change the view to "day" (view prop). Hope it helps

**Comment by ErickVoodoo** [comment]
@martinnov92 
It really helped me) Thank you!
As you said:

```
<BigCalendar 
  view={view}
  onView={view => {
    this.setState({
      view,
    });
  }}
  date={new Date(moment(day).format())}
  onNavigate={(day) => {
    this.setState({
      day,
    });
 }}
/>
```

`view` - is current calendar view mode(set via setState)
`onView` - event called when user clicks on any view(day, month etc.)
`date` - current selected day
`onNavigate` - event called when user clicks on back/next buttons

When I click on the small calendar I fire an event:
  ```
onSelectDate = (day: *): void => {
    this.setState({
      day,
      view: 'day', -> when user select a day in small calendar -> set view to 'day'
    });
  };
```
