### ISSUE TITLE
issue with week view

### ISSUE THREAD

**Issue by KhushbuThakkar** [intljusticemission/react-big-calendar#387]
I have used this plugin,it shows weird behavior when clicked on week view.Code for it is
`<div className="bigCalendar-calendarview">
            								  	{
              								      (!moment ? '' : <BigCalendar {...this.props}
              								      selectable
              								      events={(typeof (this.state.moment) !== 'undefined' && this.state.moment != null) ? events : []}
              								      defaultDate={new Date()}
              								      onSelectEvent={event => this.callCampaignDetails(event, me.state.clickListenerInfo)}
                                    components={{
                                      event: MyEvent
                                    }}
                                    views={['month', 'week']}
              								      />)
               								  }
            								  	</div>`

![image](https://cloud.githubusercontent.com/assets/20332259/25993187/dbbb59be-3726-11e7-9ee4-b6b07d5f9dc9.png)

Can anyone help?i don't know what is wrong.

**Comment by bkniffler** [comment]
I'm not able to reproduce. Also its not happening on http://intljusticemission.github.io/react-big-calendar/examples/index.html 

Whats your exact issue? The red boxes? The green line? Whats your stylesheets? What does the code of `MyEvent` look like? I'm pretty sure it doesn't come from big-calendar.

Btw, you should definitely format your code in a way that is readable more easily and provide more info if you're seeking help.

**Comment by jquense** [comment]
I'd imagine this is a style conflict issue or some other unrelated style thing, If you can provide a reproduction we can troubleshoot more

**Comment by KhushbuThakkar** [comment]
thanks @bkniffler and @jquense ,Followed the instruction and it helped.
I thought the problem is in component as it was only displayed in week view , so posted here. But the issue was in component which was rendered.
Closing question now.
