### ISSUE TITLE
Event width 100%

### ISSUE THREAD

**Issue by codenakama** [intljusticemission/react-big-calendar#388]
Hi,

I know there was an issue opened in regards to this before #306 , however there is no way to override this behaviour for example using `eventPropGetter`.

The only way I found - but I think eventPropGetter should handle this - is to set width to a value and append `!important` to it in the css file because the width is being defined inline on the event container.

Is there a solution to this?

Cheers.

**Comment by tobiasandersen** [comment]
This actually is the default behavior now, [see examples](http://intljusticemission.github.io/react-big-calendar/examples/index.html) for reference. Are you on the latest version?

**Comment by codenakama** [comment]
@tobiasandersen  I was on `0.12.3` - updated now and  can confirm. was on 0.12.3. Are there release notes? Thanks!

**Comment by vimiPonyai** [comment]
any solution for "react-big-calendar": "^0.19.2"? I am facing the same problem too.
