### ISSUE TITLE
Feature request?: Change day color by function

### ISSUE THREAD

**Issue by FRodrigues21** [intljusticemission/react-big-calendar#389]
Just like the current day has a different color is it possible to somehow change the days colors?

<img width="292" alt="9aa0af0949da064e584896c0b5e61481" src="https://cloud.githubusercontent.com/assets/11356933/25996264/6a2ff48e-370e-11e7-9cd6-17315e099080.png">

What I want, im selfish ik, is the possibility to change the day color using a function, for example:

`function shiftColor(day) {
return getDayShift(day) === A ? '#ffffff' : '#000000';
}`

**Comment by jquense** [comment]
Yes using the eventPropGetter prop, you can do this

**Comment by FRodrigues21** [comment]
Doesn't eventPropGetter only change the event cell background and not the day cell?

**Comment by jquense** [comment]
ah yes sorry misunderstood. There are a few issues about adding this, but no one has done it well. If you want to add a dayCellPropGetter, we'd be open to a PR

**Comment by alexpanov** [comment]
Why is this issue closed? If there is a feature request open, people are more likely to submit that PR.
