### ISSUE TITLE
write specific commands in README

### ISSUE THREAD

**Issue by 21ma** [intljusticemission/react-big-calendar#390]
It's better to write specific commands in README.

https://github.com/intljusticemission/react-big-calendar#run-examples-locally

## current
> * Clone this repository
> * Retrieve dependencies: `npm install`
> * Start: `npm run examples`
> * Open [localhost:3000/examples/index.html](http://localhost:3000/examples/index.html).

## what I want
> ```
> $ git clone git@github.com:intljusticemission/react-big-calendar.git
> $ cd react-big-calendar
> $ npm install
> $ npm run examples
> ```
> Open [localhost:3000/examples/index.html](http://localhost:3000/examples/index.html)

**Comment by jquense** [comment]
Thanks for the input!

**Comment by 21ma** [comment]
@jquense Thanks for your comment.
I created PR.
