### ISSUE TITLE
onSelectEvent issue

### ISSUE THREAD

**Issue by minisemi** [intljusticemission/react-big-calendar#397]
Love the calendar! I am having an issue with the onSelectEvent prop though. If just writing "onSelectEvent={(event) =>alert(event)}" it works (e.g. I get the event title etc) when clicking an event, but when passing it to a function like below it only prints an unknown event object "onselectevent event=[object Object]". What I want is to get the event information (title, date etc.) and the event's DOM element. Any thoughts?

 ```
imports...
BigCalendar.momentLocalizer(moment);

export default class BookingCalender extends Component {

constructor (props) {
        super(props);
        this.state = {
            events: []
        };
        this.handleSelectEvent= this.handleSelectEvent.bind(this)
 }

handleSelectEvent(event) {
      console.log("handleSelectEvent's event="+event)
  }

render() {
        return (
                <BigCalendar
                    selectable
                    events={this.state.events}
                    onSelectEvent={(event) =>this.handleSelectEvent(event)}
                    defaultView='week'
                    defaultDate={new Date(2017, 4, 15)}
                />
        );
    }

componentDidMount(){
        if (this.props.bookingId!==undefined) {
            getCalenderEvents(this.props.bookingId).then((events) => {
                for (var i =0; i<events.length;i++){
                    events[i].start=new Date(events[i].start);
                    events[i].end=new Date(events[i].end);
                }
                this.setState({events: events})
            })
        }
  }
}
````

**Comment by jquense** [comment]
The callback is called with your event object object so it has anything you have on your events.  It's printing something weird because you are coercing the object to a string in your console.log

**Comment by martinnov92** [comment]
Hello @minisemi , did you try this: `onSelectEvent={this.handleSelectEvent}`, I am using it that way and it works just fine...

**Comment by minisemi** [comment]
Well that's embarrassing, used the console wrong so it changed the object to a string like you said. Thanks!

**Comment by Reshma23596** [comment]
test
