### ISSUE TITLE
Events: Siblings, Overlapping (width and z-index)

### ISSUE THREAD

**Issue by AgamlaRage** [intljusticemission/react-big-calendar#404]
I'm reporting my comment on #379 as a unique issue so people can find it.
I have an other behavior that is unexpected with event overlaping.
Here the save events.

**GoogleCalendar/Fullcalendar**

![rbc-issue-fullcalendar-xs](https://cloud.githubusercontent.com/assets/15155827/26281715/2155a59e-3e00-11e7-9676-ce91ee453b69.png)

**React Big Calendar**

![rbc-issue-react-big-calendar-xs](https://cloud.githubusercontent.com/assets/15155827/26281708/d9a5226a-3dff-11e7-82bc-ba262a693925.png)

As I say in the image, ***Blue event should be bellow the red one, and stop at the same position that the yellow one***.

My questions were:

Is that plan to have the exact same behavior as GoogleCalendar/Fullcalendar ?
If yes, Is that related to this PR ?
If not, should I open a new issue ?

---

Here @bkniffler response into the #379 comments

> It seems like big calendar tries to follow google calendar in terms of look&feel, which is good since the google devs surely put lots of research into their calendar. I bet the maintainers here would be willing to accept a PR on this matter.
> 
> There is 2 things that could to be addressed somewhere around [here](https://github.com/bkniffler/react-big-calendar/blob/4ed1442f9ca69227d16e22c91c475c2076054cba/src/utils/dayViewLayout.js#L196) to imitate gcal:
> 
> - z-index of sibling events needs to be raised (through inline styles or via an additional class rdc-sibling-event) or rendering of these events needs to happen after non-sibling ones.
> - only the left offset should vary with siblingIdx rising, while still trying to fill the whole width. Currently the algorithm will make the yellow 70% width/0 offset. It could be better to follow google calendar and make the yellow 100% width/0 offset, the red 70% width/30% offset.
>
> Give it a shot, shouldn't be too hard!

**Comment by jquense** [comment]
Happy to take a PR for this :)

**Comment by emilnygaard** [comment]
Did anyone manage to find a solution for this?

**Comment by tobiasandersen** [comment]
I think the z-index problems should be solved by now..

**Comment by emilnygaard** [comment]
I have this issue, and I can't figure out if it's the same thing, hoping someone can help me:
![image](https://user-images.githubusercontent.com/1412383/39359342-f6b71a3a-4a19-11e8-98ee-21a78378a317.png)

**Comment by tobiasandersen** [comment]
Hm yeah that doesn't look right. I don't have time to look at it now, but will probably get to it eventually if no one else does it. If you'd like to give it a try, the file you should look at is: https://github.com/intljusticemission/react-big-calendar/blob/585cc392f1acdeff6cf8f1121155a059cba5fa19/src/utils/DayEventLayout.js.
