### ISSUE TITLE
Toolbar too wide

### ISSUE THREAD

**Issue by tuhlmann** [intljusticemission/react-big-calendar#405]
I'm integrating your excellent component into my app and ran into this issue:
While the calendar renders finde within the provided div the toolbar would always outgrow it:

![image](https://cloud.githubusercontent.com/assets/407319/26283669/ac2451bc-3e2c-11e7-90fa-eb565c97abbc.png)

The problem was the setting of `width: 100%` in `.rbc-toolbar-label`. When I removed that and replaced it with `flex-grow: 1` (takes all available space if the other items in the row do not grow as well) all works fine.

Thanks,
Torsten.

**Comment by jquense** [comment]
This works fine on the docs site, you may have css conflict or something else that's breaking your particular case.

**Comment by chrishud2011** [comment]
I get the same behavior, and I also see the behavior on the docs site, using google chrome.
