### ISSUE TITLE
Anchor hrefs hard coded to # 

### ISSUE THREAD

**Issue by tom-daly** [intljusticemission/react-big-calendar#407]
the following lines of code should you javascript:void(0); instead of pound. I'm using this in SharePoint Online 'Modern Pages' and the '#' is triggering navigation and it's breaking the calendar. I manually changed it to javascript:void(0); and it works.

EventEndingRow.js line 132
Month.js line 378
Timegrid.js line 332

**Comment by Paul-Colucci** [comment]
This should either be a button, or the href in the anchor should be "javascript:void(0);" having an anchor element with the href set to "#" can cause postbacks in certain environments.
