### ISSUE TITLE
dnd is broken if using eventPropGetter function

### ISSUE THREAD

**Issue by furiousOyster** [intljusticemission/react-big-calendar#408]
Take the dnd example, and modify to use an eventPropGetter returning a style object, attempt to use dnd functionality.
It seems to fail because some of the dnd props are being overridden or something ?
The event passed in to eventPropGetter has no extra information available to it, so unsure how to give the props it wants.

**Comment by furiousOyster** [comment]
works if selectable is disabled, but clicking on the event causes errors in the logs.

**Comment by jquense** [comment]
Thanks for the issue, sorry for the Delay. I don't really maintain the addons code, since they are extra functionalities provided but others and i include them here as a convenience. Please feel free to submit a PR fixing this if it's relevant to your needs thanks!
