### ISSUE TITLE
Any example for fetching events from remote api?

### ISSUE THREAD

**Issue by naveenreddyin** [intljusticemission/react-big-calendar#409]
I have a weird situation at hand while trying to make a demo appointment system. 
I want to fetch events through Django backend rest api, which works totally fine and I could see the data coming in console as well.

Here is my index file (where provider is):
https://hastebin.com/ubefumofor.js

My calendar rendering component:
https://hastebin.com/oronefibap.scala

My Redux, its reduxsauce library I am using:
https://hastebin.com/usetavasub.js

My ReduxSaga file:
https://hastebin.com/wutuvelefi.js

Now, the thing is, I am struggling to do a few things after I fetch the events:

- Where to setState, as it goes in infinite look if I call it in componentWillUpdate or componentDidUpdate?

- if I use this.props.events I get the following error which I have attached as a picture. It says `uncaught at fetchEventsByDoctor The sort method cannot be invoked on an Immutable data structure.`
[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/kX3tR.png

Now I know that props cant be modified and state could be.

What am I doing wrong, and how to rectify this please? Thanks
**Note: I am new to react and redux related technologies.**

**Comment by jquense** [comment]
Hi there, this is really more of a general react support question then an issue with anything in react-big-calendar, I'd suggest turning to the various support channels, like the reactiflux discord or stackoverflow.com
