### ISSUE TITLE
Translations on agenda view

### ISSUE THREAD

**Issue by pashtet86** [intljusticemission/react-big-calendar#412]
Hi, 
it seems that translations doesn't work on agenda view 
![screenshot 2017-05-23 15 34 30](https://cloud.githubusercontent.com/assets/11823971/26354807/ecf1697a-3fce-11e7-918d-f10237052144.png)

When I'm switching the language selector all text changing except "Date", "Time", "Event".

**Comment by jquense** [comment]
yup we don't provide translations for text, you'll need to provide them yourself via the `messages` prop, see https://github.com/intljusticemission/react-big-calendar/blob/master/src/utils/messages.js for all messages

**Comment by pashtet86** [comment]
Thank you!
