### ISSUE TITLE
Disable week-end in month view

### ISSUE THREAD

**Issue by AgamlaRage** [intljusticemission/react-big-calendar#415]
As I see in this issues #97, #372 the **work_week** view will be available in the next realease ?
I looked at the PR #383 , but I'm not sure this is about the **month** view too.

Is that ?

If not, will it be possible to do this with a **custom view component** ?
Like in this example [example/CustomView.js](https://github.com/intljusticemission/react-big-calendar/blob/master/examples/demos/customView.js).
I'm lookin at the core but for now, I don't see an easy way to acheive this.

**Comment by jquense** [comment]
You can make a custom view but it would involve a lot of rewriting. the Month view doesn't support removing the weekends.

**Comment by Guardpc** [comment]
Good afternoon!
Tell me, is there any news about this problem?

**Comment by cutterbl** [comment]
@Guardpc `work_week` is a valid `view`. You can see it in use on the [Docs](http://jquense.github.io/react-big-calendar/examples/index.html?path=/story/about-big-calendar--page) page

**Comment by Guardpc** [comment]
@cutterbl, thanks for your answer, but I'm interested about "Disable week-end in month view"

**Comment by cutterbl** [comment]
@Guardpc Missed that. Yes, that would probably require a [custom view](http://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/guides-creating-custom-views--page). Might check Stackoverflow, or ask in our Slack community. Someone may have done this before.

**Comment by Guardpc** [comment]
Hello everybody!
I have found a solution for this problem.
Maybe the solution is not quite correct, but it works (**if the week starts on Monday**).

I made a copy [Month.js](https://github.com/jquense/react-big-calendar/blob/master/src/Month.js) , defined it as a custom view (WorkMonth).
```javascript
views = {
	month: true,
	week: true,
	work_week: true,
	work_month: WorkMonth,
	day: true
};
``` 

And truncated arrays of days in the following methods:
```javascript
renderWeek = (week, week Ids) => {
	week = week.slice(0, 5);
	...
}

renderHeaders(row) {
	row = row.slice(0, 5);
	...
}
```

**Comment by InsaneRohit** [comment]
@jquense   -Tell me, is there any solution about this problem to disable weekend in month-view?

**Comment by Guardpc** [comment]
@InsaneRohit, Hi!
Ask your questions, I'll try to answer them.

**Comment by cutterbl** [comment]
@Guardpc @InsaneRohit I would suggest moving this conversation into the #custom-components channel of our Slack group

**Comment by InsaneRohit** [comment]
@Guardpc @jquense @cutterbl Can anyone help me in building Custom Month View to hide weekends ?
Is ther any solution for this?

**Comment by Guardpc** [comment]
@cutterbl, unfortunately, slack is not available in my country.

@InsaneRohit, Just copy the file [Month.js](https://github.com/jquense/react-big-calendar/blob/master/src/Month.js) in a convenient place.
Rename it and the class name as you like, for example, WorkMonth.js .
Correct 2 functions as [I showed above](https://github.com/jquense/react-big-calendar/issues/415#issuecomment-1683635018).

Then import it into your component with react-big-calendar and add it to the views object. 
I showed you what my object looks like. 
[Here's the documentation.](https://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/props--cal-views)

Good luck to you!

**Comment by InsaneRohit** [comment]
> @cutterbl, unfortunately, slack is not available in my country.
> 
> @InsaneRohit, Just copy the file [Month.js](https://github.com/jquense/react-big-calendar/blob/master/src/Month.js) in a convenient place. Rename it and the class name as you like, for example, WorkMonth.js . Correct 2 functions as [I showed above](https://github.com/jquense/react-big-calendar/issues/415#issuecomment-1683635018).
> 
> Then import it into your component with react-big-calendar and add it to the views object. I showed you what my object looks like. [Here's the documentation.](https://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/props--cal-views)
> 
> Good luck to you!

@Guardpc  Can you share the code please I really need it. I have tried not working giving so many errors. Is there any chance we can talk through email or any other social media . I really need to do it

**Comment by InsaneRohit** [comment]
@Guardpc  Need your code to understand or more help would be better in custom month view

**Comment by InsaneRohit** [comment]
@Guardpc where are you i am looking for you?
