### ISSUE TITLE
Can not read property 'matches' of null

### ISSUE THREAD

**Issue by sahilpandya** [intljusticemission/react-big-calendar#418]
Hello,

I am trying to use these module in my project, but it is throwing <code> Can not read property 'matches' of null </code> . If I keep my bundle file in body then it is working, but I don't want to keep in body, it is coming in my header, so Is there any other option/solution to solve these problem ?

**Comment by jquense** [comment]
Bundles in the head is an anti pattern, the dom helpers look for the body element which hasn't loaded yet, which is why it's breaking.
