### ISSUE TITLE
plan to make class names local-scoped, instead of global scoped?

### ISSUE THREAD

**Issue by chrisy-lili** [intljusticemission/react-big-calendar#420]
I wonder whether there's any plan to leverage libraries like css-modules to scope class names locally? It'll help to prevent styles clashing.

**Comment by jquense** [comment]
There is not, we prefix all classes to avoid this and it works well enough. It's not effect but the ease of use and familiarity of normal css for users is an advantage I'd like to maintain. Thanks!
