### ISSUE TITLE
Change language to french

### ISSUE THREAD

**Issue by mathieusanchez** [intljusticemission/react-big-calendar#428]
Hello,
I have put, thanks to moment to locale "fr", but for change week or for change the display mode, is still in englsih, do you know how can i change this.

Exemple: i want "week" in french "mois".

**Comment by martinnov92** [comment]
Hello, you have to create translation object and then pass it as a prop to calendar.

My translation object

```
const messages = {
  allDay: 'Celý den',
  previous: '<',
  next: '>',
  today: 'Dnes',
  month: 'Měsíc',
  week: 'Týden',
  day: 'Den',
  agenda: 'Agenda',
  date: 'Datum',
  time: 'Čas',
  event: 'Událost'
};
```

And then pass it `<ReactBigCalendar messages={messages} .../>`

**Comment by tophsic** [comment]
@mathieusanchez, as @martinnov92 said, you have to set `messages` prop. Here is my message configuration for french language:

```javascript
const messages = {
  allDay: 'journée',
  previous: 'précédent',
  next: 'suivant',
  today: 'aujourd\'hui',
  month: 'mois',
  week: 'semaine',
  day: 'jour',
  agenda: 'Agenda',
  date: 'date',
  time: 'heure',
  event: 'événement', // Or anything you want
  showMore: total => `+ ${total} événement(s) supplémentaire(s)`
}
```

**Comment by alansutherland** [comment]
How would you add localization/translation for all the months in a custom toolbar?

**Comment by babytiger0929** [comment]
Can I translate or customize month and day name?
Thank you
