### ISSUE TITLE
TimeIndicator "now" value is always `new Date()`

### ISSUE THREAD

**Issue by fruitraccoon** [intljusticemission/react-big-calendar#429]
Hi, I have what I think may be a bug regarding the "TimeIndicator" line when the `now` prop is provided to the Calendar - the line is always set at my current local time.  Looking at the code, when `positionTimeIndicator` runs it always uses `new Date()` rather than the `now` prop value.

```
positionTimeIndicator() {
    const { rtl, min, max } = this.props
    const now = new Date();
```

(see https://github.com/intljusticemission/react-big-calendar/blob/04f1fc736bff657aed00d57779c8eaac5487e5ba/src/TimeGrid.js#L395)

Is this the intended behaviour or hopefully an easy fix?

Thanks for a great component! :)

**Update:**
As I've dug into this more, I've found that a related issue also affects the placing of the `rbc-today` CSS class - which is determined in a few places using code like `className={cn('rbc-header', dates.isToday(date) && 'rbc-today')}`.  The `utils/dates.js` module has the following code to determine "today":

```
today() {
    return dates.startOf(new Date(), 'day')
},
```
(see https://github.com/intljusticemission/react-big-calendar/blob/04f1fc736bff657aed00d57779c8eaac5487e5ba/src/utils/dates.js#L149)

I think these calls would also require `now` to be passed in when determining what "today" is?

Let me know if you'd prefer a PR to just a report ;)

Thanks again.

**Comment by tobiasandersen** [comment]
What `now` prop are you referring to? As far as I know, neither the time indicator nor the `rbc-today` class are controllable by props, they will be always be the current time and "today".

**Comment by kiliancs** [comment]
There are a couple scenarios I can think of where being able to set `now` would be invaluable:

- *Showing events in a different time zone*. This is a scenario I'm actually facing now. Due to the lack of support for time zones, we are manipulating event dates, etc so that they show up in the right time slots. I'm referring to a booking system in which you make the booking in the target location's time zone (not the browser's). The current time indicator, however, always relies on `Date()`, like @fruitraccoon explained. I have to admit that the ideal solution, albeit probably a lot more involved, would be to introduce proper time zone support.
- *Simulated time*. What if I want to simulate time moving faster? What if I want to change the list of events as time moves backward and forward in order to visualize event creation for a given day? It just seems that being able to define what "now" is would actually allow for all this.

**Comment by fruitraccoon** [comment]
Thanks for the reply @tobiasandersen.  The `TimeGrid` and a number of other components have a [`now` prop](https://github.com/intljusticemission/react-big-calendar/blob/04f1fc736bff657aed00d57779c8eaac5487e5ba/src/TimeGrid.js#L36) and if I pass `now` to BigCalendar it does appear to be passed through.  But from your response it's clear that this is _not_ an "undocumented feature", and is not how it was intended to be used. :)

The scenario that I am using the calendar for is indeed the first one described by @kiliancs - I'm showing the event details for a location that is possibly in a different timezone.  From UTC dates in our db, we pre-convert them to the location's local time on the server, and send that to the browser without any offset.  This shows the events in the positions we are wanting.  However the highlighting of the current day, and the current time is using `new Date()` as you say, so is currently a bit misleading for our use case.

As this is not a bug, perhaps the following is a possible enhancement?

BigCalendar be updated to accept a new optional prop called something like `getNow: PropTypes.func`, which would return a js `Date` that is to be considered "now".  This prop would be passed to everywhere that currently uses `new Date()` directly, which would change to call the prop value function instead (if it has been set, otherwise use existing behaviour).  From a very quick search it looks like about 5 files would need this change.  It should be a relatively low risk, backwards compatible change, and entirely opt-in functionality.

Does it sound like something that might be feasible for BigCalendar?

**Comment by alexeybondarenko** [comment]
I have one more reason to control the time indicator position. I have configured the visual regression testing and we have to control time indicator position to avoid the useless diffs.

**Comment by BOTOOM** [comment]
Try using

```typescript
<Calendar
getNow={() => {
	return new Date('2021-12-24T11:30:20') // custom date
	} }
/>
```
