### ISSUE TITLE
Localization Issue

### ISSUE THREAD

**Issue by adeelarshad83** [intljusticemission/react-big-calendar#431]
Hi

I am population calendar using dynamic data. My even is like that
{
end : "2017-06-04T11:00:00.000Z"
id : 10
start : "2017-06-04T10:00:00.000Z"
title : "final test(10:00-11:00)"
}

Setting localization
BigCalendar.setLocalizer(BigCalendar.momentLocalizer(moment));

The issue I am facing when I click on the event. I got event time like
15:00 - 16:00 but my actual time is 10:00 - 11:00

My current Timezone is GMT  + 5

How can I fix this issue.

Thanking you in anticipation

**Comment by andresgutgon** [comment]
Have you tried to pass `Date` objects like in examples? https://github.com/intljusticemission/react-big-calendar/blob/master/examples/events.js

**Comment by adeelarshad83** [comment]
Hi Andresgutgon

Yeah the rest api which is sending data to component is creating date like mention in example

Following is the code of rest API
               

               var bookingDay = new Date(value.bookingDay);
                var startTime = value.start.split(":");
                var endTime = value.end.split(":");
                value.title = desc + "(" + value.start + "-" + value.end +")";
                value.start = new Date(bookingDay.getFullYear(),bookingDay.getMonth(),
                    bookingDay.getDate(), startTime[0], startTime[1],0);
                value.end = new Date(bookingDay.getFullYear(),bookingDay.getMonth(),
                    bookingDay.getDate(), endTime[0], endTime[1],0);

**Comment by jquense** [comment]
this is a timezone issue I beleive, you are responsible for mantaining the timezone you wish on your dates. you can search past issues as well for more info.
