### ISSUE TITLE
Paginate faster in agenda view

### ISSUE THREAD

**Issue by ongjiinjoo** [intljusticemission/react-big-calendar#433]
Agenda view previous/next navigation feels awkward when the calendar is sparse. Since the default agenda range spans a month, wouldn't paginating it month by month be better? For example, if there's an item today and the previous item is 6 months ago, one has to click some 150-180 times previous to get there (or jump through hoops like switch to month view first, traverse the months, and switch back to agenda view.

Alternatively, can we parameterise it, so that instead of 'day', we could pass in 'week' or 'month' depending on how fast we want to paginate?

```
Agenda.navigate = (date, action)=>{
  switch (action){
    case navigate.PREVIOUS:
      return dates.add(date, -1, 'day');

    case navigate.NEXT:
      return dates.add(date, 1, 'day')

    default:
      return date;
  }
}
```

**Comment by jquense** [comment]
Sorry for the delay. I'd happily merge a PR adding this if you want u want! Thanks
