### ISSUE TITLE
Landscape orientation and range for week view 

### ISSUE THREAD

**Issue by WhoseSomebody** [intljusticemission/react-big-calendar#434]
Hello, guys! 

I've chosen this calendar because it is so flexible, just I got stuck.

I have 2 questions (I suppose that I just didn't find the answer in docs):
1. Is it possible to turn the week view so day names are on the right side and time axis is a vertical?
2. Is it possible, lest's say, to choose the minimal time range (e.g. from 8am till 18pm) but if there is an event outside of the range, include all the hours where events are.

So, I need to have something like this:
![image](https://user-images.githubusercontent.com/5785260/26970480-38418072-4d12-11e7-9cbd-ee8a40f4cab2.png)

Will be appreciate for any help! 
Thanks!

**Comment by jquense** [comment]
hi there!

1. this is not possible out ofhte box, you could write your own View that does this but it would be a siginificant amount of work

2. You can do this. The `min` and `max` props control what times rang is visible, You'll have to dynamically adjust them though to account for any events that fall outside the visible range.
