### ISSUE TITLE
I can't see month view in basic react-big-calendar

### ISSUE THREAD

**Issue by vaibhav-systango** [intljusticemission/react-big-calendar#436]
@jquense @srajko @tobiasandersen @bkniffler  
I can't see month view in my project even it is visible in react-dev tools but not on DOM why it happens only with month view?
/*
 *
 * EventDetailModal
 *
 */

import React, { PropTypes } from 'react';
import { connect } from 'react-redux';
import { graphql, compose } from 'react-apollo';
import gql from 'graphql-tag';
import RaisedButton from 'material-ui/RaisedButton';
import CenteredSection from '../../containers/HomePage/CenteredSection';
import Notifications, {notify} from 'react-notify-toast';
import {
  Table,
  TableBody,
  TableHeader,
  TableHeaderColumn,
  TableRow,
  TableRowColumn,
} from 'material-ui/Table';
import {GridList, GridTile} from 'material-ui/GridList';
import Divider from 'material-ui/Divider';
import Dialog from 'material-ui/Dialog';
import FlatButton from 'material-ui/FlatButton';
import localizer from 'react-big-calendar/lib/localizers/globalize';
import globalize from 'globalize';
import BigCalendar from 'react-big-calendar';
import events from './events';
import 'react-big-calendar/lib/css/react-big-calendar.css';
//import 'react-big-calendar/lib/less/styles.less';
//import './styles.less';
import './prism.less';

localizer(globalize);

const allViews = Object.keys(BigCalendar.views).map(k => BigCalendar.views[k])

export class EventDetailModal extends React.Component { // eslint-disable-line react/prefer-stateless-function

  render() {
    return (
      <BigCalendar
        {...this.props}
        events={events}
        views={allViews}
        defaultDate={new Date(2015, 3, 1)}
      />
    );
  }
}

export default EventDetailModal;

![screen shot 2017-06-14 at 1 07 55 pm](https://user-images.githubusercontent.com/25978575/27120872-c8c60df4-5102-11e7-8adf-345bf26cfeb4.png)
![screen shot 2017-06-14 at 1 08 43 pm](https://user-images.githubusercontent.com/25978575/27120871-c8c49a46-5102-11e7-8fd8-5989806d9670.png)

**Comment by jquense** [comment]
you need to set an explicit height per the docs, please search past issues before opening new ones, thanks
