### ISSUE TITLE
Event overlap example

### ISSUE THREAD

**Issue by lastday4you** [intljusticemission/react-big-calendar#437]
I am looking for a way to prevent event overlap,i had tried onSelectSlot but no luck here

**Comment by lastday4you** [comment]
i had done it in server side but i am just curios if there any optimal way to do it in the client

**Comment by jquense** [comment]
Hi there. You can cancel the selection, e.g. Prevent it from selecting more or less by returning false from the onSelecting callback. Then you add some logic to check if the selection would overlap and cancel if so
