### ISSUE TITLE
Default DateHeader prop "drillDownView" casing (v0.14.2)

### ISSUE THREAD

**Issue by fruitraccoon** [intljusticemission/react-big-calendar#440]
I think there's a small bug that has been introduced as part of this PR: [Adding optional custom DateHeader component for month view #402](https://github.com/intljusticemission/react-big-calendar/pull/402)

The `drilldownView` passed to the `DateHeaderComponent` has a lower-case `d` for down ([code](https://github.com/intljusticemission/react-big-calendar/blob/1339cd8fd8945702777f6cadc92f6b3943a6c077/src/Month.js#L223)), but the default `DateHeader` component expects `drillDownView` with an upper-case 'D' ([code](https://github.com/intljusticemission/react-big-calendar/blob/1339cd8fd8945702777f6cadc92f6b3943a6c077/src/DateHeader.js#L4)).

The effect I'm seeing is that the date header is no longer clickable by default (you have to override the dateHeader component).

I think `drilldownView` is the style that's been used elsewhere in the project, so I think just the default `DateHeader` component needs updating.

@andresgutgon A small typo unless I've missed something? :)

**Comment by jquense** [comment]
Thanks for tracking that down, could you send over a PR?

**Comment by andresgutgon** [comment]
My bad, sorry. Here is the fix https://github.com/intljusticemission/react-big-calendar/pull/442

**Comment by andresgutgon** [comment]
@jquense will you release this fix?

**Comment by andresgutgon** [comment]
Thanks!

**Comment by fruitraccoon** [comment]
Thanks very much guys!
