### ISSUE TITLE
TypeError: body is null

### ISSUE THREAD

**Issue by majioa** [intljusticemission/react-big-calendar#443]
I've installed the package `react-big-calendar@0.14.3` with `webpack-rails` and `react@15.6.1`. And I get in browser's console the error:

    TypeError: body is null

at the line:

    import BigCalendar from 'react-big-calendar';

The more definitely the problem is described here: https://stackoverflow.com/questions/41660246/adding-react-big-calendar-will-cause-uncaught-typeerror-cannot-read-property-m

**Comment by majioa** [comment]
@jquense why?

**Comment by jquense** [comment]
Because your linked SO issue accurately describes what's wrong. Not sure what you'd like done on our end?

**Comment by majioa** [comment]
Issue yes, but answer?

**Comment by jquense** [comment]
Oops, Sorry! I thought the issue was clear on the solution. Don't load the file in the document head, that's an anti pattern in modern web development. In terms of react rails I've never used it so I'm not sure how to make that happen in it.
