### ISSUE TITLE
release 0.14.1 expects webpack 2.2

### ISSUE THREAD

**Issue by chetanjk** [intljusticemission/react-big-calendar#444]
The recent release of react-big-calendar added 'webpack-atoms', which in turn uses 'less-loader', which expects webpack 2.2.
My app runs on webpack 1.13 and can't update it because of other dependencies.

As for the fix I am using exact 0.14.0 version to avoid the webpack version issue. 
Is there a way I can use updated version of react-big-calendar and with webpack 1.13?

**Comment by jquense** [comment]
webpack is a build dependency of the component so it shouldn't be relevant to your app since the code is already built. I just need to fix the sort of dep it is, its accidentally in the wrong spot
