### ISSUE TITLE
'true' responsive design/customize calendar theme

### ISSUE THREAD

**Issue by kurt-o-sys** [intljusticemission/react-big-calendar#445]
In the current implementation, responsiveness is done by shrinking the size of the boxes. On small devices in portrait orientation, this results in something rather useful. Having a responsiveness more like https://responsivedesign.is/patterns/calendar/ would make big calendar really nice.
Look at the 'month view' in the link above: on large devices, it's like a normal calendar view, but when the width drops (`@media(max-width: 768px)`), it gives a list-like view. This makes much more sense to me, having mobile in mind. Would this be possible in big calendar? (I pretty much like the design of the calendar in the link above).
Or, well, have a customizable style/theme would do as well, I guess?

(I know I could fork and start fiddling with the less/css part of big calendar, but I thought it's more useful if there's a more generic solution, than forking each time someone prefers another theme/style)

**Comment by jquense** [comment]
it should be easy enough to implement in your code. I'd use a media query from javascript and when it matches set the calendar `view` to agenda, or whatever view you think works best. You'll probably have to do some tweaking to the toolbar though to get it to fit nicely.

**Comment by paulhan221** [comment]
there an example of this being done?
