### ISSUE TITLE
Multiple html5 backends issue

### ISSUE THREAD

**Issue by jackaryas** [intljusticemission/react-big-calendar#447]
I realise this is a react-dnd error, however, is it possible to instantiate the dragdropcontext / html5 backend at a component higher up in the tree, i.e. The index.js page? I need drop support outside of the calendar but when instantiating dragdropcontext higher up the tree I get the "can't have multiple html5 backends" error from react dnd. It appears the calendar instantiates it's own instance of html5 backend as it runs with just exporting the raw component (you don't need to wrap in dragdropcontext) 

Any help appreciated, cheers!

**Comment by koox00** [comment]
It is already solved, you can see #350

**Comment by jackaryas** [comment]
Thanks! Apologies must have missed that issue
