### ISSUE TITLE
agendaHeaderFormat date (start, end) return undefined

### ISSUE THREAD

**Issue by AgamlaRage** [intljusticemission/react-big-calendar#449]
react-big-calendar 0.14.4
localizer: moment 2.18.1

I cannot get the **start** or **end** date from the ```agendaHeaderFormat(date, culture, localizer)``` format.
This is returning undefined for both.
`culture` and `localizer` params are fine.

Others formats like dayRangeHeaderFormat, dayHeaderFormat return date normally.

Thx

**Comment by peterox** [comment]
I believe this was broken by @jquense in  f084becac0fa83ff56062094e318e10cf02dabcb.

The change to viewLabel.js expects the View.range() methods to return an array. Day, Week and WorkWeek were changed to return an array but Month and Agenda were not. As Agenda's header is a range then the getRangeBounds is failing to return the correct range object to be localized.
