### ISSUE TITLE
Add possibility to remove "All Day" row in month and day view.

### ISSUE THREAD

**Issue by vogrelord** [intljusticemission/react-big-calendar#45]
Sometimes business logic don't include All Day events.
It would be nice to have possibility to disable this functionality with a prop.

**Comment by 3plusalpha** [comment]
+1 for that! I am currently integrating the calendar into a project and there is no need for the All Day events.
Btw, great work!

**Comment by jquense** [comment]
I'd take a PR but you will run into the issue with multi-day (not all day) events, which right now are displayed in the all-day section, So I am not sure what you would do with those events in those cases.

**Comment by andrew-melnyk** [comment]
It is easy to do by overriding styles:
```
.rbc-time-content {
    border-top: none;
    padding-top: 0px;
}
.rbc-time-header.rbc-header-overflowing > .rbc-row:nth-of-type(2) {
    display: none;
}
```
But yes, agree with that prop would save the time.

**Comment by rpiaggio** [comment]
I'd appreciate this being implemented on the week view.

Multi-day events should be shown "uncollapsed", occupying all the time they encompass in the calendar.

We are using the calendar to let the user pick a time slot, but we need to blank out the existing events.

Thank you.

**Comment by djdreamer79** [comment]
this worked for me

$('#calendar').find("tr .fc-unselectable:first").css( "display", "none" );
