### ISSUE TITLE
scrollToTime prop is unintuitive

### ISSUE THREAD

**Issue by Maxincredible52** [intljusticemission/react-big-calendar#452]
First off, thank you for maintaining this awesome library! Though I have a question/request: 

In my project I only need the week view. Setting the `scrollToTime` prop is very unintuitive in my opinion. When setting the property initially everything works fine but setting it a second time nothing happens (this is especially a problem when asynchronously loading events and setting the scrolltime according tho their start/end times). 

The component only updates its scrolled time once the user navigates or when the prop is changed again (creating this off by one feeling: the scrolled time is always the value I set it before the one that the component is displaying). 

I don't know if this is expected or wanted behavior but there should be at least an option where the `scrollToTime` prop can be a completely controllable prop of the component.

**Comment by shettypuneeth** [comment]
We have a similar requirement in DAY view wherein, the scrollToTime value changes on user interaction. But currently the calendar doesn't scroll to the updated scrollToTime prop or scrolls to an incorrect slot.
Is this a bug or scrollToTime prop only works on the initial load.
I've set up a code sandbox to repro the issue: https://codesandbox.io/s/B225Y0EJ

**Comment by nabs-grg** [comment]
Hi 

I am trying to scroll down when I selecting a new slot to create an event but the calendar doesn't scroll below the current window height.

In the screenshot below, I am trying to scroll down below 12:30 pm but can't scroll down below the current window. Please do let me know why I am not able to scroll down.

Thanks

<img width="930" alt="screen shot 2017-10-11 at 14 35 35" src="https://user-images.githubusercontent.com/17575788/31443522-9a6db014-ae91-11e7-842e-29e62910aba7.png">

**Comment by Maxincredible52** [comment]
@jquense no comment on why this issue was closed?

**Comment by Way-U-Need** [comment]
what was the solution???

**Comment by zaunermax** [comment]
@Way-U-Need the issue was closed without providing any further information by @jquense
