### ISSUE TITLE
Css Issues

### ISSUE THREAD

**Issue by gate3** [intljusticemission/react-big-calendar#453]
Hello, wonderful library here. Much appreciated. I intend to use the component on a page built with bootstrap, but the css doesn't seem to work well, its just plain without background. Do i have to create my css or is there something i am missing, please advice. 

I have included an image of what it looks like currently.

![image](https://user-images.githubusercontent.com/3597437/27636177-21ea8e3c-5c02-11e7-93a9-ecc6d9042744.png)

**Comment by jquense** [comment]
You need to set an explicit height on the calendar per the docs

**Comment by gate3** [comment]
It's not just the height. I would like to have the default styling in the demo, if i can. I need a quick prototype for now.

**Comment by jquense** [comment]
you also need to include the css on your page that's included in the npm package as well.

**Comment by gate3** [comment]
Done that..

`
import BigCalendar from 'react-big-calendar'
import 'react-big-calendar/lib/css/react-big-calendar.css'`

**Comment by jquense** [comment]
great then you just need to set the height of the calendar. the demo's use the default included styles.

**Comment by alansutherland** [comment]
@jquense I've imported the css and set an explicit height, no errors shown yet the css is not being applied. 

a suggestion: these two steps could be rolled in to your default code, saving devs from this in the future and making your plugin a more user friendly experience

**Comment by alansutherland** [comment]
Note: If you're using style-loader and css-loader and you have modules:true enabled on css-loader, make sure to import it as global CSS like such: 

import '!style-loader!css-loader!react-big-calendar/lib/css/react-big-calendar.css'.

https://github.com/intljusticemission/react-big-calendar/issues/234
