### ISSUE TITLE
min, max props in Internet Explorer

### ISSUE THREAD

**Issue by au335704** [intljusticemission/react-big-calendar#454]
If i set the 'min' and 'max' props (e.g. with date objects today from 8:00 to 16:00) the timeslots will change and "cluster" in the top of the day/week view, along with all events in the timeperiod. This only happens in Internet explorer(11). 
I realized that this can also be seen in the Timeslots example's day and week view, although only timeslots "move" there and not events as well.

Any idea on how to fix this? 

![image](https://user-images.githubusercontent.com/17641817/27640032-5af23232-5c18-11e7-8d1a-4796796fbb60.png)

**Comment by jquense** [comment]
sounds like flexbox bug/difference in IE. I'm not sure why it would be present only when setting the min/max tho...Do you think you could explore it a bit? I don't have ready access to IE11
