### ISSUE TITLE
Spread operator const {...props} = this.props

### ISSUE THREAD

**Issue by diemax** [intljusticemission/react-big-calendar#455]
Hello! Great project!

Just a little enquire, I know how the spread operator [works](https://stackoverflow.com/questions/31048953/what-do-these-three-dots-in-react-do), in this [part of your code](https://github.com/intljusticemission/react-big-calendar/blob/master/src/DateContentRow.js#L136#L154) I can see: 
```javascript 
render() {
    const {
      rtl,
      events,
      range,
      className,
      selectable,
      renderForMeasure,
      startAccessor,
      endAccessor,
      renderHeader,
      minRows, maxRows,
      dateCellWrapper,
      eventComponent,
      eventWrapperComponent,
      onSelectStart,
      onSelectEnd,
      ...props
    } = this.props;
```

Just I'm not getting how is working in the last variable assign: 
```javascript 
const {...props} = this.props
```
I would appreciate if you have some explanation/example!

Thanks!

**Comment by jquense** [comment]
It's the object rest/spread syntax. https://github.com/tc39/proposal-object-rest-spread/blob/master/README.md

**Comment by diemax** [comment]
Thanks! :blush:
