### ISSUE TITLE
 'need to set an explicit height'

### ISSUE THREAD

**Issue by forhadmethun** [intljusticemission/react-big-calendar#459]
Can anybody please give me an example of the explicit height?

**Comment by tobiasandersen** [comment]
The container div must have a height (or nothing inside will be visible). You can set the height using css, just like you would set any other height using css. The simplest example would probably be something like this:
```
.rbc-calendar { 
  height: 800px; 
}
```
But you could also do it using e.g. flexbox. The main point is just that the container needs a height, or it will be 0 in some cases.
