### ISSUE TITLE
add setting to allow / prevent overlapping slots

### ISSUE THREAD

**Issue by 3plusalpha** [intljusticemission/react-big-calendar#46]
In some cases it should be prevented to create overlapping slots.
I would propose a property e.g. `overlapping={false}`, which defaults to true.

I implemented an overlapping check into an own calendar and disabled the slot creation for areas where a slot / event already existed.

**Comment by Joramt** [comment]
Big calendar purpose is to display events on a calendar graphic support. Therefore it makes sense for the events to overlap, as one person might be attending various numerous of events in a single day. This isn't an issue, but simply a request that you'd like big calendar to have to suit your needs.

**Comment by 3plusalpha** [comment]
Yes, it's a feature request. In my case I want to let users define dates / slots that do not overlap. For example teacher can only teach one class at once.

**Comment by jquense** [comment]
Generally I think the best way to handle this is to enforce the event overlapping constraints outside of the calendar using the callbacks. I thnk the only things thats missing to allow this usecase is the ability to prevent the actual drag and select to create a an event. the`onSelectStart` callback already exists it probably makes sense to allow preventDefault in those cases.

**Comment by 3plusalpha** [comment]
Callbacks would be a nice generic solution. I would propose to add these two events: `onSelect` and `onSelectEnd`.

**Comment by 3plusalpha** [comment]
Thanks! :)
