### ISSUE TITLE
Uncaught Error: Cannot have two HTML5 backends at the same time.

### ISSUE THREAD

**Issue by szopenkrk** [intljusticemission/react-big-calendar#460]
Hi i have same problem but we use react-data-grid and try to add react-big-calendar
After add component which include react-big-calendar we have error "Uncaught Error: Cannot have two HTML5 backends at the same time."

react-big-calendar use react-dnd and react-dnd-html5-backend how to solve that problem?

**Comment by jquense** [comment]
RBC let's you specify your own backend so you can pass in one shared on to it. I'm assuming that data grid allows this as well. If not I'd ask them to make it pluggable :)

**Comment by szopenkrk** [comment]
react-data-grid works fine its creates one instance to multi grids but adding drag and drop callendar i lost stable app and have that error any other solution ?

**Comment by jquense** [comment]
did you try the solution i just suggested?

**Comment by szopenkrk** [comment]
Yes we tried and all the time the same error

**Comment by jquense** [comment]
if you only have one backend there isn't any way to get this error. pass the same backend to react-big-calendar _and_ react-data-grid. If react-data-grid does not allow you to pass it a backend then the problem is on their end and there is nothing I or you can do.
