### ISSUE TITLE
Overnight event doesn't render on second day

### ISSUE THREAD

**Issue by jasonogasian** [intljusticemission/react-big-calendar#461]
I have a use case where events can span midnight. When these events are drawn on the calendar only the portion on the first day is shown.

**Comment by jquense** [comment]
Do you have a specific example? Please provide a reproduction thanks

**Comment by jasonogasian** [comment]
When adding the following event to examples/events.js I would not expect to see an "all day" event as the event does not go for an entire day.

  {
    'title': 'TEST',
    'start': new Date(2015, 3, 3, 11, 0, 0),
    'end': new Date(2015, 3, 4, 0, 10, 0)
  },
