### ISSUE TITLE
src/utils/eventLevels.js : findIndex is not supported on ie11

### ISSUE THREAD

**Issue by o-bo** [intljusticemission/react-big-calendar#464]
Since this [commit](https://github.com/intljusticemission/react-big-calendar/commit/2a70c3c3134b26e60997a729cc8048a8be91ee83), an error is thrown by ie11, complaining about findIndex [support](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findIndex#Browser_compatibility).

We solved the problem by adding the [polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findIndex#Polyfill) when initializing our project.

**Comment by o-bo** [comment]
We corrected the problem by adding the [polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findIndex#Polyfill) when initializing our project.

**Comment by tobiasandersen** [comment]
This should be fixed since https://github.com/intljusticemission/react-big-calendar/pull/671 by including lodash's `findIndex` method.
