### ISSUE TITLE
Time column shrinks when modifying events on IE 11

### ISSUE THREAD

**Issue by gandrin** [intljusticemission/react-big-calendar#466]
I have an issue with the calendar and events on IE 11.
When I add an event, or modify one, the time column containing it shrinks (see screenshot).

For now, I use a hack that consists in adding `height: 100%;` to the `.rbc-time-column` class.

<img width="1021" alt="screen shot 2017-07-11 at 10 26 28" src="https://user-images.githubusercontent.com/3703692/28059166-8746da30-6623-11e7-811c-b1482aa756cb.png">

Any Idea how to solve this properly ?

Thanks in advance for your help.

**Comment by jquense** [comment]
I'm not sure how to fix it :) I'm sure it's related to flexbox bugs in ie11 though. I don't have easy access to IE11 at the moment, but i'm happy to implement any css fix you can find that fixes it.

**Comment by emilnygaard** [comment]
@jquense Don't know if it helps you, but we had a similar issue where the calendar didn't show in IE as the CSS was bugged.
The solution for us, was to overwrite the height on `.rbc-calendar` to use a px value instead of 100% .
Hope that solves it for other people :)
