### ISSUE TITLE
Broken in IE11 due to missing Object.assign

### ISSUE THREAD

**Issue by forum-is** [intljusticemission/react-big-calendar#467]
Commit 464af403aec464d2428220288960f6b16e01c34a by @jquense completely breaks IE11 due to removal of babel-plugin-object-assign.

Please re-add the polyfill for Object.assign and also consider fixing #464, which is another show-stopper for IE11. Thanks!

**Comment by Paul-Colucci** [comment]
this would be nice!

**Comment by tobiasandersen** [comment]
This should be fixed by https://github.com/intljusticemission/react-big-calendar/pull/542.
