### ISSUE TITLE
IE10 flexbox layout not working properly

### ISSUE THREAD

**Issue by qudde** [intljusticemission/react-big-calendar#468]
The calendar is not rendering properly on IE10. I think it's a problem with flexbox.

From "Big Calendar" examples:
![skarmavbild 2017-07-12 kl 13 01 49](https://user-images.githubusercontent.com/16950578/28114770-88155d8a-6702-11e7-9e6f-430798e89960.png)

Anyone have any idea how to fix this on IE10?

**Comment by olivergeorge** [comment]
It think the problem is IE10 doesn't provide flexbox support.

http://caniuse.com/#feat=flexbox

**Comment by erback** [comment]
@olivergeorge it says in the documentation the calendar should have ie10+ support. There are also fallbacks in the css for handling flexbox in ie10 from what i can se.
