### ISSUE TITLE
Vertical Resource View

### ISSUE THREAD

**Issue by JD2k** [intljusticemission/react-big-calendar#469]
Hello,

is it possible to change the timeslot view to use custom resources instead of time slots? Couldn't find anything like it. Propably kind of a feature request, but maybe someone can help :).

E.g.:

/ Ressources | Monday | Tuesday  | ....
/---------------------------------
/Resource1    | Holiday | Available  |
/Resource2    | Work     |                  | ....
/....

Thanks in advance

**Comment by JD2k** [comment]
Some addition. It should exactly look like this https://fullcalendar.io/scheduler/ , but i need it in react.

**Comment by sheam** [comment]
I would like this too. Similar to this: https://www.npmjs.com/package/react-calendar-timeline

**Comment by tobiasandersen** [comment]
Not quite what @sheam suggests, but it sounds like https://github.com/intljusticemission/react-big-calendar/pull/423 will help you! Feel free to re-open otherwise!

**Comment by tobiasandersen** [comment]
Sorry, I didn't read through this properly before closing...
