### ISSUE TITLE
Support popup in week and day view

### ISSUE THREAD

**Issue by GabiAxel** [intljusticemission/react-big-calendar#47]
If a slot contains more than one event in week or day view, the events are overlapping horizontally, even if popup=true. It would be nice if for that case there would be a "+" on the right of the slot that would open the popup same as in month view.

**Comment by jquense** [comment]
thanks for the issue, The complexity involved in something like that would be really tough, since unlike month views, there are many different sections of the of the day slot that can have overlapping events.

The overlapping behavior is, I think the best way to express events in that context.
