### ISSUE TITLE
Change event-cell hoover behavior

### ISSUE THREAD

**Issue by gryzik** [intljusticemission/react-big-calendar#470]
I need to change event hoover behavior.
I want to remove existing tooltip and add my hoover function.
Is it possible ?

**Comment by GhislainRoy04** [comment]
I manage to do something using eventPropGetter, I passed a component that had hover events on it and I displayed the info there. Not sure on how to remove the exiting tooltip tho

**Comment by skhamoud** [comment]
Any updates on this ? I can't find a way to neither hide nor change the behavior of the tooltip .

**Comment by jquense** [comment]
No updates. PR's welcome!

**Comment by aappddeevv** [comment]
I think I responded to  a closed issue, but we need to create our own event renderings. Something I have seen that is useful in other libraries is a `onEventRender` type property that takes the properties and default rendering function. Then someone can just use the default rendering and wrap the default rendered component easily with something that does tooltip/hover behavior with your own hover content of course. 

onEventRender would get a default rendering function that renders an EventCell object  so you can really do what you want easily. This also fits into the renderprops pattern that is popular.
