### ISSUE TITLE
components.Slot - customizing slot rendering

### ISSUE THREAD

**Issue by alex-mironov** [intljusticemission/react-big-calendar#471]
hey, probably I'm doing/understanding something wrong, but why is it impossible to use custom component for slots? It would be nice because we could render some slots marking them as busy etc.

**Comment by tobiasandersen** [comment]
You should be able to use the `dayWrapper` [component prop](http://intljusticemission.github.io/react-big-calendar/examples/index.html#prop-components) for this.
