### ISSUE TITLE
"+X More" causing routing problems

### ISSUE THREAD

**Issue by mgoudy91** [intljusticemission/react-big-calendar#477]
We're using react-big-calendar and having some routing issues as a result of the "+X More" <a> tag using href='#'. I removed this href, as I don't see it being used anywhere, and it seems to work fine without it.  Is this a reasonable change, or is the href being used for something I'm missing? I'll submit a PR with the change if not.

Thanks

**Comment by mgoudy91** [comment]
#478

**Comment by ravihugo** [comment]
Just ran into this issue.
This was my local fix in my component that was rendering my BigCalendar:

    componentDidUpdate() {
        // After an update, we must dynamically replace all +1 more links a bit
        var calendar = ReactDOM.findDOMNode(this);
        if (calendar instanceof Element) {
            calendar.querySelectorAll('a').forEach(a => {
                a.href = 'javascript:false';
            });
        }
    }

Effectively using javascript:false instead of hash-symbol works perfectly for our use-case.
