### ISSUE TITLE
Update Get Started

### ISSUE THREAD

**Issue by carlos-peru** [intljusticemission/react-big-calendar#480]
The get started guide says to include react-big-calendar/lib/css/react-big-calendar.css, but that file doesn't seem to be present in the repo. It's a bit confusing and it's just at the beginning which can easily mislead or discourage newcomers.

Thank you for the awesome work!

**Comment by jquense** [comment]
It's in the npm package, not the repo, since it's a generated file. The direction though is correct still :)
