### ISSUE TITLE
How to hide all day row

### ISSUE THREAD

**Issue by martinnov92** [intljusticemission/react-big-calendar#481]
Hello is there any way how to properly hide all day row or should I just hide it with css?
Thank you

**Comment by jquense** [comment]
Hi there, There isn't any way to do so, which is intentional. That row says all day and a events that span multiple days, hiding it would cause such events to disappear from the calendar

**Comment by krvajal** [comment]
Thats exactly what I want, to make this events to disappear from the calendar. Can it be hidden with CSS? Will it have any impact?

**Comment by Noitidart** [comment]
I also want to hide all day row. (we have no all day events)

**Comment by shivamjjha** [comment]
You can do it with css:

```css
/* hide all day row */
.rbc-allday-cell {
  display: none;
}
```
