### ISSUE TITLE
Customize the ceil background 

### ISSUE THREAD

**Issue by lastday4you** [intljusticemission/react-big-calendar#482]
Would it be possible to change the ceil background color based on certain class? or it is too costly for performance ?

**Comment by jquense** [comment]
sorry what are you trying to change the color of?

**Comment by lastday4you** [comment]
sorry for my clear definition was wonder if there a way to change rbc-time-slot class based on certain condition

**Comment by jquense** [comment]
There is not, there was some work on adding such a feature (layouts, background events, etc) but nothing got finished.

**Comment by lastday4you** [comment]
thank you for your kind answer :) and for your great work i understand
