### ISSUE TITLE
Changing header for various views?

### ISSUE THREAD

**Issue by tylerbhughes** [intljusticemission/react-big-calendar#483]
I like the week view, but for my project I'm trying to schedule events for multiple locations. Is it possible to set up the header so that instead of each column being a different day it's instead something else say a different location. That way I can get quick glance at what locations are scheduled for a given time slot. If not, then what about adding additional columns to the day view? That'd give me the same result.

**Comment by jquense** [comment]
You are probably looking for "resources" https://github.com/intljusticemission/react-big-calendar/pull/423 there isn't anything there yet, but if you want to pick up the PR and finish it we can get it merged :)
