### ISSUE TITLE
Different Background Colors for Different Events? 

### ISSUE THREAD

**Issue by ramkandasamy** [intljusticemission/react-big-calendar#484]
Hello, I've been playing with your library and really like it! I had a question with respect to having events with different colors.

I realize from looking at this: https://github.com/intljusticemission/react-big-calendar/blob/master/examples/demos/rendering.js that you can customize the look of each event, but it looks like it only pertains to the content within rbc-event-content. So for example, I could change the color of the text of an event, but I can't seem to change the background color of the whole event rectangle.

What I want to do is to change the color of the event rectangles themselves (these are determined by the .rbc-event css class). Is there an easy way to do this without having to hack the source code?

**Comment by ramkandasamy** [comment]
Just to clarify, my use case is to have a 'green' background color for ongoing events and the default blue color for events in the future and past.

**Comment by jquense** [comment]
yes you can use the prop `eventPropGetter` to return a class name based on the event!

**Comment by ramkandasamy** [comment]
Thanks, works great!
