### ISSUE TITLE
Background color when selecting

### ISSUE THREAD

**Issue by GhislainRoy04** [intljusticemission/react-big-calendar#486]
Hello, I know that with eventPropGetter you can change the color of the event cell, but when selecting that event it returns back to dark blue, is there a way to change that color in a similar way to eventPropGetter?
Cheers

**Comment by ramkandasamy** [comment]
Sure, the answer is to use the eventPropGetter. The eventPropGetter is a function with the following signature: 
function(
    event: object,
    start: date,
    end: date,
    isSelected: bool
) -> { className: string?, style: object? }

This means in your function, you can have an if statement based on the value of isSelected and assign a different color for both cases.

**Comment by GhislainRoy04** [comment]
Mmm didn't thought of the isSelected. will try that thanks!
