### ISSUE TITLE
Click in the entire box

### ISSUE THREAD

**Issue by Bombe93** [intljusticemission/react-big-calendar#487]
Hi,

it's possible to access the day view by clicking inside the blank space of the day box?
(The number is really small)

Thanks

**Comment by mikeyc7m** [comment]
use the onSelectSlot property

**Comment by Bombe93** [comment]
I had tried but did not work. I called the function to enter the day view but could not pass all the data

**Comment by Bombe93** [comment]
Any update on this?
Thanks

**Comment by jquense** [comment]
no update, `onSelectSlot` is still the correct the prop, it gives the day or timeslot you select
