### ISSUE TITLE
defaultView missing from api docs

### ISSUE THREAD

**Issue by olivergeorge** [intljusticemission/react-big-calendar#488]
I think this is a small oversite from the docs/demo page.  `defaultView` is not listed as a prop and the only mention is associated with the `view` property.

http://intljusticemission.github.io/react-big-calendar/examples/index.html

**Comment by jquense** [comment]
yeah, the `default` props aren't listed seperately as they are directly tied to their related controlled/uncontrolled prop. I'm open to a PR adding them tho if anyone wants to tackle it
