### ISSUE TITLE
I want to add the 'id' to EventCell

### ISSUE THREAD

**Issue by 21ma** [intljusticemission/react-big-calendar#49]
I want to see the details View from the pop-up by clicking the event-cell.
(for example. https://github.com/romainberger/react-portal-tooltip)

To use the 'react-portal-tooltip' component requires 'id' element.
I know className and style can be added, or id is not able to add?

lib/EventCell.js 
```
    if (eventPropGetter) var _eventPropGetter = eventPropGetter(event, start, end, selected),
          id = _eventPropGetter.id, // ***** for example. *****
          style = _eventPropGetter.style,
          xClassName = _eventPropGetter.className;

    return _react2['default'].createElement(
      'div',
      _extends({}, props, {
        id: id, // ***** for example. ***** 
        style: _extends({}, props.style, style),
        className: _classnames2['default']('rbc-event', className, xClassName, {
          'rbc-selected': selected,
          'rbc-event-allday': isAllDay || _utilsDates2['default'].diff(start, _utilsDates2['default'].ceil(end, 'day'), 'day') > 1,
          'rbc-event-continues-prior': continuesPrior,
          'rbc-event-continues-after': continuesAfter
        }),
        onClick: function () {
          return onSelect(event);
        }
      }),
      _react2['default'].createElement(
        'div',
        { className: 'rbc-event-content', title: title },
        Component ? _react2['default'].createElement(Component, { event: event, title: title }) : title
      )
    );
```

Place to use the r-b-c
```
    eventStyleGetter(event, start, end, isSelected) {
        let style = {
            backgroundColor: '#ff0000',
        };
        return {
            id: 'rbc-cell-' + event.id, // ***** for example. ***** 
            className: 'hoge',
            style: style
        };
    }
```

**Comment by jquense** [comment]
You intentionally can't add an `id` prop, just class and style, since the primary purpose of it is to allow styling hooks, not hooks to the DOM node.

I am a bit of the opinion that the react-portal-tooltip API is not very "react-y" if it requires id's. You might want to ask if they would allow a more flexible API (such as providing a function that returns an element). You can also provide a custom event Component and add an ID to that if you want to make it work as is.

**Comment by 21ma** [comment]
Thank you.

**Comment by TheZoraiz** [comment]
An alternative is to assign a class to the event in `eventStyleGetter()`, then programmatically set that class as the div's id after it's mounted.
