### ISSUE TITLE
Events that span longer than 1 day with specific hours it starts and ends at show as all day events

### ISSUE THREAD

**Issue by Auchindoun** [intljusticemission/react-big-calendar#490]
If there is an event that starts at 9am and ends 3 days later at say, 10pm, this shows as an all day event for the starting and ending days.

If I find a solution on my own I will submit a PR, but just wanted to bring visibility to this use case.

**Comment by jquense** [comment]
Yes this is intentional, otherwise events would completely cover the day views which is fairly annoying for the days it spans the entire day. There are a few past issues on this you can reference

**Comment by Auchindoun** [comment]
Sounds good, but I can’t seem to find the reference issue or example of someone implementing this functionality. Do you have a reference to itby any chance I could take a look at @jquense? As even though this would cover the entire day views, this is preferable in my application. Thanks!

**Comment by mikeyc7m** [comment]
perhaps the start (and end) time could be visible in the spanning allday event title.

**Comment by Auchindoun** [comment]
I think I will be taking the approach that was done in PR [#42](https://github.com/intljusticemission/react-big-calendar/pull/42), and make it up to date with the newest changes. I'll likely just use this myself though, since the original PR was denied.

**Comment by jquense** [comment]
If you do complete that PR i may be open to accepting it if it's configurable.

**Comment by Auchindoun** [comment]
Sure thing! I'll close this issue.
