### ISSUE TITLE
Different height calculation

### ISSUE THREAD

**Issue by steodor** [intljusticemission/react-big-calendar#492]
Hello, first off congratulations for this great component! 

Now, i have an issue with the calendar height. Not with not seeing anything like so many other issues around here (i did read the docs :) ), but with why the height is required and must be fixed. I'm guessing this is because you calculate the row height depending on the container height, then display as many events in each row as they fit. The rest go in the `+1 more` links in each cell. And that's fine.

What i'd like more though, would be to specify a min/max number of concurrent events to display (let's say 3/5). Now, if a row has 0 to 3 events in a cell, it would render 3 event slots in order to give the entire row a nice appearance. If there are more than 5 events in a cell, it would render the first 5 and put the rest under the '+1 more' link as it already does (same appearance, but kinda different meaning as you can see). Rows with 3 to 5 concurrent events would take the corresponding height to fit them all but no more.

Cons:
- this implies changing the mindset a bit: no more calculating heights depending on container, but let container occupy the height of its children. This might be a lot easier said than done, depending on how deep the fixed height assumption is hard-coded into the component (i didn't have time to look through the code yet). But, i'm confident it's not impossible to implement, nor that it would bring many (if any) disadvantages. If anything, it should skip quite some height calculus.

Pros:
- it relieves the calendar component from dealing with scroll (now it reserves a bit of space on the right for the scrollbar). That would become the user's concern, with multiple solutions to choose from depending on the desired look & feel they're going for.
- week/day/agenda views would also look good (better imo) integrated with the page's scroll instead of scrolling in a box. Sticky headers might become handy, but again, it becomes the user's concern. Implementing optional out-of-the-box support for it would be a different matter.
- you could decide to make auto-height mode default with sensible defaults like 3/5 above (and opt-in into the fixed height mode via a prop) and avoid all the issues people have been submitting about not being able to see anything because they didn't have any height set. It's not your fault people aren't paying attention to the docs, of course, but if so many people have this issue, i see it as an opportunity to make the library one step more intuitive to use than it already is.

I would implement this as an opt-in feature at first (something like `autoHeight={{ min: 3, max: 5 }}`, with `autoHeight=false` as default), then just making `{ min: 3, max: 5 }` the default value if people use it frequently enough for it to make sense. What do you think?

Thanks for your time!

**Comment by jquense** [comment]
The reason height works the way it does really isn't for calculating surprisingly. It's really more a consequence of the flexbox styling. Overall it's preferable for the calendar to easily expand or shrink to fit the space you want...generally you want the calendar to be about the window height so it is visible without scrolling. With flexbox you can use height: 100% and have that just work without explicit heights (e.g 400px). For events we then just look at how many events fit in the available space and render that many. 

You are correct we could start with how many events you want to render and do that, letting that determine the height of the calendar overall, but my experience is that is generally less preferable because it makes fitting a calendar on the screen without scrolling and not clipping events basically impossible

**Comment by steodor** [comment]
I understand that it's preferable in most cases for the calendar to fill a certain space, that's why i didn't suggest changing the layout altogether but rather having an opt-in alternative. I did get ahead of myself with suggesting that it may become the default behavior, sorry about that :)

However, there are cases when having all events visible (not hidden beneath a `+X more` link) is more important than having the calendar fit the page vertically. Think about having most users with an average of 6 to 10 events per working day in a month view (that's my use case actually). On a laptop screen, as much as i try to tweak the layout, there's pretty little room left for the calendar so basically each day ends up having a `+X more` link. Trying to look for a specific event if you don't remember exactly when it is becomes a huge hassle. A few links are ok, let's say for more than 12 events, but a link in every cell is definitely not. Going to an extreme in this direction (just for completeness), we could even display all events by setting something like `max: 0` or `max: false`. The calendar not fitting in the page becomes an intrinsic and accepted trade-off. The user would have to scroll, but he would see all events at a glance and be able to click the one he's interested in immediately, without click-searching. Color-coding events by category and on a per-event basis goes a long way in making events very easy to identify even if there are a lot of them (we have that already). We could try to also add tooltips with pictures, something like http://wpshindig.com/events/ for example, but i'm not yet sure about it.

I know dimensions are tweak-able up to a point, but i just want to get a sense of scale, if you will bear with me. If not, please just skip this paragraph, no problem. So right now an event is about 24px high, so accounting for max. 12 events means about 285px, times 5 rows + around 40px for the header means roughly 1450px, which is not available even on a full-hd display. Having the user scroll this much if he has this many events is ok, but for people with 6-7 events per day i'd like to render just the roughly 800px they occupy and have them scroll less. Or people with a week's vacation - i'd like to "collapse" that week and not render 200 or so px of empty space. Or new people with 2-3 events, they'd see the entire calendar without even scrolling.

Overall, i think this is a valid use-case for an opt-in feature. Having both layouts available would provide the best of both worlds: instant view of all days with `+X more` links wherever needed (in the current form), or instant view of all or most events, depending on configuration, with the proposed solution. 

I am tempted to fork this repo and have a go at adding it, but it would obviously take me a lot more time than it would take you to do it. Please let me know if you're interested either in doing it yourself or in a pull request if/when i get the time for it.

Thanks!

**Comment by steodor** [comment]
@jquense should i take your lack of reply as you're not interested? Thanks again.

**Comment by jquense** [comment]
Sorry i just don't have a ton of time :)

I'm fine i with allowing a "fit events" mode that doesn't truncate events, _provided_ it doesn't add a large amount of complexity, or configuration. My hunch here is that its not going to be easily doable because the "logic" for the current approach isn't really logic is the css of the month view (and a measure check in TimeGrid). If you want to give it a shot go for it!

**Comment by steodor** [comment]
No problem, i'll post back if/when i get the time to give it a whirl.

**Comment by ehahn9** [comment]
I don't know if this is helpful, but I found wrapping the calendar in a flex container with `flex-grow=1, height=0` "tricks" the calendar into seeing an explicit height, yet filling the parent completely. You can't use `height=100%` because that's still not explicit. Just FYI in case that helps anyone!

**Comment by steodor** [comment]
Thanks @ehahn9 but that's not the issue described here (or am i misinterpreting something?). I do NOT want the calendar "filling the `parent` completely" but rather expand or shrink depending on contents. The parent would NOT have an explicit height so that page scroll would appear and do its job. Please read the issue carefully and let me know if i'm mistaking. In my case we ended up doing something like you said and left it like that - there's a task in our backlog but won't be reached anytime soon. I will report back if/when we do.

**Comment by ehahn9** [comment]
so sorry - I didn't mean to imply I had something to fix your OP.  I Was just trying to add some related info for other readers. My apologies if my comment was unclear.

**Comment by steodor** [comment]
Oh, ok, no problem. However, there are many other issues ("height is 0"-like) which would benefit a lot more from your experience. Thanks for the clarification :)

**Comment by xorozo** [comment]
If you want to show all the events without a scroll. here is my solution.
```
.rbc-month-row {
  flex-basis: auto !important;
  .rbc-row-content-scrollable {
    .rbc-row-content-scroll-container {
      min-height: 150px !important;
    }
  }
}
```
and necessary props are here.
```
<Calendar
   ...
  showAllEvents={true}
/>
```

**Comment by ChrisB1123** [comment]
Just commenting to say @ehahn9's solution fixed a problem for me where the calendar wasn't adhering to the parent's height, and incorrectly extending beyond the bottom of the view port, in case anyone is searching for a similar problem in the future!
