### ISSUE TITLE
Week view doesn't work in Safari with no events

### ISSUE THREAD

**Issue by thedeadc0der** [intljusticemission/react-big-calendar#493]
The calendar is set to week view, with a set start and end time. When no events are present, it displays correctly in Chrome and Firefox, but in Safari only the toolbar is displayed:

<img width="797" alt="rbc bug safari" src="https://user-images.githubusercontent.com/14041174/28975535-aa93c230-793a-11e7-8691-23fb802e5f2d.png">

**Comment by jquense** [comment]
should be some fixes coming for that

**Comment by tkporter** [comment]
@jquense Any update on this? Workarounds?

**Comment by shilch** [comment]
Same for me, but for me Safari and Firefox are not working while Chrome does.

**Comment by gigerbytes** [comment]
Had the same problem and found the solution in #253
