### ISSUE TITLE
eventPropGetter for each view

### ISSUE THREAD

**Issue by zunder** [intljusticemission/react-big-calendar#495]
Is it possible to provide the current view information to `eventPropGetter`? I would like to render events differently depending on the view.

**Comment by wasabigeek** [comment]
Could you use the parent's classes?
- Month: `rbc-month-view`
- Week, Day: `rbc-time-view`
- Agenda: `rbc-agenda-view`

**Comment by tobiasandersen** [comment]
If @wasabigeek's suggestion isn't enough, you could store the current view in your state, and keep track of it using the `onView` prop.

**Comment by josh-g3** [comment]
>     * Week, Day: `rbc-time-view`
Am I the only one who sees this as a problem? If they're separate concepts in the views array, why is it assumed they're always going to look exactly the same?
