### ISSUE TITLE
Missing `rbc-now` class

### ISSUE THREAD

**Issue by nadezhda-devlabs** [intljusticemission/react-big-calendar#497]
I want to style only the date number of the current date, but the `rbc-now` class is missing from the `rbc-current` element. If I style by `rbc-current`, then all the dates in every month are styled, for example: 9th August, 9th September, 9th Ocotber etc.

The demo works correctly.

I'm using the latest stable version of the component.

Can you please give me an advice? :)

**Comment by arecvlohe** [comment]
You might have to traverse the DOM for all `a` tags (getElementsByTagName) then filter for the tag whose `textContent` is today's date. Once you have the DOM node you can add styles to it. Kind of a round about way but that's how I would attempt it.

**Comment by jquense** [comment]
we should also fix the missing class.

**Comment by owzzz** [comment]
Is there a fix being worked on for this? I've experienced the same issue.

@arecvlohe Do you have a code example of how you went about traversing the DOM nodes and extracting element based on current date.

**Comment by owzzz** [comment]
I've created a solution, code below:

I created a custom dateHeader Component for the month view. The documentation was not very clear but I figured out that the dateHeader component is the element that is responsible for outputting the date label in a cell.

`const components = {
  month: {
    dateHeader: CellLabel
  }
};`

I then created the CellLabel component

`import React, { Component } from 'react';
import styled from 'styled-components';
import moment from 'moment';


const CellElem = styled.div`
	position: relative;

	a {
		background:	${(props) => props.isToday ? 'black' : 'none'};
		color: ${(props) => props.isToday ? 'white' : 'black'};

    	position: absolute;
    	top: ${(props) => props.isToday ? '-28px' : '-32px'};
    	right: ${(props) => props.isToday ? '8px' : '5px'};
    	display: flex;
    	align-items: center;
    	justify-content: center;
    	width: 30px;
    	height: 30px;
    	border-radius: 15px;
    	text-decoration: none;
	}
`;


class CellLabel extends Component { // eslint-disable-line react/prefer-stateless-function

  render() {
    return (
      <CellElem {...this.props} isToday={moment(this.props.date).isSame(new Date(), "day")}>
      	<a href="#">{this.props.label}</a>
      </CellElem>
    );
  }
}
`;

Fix for `rbc-now` class still needs to be added, but this worked as an interim solution.

**Comment by tobiasandersen** [comment]
This seems to be fixed on latest master (just tried it locally), so I'll go ahead and close it.
