### ISSUE TITLE
Option to fix calendar headers to allow visibility during scrolling. 

### ISSUE THREAD

**Issue by JonEustace** [intljusticemission/react-big-calendar#501]
Similar to Google Calendar, I would like to fix the header of the calendar (for example, days of the week in month view, week view) during scroll. 

![screen shot 2017-08-11 at 1 07 05 pm](https://user-images.githubusercontent.com/2601128/29277377-4f915940-80c6-11e7-9de6-18436f90d9cb.png)

**Comment by JonEustace** [comment]
![](https://files.slack.com/files-pri/T4T80L9MK-F6NMRTZPZ/screen_shot_2017-08-11_at_1.07.05_pm.png)

**Comment by JonEustace** [comment]
![screen shot 2017-08-11 at 1 07 05 pm](https://user-images.githubusercontent.com/2601128/29277353-3db7071a-80c6-11e7-8ddc-14d6796d55df.png)

**Comment by jquense** [comment]
i'd like this option but it is technically challenging to do, and i'm not sure it's worth the added complexity. I'd be open to reconsidering tho if someone added a PR.

**Comment by yash-zorp** [comment]
Is the Sticky header feature added or not?
