### ISSUE TITLE
Cannot run

### ISSUE THREAD

**Issue by Gregorysoh** [intljusticemission/react-big-calendar#502]
Hey, I already followed the steps to download: 

1) I downloaded zip file and unzipped it in documents
2) I ran install npm
3) I went to the directory and typed npm run examples: 

I got the following and I do not know what is wrong! 

npm WARN invalid config loglevel="notice"

> react-big-calendar@0.14.4 clean:examples C:\Users\...\Documents\react-big-calendar-master
> rimraf examples/static

'rimraf' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-big-calendar@0.14.4 clean:examples: `rimraf examples/static`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-big-calendar@0.14.4 clean:examples script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\...\AppData\Roaming\npm-cache\_logs\2017-08-15T05_17_36_422Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-big-calendar@0.14.4 examples: `npm run clean:examples && webpack-dev-server --inline --hot --config webpack/examples.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-big-calendar@0.14.4 examples script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\...\AppData\Roaming\npm-cache\_logs\2017-08-15T05_17_36_476Z-debug.log

**Comment by arecvlohe** [comment]
Did you try install rimraf globally?
