### ISSUE TITLE
Calendar rendering events outside of the defined hours

### ISSUE THREAD

**Issue by stefyrosca** [intljusticemission/react-big-calendar#504]
In my current application I have a configurable calendar where the user can chose the start and end hours for the calendar events to be displayed. That is independent from the creation of events from different sources, so when I create them I don't know which one should be or not displayed. 

I ran into a problem when the user changes the calendar starting hours and there are some events before the selected hour, they are all rendered at the beginning of the day.

![calendar-error](https://user-images.githubusercontent.com/13037099/29359584-e82e1a36-8287-11e7-8462-90103c4c9883.png)

Is this a bug or is there any way I can fix this from the calendar configuration, or should I filter the events every time there is a change?

Currently used version: "react-big-calendar": "0.14.4"
Thanks!

**Comment by stefyrosca** [comment]
Also, if I have an event that starts before the selected start hour and ends after the start hour, it is rendered from the beginning of the day (which is fine), but it renders all the events that were not rendered before and they should not be rendered.

![events-1](https://user-images.githubusercontent.com/13037099/29361624-28f4c6b0-8291-11e7-8af9-2f7ca6c30638.png)
![events-2](https://user-images.githubusercontent.com/13037099/29361625-28fbe418-8291-11e7-8c3e-da3ced80748e.png)

In this example, from one event from 9.00 to 9.30, it renders the shown event from 7.30 and a few more, that are before the 9.00 start hour of the calendar.

**Comment by jquense** [comment]
I'm not sure how to handle a case like this. I would say that ya'll should filter out events you can't display, but showing them on the first slot like we do is not great default behavior either

**Comment by stefyrosca** [comment]
Will do, but in the second example there is an inconsistency in how the events are displayed. Maybe you should check that out? I will make the changes on my part and hope that it doesn't slow down the application too much.

**Comment by tobiasandersen** [comment]
Not sure what the way forward is here. Any suggestions? Is there a reason RBC doesn't filter them out internally?

**Comment by stefyrosca** [comment]
I filtered them manually based on the start and end hours. Not the best approach probably

**Comment by wejden-hadded** [comment]
> I filtered them manually based on the start and end hours. Not the best approach probably

can u show us an exemple of filtered events, please!!!
