### ISSUE TITLE
What does an event object consist of?

### ISSUE THREAD

**Issue by aarohmankad** [intljusticemission/react-big-calendar#506]
The API docs on the website should be updated to include fields that can be present on an event.

**Comment by jquense** [comment]
it can be anything you want, The calendar doesn't what your events look like as long as you tell it how to set the start, end, and allDay state from it using the accessor props

**Comment by aarohmankad** [comment]
In that case, mention the minimum required properties.

would it be able to render images per day on a month view? That is my specific use case.

**Comment by arecvlohe** [comment]
I think he mentions this in the API docs that you just need a start and end date.
> just tell it how to find the start and end datetimes and you can pass it whatever you want.
[startAccessor](http://intljusticemission.github.io/react-big-calendar/examples/index.html#prop-startAccessor)
[endAccessor](http://intljusticemission.github.io/react-big-calendar/examples/index.html#prop-endAccessor)

**Comment by danieljamesross** [comment]
@aarohmankad did you get images to display on events? Might you have an example to share, please?
