### ISSUE TITLE
EventCell needs key props to prevent rendering bug on event component

### ISSUE THREAD

**Issue by AgamlaRage** [intljusticemission/react-big-calendar#507]
On month view, when I add some events to my stream, sometimes the calendar is re-rendering an old event with the new props, instead of rendering a totally new event component.

_Only saw it in my month view.
And said "sometimes" because in my configuration it's not happening on all the cells, sometimes it works, normally. (Mostly happend on the today cell, and the cell that have an event in the same "month line")_

### Solution

I add a **key** props to the [EventCell](https://github.com/intljusticemission/react-big-calendar/blob/master/src/EventCell.js) component. That's all.

For now I used my own events **idAccessor** like this `<EventWrapper event={event} key={event.id}>`

What way would you do this ? 
Adding an **idAccessor** props to the calendar ?

**Comment by tobiasandersen** [comment]
I guess this could happen if a new event has the same start and end time as one that gets removed. I think the idea of an `idAccessor` sounds good. What are your thoughts @jquense?

**Comment by jquense** [comment]
I'm not sure why it's important that event components remount if they're different, there really shouldn't be a lot of mount/unmount logic there I think...

I don't really want to require folks to include id's on events for this, it seems like probably a minor use case and one that can be work arounded fairly easily if you do have this issue

**Comment by tobiasandersen** [comment]
Hm you're right. I can't find any `shouldComponentUpdate` methods in RBC(?), so not sure how this could be a problem?

**Comment by joeyparis** [comment]
Now that hooks are commonplace and they depend on their call order to maintain consistency using keys is now more critical. Can we reopen this issue?
