### ISSUE TITLE
Google Calendar integration

### ISSUE THREAD

**Issue by crashspringfield** [intljusticemission/react-big-calendar#509]
FullCalendar.io allows for users to call from the Google Calendar API and renders the data in a way that it can be displayed on the calendar. I'm currently building this capability with react-big-calendar on a client project and could create a branch for this if you want.

**Comment by jquense** [comment]
That's really cool! Generally we don't want that sort of thing built into the library but I think we already provide all the API's necessary for it to be a standalone addon or wrapper over the core Calendar component. I'd be happy to promote or bump such a project in the docs as a good companion to RBC if you build it!

**Comment by crashspringfield** [comment]
Sounds good. Getting the events is easy....now to writing the recursion logic.

**Comment by simondegheselle** [comment]
+1 for the Google Calendar integration

**Comment by crashspringfield** [comment]
@simondegheselle I'm starting to built [a function](https://github.com/crashspringfield/recurring-google-events) to handle it if you want to try it out and test its capabilities.

**Comment by crashspringfield** [comment]
I built [an implementation for Google](https://github.com/crashspringfield/react-google-calendar), which is basically just using a handful of functions to display events from Google calendars in react-big-calendar.
