### ISSUE TITLE
Change What Day Today Goes To

### ISSUE THREAD

**Issue by FIL1994** [intljusticemission/react-big-calendar#511]
is there a prop that can change what day the today button goes to?

**Comment by FIL1994** [comment]
Or a way to keep the back and next buttons, remove today, and have a custom button?

**Comment by tobiasandersen** [comment]
You can create your own toolbar, and pass that to the `components` prop of the Calendar.

**Comment by FIL1994** [comment]
Thanks for the reply.  I dug through the docs and came up with this:

<image src="https://image.ibb.co/gfip95/image.png"/>

**Comment by tobiasandersen** [comment]
Awesome!
