### ISSUE TITLE
Event shown on top of another Event (hiding the one below)

### ISSUE THREAD

**Issue by sobanhameed** [intljusticemission/react-big-calendar#512]
Version 0.12.3 didn't have this issue. I only see this issue in the latest 0.14.4. Notice that we have are giving events 1-6 (with titles 0 to 5). 4 & 5 are displayed on top of each other. If I do display:none on #5 you will see #4 show up. Attaching the start and end times along with order of events array we are passing. I JSON.stringified it so you guys can easily look at it. Seems like an offset calculation issue.

[json.stringify.txt](https://github.com/intljusticemission/react-big-calendar/files/1232684/json.stringify.txt)

<img width="1190" alt="screen shot 2017-08-17 at 2 28 42 pm" src="https://user-images.githubusercontent.com/5161456/29434626-a7dfafa4-8358-11e7-8c9c-732aa9dc03e4.png">
<img width="1195" alt="screen shot 2017-08-17 at 2 28 54 pm" src="https://user-images.githubusercontent.com/5161456/29434628-a7e0a094-8358-11e7-872f-019dd888c5eb.png">
<img width="1217" alt="screen shot 2017-08-17 at 2 29 17 pm" src="https://user-images.githubusercontent.com/5161456/29434627-a7e0a454-8358-11e7-8c55-21d3526c9e1c.png">

**Comment by sobanhameed** [comment]
We are a bit stuck with this. We can't revert to 0.12.3 as it had other issues. Any help or guidance here will be greatly appreciated.

**Comment by jquense** [comment]
Not sure honestly. We'll get around to looking at it, but the fastest way to get it fixed would be to dig into the code and see what's going one, also css @tobiasandersen

**Comment by tobiasandersen** [comment]
Great catch @sobanhameed, I haven't seen this before. I've narrowed down the problem and have an very rough solution (kind of) working. It'll need a little bit of testing and re-work/cleaning up before we can merge it though. I don't have the time at this moment, but if you can wait, I'll submit a fix in the following days (probably next week).

**Comment by sobanhameed** [comment]
Thanks. Appreciate the help. We are putting a hacky fix at our end to add forced margin to events with matching start and end (not sure if it will cause other issues) but it will be great to have a right fix for this issue (and get a build up on NPM).

**Comment by sobanhameed** [comment]
@tobiasandersen Need your input on the fix we are doing at our side. Is there any way to detect that this is going to happen to some events on rendering? We would like to add some incremental offset to all such events. We attempted setting the incremental offset to all events that have same start date/time but that causes events to unnecessarily bleed out of the calendar rendering area.

Appreciate the help so we can ublock our users.

**Comment by tobiasandersen** [comment]
You can take a look at the changes I've made in [this branch](https://github.com/tobiasandersen/react-big-calendar/tree/fix-day-view-layout), and see if that helps you. I'm currently trying some other ideas as well, but that might take a while (and might not even work out in the end).

**Comment by sobanhameed** [comment]
I looked at the changes. If you would like I can test these changes in our own setup to see if they work fine.

We have put a hack at our end to force add incremental margins when times exactly match for the appointments on the day. Obviously, it's bad and is causing contents to bleed out of the calendar. Will be great to get this fix in as soon as it looks complete and we can help test it.

**Comment by tobiasandersen** [comment]
I think what's in that branch should make it better than what we currently have. But I think it's a bit outdated at the moment.

I'm still working on a new implementation of this, but I went on vacation and haven't touched it in quite a while, until this week when I picked up on it again. Still not sure if/when I'll have anything ready, so I wouldn't count on it.

**Comment by tobiasandersen** [comment]
@sobanhameed could you see if #677 fixes your problems?
