### ISSUE TITLE
Localized Agenda Header Text

### ISSUE THREAD

**Issue by benjamin-wss** [intljusticemission/react-big-calendar#513]
Firstly, this is a really simple to use component for calendars. I need to make the calendar localized in Danish. However, a problem I have is that I cannot seem to replace the headers in the agenda view.

The localizations will localize everything except the headings, which seem to always be 'Date', 'Time' and 'Event'.

Please advise if this is doable. In the short run, this is fine but over the long term, we need to be able to change the text in the headers for agenda view.

Thanks.

**Comment by jquense** [comment]
Hi there. You can change the text via the messages prop it accepts a hash of string for replacing the various bits of text throughout the calendar with your localized messages.
