### ISSUE TITLE
create custom button (i.e. "Staff View") near day, month, week 

### ISSUE THREAD

**Issue by Puneetbh** [intljusticemission/react-big-calendar#514]
I have requirement to display events on calendar based on users. So events will be listed by users.
tried to create custom component but its not working. Also in my custom view i need calendar that will have events and user list come on top where currently we have dates coming. 

Please suggest

```
const testCom = () => {
  return (
    <div>test cale</div>
  );
};


<BigCalendar
          selectable
          events={this.state.appointments}
          defaultView='week'
          scrollToTime={new Date(1970, 1, 1, 6)}
          defaultDate={new Date()}
          components={{
            test: {
              event: testCom,
            },
          }}
          views={{ month: true, week: true, day: true, test: true }}
          onSelectEvent={(event) => this.openDialog(event)}
          onSelectSlot={(slotInfo) =>
            this.openDialog(slotInfo)
          }
        />
```

**Comment by Puneetbh** [comment]
Kindly suggest if this is possible?

**Comment by jquense** [comment]
It's possible, but requires extensive work. There are some existing PRs adding "resource" grouping which sounds like what you are looking for. It's not  done yet tho.

**Comment by Puneetbh** [comment]
@jquense please tell when can I expect this functionality in this, as I have a requirement to display events based on staff.

**Comment by jquense** [comment]
The time line is: when/if It gets done!

**Comment by jquense** [comment]
Feel free to jump into the existing work and help get it done if it's important to you!
