### ISSUE TITLE
Thoughts on adding dragging feature that updates event end time

### ISSUE THREAD

**Issue by arecvlohe** [intljusticemission/react-big-calendar#515]
First off, this is a great library and fulfills a lot of what is needed from a calendar application right out the gate. I was wondering what your thoughts are on adding a feature that allows the user to drag an event to update the end time for it? Example gif from google calendar:

![screen recording 2017-08-18 at 11 30 am](https://user-images.githubusercontent.com/9747933/29465982-29f7ea00-8409-11e7-98e3-53204b47d096.gif)

This would be something I would like to work on if you are interested in implementing it.

**Comment by jquense** [comment]
#406 but we haven't gotten it merged yet :)

**Comment by arecvlohe** [comment]
Awesome! That is great 🙂
