### ISSUE TITLE
Use Case: All Day events only, HELP!

### ISSUE THREAD

**Issue by nosnaj** [intljusticemission/react-big-calendar#520]
![image](https://user-images.githubusercontent.com/1735634/29711404-2ea336d6-89c7-11e7-965f-e3ed90b675be.png)

So I mainly use the calendar for all day events only, and as you can see from the image, only one all day event is shown per cell. How do I get more rows to show up? At least not just 1? Doesn't seem to be a height issue... 

Help much appreciated!

PS. While I'm at it, is there a way to remove timeslots altogether? Since I only use all-day mainly.

**Comment by jquense** [comment]
Seems like you have styling issue, that is preventing the calendar from correctly calculating how many events fit. It looks like maybe you have some height set on them, events should align along the top of the day cell, not the bottom like in your picture

**Comment by nosnaj** [comment]
@jquense, Ah I see, thanks for the pointer. At least now I know where to start looking!

Thanks for the package. Keep up the good work.

**Comment by nosnaj** [comment]
I was able to fix this by setting a specific height on the calendar's container.

Beforehand, I wrongfully added a height to `rbc-date-cell` instead and that created an illusion that the height is OK.
