### ISSUE TITLE
How can I disable Time slots in day view and week view? 

### ISSUE THREAD

**Issue by SilwalUjjwal** [intljusticemission/react-big-calendar#521]

**Comment by jquense** [comment]
You can't, since that is most of the view. You could write a custom view if you wanted too for that

**Comment by SilwalUjjwal** [comment]
Both the day view and week view are based on timegrid and timeslot components, how can I go about creating a view without any time slots in both day and week view just as basicWeek and basicDay options of fullCalendar?

**Comment by jquense** [comment]
Like I said you'd have to write those components, maybe you could leveraging the components used to build the all day row. I'm  out sure what would be involved. It's not something we are planning on adding ourselves though

**Comment by leschekfm** [comment]
We are also looking for that functionality. If someone has implemented a custom view like that I would be very happy if it could be shared here.

**Comment by nikunjmavani** [comment]
Hello,

I found very easy solution for this but it won't work in "Day" view because of hide the rbc-time-content div. 
Just you need to overwrite styling in your app after importing the BigCalendar css as below.

.rbc-time-view {
        .rbc-label {
            display: none;
        }
        .rbc-allday-cell {
            height: calc(100vh - 98px);
            max-height: unset;
        }
        .rbc-time-content {
            display: none;
        } 
    }

Result:

![Screen Shot 2019-03-30 at 5 13 56 PM](https://user-images.githubusercontent.com/40333875/55275735-6c1e0680-5310-11e9-894d-9169663cfe2a.png)

**Comment by matias-herreros** [comment]
It would be like the Month view but with just one row and some minor styling changes

**Comment by kiurious-designco** [comment]
Thank you, this was very helpful. 
I am building a calendar view where it displays the weekly events of the city. If it is organized by timeslots, we'd have many starting at 11PM, and that slot would be cluttered. This way, I just display some custom cards on the day without caring for the time they start and they fill out the full height of day in a much better way.
