### ISSUE TITLE
reading format 'YYYY-MM-DD hh:mm:ss'

### ISSUE THREAD

**Issue by jcabrerazuniga** [intljusticemission/react-big-calendar#522]
Is it possible for react-BigCalendar to output dateTime Values in the 'YYYY-MM-DD hh:mm:ss' format and to read events specifying their start and end using the same date time format ? I need this because this is the format used by mysql (by default),

Thanks
Jose

**Comment by jquense** [comment]
RBC itself needs javascript date objects to work on, but you can convert between the string format and a real date however you like. Doing that is more the job of you api fetch and post logic than it is the component here.
