### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by linginging** [intljusticemission/react-big-calendar#527]
`moment.js:27 Uncaught ReferenceError: require is not defined
    at eval (moment.js:27)
    at Object.<anonymous> (index.js:5758)
    at __webpack_require__ (index.js:556)
    at fn (index.js:87)
    at eval (index.js:19)
    at Object.<anonymous> (index.js:5746)
    at __webpack_require__ (index.js:556)
    at fn (index.js:87)
    at eval (index_teach.js:23)
    at Object.<anonymous> (index.js:13834)`

**Comment by jquense** [comment]
That looks like a problem with your build or webpack setup!

**Comment by feiZhang** [comment]
more file have..
27:var _dates = require('../utils/dates');

only moment error..

why?

**Comment by cyang78** [comment]
I have the same issue. I'm using this component with AntD component. All other reactor components works fine work require

**Comment by cyang78** [comment]
@feiZhang How do you resolve it? Look like I am using moment 2.18.1 on other part of the project, versus the 2.17.1 included by the big-calendar itself, could that be the issue

**Comment by cyang78** [comment]
Making my project to use moment2.17.1 does not solve the issue. @jquense Could you repopen this issue and take a look? Seems at least three people has this issue. Mine was a straight https://ant.design project setup. I like this calendar over antd's own calendar.

**Comment by panta82** [comment]
Check your webpack config. If you followed advice in [this](https://github.com/webpack/webpack/issues/3128) thread, you might have added something like this:

```javascript
  module: {
    noParse: [/moment.js/],
    //...
  }
```

That is supposed to reduce the size of momentjs deployment, but will also screw with any module that has `moment.js` file in it, like ReactBigCalendar for example :)

**Comment by Zakkenroeler** [comment]
I am also trying to use this Calendar with AntD component. I receive the same error. The webpack config shows the following, but nothing seeems out of the ordinary:

`module.exports = function(webpackConfig) {
  webpackConfig.babel.plugins.push('transform-runtime');
  webpackConfig.babel.plugins.push(['import', {
    libraryName: 'antd',
    style: 'css',
  }]);
  return webpackConfig;
};`

Any idea how to get this fixed?
