### ISSUE TITLE
Clicking on cell day number in month view adds 'rbc-current' class

### ISSUE THREAD

**Issue by owzzz** [intljusticemission/react-big-calendar#528]
Hi,

I have a page with two calendars and both of them are showing the same issue.

When I click on the `rbc-date-cell` anchor tag of any cell it adds the`rbc-current` to it. 

Any ideas on how this can be solved?

Experiencing the issue on latest versions of Safari, Chrome and Firefox (Mac)

![screen shot 2017-08-30 at 3 36 03 pm](https://user-images.githubusercontent.com/1162357/29891416-fd43c54e-8d98-11e7-9190-f41d3e52fc33.png)

**Comment by jquense** [comment]
sorry what is the problem to be solved? `rbc-current` (I believe) is the currently selected cell `rbc-now` should represent "today"

**Comment by owzzz** [comment]
It looks like I mixed up the classes. So the `rbc-current` works as expected. 

What I'm trying to do is style the `rbc-now` class but I'm not finding it in the dom.

Temporary link here: https://d2bcd943.ngrok.io

**Comment by owzzz** [comment]
Apologies, The `rbc-current` works as expected, the issue is with the `rbc-now` is not being displayed. I'll close this to avoid confusion.

I added a comment about the `rbc-now` issue raised here: https://github.com/intljusticemission/react-big-calendar/issues/497#issuecomment-325712682
