### ISSUE TITLE
Provide format for time labels in day view?

### ISSUE THREAD

**Issue by felizuno** [intljusticemission/react-big-calendar#53]
Hi, I'm really new to React so perhaps I'm missing something, but it seems like there is no way to use the `formats` config to provide a format for the timestamps on the left hand side of the day view. It defaults to `hh:mm a` but I would like to simply use `hh a` as all our events will start/end at the top of an hour.

Is this already possible and I missed it? Should it be possible?

I looked in the code and didn't see an obvious opportunity to provide a pull request, but would be happy to if you could point me in the right direction :-)

**Comment by jquense** [comment]
Hi there, Yeah you should be able to set it, but I think its missing in the documentaion.

If you use the `formats` prop its `timeGutterFormat` so `formats={{ timeGutterFormat: 'hh a' }}`, should work.Let me know if it doeasn't!

**Comment by felizuno** [comment]
Works like a charm, thank you!
