### ISSUE TITLE
Question - is it possible to render a 5 day (Mon-Fri) month view?

### ISSUE THREAD

**Issue by jhorst11** [intljusticemission/react-big-calendar#531]

**Comment by mcocoba** [comment]
maybe this example can help...

[https://github.com/intljusticemission/react-big-calendar/blob/master/examples/demos/customView.js](url)

**Comment by tobiasandersen** [comment]
As stated by Jason [in this issue](https://github.com/intljusticemission/react-big-calendar/issues/525), it's not possible. But as @mcocoba says, you can create a custom view for it based on the current month view!
