### ISSUE TITLE
Custom views break title formatting

### ISSUE THREAD

**Issue by developit** [intljusticemission/react-big-calendar#537]
Creating a new custom view and exposing it into Calendar via the `views` prop ([as shown here](https://github.com/intljusticemission/react-big-calendar/blob/master/examples/demos/customView.js)) seems to break view label display.

I've worked around this by patching my named view into `lib/Views`:

```js
import Views from 'react-big-calendar/lib/Views';

Views.Year = YearView;
```

It seems like the static Views mapping in `lib/viewLabel.js` is what causes the issue:
https://github.com/intljusticemission/react-big-calendar/blob/136aa09127b19c4dc23d54e1ad82504b7665ad7f/src/utils/viewLabel.js#L25

**Comment by jquense** [comment]
Hmm yeah, I'm gonna guess we haven't noticed because we usually have a custom toolbar when using custom views. There really should be a proper defined interface for these...I'll poke around at it tomorrow

**Comment by developit** [comment]
Awesome, thanks for the quick reply. I'm actually using a custom toolbar - the error is triggered when computing the value of `props.label` that gets passed to it:

https://github.com/intljusticemission/react-big-calendar/blob/0dc141829855d26a13451e71a14c7df84f114f40/src/Calendar.js#L568

Let me know if there's any way I can help, this library is excellent.
