### ISSUE TITLE
Events greater than half hour that are set to 11:30pm go to All Day

### ISSUE THREAD

**Issue by mub33n** [intljusticemission/react-big-calendar#543]
Hi,

While this is a rare case, if you have an event that is an hour or longer, and then drag that event in day view to 11:30pm, it turns that event into an all day event. Is there a way to disable this? As I would like the remaining time for the event to spread over to the next day?

Thanks

**Comment by jquense** [comment]
There is not a way to display events like that at the moment, but there is an effort to add it in #496
