### ISSUE TITLE
Hosting with IIS

### ISSUE THREAD

**Issue by paulyung** [intljusticemission/react-big-calendar#544]
Can you shed some light to host this app in IIS ?  I am able to host it locally with port #3000.  But having problem when hosting in IIS.

Error
warning.js:36 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined.

**Comment by jquense** [comment]
Hi there. RBC isn't an app it's only a single component you can use to build a react app. I'm not honestly sure how you host a react app on IIS but if you build the static assets correctly it should just be a matter of sitting the files in directory and configuring it to serve them. Generally folks use something like webpack to do that, and I beleive there is a whole tool chain for aspnetcore and react.net as well
