### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by adeelarshad83** [intljusticemission/react-big-calendar#545]
Hi

Is there any possibility that we can use hijri calendar instead of Georgian Calendar

 Regards
Adeel Arshad

**Comment by jquense** [comment]
you can adjust the localization used, but i think that probably stops working sort of using a different calendar, given how many assumptions i've probably made in the code about Georgian calendar things (like week length). I'm not really familiar with other cal types so it'd be hard for me to support them but i'd be open to a PR
