### ISSUE TITLE
Turn off dragging for some events

### ISSUE THREAD

**Issue by martinnov92** [intljusticemission/react-big-calendar#552]
Hello,
is there any way how to stop dragging for some events in calendar?
I got some events in the past which I do not to want to move, so I need to turn off their drag event. Is it possible?

Thank you very much

**Comment by jquense** [comment]
D&D uses react-dnd, which i'm not super familar with (i don't really maintain the addon) but i'm sure there is a way to cancel events from it, if you poke around in the docs.

**Comment by dbuchet-bandc** [comment]
Hello there,
Could you uncomment this line https://github.com/intljusticemission/react-big-calendar/blob/master/src/addons/dragAndDrop/DraggableEventWrapper.js#L138 on next release ?

You then just need to add a key 'draggable: true/false' in your event object.

**Comment by aoll** [comment]
Hello there,

Yes you can,

with the  api: draggableAccessor

draggableAccessor={event => true}

https://github.com/intljusticemission/react-big-calendar/tree/master/src/addons/dragAndDrop
