### ISSUE TITLE
Changing color of clicked day slot?

### ISSUE THREAD

**Issue by jonnetanninen** [intljusticemission/react-big-calendar#553]
Is there a convenient way to change the color of the target of onSelectSlot?

I would like to open kind of an editor after clicking a date and highlight the day that is currently selected.

**Comment by jquense** [comment]
there isn't but i'd be open to a PR adding it !

**Comment by aikafourteen** [comment]
Is this problem solved? thanks

**Comment by jquense** [comment]
Not a problem,  a feature request, same holds, I'm open to a PR if you want to add it :)
