### ISSUE TITLE
Styling rbc-row-segment div with rbc-off-range CSS

### ISSUE THREAD

**Issue by Gilks** [intljusticemission/react-big-calendar#557]
I'm working on styling my react-big-calendar. I was able to style off-range days in the month view by adding the following CSS into react-big-calendar.css:

    .rbc-off-range {
    color: grey;
    background-color:rgba(0,0,0,0.4);
    } 

This styles the div correctly. However, I am not able to get the styling to apply to the rbc-row-segment div. The result is this:

![style_not_applied](https://user-images.githubusercontent.com/11075149/30672134-991f1086-9e38-11e7-8864-158f37a1f86e.png)

I would like to apply the rbc-off-range CSS to the applicable rbc-row-segment div(s). Here is the result I am looking for:

![applied_styling_manually](https://user-images.githubusercontent.com/11075149/30672194-ee4cc288-9e38-11e7-984d-e4bb2a201107.PNG)

I did not see any reference to this in the docs. Is this possible with the current version of react-big-calendar? Here's some information on my current environment:

    package versions: 
        node@v6.10.3
        react@15.6.1
        react-big-calendar@0.15.0

**Comment by jquense** [comment]
There isn't really a good way to do this right now, we should add the `rbc-off-range` class to the background cells as well probably

**Comment by jquense** [comment]
added by #499

**Comment by josh-g3** [comment]
The PR above did not address the actual event content not being selectable by this
