### ISSUE TITLE
Show more button is hidden on custom event with line-height property

### ISSUE THREAD

**Issue by sartios** [intljusticemission/react-big-calendar#558]
Steps to reproduce:

I add a custom event component for the month view.
I add css property to the div container of the event, e.g. line-height: 34px;

The show more button disappears behind the date cell.

With line height:

![with-line-height](https://user-images.githubusercontent.com/917573/30696849-af5da0bc-9ee5-11e7-8db5-774383340fdc.PNG)

Without line height:

![with-out-line-height](https://user-images.githubusercontent.com/917573/30696850-af60bbc6-9ee5-11e7-8560-3b2fa4ad883d.PNG)

**Comment by koox00** [comment]
setting a fixed height for `.rbc-event` works for me.
see  #92

**Comment by tobiasandersen** [comment]
Thanks @koox00!
