### ISSUE TITLE
Daylight Savings problem - 2am time slot missing

### ISSUE THREAD

**Issue by pdornier** [intljusticemission/react-big-calendar#56]
First off, love react-big-calendar thanks for all the work you guys have done!
Looks like today's (March 13th) daylight savings time is causing problems in the week view. The 2am time slot isn't rendered at all in the time-gutter (calendar basically skips from 1am to 3am). This problem showed up locally for me but I noticed that it's also happening on the demo page. Theoretically it makes sense that the 2am time slot disappeared (since that hour was skipped) but even when switching between weeks in the calendar the 2am slot doesn't appear.

**Comment by jquense** [comment]
thanks for the kinds words.

I see what you saying, though I had to actually reset my computer date back to march 13. For now at least it seems to be mostly not a problem. But we will look into it!
