### ISSUE TITLE
Step property does not work

### ISSUE THREAD

**Issue by sartios** [intljusticemission/react-big-calendar#562]
TimeGrid always get the default step value.

**Comment by jquense** [comment]
I just tried it it on a few of the examples and it was working. here is set to `60`

![image](https://user-images.githubusercontent.com/339286/31017985-6be606c6-a4f8-11e7-9127-35edcf9bd9bf.png)

**Comment by sartios** [comment]
Yes, but the slots are 30 minutes each. When I click in a slot, for example 12:00 AM, I get back the range 12:00 AM - 12:30 AM. Does step 60 means that I would get back 12:00 AM - 13:00 AM ?
