### ISSUE TITLE
Add double click handler

### ISSUE THREAD

**Issue by AlexMarvelo** [intljusticemission/react-big-calendar#563]
Hello, guys
I think that double click is very common interaction kind among calendars. So it would be useful to have:

1. Handler for double click on an event
2. Handler for double click on an empty cell/empty part of a day cell (to add new event, for example)

What do you think about it?

**Comment by jquense** [comment]
sure, care to submit a PR?

**Comment by AlexMarvelo** [comment]
Yes, in couple of days
