### ISSUE TITLE
Update Event by DnD Either Ends of the Event

### ISSUE THREAD

**Issue by arecvlohe** [intljusticemission/react-big-calendar#564]
A quick question: Does react-big-calendar support adjusting the start and end time of an event by dragging an event on either end in month view? From what I can tell it doesn't. Are you @jquense open to adding this functionality to the calendar? I know that both Google Calendar and iCal do not support this but it is a cool feature.

**Comment by jquense** [comment]
It doesn't support this, i'm not sure i've ever seen this feature do you have an example of something that works like that?

**Comment by arecvlohe** [comment]
Here is an example:

![react-big-calendar-resizing](https://user-images.githubusercontent.com/9747933/31019064-78a37ab6-a4fc-11e7-844f-265768063bbf.gif)

**Comment by jquense** [comment]
o ok, sorry i misunderstood :P We don't have anything but maybe the #406 PR covers it (or could)?

**Comment by arecvlohe** [comment]
Yes, I think it could! I will dig into it some and consolidate this issue with it.
