### ISSUE TITLE
Removing View.range() broke my code

### ISSUE THREAD

**Issue by jhockett** [intljusticemission/react-big-calendar#565]
In my web app, I would use the range function that was apart of day, week, and month.

import Views from 'react-big-calendar/lib/Views';

// this.view and this.navDate come from onView() and onNavigate() props
get range() {
    return Views[this.view].range(this.navDate, {});
}

This no longer works in rbc 0.16.1

Is there a new way to do this going forward? I use the current visible range to generate repeating events on the fly.

**Comment by jquense** [comment]
There isn't anything to replace it at the moment, they were never really public to begin with...I'm open to adding some exposed util functions for getting the current visible range of the calendar tho if you want to PR something
