### ISSUE TITLE
Question - Can you customize number of events per day?

### ISSUE THREAD

**Issue by babycourageous** [intljusticemission/react-big-calendar#566]
hi there

Is there any way to customize the month view so the "+ X more" EventEndingRow component is not used but instead all events for each day show up?

Thank you

**Comment by jquense** [comment]
How many events shown is determined by how many fit. There isn't an option to expand to fit but there was talk about it, at the moment tho it's not an easy change give the complexity of style changes needed

**Comment by babycourageous** [comment]
Thanks for the reply @jquense.

**Comment by guptaji048** [comment]
is there a way i can show max 3 event on a particular date cell and if more than 3 then "+Number of more events" appear?
i want to change the limit of max event from 5 to 3

**Comment by sgarcia30** [comment]
@guptaji048 did you find a work around for this?  I want to do the same thing.

**Comment by RajvirS99** [comment]
I want to do the same thing, except to show 1 event and if there are more events then display show more below the first event
If anyone found a workaround then kindly let me know too!

**Comment by cutterbl** [comment]
@guptaji048 @sgarcia30 @RajvirS99 I would point you all back to @jquense 's comment in this thread, from 2017
