### ISSUE TITLE
How to set time zone correctly the way examples do

### ISSUE THREAD

**Issue by Sihui** [intljusticemission/react-big-calendar#568]
I want to use the user's timezone.

And here is how I do that:

```
import moment from 'moment';
import moment_timezone from 'moment-timezone';

moment.tz.setDefault(Intl.DateTimeFormat().resolvedOptions().timeZone);
BigCalendar.momentLocalizer(moment);
```

Everything works except that now the start time of each day is 5 pm if the user is in PT. I believe that because 5 pm PT is 12 am UTC.

![image](https://user-images.githubusercontent.com/3139206/31066001-82673d68-a6fe-11e7-9205-7aa127f228af.png)

How can I make the calendar starts at 12 am in the user's timezone instead of UTC?
The way the examples do it is exactly what I want.
![image](https://user-images.githubusercontent.com/3139206/31066104-3b648cc6-a6ff-11e7-9122-7a59625ab941.png)

Thanks a lot!

**Comment by jquense** [comment]
You can check out the examples code in the repo here, but we don't actually do anything to set the timezone specifically
