### ISSUE TITLE
Question: Does this react component support Timeline feature (premium feature) of the FullCalendar?

### ISSUE THREAD

**Issue by gam0ny** [intljusticemission/react-big-calendar#569]
https://fullcalendar.io/docs/timeline/

**Comment by jquense** [comment]
we don't have any resource or timeline features at the moment but there are a few PR's adding similar features in the works

**Comment by kiwicopple** [comment]
I don't want to open a new issue if this has been solved - was the PR ever completed for timeline? I can't find it in the docs, only resource view (which is also great!)
