### ISSUE TITLE
Remove popup icon and display all events by increasing cell height accordingly

### ISSUE THREAD

**Issue by araskrj1992** [intljusticemission/react-big-calendar#571]
![more icon](https://user-images.githubusercontent.com/19901353/31121938-b6b2b462-a857-11e7-9b38-f7754fd88c9d.jpg)

I'm facing a problem to remove +more icon of popup and expanding cell or row according to events so that every event can be displayed in the cell itself.
Is it possible with react-big-calendar.

**Comment by jquense** [comment]
It's not possible let right now, see previous issues on the subject

**Comment by paisapoo** [comment]
@jquense  this issue has been fixed? or still not able to do this

**Comment by cutterbl** [comment]
@paisapoo The current behavior is still the same.
