### ISSUE TITLE
PropGetter for slot background

### ISSUE THREAD

**Issue by danbovey** [intljusticemission/react-big-calendar#572]
Hi! I'd like to style the background of a slot based on dates in my app.

It looks like it's possible to provide a custom `dateCellWrapper` but that means keeping all of the functionality of `BackgroundCells` in my app and reimplementing it just to change the `className` of the `.rbc-day-bg` element it renders.

Would it be possible to implement a new propGetter called `slotBgPropGetter` that adds className or style to a month's cell background? You could potentially use `slotPropGetter`'s value and append `-bg` to it - but that's quite opinionated.

**Comment by danbovey** [comment]
Sorry, my bad. `dateCellWrapper` is a wrapper not a replacement of background cells component. Should have seen that in the name... 😨

**Comment by danbovey** [comment]
May still have an issue with custom backgrounds though, as the `cellWrapperComponent` does not receive the style for flex-basis and max-width - so I can't style the wrapper to be the correct width and height.

**Comment by mx781** [comment]
I encountered this issue as well - I initially thought this should be handled by `slotPropGetter` but this I think your approach is the correct one.

I was, however, able to work around this by emulating the behavior that applies flex-basis and max-width, which lives in utils/eventLevels.js:
```js
export function segStyle(span, slots){
  let per = (span / slots) * 100 + '%';
  return { WebkitFlexBasis: per, flexBasis: per, maxWidth: per } // IE10/11 need max-width. flex-basis doesn't respect box-sizing
}
```
`span` is always 1 for months and
`slots` equals `range.length` where `range` is the period you're displaying (which is always 7 for a week, if you only need month view)

Hence `per` is always "14.28571429%" for month view, but you can calculate it as above if you need multiple views.

This is what my wrapper looks like in the end with proper sizing:
```js
const DateCellWrapper = ({ value, children }) => {
    const width = "14.28571429%";
    const style = {
      WebkitFlexBasis: width,
      flexBasis: width,
      maxWidth: width,
      ...otherStylesDepenedingOnDateAndEvents
    };

    return (
      <div style={style}>{children}</div>
    );
  }
```

**Comment by jquense** [comment]
The wrappers can inspect the injected child styles/classes and alter them. Generally wrappers are low level api's for addons so i don't necessarily recommend that but it should work
