### ISSUE TITLE
Upgrade peer dependencies to allow for React v16

### ISSUE THREAD

**Issue by tfuqua** [intljusticemission/react-big-calendar#573]
After upgrading to React v16, rendering the calendar throws an except about multiple copies of react.

> Invariant Violation: Element ref was specified as a string (view) but no owner was set. You may have multiple copies of React loaded. (details: https://fb.me/react-refs-must-have-owner).

Please let me know if I can provide any more information or details. 

Thanks!

**Comment by jeffreyabarrios** [comment]
The same happened after upgrading to React v16, please help!
