### ISSUE TITLE
Render custom component as Event

### ISSUE THREAD

**Issue by tsvetann** [intljusticemission/react-big-calendar#576]
Can somebody point me on how to render a custom component as an event. Ideally, I would like to render different components for different days

Thx in advance

**Comment by jrhalchak** [comment]
All you need is a component or function that uses an event prop.  You can then pass it to the calendar component.

A simplified example of one I started (_I'm using CSS modules_):
```javascript
const MonthEvent = ({ event }) => (
  <div className={event.someProp ? styles.specialEvent : styles.event}>
    <div className={styles.eventTime}>{event.start}</div>
    <div className={styles.eventName}>{event.name}</div>
  </div>
);
```
Then in the calendar just do
```javascript
<BigCalendar
  components={{
    month: { event: MonthEvent },
  }}
/>
```

or if you wanted to use that for all events you could do
```javascript
<BigCalendar
  components={{
    event: MonthEvent,
  }}
/>
```

**Comment by wasabigeek** [comment]
This is my guess from digging the [source](https://github.com/intljusticemission/react-big-calendar/blob/6c517dd41ca2ac0266d2b3a3d5f56affb356975d/src/EventCell.js) - you can basically pass any renderable component. By default, it just shows "title":
```
<div className='rbc-event-content' title={title}>
    { Event
        ? <Event event={event} title={title}/>
        : title
     }
</div>
```

So, passing `components={{event: ...}}` allows you to change the text inside the event. Now as you have control over the `events` prop in `<BigCalendar\>`, you can pass in your own key/values and event titles can be modified depending on those values.

My example with simplified code, where I've added `isBooked` and `noOfPax` key/values to my event objects:
![image](https://user-images.githubusercontent.com/4256705/32895831-56e72616-cb1c-11e7-94c5-722962a3e7be.png)
```
class CustomEvent extends React.Component {
  render() {
    const bookedIcon = event.isBooked ? <Badge><i className="fa fa-bookmark"></i></Badge> : null ;

    return (
      <div>
        <strong>{moment(event.start).format('ha')}</strong> {event.title}
        <span className="pull-right">
          {bookedIcon}
          <Badge>{event.noOfPax} <i className="fa fa-user"></i></Badge>
        </span>
      </div>
    );
  }
}
```

There are two other things you can control:
- `eventPropGetter` lets you change the styling of the event background (the blue portion) by changing CSS classes or adding inline styles ([source](https://github.com/intljusticemission/react-big-calendar/blob/6c517dd41ca2ac0266d2b3a3d5f56affb356975d/src/EventCell.js#L49))
- `eventWrapper`  provides a wrapper around the whole event - I'm not sure why/how one would use this, but it's [there](https://github.com/intljusticemission/react-big-calendar/blob/6c517dd41ca2ac0266d2b3a3d5f56affb356975d/src/EventCell.js#L53).

**Comment by tobiasandersen** [comment]
Thanks @jrhalchak and @wasabigeek!

**Comment by bradeac** [comment]
I am trying to resolve a much simpler problem: displaying just the event title without the event start / end time.

My custom event:
`
export default class CustomEvent extends React.Component {
    render() {
        return (
        <div>
            {this.props.title}
        </div>
        );
    }
}
`

How I use BigCalendar:
`
import CustomEvent from './CustomEvent';

<BigCalendar
                        selectable
                        events={this.props.bookingsList}
                        components={{
                            event: CustomEvent,
                        }}
                        defaultView="week"
                        defaultDate={moment().toDate()}
                        min={moment('2018-02-23 09:00:00').toDate()}
                        max={moment('2018-02-23 19:00:00').toDate()}
                        onSelectEvent={event => //some code}
                        onSelectSlot={slotInfo => //some code}
`
The event box still has the start / end time.
Quite a newbie here, so I'm not figuring out what I'm doing wrong. Any help woul be appreciated. Thanks

**Comment by jrhalchak** [comment]
@bradeac This site is more for issues with the library itself (bugs/improvements).  Your question would do better over on stackoverflow.

Just from glancing at it, you're using `this.props.title`, I believe the prop that gets passed to the event component is just `event` so you'd want `this.props.event.title`.  Although it looks like you're passing a different component so I'm not sure why it would display otherwise.

**Comment by bradeac** [comment]
That's exactly why I commented on an already closed issue, because it's more of a question instead of a bug.

True, it should be ```this.props.event.title```. But this is not the problem. The problem is that the time range is still displayed, even though ```{this.props.event.title}``` is the only thing displayed by the custom component.

**Comment by bradeac** [comment]
Maybe some else needs this behaviour. The fix is to modify the CSS:
```
.rbc-event-label {
  display: none;
}
```

**Comment by tomwalters** [comment]
@bradeac You can remove the time range using the [`formats`](http://intljusticemission.github.io/react-big-calendar/examples/index.html#prop-formats.eventTimeRangeFormat) prop:

```
<BigCalendar
  formats={{ eventTimeRangeFormat: () => null }}
/>
```

**Comment by schevall** [comment]
quick fix if someone need,
.rbc-time-content {
  display: none;
}
.rbc-time-view {
  flex: none;
}

**Comment by rdalfonso** [comment]
Is there a way to pass props from the parent component that creates the BigCalander into the custom Event component? I'd love the ability to change the each individual event.title when the user clicks the event.title

**Comment by FatjonRrapaj** [comment]
Hello, I'm veeeery late to the party, but here's a demo on how you can change the styles of the EventWrapper.
I'm using tailwind but I believe you can use whatever you like.


`const EventWrapperComponent = ({ event, children }: any) => {
  const newChildren = { ...children };
  const newChildrenProps = { ...newChildren.props };
  newChildrenProps.className = `${newChildrenProps.className} outline-none border-none  bg-red-500`;
  newChildren.props = { ...newChildrenProps };

  return <div>{newChildren}</div>;
};
`
For any adittional modification, just log the children props, copy the object, make the necessary modifications on the class name, (you have the event for your conditions) and replace it on the newChildren object you're passing.

 ```
<BigCalendar
      components={{
        eventWrapper: EventWrapperComponent,
      }}
    />
```

**Comment by mourabitiziyad** [comment]
> All you need is a component or function that uses an event prop. You can then pass it to the calendar component.
> 
> A simplified example of one I started (_I'm using CSS modules_):
> 
> ```js
> const MonthEvent = ({ event }) => (
>   <div className={event.someProp ? styles.specialEvent : styles.event}>
>     <div className={styles.eventTime}>{event.start}</div>
>     <div className={styles.eventName}>{event.name}</div>
>   </div>
> );
> ```
> 
> Then in the calendar just do
> 
> ```js
> <BigCalendar
>   components={{
>     month: { event: MonthEvent },
>   }}
> />
> ```
> 
> or if you wanted to use that for all events you could do
> 
> ```js
> <BigCalendar
>   components={{
>     event: MonthEvent,
>   }}
> />
> ```

This part doesn't seem to work. But allowing the custom element to be applied over all views can ruin the styling in the month view for instance.

 ```js
 <BigCalendar
   components={{
     month: { event: MonthEvent },
   }}
/>
```
However, this is a potential work-around to control the card style depending on the view it is being looked from:

```js
const EventComponent = ({ event }: any) => (
 <div>
  <div>{ parent.document.querySelector('.rbc-month-view') ? 'Month View' : 'Nope' }</div>
 </div>
);
```
Then applying EventComponent here:

```js
components= {{
   event: EventComponent,
}}
```

As you can see, the text changes depending on the view:
Month View:
<img width="400" alt="image" src="https://user-images.githubusercontent.com/60394642/192103906-d0313ba2-6d64-4b80-9e3e-72c5c75a78f9.png">
Week View:
<img width="400" alt="image" src="https://user-images.githubusercontent.com/60394642/192103934-8048ee04-9ae8-47c6-9a15-32dffeff3c94.png">

If there are better work-arounds other than setting a `max-height` property (something like what follows), please do let me know.
```CSS
.rbc-month-view {
  .rbc-month-row {
    .rbc-event {
      max-height: 1.5rem;
    }
  }
}
```

**Comment by cutterbl** [comment]
@mourabitiziyad A few things here

This works fine
```
components={{
  month: {event: MyMonthEventLayout}
```

**Comment by lcim** [comment]
Hi everyone,
Thanks in advance. Is there a way one can edit calendar event (change start or end) without using DragAndDrop? I wish one can help me with a code please

**Comment by cutterbl** [comment]
@lcim This question is better asked in our Slack `#general` channel, of on StackOverflow.
