### ISSUE TITLE
IE 11 missing polyfill

### ISSUE THREAD

**Issue by david-mart** [intljusticemission/react-big-calendar#579]
I recently updated to a newer version and now IE 11 is broken. Even the demo page on your website is not loading - looks like it's missing a polyfill of `Object.assign`

![image](https://user-images.githubusercontent.com/20728627/31301169-e591728a-aaac-11e7-8e7c-1d5bbdd59971.png)

**Comment by hlehmann** [comment]
Same issue, worth using `babel-plugin-transform-runtime` ?

**Comment by anissaSanadtech** [comment]
Same issue, are there any updates regarding this ticket ?

**Comment by anissaSanadtech** [comment]
You can use `es6-shim` until the issue is fixed

**Comment by hlehmann** [comment]
@jquense Did you change something ? I just made the update and there is still a `Object.assign(...)` in `lib/index.js:35`.

Can you add `babel-plugin-transform-runtime` in your `.babelrc` ?

It would be much smaller if we don't have to include `es6-shim`.

**Comment by vinitkumar** [comment]
I have no errors in the console and the calendar doesn't gets rendered at all. Not sure what is going wrong. I am using the latest version of the plugin `0.17.0`. Does anyone else have this issue too on IE 11?

**Comment by bmueller-sykes** [comment]
In IE11 with 0.19.0 on their examples page, I get `Object doesn't support property or method 'assign'`. That's almost certainly a polyfill issue.

**Comment by bmueller-sykes** [comment]
Actually, to add a little more to the story. Because my project contains `babel-polyfill`, RBC works in IE11 for me. So it would appear (perhaps obviously) that as long as you have the necessary polyfills somewhere in your project, it'll work. What's weird is that their examples *don't* have the polyfills.
