### ISSUE TITLE
popup example not working on your example website

### ISSUE THREAD

**Issue by laitang2000** [intljusticemission/react-big-calendar#58]
Popup example not working on your example website/

**Comment by jquense** [comment]
not sure what you mean there, its working fine for me.

**Comment by ppiekarczyk** [comment]
:wave: Hey, I'm having this same issue.

Where is `+x more` located? Maybe I'm misunderstanding how this is supposed to work?

Thanks!

**Comment by jquense** [comment]
![show-more](https://cloud.githubusercontent.com/assets/339286/14024599/467831b2-f1c0-11e5-8d00-01b34f4e6440.png)

**Comment by ppiekarczyk** [comment]
Thanks for the quick reply! Here's what I'm seeing:

![image](https://cloud.githubusercontent.com/assets/1211905/14024619/ff770160-f1b7-11e5-836b-6b896074788a.png)

**Comment by ppiekarczyk** [comment]
After some digging around, it looks like the css is different from what's in the examples? Could there may be a possibility that github !== npm ?

**Comment by ppiekarczyk** [comment]
Also, I'm using Chrome Canary

**Comment by ppiekarczyk** [comment]
Setting an explicit height on `BigCalendar` 

eg:
```
<BigCalendar
  style={{height: 800}}/>
```

fixes this issue :)

**Comment by jquense** [comment]
It only shows a link if you can't see all the events for a day. Your screenshot has plenty of room, so there is no more to see.

Shrink the window and you'll see them
