### ISSUE TITLE
How do I copy events on certain days - showing demo of what I want to do

### ISSUE THREAD

**Issue by silentarrowz** [intljusticemission/react-big-calendar#580]
I have created a demo of what I'd like to do using react big calendar and would appreciate it if you could tell me how it can be done or give me a link to the instructions for doing this.
here's the video
![calendar](https://user-images.githubusercontent.com/16062099/31314055-c0b04ab4-ac13-11e7-9597-a58f6d80901f.gif)

**Comment by tobiasandersen** [comment]
Hi! You'd have to implement this yourself outside of the calendar. Please see these issues for some more info: https://github.com/intljusticemission/react-big-calendar/issues/355, https://github.com/intljusticemission/react-big-calendar/issues/51.

**Comment by silentarrowz** [comment]
Ok, is it possible to select a certain slot programatically. I have thought of an idea and  knowing this would help me implement it.

**Comment by arjamizo** [comment]
this might be useful for those finding this issue being just closed a little bit disappointing when implementing your own way https://github.com/ClickerMonkey/dayspan
