### ISSUE TITLE
Current time indicator

### ISSUE THREAD

**Issue by RamanKhakhlou** [intljusticemission/react-big-calendar#583]
Hi,

Is there any way to hide current time indicator (green line for week view) or only with usage of css?

**Comment by tobiasandersen** [comment]
You can style is using its classname: `.rbc-current-time-indicator`

**Comment by RamanKhakhlou** [comment]
I see. But may be you can add some additional setting to decide show it on not, cause this control is not always necessary?

**Comment by jquense** [comment]
There isn't right now, happy to take a PR adding a toggle though if you want to send one over :)

**Comment by Wgil** [comment]
It would be cool to have a `currentTimePropGetter` prop. Is still there any interest in this? I can open a PR if you want. @jquense

**Comment by nomrik** [comment]
@Wgil @jquense There is interest! It is needed for my usage too. Currently we have to employ css for this, but would be great to have a prop.

**Comment by abir-hasan-by** [comment]
is there a solution for this, or is it still the same
