### ISSUE TITLE
Drag-and-drop issuse

### ISSUE THREAD

**Issue by vasilevich** [intljusticemission/react-big-calendar#587]
## There is an issue with the drag and drop addon.
in basic calendar
when you click on a day number like this:
![image](https://user-images.githubusercontent.com/1217224/31667891-610b5c8c-b359-11e7-9f39-6c34763af9ad.png)

it goes to the Day time of that particular date:
![image](https://user-images.githubusercontent.com/1217224/31667923-7468c1fc-b359-11e7-934e-0110800867b0.png)

this feature does not seem to work in drag-and-drop,
the day number is unclickable.
![image](https://user-images.githubusercontent.com/1217224/31667961-906026b6-b359-11e7-8c6e-14dc90c08cc5.png)

this seems not to happen unless you add drag/drop.

I suspect the reason for that is, because the cell is being overidden not properly in [here](https://github.com/intljusticemission/react-big-calendar/blob/master/src/addons/dragAndDrop/index.js#L76).

## and while you are at it, may I suggest an useful feature in my opinion:
in addition to providing a "onEventDrop" event, please provide, "onEventDrag" and "onEventMove" which is activated after the drag, and sends x/y etc, durning movement. this will let us create more visually appealing drag and drop functionality.

thank you so much for your hard work!
good luck!

**Comment by jquense** [comment]
Does seem like a bug, unfortunately we don't provide great support for addons since they are community donated. AS such the best way to get it fixed is to summit a patch :)

**Comment by vasilevich** [comment]
Dear jquense.
While I agree that this is a community addon and I will definetly try to provide a patch for this bug.
in my opinion you should leave the case open until fixed so that the community is aware and can recognize the bug, since. because even tho it is a community addon it is still a part of the codebase(in the same repository). please consider leaving the issuse open or maybe it should be a sub-git of the relevant repository rather than the code direcctly.
just an opinion.
regardless thank you for your time and best of luck.

**Comment by vasilevich** [comment]
I made a simple fix:
