### ISSUE TITLE
Last row of events in month view not rendered correctly

### ISSUE THREAD

**Issue by peterdivvito** [intljusticemission/react-big-calendar#592]
I noticed that sometimes the last events for a day in the month view are not rendered correctly.
 
![calendarscreenshot](https://user-images.githubusercontent.com/29786286/31799698-0d74f380-b57f-11e7-8028-d28bb56c4cd7.jpg)

I tracked this down to DateContentRow not passing on the start and end accessors to EventEndingRow.

I'll try and create a pull request to fix this when I get a chance.

Thanks

**Comment by tobiasandersen** [comment]
I take it that this is solved by https://github.com/intljusticemission/react-big-calendar/pull/593. Feel free to re-open otherwise!
