### ISSUE TITLE
minDate and maxDate not exist

### ISSUE THREAD

**Issue by vitaliybilous** [intljusticemission/react-big-calendar#595]
Hello dev and contributors! 
I can't find props for setting max and min date (not time).
Maybe, someone can present some fix for this issue for own fork.
Also, as I understand, U don't realize this feature by own reasons.
Do U can explain this moment?

**Comment by jquense** [comment]
Yes they do not exist. the reason is just that i haven't had any need for that behavior. I'm happy to take a PR adding it tho
