### ISSUE TITLE
Having more than 3 elements in month view

### ISSUE THREAD

**Issue by dbrrt** [intljusticemission/react-big-calendar#596]
Is that possible to have more than 2 element in the monthly view rather than `1 row + x more` when there are more than 2 events per day? Like disabling this feature if a specific prop is passed to the component?

**Comment by jquense** [comment]
It'll show as many rows as fit in the space. There is no feature to disable truncating tho, you can check back issues for the reason why

**Comment by dbrrt** [comment]
Ok, thanks
