### ISSUE TITLE
Request: Mini-month view

### ISSUE THREAD

**Issue by wmertens** [intljusticemission/react-big-calendar#597]
For date selectors etc it would be nice to have a mini month view, where events take up the entire day cell, sharing it for multiple events on the same day.

Selection would be limited to per-day, and to make a year calendar you'd just render multiple mini-months.

**Comment by jquense** [comment]
you have an example of what that might like?

**Comment by wmertens** [comment]
Something like ![year calendar](http://www.efgboston.org/uploads/4/5/5/8/45581957/published/calendar-2017-2018-ptitsbouts-v3.jpg?1501705803)

**Comment by wmertens** [comment]
To show multiple events on one day, maybe use a striped pattern with the event colors? Like https://css-tricks.com/stripes-css/

And the text color can be decided with e.g. tinycolor2 library, if a color is dark, use white foreground.

**Comment by jquense** [comment]
ah I see yeah. I want to try and keep RBC fairly focused on the big calendar/scheduler use case, tehre are a few other libraries that can meet this need, personally i use http://jquense.github.io/react-widgets/api/Calendar/
