### ISSUE TITLE
Week view customization

### ISSUE THREAD

**Issue by araskrj1992** [intljusticemission/react-big-calendar#601]
Can I customize the week view in which the week comes on the left and the time where the week is seen?
![screenshot 18](https://user-images.githubusercontent.com/19901353/32156803-86494750-bd65-11e7-8324-6af9775115e7.png)
right now the view is like above diagram
can somebody please provide a good suggestion for this

**Comment by jquense** [comment]
There isn't any way to configure this with the built in components, but RBC allows custom views, you might be able to put something together to meet your apps needs

**Comment by RusselFourteen** [comment]
@jquense hey brother is there any way to make Apr 12- 18 like Apr 12-18 2018?

**Comment by araskrj1992** [comment]
You can pass custom component for the toolbar where you can handle that by passing the date.

**Comment by RusselFourteen** [comment]
Oh thanks ;)

**Comment by mahadihpu** [comment]
### Custom Week View

I have need the week view to be based on People not hours. It will show who is assigned on that week

**Is there a way , i can do this?**

**Comment by halilguler** [comment]
> ### Özel Hafta Görünümü
> Saatlere değil, İnsanlara dayalı hafta görünümüne ihtiyacım var. O hafta kimin atandığını gösterecek
> 
> **Bunu yapabilmemin bir yolu var mı?**

+
