### ISSUE TITLE
cant get any display??

### ISSUE THREAD

**Issue by robbiemilejczak** [intljusticemission/react-big-calendar#602]
I'm attempting to integrate this into my app but I cannot get any visuals and I'm really not sure what I'm doing wrong.

I'm not sure if this is an actual issue with the code or an issue with the documentation (though I strongly suspect the former). I have an array of 170 objects, I specify the startAccessor and endAccessor properties to correspond to the date properties of the objects, and I get nothing. 

To clarify, I see the controls for the calendar, I have the css imported, but there is no grid for the month view let alone any actual data displaying. Here is my render code:

`<BigCalendar
          events={this.state.events}
          endAccessor='time_started'
          startAccessor='time_ended'
          />`

I have this placed directly beneath my import statement

`BigCalendar.setLocalizer(
  BigCalendar.momentLocalizer(moment)
);`

When the time_started and time_ended properties are moment objects, I get a console error upon selecting "week" (but not on render):

`TypeError: date[("get" + method)] is not a function`

When the time_started/time_ended properties are formatted date strings ("YYYY-MM-DDTHH:MM:SS") I get no errors. Neither of these provide any display. I'm not sure what to do so I'm hoping I can get some direction, even if this technically isn't an "issue". Thanks

**Comment by robbiemilejczak** [comment]
Okay so I sort of got it working? I had to explicitly set a height for the calendar (is there any chance this can be set to happen automatically? sort of a silly waste of an hour that the calendar just didn't have the correct display height...) and I also had to change the time_started, time_ended properties to be start and end, the calendar defaults.

But now there is only a single date (10/30) that contains ALL the events. It says 169 more (there are 170) and nothing else. When I click to change the view I get the `TypeError: date[("get" + method)] is not a function`

What am I doing wrong? Am I missing something in the docs?

**Comment by jquense** [comment]
Yes you need to set the height of the calendar explicitly (per the documentation). Unfortunately it can't be done automatically. In addition your start and end dates need to be Date objects not string. You can preprocess your events array or use a function for start and end accessors to do it on the fly

**Comment by robbiemilejczak** [comment]
@jquense  ah I see, I missed that. Maybe add setting the height in the examples? I didn't see it.

I've got everything working now mostly (I already am preprocessing my events array so that was pretty easy to add in) but I am still getting the error `TypeError: date[("get" + method)] is not a function` when I try to click an individual event or change the view to week/agenda. What is causing that? My accessors are correct and they contain moment objects

**Comment by jquense** [comment]
> [...] and they contain moment objects

Sorry, they have to be `Date` objects, not moment wrappers, the error is occurring because the calendar is trying to call date specific methods, e..g `date.getHours()` and its failing because its not a date

**Comment by robbiemilejczak** [comment]
oooooooooooh okay! thank you so much for your help
