### ISSUE TITLE
Month view not show calendar.

### ISSUE THREAD

**Issue by frankdavidcorona** [intljusticemission/react-big-calendar#603]
Hi, I'm using this component but when I show the **month** view the calendar don't show only works the rest of views and I do not see any error on my dev tools.
Here it's my code on render function from my component of React:

`<BigCalendar
                {...this.props}
                selectable
                defaultView='week'
                events={events}
                views={allViews}
                step={60}
                defaultDate={new Date(2015, 3, 1)}
                onSelectEvent={event => console.log(event)}
            />`

**Comment by tobiasandersen** [comment]
Have you set an explicit height to the calendar's container?

**Comment by frankdavidcorona** [comment]
@tobiasandersen Just that, thanks.

**Comment by rdalfonso** [comment]
@tobiasandersen @frankdavidcorona - I cannot get the month view working. Everything else works great. My code below:
import React, { Component } from 'react';
import moment from 'moment';
import events from './events';
import BigCalendar from 'react-big-calendar';
import 'react-big-calendar/lib/css/react-big-calendar.css';

BigCalendar.momentLocalizer(moment);

let allViews = Object.keys(BigCalendar.Views).map(k => BigCalendar.Views[k])

class Dashboard extends Component {


    render() {

      return (
        <div style={{ height: `100%` }} className="sitter-dash--details">
            <BigCalendar {...this.props}
                electable defaultView='week'
                events={events}
                views={allViews}
                step={60}
                defaultDate={new Date(2015, 3, 1)}
                onSelectEvent={event => console.log(event)}
                />
        </div>
        )
    }
}

export default Dashboard;

**Comment by alphakennyn** [comment]
@rdalfonso You height shouldn't be relative `%`. Try another unit (`px`,`vh`, ...)
