### ISSUE TITLE
Issue in displaying event in Week view and Day View

### ISSUE THREAD

**Issue by bansalritesh18** [intljusticemission/react-big-calendar#605]
I have created an event with start date **11/01/2017 05:30 PM** and end date **11/02/2017 02:00 AM**. This event is being displayed in the all-day row for both dates in week view and day view. Instead, the event should be displayed in main parts of the calendar (in the date column for both dates) if the duration of the event is not more than 24 hours.

**Comment by tobiasandersen** [comment]
Have you tried setting `showMultiDayTimes` on the calendar?

**Comment by tobiasandersen** [comment]
I'll close this for staleness.
