### ISSUE TITLE
How to style events in week/month view

### ISSUE THREAD

**Issue by buddythumbs** [intljusticemission/react-big-calendar#608]
Hi,

Super lib btw - really appreciate what you have done here!

Sorry for asking possible already answered question.

I am providing a custom event and toolbar via:

```
                        components={{
                            event: this.Event,
                            eventWrapper: EventWrap,
                            toolbar: CustomToolbar,
                            agenda: {
                                event: this.EventAgenda
                            },
                            week: {
                                event: WeekEvent
                            }
                        }}
```

And this works well - however I want to style the container of the Event. As you can see I have the EventWrap component defined but there is another wrapper between that and the event (the container of the event time and description, also the container containing the styles).

How can I style this container? 

I am looking for an example if possible.

I did see in another issue someone trying to style an EventCell but I don't see the api allowing to input EventCell ???

**Comment by jquense** [comment]
The EventPropGetter prop

**Comment by buddythumbs** [comment]
Could you expand on that please?

I provide the following on init:

```
eventPropGetter={(event,start,end,isSelected)=>{
                            return className?: string, style?: Object
                        },
```

And return either a className or style object based on whatever logic I choose based on event?

**Comment by jquense** [comment]
yup

**Comment by buddythumbs** [comment]
You wouldn't have an example of it in use for custom styling would you?

**Comment by buddythumbs** [comment]
Got it:

```
const eventStyles = {
    event: {
        backgroundColor:'#1C7DDB',
        color: 'white',
        borderRadius:0
    },
}

...

eventPropGetter={(event,start,end,isSelected)=>{
    return {
        style: eventStyles.event
    }
}}
```
