### ISSUE TITLE
Show events in UTC

### ISSUE THREAD

**Issue by zavernutiy** [intljusticemission/react-big-calendar#61]
Hello, I have a question. Is it possible to show events in UTC time, and not in local? I want events to be at the same date and time no matter where the user is from.
I was making quite hacky code to neglect the timezone offset `date.setMinutes(date.getMinutes() + date.getTimezoneOffset())`, but because of this I have a problem with Daylight Saving Time. I've got all events shifted on 27 March. But all other events, before and after 27 of March are good.
So if possible, please give me a hand with my problem, either it is a solution for showing UTC dates or DST shift.

**Comment by jquense** [comment]
how you handle the dates is up to you, Big-Calendar just lays them out. Under the hood you are just using normal Javascript Date objects, so if you dates are all in UTC time then the calendar will display them as such.
