### ISSUE TITLE
Exposing view type to eventStyleGetter

### ISSUE THREAD

**Issue by asaf** [intljusticemission/react-big-calendar#613]
Hey,

Changing event background color is done via `eventPropGetter` but styles the event in all views (I'd like to replace the 'blue' background of the event in the _Month_ view but not having a background in the _Agenda_ view)

If it makes sense, we can expose the 'view' in `eventPropGetter` so event can be styled differently per view.

Thanks.

**Comment by tobiasandersen** [comment]
I think you have all the data you need to accomplish this available already. If you're using css, you can target the specific view using e.g. `.rbc-month-view .rbc-event`. And if you're js styles, you could keep track of the current view yourself using the `view` and `onView` props , and then pass styles accordingly. 

Having said that, I guess it would be possible to add this to the eventPropGetter as well, but I'm not sure it's worth it? cc @jquense

**Comment by jquense** [comment]
yeah I think if you need track this by view, the controlled props suit that use case reasonably well already
