### ISSUE TITLE
onSelectSlot callback is called instead of onSelectEvent (sometimes)

### ISSUE THREAD

**Issue by remituveri** [intljusticemission/react-big-calendar#614]
Sometimes, clicking on an event will execute the onSelectSlot callback (instead of onSelectEvent)
This is caused by the document.elementFromPoint (in isEvent function of Selection.js) which will return the span contained in the rbc-slot-selection div...
Removing the following code from DayColumn.js fixed that issue but I'm not sure 100% that it's the better way to do it. rbc-slot-selection does not seems to be used

&& _react2.default.createElement(
        'div',
        { className: 'rbc-slot-selection', style: style },
        _react2.default.createElement(
          'span',
          null,
          _localizer2.default.format(selectDates, selectRangeFormat, culture)
        )
      )

**Comment by jquense** [comment]
Sorry folks I can't reproduce on the examples, perhaps it was inadvertently fixed recently

**Comment by arximughal** [comment]
@jquense it's not fixed I guess. I am facing the same issue! 
It's on the demo page as well! 
**Reproduce:**

* Go to [DEMO](http://intljusticemission.github.io/react-big-calendar/examples/index.html)
* Navigate to the **Selectable** event tab
* Click on the events there

Events in **all day** group seems to be working just fine. But the events underneath aren't working! 
Click a couple of times on different parts of the events e.g., Click on Time, Click on any place other than the title...

The solution by SamHurne in https://github.com/intljusticemission/react-big-calendar/issues/630 seemed to have fixed the issue previously. But we updated the package recently and that fix is not working either!

**Comment by arximughal** [comment]
![rbc](https://user-images.githubusercontent.com/8762441/39239195-99119e68-4899-11e8-9e03-4f294ebcdf13.png)
@jquense the issue occurs on some events in different scenarios!

**Comment by noagani** [comment]
I had this problem. Resolved it very simple: I gave the event class z-index:999 so when clicking an event it will catch the event and not the slot below.

**Comment by llewellyn1411** [comment]
This issue is still happening for me. 

@noagani that fix did not work for me

**Comment by arximughal** [comment]
@noagani that was the first thing I tried. Did work for sometime. But recently, after upgrading to the latest version, the `z-index` stopped working for me.

**Comment by ash-PS** [comment]
Also still happening for me.
