### ISSUE TITLE
Bug with DST

### ISSUE THREAD

**Issue by Tommy10802** [intljusticemission/react-big-calendar#616]
Hello, thanks for great library, but i have one little problem :/

Step to reproduce:
1. Open your example demo http://intljusticemission.github.io/react-big-calendar/examples/index.html#prop-eventPropGetter

2. choose selectable demo page

3. select day view

4. with 'back' button on calendar navigate into Sunday Mar 29 which is the day when DST is applied ( 2:00 -> 3:00)

5. scroll on down and 11pm is not renderend right

<img width="1350" alt="screen" src="https://user-images.githubusercontent.com/543195/32599086-bb14e11e-c53b-11e7-895a-21a683d59a42.png">

**Comment by arecvlohe** [comment]
Is this a bug in the current version?

**Comment by jquense** [comment]
Probably, I have a PR up to address this I think

**Comment by klinskyc** [comment]
@jquense There still appears to be an issue with this for both display, and drag on November 4th. 
Is there an open PR, we can merge in to resolve this?
If we wanted to fix this on our end, what would be the right file to look into

**Comment by quyphan** [comment]
Seems like there is still a DST issue; in this case; November 4th.

Issue related to this: #1083, I elaborated more and put in a screen shot to demo it.

**Comment by anna-kartynnik** [comment]
@klinskyc have you seen #1044 and corresponding fix in PR #1046? I can't reproduce the original issue (with the date when DST starts) but you mentioned November 4th, the date when DST ends in California, for example, so maybe the mentioned fix will help you too.
