### ISSUE TITLE
Hiding Time

### ISSUE THREAD

**Issue by lomo009** [intljusticemission/react-big-calendar#617]
Is there any way to hide the Time column in Agenda? As well as the Time values in the Day, Week, and Work Week views? If not, this would be a nice feature.

**Comment by jquense** [comment]
what would be the point of the Day, Week, and Workweek views if you don't show the time?

**Comment by gpascale** [comment]
It would be very useful for me. All of my events are all-day events so I have no concept of start and end times.

I'd essentially like to have a week view that is exactly the same as the month view, except only 7 days and each day is larger. I could use this to show more data for each event.

**Comment by jquense** [comment]
#673

**Comment by gtnx** [comment]
Same here. Would be very useful

**Comment by stevomcnevo** [comment]
Likewise

**Comment by cosst** [comment]
Not the cleanest solution but this has worked for me in terms of manipulating the formatting to hide the time parts (also only care about all-day stuff):

.rbc-time-content, .rbc-time-header-gutter {
    display: none !important;
}

.rbc-time-header {
    height: 650px;

    .rbc-time-header-content {
        border-left: none;
    }
}

.rbc-allday-cell {
    min-height: 637px;
}

(my calendar's set height is 700px)
