### ISSUE TITLE
Custom view component connected to redux

### ISSUE THREAD

**Issue by buddythumbs** [intljusticemission/react-big-calendar#620]
Hi, I have a list view which looks like below and I want to make this a custom view:

![image](https://user-images.githubusercontent.com/24975408/32827336-b44862b4-c9e3-11e7-8aba-bee1f2df722a.png)

The problem I am encountering (and this goes for the custom toolbar I have also) is that I don't know how to connect my component to the redux store as well as receive props from the calendar.

At the moment the component is a standalone component and is working fine with redux, however when I pass it into the calendar as a custom view (iso `agenda`) as follows

```
views={{ month: true, week: true, day: true, agenda: TimeWriting }}
```

the props available are : 

views={{ month: true, week: true, day: true, agenda: TimeWriting }}
![image](https://user-images.githubusercontent.com/24975408/32827478-3fa38c76-c9e4-11e7-992b-27e26538d8c4.png)

Is it possible to pass in extra props to the custom view component?

And an extension of this is; is it possible to pass in extra props to the custom toolbar component?

great library by the way!

**Comment by tobiasandersen** [comment]
Hi, please have a look at https://github.com/intljusticemission/react-big-calendar/issues/623, I believe you're asking the same thing here!
