### ISSUE TITLE
Rerender the calendar when events has changed

### ISSUE THREAD

**Issue by dantudor** [intljusticemission/react-big-calendar#621]
I would expect the calendar to rerender when the events have changed.

This my render function:
```
return (
    <div id="schedule">
        <h1>Schedule</h1>
        <BigCalendar toolbar events={this.state.dates} />
    </div>
);
```

I have an event logged in the componentDidMount function:
```
scheduleStore.on("updated", () => {
    this.setState({
        dates: scheduleStore.getAll()
    });
});
```

Even though the component state changed and the events are populated from the state then component doesn't render any new events.

I've considered `this.forceUpdate()` but even then the calendar doesn't refresh.

Any help appreciated

Edit: If I `setState({dates: null})` then it will update, but not if I just add a new event to the array.

**Comment by tobiasandersen** [comment]
How are you updating the events? The calendar will re-render if the `events` prop changes.

**Comment by jquense** [comment]
Yeah there is no logic preventing updates in the calendar, no shouldComponentUpdate. It will rerender any time the parent does. I'd check you don't have something preventing updates in your code

**Comment by dantudor** [comment]
Thanks for the replies. I've realised why it wasn't updating. 

The new event object was incorrectly formatted and therefore ignored by the calendar.
