### ISSUE TITLE
allDayAccessor is not enough to stop rendering events in all day section

### ISSUE THREAD

**Issue by snozal** [intljusticemission/react-big-calendar#622]
Hi,

In the TimeGrid component, when determining if an event is an all day event, even though my allDayAccessor returns always false since I don't want to display events in that section, there is another condition that includes the events as all day events that can't be controlled via props:

(dates.isJustDate(eStart) && dates.isJustDate(eEnd))

Could this be modified in order to get the result of the allDayAccessor function passed to the component?

https://github.com/intljusticemission/react-big-calendar/blob/6c517dd41ca2ac0266d2b3a3d5f56affb356975d/src/TimeGrid.js#L167

Thanks.

**Comment by jquense** [comment]
There are a few past issues that cover why this is and how you can handle it, please see them thanka
