### ISSUE TITLE
I need to get each timeslots as a components

### ISSUE THREAD

**Issue by simonescob** [intljusticemission/react-big-calendar#625]
i am building a system with your calendar but i need to get the timeslots for active a modal

**Comment by jquense** [comment]
The select slot event is called with the time slots

**Comment by simonescob** [comment]
But how do i take this and transform it to component?

**Comment by simonescob** [comment]
Do i call to TimeSlots.js?

**Comment by tobiasandersen** [comment]
I'm not sure I get your question @simonescob. Do you think you could explain a bit more what you're trying to achieve?

**Comment by arecvlohe** [comment]
This issue is pretty old and inactive. I am going to close.
