### ISSUE TITLE
Question - Is it possible to use the week view as timetable only?

### ISSUE THREAD

**Issue by petersonsc** [intljusticemission/react-big-calendar#627]
I'm trying to use the week view as a timetable, but a can't disable the current date.

**Comment by eschreiner** [comment]
You could override the class `.rbc-today` like so:

```
.rbc-today {
  background-color: #fff;
}
```

**Comment by tobiasandersen** [comment]
As @eschreiner said, you should be able to hide everything related to "today" using css. If that's not what you're asking for, feel free to re-open :)
