### ISSUE TITLE
Drag & Drop Calendar dateCellWrapper

### ISSUE THREAD

**Issue by svanetten1976** [intljusticemission/react-big-calendar#629]
Hi, great component you have built here. Just wanted to point out that I discovered a small bug, in which the drag & drop implementation of the calendar does not recognize custom dateCellWrapper components. Works fine when using the non-draggable BigCalendar component, but not when using the DragAndDropCalendar component. One other quick question, I was looking at the changelog and it appears as though you'd intended for the onSelectSlot callback to report double click events. I am using Big Calendar version 17.0 and I can report that the slotInfo object that comes back only reports a 'click' action, not a 'doubleClick' action. Thanks -- Steve

**Comment by arecvlohe** [comment]
This looks to be fixed in #716
