### ISSUE TITLE
Month / Agenda View not working when copying demo from example

### ISSUE THREAD

**Issue by ppiekarczyk** [intljusticemission/react-big-calendar#63]
Hey!

Great work on this!

One of my biggest issues I'm trying to debug right now is that the `month` and `agenda` views aren't working with the basic example data you have on your site.

I've supplied a gif so you could see what I mean. It looks like the issue has to do with a `min-height: 0` property, but I wonder if I'm doing something wrong?

![calendar](https://cloud.githubusercontent.com/assets/1211905/14024221/37688f82-f1b6-11e5-8cd7-0312ce068986.gif)

Thanks again

**Comment by ppiekarczyk** [comment]
For the `agenda view`, `.rbc-agenda-view` has `overflow: auto`. Removing this class fixes it.

**Comment by ppiekarczyk** [comment]
For `month view`, everything works surprisingly well if I remove the entire `rbc-month-view` class

**Comment by jquense** [comment]
You need to set an explicit height on the calendar in general.

**Comment by ppiekarczyk** [comment]
Hey, that did it! Thank you.

**Comment by rdalfonso** [comment]
@peterpme - I'm seeing the same issue: For month view, everything works surprisingly well if I remove the entire rbc-month-view class

How did you solve this?

" set an explicit height on the calendar in general."---is height a property of BigCalendar or did you solve it by adding the height to the outer div?

<div style={height:100X}>
            <BigCalendar
                electable
                defaultView='week'
                events={events}
                views={allViews}
                step={60}
                defaultDate={new Date(2015, 3, 1)}
                onSelectEvent={event => console.log(event)}
                />
        </div>

**Comment by rdalfonso** [comment]
I can only get this working when I edit the react-big-calendar/lib/css/react-big-calendar.css and remove the flexbox code from rbc-month-view.

``` 
.rbc-month-view {
  position: relative;
  border: 1px solid #DDD;
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
  -webkit-flex-direction: column;
      -ms-flex-direction: column;
          flex-direction: column;
  -webkit-flex: 1 0 0;
      -ms-flex: 1 0 0px;
          flex: 1 0 0;
  width: 100%;
  -moz-user-select: none;
   -ms-user-select: none;
       user-select: none;
  -webkit-user-select: none;
  height: 100%;
}```
I can only get this working when I edit the react-big-calendar/lib/css/react-big-calendar.css and remove the flexbox code from 

``` .rbc-month-view {
  position: relative;
  border: 1px solid #DDD;
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
  -webkit-flex-direction: column;
      -ms-flex-direction: column;
          flex-direction: column;
  -webkit-flex: 1 0 0;
      -ms-flex: 1 0 0px;
          flex: 1 0 0;
  width: 100%;
  -moz-user-select: none;
   -ms-user-select: none;
       user-select: none;
  -webkit-user-select: none;
  height: 100%;
}```

      -ms-flex: 1 0 0px;
          flex: 1 0 0;
  width: 100%;
  -moz-user-select: none;
   -ms-user-select: none;
       user-select: none;
  -webkit-user-select: none;
  height: 100%;
}
```

**Comment by CyrusZei** [comment]
Just add this to your `index.css` file

```
.rbc-agenda-view {
  overflow: unset;
}
.rbc-month-view {
  display: block;
}

```
