### ISSUE TITLE
Bug with selecting events in Chrome

### ISSUE THREAD

**Issue by eschreiner** [intljusticemission/react-big-calendar#630]
When trying to select an existing event in Chrome, a new event is created instead.

As indicated by the popups on the Demo page:

- the error occurs most of the time when clicking on the left part of the event (title or background)
- sometimes works fine when clicking close to the right border
- works fine in FireFox (also when clicking on the background)
- full day event selection seems to work fine

### Steps to reproduce:

Open the official Demo page in Chrome, navigate to 'Selectable' and click on an event.

**Comment by eschreiner** [comment]
related to #614

**Comment by SamHurne** [comment]
I just encountered this same problem, and although it's probably not ideal, I was able to sort of fix the issue by increasing the z-index of `.rbc-event`:

```css
.rbc-calendar .rbc-event {
  z-index: 11;
}
```

It looks like by default, the `.rbc-slot-selection` css class has a z-index of 10 in the css, while the `.rbc-event` has a z-index of 2.

I haven't spent enough time to know if this is really the best solution, but it fixes the issue for me.

**Comment by jquense** [comment]
Sorry folks I can't reproduce on the examples, perhaps it was inadvertently fixed recently

**Comment by paw-e-l** [comment]
Bug is still present, but i find it hard to reproduce. One user using Chrome can't click any event (instead selects slot every time), but on the other hand I am using the same version of chrome and don't have any problems.

**Comment by shundy** [comment]
@jquense This issue is happening in chrome on **Windows**.
But isn't happening in chrome on **MacOS**.
