### ISSUE TITLE
Some border alignment issues

### ISSUE THREAD

**Issue by queicherius** [intljusticemission/react-big-calendar#631]
I know it's a super tiny nit-pick, but the "all day" row in the daily and weekly view doesn't correctly line up with the other rows :(

![fldkv6b 1](https://user-images.githubusercontent.com/4615516/33498533-9bb85f22-d6c9-11e7-9876-01ea89b0319e.png)

**Comment by tobiasandersen** [comment]
Should be fixed by #669, please give it a try!

**Comment by queicherius** [comment]
Oh wow, I didn't expect it to get in so fast, can confirm the PR fixes it. Thanks!
