### ISSUE TITLE
Event is set to all day, when it happens between 2 days

### ISSUE THREAD

**Issue by emarques** [intljusticemission/react-big-calendar#632]
When a event starts at some time in day 1 and continues to following day, the event will be set to an all day event.

You can reproduce this here:
http://intljusticemission.github.io/react-big-calendar/examples/index.html#
- Go to Drag and Drop
- Select to view the weekly schedule
- Move the Birthday Event on Monday to 11PM
- The event will be set to an all day event

**Comment by jquense** [comment]
yes, this is intentional, there are some past issues on this, and at least one PR to add an option to change the behavior if you want to

**Comment by tobiasandersen** [comment]
Isn't this what you're looking for? http://intljusticemission.github.io/react-big-calendar/examples/index.html#prop-showMultiDayTimes

**Comment by emarques** [comment]
Oh nice, that's exactly what I wanted! Should have read the documentation better 😅

Thanks for the help guys

**Comment by frederic117** [comment]
sorry but the link is broken and i have the same problem : an event like this one :{
    "start": "2023-08-07T21:55:00.000Z",
    "end": "2023-08-07T22:08:00.000Z",
    "title": " -  Travail - départ : La Confluence, Lyon, France - arrivée : Gare de Lyon Part-Dieu",
    "id": "6727741002",
    "hasDriver": true
} is set to all day, when it happens between 2 days and it doesn't display the hours
Thank in advance for any help :)
