### ISSUE TITLE
Custom Agenda View Header

### ISSUE THREAD

**Issue by valentinmirchev** [intljusticemission/react-big-calendar#633]
First of all, awesome project! 👍 🏆 

Is it possible to remove columns from the table header, and respectively the content from the table for the agenda view?

Thank you.

**Comment by tobiasandersen** [comment]
Hi! Nope, but you can create a custom view for it!

**Comment by guptaji048** [comment]
@tobiasandersen I tried doing that, but getting error 'View.title is not function'. Please help

**Comment by redimongo** [comment]
would like to see this too.

**Comment by cutterbl** [comment]
@redimongo There is an example of a [Custom View](https://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/examples--example-9) in our documentation.
