### ISSUE TITLE
Current timeslot indicator does not update if page is left open

### ISSUE THREAD

**Issue by sciyoshi** [intljusticemission/react-big-calendar#636]
The [time indicator updating code](https://github.com/intljusticemission/react-big-calendar/blob/483534f2798e66c46550af3da7c572624baa63e0/src/TimeGrid.js#L431) manually changes the position of the indicator, but doesn't re-render the component or change the [`now` prop which is set by default at page load time](https://github.com/intljusticemission/react-big-calendar/blob/483534f2798e66c46550af3da7c572624baa63e0/src/TimeGrid.js#L79). This leads to the issue below if the page is left open:

![screen shot 2017-12-05 at 3 30 39 pm](https://user-images.githubusercontent.com/39950/33629253-5b1b2084-d9d1-11e7-8cf8-0784a9861769.png)

My suggestion would be to remove the repositioning code entirely, relying on React to do that instead, put `now` as state instead of as a prop, and simply calling `setState()` in the timeout.

**Comment by jquense** [comment]
the time indicator logic doesn't use `props.now` and isn't supposed to, nor is it supposed to change it. I'm not sure why you say it doesn't update...

**Comment by sciyoshi** [comment]
@jquense the time indicator (the green bar in my screenshot) updates correctly. This bug is about the "current timeslot" indication not updating accordingly (you can see 2pm is bolded in my screenshot since it has the `rbc-now` class). I would expect `3pm` to become bolded once the time rolls over, unless I'm misunderstanding the purpose of that indication.

**Comment by jquense** [comment]
ah ok, no, that doesn't update. I'm not too concerned about that as you can provide the value of `now` yourself, Potentially we could auto update it if it's not passed in, but it's not high on the priority list, if you want to take a stab at it.

**Comment by jquense** [comment]
fixed by #707
