### ISSUE TITLE
Changing the background color of `EventCell`

### ISSUE THREAD

**Issue by ppiekarczyk** [intljusticemission/react-big-calendar#64]
Hey, 

Thanks again for your quick responses. 

Is there a way to edit the `EventCell` component as well as the event?

I would like to color-code events depending on the type of event I've got. I can update `Event`, but `EventCell` still applies the blue background color.

My other option is to edit the css, which I don't mind, but I'd figure I'd ask :)

Thanks again

image: 
![image](https://cloud.githubusercontent.com/assets/1211905/14025122/71f740a4-f1ba-11e5-8dc2-b616833f15f0.png)

**Comment by jquense** [comment]
http://intljusticemission.github.io/react-big-calendar/examples/index.html#prop-eventPropGetter

to set a class or style on the whole event object
