### ISSUE TITLE
React big calendar weekly view not working correctly

### ISSUE THREAD

**Issue by Less97** [intljusticemission/react-big-calendar#643]
Hi guys,

I want to say that I love this component. It's very good. I have a problem with it though. In particular I can't make it work for the montly view (that I would actually be more keen to have in my calendar). It seems that all the heights and the rows are 0 and I have no idea why. I've loaded correctly the react-big-calendar css. and I'm using bootstrap 3.3.7 in the project. 

Any ideas? [here the image](https://ibb.co/dEwzHw)

**Comment by tobiasandersen** [comment]
Hi, you have to set an explicit height on your container, [from docs](http://intljusticemission.github.io/react-big-calendar/examples/index.html#api):

> note: The default styles use height: 100% which means your container must set an explicit height (feel free to adjust the styles to suit your specific needs).

**Comment by Less97** [comment]
Sorry, I hadn't realised that. my fault. Thanks a lot for the quick reply.
