### ISSUE TITLE
Customize day item in month view

### ISSUE THREAD

**Issue by Daavidaviid** [intljusticemission/react-big-calendar#644]
Hi,
I'd like to be able to customize day container but couldn't find how to do that yet...
I tried by supplying a dayWrapper to the components props, but it didn't seem to work.
Here's an example of what I'm willing to do, the circle I drawn are representating pictures that I'd like to be displayed for each day.

![capture d ecran 2017-12-14 a 10 45 54](https://user-images.githubusercontent.com/32457364/33986161-0b1d5b72-e0bd-11e7-8678-e6a5dd44b152.png)

So if you have any idea that would be great thanks!

**Comment by medslt** [comment]
+1

**Comment by dokicoder** [comment]
I second that

**Comment by Daavidaviid** [comment]
I made it and made a pull request https://github.com/intljusticemission/react-big-calendar/pull/646

**Comment by tobiasandersen** [comment]
You can use the `dateHeader` component prop for this:
```
<BigCalendar
  components={{
    month: {
      dateHeader: (props) => (
        <div>Custom Date Header</div>
      )
    }
  }}
/>
```

**Comment by RusselFourteen** [comment]
@tobiasandersen @jquense is there any way to make Apr 12-18 like Apr 12-18, 2018? I cant figure it out. Thanks

**Comment by jquense** [comment]
Use the message props

**Comment by hzb-imasine** [comment]
Is there any similar props for week view and day view?

**Comment by pitops** [comment]
@hzb-imasine you can use header instead of dateHeader

```
components={{
        week: {
            header: CustomDateHeader
        }
      }}
```

**Comment by adirzoari** [comment]
@pitops  @alansutherland @hzb-imasine  how to do custom header for day view?

**Comment by guptaji048** [comment]
@jquense @alansutherland is there a way we can the number of dates shown in month view? Right now month view has 5 rows consisting of 7 dates each, can i reduce it to 4 or 3 rows???

**Comment by cutterbl** [comment]
@chrysillo In the [components prop](http://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/props--components) documentation. I think that's a comprehensive list. Especially used in conjunction with the various [formats props](http://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/props--formats)
