### ISSUE TITLE
Customize the Hour range

### ISSUE THREAD

**Issue by kweisamx** [intljusticemission/react-big-calendar#645]
Hi, I want to use the calendar only show the hour from 10.am to 10.pm , and how can I to set this,
I see the doc and still don't know how to do,
Thanks

**Comment by andela-koni** [comment]
@kweisamx You can set a min and max property on the calendar. See here http://intljusticemission.github.io/react-big-calendar/examples/index.html#prop-min

**Comment by onikehinde** [comment]
@kweisamx You can set a min and max property on the calendar. See here http://intljusticemission.github.io/react-big-calendar/examples/index.html#prop-min

<Calendar min={time} max={time} />

Is this what you are looking for?

**Comment by jquense** [comment]
Yup the min and max props are the way to go, thanks!

**Comment by syang** [comment]
>    min={new Date(2017, 10, 0, 10, 0, 0)}
>    max={new Date(2017, 10, 0, 22, 0, 0)}

How should I interpret the above lines? Why do we have `2017, 10, 0` if we are in 2019 calendar year (but it still seems to work)?

**Comment by Mohelmy7070** [comment]
min={new Date(0, 0, 0, 10, 0, 0)}
max={new Date(0, 0, 0, 22, 0, 0)}

you can set your range time as you see and it will work, too

**Comment by KaushikKondu** [comment]
Hi, How Can I make the Time Intervals from 1hr to Half an hour. 
Example: 
Now we get 10pm-11pm. but I want 10pm-10:30pm

**Comment by RainbowGiantSquid** [comment]
Add prop step with value 30 to your Calendar component.

```
<Calendar
   step={30}
   ...
/>
```

**Comment by p-sreekanth** [comment]
In the react-big-calender, in the week view, it is showing on top bar with resources and under it, week days, and on left side hourly time slots with 1 hour gap.

I want to have a functionality such that, when i click week view, on top bar only resources should display, and left side, instead of time slots, i want to display week days with dates. and not repeating for each resource.

**Comment by Anila-keren** [comment]
Hi in my react calendar I want to deactivate the following time slots( 10h15 - 10h30 and 13h30 - 14h30 ) how can i do it please
