### ISSUE TITLE
Display day view with horizontal time scale?

### ISSUE THREAD

**Issue by eschreiner** [intljusticemission/react-big-calendar#647]
Hi, is it possible to display the day view with a horizontal time scale?

**Comment by jquense** [comment]
not out of the box, buy you can probably put together a custom view to do it if you so desire

**Comment by eschreiner** [comment]
OK, will give it a try. I'll come back to you once I have something to show...

**Comment by HartiganHM** [comment]
@eschreiner Have you had any luck with putting something together for a custom view? I'm working on a similar problem and thought I'd check. Otherwise, I'll be working on this and can post if I come up with a viable solution.

**Comment by eschreiner** [comment]
@HartiganHM  No, sorry, no time yet.

**Comment by rajanmagar** [comment]
@jquense Yes we can do that with css but not possible to manage event position on calendar.
