### ISSUE TITLE
showMultiDayTimes rendering wrong - top and height aren't set

### ISSUE THREAD

**Issue by liron00** [intljusticemission/react-big-calendar#648]
I have an event that goes from Fri 15/12 10:00pm to Sat 16/12 at 3:00am. I did showMultiDayTimes={true} and this is how it's rendering:

![image](https://user-images.githubusercontent.com/699733/34065864-7290661a-e1bb-11e7-85b2-c3ca4aa48fdd.png)

**Comment by tobiasandersen** [comment]
Could you see if this was fixed by https://github.com/intljusticemission/react-big-calendar/pull/677? :)

**Comment by mikeyc7m** [comment]
seems fixed to me
