### ISSUE TITLE
Multiple events at the same time

### ISSUE THREAD

**Issue by zackify** [intljusticemission/react-big-calendar#649]
If multiple events are in the same time slot, only the top most one shows, and the others are rendered under it on the day view.

**Comment by tobiasandersen** [comment]
That sounds like a bug, but the examples page seems to be working. Can you post a screenshot, along with the events data?

**Comment by zackify** [comment]
<img width="1021" alt="screen shot 2017-12-18 at 9 43 53 am" src="https://user-images.githubusercontent.com/449136/34111535-ff89d60a-e3d7-11e7-92e0-c0decbf84fee.png">
<img width="909" alt="screen shot 2017-12-18 at 9 43 49 am" src="https://user-images.githubusercontent.com/449136/34111536-ff952578-e3d7-11e7-9ba4-cb12b021658b.png">

I was thinking maybe its a css issue, but the percentages are all the same

**Comment by zackify** [comment]
![image](https://user-images.githubusercontent.com/449136/34111790-bc1b9eca-e3d8-11e7-8c36-94624da71037.png)
here's the data, had to delete sensitive stuff lol

**Comment by sandysandajan** [comment]
I also encountered the same issue that the events overlap when the time slots are the same.  Awaiting for reply from the developers.

**Comment by jquense** [comment]
@zackify can use actually paste the cleaned events that cause the issue so we can copy it here? Or just put something together we can run

**Comment by zackify** [comment]
yeah ill try to make a little CRA demo soon

**Comment by jquense** [comment]
Thanks!

**Comment by zackify** [comment]
1. create-react-app cal
2. npm install react-big-calendar moment
3. Paste code below into App.js
4. npm start

```import React, { Component } from 'react';
import moment from 'moment';
import BigCalendar from 'react-big-calendar';
import 'react-big-calendar/lib/css/react-big-calendar.css';
BigCalendar.momentLocalizer(moment);

class App extends Component {
  render() {
    return (
      <div>
        <BigCalendar
          popup
          events={[
            {
              end: new Date('2017-12-27T21:45:00.000Z'),
              patient_id: 1,
              selectable: true,
              start: new Date('2017-12-27T21:45:00.000Z'),
              title: 'test',
            },
            {
              end: new Date('2017-12-27T21:45:00.000Z'),
              patient_id: 2,
              selectable: true,
              start: new Date('2017-12-27T21:45:00.000Z'),
              title: 'test 2',
            },
            {
              end: new Date('2017-12-27T21:45:00.000Z'),
              patient_id: 3,
              selectable: true,
              start: new Date('2017-12-27T21:45:00.000Z'),
              title: 'test 3',
            },
          ]}
          defaultView="agenda"
          onSelectEvent={({ patient_id }) => console.log(patient_id)}
          startAccessor="start"
        />
      </div>
    );
  }
}

export default App;```

Go to the day view for december 27. All events are right on top of each other.

@jquense

**Comment by zackify** [comment]
Oh by the way awesome work on this component, you all are great :)

**Comment by sandysandajan** [comment]
Do you have any update regarding this issue?

**Comment by jquense** [comment]
Nope I'm on vacation

**Comment by tobiasandersen** [comment]
I've fixed this on my local branch (along with some other stuff). I'll let you know once the PR is ready!

**Comment by sandysandajan** [comment]
@tobiasandersen what is the fix for this bug?

**Comment by smandell** [comment]
@tobiasandersen I'm dying to know what 'more google-like' means. Any chance you could post a before-after of day view so we could get a preview?

**Comment by tobiasandersen** [comment]
@smandell I think the visual changes should be quite subtle, but you can try for yourself now with https://github.com/intljusticemission/react-big-calendar/pull/677. It'd be really helpful if people could help testing with their own data and report back!

**Comment by jquense** [comment]
should be fix on master, gonna try and get a release out

**Comment by zackify** [comment]
Anyway you could post back here when it's released since it's fixed but not out?

**Comment by Nageswaran-1997** [comment]
if events date and time is same, events showing multiple time in week and day view, but in month view showing a one event first another events are showing using more button, so i need same more button login in week and day view also.

Can any one help me to fix this issue?
