### ISSUE TITLE
How to custom View different have header title not format is date and have multiple header title ???

### ISSUE THREAD

**Issue by ProjectSVN** [intljusticemission/react-big-calendar#650]
Hi Admin,
I did build one component has use react-big-calendar. I want to header of em will name different day name and number header not fix.
Thanks,

**Comment by tobiasandersen** [comment]
Sorry I'm not sure what you ask here. Can you try to explain it a bit further?

**Comment by tobiasandersen** [comment]
I'll close this for now, but please re-open if you have more info to add!
