### ISSUE TITLE
Droping over itself, does not fire trigger onDrop. 

### ISSUE THREAD

**Issue by sergioshev** [intljusticemission/react-big-calendar#656]
Hello guys.
   We are using your calendar in our project and running in an issue. If I drag and drop an event over itself onDrop trigger is not fired. I tried adding z-index: -1 in react-big-calendar/lib/addons/dragAndDrop/styles.css with no luck. In all other cases the calendar is working ok.

Could you helpme figure out what is gooing on?

**Comment by tobiasandersen** [comment]
It seems to be working for me on the example site, could you show the problem using e.g. http://recordit.co/ or in a [codesandbox](https://codesandbox.io/s/l9jwl0kj6m)?

**Comment by arecvlohe** [comment]
I know what this issues is:

<a href="https://cl.ly/203w1n2J2U3n" target="_blank"><img src="https://dha4w82d62smt.cloudfront.net/items/0O0G3a2V3k0g1T3Q2c1l/Screen%20Recording%202018-01-12%20at%2005.23%20PM.gif" style="display: block;height: auto;width: 100%;"/></a>

**Comment by jquense** [comment]
what's the status on this one?

**Comment by arecvlohe** [comment]
I think there is a somewhat simple way to handle this on resize. I will try and take a stab at it this weekend.

**Comment by arecvlohe** [comment]
Deployed in #724
