### ISSUE TITLE
i18n on selectable Time and Views 

### ISSUE THREAD

**Issue by VincentSim** [intljusticemission/react-big-calendar#657]
Hi all,

Thanks for your amazing work.
Have you any idea how to change 'Today, prev, next' and 'agenda, week, month' with appropriate i18n translation ?

Or for a first try how to change 'Today, prev, next' text :)

Thanks,

Vincent

**Comment by arecvlohe** [comment]
Looks like you can pass a `messages` prop with the localizations you want to provide.

http://intljusticemission.github.io/react-big-calendar/examples/index.html#prop-messages

**Comment by crystal1990** [comment]
can you tell me how to localize "+ more" in month view ,

**Comment by jquense** [comment]
Messages also. That's where all text is customized

**Comment by VincentSim** [comment]
thanks all 👍 
Here is the syntax when you are setting your BigCalendar in React : 
```js
<BigCalendar
  events={events}
  startAccessor='startDate'
  endAccessor='endDate'
  defaultView='week'
  culture='fr'
  messages={{'today': "Aujourd'hui", "previous":'précédente', "next":"suivante"}}
/>
```

**Comment by adved85** [comment]
https://github.com/intljusticemission/react-big-calendar/issues/274

**Comment by AdrianoGuzzo** [comment]
All syntax...
`<BigCalendar
  events={events}
  startAccessor='startDate'
  endAccessor='endDate'
  defaultView='week'
  culture='fr'
  messages={{ date: 'Date',
        time: 'Time',
        event: 'Event',
        allDay: 'All Day',
        week: 'Week',
        work_week: 'Work Week',
        day: 'Day',
        month: 'Month',
        previous: 'Back',
        next: 'Next',
        yesterday: 'Yesterday',
        tomorrow: 'Tomorrow',
        today: 'Today',
        agenda: 'Agenda',
        noEventsInRange: 'There are no events in this range.',
        showMore: function(e) {
          return '+' + e + ' more'
        }}}
/>`
