### ISSUE TITLE
the style of week view that contain today is error 

### ISSUE THREAD

**Issue by crystal1990** [intljusticemission/react-big-calendar#659]
![image](https://user-images.githubusercontent.com/20199753/34401299-f934a758-ebd4-11e7-9df2-3596d77dbf7d.png)
![image](https://user-images.githubusercontent.com/20199753/34401324-2a6fb9a2-ebd5-11e7-9192-8d68ade17865.png)

who meet this problems? and  how you resolve it

**Comment by crystal1990** [comment]
the line is not correct in the second image

**Comment by tobiasandersen** [comment]
If you could post the events data, or create a minimal reproducible example on [codesandbox](https://codesandbox.io/s/l9jwl0kj6m) it would be a lot easier to debug!
