### ISSUE TITLE
how can i realize locales of  'more' in   month view 

### ISSUE THREAD

**Issue by crystal1990** [intljusticemission/react-big-calendar#660]
![image](https://user-images.githubusercontent.com/20199753/34401932-58f91594-ebd9-11e7-85c4-616c2e87c04d.png)

How can i show ”更多” instead of ”more”？

**Comment by jquense** [comment]
https://intljusticemission.github.io/react-big-calendar/examples/index.html#prop messages the showMore property specifically :)
