### ISSUE TITLE
Toolbar Too Wide

### ISSUE THREAD

**Issue by chrishud2011** [intljusticemission/react-big-calendar#662]
I get the same behavior as discussed in issue #405 . The toolbar does not adjust size for small screens past the point where it can compress empty space. This depends upon the number of items in toolbar. For example, On the docs website using google chrome and the basic table, the toolbar overflows on screens smaller than 650.

<img width="413" alt="screen shot 2017-12-29 at 1 05 03 pm" src="https://user-images.githubusercontent.com/32603777/34449131-1567af46-ec99-11e7-9a9b-1fa1e9c14a81.png">

**Comment by jquense** [comment]
Yeah, it's not super responsive right now. I'd happily take a PR improving
