### ISSUE TITLE
In month view, if the "+more" not show,how can i get the detail of schedule in day view? 

### ISSUE THREAD

**Issue by crystal1990** [intljusticemission/react-big-calendar#665]
![image](https://user-images.githubusercontent.com/20199753/34476790-e93ec614-efce-11e7-916f-c27a69aa2929.png)
![image](https://user-images.githubusercontent.com/20199753/34476845-54037814-efcf-11e7-849e-b1533e793baa.png)

We know, if we click "+more ",we can jump to the day view to see the detail of the schedule lists.but how can I see the detail of every day's schedule lists in month view if they do not have “+ more”

**Comment by jquense** [comment]
Clicking the date also navigates to the day view. There are also handlers for when an event is clicked, you can do whatever you like then as well (like switch views or show a pop up)
