### ISSUE TITLE
Create sample of JSFiddle

### ISSUE THREAD

**Issue by dtmunir** [intljusticemission/react-big-calendar#667]
## Problem

This is an amazing calendar plugin. But currently, there's a lot of work required to experiment with it, including setting up a local app and configuring all the plugins before you can actually mess with it.

## Proposed Solution

Set up a sample on JSFiddle.net or Codepen.io showing basic use of the calendar. This could be forked by anyone looking to experiment. This should drive up the adoption of the calendar quite a bit since a lot of people will be able to tinker with it. You could even take the existing demos and post them on JSFiddle

**Comment by tobiasandersen** [comment]
I don't think it's possible to create a jsfiddle or codepen with the current build(?), but here's a codesandbox: https://codesandbox.io/s/l9jwl0kj6m. I'll add this to an issue template @jquense, and you can do what you want with it :)
