### ISSUE TITLE
Bug: date ranges are not presnted consistently (e.g. 2 day events sometimes show as 1 and etc).

### ISSUE THREAD

**Issue by tasn** [intljusticemission/react-big-calendar#680]
#### Do you want to request a *feature* or report a *bug*?

Bug

#### What's the current behavior?

An event sometimes spans a few days, sometimes spans one day, with the same range and depending on the day of the week.

I assume, looking from the demos, that an event from 1/1/2018-1/1/2018 is one day, and 1/1/2018-2/1/2018 is two days. However it's not the case. It changes depending on the day of the week, year and really just inconsistent all around.

Code sandbox: https://codesandbox.io/s/vlyl9q93y

I put two calendars there. Look at events "A" and "B". Both are the same range (but a different month/year). One shows as a 3 day event, the other as 2.
Then look at C and D. Both show as 2 days although one is 1 day the other is 2. Then look at E which should be 2 days but is 1.
Even if I misunderstood (wasn't obvious from the docs) what are the expected ranges for allDay events, the inconsistencies are still there, and they are not very predictable.

**Note:** I removed the moment locale setting from the sandbox because it was causing issues in the sandbox, but I have it in my local example and it's still broken.

Versions are like in the codesandbox. React: 0.16.2, calendar: 0.17.0 (latest of both). Tried on both chrome and firefox.

#### What's the expected behavior?

Should be consistent and the same ranges should be presented the same. In addition, it's probably a good idea to document the ranges. That is, is 1/1/2018-2/1/2018 a two days event, or a 1 day event like in ical (probably the latter).

**Comment by jquense** [comment]
Thanks for the report I believe I have this fixed in master should be in the next release

**Comment by tasn** [comment]
Ah, damn. I wasted all of this time to make an example and it's already fixed? :)

I'll try to test with master tomorrow and confirm the fix, though just one question, when do you expect a new version to be out? I have users complaining about events being presented wrong in [EteSync](https://www.etesync.com) and I'd really like to get a fix out.

In addition, do you remember which commit it was from the top of your head? Would love to take a look. Also, what is the expected behaviour for those events? 1/1-1/1 is one day, or 1/1-2/1? And please consider updating the docs (I can make a pull request if you prefer and confirm the correct behaviour).

Thanks.

**Comment by tasn** [comment]
Follow up to the previous comment: I took a look at the commit log, and at least based on the commit messages (summary lines), there seems to be something relevant. Are you sure this has been fixed?

**Comment by jquense** [comment]
i'd try with master, the commits are all mixed together. I still have one part of the fix pending in the PR but you shouldn't see that in the month view

**Comment by tasn** [comment]
Sorry, that was actually an issue I caused when building latest react-big-calendar.

I managed to test it, and my test case still partially fails.

Event A is 3 days, and event B is 2 days although they have the same span (12-14 but on different months and years). Please refer to the test case, it's very easy to see what's wrong.

In addition, event "C" is presented improperly in the weekly view. It's rendered as if it continues to the next week though it doesn't.

**Comment by tchamberlin** [comment]
I am running into this same issue, and my guess is that everyone who is running a recent version is experiencing the same. I've forked another example to demonstrate my specific issue, but it seemed similar enough that I won't open a new issue: https://codesandbox.io/s/mq351qv968

From what I can tell, **only events that terminate on the first day of the week will actually display correctly** in the month and week views. In the day and agenda views they display as expected. By changing the day on which the week starts, e.g. from Sunday to Monday by switching locale to `en-GB`, you can see that the problem persists and is not specific to Sunday.

Further, I cannot figure out how to install from `master`. I had assumed that I could install straight from GitHub, but that fails:

    $ npm install git+https://git@github.com/intljusticemission/react-big-calendar.git
    <my_package> <my_path>
    `-- react-big-calendar@0.17.0  invalid (git+https://git@github.com/intljusticemission/react-big-calendar.git#a1f17bf475ba7c07e2f825956d5486e6117f434b)

Any help would be greatly appreciated

**Comment by tchamberlin** [comment]
> Further, I cannot figure out how to install from master.

Scratch that; my `package.json` simply had an invalid version specifier. After getting the latest commit from `master` installed, I see no difference in behavior from `0.17.0`.

**Comment by tchamberlin** [comment]
Scratch that _again_ -- I must have done something wrong when installing the latest from `master` before. When I tried again today things were working as expected.

So, the bug definitely still exists in `0.17.0`, but at least my specific issue is resolved in the current `master`.

Thanks

**Comment by tasn** [comment]
@tchamberlin, lucky you. As you can see, some of the bugs in my example still occur (at least at the last time I checked).

Any news about when 017.1 is going to be out? At least having some of the issues fixed would be a great start, and I'd rather not run this lib from master.

**Comment by tasn** [comment]
Just verified again with 0.18.0, it's still broken. Specifically, the example I posted above is still broken, please take a look at the upper calendar in the example.

Please re-open this ticket.

Thanks!

**Comment by jquense** [comment]
The bug in your example is that you are using strings as dates in your events and not Date objects. Dates are being parsed as local dates from UTC so they aren't "even" over mightnight and so cross days than you want. The same example with correctly specified dates works: https://codesandbox.io/s/7oj4w4vzlq

**Comment by tasn** [comment]
Great, thanks, this indeed fixes the last remaining issue.

**Comment by aman0511** [comment]
hi @tasn is that issue if fixed ?

**Comment by tasn** [comment]
@aman0511, yeah... Look at my previous comment.

**Comment by aman0511** [comment]
@tasn 
for me if two day event is in all day it showing for only one day i am using the date object

**Comment by tasn** [comment]
Take a look at @jquense's example from above, it should work and show you what the correct values should be. I think you're most likely just misunderstanding how multi day events are represented.
I don't remember from the top of my head, but I assume it's like iCal where an event from 1/12 at 00:00 to 2/12 at 00:00 is *one* day. You probably got that wrong.

No idea though, sorry, I'm not the maintainer of this library, but I assume the above code examples should be sufficient.
