### ISSUE TITLE
Horizontal Scrolling: Too many resources will make the columns too small

### ISSUE THREAD

**Issue by vongdarakia** [intljusticemission/react-big-calendar#682]
I'm currently using another branch with the resource feature (I know the feature has been pushed to master recently though), and when I have too many resources, the columns will get too small to read.

Is there a feature for horizontal scrolling or does anybody have a good idea on how to make it work? I can work on this feature if nothing exists for it yet.

**Comment by jquense** [comment]
Nothing exists at the moment but it should be solvable with css. I'm happy to take a PR addressing this for the resource case

**Comment by vongdarakia** [comment]
That would be great! Thanks a lot, Jason!

**Comment by marwej** [comment]
This is implemented in version 20, right? Great feature, but I wonder if there's any way to disable it in some cases? I have a calendar where horizontal scrolling is not preferred and want to disable it for this specific case.

**Comment by jquense** [comment]
It's all implemented with css so you can reset or disable it that way if needed

**Comment by ameerahm** [comment]
Hi, it would be great if you could provide an example of exactly where the overrides in css would be to enable / disable horizontal scroll. Thanks

**Comment by yash-zorp** [comment]
Hello, How to enable right to left scroll after a particular number of recourses exceeds or is there any other parameter to do that?

**Comment by saadqu** [comment]
to all the world struggling with horizontal scroll, just add `overflow-x: auto;`

**Comment by saadqu** [comment]
or add `width: 95vw`
