### ISSUE TITLE
Sticky Time Sidebar

### ISSUE THREAD

**Issue by leesalminen** [intljusticemission/react-big-calendar#686]
Hi All,

I'm using a modified version of react-big-calendar where the day view is split into several columns (each person has their own column). I'm trying to figure out how to make the time gutter "sticky", so that as I scroll to the right the time gutter is always visible on the far left of the page. 

I think I have to modify CSS on `.rbc-time-gutter`, but I'm no flexbox expert and can't seem to find the right combination of styles to apply.

I've attached an image outlining what I mean. Any assistance would be greatly appreciated!

<img width="1391" alt="screen shot 2018-01-10 at 8 54 46 am" src="https://user-images.githubusercontent.com/3018359/34781876-3eed33e6-f5e4-11e7-87c3-113ac660cf00.png">

**Comment by jquense** [comment]
there isn't really a good way to handle this since the DOM elements are constructed to allow scrolling the other direction with the sticky headers. You could try `position: sticky` but browser support isn't great for it

**Comment by marwej** [comment]
@leesalminen I was just about to request such a feature (multiple columns representing users, departments, etc.)! It would be great if it was included in the library. Can you share your version? :)
