### ISSUE TITLE
Question about timeslots' height?

### ISSUE THREAD

**Issue by ehahn9** [intljusticemission/react-big-calendar#687]
Phenomenal work! I've been using fullCalendar for 2 years and this is an amazing improvement! THANK-YOU THANK-YOU! I'm making progress on synthesizing the fullCalendar features I've been needing, but one has me tripped up and I'd love some advice from the community:

tl;dr: rbc's slot heights shrink as `timeslots` increases, which (for me) is odd and quite different than fullCalendar's strategy. Any thoughts on how to change this?

In fullCalendar, if you increase the number of steps, each step retains its original height. An hour with 4 steps (`timeslots=4; step=15`) is twice as tall as an hour with 2 steps (`timeslots=2; step=30`). This makes some sense: the user presumably wants to see and select things with higher granularity. Of course, this means more scrolling to see the full day's worth of slots, but that's as designed, I believe.

In react-big-calendar, the slot height *shrinks* as the number of timeslots increases. Increasing the number of steps therefore makes each slot smaller to retain the constant hour height. That makes it very difficult to interact with calendars with smaller steps sizes (`timeslots=4` is difficult, `timeslots=20` (e.g. 5 minute steps) is impossible - each step is only a few pixels tall).

Here's an example of the suboptimal behavior I'm wondering about:

https://codesandbox.io/s/znwyoyw43

So my question is: is there an easy way to coax rbc into having its slots keep their height so more of them just means a "taller" grid w/ more scrolling. I'd be delighted to write a custom component, just looking for guidance if so.

Best & thanks again!

**Comment by tobiasandersen** [comment]
Great write-up, and I agree that the behavior you describe would be better! I also **think** it'd would be a pretty straight forward change. But @jquense has the full picture so I'd wait for his thoughts!

**Comment by jquense** [comment]
So Originally the timeslot feature was added by @cellog for the express purpose (I believe) of fitting more in without scrolling, hence the current behavior. I see why one would want it to work differently, and it should be easy enoguh to achieve with a css override. I think going the other way (from that to the current way) would be harder to do

**Comment by ehahn9** [comment]
perfect:

`.rbc-time-slot { min-height: 8px; }`

did the trick. I was afraid this would require work in the geometry computations but once again the fact that rbc just uses flexbox layout makes this sort of thing easy-peasy. Thanks!

**Comment by hacker0limbo** [comment]
> perfect:
> 
> `.rbc-time-slot { min-height: 8px; }`
> 
> did the trick. I was afraid this would require work in the geometry computations but once again the fact that rbc just uses flexbox layout makes this sort of thing easy-peasy. Thanks!

Another option using javascript would be custom style in the components props:

```js
timeSlotWrapper: (props) => {
  const { children, resource, value } = props;
  return <div style={{ minHeight: 48 }}>{children}</div>;
},
```

**Comment by irakli2206** [comment]
> ```js
> timeSlotWrapper: (props) => {
>   const { children, resource, value } = props;
>   return <div style={{ minHeight: 48 }}>{children}</div>;
> },
> ```

This works great too, nice
