### ISSUE TITLE
Day & Week views are broken on first render

### ISSUE THREAD

**Issue by tobiasandersen** [intljusticemission/react-big-calendar#688]
#### Do you want to request a *feature* or report a *bug*?
Bug

#### What's the current behavior?
The day and week views are broken on first render (only if they're the selected view during the calendar's first render). I haven't really looked into what's going on, but it seems like the gutter grows way too much for some reason, resulting in all the content being pushed off screen. If I in this state go to another view, and then switch back, it goes back to normal.

This is how it should look:
<img width="1027" alt="screen shot 2018-01-10 at 22 46 33" src="https://user-images.githubusercontent.com/3599069/34797291-3c499566-f658-11e7-8780-4a36d94b2af9.png">

But this is what we get:
<img width="1029" alt="screen shot 2018-01-10 at 22 46 17" src="https://user-images.githubusercontent.com/3599069/34797296-41802c2a-f658-11e7-8d5c-cc6376cc5081.png">

I'll look into this when I have time if no one else gets to it first, but I want to finish up [this PR](https://github.com/intljusticemission/react-big-calendar/pull/677) before...

**Comment by jquense** [comment]
so this happens when "measureGutter" is run before the RBC css is loaded. At that point the gutter has a width of the entire calendar. This really shouldn't happen in a real app since you'd be using extract-text-plugin and the css would be loaded upfront before anything else.

**Comment by jquense** [comment]
(i'm sure there is anything we can do about this in RBC)

**Comment by tobiasandersen** [comment]
Ok got it, makes sense!
