### ISSUE TITLE
Left menu in examples not visible on small screens

### ISSUE THREAD

**Issue by antoinerousseau** [intljusticemission/react-big-calendar#69]
When the screen width is smaller than 1400px (!), the menu on the left goes off the screen, because it is positioned with a negative margin left instead of using the responsive grid.

<img width="1181" alt="capture d ecran 2016-04-04 10 30 50" src="https://cloud.githubusercontent.com/assets/160279/14253241/5409a4c6-fa50-11e5-8ed5-b56cb0eda261.png">

**Comment by jquense** [comment]
ya I just haven't had a chance to fix it. PR's welcome

**Comment by antoinerousseau** [comment]
here you go :)
