### ISSUE TITLE
Rendering issue with react big calendar on Ipad Safari v10.3

### ISSUE THREAD

**Issue by prh7** [intljusticemission/react-big-calendar#692]
I have integrated react big calendar for my use case and works perfectly. But, there seems to be a rendering issue on Ipad Safari v10.3 as seen like below:

![image](https://user-images.githubusercontent.com/10049692/35038094-ed48792e-fb79-11e7-86f0-4912a58827ca.png)

It is supposed to look like below: 
![image](https://user-images.githubusercontent.com/10049692/35038079-def4adf2-fb79-11e7-85ae-d4eea9427a92.png)

I have not overridden any CSS which comes along with it. i really can't figure out the issue. Any sor t of help will be appreciated.

**Comment by jquense** [comment]
It's probably a flexbox bug on mobile safari. It's a bit hard for me help there tho since I don't have an iPad to test on

**Comment by prajwal78** [comment]
Do you have browserstack account ?

**Comment by jquense** [comment]
nope, happy to take a PR fixing it tho :)

**Comment by cfunkrun** [comment]
I have not tried it, but looks like Browserstack is free for open source projects, you just need to contact them.

**Comment by jquense** [comment]
fair warning i'm probably not going to do that.

**Comment by powermikee** [comment]
Just run it in the chrome device emulator. It's the same thing.
