### ISSUE TITLE
How to get all the events of one day

### ISSUE THREAD

**Issue by foromir** [intljusticemission/react-big-calendar#695]
when you click on the slot get array all event selected day
onSelectSlot => get all day event

**Comment by foromir** [comment]
<BigCalendar
            className="calendarDefault"
            events={this.props.events}
            startAccessor="startDate"
            endAccessor="endDate"
            selectable={true}
            onSelectSlot={this.props.slotSelect}
            onSelectEvent={this.props.eventSelect}
            views={["month"]}
            defaultView="month"/>

**Comment by jquense** [comment]
that's up to you, you already know all the events since you passed them into the calendar. You can use the event in the selectSlot handler to filter your events and get the ones you need
