### ISSUE TITLE
How to use 24 hours to display time in Day view ?

### ISSUE THREAD

**Issue by seeyoumr** [intljusticemission/react-big-calendar#698]
#### What I want ?
Use 24 hours to display time in Day view .
#### What's the current behavior?

Use am instead of morning, PM instead of afternoon.
Eg: 3:00 PM

#### What's the expected behavior?
Use 24 hours to display time,
Eg: 15:00

**Comment by tobiasandersen** [comment]
The easiest way is just to pick a locale with 24-hour format. If you look at the example "I18 and Locales" you can see that the format changes when you change culture. Choosing e.g. Brittish English should work:

```
import BigCalendar from 'react-big-calendar'
import moment from 'moment'

moment.locale('en-GB')
BigCalendar.momentLocalizer(moment)
```

**Comment by seeyoumr** [comment]
Thanks @tobiasandersen

**Comment by takeda-scrm-O365-AUS8474** [comment]
its is not  working

**Comment by takeda-scrm-O365-AUS8474** [comment]
is the above solution working? because it is not working for me. please help me on the same

**Comment by tnemalili** [comment]
The above solution is not working for me either. Headsup on version 0.26.0 <Calender /> is being used not <BigCalendar />
