### ISSUE TITLE
EventPropGetter and All days event

### ISSUE THREAD

**Issue by jesty** [intljusticemission/react-big-calendar#7]
Hi, I'm using your component, but I have an issue. I implemented a eventPropGetter method and I return an object with a className attribute. The class was correctly assigned to the event in the month view, but it is ignored in the other views.

**Comment by jquense** [comment]
Hi there, thanks for the issue...I can't reproduce the behavior your seeing. Even in the demo you can see that the class `'hi-event`' is being added to the `'rbc-event'` node in the time and day views.

**Comment by GabiAxel** [comment]
I encountered this issue with week and day views for all day events. Events with time get the style properly in these views and all events get the style properly in the month view.

**Comment by dyoxyne** [comment]
Hi, I just used the EventPropGetter. 
The issue I encountered was: EventPropGetter is not called for allDay event on the week and day views. Otherwise it worked as expected.
