### ISSUE TITLE
popupOffset is not working

### ISSUE THREAD

**Issue by Flaeron** [intljusticemission/react-big-calendar#700]
Got the error when try to add popupOffset prop as object and didn't see any offset changes.

**Warning: Failed prop type: Invalid prop `popupOffset` of type `object` supplied to `Popup`, expected `number`.**

Example how I added popup props:
`<BigCalendar
    popup={true}
    popupOffset={{x: 100, y: 50}}
/>
`

**Comment by tobiasandersen** [comment]
The warning definitely shouldn't be there, but I'm a bit confused about the prop itself. According to the docs it controls: 
> Distance in pixels, from the edges of the viewport, the "show more" overlay should be positioned.

I haven't used this prop myself, but looking at the code it seems like it will only affect the popup's position if it can't fit in its "default position". So only if the popup would normally go outside of the viewport will this prop kick in.

I'm not sure if this is the intended behavior @jquense? Again, I haven't used it, but to me it sounds like it would make sense to have this behave either like a `min-offset` or as the actual offset.

**Comment by jquense** [comment]
the prop type is just wrong i think
