### ISSUE TITLE
feature request: nowAccessor (or equiv)

### ISSUE THREAD

**Issue by ehahn9** [intljusticemission/react-big-calendar#704]
The `timeIndicator` is always placed by `positionTimeIndicator()` at the time corresponding to `new Date()` - e.g. the browser's local time. 99% of the time this is perfect.

... but if you're displaying the calendar in another time zone (e.g. using any of the great ideas from #118), then you also need to adjust (e.g. "fake out") the notion of 'now' to match.

tl;dr - a `nowAccessor` would be lovely.

If I was more confident in my open source manners, I'd submit a PR, but alas, I'm a newb. :-(

**Comment by ehahn9** [comment]
Also would impact the determination of `rbc-today` styling.

... and `nowAccessor` wouldn't really be an accessor insofar as it requires a fn(), and can't take a sting (there's no named property option to reference). So, to keep consistent with the api, maybe `getNow` or `nowGetter` is a more accurate name?

**Comment by jquense** [comment]
Sorry closed accidentally!

**Comment by ehahn9** [comment]
Made some progress on this - might issue a PR shortly (my first ever!). Please accept my apologies if I'm doing any of this incorrectly... Would love some feedback if that's not unreasonable...

I named the property `now`. It can be either a date or (more usefully) a fn which returns a date, since that way the time-indicator bar will correctly poll for changes as it currently does. The default prop value is therefore `() => new Date()`. I created a new `PropType.dateGetter` (which is either `instanceOf(Date)` or `func`). `now` is the only prop using it, tho.

The behavior affects the `.rbc-today` shading, the `.rbc-time-indicator` horizontal line and the behavior of `navigate.TODAY` - all of which get the notion of now (or today) from the new prop.

Turns out it also impacted the calculations for `min`, `max` and `scrollToTime` which were all hardcoded to `new Date()` (they use the new prop, too).

Finally, I changed the `rendering` demo to illustrate a customized `now` fn, but I suspect that's not worth it since it's sort of a trivial api change. Thoughts?

Worth issuing a PR or am I the only person likely to ever use this? (in fairness, I think anyone wanting to display calendars in different time zones will need something like this?).

**Comment by tobiasandersen** [comment]
Hey @ehahn9! This sounds great! 

About the name, I actually think I like your original naming better (i.e. `nowAccessor`). It's more consistent with the rest of the api. Having said that, I think it makes sense if that prop only accepts functions. I don't really see the value of passing just a date, but maybe I'm missing something? It sounds like something that people will do by mistake quite easily.

I definitely welcome a PR! We can continue the discussions on that instead. Great work!

**Comment by tobiasandersen** [comment]
I'll close this now that https://github.com/intljusticemission/react-big-calendar/pull/707 is merged. Great work @ehahn9!
