### ISSUE TITLE
Feature Request: make Month rowLimit configurable via props

### ISSUE THREAD

**Issue by josephrace** [intljusticemission/react-big-calendar#708]
Rather than have `rowLimit` hardcoded as 5 in the `Month` view it would be great to make it configurable via a prop.

The calendar may end up being unusually tall but I think this choice should be left to the user of the package.

FullCalendar appears to allow this via the `eventLimit` property.

**Comment by jquense** [comment]
there are many issues discussion this already, please read one of those thanks!

**Comment by josephrace** [comment]
Found #679 - sorry, the issue title didn't appear related before. Thanks!
