### ISSUE TITLE
Passing props to custom components

### ISSUE THREAD

**Issue by glouhaichi** [intljusticemission/react-big-calendar#709]
#### Do you want to request a _feature_ or report a _bug_?
Not sure, it could be a bug or a new feature.
#### What's the current behavior?
At the moment, the only way to pass custom components to be rendered by the calendar is to use the ```components``` prop as follows:
```javascript
<BigCalendar components={ { event: MyCustomEvent } } />
```
```MyCustomEvent``` is a React-JS class that is passed as is to the calendar as is and I assume that somewhere in the code something like the following is done:
```javascript
<MyCustomEvent event={ sthg.event } /* etc... */ />
```
#### What's the expected behavior?
Have some way of specifying custom props to those custom components. This way somewhere in the code, the rendering is somethnig like this:
```javascript
<MyCustomEvent event={ sthg.event } { ...myCustomProps } /* etc... */ />
```

**Comment by tobiasandersen** [comment]
Hi! This is basically the same question as https://github.com/intljusticemission/react-big-calendar/issues/623. I made a [codesandbox](https://codesandbox.io/s/kw645vwm27) back then that achieves what you're asking for here.

**Comment by glouhaichi** [comment]
Thanks for the response, I was looking for a similar post but could not find one. I took a look at the code sandbox and I see now how to do it, thanks.
