### ISSUE TITLE
dayPropGetter not documented, is it working ?

### ISSUE THREAD

**Issue by lepirlouit** [intljusticemission/react-big-calendar#710]
#### Do you want to request a _feature_ or report a _bug_?
request a _feature_
#### What's the current behavior?
I don't see the functionality of the dayPropGetter for custom renderer. and it is not in the documentation API.

#### What's the expected behavior?

Can I add an element next to the date day in the montly view ?
Should this be done with the dayPropGetter property ?
![image](https://user-images.githubusercontent.com/1354968/35688962-b1cf7ba4-0772-11e8-98aa-e907357c78c7.png)

**Comment by tobiasandersen** [comment]
This looks very similar to https://github.com/intljusticemission/react-big-calendar/issues/644. Have a look at the `dateHeader` prop:



```
<BigCalendar
  components={{
    month: {
      dateHeader: (props) => (
        <div>Custom Date Header</div>
      )
    }
  }}
/>
```

**Comment by lepirlouit** [comment]
Thanks for your quick reply.
