### ISSUE TITLE
Feature request / Issue - Resources not working

### ISSUE THREAD

**Issue by basilbthoppil** [intljusticemission/react-big-calendar#711]
I do see the calendar accepting 'resources' list. Doesn't look like the code is working.

`<BigCalendar
       views={['week', 'day']}
       resources= { [{id: 1, title: 'John'}, {id:2, title: 'Linda'}] } />`

It doesn't change anything in the view. npm install doesn't have resource changes - i build it directly from the source (master) and used.

**Comment by jquense** [comment]
there is now an example of how to use it you can look at, as well as the various stories the repo here for inspiration

**Comment by basilbthoppil** [comment]
1. Not sure if the latest master is published to npm. I am not getting any code related to resource service in npm install

2. Tried building it from the master - has some UI issues - but example code works.

**Comment by asharafshahi** [comment]
Does installing from npm not give you the resource feature?  I cannot get it working for the life of me.  How did you manage to make it work from master?

**Comment by jquense** [comment]
its in the latest release, i still haven't updated the docs but you can look at this example: https://github.com/intljusticemission/react-big-calendar/blob/master/examples/demos/resource.js
