### ISSUE TITLE
Multi day not displayed properly as per strat and end time

### ISSUE THREAD

**Issue by neha-empyra** [intljusticemission/react-big-calendar#720]
Bug : 
The "start_date_time": "2018-02-16T15:30:00" and  "end_date_time": "2018-02-22T15:30:00",
and showMultiDayTimes = { true }
but events are not displayed properly as per time interval

please find below images for your reference 

![capture 1](https://user-images.githubusercontent.com/36193186/35971496-2c625586-0cf4-11e8-848f-3bbd4480d99a.PNG)
![capture 2](https://user-images.githubusercontent.com/36193186/35971499-2e3b4192-0cf4-11e8-820f-b73f8c96b176.PNG)
![capture 3](https://user-images.githubusercontent.com/36193186/35971502-2f939594-0cf4-11e8-95ed-479221c29c42.PNG)

calendar version : "0.17.0"
chrome version : Version 63.0.3239.132

**Comment by jquense** [comment]
Try updating to the latest version
