### ISSUE TITLE
BigCalendar.length

### ISSUE THREAD

**Issue by kocka5** [intljusticemission/react-big-calendar#723]
Hello,

  I set in my project not documented property length to set longer range in agenda view. This work fine, but range in <span class="rbc-toolbar-label"> dont show new range correctly and show month range instead of BigCalendar.date plus BigCalendar.length.  

 I use 0.18.0 version.

 Pavel

**Comment by tobiasandersen** [comment]
Hi, 

I'm not really sure what you're asking here. Could you try and explain it a bit further please?

**Comment by kocka5** [comment]
I try explain by example.
I set BigCalendar. length to 365. But agenda view show title: 14.02.2018 — 16.03.2018 but correct value sholud be 14.2.2018 - 14.2.2019. 
  Pavel

**Comment by kocka5** [comment]
Sorry, npm install resolved me that problem.
