### ISSUE TITLE
Error on component resize when view prop has changed

### ISSUE THREAD

**Issue by marwej** [intljusticemission/react-big-calendar#725]
#### What's the current behavior?

When the view is changed (with new value in prop) the calendar throws an error on component resize.
"Uncaught TypeError: Cannot read property 'scrollHeight' of undefined"
https://github.com/intljusticemission/react-big-calendar/blob/3903fd7066dafcc7dd528fa9889748cf75e0e5df/src/TimeGrid.js#L470

Haven't succeeded with reproducing the problem yet though (I'll keep trying):
https://codesandbox.io/s/wyzj8o3228

#### What's the expected behavior?

No errors.

**Comment by marwej** [comment]
Don't know if abandoning string refs would do anything about this, but maybe should be done anyway. Will do tests but maybe someone else is faster than me.

**Comment by mprobus** [comment]
I've run into same message after navigating from page with a calendar view to one without, and then resizing app.  Is this because the TimeGrid resize listener never gets removed?

**Comment by panta82** [comment]
I can confirm the behavior @mprobus has described.

**Comment by beausmith** [comment]
I can also confirm this behavior.

![image](https://user-images.githubusercontent.com/28444/36572355-21f3cea2-17f0-11e8-940d-553f3e0755db.png)

## Repro Steps
1. View calendar in "month" view.
2. Resize browser window.
3. Check console for errors.

**Comment by johnunclesam** [comment]
Same here:

![image](https://user-images.githubusercontent.com/21275217/37261014-3ff1d758-2599-11e8-9962-e9f2984cfd86.png)
