### ISSUE TITLE
Start Date Undefined on Resize

### ISSUE THREAD

**Issue by svanetten1976** [intljusticemission/react-big-calendar#726]
#### Do you want to request a _feature_ or report a _bug_?
Potential bug
#### What's the current behavior?
I realize this is a breaking change that we now have the ability to resize, but I'm running into an issue with this initial setup. For some reason, the 'start' argument is coming back as undefined in the onEventResize callback method. Because of this, the UI does not look right while resizing -- the event looks more like you are dragging it to a new cell. I'm bandaging this for now by grabbing the startDate from my own internal event data, so that the resize feature *works* but the interaction doesn't look right (I'm assuming because of the missing 'start' arg.) There's no doc or demo for this feature yet, was hoping maybe somebody could point me in the right direction? Here's the whole config...

              <DragAndDropCalendar
                selectable
                events={events}
                eventPropGetter={this.eventPropGetter}
                resizable
                onEventResize={this.resizeEvent}
                defaultDate={activeDate}
                date={activeDate}
                view={calendarView}
                onView={view => changeCalendarView({ date: activeDate, view })}
                popup
                timeslots={8}
                startAccessor="startDate"
                endAccessor="endDate"
                onNavigate={date => changeActiveDate(date)}
                onEventDrop={this.onEventDrop}
                ref={el => (this.eventCalendar = el)}
                onSelectEvent={(activity, evt) => this.editCalendarEvent(activity, evt)}
                onSelectSlot={slot => this.addCalendarEvent(slot)}
                style={{ height: '100%' }}
              />

**Comment by arecvlohe** [comment]
Can you show your `this.resizeEvent` function?

**Comment by svanetten1976** [comment]
Hey @arecvlohe thanks for the quick reply. Here is my resizeEvent function. Its destructuring the second argument, just like in the (non-active) demo on the RBC site. The 'start' param just comes back as undefined for me. That updateActivity prop is just a Redux action that sends the update data to our API

  resizeEvent = (resizeType, { event, start, end }) => {
    console.log('RESIZE', resizeType, event, start, end)

    this.props.updateActivity({
      activeDate: new Date(event.startDate),
      dataId: event.dataId,
      endDate: `${timestampFormatter(end)} ${timestampFormatter(end, 'hh:mm A')}`,
      startDate: `${timestampFormatter(event.startDate)} ${timestampFormatter(event.startDate, 'hh:mm A')}`
    })
  }

**Comment by arecvlohe** [comment]
What version of rbc do you have?

**Comment by svanetten1976** [comment]
@arecvlohe v. 0.18.0 -- just updated today because I noticed that the resize feature had been added, and we have been looking to integrate that feature. Thanks -- Steve

**Comment by arecvlohe** [comment]
I don't really know why the start value is not being returned other than if when you drop the event, it's not dropping on the day to trigger the date to be returned which maybe due to some CSS or some element preventing the drop on the drop target. I can't really say for sure though.

**Comment by svanetten1976** [comment]
Hey @arecvlohe many thanks for taking the time to look into it for me. If I figure out what the cause was, I'll let you know. Otherwise, this feature is working just like it should and we appreciate the addition of this functionality. Cheers -- Steve
