### ISSUE TITLE
eventPropGetter / slotPropGetter should accept more props

### ISSUE THREAD

**Issue by bkniffler** [intljusticemission/react-big-calendar#728]
Hey, 
slotPropGetter and eventPropGetter currently support className / style, but wouldn't it be nice if we could hand them more props like onMouseEnter or onContextMenu to do all sorts of exciting stuff on slots and events?

I'd like to commit a PR if you're willing to accept such, are you open for that?

**Comment by arecvlohe** [comment]
I think a PR would be worth it! I would be interested to see what you could come up with.
