### ISSUE TITLE
Where does the inline styling of the rbc-event div get generated?

### ISSUE THREAD

**Issue by The-Oracle** [intljusticemission/react-big-calendar#729]
So I have a BigCalendar react app that displays events from two Google calendars. The events are all 30 minutes in length. I would like the cells to be split 50/50 and span edge to edge. 

Basically, I need to make the inline styling of the blue events to be: 
`left: 0%;  width: 50%;`
Then the red events would be:
`left: 50%;  width: 50%;`

I can't figure out where in the codebase the inline styling for the event div's is generated. If someone could point me to the file that generates the inline style, I can take care of the rest. Thanks

<img width="1920" alt="screenshot_69" src="https://user-images.githubusercontent.com/875616/36237889-1d7d5134-11bc-11e8-8c68-79aa35c98278.png">

**Comment by jquense** [comment]
here is where it's calculated: https://github.com/intljusticemission/react-big-calendar/blob/master/src/utils/dayViewLayout/index.js#L97-L101

**Comment by The-Oracle** [comment]
Thanks, I was able to modify it to get the desired result.
<img width="1988" alt="screenshot_70" src="https://user-images.githubusercontent.com/875616/36275555-697db72c-1248-11e8-9c3b-64c9abf8ac15.png">

**Comment by x1mrdonut1x** [comment]
@The-Oracle did you modify the original file?
I don't want to mess with those, is there a way to customize this using another way?
Ideally, I would like my events to have a set width (or one that I can control).

Thanks
