### ISSUE TITLE
All day event : Date and time is same 

### ISSUE THREAD

**Issue by bhagayshriajmera** [intljusticemission/react-big-calendar#730]
All day event : There is no identifier to identify the all day event
There should be some identifier to identify the all day event or date should be different

e.g  selected slot 
start date and time  :  16-02-2018 12:00 AM
end date and time  :  16-02-2018 12:00 AM

Either end date should be 17-02-2018 12:00 AM (because its of 24 hrs)
Or there there should be some identifier to identify that it is all day event

**Comment by jquense** [comment]
Whether something is an all day event is up to you, that why provide and accessor prop for it. You can pick whether it counts or not but we just provide the times when selecting slots
