### ISSUE TITLE
Event height is incorrect for 15 minute slots

### ISSUE THREAD

**Issue by vongdarakia** [intljusticemission/react-big-calendar#731]
When the start and end times are 15 minutes apart, the height is rendered as if it's a 30 minute slot.

**Comment by tobiasandersen** [comment]
I think there's a `min-height` of 20px set on events (using css). You should be able to override this though.

**Comment by vongdarakia** [comment]
The height of the 15-minute event is actually more than 20px. So, I know
the min-height isn't the problem. But it's good to keep in mind, in case I
make event cell smaller, thanks.

I see that calculation of the height is the same as 30-minute events.

The time range is from 8am - 5pm, total of 540 minutes. Thirty minutes give
5.55%, and that's exactly what I see for the 15-minute event. It should be
2.77%. There has to be something wrong with the event height calculations.


ᐧ

**Comment by jquense** [comment]
Can you please provide a repro using the code sandbox in the issue template thanks!

**Comment by vongdarakia** [comment]
https://codesandbox.io/s/wjjq8k6ow

I created an event called "Event shorter than step" for 3/10/2015.

I think I know what the problem is. It seems the minimum height is based on the time-step. By default, the time-step is 30 minutes, so anything shorter will not have its actual height.

I bypassed this by setting the steps to 5 minutes and overriding the css to remove the step borders. That should cover most events, but not for events with time durations that are not a multiple of 5.

**Comment by sasacocic** [comment]
Any update on this?

**Comment by gseguin31** [comment]
I was also having issues when two 15 minute events where back-to-back. The style of the events would be like when events are at the same time.

```
<Calendar
    ...
    defaultView="week"
    views={['week']}
    step={15}
    timeslots={4}
/>

.rbc-event {
    //fix 15 minute events overlapping their timeslot
    min-height: 5px;
    //fix back-to-back 15minute event overlapping style
    width: 100% !important;
    left: 0% !important;
}
```
