### ISSUE TITLE
Work week example?

### ISSUE THREAD

**Issue by VincentRichard555** [intljusticemission/react-big-calendar#735]
Is there an example using the work_week view? I see that it was introduced in #383 but I do not see an example explicitly showing how it is used.

I am trying:

`defaultView={'work_week'}`

But it does not seem to work. Thanks.

**Comment by jquense** [comment]
set the `views` prop to the ones you want. e.g `views=['day', 'agenda', 'work_week', 'month']`

**Comment by VincentRichard555** [comment]
Ah simple, not sure how I missed that. Thank you.

**Comment by bradeac** [comment]
Hi.

```views``` prop doesn't work for me.
I tried: 
```views={['work_week']} ```
Also the default:
```views={['day', 'agenda', 'work_week', 'month']}```

What I get is:
```Uncaught TypeError: Cannot read property 'title' of undefined at Calendar.render 
(modules.js?hash=e17e769497864e1c3da496c8e383db12da977918:1231)```
which is kind of strange.

If I don't use the ```views``` prop, the calendar works as expected.

**Comment by bradeac** [comment]
Somehow it worked like this:
```
                        defaultView={'work_week'}
                        views={['day', 'work_week']}
```

**Comment by milan2you** [comment]
defaultView={'work_week'}
views={['day', 'work_week']}
this work for me

**Comment by Lipemenezes** [comment]
Well, my problem was that @bradeac, thanks.

`
views={['day']}
defaultView={'day'}
`

Should be improved tho. What's the point of having to specify default view when you configure it ot have only one view available?

**Comment by irfanullahjan** [comment]
Yes, please fix this for everyone.
