### ISSUE TITLE
Feature request: allow adding UI elements to day cells

### ISSUE THREAD

**Issue by Thr44** [intljusticemission/react-big-calendar#736]
At the moment it is very difficult to implement something like adding an add button to the calendar cells that only is visible on the cell hover (just like google calendar has).

My solution was to add a custom event, with absolute position that floats on top of the other events (which prevents any pointer-events to the other events)

Any better solution?

Thanks

**Comment by aappddeevv** [comment]
I think I responded to a closed issue, but I need to customize the "event" cell that is displayed which I think would address your issue. 

Something I have seen that is useful in other libraries is a "onEventRender" type property that takes the properties and default rendering function. Then someone can just use the default rendering and wrap the default rendered component easily with something that does tooltip/hover/button behavior with your own hover/button content of course.

onEventRender would get a default rendering function that renders the default EventCell object so you can wrap it if you want to. This also fits into the renderprops pattern that is popular.

**Comment by aappddeevv** [comment]
It looks like "components" was added to allow you to customize the component used for things like events and such. I suggest closing this as you will not want 2 APIs.
