### ISSUE TITLE
Is there an example using resizable events?

### ISSUE THREAD

**Issue by VincentRichard555** [intljusticemission/react-big-calendar#738]
Is there an example using resizable events?  On the demo and docs page I see one for drag and drop but not for resizable events. The code for that example appears to have a resize prop but the example doesn't show any resize functionality.

Thanks

**Comment by seeyoumr** [comment]
I had the same problem.

**Comment by tobiasandersen** [comment]
I don't think there is. But you're welcome to create one and make a PR! :)
