### ISSUE TITLE
Start a channel on Slack, Gitter, or Discord

### ISSUE THREAD

**Issue by arecvlohe** [intljusticemission/react-big-calendar#739]
This is more of a community request. I notice that some questions that come in as issues are more inquiries and can easily be answered in a chat conversation than through an issue thread. I think it would improve the project if there was a channel on either Slack, Gitter, or Discord to answer small or frequently asked questions to reduce a lot of noise under issues.

**Comment by jquense** [comment]
I think this is a fine idea 👍 I don't have a ton of time to spend there, but if folks wnat to put something together i'm happy to promote it here

**Comment by arecvlohe** [comment]
Okay, I will look into setting something up on one of the services mentioned.

**Comment by arecvlohe** [comment]
Deployed in #767
