### ISSUE TITLE
Month view is empty

### ISSUE THREAD

**Issue by RaedsLab** [intljusticemission/react-big-calendar#740]
#### Do you want to request a _feature_ or report a _bug_?

Report a bug

#### What's the current behavior?

Month view does not show dates. 

https://codesandbox.io/s/8n92mr59q2 (edit) 

#### What's the expected behavior?

Month view to show dates & events

**Comment by tobiasandersen** [comment]
The codesandbox doesn't work. Have you set a height on your container element?

**Comment by RaedsLab** [comment]
@tobiasandersen  thank you for quick response. 

My bad here is an updated link: https://codesandbox.io/s/8n92mr59q2

**Comment by tobiasandersen** [comment]
You haven't set a height on the div holding the calendar — it needs an explicit height.
