### ISSUE TITLE
Internatinalisation with react-intl

### ISSUE THREAD

**Issue by lepirlouit** [intljusticemission/react-big-calendar#741]
#### Do you want to request a _feature_ or report a _bug_?
I want to request a _feature_

#### What's the current behavior?
Internationalization is handled with moment and with globalizer

#### What's the expected behavior?

I want internationalisation with react-intl

Hi,

Is there any project bussy on internationalization with react-intl ?

**Comment by jquense** [comment]
there isn't any existing solution, but you could probably look at the globalize example and adapt it for date formating since they both mimic/use the `Intl` api.

For messages, the interop is do something like `intl.formatMessage(messages.allDay)` and pass that to the calendar messages prop
