### ISSUE TITLE
Show labels on available timeslots

### ISSUE THREAD

**Issue by sappleg** [intljusticemission/react-big-calendar#742]
#### Do you want to request a _feature_ or report a _bug_?
Feature Request

Currently, there is no way to get labels to show on available timeslots. The hack around it is to change the default value of `showLabels` to `true` in `lib/TimeColumn.js`. I'd like to be able to induce this behavior from the `BigCalendar` component.

Something like the following:
```
          <BigCalendar
            culture="en-US"
            defaultView="work_week"
            longPressThreshold={150}
            selectable="ignoreEvents"
            step={20}
            timeslots={1}
            views={['work_week']}
            showLabels
          />
```

#### What's the expected behavior?
When set to `true`, labels would be shown on all available timeslots. If set to `false`, the current behavior would occur (no labels).

Is this something that can already be done or would you like a PR?

**Comment by arecvlohe** [comment]
I think this would be a good PR.

**Comment by jquense** [comment]
feel free to PR something!
