### ISSUE TITLE
Selecting event in agenda view should call `onSelectEvent` 

### ISSUE THREAD

**Issue by beausmith** [intljusticemission/react-big-calendar#743]
#### Do you want to request a _feature_ or report a _bug_?

Feature.

#### What's the current behavior?

Selecting events in the "agenda" view do not call the `onSelectEvent`.

#### What's the expected behavior?

Selecting events in all views should call the `onSelectEvent`.

**Comment by Selast** [comment]
Hello ! I'm having the same issue here. Help please. =)

**Comment by johnmichael246** [comment]
I'm having the same issue. @beausmith , @Selast  were you able to fix the issue?
My way around was to add an onClick to the top div in a custom Agenda event, the only problem is then the .rbc-selected is not synced between agenda and month after

**Comment by beausmith** [comment]
@johnmichael246 - I don't currently need the view, but will be tempted to make a PR when I need this in the future if someone doesn't beat me to it.

**Comment by silentsakky** [comment]
Have created pull request https://github.com/intljusticemission/react-big-calendar/pull/852 to handle this issue

**Comment by beausmith** [comment]
Right on @silentsakky! Thank you!
