### ISSUE TITLE
Agenda not updating on event changes

### ISSUE THREAD

**Issue by jesseluowork** [intljusticemission/react-big-calendar#744]
I have something like this as my core component
```
      <BigCalendar
        events={events}
        defaultView="week"
        defaultDate={new Date()}
        startAccessor="start"
        endAccessor="end"
        onSelectSlot={slotInfo =>
          createCalendarChangeHandler(slotInfo, events)
        }
        style={
          {
            height: '800px'
          }
        }
      />
```

When I drag and drop it successfully creates the new event as I update the  store.

![image](https://user-images.githubusercontent.com/22160022/36765750-975336d8-1be7-11e8-90f6-18fa1018f828.png)

For some reason the agenda isn't reflecting the new event?
![image](https://user-images.githubusercontent.com/22160022/36765772-bb0b6424-1be7-11e8-86e2-453dacf1cfe5.png)

**Comment by jquense** [comment]
please put together a minimal reproduction using the codesandbox template thanks!

**Comment by jesseluowork** [comment]
Hey tracing my issue, was wondering this function is using (day, day)

https://github.com/intljusticemission/react-big-calendar/blob/master/src/Agenda.js#L105

I'm on a proprietary work library so it's more difficult to create a sandbox.

**Comment by jquense** [comment]
That function call looks good, it's checking if events are with the particular day. It's tough to help out unfortunately without something to troubleshoot :/

**Comment by jquense** [comment]
Closing for staleness
