### ISSUE TITLE
styling problem with allDay event header?

### ISSUE THREAD

**Issue by ehahn9** [intljusticemission/react-big-calendar#747]
#### Do you want to request a _feature_ or report a _bug_?

bug?

#### What's the current behavior?

Looks like maybe there's a styling problem in `.rbc-allday-cell`? For some reason, although `.rbc-allday-cell` is styled with `width: 100%`, it is larger than the remaining space in the `rbc-row` - the gutter is correctly fixed width at the left side, but the remaining portion of the `rbc-row` seems to be too big (see below - red box added for illustration). This causes busy views to overflow and the header columns to become unaligned vertically...

This is *not* a problem with the row immediately above it (the one with the day/date headers) - the only difference in the markup between these rows is the insertion of the `.rbc-allday-cell` and the `.rbc-row-bg` and `.rbc-row-content` divs, so I presume there's a (minor?) css problem there somewhere?

I tried to figure this out but became stumped (I'm not great at css!) - I'm happy to work on this but I need some advice on where to invest more time. Seems like it is some odd interaction of `flex` and the intervening `divs` below `rbc-row`?

![rbc-row problem](https://user-images.githubusercontent.com/299134/36871502-4506ed0e-1d57-11e8-8551-c451d0db9fd6.png)

#### What's the expected behavior?

I'd expect the allday-cell columns to line up exactly with the rest of the grid and not overflow.

**Comment by ehahn9** [comment]
I'm not 100% sure this is the right fix, setting `overflow: hidden` on the `.rbc-allday-cell` fixes my problem. Happy to do a PR if desired. Feel free to close.

**Comment by jquense** [comment]
@ehahn9 i'd make sure it's not still present with the diff from #733 there is a bunch of small styling things there

**Comment by arecvlohe** [comment]
There looks to be a fix to this issue so closing this issue for now.
