### ISSUE TITLE
If not enable removal of all-day-row, at least add a special class name

### ISSUE THREAD

**Issue by marwej** [intljusticemission/react-big-calendar#750]
#### feature request

There has been suggestions of a prop to disable the all-day row, but it has been argued against. 

A workaround would be the proposed styles here https://github.com/intljusticemission/react-big-calendar/issues/203#issuecomment-337669064, but that does not work if resources are enabled. The styles could of course be modified, but in my case the component must be able to handle both situations (with/without resources).

I suggest that the row at least gets its own class name so that it's possible to `display: none` on this.
https://github.com/intljusticemission/react-big-calendar/blob/master/src/TimeGrid.js#L298

**Comment by jquense** [comment]
happy to take a PR!

**Comment by drewandrew** [comment]
+1

**Comment by drewandrew** [comment]
@marwej It appears there is a `rbc-allday-cell` class name that I was able to use with `display: none` https://github.com/intljusticemission/react-big-calendar/search?q=rbc-allday-cell&unscoped_q=rbc-allday-cell

**Comment by jquense** [comment]
http://intljusticemission.github.io/react-big-calendar/examples/index.html#prop-showMultiDayTimes
