### ISSUE TITLE
Question: can we auto expand the date slots to show all content?

### ISSUE THREAD

**Issue by loaibassam** [intljusticemission/react-big-calendar#751]
Is it possible to allow the date slots to automatically change its height to adopt / fit the content inside it? 
 
From this: 
![screen shot 2018-03-03 at 14 42 55](https://user-images.githubusercontent.com/4785390/36935564-3cc201b0-1ef1-11e8-8d20-70bd9b315ce4.png)

To this:
![screen shot 2018-03-03 at 14 43 09](https://user-images.githubusercontent.com/4785390/36935565-3d9b244a-1ef1-11e8-82e3-52c835a6ca32.png)

**Comment by jquense** [comment]
Please see previous issues on this thanks!
