### ISSUE TITLE
Supplying min/max props breaks 'week' view in Safari

### ISSUE THREAD

**Issue by balthatrix** [intljusticemission/react-big-calendar#756]
#### Do you want to request a _feature_ or report a _bug_?
BUG
#### What's the current behavior?
When giving min OR max properties for time slots, the week view breaks, not showing any time slots except "all day"

#### What's the expected behavior?
When giving min OR max properties for time slots, the week view should work just as it does in Chrome and Firefox.

<img width="1310" alt="screen shot 2018-03-06 at 3 44 11 pm" src="https://user-images.githubusercontent.com/5818492/37065429-acbf3bd4-2155-11e8-86da-b0b002dbe50e.png">

Steps to reproduce:
1) supply min/max properties to a react big calendar component
2) open up safari, and check out your 'week' view

**Comment by jesseluowork** [comment]
Also having trouble with something similar to this.  

![image](https://user-images.githubusercontent.com/22160022/37231400-0a3262ae-23b9-11e8-9bfa-27062d15a725.png)

timeslots have also disappeared...?
