### ISSUE TITLE
Unable to resolve module 'react-big-calendar/lib/css/react-big-calendar.css

### ISSUE THREAD

**Issue by uguryiilmz** [intljusticemission/react-big-calendar#757]
I have tried every single solution has been stated here but did not find a way to get rid of this error. I am newbie to js and react environment. Is it something caused by web pack or might be related to how I load this? 

Tried this import 'react-big-calendar/lib/css/react-big-calendar.css';
and tried this import '!style-loader!css-loader!react-big-calendar/lib/css/react-big-calendar.css' instead
Both throw the same error

**Comment by uguryiilmz** [comment]
Any idea?? I really can't figure out what to do.

**Comment by jquense** [comment]
I don't know :( I would check that the file is in `node_modules/react-big-calendar/lib/css/react-big-calendar.css`, if not reinstall. If it is the problem is your webpack configuration. I'd suggest trying one of their support avenues like the discord channel

**Comment by arecvlohe** [comment]
This should be pretty easy if you are using `create-react-app`. If you are rolling your own webpack then you need to make sure you are using the right loaders.

**Comment by trleithoff** [comment]
I'm having the same issue.
![calendar-css-error](https://user-images.githubusercontent.com/1391687/37786610-7d030e90-2dd3-11e8-9ed3-8e8951a008b1.png)

**Comment by arecvlohe** [comment]
I don't think `Calendar.css` is a module

**Comment by khaledbk** [comment]
Hi,
Easiest way to solve that problem is to add the css file to your header : 
<link href="https://cdn.jsdelivr.net/npm/react-big-calendar@0.19.0/lib/css/react-big-calendar.css" rel="stylesheet"/>

**Comment by arecvlohe** [comment]
This hasn't been responded to from the original poster for sometime so I am going to close. Please refer to https://github.com/arecvlohe/rbc-starter as an example to help.
