### ISSUE TITLE
Styling cells in month view

### ISSUE THREAD

**Issue by smajazayeri** [intljusticemission/react-big-calendar#759]
How can we give a custom styling to each cell in the month view? I found `DateCellWrapper` in the previous issues, but I didn't find any working example...

**Comment by ndrd** [comment]
I include the .less files of the project into mine, then, import your custom styles and override only the elements you need.
<img width="832" alt="screen shot 2018-03-09 at 9 07 35 am" src="https://user-images.githubusercontent.com/8826286/37214115-a2c0cec4-2379-11e8-880e-3c17a706d588.png">
