### ISSUE TITLE
Setting min and max when changing timezone messes with time slots + displays

### ISSUE THREAD

**Issue by jesseluowork** [intljusticemission/react-big-calendar#760]
Reproduction - https://codesandbox.io/s/j7rxpp4715

Trying to figure a way to start the calendar from 0:00 (start of day) after changing the Calendar timezone to UTC.  If you take out the min/max in the sandbox you'll see its shifted based on the browser local time.  

Also if you look at the existing events it seems like they're extremely distorted and the onselect no longer works as expected.  

Using
```
moment_timezone.tz.setDefault('ETC/utc');
BigCalendar.momentLocalizer(moment_timezone);


  <MyCalendar
    min={moment().startOf('day').toDate()}
    max={moment().endOf('day').toDate()}
    ...otherProps
  />
```

from https://github.com/intljusticemission/react-big-calendar/issues/756 on chrome

**Comment by jquense** [comment]
check out the existing issue for timezone support #118
