### ISSUE TITLE
Two events for the same date/time

### ISSUE THREAD

**Issue by DanZeuss** [intljusticemission/react-big-calendar#763]
#### Do you want to request a _feature_ or report a _bug_?
Both
#### What's the current behavior?
When there are 2 or more events for the same date/time, just one event is shown in the **Day** tab/view. I believe that it's happening because the approach using `position: absolute`.

In the image below, there are 2 events for the same date/time;
![image](https://user-images.githubusercontent.com/24215587/37431179-47bc71b6-27b3-11e8-80c7-ace5c5c914e4.png)

Changing the top property, shows up the other element:
![image](https://user-images.githubusercontent.com/24215587/37432751-3d65f7aa-27b8-11e8-8827-eed3faafe4ea.png)

**When could we have this scenario?**
For applications where there is an engagement form, and the engagement could be for **incoming** or **outgoing** events, or even a shared calendar where many engagements are scheduled to the same date/time for different person/reason.

#### What's the expected behavior?
Would be nice-to-have it in fit inside the line of the hour.

**Comment by DanZeuss** [comment]
even in the version .18, the error still persist.

**Comment by jquense** [comment]
Can you post a reproduction in codesandbox thanks!

**Comment by Yamin-lawar** [comment]
I am still getting the same error, is there any solution found?

**Comment by tobiasandersen** [comment]
I'll have a look if someone could provide a codesandbox.

**Comment by edrdesigner** [comment]
Attributes on Event: start and end dates are equals, start time is 09:00 , end time is 09:00 try to change it to: start: 09:00, end: 09:30.

**Comment by arecvlohe** [comment]
Fixed in #677 I think
