### ISSUE TITLE
Disable weekends

### ISSUE THREAD

**Issue by smajazayeri** [intljusticemission/react-big-calendar#764]
Hi there,

Does anyone know how to disable weekends?

**Comment by jquense** [comment]
use the 'work_week' view?

**Comment by willmurdoch** [comment]
I'm wondering too. I want to exclude weekends in the monthly view, afaik work_week is only for the weekly view.

**Comment by jawblia** [comment]
I managed to hide them in css: 
`````
/* Remove weekends in month view */
.rbc-month-header > :first-child,
.rbc-month-header > :last-child{
  display: none;
}

.rbc-row-segment {
    flex-basis: 20% !important;
    max-width: 20% !important;
}

.rbc-month-row > .rbc-row-bg > :first-child,
.rbc-month-row > .rbc-row-bg > :last-child {
  display: none;
}

.rbc-row-content > .rbc-row > .rbc-date-cell:first-child,
.rbc-row-content > .rbc-row > .rbc-date-cell:last-child {
  display:none;
}

**Comment by mpeng** [comment]
Using css to hide weekends in Month view cause the events not to align properly.

**Comment by cutterbl** [comment]
@nossair-additio You would have to create a [Custom View](http://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/guides-creating-custom-views--page)

**Comment by nossair-additio** [comment]
@cutterbl Thanks for your quick answer, I am creating a custom view, but I have a doubt on how I can modify the [rows limit](https://github.com/jquense/react-big-calendar/blob/master/src/Month.js#L29). 

I've seen an [example](https://github.com/jquense/react-big-calendar/issues/679#issuecomment-1346797179) from someone else, but I don't think it's good practice.

**Comment by InsaneRohit** [comment]
@nossair-additio @mpeng @willmurdoch  Can anyone help me in building Custom Month View to hide weekends ?
Is ther any solution for this?

**Comment by NicolasD27** [comment]
I have done a month view with only workdays : https://github.com/NicolasD27/react-big-calendar-workdays-month-view
it look like this : 
<img width="1500" alt="Capture d’écran 2024-10-23 à 10 30 16" src="https://github.com/user-attachments/assets/e84b5e4c-f126-47b4-831f-02cf43056daa">
