### ISSUE TITLE
All day events in Day and Week View

### ISSUE THREAD

**Issue by RaedsLab** [intljusticemission/react-big-calendar#765]
#### Do you want to request a _feature_ or report a _bug_?
Feature request
#### What's the current behavior?

When calendar has only "All day" events, the calendar (in week and day view) shows the events in "all day" section, but leaves the time section empty below.

#### What's the expected behavior?

I would like to be able to show only the "all day" view as the rest is just white space for me.

**Comment by jquense** [comment]
hey there! We probably won't add that to the library here since it's pretty specific to your use case, but you can accomplish it with custom views and reusing some of the libraries constituent components

**Comment by RaedsLab** [comment]
Hey, thanks for the response.

Thanks for the hint to custom views i missed the part where we could pass Components.

However, I don't think that this is really a specific thing as all day events are already supported by react-big-calendar. 

Maybe a boolean passed to TimeGrid?
