### ISSUE TITLE
Next/Prev give "Invalid Date"

### ISSUE THREAD

**Issue by npalansky** [intljusticemission/react-big-calendar#768]
#### Do you want to request a _feature_ or report a _bug_?
report a bug

#### What's the current behavior?
Clicking the next / prev button results in an "Invalid Date".  
Clicking on the today button before clicking next/prev fixes this 

Note: this bug only occurs in v0.18

**Comment by arecvlohe** [comment]
Duplicate of #718 I believe.

**Comment by arecvlohe** [comment]
Looks like there is a workaround for this at the moment. I am going to close.
