### ISSUE TITLE
Add loading state

### ISSUE THREAD

**Issue by RaedsLab** [intljusticemission/react-big-calendar#773]
#### Do you want to request a _feature_ or report a _bug_?

Feature request

#### What's the expected behavior?

Add  a _loading_ prop that would show a loading indicator on top of the calendar and prevent user interaction.

**Comment by tobiasandersen** [comment]
This sounds more like something you'd build yourself outside of the calendar. Or how/when would the calendar show it?

**Comment by RaedsLab** [comment]
I did, but it would be nice to just have a boolean to flip

**Comment by jquense** [comment]
It's not obvious to me that there is a good, general, UI/UX for that. I'm ok adding some defaults but in this case i don't most people would be happy with the default, regardless of what it is, since it'll be so specific to what your app wants.

**Comment by RaedsLab** [comment]
Agreed -maybe a HoC- but that would derail the lib. closing

**Comment by jordan-enev** [comment]
**I had a similar use-case:**
I just wanted to indicate somehow that the Calendar events are filtering or data is loading (waiting for back-end response).

**Here's my simple approach:**
I'm adding `filtering` class to the wrapper div of Calendar when I'm waiting for the new events (back-end response). This class manipulates the `opacity` of Calendar. it works smoothly, looks good and it is a very simple as implementation.

```
// CSS
.filtering  .rbc-time-view, .filtering .rbc-month-view {
  opacity: 0.5;
}

// React
<div className={isFiltering ? 'filtering' : null}>
    <Calendar {...rest} />
</div>
```

**Comment by MounirElAbbas** [comment]
> **I had a similar use-case:** I just wanted to indicate somehow that the Calendar events are filtering or data is loading (waiting for back-end response).
> 
> **Here's my simple approach:** I'm adding `filtering` class to the wrapper div of Calendar when I'm waiting for the new events (back-end response). This class manipulates the `opacity` of Calendar. it works smoothly, looks good and it is a very simple as implementation.
> 
> ```
> // CSS
> .filtering  .rbc-time-view, .filtering .rbc-month-view {
>   opacity: 0.5;
> }
> 
> // React
> <div className={isFiltering ? 'filtering' : null}>
>     <Calendar {...rest} />
> </div>
> ```


One step further, for a 'flashing' effect
`@keyframes flash-opacity {
  0%, 100% {
    opacity: 0.2;
  }
  50% {
    opacity: 0.8;
  }
}

.filtering .rbc-time-view,
.filtering .rbc-month-view {
  animation: flash-opacity 1s infinite;
}
`

**Comment by d-baranowski** [comment]
I have a valid use case. I have a custom toolbar with a pop up for filters. When filters change I render a skeleton which unmounts the toolbar which hides my pop up. That is bad ux. Would be nice to be able to pass a loading state and keep the toolbar mounted when loading.
