### ISSUE TITLE
Passed events displaying on Day view

### ISSUE THREAD

**Issue by daniwaxman** [intljusticemission/react-big-calendar#774]
#### Do you want to request a _feature_ or report a _bug_?
Bug report
#### What's the current behavior?

An event shows in the first available timeslot if the min prop is greater then event begin time.
https://codesandbox.io/s/lyy3zkm2kq

#### What's the expected behavior?

The expected behavior is that the event that has passed would not display at all.

**Comment by MuffinLightning** [comment]
Was this ever addressed? I seem to be experiencing this same issue
