### ISSUE TITLE
Custom rendering popup?

### ISSUE THREAD

**Issue by RaedsLab** [intljusticemission/react-big-calendar#775]
#### Do you want to request a _feature_ or report a _bug_?
Feature request 

#### What's the current behavior?

Popup component can't be overridden.
Events in popup are rendered the same way. 

#### What's the expected behavior?

Able to pass a custom popup component.

**Comment by lalithnarayan** [comment]
+1. Custom rendering of popup would be an interesting feature

**Comment by arecvlohe** [comment]
Happy to take PRs based on this idea!

**Comment by arecvlohe** [comment]
Closing in favor of #803
