### ISSUE TITLE
Add only days in week view.

### ISSUE THREAD

**Issue by uditparmar23** [intljusticemission/react-big-calendar#776]
In week view it shoe date and day both. I just need to show day not with date. Is it possible to show only days without date in week View ?????????

**Comment by arecvlohe** [comment]
Can you not pass down a custom header component on the day view?
http://intljusticemission.github.io/react-big-calendar/examples/index.html#prop-components

**Comment by arecvlohe** [comment]
Or you can use formats to format the day header: http://intljusticemission.github.io/react-big-calendar/examples/index.html#prop-formats

**Comment by uditparmar23** [comment]
format day header works for me thank you so much for quick reply and very useful suggestion.

**Comment by josh-g3** [comment]
@arecvlohe The prop components approach in your first response doesn't seem to be working unless I'm getting the prop name wrong
