### ISSUE TITLE
Changelog 

### ISSUE THREAD

**Issue by TimNZ** [intljusticemission/react-big-calendar#777]
Can you please list changes in the changelog.

**Comment by jquense** [comment]
We don't always have time to do that, you can scan over the commit history since the last tag or merged PRs thanks!

**Comment by TimNZ** [comment]
@jquense  Not enough time to write a single line in the changelog after the substantially more time spent on doing dev or submitting/reviewing a PR?

Forcing us to individually to spend substantially more time reviewing commits (which is what I did before I created this issue).

Lazy, brother! 

You got 1700+ stars, not an insignificant number of people are using this. 
Thanks for making it.

**Comment by jquense** [comment]
Sorry you seem to be confusing us your paid employees, and not the volunteer's who work on this in there spare time at the expense of other things.

Take your entitlement and shove it. No one here owes you thing, and they certainly don't need to sit here and be called lazy, by someone benefiting from their free work. Who, I might add, can't be bothered to spend 4 min glancing over recently closed PRs.
