### ISSUE TITLE
getSlotMetrics throws RangeError in IE11

### ISSUE THREAD

**Issue by marwej** [intljusticemission/react-big-calendar#779]
More of a question: Is react-big-calendar supposed to support IE11? I see "IE10+" in the README but a "no"-answer would be fine.

We are hoping to drop support due to all problems, but currently one of our customers is using it. We notice a problem in IE11 with the new 0.19 version and investigating the issue I found that I cannot access the page http://intljusticemission.github.io/react-big-calendar/examples/index.html with IE11 either.

**Comment by jquense** [comment]
The core library, (add-ons less so) should support ie11 but there is no active testing on it. We're happy to fix stuff as it comes up, the docs page may not work for unrelated reasons

**Comment by marwej** [comment]
Ok, great. This line throws an Exception:

https://github.com/intljusticemission/react-big-calendar/blob/8bebff1dc51c98744deaee4f0f94f435991cc4a8/src/utils/TimeSlots.js#L24

RangeError: Array length must be a finite positive integer
Argument seems to be a large negative number.

**Comment by marwej** [comment]
Managed to find some more info now. It was NaN

In Chrome: totalMin = 720 step = 60 timeslots = 2 numGroups = 6
In IE11: totalMin = NaN step = 60 timeslots = 2 numGroups = NaN

**Comment by jquense** [comment]
Ok so the problem seems like it's earlier in the totalMin calculation. Thanks for helping track this down, i don't have a lot of access to IE11 at the moment

**Comment by marwej** [comment]
Yes, the start and end date seems to be invalid. TBC...

**Comment by marwej** [comment]
Ah, sorry, it seems to be my Date() constructions... String arguments doesn't work in IE. My bad.
