### ISSUE TITLE
Calendar first day of week changed to Saturday without provocation

### ISSUE THREAD

**Issue by harel** [intljusticemission/react-big-calendar#78]
**NOTE** : I've discoverd the reason but leaving the ticket as is - see both edits at the bottom - I do think its a bug in the Calendar code. 

My Calendar is loaded with an "en-GB" locale. Globalize is used as the localizer. Everything was working fine until today I noticed the calendar has switched from starting the week on Monday as it should for this locale, to starting it on Saturday (as no locale I can think of does). 
I've been trying to figure out what has changed (it was fine yesterday). I've tried upgrading Globalize/CLDR to the latest versions, as well as ensuring the "en-GB" culture is provided and changing my localization of the calendar from 

```
BigCalendar.globalizeLocalizer(locale)
```

to 

```
localizer(Globalize)
```

(as I see now in the examples), but nothing seems to revert it back to start the week on Monday. 

![image](https://cloud.githubusercontent.com/assets/985978/14412338/78bdcad8-ff58-11e5-8eed-1cac89dec088.png)

What could cause this all of the sudden?
**Edit:** I've confirmed via a screenshot I sent last night that it was indeed fine and started the week on monday. Today when I opened my laptop and reloaded the page it flipped to Saturday. 

**Edit 2:**
At first I thought it was too far fetched to mention, but I've just tried to move my clock a day forward and it fixed it! There is something either on "Sunday" or today's date that causes the calendar to start on Saturday. I cannot replicate this on the Demo site. 

Thanks!

**Comment by harel** [comment]
And at the stroke of midnight, the calendar "righted" itself and reverted back to Monday as first day of the week.

**Comment by jquense** [comment]
that is a very weird issue... honestly I have idea what might have caused it.

**Comment by harel** [comment]
This was tested on multiple computers/OSes by the way and by myself in the UK and my partner in the West Coast (PST). Both of us saw the calendar in the same way during yesterday. I've never seen anything like it

**Comment by harel** [comment]
I can confirm that every Sunday, the calendar flips to having Saturday as the starting day of the week in my calendar. This is a calendar initialised to the en-UK locale, using Globalize. Its fine all week, except on Sundays where it goes crazy.

**Comment by harel** [comment]
This could very well be a problem in Globalize. 
When ``userlocale`` is a Globalize object loaded with 'en-UK' locale: 

```
// On any non sunday day:
userlocale.formatDate(new Date(), {raw:'e'});
> "2"
```

```
// On a sunday :
userlocale.formatDate(new Date(), {raw:'e'});
> "7"
```

**Comment by harel** [comment]
Opened a ticket with Globalize as well: https://github.com/jquery/globalize/issues/608

**Comment by harel** [comment]
@jquense I've found the problem is coming out of the ```firstOfWeek``` function here: https://github.com/intljusticemission/react-big-calendar/blob/master/src/localizers/globalize.js#L40.

For the en-GB (didn't check other locales) it returns the correct value of 1 unless 'today' is sunday where it returns '6'. 

```
// on any day of the week except sunday:
firstOfWeek('en-GB');
> 1
```

However  

```
// on any given Sunday
firstOfWeek('en-GB');
> 6
```

Something in the calculations done there based on the current date is breaking up...

**Comment by harel** [comment]
@jquense , why not use something like 

```
> locale.cldr.supplemental.weekData.firstDay()
> "mon"
```

to get the first day of the week for the given locale?

**Comment by jquense** [comment]
mostly because I couldn't figure out how to do that :P PR?

**Comment by harel** [comment]
I'll be happy to. Coming right up!

**Comment by harel** [comment]
@jquense I hope you can help with one detail, as I've never done it this way before: 
I've done my fix on a fork. I'm not trying to install the package into my project from github. It all seems ok, but when the ```npm install``` finishes, my node_moduels/react-big-calendar directory contains just the README/LICENSE files, package.json and node_moduels of its own with just react-overlays package in it.  Am I missing something? Is there another step because i'm installing from github?

**Comment by harel** [comment]
@jquense turns out the whole project cannot be installed via github because of an issue in packages.json file. I update that as well in the PR, which also resolves the issue of first week day.
