### ISSUE TITLE
Improve docs

### ISSUE THREAD

**Issue by tpater** [intljusticemission/react-big-calendar#780]
Hi there, nice work on the calendar! Just started to use it and found out issues with bootstrapping the component. I'm talking about setting localizers. In your **Getting started** section of demo app you suggest using `BigCalendar.momentLocalizer(moment)` format, on master **Readme** there's `BigCalendar.setLocalizer(BigCalendar.momentLocalizer(moment))`, and in the demo app there's third option introduced: `localizer(globalize)`. Which one of them is correct? :) Can you make it aligned with the docs? Cheers & keep up the good work!

If you point a preferred way I can come up with an PR.

**Comment by tobiasandersen** [comment]
Hi! Either one is fine, both moment and gloablize are supported!

**Comment by pellea** [comment]
`BigCalendar.setLocalizer(BigCalendar.momentLocalizer(moment))` doesn't work. The `setLocalizer` is not in type definition either. How can we use a custom localizer?

**Comment by jquense** [comment]
you use `BigCalendar.setLocalizer(localizer)` i'd read the source code for the the two localizers to see how to do it

**Comment by tpater** [comment]
I find it very useful when using some external APIs authors set one clean approach :) Just a suggestion to align it everywhere on docs.

**Comment by pellea** [comment]
@jquense What I understand from the code is that there is no type definition available that allow me to set a custom localizer (I use TypeScript). Am I wrong?

I can't agree more with @tpater .

**Comment by jquense** [comment]
@pellea I can't really speak to that, we don't maintain or control the type defs, they may be wrong on DT

**Comment by jquense** [comment]
Happy to take PRs for the docs y'all for stuff you think is unclear :)

**Comment by karltaylor** [comment]
+1 for improve docs. Will try and make a few PR's to make things a bit clearly that I found confusing at first! 👍
