### ISSUE TITLE
.17 -> .18 initialization

### ISSUE THREAD

**Issue by hunterpankey** [intljusticemission/react-big-calendar#781]
#### Do you want to request a _feature_ or report a _bug_?
bug

#### What's the current behavior?
.17 initializes correctly with:

```
import * as moment from 'moment';
import BigCalendar from 'react-big-calendar';
```

and then

`BigCalendar.momentLocalizer(moment);`

But when I use .18, the BigCalendar variable isn't initialized, so the momentLocalizer method doesn't exist and it throws an error that BigCalendar is undefined. Did something change from .17 to .18 that changed the initialization?

#### What's the expected behavior?

BigCalendar object should be initialized and ready to render.

Sorry for the relative paucity of details. Given that this issue is with the barest beginning of use, I feel like it's pretty quick to reproduce.

**Comment by hunterpankey** [comment]
**Update:** 
Typescript 2.4.2
Compiling to es5 target
SPFx yeoman generator for SharePoint

**Comment by arecvlohe** [comment]
Is this still an issue? Seems to work fine with .19.

**Comment by ggsjyoon** [comment]
I had the issue with `.19`

**Comment by dsinghvi** [comment]
How are you guys dealing with this now ?

**Comment by hunterpankey** [comment]
I rolled back to .17 in my project and it's going fine. I was inclined to
just leave it because all of the functionality that I need is there, but
I'll try .19 at some point and confirm that we're back to normal.

**Comment by josdejong** [comment]
Same issue here using a react+typescript application (`create-react-app` with `react-scripts-ts`).

As a workaround I use `require` instead of `import`:
```js
const BigCalendar = require('react-big-calendar')
```

**Comment by ggsjyoon** [comment]
I'll try `require` instead of `import` on the latest version. I also use `react-scripts-ts`

**Comment by josdejong** [comment]
>  I also use react-scripts-ts

In that case you probably also want to add a tslint ignore line:

```js
// tslint:disable-next-line
const BigCalendar = require('react-big-calendar')
```

:)

**Comment by ggsjyoon** [comment]
It's okay. I'm not using `no-var-requires`.

**Comment by Goregut** [comment]
Can confirm on 0.19.2 require works. Thanks @josdejong ! We're running react and typescript here as well.

**Comment by josdejong** [comment]
Great! I can confirm too that import works in `0.19.2`:

```js
import BigCalendar from 'react-big-calendar'
```

:+1:  thanks guys!

**Comment by josdejong** [comment]
UPDATE: sorry, turns out it still only works in develop mode, not in production bundles :(

**Comment by Distil62** [comment]
Same issue :,(

**Comment by cjduncana** [comment]
Still a problem in v0.20.3

**Comment by PeterYangIO** [comment]
For me it works in `v0.20.3` but does not work in `v0.20.4` with a React and TypeScript combination. Did this issue come back for anyone else?

I am importing as such
```ts
import * as moment from "moment";
const BigCalendar = require("react-big-calendar");
```

**Comment by ZakRabe** [comment]
We've bumped to 0.20.4, and we use this syntax to import the component with the moment localizer, instead of the require syntax.

```
import * as moment from 'moment';
import BigCalendar, { BigCalendarProps, Navigate } from 'react-big-calendar';
import * as withDragAndDrop from 'react-big-calendar/lib/addons/dragAndDrop';
const DragAndDropCalendar = withDragAndDrop(BigCalendar);
...
 <DragAndDropCalendar
    localizer={BigCalendar.momentLocalizer(moment)}
/>
```

**Comment by PeterYangIO** [comment]
Using the solution that @ZakRabe provided seems to work for me.

**Comment by cjduncana** [comment]
I just bumped to v0.20.4 and get the following error if I follow @ZakRabe advice:
`TypeError: Cannot read property 'momentLocalizer' of undefined`

``` typescript
import Calendar, { Components, View } from 'react-big-calendar';

const localizer = Calendar.momentLocalizer(moment);
```
