### ISSUE TITLE
Feature request: Business Hours

### ISSUE THREAD

**Issue by padsbanger** [intljusticemission/react-big-calendar#783]
Hello,

Fullcalendar has na option to set up working hours. Would be nice if we could have this options here too 😄 

https://fullcalendar.io/docs/business-hours

**Comment by jquense** [comment]
I think you can use min and Max to accomplish this?

**Comment by padsbanger** [comment]
Oh, sorry, didnt notice this. Is it possible to set up diffrent buissness hours for each day of the week ?

**Comment by jelly** [comment]
Would it be possible to 'zoom' in to the current business hours which min/max does but allowing the user to scroll up and down to view appointments outside of the business hour range.

**Comment by HartiganHM** [comment]
I'll hop on this bandwagon. I'm working on a use case where the min and max will be set based on one hour outside of the respective daily store hours.

This is fine on a day view, but on a week view, I'm taking the earliest week min and the latest week max to set the base parameters. I'm then looking to 'gray out' time slots based on what each day's respective min and max are per the store hours.

Example:
```
Monday: 8 AM - 5 PM
Tuesday: 9 AM - 7 PM

<RBC
  date={Monday}
  defaultView={'week'}
  min={8 AM}
  max={7 PM}
/>
```

Here, the overall week would have the min/max limits, but Monday and Tuesday would know their respective ranges.

Any advice/help is appreciated. Thanks!
