### ISSUE TITLE
There is no month view

### ISSUE THREAD

**Issue by jayzabs** [intljusticemission/react-big-calendar#79]
I am having a problem with the month view. the week, day and agenda view is doing fine. I am not sure on why there is no events or even rows and columns for the month view. Below is my Code and a screenshot of month view. I have imported the css on a different file.
<img width="1211" alt="screen shot 2016-04-11 at 11 57 47 am" src="https://cloud.githubusercontent.com/assets/6244798/14416431/a52a72a4-ffdc-11e5-9af1-ad1fe9b218c9.png">

```

class CalendarPage extends Component {
  componentWillMount() {
  BigCalendar.setLocalizer(
    BigCalendar.momentLocalizer(moment)
  );

    }  


  render() {  
    const date = moment('2015-10-21');
    const events = [{
    "title": "All Day Event",
    "allDay": true,
    "start": new Date(2015, 3, 0),
    "end": new Date(2015, 3, 0)
  },
  {
    "title": "Long Event",
    "start": new Date(2015, 3, 7),
    "end": new Date(2015, 3, 10),
  },
  {
    "title": "Some Event",
    "start": new Date(2015, 3, 9, 0, 0, 0),
    "end": new Date(2015, 3, 9, 0, 0, 0),
  },
  {
    "title": "Conference",
    "start": new Date(2015, 3, 11),
    "end": new Date(2015, 3, 13),
    desc: 'Big conference for important people'
  },
  {
    "title": "Meeting",
    "start": new Date(2015, 3, 12, 10, 30, 0, 0),
    "end": new Date(2015, 3, 12, 12, 30, 0, 0),
    desc: 'Pre-meeting meeting, to prepare for the meeting'
  },
  {
    "title": "Lunch",
    "start":new Date(2015, 3, 12, 12, 0, 0, 0),
    "end": new Date(2015, 3, 12, 13, 0, 0, 0),
    desc: 'Power lunch'
  },
  {
    "title": "Meeting",
    "start":new Date(2015, 3, 12,14, 0, 0, 0),
    "end": new Date(2015, 3, 12,15, 0, 0, 0)
  },
  {
    "title": "Happy Hour",
    "start":new Date(2015, 3, 12, 17, 0, 0, 0),
    "end": new Date(2015, 3, 12, 17, 30, 0, 0),
    desc: "Most important meal of the day"
  },
  {
    "title": "Dinner",
    "start":new Date(2015, 3, 12, 20, 0, 0, 0),
    "end": new Date(2015, 3, 12, 21, 0, 0, 0)
  },
  {
    "title": "Birthday Party",
    "start":new Date(2015, 3, 13, 7, 0, 0),
    "end": new Date(2015, 3, 13, 10, 30, 0)
  }]

    return (
      <div style={{ padding: '1% 0 0 3%'}}>
        <BigCalendar
          events={events}
          defaultView='month'
          defaultDate={new Date(2015, 3, 1)}
        />
      </div>
    )
  }

}


export default withStyles(CalendarPage, s)
```

**Comment by jayzabs** [comment]
removing `rbc-month-view` in the css file fixes the issue but the height is a bit weird. setting the height: 100%; does nothing and I am assuming this is the cause of it?

**Comment by jayzabs** [comment]
fixed it by changing `rbc-month-view {display: flex;}` to `rbc-month-view {display: block;}`

**Comment by jayzabs** [comment]
now my question is how to set its height? the view for every box is a bit small. it can only contain 1 item. I want it to contain to at least 3-5 items
<img width="1206" alt="screen shot 2016-04-11 at 2 13 26 pm" src="https://cloud.githubusercontent.com/assets/6244798/14418252/970cd2ee-ffef-11e5-969c-179b2340fe5f.png">

**Comment by jayzabs** [comment]
I have solved my problem. Creating new issue as I am facing a new one

**Comment by jquense** [comment]
hi, leave the styles of the month view alone and just set an explicit height on the calendar per the documentation.
