### ISSUE TITLE
v0.19 has layout bug

### ISSUE THREAD

**Issue by gimdongwoo** [intljusticemission/react-big-calendar#792]
#### Do you want to request a _feature_ or report a _bug_?
_bug_

#### What's the current behavior?
v0.19
![2018-03-31 12 34 38](https://user-images.githubusercontent.com/7310854/38159279-17e573ea-34e0-11e8-88eb-01e6ed689bc0.png)

#### What's the expected behavior?
v0.18
![2018-03-31 12 36 21](https://user-images.githubusercontent.com/7310854/38159283-27b3cd1c-34e0-11e8-8cc6-3c7d0660a9a9.png)

Width is not set in cell.
```
// v0.18
<div class="rbc-date-cell rbc-off-range" style="flex-basis: 14.2857%; max-width: 14.2857%;"><a href="#">25</a></div>
// v0.19
<div class="rbc-date-cell rbc-off-range"><a href="#">25</a></div>
```

Thank you!

**Comment by jquense** [comment]
Can you put together a reproduction in the code sandbox template?

**Comment by BilalBudhani** [comment]
@jquense Have a look at this https://codesandbox.io/s/kwxjmo69po

**Comment by jquense** [comment]
@BilalBudhani that is because you haven't provided a height to the calendar

**Comment by BilalBudhani** [comment]
@jquense Oh, I see! Thanks for helping me out.
