### ISSUE TITLE
V0.19 don't have 'all day' label in the row and have duplicate 12:00 AM 1:00 AM

### ISSUE THREAD

**Issue by Tim1023** [intljusticemission/react-big-calendar#793]
V0.19 don't have 'all day' label in the row and have duplicate 12:00 AM 1:00 AM

You can see it through:

$ git clone git@github.com:intljusticemission/react-big-calendar.git
$ cd react-big-calendar
$ npm install
$ npm run examples
Open localhost:3000/examples/index.html.

**Comment by jquense** [comment]
Yes we removed the label to avoid having to do a runtime width check, and it didn't add much ux-wise.

**Comment by jquense** [comment]
That sounds like a bug but I can't check it right now. Can you use the codesandbox template to reproduce it here?
