### ISSUE TITLE
"Uncaught TypeError: _onDoubleClick is not a function" when trying to double click event from popup

### ISSUE THREAD

**Issue by lalithnarayan** [intljusticemission/react-big-calendar#794]
I'm currently on Version 0.0.3 

![screen shot 2018-04-02 at 1 23 07 pm](https://user-images.githubusercontent.com/11024780/38188834-3e9641c6-367b-11e8-97e5-c3f268d05a27.png)

It looks like its resolved in #694 but isn't reflecting. Please check

Thanks in Advance

**Comment by jquense** [comment]
can you upgrade to the latest version?

**Comment by arecvlohe** [comment]
@lalithnarayan Have you updated?

**Comment by lalithnarayan** [comment]
@arecvlohe  yaa I did it works :)
