### ISSUE TITLE
change background color of selected date

### ISSUE THREAD

**Issue by dubstylee** [intljusticemission/react-big-calendar#796]
#### Do you want to request a _feature_ or report a _bug_?
feature

#### What's the current behavior?
The background color of the current date is styled with rbc-today, when on the month view, there is no way to distinguish between the other days of the month and the "selected" date.

For example, clicking on "4/1/18" will set the date property of the calendar, but does not apply any different style to that cell.

Also, is there a way to get the selected date besides "onNavigate" event? I tried onSelectSlot and onSelectEvent, but those are not fired when clicking on a date.

#### What's the expected behavior?
Clicking on a date (changing the calendar's date property) to add some style to the selected date. Of course, this can be customizable so that you can style selected-date the same as a regular date.

**Comment by jquense** [comment]
There should be a class on the current date you can style

**Comment by mikeyc7m** [comment]
`.rbc-day-bg.rbc-today` gives you access to the background of today's cell. Good times!

`.rbc-date-cell.rbc-current` only gives you access to the date link of the selected cell. You can fake a background using this:

```css
.rbc-date-cell.rbc-current::after {
    content: "";
    position: absolute;
    background: red; /* use whatever colour your little heart desires */
    z-index: -1;
    height: 100%;
    width: 14.2857%;
    margin-left: calc(-14.2857% + 8px); /* I had an 8px offset */
    margin-top: -8px; /* I had an 8px offset */
}

**Comment by dubstylee** [comment]
@mikeyc7m  thanks, that does work great! It only applies to the header of the cell though, where the date is. Have you found a way to get the background of the entire cell? .rbc-day-bg.rbc-current and .rbc-day-bg.rbc-current::after didn't work. For now, your suggestion will work for what I'm trying to do though. Much appreciated!

**Comment by dubstylee** [comment]
I was actually able to get the desired effect by changing the height of the element to 105px to match the height of the row of the calendar. That will do, I'll check back in if I run into any issues with that solution.

**Comment by kusalhasintha** [comment]
Hello,

I want to change the full column color, as an example - Whole Saturday column to be in a different color. How can I do it?

**Comment by khoibuda2504** [comment]
hi bro!
Let's try to use dayPropGetter prop to our Calendar
`date={dateValue}`
`onNavigate={date => setDateValue(date)}`
`
dayPropGetter={date => (moment(date).format('DD') === moment(dateValue).format('DD')) && ({
          className: 'rbc-selected-day'
        })}
`
dateValue is my state, for example
`const [dateValue, setDateValue] = useState(moment())`

**Comment by khoibuda2504** [comment]
> Hello,
> 
> I want to change the full column color, as an example - Whole Saturday column to be in a different color. How can I do it?

hi bro, let's refer to this docs https://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/props--day-prop-getter
