### ISSUE TITLE
List of items for the month view is only 1

### ISSUE THREAD

**Issue by jayzabs** [intljusticemission/react-big-calendar#80]
How Can I have more items for a day for the month view? the view for every box is a bit small. it can only contain 1 item. I want it to contain to at least 3-5 items
<img width="1206" alt="screen shot 2016-04-11 at 2 13 26 pm" src="https://cloud.githubusercontent.com/assets/6244798/14418384/bb32edd8-fff0-11e5-972d-382671c0b722.png">

**Comment by jayzabs** [comment]
Whenever I set the height for `.rbc-month-view` there will be a space after the first row. Refer to the image below.
<img width="1197" alt="screen shot 2016-04-11 at 2 53 52 pm" src="https://cloud.githubusercontent.com/assets/6244798/14419004/3e6024ba-fff5-11e5-9bbe-caa363359e00.png">

**Comment by jquense** [comment]
set the height of the calendar to a minimum that fits more than 2 rows. like in the doc examples
