### ISSUE TITLE
Please release new version

### ISSUE THREAD

**Issue by gregeinfrank** [intljusticemission/react-big-calendar#800]
#### Do you want to request a _feature_ or report a _bug_?

Release

#### What's the current behavior?

There's a bug fix in `master` that I want to pull into my project, could you please release a new version? Thanks!!

**Comment by arecvlohe** [comment]
Is this really an issue? Seems like more of a request. Versions get bumped every few weeks so not sure if this will work for you in time but you are more than free to fork the repo and update the project internals.
