### ISSUE TITLE
Css link "+X more"

### ISSUE THREAD

**Issue by afgoulart** [intljusticemission/react-big-calendar#802]
#### Do you want to request a _feature_ or report a _bug_?
Report a bug

#### What's the current behavior?
I have many events in two days consecutive, the link for open "+2 more" is css broken.
I'm using the last version ("react-big-calendar": "^0.19.0").

![image](https://user-images.githubusercontent.com/273370/38731616-713d9bfa-3ef1-11e8-9f79-2859f5ccfcf8.png)

#### What's the expected behavior?
I expected the links inside of the days boxes

![image](https://user-images.githubusercontent.com/273370/38731876-76efede0-3ef2-11e8-8b97-309a657a52da.png)

**Comment by mikeyc7m** [comment]
+1

**Comment by elkinjosetm** [comment]
+1

**Comment by jquense** [comment]
I don't think so, we may need a release tho
