### ISSUE TITLE
Enable support per-event dragability/sizability

### ISSUE THREAD

**Issue by dbuchet-bandc** [intljusticemission/react-big-calendar#805]
The code to enable per-event dragability is already implemented but is commented.
Please remove the comment, so we'll be able to set a `draggable` key on each event to allow or prevent draging

https://github.com/intljusticemission/react-big-calendar/blob/master/src/addons/dragAndDrop/DraggableEventWrapper.js#L138

**Comment by arecvlohe** [comment]
This seems like a good idea. @dbuchet-bandc Can you submit a PR? Then we can get the ball rolling on this.

**Comment by dbuchet-bandc** [comment]
Done here https://github.com/intljusticemission/react-big-calendar/pull/808

Thanks :)

**Comment by arecvlohe** [comment]
We will move the conversation over to the PR.
