### ISSUE TITLE
Month View doesn't render

### ISSUE THREAD

**Issue by DavidTNguyen** [intljusticemission/react-big-calendar#806]
My configuration seem to only render the 'agenda' view, but not 'month'.  What did I miss?

` <BigCalendar
  events={actionItems}
 titleAccessor="name"
 step={30}
                  defaultDate={new Date()}
                  startAccessor="startDate"
                  endAccessor="endDate"
                  resources={actionItems.contributors}
                  resourceIdAccessor="id"
                  resourceTitleAccessor="name"
                />`

**Comment by jquense** [comment]
you need to provide a height to the calendar. In general please search issues, this has been addressed like 100 times

**Comment by RaedsLab** [comment]
@jquense maybe even a better idea. get the height to have a default value? (window.height) or Have the component throw a very violent error if its not provided.
