### ISSUE TITLE
possible to disable show more?

### ISSUE THREAD

**Issue by umarrg97** [intljusticemission/react-big-calendar#811]
Hi, just got to grips with big calendar. great library btw. im running into an issue where the show more button hides my events. is it possible to disable this? and just have my list of events on the same day. (only need to display 3 event groups)

**Comment by jquense** [comment]
there is no way to disable it, best you can due is make your calendar tall enough that they are all visible, you can search for previous issues for a few explanations on why it works the current way. thanks!

**Comment by ZeeshanAhmadKhalil** [comment]
My Calendar is scrollable but after 6 events it shows "Show more"

**Comment by Gbgourav** [comment]
Hi, did you got the answer?? I'm facing the same problem, can't we disable more option ???

**Comment by cutterbl** [comment]
You can use the [showAllEvents](http://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/props--show-all-events) prop...

**Comment by Susenthiran28** [comment]
There is a way to hide the show more option in react-big-calendar.
<Calendar
                className='w-full !h-full text-inputTextSize flex flex-col'
                localizer={localizer}
                events={updatedList}
                views={['month', 'week', 'day']}
                components={components}
                messages={{
                    showMore: (total, remainingEvents, events) => {
                       return " ";
                    }
                }}
                startAccessor='start'
                endAccessor='end'
                eventPropGetter={customEventPropGetter}
                onSelectEvent={(event) => console.log('Selected event:', event)}
                onSelectSlot={(slotInfo) => console.log('Selected slot:', slotInfo)}
            />
            
           add messages props inside showMore function and return the empy string. Its remove the show more option
