### ISSUE TITLE
Ability to avoid adjacent events overlapping in day view

### ISSUE THREAD

**Issue by alliuca** [intljusticemission/react-big-calendar#814]
Hi, is there any way to have the events in the same row not to overlap but display next to each other in a flexbox fashion? It seems like the final width/left values always account for that.

Here's my sandbox: https://codesandbox.io/s/wq117r3yr8. I'd like those three events to be 33.33% wide in relation to the row's width, so that they appear next to each other.

react-big-calendar v0.19.0

**Comment by alliuca** [comment]
think I achieved that using css grid
https://codesandbox.io/s/zqk8vmqn3m

still wonder if something can be done within react-big-calendar

**Comment by jquense** [comment]
There isn't a way to adjust how RBC does layout at the moment, tho we've talked about making it pluggable. RBC picked a layout strategy that we think is useful and appropriate for a wide variety of cases, like having lots of events in a day, and we're happy with the results generally.
