### ISSUE TITLE
Issues showing past events in calendar

### ISSUE THREAD

**Issue by ashishbrst** [intljusticemission/react-big-calendar#815]
Hello,

I am facing the issue to show events from google calender into react-big-calendar

I'm  not able to get past endtime events. e.g. if I have events with time 5:00pm to 5:30pm and current time is 5:45pm then events are not showing on agenda calender. If I change the event end time 5:30 to 6:00pm then it starts showing. 

I need to show all events past and upcoming. 

-- Google calender screen-shot http://prntscr.com/j7sygr
-- Event not showing on agenda calender in 18 april http://prntscr.com/j7sz0w
http://prntscr.com/j7tmc2

      <BigCalendar
        style={{height: '450px'}}
        events={this.state.events}
		defaultDate={new Date()}
		defaultView="agenda"
		
      />

	  

Thanks in advance..!!

**Comment by xijun** [comment]
I have the same problem, hope we can have an answer as soon as possible

**Comment by mikeyc7m** [comment]
i got around the problem by sending the date prop as start-of-day. the agenda tries to omit events that have already happened today.
defaultDate={new Date(moment().startOf('day'))}

**Comment by xijun** [comment]
Thank you, I think that fixed the problem.

**Comment by mikeyc7m** [comment]
it just hides the problem - the agenda should hide today's past events and show those past events when navigating back. or maybe it is better to see everything for the current day?

**Comment by jquense** [comment]
it's probably a math bug, anyone care to submit a PR?

**Comment by silentsakky** [comment]
Looks like https://github.com/intljusticemission/react-big-calendar/pull/850 should fix this issue

**Comment by arecvlohe** [comment]
This has a couple solutions already related. Open to a PR if this specific problem is not fixed.
