### ISSUE TITLE
custom toolbar

### ISSUE THREAD

**Issue by seoyunho** [intljusticemission/react-big-calendar#818]
Hello I was using a react-big-calendar on my project
While I was using it, I needed to do onclick on the toolbar, so I customized the toolbar
I created a class named CustomToolbar and passed the class with props, but I got the following error:
```
Warning: Failed prop type: You have provided a `view` prop to `Calendar` without an `onView` handler. This will render a read-only field. If the field should be mutable use `defaultView`. Otherwise, set `onView`
    in Uncontrolled(Calendar) (created by Calendar)
    in Calendar (created by Uncontrolled(Calendar))
    in Uncontrolled(Calendar) (at Calendar.js:19)
    in div (at Calendar.js:18)
    in div (at Calendar.js:17)
    in Calendar (at AssignmentSection.js:10)
    in div (at AssignmentSection.js:9)
    in AssignmentSection (at Main.js:15)
    in div (at Main.js:13)
    in Main (created by RouterContext)
    in div (at DefaultLayout.js:12)
    in DefaultLayout (created by RouterContext)
    in RouterContext (created by Router)
    in Router (at index.js:10)
    in MainProvider (at index.js:9)
```
How can we solve this problem?

this is my code:
```js
import React from 'react';
import BigCalendar from 'react-big-calendar';
import Toolbar from 'react-big-calendar';
import moment from 'moment';
import 'react-big-calendar/lib/css/react-big-calendar.css';
import '../../css/calendar.css';

BigCalendar.momentLocalizer(moment);

const Calendar = ({ state, selectDate, selectEvent }) => {
  const eventStyleGetter = (event, start, end, isSelected) => {
    return { 
      style: { backgroundColor: event.color } 
    }
  } 
  return (
    <div id="calendar-section">
      <div id="calendar-wrapper">
        <BigCalendar
          selectable
          views = {['month']}
          defaultView = "month"
          defaultDate = {new Date()}
          components = {{toolbar : CustomToolbar}}
          onSelectSlot = {selectDate}
          onSelectEvent = {selectEvent}
          eventPropGetter = {(eventStyleGetter)}
          events = {state.assignments[state.subjects[state.selectedSubject]]}
        />
      </div>
    </div>
  )
}

class CustomToolbar extends Toolbar {
  render() {
    return (
      <div className='rbc-toolbar'>
        <span className="rbc-btn-group">
          <button type="button" onClick={() => this.navigate('TODAY')} >today</button>
          <button type="button" onClick={() => this.navigate('PREV')}>back</button>
          <button type="button" onClick={() => this.navigate('NEXT')}>next</button>
        </span>
        <span className="rbc-toolbar-label">{this.props.label}</span>
      </div>
    );
  }

  navigate = action => {
    console.log(action);
    
    this.props.onNavigate(action)
  }
}

export default Calendar;
```

**Comment by mikeyc7m** [comment]
view = view => {
    this.props.onViewChange(view);
  };

**Comment by jquense** [comment]
no need to be snarky...

@seoyunho yes provide the `onView` prop like you would an `onChange` and `value` prop for a controlled input, they work similarly. The calendar also has it's own moments when it wants to navigate and you should be listening for them, even with a custom toolbar.

**Comment by pixelwhip** [comment]
I was able to create a custom Toolbar component by extending the default Toolbar component and overriding the render method. In order to properly import the default component I had to use the following import statement. 

`import Toolbar from 'react-big-calendar/lib/Toolbar';`

I don't think the import statement in the OP would work. At least it didn't for me.

**Comment by GavinThomas1192** [comment]
@jquense Can we please have a custom toolbar example put in the docs? I am getting this same error, and have searched for a while, I am fundamentally missing something. Can you provide a link to the source code where I can find an example where you provide the onView prop?

**Comment by sittmannkatia** [comment]
I am also having this issue. I have an onView provided to the BigCalendar component but when I pass in a custom toolbar, I start seeing this error. How can I fix it?

**Comment by sittmannkatia** [comment]
@jquense Any help with this one? This is what my current Calendar component looks like:

```
<BigCalendar
              events={this.state.events}
              date={moment(this.state.currentDate).toDate()}
              onNavigate={() => {}}
              components={
                {
                  toolbar: BIToolbar({
                    onMonthChange: this.onMonthChange,
                  }),
                }
              }
              view={defaultView}
              views={['month', 'agenda']}
              onView={() => {}}
              formats={formats}
              onSelectEvent={event => this.selectEvent(event)}
            />
```

Everything works fine until I added in the custom component for the toolbar. Now I keep getting this error:

<img width="1076" alt="error" src="https://user-images.githubusercontent.com/5580517/44545804-a7ea5100-a6db-11e8-8845-30c610706825.PNG">

I've also tried passed an onView to the toolbar component too but it hasn't worked. Any ideas?

**Comment by wangdicoder** [comment]
The code below is working for me.

```
import React from 'react';
import Toolbar from 'react-big-calendar/lib/Toolbar';

export default class CalendarToolbar extends Toolbar {

	componentDidMount() {
		const view = this.props.view;
		console.log(view)
	}

	render() {
		return (
			<div>
				<div className="rbc-btn-group">
					<button type="button" onClick={() => this.navigate('TODAY')}>today</button>
					<button type="button" onClick={() => this.navigate('PREV')}>back</button>
					<button type="button" onClick={() => this.navigate('NEXT')}>next</button>
				</div>
				<div className="rbc-toolbar-label">{this.props.label}</div>
				<div className="rbc-btn-group">
					<button type="button" onClick={this.view.bind(null, 'month')}>Month</button>
					<button type="button" onClick={this.view.bind(null, 'week')}>Week</button>
					<button type="button" onClick={this.view.bind(null, 'day')}>Day</button>
					<button type="button" onClick={this.view.bind(null, 'agenda')}>Agenda</button>
				</div>
			</div>
		);
	}
}
```

**Comment by tomerpaz** [comment]
excellent, thanks!

**Comment by mehranabi** [comment]
You have to pass a function as Components in props (Check http://intljusticemission.github.io/react-big-calendar/examples/index.html#prop-components or your error).
So if you have a react component like `<MyToolbar />` for Calendar Toolbar,
then you must pass
```
components={{
  toolbar: () => (<MyToolbar />)
}}
```
to BigCalendar component.
** Actually `() => (<MyToolbar />)` is a function that returns `<MyToolbar />`

Exmaple:
```
<BigCalendar
	localizer={localizer}
	startAccessor='start'
	endAccessor='end'
	events={[]}
	view={this.state.view}
	components={{
		toolbar: (toolbar) => (
			<CalendarToolbar
				onMonthView={() => this.setState({ view: Views.MONTH })}
				onWeekView={() => this.setState({ view: Views.WEEK })}
				onDayView={() => this.setState({ view: Views.DAY })}
				onNext={() => toolbar.onNavigate('NEXT')}
				onPrevious={() => toolbar.onNavigate('PREV')}
				onToday={() => toolbar.onNavigate('TODAY')}
			/>
		)
	}}
/>
```

**Comment by Liel208** [comment]
It is a big no no to do inheritance in react! see [docs here](https://reactjs.org/docs/composition-vs-inheritance.html)

You dont really  need to use the Toolbar from rbc just use the onNavigate function passed from rbc

here is my code:
```
export default class CalendarToolbar extends React.Component {
  render() {
    return (
      <div className="rbc-btn-group">
          <button
            className="toolbar-navigation-button"
            type="button"
            onClick={() => **this.props.onNavigate**('PREV')}
          >
            <Icon
              className="navigate-icon"
              icon={this.props.isRTL ? 'chevron-right' : 'chevron-left'}
            />
          </button>
          <span
            className="today-label"
            onClick={() => **this.props.onNavigate**('TODAY')}
          >
            {i18n('calendar-today')}
          </span>
          <button
            className="toolbar-navigation-button"
            type="button"
            onClick={() => **this.props.onNavigate**('NEXT')}
          >
            <Icon
              className="navigate-icon"
              icon={this.props.isRTL ? 'chevron-left' : 'chevron-right'}
            />
          </button>
        </div>
      </div>
    );
  }
}
```

I then just pass this class into the components prop in BigCalendar

**Comment by jacklimwenjie** [comment]
@Liel208 's answer should deserve more upvotes. 

When reading this thread I've been wondering what exactly is the cause of this issue, because from my understanding, the `onView` props should only be used when you need to change the `view` from your custom toolbar.

Some people here suggested that to handle `onView` props implicitly, but the OP does not need to, and do nothing to change `view` from his/her custom toolbar. So why is this warning thrown?

I got a real "ahha" moment after reading @Liel208 's answer, I missed out the fact that OP is extending from the `react-big-calendar`'s Toolbar. Also, OP is importing the Toolbar wrong, as it is a default import from `react-big-calendar`, which is actually the `Calendar` component itself.

**Comment by paulhuisman** [comment]
Can someone tell me how to modify the state of the calendar from within the custom tool bar component? I want to include a handler but cant seem to add it to the components.

**Comment by lehaiquantb** [comment]
It 's not working now

**Comment by lehaiquantb** [comment]
Based on the above answers, this current solution worked for me
`
const CustomToolbar = (props) => {
  const [viewState, setViewState] = useState('month');

  const goToDayView = () => {
    props.onView('day');
    setViewState('day');
  };
  const goToWeekView = () => {
    props.onView('week');
    setViewState('week');
  };
  const goToMonthView = () => {
    props.onView('month');
    setViewState('month');
  };

  const goToBack = () => {
    if (viewState === 'month') {
      props.date.setMonth(props.date.getMonth() - 1);
    } else if (viewState === 'week') {
      props.date.setDate(props.date.getDate() - 7);
    } else {
      props.date.setDate(props.date.getDate() - 1);
    }
    props.onNavigate('prev');
  };

  const goToNext = () => {
    if (viewState === 'month') {
      props.date.setMonth(props.date.getMonth() + 1);
    } else if (viewState === 'week') {
      props.date.setDate(props.date.getDate() + 7);
    } else {
      props.date.setDate(props.date.getDate() + 1);
    }
    props.onNavigate('next');
  };

  const goToToday = () => {
    const now = new Date();
    props.date.setMonth(now.getMonth());
    props.date.setYear(now.getFullYear());
    props.date.setDate(now.getDate());
    props.onNavigate('current');
  };

  useEffect(() => {
    console.log(props);
  }, []);

  return (
    <div>
      <label>{moment(props.date).format('DD/MM/YYYY')}</label>

      <div>
        <button onClick={goToBack}>&#8249;</button>
        <button onClick={goToToday}>today</button>
        <button onClick={goToNext}>&#8250;</button>
        <button onClick={goToMonthView}>month</button>
        <button onClick={goToWeekView}>week</button>
        <button onClick={goToDayView}>day</button>
      </div>
    </div>
  );
};`

**Comment by lehaiquantb** [comment]
`
const CustomToolbar = (props) => {
  const [viewState, setViewState] = useState('month');

  const goToDayView = () => {
    props.onView('day');
    setViewState('day');
  };
  const goToWeekView = () => {
    props.onView('week');
    setViewState('week');
  };
  const goToMonthView = () => {
    props.onView('month');
    setViewState('month');
  };

  const goToBack = () => {
    if (viewState === 'month') {
      props.date.setMonth(props.date.getMonth() - 1);
    } else if (viewState === 'week') {
      props.date.setDate(props.date.getDate() - 7);
    } else {
      props.date.setDate(props.date.getDate() - 1);
    }
    props.onNavigate('prev');
  };

  const goToNext = () => {
    if (viewState === 'month') {
      props.date.setMonth(props.date.getMonth() + 1);
    } else if (viewState === 'week') {
      props.date.setDate(props.date.getDate() + 7);
    } else {
      props.date.setDate(props.date.getDate() + 1);
    }
    props.onNavigate('next');
  };

  const goToToday = () => {
    const now = new Date();
    props.date.setMonth(now.getMonth());
    props.date.setYear(now.getFullYear());
    props.date.setDate(now.getDate());
    props.onNavigate('current');
  };

  useEffect(() => {
    console.log(props);
  }, []);

  return (
    <div>
      <label>{moment(props.date).format('DD/MM/YYYY')}</label>

      <div>
        <button onClick={goToBack}>&#8249;</button>
        <button onClick={goToToday}>today</button>
        <button onClick={goToNext}>&#8250;</button>
        <button onClick={goToMonthView}>month</button>
        <button onClick={goToWeekView}>week</button>
        <button onClick={goToDayView}>day</button>
      </div>
    </div>
  );
};
`

**Comment by lehaiquantb** [comment]
Based on the above answers, this current solution worked for me
```

const CustomToolbar = (props) => {
  const [viewState, setViewState] = useState('month');

  const goToDayView = () => {
    props.onView('day');
    setViewState('day');
  };
  const goToWeekView = () => {
    props.onView('week');
    setViewState('week');
  };
  const goToMonthView = () => {
    props.onView('month');
    setViewState('month');
  };

  const goToBack = () => {
    if (viewState === 'month') {
      props.date.setMonth(props.date.getMonth() - 1);
    } else if (viewState === 'week') {
      props.date.setDate(props.date.getDate() - 7);
    } else {
      props.date.setDate(props.date.getDate() - 1);
    }
    props.onNavigate('prev');
  };

  const goToNext = () => {
    if (viewState === 'month') {
      props.date.setMonth(props.date.getMonth() + 1);
    } else if (viewState === 'week') {
      props.date.setDate(props.date.getDate() + 7);
    } else {
      props.date.setDate(props.date.getDate() + 1);
    }
    props.onNavigate('next');
  };

  const goToToday = () => {
    const now = new Date();
    props.date.setMonth(now.getMonth());
    props.date.setYear(now.getFullYear());
    props.date.setDate(now.getDate());
    props.onNavigate('current');
  };

  useEffect(() => {
    console.log(props);
  }, []);

  return (
    <div>
      <label>{moment(props.date).format('DD/MM/YYYY')}</label>

      <div>
        <button onClick={goToBack}>&#8249;</button>
        <button onClick={goToToday}>today</button>
        <button onClick={goToNext}>&#8250;</button>
        <button onClick={goToMonthView}>month</button>
        <button onClick={goToWeekView}>week</button>
        <button onClick={goToDayView}>day</button>
      </div>
    </div>
  );
};
```

**Comment by sadiki-o** [comment]
```tsx
import 'react-big-calendar/lib/css/react-big-calendar.css';

import moment from 'moment';
import { useEffect, useState } from 'react';
import { momentLocalizer, Navigate, ToolbarProps } from 'react-big-calendar';
const localizer = momentLocalizer(moment);

const CustomToolbar = (props: ToolbarProps) => {
  const [viewState, setViewState] = useState('month');

  function addMonths(date: Date, months: number) {
    const d = date.getDate();
    date.setMonth(date.getMonth() + months);
    if (date.getDate() != d) {
      date.setDate(0);
    }
    console.log(date);
    return date;
  }

  function addWeeks(date: Date, weeks: number) {
    date.setDate(date.getDate() + 7 * weeks);
    return date;
  }

  function addDays(date: Date, days: number) {
    date.setDate(date.getDate() + days);
    console.log(date);
    return date;
  }

  const goToDayView = () => {
    props.onView('day');
    setViewState('day');
  };
  const goToWeekView = () => {
    props.onView('week');
    setViewState('week');
  };
  const goToMonthView = () => {
    props.onView('month');
    setViewState('month');
  };

  const goToBack = () => {
    if (viewState === 'month') {
      props.onNavigate(Navigate.PREVIOUS, addMonths(props.date, -1));
    } else if (viewState === 'week') {
      props.onNavigate(Navigate.PREVIOUS, addWeeks(props.date, -1));
    } else {
      props.onNavigate(Navigate.PREVIOUS, addDays(props.date, -1));
    }
  };

  const goToNext = () => {
    if (viewState === 'month') {
      props.onNavigate(Navigate.NEXT, addMonths(props.date, +1));
    } else if (viewState === 'week') {
      props.onNavigate(Navigate.NEXT, addWeeks(props.date, +1));
    } else {
      props.onNavigate(Navigate.NEXT, addDays(props.date, +1));
    }
  };

  const goToToday = () => {
    const now = new Date();
    props.date.setMonth(now.getMonth());
    props.date.setFullYear(now.getFullYear());
    props.date.setDate(now.getDate());
    props.onNavigate(Navigate.TODAY);
  };

  useEffect(() => {
    console.log(props);
  }, []);

  return (
    <div>
      <label>{moment(props.date).format('DD/MM/YYYY')}</label>

      <div>
        <button onClick={goToBack}>&#8249;</button>
        <button onClick={goToToday}>today</button>
        <button onClick={goToNext}>&#8250;</button>
        <button onClick={goToMonthView}>month</button>
        <button onClick={goToWeekView}>week</button>
        <button onClick={goToDayView}>day</button>
      </div>
    </div>
  );
};

export default CustomToolbar;

```

updated CustomToolbar version for 2023 :100: 

ps: u can manipulate styling the way u want

**Comment by htutwaiphyoe** [comment]
> ```tsx
> import 'react-big-calendar/lib/css/react-big-calendar.css';
> 
> import moment from 'moment';
> import { useEffect, useState } from 'react';
> import { momentLocalizer, Navigate, ToolbarProps } from 'react-big-calendar';
> const localizer = momentLocalizer(moment);
> 
> const CustomToolbar = (props: ToolbarProps) => {
>   const [viewState, setViewState] = useState('month');
> 
> const goToDayView = () => {
>     props.onView('day');
>     setViewState('day');
>   };
>   const goToWeekView = () => {
>     props.onView('week');
>     setViewState('week');
>   };
>   const goToMonthView = () => {
>     props.onView('month');
>     setViewState('month');
>   };
> 
>   const goToBack = () => {
>     props.onNavigate(Navigate.PREVIOUS);
>   };
> 
>   const goToNext = () => {
>     props.onNavigate(Navigate.NEXT);
>   };
> 
>   const goToToday = () => {
>     props.onNavigate(Navigate.TODAY);
>   };
> 
>   // if you decided to inject a datepicker such as MUI or React Widgets ones, use this function on datepicker onChange 
>   const goToSpecificDate = (newDate: Date) => {
>     props.onNavigate(Navigate.DATE, newDate);
>   };
> 
>   return (
>     <div>
>       <label>{moment(props.date).format('DD/MM/YYYY')}</label>
> 
>       <div>
>         <button onClick={goToBack}>&#8249;</button>
>         <button onClick={goToToday}>today</button>
>         <button onClick={goToNext}>&#8250;</button>
>         <button onClick={goToMonthView}>month</button>
>         <button onClick={goToWeekView}>week</button>
>         <button onClick={goToDayView}>day</button>
>       </div>
>     </div>
>   );
> };
> 
> export default CustomToolbar;
> ```
> 
> updated CustomToolbar version for 2023 💯

Need to add onView and onNavigate in <Calendar /> component to work correctly

const [view, setView] = useState<View>(Views.MONTH)

  const handleOnChangeView = (selectedView: View) => {
    setView(selectedView)
  }

  const [date, setDate] = useState(new Date())
  const onNavigate = useCallback(
    (newDate: Date) => {
      return setDate(newDate)
    },
    [setDate]
  )

**Comment by aviemet** [comment]
This issue is the first result when searching Google for how to customize the toolbar, but the examples are either using class components, or not properly using the calendar methods. So I figured I'd leave an example of a functional component version of the base Toolbar component:

```typescript
import { Navigate, ToolbarProps } from "react-big-calendar"
import cx from "clsx"

export const CustomToolbar = ({
  date,
  label,
  localizer,
  onNavigate,
  onView,
  view,
  views,
}: ToolbarProps) => {
  return (
    <div className={ cx("rbc-toolbar") }>
      <span className={ cx("rbc-btn-group") }>
        <button onClick={ () => onNavigate(Navigate.PREVIOUS) }>{ localizer.messages.previous }</button>
        <button onClick={ () => onNavigate(Navigate.TODAY) }>{ localizer.messages.today }</button>
        <button onClick={ () => onNavigate(Navigate.NEXT) }>{ localizer.messages.next }</button>
      </span>

      <span className={ cx("rbc-toolbar-label") }>{ label }</span>

      <span className={ cx("rbc-btn-group") }>
        { Array.isArray(views) && views.map(name => {
          return (
            <button
              key={ name }
              onClick={ () => onView(name) }
              className={ cx({ "rbc-active": view === name }) }
            >
              { localizer.messages[name] }
            </button>
          )
        }) }
      </span>
    </div>
  )
}
```

That will reproduce the original Toolbar component, from there you can customize it however you like. For instance, I'm using Mantine, so I wanted to use the Mantine components and add a date picker to the label section:

```typescript
import { Navigate, ToolbarProps } from "react-big-calendar"
import { Box, Button, Group, Menu } from "@mantine/core"
import { DatePicker, DateValue, MonthPicker } from "@mantine/dates"
import { useDisclosure } from "@mantine/hooks"
import { PreviousIcon, NextIcon } from "../Icons"
import cx from "clsx"

export const CustomToolbar = ({
  date,
  label,
  localizer,
  onNavigate,
  onView,
  view,
  views,
}: ToolbarProps) => {
  const [opened, { toggle, close }] = useDisclosure(false)

  const handlePickDate = (d: DateValue) => {
    close()
    if(!d) return
    onNavigate(Navigate.DATE, d)
  }

  return (
    <Group justify="space-between" my="md">
      <Box component="span" className={ cx("rbc-btn-group") }>
        <Button variant="light" onClick={ () => onNavigate(Navigate.PREVIOUS) }><PreviousIcon />{ localizer.messages.previous }</Button>
        <Button variant="light" onClick={ () => onNavigate(Navigate.TODAY) }>{ localizer.messages.today }</Button>
        <Button variant="light" onClick={ () => onNavigate(Navigate.NEXT) }>{ localizer.messages.next }<NextIcon /></Button>
      </Box>

      <Box component="span">
        <Menu opened={ opened } onClose={ toggle }>
          <Menu.Target>
            <Button onClick={ toggle } variant="subtle">{ label }</Button>
          </Menu.Target>

          <Menu.Dropdown>{ view === "month"
            ? <MonthPicker onChange={ handlePickDate } />
            : <DatePicker onChange={ handlePickDate } />
          }</Menu.Dropdown>
        </Menu>
      </Box>

      <Box component="span" className={ cx("rbc-btn-group") }>
        { Array.isArray(views) && views.map(name => {
          return (
            <Button
              key={ name }
              variant={ view === name ? "filled" : "light" }
              onClick={ () => onView(name) }
            >
              { localizer.messages[name] }
            </Button>
          )
        }) }
      </Box>
    </Group>
  )
}
```
