### ISSUE TITLE
Better mobile experience requested.

### ISSUE THREAD

**Issue by inunotaisho26** [intljusticemission/react-big-calendar#821]
#### Do you want to request a _feature_ or report a _bug_?
Have a feature request: Does not respond all that well when using a mobile device.

#### What's the current behavior?
<img width="433" alt="screen shot 2018-04-23 at 5 39 00 pm" src="https://user-images.githubusercontent.com/19748234/39154821-a4dd7410-471d-11e8-9478-dcd89cc7dc8a.png">

Should have a better flow like Apple or Google calendar while in mobile mode.
<img width="433" alt="img_8782" src="https://user-images.githubusercontent.com/19748234/39155022-6b58d922-471e-11e8-8181-e623a6ab35fd.PNG">

**Comment by xijun** [comment]
I am actually very interested in this kind of feature as I need to adapt my website with a mobile layout but the library doesn't support well mobile devices viewports

**Comment by arecvlohe** [comment]
Yes, it would be nice to have a better mobile experience. We are open to PRs!

**Comment by inunotaisho26** [comment]
@arecvlohe Would you mind adding some tags to this issue? needs to be addressed.

**Comment by nikitaulshin** [comment]
Does anybody doing anything on this? I need to adapt my website with a mobile layout too and I would like to participate.
