### ISSUE TITLE
Agenda headers misaligned in Chrome on initial agenda load

### ISSUE THREAD

**Issue by bmueller-sykes** [intljusticemission/react-big-calendar#822]
#### Do you want to request a _feature_ or report a _bug_?
Bug
#### What's the current behavior?
Go here in Chrome (on macOS):
http://intljusticemission.github.io/react-big-calendar/examples/index.html

...by default, the calendar appears on month view (which is fine). Click "agenda", and the agenda table head is misaligned with the body. As soon as the browser is resized, the head snaps into the correct location.
<img width="767" alt="screen shot 2018-04-26 at 12 49 05 pm" src="https://user-images.githubusercontent.com/12236379/39322659-399b604c-4950-11e8-8221-43d8aa4a1d07.png">

Safari and FF on macOS appear to work fine. MS Edge also works fine. (The library appears incompatible with IE11?)

#### What's the expected behavior?
Headers should line up with agenda body at all times.

**Comment by dgana** [comment]
Yes im having the same problem so what is the quick fix for this

**Comment by dgana** [comment]
`
viewChange = view => {
    if (view === "agenda")
      setTimeout(() => {
        this.setState(
          {
            width: window.innerWidth - 1
          },
          () =>
            this.setState({
              width: window.innerWidth + 1
            })
        );
      }, 1);
  };

  render() {
    return (
            <BigCalendar
              onView={this.viewChange}
            />
    );
  }
`

My quick fix is use set width and set it to style in render for 1ms and turn it back

**Comment by Soundvessel** [comment]
This also occurs when you get a view with the empty agenda text then navigate back into an agenda with events.

**Comment by laradevitt** [comment]
This is still an issue. I'm seeing the behaviour as described by @bmueller-sykes and @Soundvessel. My workaround was to wrap component in a conditional to slightly delay rendering.
