### ISSUE TITLE
Layout is mess up

### ISSUE THREAD

**Issue by sandropoluan** [intljusticemission/react-big-calendar#824]
#### Do you want to request a _feature_ or report a _bug_?
BUG

#### What's the current behavior?
The layout is mess up
![m-up](https://user-images.githubusercontent.com/11922251/39353105-4812afba-4a39-11e8-80ff-ba845956634b.png)

My setting
```
        <BigCalendar
          events={[]}
          startAccessor="startDate"
          endAccessor="endDate"
        />
```

**Comment by tobiasandersen** [comment]
Like @Jmenache says, you have to import the styles. If you still have a problem, please provide a codesandbox so that we can see what's wrong.

**Comment by sandropoluan** [comment]
Thank you!

**Comment by alansutherland** [comment]
Note: If you're using style-loader and css-loader and you have modules:true enabled on css-loader, make sure to import it as global CSS like such: 

import '!style-loader!css-loader!react-big-calendar/lib/css/react-big-calendar.css'.

P.S. big calendar devs adding this to the docs you muppets

https://github.com/intljusticemission/react-big-calendar/issues/234
