### ISSUE TITLE
Strict time ordering events

### ISSUE THREAD

**Issue by ivkirill** [intljusticemission/react-big-calendar#825]
I'm trying to use calendar for rendering events with duration between days, events isn't overlaping.

Events doesn't sorting by time in day block, but sorting by available space:
http://dl4.joxi.net/drive/2018/02/15/0005/4033/360385/85/a4ae49a9f7.png

I need to reorder events in day block. "Event 3" should be after "Event 2", "Event 5" after "Event 4".
https://image.ibb.co/fEqjGS/Screen_Shot_2018_02_19_at_13_56_16.png

It's like agenda view but for month timeline.

**Comment by ivkirill** [comment]
Problem solved :)

**Comment by renatho** [comment]
How did you solve that?

**Comment by ivkirill** [comment]
With moment.js and fake events.
Add `fake event` directly after normal event and set duration to end of the week, then hide all `fake events` thought css styles. Dummy and simple.
