### ISSUE TITLE
Weekdays as events?

### ISSUE THREAD

**Issue by Ancinek** [intljusticemission/react-big-calendar#826]
More like a question, as I couldn't find it anywhere.
Is it possible to pass weekdays with hours as events?

Like if I know that on every Monday there will be an scheduled event from 1PM to 3PM, and I could somehow pass:

```
{
    id: 0,
    title: 'Monday Event',
    allDay: false,
    weekday: 'monday', // or in numbers
    start_time: Moment or Date instance,
    end_time: Moment or Date instance,
  },
```

**Comment by jhockett** [comment]
Not that I know of. This was my motivation for #641 

If you keep track of the currently viewed date range, you can generate repeating events on the fly as necessary. Hope that helps!

**Comment by Ancinek** [comment]
Thanks a lot :)!
