### ISSUE TITLE
Recalculate the need of `more`

### ISSUE THREAD

**Issue by porfirioribeiro** [intljusticemission/react-big-calendar#828]
react-big-calendar calculates the layout of the events and the need to show the `more` link when the component mounts and when the window resizes, but i am using my component inside a resizeable component and the calendar events are not recalculated when the parent component resizes.

You can see a demo here: https://codesandbox.io/s/mzz0p2pr0y

The solution could be using a resize observer with a polyfill like https://github.com/que-etc/resize-observer-polyfill, or having some way to flag the calendar that it needs to update the layout.

**Comment by tobiasandersen** [comment]
I like the idea of using a resize observer 👍

**Comment by porfirioribeiro** [comment]
It could replace the window resize event.
If i have time this weekend i will try to look how it can be done.

**Comment by nguyenanduong** [comment]
I'd also like to add that recalculation does not work well when the event div (rbc-event) has border. The More link always goes off the cell limit
