### ISSUE TITLE
Custom show more value and path

### ISSUE THREAD

**Issue by willian** [intljusticemission/react-big-calendar#835]
Currently, the calendar auto-calculates the space for each day and shows the `+x show more` link that opens a popup, when X is the number of remaining events in that day.

I have a different use case: I got X events from the API for each day, is the number of events is greater than 3 I want to display the first 2 in the list and add the `+x show more` link pointing to a specific URL (a page not related to the calendar's page that will display all events in a list).

Is it possible? I was looking at the codebase and realized the `+x show more` is not a component that I can customize by myself, also I didn't find any prop that I can pass to accomplish what I need.

I really like the library, you did a great work with it. But since all I need is the Month view with a custom `+x show more` link, I think I will need to build my own set of components to do it if what I need is not possible to do with `react-big-calendar`.

Thank you in advance,

**Comment by arecvlohe** [comment]
Happy to accept a PR on this!

**Comment by philipLutz** [comment]
I am also looking for this feature.  Is there any update to what is going on?  Where in the codebase is the `+x show more` link created?

**Comment by victorvarenic** [comment]
I'm looking for this feature.

**Comment by pietrofxq** [comment]
It is possible to create a custom value:

```js
<BigCalendar messages={{ showMore: (count) => 'custom show more'}} />
```
