### ISSUE TITLE
rbc-current-time-indicator not displaying well

### ISSUE THREAD

**Issue by akiratee** [intljusticemission/react-big-calendar#836]
#### Do you want to request a _feature_ or report a _bug_?
Is this a bug?

#### What's the current behavior?
Instead of a full line being drawn, only a very short line is draw, without a dot indicator on the left.

This is the same even when I run the samples locally.
When I compare the css with the one on the live website, i noticed that the :before element is missing too.

I'm using the Week View.

Locally:
![screen shot 2018-05-08 at 4 03 32 pm](https://user-images.githubusercontent.com/8487679/39745400-b7ec1cf6-52d9-11e8-8539-6b4341008d44.png)

On the live website:
<img width="757" alt="screen shot 2018-05-08 at 4 06 31 pm" src="https://user-images.githubusercontent.com/8487679/39745442-d1c8a022-52d9-11e8-80e3-22e9ac5450b3.png">

#### What's the expected behavior?
It should display like in the live website i guess..

**Comment by tobiasandersen** [comment]
I think we generally try to do it similar to Google, and they put it on the current day only. But it does look a bit misaligned in your screenshot...

**Comment by Dyasik** [comment]
I don't know if this is an issue, but I've mentioned that current time indicator is not displayed when `min` and `max` props are provided, even though current time is between these boundaries.

**Comment by Dyasik** [comment]
This offset creates the horizontal scroll if current day is the last in the week:

![image](https://user-images.githubusercontent.com/12381295/40531875-b1f7222c-600e-11e8-81c1-1b45b40e36aa.png)

**Comment by longsleep** [comment]
I think the change of the time indicator should be reverted. Where it previously was not looking good, it now looks broken as soon as the dimensions of the container change.

**Comment by euvs** [comment]
It also causes visual glitches in my project. And the green circle disappeared. 
It is really hard to see the shot line on a busy calendar now. 

I agree with @longsleep it should be reverted. Or at least make this behaviour optional please.

**Comment by jquense** [comment]
Happy to take a PR fixing the glitches

**Comment by HartiganHM** [comment]
@jquense: Since this is the most recent post on the `rbc-time-indicator` I thought I would ask here for help. Happy to open another issue if need be.

I'm having some issues with getting the time indicator to display or render on the DOM. I am using `styled-components`, so I'm not sure if that would pose an issue. Everything else is rendering fine, I'm just not sure if I'm missing a particular prop for the time indicator. If anyone needs more details as to what's being passed down to this component, let me know!

Here's the gist of my setup:

```javascript
BigCalendar.setLocalizer(BigCalendar.momentLocalizer(moment))

const StyledReactBigCalendar = styled(BigCalendar)`
...
`

class Calendar extends Component {
  render() {
    const {
      ...
    } = this.props

    return (
      <StyledReactBigCalendar
        height={height}
        date={date || new Date()}
        toolbar={toolbar} 
        events={events} 
        defaultView={defaultView} 
        views={views} 
        selectable={selectable} 
        step={step}
        timeslots={timeslots}
        min={min}
        max={max}
        onSelectSlot={onSelectSlot}
        onSelectEvent={onSelectEvent}
        formats={formats}
        titleAccessor={titleAccessor}
        startAccessor={startAccessor}
        endAccessor={endAccessor}
        allDayAccessor={allDayAccessor}
        eventPropGetter={eventPropGetter}
      />
    )
  }
}
```

**Comment by HartiganHM** [comment]
I'll also note that, per #591, it looks like removing the `min/max` props shows the time indicator. Is there any particular reason why adding those properties removes its functionality?

**Comment by rebirthtobi** [comment]
@Dyasik i can see that the header in your calendar seems not to be aligned. Please do you know how to correct this as i'm having that same problem?

**Comment by jquense** [comment]
this has been fixed in the latest version 👍

**Comment by sujin-lifology** [comment]
is the new version solved the bug?
