### ISSUE TITLE
[Feature Request] Add support for repeated events

### ISSUE THREAD

**Issue by nobobo1234** [intljusticemission/react-big-calendar#839]
#### Do you want to request a _feature_ or report a _bug_?
I want to request a feature

#### What's the current behavior?
I currently can't add repeated events without adding massive amounts of events, with a drop of performance.

#### What's the expected behavior?
I expect to add some sort of property to an event where I can set a string like 'daily' or 'weekly' and optionally add a moment-range (or another way to add a range) to constrain it within a certain range.

**Comment by jquense** [comment]
Hey there, this has been been covered in past, please search past issues for more info. The short version is RBC is data agnostc and reoccurring events is mostly a data concern. You can implement it effectively by generating or porjecting the needed events when the calendar navigates
