### ISSUE TITLE
Applying styles should be easier

### ISSUE THREAD

**Issue by himanshuc3** [intljusticemission/react-big-calendar#841]
Feature Request.

I am using this library( it is good), but I want to customize it to my theme. This have to be done manually right now. It could be made better by passing props or something.

**Comment by jquense** [comment]
We have chosen to have a traditional approach to styling, just css. Tye supported why to theme the calendar is to add your own stylesheet using the CSSTransition classes as hooks and adding your own stylesheet to them. Thanks!
