### ISSUE TITLE
How can i add my custom styles?

### ISSUE THREAD

**Issue by vd1216** [intljusticemission/react-big-calendar#842]
Hi to everyone)
i need a little help 
i'd like to use this calendar in progect, but after researching documentation i haven't find any information about adding custom styles. should i overriding native styles(by custom css file added after react-big-calendar.css) or can i just change them in react-big-calendar.css?

**Comment by jquense** [comment]
Yup add the react big calendar.css and then include any overrides or styles of your own after using the CSSTransition class nams as selectors

**Comment by jquense** [comment]
You can also compile the styles from the LESS files directly if you'd like to use that approach as well
