### ISSUE TITLE
onSelectSlot in Firefox

### ISSUE THREAD

**Issue by zemant91** [intljusticemission/react-big-calendar#845]
Hello! 
How can I get global object "window" or "window.event" in Firefox, if onSelectSlot event hasn't "event" argument 
I call "window.event.target.className" inside onSelectSlot function and browser throw me an error, what window.event is undefined

**Comment by jelly** [comment]
window.event is non-standard and not [supported by Firefox](https://developer.mozilla.org/en-US/docs/Web/API/Window/event)
