### ISSUE TITLE
Polymer 3 compatibility

### ISSUE THREAD

**Issue by titilambert** [intljusticemission/react-big-calendar#851]
Hello, I'm trying to integrate react-big-calendar in home-assistant which is polymer 3 based.
Does someone know how can I use react-big-calendar which polymer 3 ?

Thanks !

**Comment by jquense** [comment]
I am not familiar with polymer, but my guess it that it wouldn't work smoothly since this is a React component not a native web component. Maybe this SO question is helpful tho: https://stackoverflow.com/questions/38175599/how-to-use-react-inside-a-polymer-component
