### ISSUE TITLE
Specify rbc-time-header-gutter content

### ISSUE THREAD

**Issue by Dyasik** [intljusticemission/react-big-calendar#853]
#### Do you want to request a _feature_ or report a _bug_?

_Feature_

#### What's the current behavior?

`rbc-time-header-gutter` is always empty.

#### What's the expected behavior?

Add new prop to specify the text (at least) content of `rbc-time-header-gutter`

**Comment by danbovey** [comment]
I've made a pull request with this feature.

However, now that I've got further towards my use case I realise I'd actually prefer the ability to more easily change the TimeGutter component as a whole, not just the header.

Proposal: Add a `timeGutter` component

```js
<BigCalendar
  {...props}
  components={{
    timeGutter: MyTimeGutter, // <----- Add timeGutter component
    timeGutterHeader: <p>Custom gutter text</p>, // <----- Exists in PR #874
  }}
/>
```

Then in `TimeGrid` we'd need a PR to change how the `TimeGutter` is rendered

```js
// Choose the custom component or default to the component in ./TimeGutter
const TimeGutterComponent = components.timeGutter || TimeGutter;

// TimeGrid renders rbc-time-view and TimeGridHeader here
<TimeGutterComponent
  {...this.props}
  date={start}
  ref={this.gutterRef}
  className="rbc-time-gutter"
/>
```

Here's an example use case. I found a solution in #118 Timezone support, to convert datetimes into JS dates, to allow events to be displayed in a different time relevant to a timezone. Adding this new `components.timeGutter` option, I can then render a custom time gutter with the different UTC+`x` times alongside what the browser would normally show.

![image](https://user-images.githubusercontent.com/1503076/41352106-5c5a559e-6f10-11e8-8100-b32d05a1176e.png)

This might be a bit of a specific use case, so @jquense let me know if this is worth making a PR for.

**Comment by vvgokul55** [comment]
Though timeGutterHeader is added into the propTypes and all, when the context object in the state of calendar is created, this property is missed therefore cannot set timeGutterHeader now.

**Comment by gthomas** [comment]
@danbovey @jquense I could use that custom <TimeGutter> feature  -- it would help me render multiple timezones the same way gCal handles them. Has support for this sort of thing dropped in the subsequent two years? (I can't seem to find it)

**Comment by owenn2106** [comment]
@gthomas Have you found anything regarding this multiple timezones? 😄
