### ISSUE TITLE
react-dnd compatability issue

### ISSUE THREAD

**Issue by spasem** [intljusticemission/react-big-calendar#857]
I have an issue with one of my projects where I updated react-dnd to 4.0.2 and I get an error with either createContext or createBackend. 
A Codesandbox can be found here:
https://codesandbox.io/s/l9zlz7qy5z

Downgrading to to react-dnd 2.6.0 resolves the issue. Tested with react-dnd 3 and it seems the error start with that release.

Is this a bug or should this be considered a feature request for compatibility with react-dnd 3 or higher.

**Comment by amkoehler** [comment]
Based on the [release history](https://github.com/react-dnd/react-dnd/releases), `react-dnd` is going through some instability right now. If things settle down I definitely think we should work on supporting the latest version.

**Comment by schester44** [comment]
Could this be related to an error i'm getting while attempting to implement the dnd resource example? 

`TypeError: createBackend is not a function`

**Comment by rhuanbarreto** [comment]
+1 for the issue. How to solve it?

**Comment by rhuanbarreto** [comment]
@schester44 for now you just maintain the old versions of react-dnd. In your package.json, put the following:
```
"react-dnd": "^2.6.0",
"react-dnd-html5-backend": "^2.6.0",
```
And it will work.

**Comment by spasem** [comment]
I agree. I am using this in production and can confirm it works with keeping these at the older versions.

**Comment by arecvlohe** [comment]
It looks as though there is a resolution to this issue, using an older version of `react-dnd` that supports the same context API as rbc. Although not ideal, it should be the go-to answer until rbc updates to support the newest version of the context API.

**Comment by tbarho** [comment]
Just letting you guys know that this is still problematic for packages that use private npm packages which consume `react-redux`.  There is a known bug with react-redux@6.x.x and `npm link`ing (https://github.com/reduxjs/react-redux/issues/1166#issuecomment-460082580) that requires you to eject and alias dependencies, which breaks
```
"react-dnd": "^2.6.0",
"react-dnd-html5-backend": "^2.6.0",
```
since they rely on an older version of Context and `react-redux`

**Comment by sidduRam89** [comment]
@tbarho thanks for the reply.
It's working for my current react version 15.6.0

**Comment by jameschou-bk** [comment]
Is maintaining these older versions of react-dnd and react-dnd-html5-backend still the only way for this to resolve this error?
