### ISSUE TITLE
Failed at the react-big-calendar@0.9.11 examples script 'npm run clean:examples && babel-node ./examples/server.js "3000"

### ISSUE THREAD

**Issue by sap-glooko** [intljusticemission/react-big-calendar#86]
17 error Darwin 15.4.0
18 error argv "/usr/local/Cellar/node/5.10.1/bin/node" "/usr/local/bin/npm" "run" "examples" "3000"
19 error node v5.10.1
20 error npm  v3.8.3
21 error code ELIFECYCLE
22 error react-big-calendar@0.9.11 examples: `npm run clean:examples && babel-node ./examples/server.js "3000"`
22 error Exit status 1
23 error Failed at the react-big-calendar@0.9.11 examples script 'npm run clean:examples && babel-node ./examples/server.js "3000"'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the react-big-calendar package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run clean:examples && babel-node ./examples/server.js "3000"
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs react-big-calendar
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls react-big-calendar
23 error There is likely additional logging output above.
[npm-debug.log.zip](https://github.com/intljusticemission/react-big-calendar/files/236748/npm-debug.log.zip)

**Comment by jquense** [comment]
fairly certain this isn't a problem in this module, try reinstalling or starting with a fresh `node_modules` directory

**Comment by sap-glooko** [comment]
/Users/SAPMBP/Downloads/react-big-calendar-master/node_modules/babel-core/lib/transformation/plugin.js:115

      throw new Error(messages.get("pluginInvalidProperty", loc, i, key));

      ^


Error: Plugin 0 specified in
"/Users/SAPMBP/Downloads/react-big-calendar-master/node_modules/babel-preset-jason/index.js"
provided an invalid property of "default"

    at Plugin.init
(/Users/SAPMBP/Downloads/react-big-calendar-master/node_modules/babel-core/lib/transformation/plugin.js:115:13)

    at Function.normalisePlugin
(/Users/SAPMBP/Downloads/react-big-calendar-master/node_modules/babel-core/lib/transformation/file/options/option-manager.js:149:12)

    at
/Users/SAPMBP/Downloads/react-big-calendar-master/node_modules/babel-core/lib/transformation/file/options/option-manager.js:183:30

    at Array.map (native)

    at Function.normalisePlugins
(/Users/SAPMBP/Downloads/react-big-calendar-master/node_modules/babel-core/lib/transformation/file/options/option-manager.js:155:20)

    at OptionManager.mergeOptions
(/Users/SAPMBP/Downloads/react-big-calendar-master/node_modules/babel-core/lib/transformation/file/options/option-manager.js:277:36)

    at
/Users/SAPMBP/Downloads/react-big-calendar-master/node_modules/babel-core/lib/transformation/file/options/option-manager.js:349:14

    at
/Users/SAPMBP/Downloads/react-big-calendar-master/node_modules/babel-core/lib/transformation/file/options/option-manager.js:369:24

    at Array.map (native)

    at OptionManager.resolvePresets
(/Users/SAPMBP/Downloads/react-big-calendar-master/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:20)


Syed Arsalan Pervez | Software Engineer

**Comment by mazemax** [comment]
I have exactly same issue. I recommend that following dependencies should be updated to latest version and then pushed to master branch:
- lodash
- css-list
- jade
- graceful-fs

**Comment by jquense** [comment]
this was due to a Babel plugin, its been fixed upstream so nuke node_modules and reinstall to fix!
