### ISSUE TITLE
Capitalize Tabs Titles 

### ISSUE THREAD

**Issue by yolixtly** [intljusticemission/react-big-calendar#861]
#### Do you want to request a _feature_ or report a _bug_?
Feature 
#### What's the current behavior?
The current implementation of the Calendar renders the Toolbar Tabs in lower case as follows : 

**[today] [back] [next]                  June 04 - 08        [month] [week] [work week] [day] [agenda]**

I want/need the words to have the first letter capitalized however, I've research online and through the code and it does not seems to be a dynamic nor easy way I can update these values through props or without updating the source code 

#### What's the expected behavior?
I want/need the words to have the first letter capitalized. example: 

**[Today] [Back] [Next]                  June 04 - 08        [Month] [Week] [Work Week] [Day] [Agenda]**

**Comment by yolixtly** [comment]
The current work around was to override the styles like this: 
 div.rbc-calendar div.rbc-toolbar span.rbc-btn-group button {
	text-transform:capitalize
}

**Comment by arecvlohe** [comment]
This seems to be a good solution so I am closing.
