### ISSUE TITLE
Background image for a tile 

### ISSUE THREAD

**Issue by KartikShankhavaram** [intljusticemission/react-big-calendar#863]
#### Do you want to request a _feature_ or report a _bug_?
Feature
#### What's the current behavior?
There currently seems no way to add background to a tile

#### What's the expected behavior?
A prop to add a url to an image to show the background as the image

**Comment by KartikShankhavaram** [comment]
Could someone guide mt to where the styling for a cell div is so I can try it myself?

**Comment by arecvlohe** [comment]
@KartikShankhavaram Check out the styles for the library itself.

**Comment by KartikShankhavaram** [comment]
Hey, I completed that task a while back by customising the date cell wrapper, but thanks for replying!
