### ISSUE TITLE
onSelectEvent not called in Day and Week views

### ISSUE THREAD

**Issue by berryman17** [intljusticemission/react-big-calendar#867]
I experienced the issue in v0.18.0, but was able to work around it by clicking on rightmost half of event slot. .rbc-slot-selection only covered about 50% of column. After updating to v0.19.0, I am unable to select events except in Month view. .rbc-slot-selection is now full width of column.

I've tried changing z-index of rbc-event and even removing rbc-slot-selection from DayColumn.js, but to no avail.

**Comment by berryman17** [comment]
To clarify, changing z-index of rbc-event resolves issue in v0.18.0 but not v0.19.0

**Comment by tanmay-cs13** [comment]
Well it working fine for me! Will you please share code snip or on sandbox. Thank You

**Comment by miltonmc** [comment]
I've found out that it's working fine with touch events.

That is how I'm using it:
```jsx
<BigCalendar
  defaultDate={new Date()}
  events={events}
  defaultView="week"
  step={30}
  selectable
  showMultiDayTimes
  onSelectSlot={slotInfo => this.handleSelectNew(slotInfo)}
  onSelectEvent={this.handleSelectExisting}
  messages={{
    today: "Hoje",
    next: "Próximo",
    previous: "Anterior",
    month: "Mês",
    week: "Semana",
    day: "Dia",
    agenda: "Agenda"
  }}
  style={{ height: "100vh" }}
/>
```

**Comment by miltonmc** [comment]
I'm able to reproduce the behavior on your sandbox example, running on Google Chrome 67.0.3396.87 (64-bit), but it works fine on the MS Edge.

More info: My computer is a Microsoft Surface Book with touchscreen and Windows Pro 10 (1803)
