### ISSUE TITLE
RangeError: Invalid array length on line var groups = new Array(numGroups)

### ISSUE THREAD

**Issue by tanmay-cs13** [intljusticemission/react-big-calendar#870]
There is a bug on clicking the 'next' in a case of day view!
```
         <BigCalendar
            events={ events }
            defaultView="day"
            views={ ['day', 'work_week'] }
            resources={ resourceMap }
            resourceIdAccessor="resourceId"
            resourceTitleAccessor="resourceTitle"
          />
```
I am using
"react": "^16.3.2",
"react-big-calendar": "^0.19.1"

Here the sandbox link: https://codesandbox.io/s/v3pnjxln80

This issue is coming only when I clicked the next from first screen.
If I click on work_week view and then click next no error is thrown. Even when I go back to day view this time on clicking next would not throw any error.
The event and the resourceMap error is here:

```            events: [
              {
                id: 0,
                title: 'Board meeting',
                start: new Date(2018, 5, 11, 9, 0, 0),
                end: new Date(2018, 5, 11, 13, 0, 0),
                resourceId: 1,
              },
              {
                id: 1,
                title: 'MS training',
                start: new Date(2018, 5, 11, 14, 0, 0),
                end: new Date(2018, 5, 11, 16, 30, 0),
                resourceId: 2,
              },
              {
                id: 2,
                title: 'Team lead meeting',
                start: new Date(2018, 5, 11, 8, 30, 0),
                end: new Date(2018, 5, 11, 12, 30, 0),
                resourceId: 3,
              },
              {
                id: 3,
                title: 'Birthday Party',
                start: new Date(2018, 5, 11, 7, 0, 0),
                end: new Date(2018, 5, 11, 10, 30, 0),
                resourceId: 4,
              }
            ],
            resourceMap: [
              { resourceId: 1, resourceTitle: 'Room A' },
              { resourceId: 2, resourceTitle: 'Room B' },
              { resourceId: 3, resourceTitle: 'Room C' },
              { resourceId: 4, resourceTitle: 'Room D' }
            ]
```

**Comment by tanmay-cs13** [comment]
Using your given example when I remove prop one by one I noticed its because of not providing defaultDate. But as per document I think it says that if defaultDate will not be provided it will use current date as default but For Day View its's throwing error.

**Comment by arecvlohe** [comment]
I think what we are missing here is that the `defaultDate` is not set. I think there should be a defaultProp that sets `defaultDate` to `new Date()` if it is not already set. I am going to create a separate issue to address this.

**Comment by AbdelrhmanAmin** [comment]
In my case, I was passing `date` prop an invalid date.
