### ISSUE TITLE
Feature request: Customizable Content while selecting/creating new event

### ISSUE THREAD

**Issue by mokimo** [intljusticemission/react-big-calendar#872]
I couldn't find something that currently supports this functionality.
(OnSelecting, maybe?... That doesn't do the deal for me though)

While selecting the slots for the new event it
currently it displays from time - to time.
![x](https://user-images.githubusercontent.com/39759830/41277017-47529c00-6e26-11e8-823d-39163c15e076.png)

Suggestion:
Callback like CustomEvent

**PS:**
incase my implementation of OnSelecting is just wrong, 
since it seems really like the functionality I try to achieve...
```

<RBC onSelecting={this.OnSelecting}/>
  onSelecting = range => { //doesnt do anything at all
    console.log(range)
  };
```

**Comment by arecvlohe** [comment]
Issue is stale so closing for now. Feel free to reopen if you have more to contribute.
