### ISSUE TITLE
Tooltip prepended by unwanted time range in week and day view despite tooltipAccessor updates

### ISSUE THREAD

**Issue by el-zoltan** [intljusticemission/react-big-calendar#879]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?

CodeSandbox: https://codesandbox.io/s/lyymjz4017
Using most recent react-big-calendar and chrome

So, I'm not sure if this is a bug or if I need clarification, but I can't get the prepended time range to not display on the tooltip in the week and day views.

- I've tried using the `tooltipAccessor`, which is great, but doesn't get rid of the prepended time range string in week and day views.
- I've tried setting `eventTimeRangeFormat` to return an empty string, which almost works. If you go to my sandbox and hover over an event you'll see that it still prepends ': ' in the tooltip, and that's what I'm trying to get rid of.

#### What's the expected behavior?

`tooltipAccessor`'s return value shouldn't be prepended by an unwanted time range.

**Comment by jquense** [comment]
Looks like a bug! Want to send a PR?

**Comment by chj-damon** [comment]
@jquense will you fix this bug?

**Comment by RahulShahUI** [comment]
any solution for this issue?
