### ISSUE TITLE
weekHeaderFormat has no effect

### ISSUE THREAD

**Issue by kromit** [intljusticemission/react-big-calendar#88]
it is used only in `propTypes` and nowhere else in the code

**Comment by Klayderpus** [comment]
Bump - can confirm this is the case. It was really quite frustrating to realize after so much time debugging.

**Comment by jquense** [comment]
PR's Welcome, not sure when we'll get a moment to fix it. But i'll happily merge a PR

**Comment by kromit** [comment]
This should be removed from documentation entirely. It is not a bug, but a missing feature since it is not implemented at all.

**Comment by jquense** [comment]
I mean it's clearly a bug

**Comment by kromit** [comment]
I meant it's is not even a bug. :smile:  A bug would require some sort of implementation that does not work correctly. But here even the basic implementation is missing, so it is clearly not a "bug" but a "feature". 

The documentation suggests that the feature already exists. This is highly misleading. 

Its like putting some documentation about a method like `enableGmailSync` that is not event implemented. It feels like serious cheating.

**Comment by jquense** [comment]
not really sure why you are splitting hairs over this...

**Comment by nickwanhere** [comment]
Seems working for me

`var formats = {
      dayRangeHeaderFormat : function(_ref3, culture, local) {
        var start = _ref3.start;
        var end = _ref3.end;
        return local.format(start, 'D MMM YYYY', culture) + ' - ' + local.format(end,  'D MMM YYYY', culture);
      }
  }`

`<BigCalendar formats={formats} />`

**Comment by ejowers** [comment]
I cannot get this to work either, but it is unclear what the props should be. I assumed it would be a string format, but the above commenter used a function?
