### ISSUE TITLE
have added timezone picker  to 3 fields in react component . it takes at least 5 to 10 seconds for component to load, if i use reacttimezonepicker  on only 1 field  then it is  loading quickly . Please help me out on this.

### ISSUE THREAD

**Issue by preetham07** [intljusticemission/react-big-calendar#882]

**Comment by jquense** [comment]
Sorry I'm not sure what this is about, please provide a reproduction and clear explanation of the issue you are facing with react-big-calendar thanks!

**Comment by arecvlohe** [comment]
Because of inactivity on the part of the original poster I am going to close this for now. If anyone else wants to chime in please do.
