### ISSUE TITLE
Error when using globalize@1.3.0

### ISSUE THREAD

**Issue by josdejong** [intljusticemission/react-big-calendar#885]
#### Do you want to request a _feature_ or report a _bug_?

_bug_

#### What's the current behavior?

Using `react-big-calendar` with the latest version of `globalize` (`1.3.0`):

```js
import * as globalize from 'globalize'
import * as React from 'react'
import BigCalendar from 'react-big-calendar'

BigCalendar.setLocalizer(BigCalendar.globalizeLocalizer(globalize))
```

Throws an error:

```
./node_modules/globalize/dist/globalize.js
Module not found: Can't resolve 'cldr' in `.../node_modules/globalize/dist'
```

It works fine though when installing `globalize@0.1.1` as used in the examples project.

#### What's the expected behavior?

Expected behavior is to work with the latest version of `globalize`.

**Comment by josdejong** [comment]
Thanks for sharing this awesome project btw, its really impressive!

**Comment by pgomez89** [comment]
@josdejong the component doesn't have support for newest versions of globalize, but try to load the cldr file. More info: https://github.com/globalizejs/globalize/blob/HEAD/doc/migrating-from-0.x.md

**Comment by jquense** [comment]
There should be support for v1.0.0 but the setup on glovalizes side is different than pre v1 check their site for docs on installing and setting up

**Comment by josdejong** [comment]
Thanks, you're right it is a loading issue with globalize itself, see https://github.com/globalizejs/globalize/issues/814, https://github.com/globalizejs/globalize/issues/603.

I don't know if it will work besides the loading issue. Will stick with `globalize@0.1.1` for now and switch to `globalize@2.0.0` when that comes available.
