### ISSUE TITLE
Horizontal event alignment

### ISSUE THREAD

**Issue by sandorvasas** [intljusticemission/react-big-calendar#886]
#### Do you want to request a _feature_ or report a _bug_?
bug
#### What's the current behavior?
See screenshot: appointment indented further after the middle, 15 min appointment.
![rbc_bug](https://user-images.githubusercontent.com/9200077/41904992-f6c0a868-798d-11e8-896d-c63e3cb464f4.png)
#### Expected behavior:
The two events in the middle should be aligned horizontally to start at the same x position.

#### Suggested fix:
DayEventLayout.js
```
function onSameRow(a,b) {
  return (
    // Occupies the same start slot.
    (Math.abs(b.start - a.start) < 15) ||
    // A's start slot overlaps with b's end slot.
    (b.start > a.start && b.start < a.end)
  )
}
```

At the moment a,b events in the second part of the condition are swapped, and the first part, the difference is set to 30 mins. Should I create a PR?

**Comment by arecvlohe** [comment]
Fixed in #910
