### ISSUE TITLE
Click inside event should disable the select slot event

### ISSUE THREAD

**Issue by f2net** [intljusticemission/react-big-calendar#89]
I need to have the Selectable option enabled, so that it is possible to create new events.
The problem is that **clicking on an existing** event sometimes works, but **often triggers the select slot event instead**. I think that clicking inside an event box should trigger only the event-selected event.

Thank you,
Matteo

**Comment by jquense** [comment]
hi there, the problem is that if you can't drag to select over events it sakes the target area for adding a new event really small when there are lots of events on a day. you'd have to select over in the tiny margin which isn't intuitive.

**Comment by f2net** [comment]
Thank you for your quick and clear answer.
I understand that selecting over a tiny margin isn't intuitive, but my users find very unintuitive that clicking on an event 9 times out of 10 don't work and selects a new slot instead :)
Maybe we could select a slot only when dragging happens with min 10 pixels?

Thank you

**Comment by jquense** [comment]
There is a tolerance of 5px already, I'm reticent to increase it more as that starts to feel wonky beyond that...if you want to PR something that allows adjusting the click tolerance tho i'd be open to it.

**Comment by f2net** [comment]
I see that in your "selectable" example it works much better. On my calendar (I have the last version 0.9.11) clicking near the vertical center of the half-an-hour slot always causes the slot to be selected instead of the event (without moving of any pixels).

Here's my code:
```javascript
import React, { Component, PropTypes } from 'react';
import { connect } from 'react-redux';
import BigCalendar from 'react-big-calendar';
import moment from 'moment';

import { fetchSlots } from '../../actions';

import './calendario.less';

const Event = ({ event }) => {
  return (
    <span>
      <p className="descrizione">{event.title}</p>
			<p className="numero-appuntamenti">{`${event.numeroAppuntamenti} / ${event.numeroMassimoCandidati}`}</p>
    </span>
  )
}

class CalendarioAppuntamenti extends Component {

	static contextTypes = {
		router: PropTypes.object
	};

	constructor(props) {
		super(props);

		// Voglio l'ora su 24 ore
		let timeRangeFormat = ({ start, end }, culture, local) =>
			local.format(start, 'HH:mm', culture) +
			' - ' + local.format(end, 'HH:mm', culture);

		this.state = {

			messages: {
				date: 'Data',
				time: 'Ora',
				event: 'Appuntamento',
				allDay: 'Tutto il giorno',
				previous: '<',
				next: '>',
				today: 'Oggi',
				month: 'Mese',
				week: 'Settimana',
				day: 'Giorno',
				agenda: 'Agenda'
			},

			formats: {
				selectRangeFormat: timeRangeFormat,
				agendaTimeFormat: timeRangeFormat,
				agendaTimeRangeFormat: timeRangeFormat
			},

			events: this.props.events
		}
	}

	componentWillMount() {
		moment.locale('it');
		BigCalendar.momentLocalizer(moment);
		this.props.fetchSlots();
	}

	creaSlotAppuntamenti(slot) {
		// After selecting, DaySlot fires a setState (to set "selecting" to false)
		// ==> I have to wait a moment, otherwise I receive an error because of
		// the setState on Unmounted component :S
		setTimeout(() => {
			const start = moment(slot.start).format();
			const end = moment(slot.end).format();
			this.context.router.push(`/appuntamenti/new?start=${start}&end=${end}`);
		}, 100);

	}

	modificaSlotAppuntamenti(slotId) {
		this.context.router.push(`/appuntamenti/${slotId}`);
	}

	render() {
		return (
			<div className="card-box calendario" style={{height: 550+'px'}}>
				<BigCalendar
					selectable
					events={this.props.events}
					defaultView='week'
					messages={this.state.messages}
					formats={this.state.formats}
					min={new Date(2016,1,1,8,0,0)}
					max={new Date(2016,1,1,20,0,0)}
					components={{event: Event}}
					onSelectSlot={(slot) => this.creaSlotAppuntamenti(slot)}
					onSelectEvent={(event) => this.modificaSlotAppuntamenti(event.slotId)}
				/>
			</div>
		);
	}
}

function mapStateToProps(state) {
	return {
		events: state.slots
	};
}

export default connect(mapStateToProps, { fetchSlots })(CalendarioAppuntamenti);

```


Anyway, I think that the best thing would be to have two props:
- SlotsSelectable
- EventsSelectable

so that it would be possibile to switch between the two editing modes (slots or events).
What do you think about it?

Thank you,
Matteo
