### ISSUE TITLE
ToolTip - Show time in Month View

### ISSUE THREAD

**Issue by shruti-rao** [intljusticemission/react-big-calendar#890]
#### Do you want to request a _feature_ or report a _bug_?
bug
#### What's the current behavior?
Select "Month" view and hover over an appointment, the tool tip doesn't show the time (shows only the title).  
http://intljusticemission.github.io/react-big-calendar/examples/index.html

#### What's the expected behavior?
Show time in tool tip, consistent with other views

**Comment by arecvlohe** [comment]
Happy to accept a PR for this
