### ISSUE TITLE
Feature request: selectedSlot prop

### ISSUE THREAD

**Issue by dmitrykrylov** [intljusticemission/react-big-calendar#893]
#### Do you want to request a _feature_ or report a _bug_?

Feature

#### What's the current behavior?

Selected slots are reset after mouse up.

#### What's the expected behavior?

I would like to have possibility of controlling selected slots state in parent component

**Comment by karltaylor** [comment]
Can't you just pass the the selectedSlot data to a parent component?

**Comment by dmitrykrylov** [comment]
@karltaylor thanks, I finally solved this with the way your proposed and setting styles to selected slots using slotPropGetter.
However, in my opinion, it would be nice to have a possibility to show time range inside selected area by making this condition controllable: https://github.com/intljusticemission/react-big-calendar/blob/74113867fcd72e28772794ac2e521009682efd18/src/DayColumn.js#L140
