### ISSUE TITLE
Element ref was specified as a string (inner) but no owner was set. 

### ISSUE THREAD

**Issue by karamat** [intljusticemission/react-big-calendar#895]
Hi I have followed the example

http://intljusticemission.github.io/react-big-calendar/examples/index.html#intro

"dependencies": {
  "@rails/webpacker": "^3.3.1",
  "babel-preset-react": "^6.24.1",
  "bootstrap": "4.0.0",
  "react": "^16.2.0",
  "react-big-calendar": "^0.19.2",
  "react-dom": "^16.2.0",
},

It giving this error https://cl.ly/3z3c42292l0e

**Comment by jquense** [comment]
you have multiple copies of react installed! Sorry i know the error says that, but that is actually the propblem 99.9999% of the time, even tho it can feel like its not

**Comment by kgdiem** [comment]
@amanmibra I ran into this issue tonight on a new project (no other dependencies) after installing react-big-calendar v 0.19.1 with React 16.4.1. 

I was able to remedy it by installing React 15.6.2 instead.

**Comment by jquense** [comment]
`yarn list` my be misleading, i think it only checks the what the lockfile says, not what is on disk. nuke node_modules _and_ yarn.lock and reinstall to get an accurate picture

**Comment by amanmibra** [comment]
Yea, it still shows up as one dep

**Comment by zbaylin** [comment]
I too am having this same issue -- it looks like some libraries are having this issue with newer versions of React.

**Comment by kelleg1** [comment]
Having this issue as well. In my case I have react-big-calendar installed into a module that is being transpiled with Babel before being used by another module. When I use react-big-calendar from the top-level module directly, I do not have this problem. Any ideas? I tried listing react, react-dom, and react-big-calendar as devDependencies and peerDependencies in the submodule to no avail.

**Comment by jquense** [comment]
The issue is multiple instances of react or react-dom, there isn't anything we can do as a library, please double check your build process
