### ISSUE TITLE
Feature request: additional buttons for toolbar (as renderable)

### ISSUE THREAD

**Issue by mkontula** [intljusticemission/react-big-calendar#90]
Generally what makes my users angry is the lack of datepicker control to jump to specific day or month. Such button, much calendar would a be a great addition. I might take it for a spin and make a PR if interested. Original idea was to provide extension point and prop for adding your own buttons to the toolbar. How bout that?

**Comment by jquense** [comment]
the toolbar is intentionally simple to reduce extra dependencies, so I don't want to add a date-picker as part of the default. However, I would be fine with making the _entire_ toolbar replaceable, but anything more detailed then that is going to invariably not work for a bunch of folks who want to do more then just add buttons.

For what it's worth, we just turn off the toolbar and create a custom one with a calendar component from react-widgets to navigate to a specific date.

**Comment by mkontula** [comment]
Replaceable custom toolbar sounds great. It could get the navigation function and constants as prop from utils/navigation? In that case, custom toolbar could do whatever it (or it's maker) thinks is worth at any given use case.

**Comment by craig-day** [comment]
@mkontula @jquense for what it's worth, I made this simple PR that makes the entire toolbar replaceable with your own component.  https://github.com/intljusticemission/react-big-calendar/pull/91
