### ISSUE TITLE
Be able to drag events so they recur on multiple days at certain time

### ISSUE THREAD

**Issue by nabeelz6** [intljusticemission/react-big-calendar#903]
#### Do you want to request a _feature_ or report a _bug_?
Feature. 

Similar to #355. Not sure if this is already possible via ```react-big-calendar/lib/addons/dragAndDrop```?

#### What's the current behavior?

In Week view, you cannot drag an event horizontally across days so it can recur the same time on consecutive days (e.g. between 4 and 8 PM every Tuesday and Wednesday). Right now you can only drag horizontally across days for all day events.

Workaround for dragging is to have the user manually create the same event for the same hours (interval) multiple times.

#### What's the expected behavior?

Be able to drag an event horizontally across days so it can recur the same time on consecutive days (e.g. between 4 and 5 PM every Tuesday and Wednesday). Ideally, the library would treat this multi-day same time event as one block so you can delete the group together. You should also be able to resize or move this group.

Example mock-up; I'd like to be able to drag on react-big-calendar so I can create this multi-day certain time event:
![multiple-days-same-time](https://user-images.githubusercontent.com/36421/42703027-3d48b222-8699-11e8-9563-2fa0740432ac.png)

**Comment by arecvlohe** [comment]
This is a feature request but will not be supported out of the box per #355. You will need to handle this programmatically on your end.
