### ISSUE TITLE
how to render a custom popup

### ISSUE THREAD

**Issue by neove** [intljusticemission/react-big-calendar#904]
when i click '+x more' button, i want to show my custom popup to display more events.  i check the document , however there is no API for this. is there any help ? thanks

**Comment by amkoehler** [comment]
#610 added an optional `onDrilldown` to the Calendar component. This might be what you're looking for.

**Comment by arecvlohe** [comment]
@neove I think you will need to update the styles of the overlay element to achieve what you are looking to do. Because there has not been any activity on this I will close for now.
