### ISSUE TITLE
Pass an existing backend to withDragAndDrop - a practical example

### ISSUE THREAD

**Issue by artooras** [intljusticemission/react-big-calendar#905]
I'm attempting to use `react-dnd` and `react-big-calendar` `withDragAndDrop` in an app together. However, if I initiate them separately, I get an error:

`Uncaught Error: Cannot have two HTML5 backends at the same time.`

I know this error has already been discussed in a few tickets, like [this one](https://github.com/intljusticemission/react-big-calendar/issues/350). However, looking at the current [documentation](https://github.com/intljusticemission/react-big-calendar/blob/master/src/addons/dragAndDrop/withDragAndDrop.js) of `withDragAndDrop` it appears that the solution in the PR linked from above-mentioned ticket has been replaced with an optional backend that can be passed.

The big question for me is - **how do I get the same backend _instance_ so I can use it in two places?**

Here's my code:

**App.js**
```
import React from 'react'
import {DragDropContext} from 'react-dnd'
import HTML5Backend from 'react-dnd-html5-backend'
import Calendar from './Calendar'

class App extends React.Component {
  render() {
    return {
      <div>
        ...
        <Calendar />
      </div>
    }
  }
}

export default DragDropContext(HTML5Backend)(App)
```

**Calendar.js**
```
import React from 'react'
import BigCalendar from 'react-big-calendar'
import withDragAndDrop from 'react-big-calendar/lib/addons/dragAndDrop'

const Calendar = withDragAndDrop(BigCalendar)
...
```

As you can see, my `Calendar` component is a child of my `App` component where I set the `react-dnd DragDropContext`. So, how do I pass the same backend instance down to the `Calendar` component?

`react-dnd` documentation for [`DragDropContext`](http://react-dnd.github.io/react-dnd/docs-drag-drop-context.html) mentions an instance method `getManager()` which should help me retrieve the backend (`getManager().getBackend()`). However, the key here is _instance_ method. How do I get the instance of `DragDropContext(HTML5Backend)(App)` from my Calendar.js file?

I'm quite new to React, and I have a feeling the answer is quite trivial, I just can't figure it out. I will appreciate any help!

**Comment by rhuanbarreto** [comment]
Hi @artooras! I'm also a newbie in react, but I don't think that it should be the best way to do it. I think that you should have all in the same file as per the example on [this file](https://github.com/intljusticemission/react-big-calendar/blob/master/examples/demos/dnd.js).

This is my calendar component:

```js
import React from 'react'
import events from './events'
import HTML5Backend from 'react-dnd-html5-backend'
import { DragDropContext } from 'react-dnd'
import BigCalendar from 'react-big-calendar'
import moment from 'moment'
import withDragAndDrop from 'react-big-calendar/lib/addons/dragAndDrop'
import 'react-big-calendar/lib/addons/dragAndDrop/styles.css'
import 'react-big-calendar/lib/css/react-big-calendar.css'

BigCalendar.momentLocalizer(moment);
const DragAndDropCalendar = withDragAndDrop(BigCalendar)

class Calendar extends React.Component {
  constructor(props) {
    super(props)
    this.state = {
      events: events,
    }
    this.moveEvent = this.moveEvent.bind(this)
    this.newEvent = this.newEvent.bind(this)
  }

  moveEvent({ event, start, end }) {
    const { events } = this.state

    const idx = events.indexOf(event)
    const updatedEvent = { ...event, start, end }

    const nextEvents = [...events]
    nextEvents.splice(idx, 1, updatedEvent)

    this.setState({
      events: nextEvents,
    })

    alert(`${event.title} was dropped onto ${event.start}`)
  }

  resizeEvent = (resizeType, { event, start, end }) => {
    const { events } = this.state

    const nextEvents = events.map(existingEvent => {
      return existingEvent.id === event.id
        ? { ...existingEvent, start, end }
        : existingEvent
    })

    this.setState({
      events: nextEvents,
    })

    alert(`${event.title} was resized to ${start}-${end}`)
  }

  newEvent(event) {
    let idList = this.state.events.map((a) => a.id);
    let newId = Math.max(...idList) + 1;
    let hour = {
      id: newId,
      title: 'New Event',
      allDay: event.slots.length === 1,
      start: event.start,
      end: event.end,
    }
    this.setState({
      events: this.state.events.concat([hour])
    });
  }

  render() {
    return (
      <DragAndDropCalendar
        selectable
        resizable
        events={this.state.events}
        onEventDrop={this.moveEvent}
        onEventResize={this.resizeEvent}
        onSelectSlot={this.newEvent}
        defaultView={BigCalendar.Views.WEEK}
        defaultDate={new Date(2015, 3, 12)}
        style={{ height: "100vh" }}
      />
    )
  }
}

export default DragDropContext(HTML5Backend)(Calendar)
```

This is my application:

```js
import React, { Component } from 'react';
import Calendar from './calendar/Calendar';
import { Sidebar } from './Sidebar';
import 'bootstrap/dist/css/bootstrap.css';
import '@fortawesome/fontawesome-free/js/all.js';

class App extends Component {
  render() {
    return (
      <div className="row">
        <div className="col-1 bg-light flex-grow-1 flex-shrink-1">
          <Sidebar />
        </div>
        <div className="col">
          <Calendar />
        </div>
      </div>
    );
  }
}

export default App;
```

**Comment by artooras** [comment]
Thanks @rhuanbarreto for the example. It looks a little strange though.. I thought that `withDragAndDrop` creates a `DragAndDropContext` under the hood, but you initiate it explicitly when exporting your Calendar. Does it work? [Other implementations](https://github.com/arecvlohe/rbc-with-dnd-starter/blob/master/src/App.js) I have seen don't do this.

Also, my case is slightly different. I need to create the `DragAndDropContext` on the `App` as I need it for more than the scope of the Calendar - I simply need the Calendar to re-use the same backend.

**Comment by rhuanbarreto** [comment]
Yes it works. This comes from [the examples](https://github.com/intljusticemission/react-big-calendar/blob/master/examples/demos/dnd.js) in the repo.

**Comment by arecvlohe** [comment]
I think we were able to resolve this on discord but feel free to reopen if another issue arises.

**Comment by artooras** [comment]
We have. Just for those running into the same issue and looking for an answer, the secret is to explicitly omit a backend from `withDragAndDrop`, like so:

`const DragAndDropCalendar = withDragAndDrop(BigCalendar, { backend: false })`
