### ISSUE TITLE
Bug on events width when changing the step or timeslots argument

### ISSUE THREAD

**Issue by bgelineau** [intljusticemission/react-big-calendar#909]
#### Do you want to request a _feature_ or report a _bug_?

bug

#### What's the current behavior?

The computation to see if events are on the same row is broken when someone changes the `step` or `timeslots` arguments. Linked to #886 but different, as the current problem arises from the hard coded minutes implemented in the computation.

![bug](https://user-images.githubusercontent.com/1941277/43008811-48460a28-8c3c-11e8-952f-2eaa68116e1e.png)

Full sample implementation on https://codesandbox.io/s/j39nx6x793

#### What's the expected behavior?

The events should each take the whole width.

**Comment by arecvlohe** [comment]
Fixed in #910
