### ISSUE TITLE
Not resizable calendar shows resize graphics for events.

### ISSUE THREAD

**Issue by rhuanbarreto** [intljusticemission/react-big-calendar#914]
Even if the calendar is not resizable, the resize handlers appears on the event.

See it below.

[![Edit j37nk8zqz9](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/j37nk8zqz9)

**Comment by arecvlohe** [comment]
@rhuanbarreto What version of rbc are you using? Looks like this is handled in the latest release (0.19.2): https://github.com/intljusticemission/react-big-calendar/blob/db322f5adad12f0a6a4f37de55f8cb7fd9062d1e/src/addons/dragAndDrop/DraggableEventWrapper.js#L106

**Comment by arecvlohe** [comment]
Ah I see, it looks as though an event is defaulted to being resizable even if there is not a `resizable` prop being passed down. Therefore, you need to set the resizable prop on each event.

**Comment by arecvlohe** [comment]
Or you can set the resizable accessor to always pass back false.

**Comment by rhuanbarreto** [comment]
But even if I set `resizeable={false}` on the calendar component it doesn't work. The resize handlers are still there.

**Comment by rhuanbarreto** [comment]
This doesn't exist on the API definition right? Can you say how can I make it?

**Comment by arecvlohe** [comment]
The resizableAccessor is in the API of drag and drop. So on the calendar you would put something like this: `<Calendar resizableAccessor={() => false} />`

https://github.com/intljusticemission/react-big-calendar/blob/db322f5adad12f0a6a4f37de55f8cb7fd9062d1e/src/addons/dragAndDrop/DraggableEventWrapper.js#L106
