### ISSUE TITLE
Inconistent date format when using showMultiDayTimes

### ISSUE THREAD

**Issue by eps1lon** [intljusticemission/react-big-calendar#918]
#### Do you want to request a _feature_ or report a _bug_?
_bug_

#### What's the current behavior?
Format for dates is different for multi day events and non multi day events.
![rbc_multiday_localizer_bug](https://user-images.githubusercontent.com/12292047/43181840-5dd62c3c-8fdf-11e8-81c3-1640484e6707.png)

##### localizer:
```typescript
BigCalendar.setLocalizer(BigCalendar.momentLocalizer(moment));
```

##### dependencies:
`react-big-calendar@0.18.1`
`moment@2.22.2`

#### What's the expected behavior?
Same format is used.

**Comment by jquense** [comment]
This is intentional, you can change all the event range formates to match if you want them to be the same. Thanks!

**Comment by eps1lon** [comment]
I don't understand why the default format for multi day events does not match the default format for single day events. I get that I'm able to change the format but why do I provide a localizer if that localizer is not used by default?

Maybe I didn't make myself clear: The issue is not about the format of the range but the format of the time which should be formatted equally regardless of multi day event or not.

**Comment by jquense** [comment]
O! I see what you're saying, yes that seems to be a bug with the moment localizer.
