### ISSUE TITLE
components.header undocumented

### ISSUE THREAD

**Issue by eps1lon** [intljusticemission/react-big-calendar#924]
#### Do you want to request a _feature_ or report a _bug_?
_question_

Currently TimeGridHeader makes use of a header component that can be passed from Calendar. https://github.com/intljusticemission/react-big-calendar/blob/d2e02c4bfde41b39ea22db344cbd8b948b17fc8b/src/TimeGridHeader.js#L70

The property is however [not documented](http://intljusticemission.github.io/react-big-calendar/examples/index.html#prop-components). Is this indeed only an implementation detail or meant for actual usage? Currently this seems to be the only way to render a custom header for days in the week view.

**Comment by jquense** [comment]
It's intended for use, it's an oversight it's not documented! If your up for it, the fix is adding it to the proptype in Calendar.js

**Comment by eps1lon** [comment]
Will do. Thanks.

**Comment by eps1lon** [comment]
One question remains: 

https://github.com/intljusticemission/react-big-calendar/commit/d2e02c4bfde41b39ea22db344cbd8b948b17fc8b#diff-3a1d9f7d22bf911fb6fa60b0b0daae4cL105 removed some passed props. Was this on accident or was this indeed a breaking change? This could however be considered a non-breaking change since it was not documented before. Just need to know this for the relevant `@types` PR.

**Comment by jquense** [comment]
yes intentional, `format` and `culture` are long longer needed as the localizer knows them already

**Comment by eps1lon** [comment]
Well then I think only the pending PR is left. Closing here.
