### ISSUE TITLE
Month and day does not work preview

### ISSUE THREAD

**Issue by henriqueweiand** [intljusticemission/react-big-calendar#933]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

![erro bigcalenddar](https://user-images.githubusercontent.com/6539492/43535420-50a9c5e4-9590-11e8-8338-830d5f3fad0c.gif)

Code:

```js
...
import BigCalendar from 'react-big-calendar';
import moment from 'moment';
import { getEvents } from '~/services/google-calendar';

import styles from './styles';

moment.locale('pt-BR');
BigCalendar.setLocalizer(BigCalendar.momentLocalizer(moment));

require('react-big-calendar/lib/css/react-big-calendar.css');

class Contatos extends Component {
  state = {
    events: [],
  };

  componentDidMount() {
    getEvents((events) => {
      this.setState({ events });
    });
  }

  render() {
    const { location } = this.props;

    return (
      <Layout loading={false} title="Agenda" location={location}>
        <BigCalendar events={this.state.events} />
      </Layout>
    );
  }
}

...
```

#### What's the expected behavior?

Should work normally

**Comment by jquense** [comment]
I'm gonna guess your events start and end dates are not `Date` objects?

**Comment by arecvlohe** [comment]
@henriqueweiand What events are you passing in? In the code there are none but in your screen shot it looks like there is 1 event on the calendar.

**Comment by henriqueweiand** [comment]
I was integrating with google calendar, but actually in the return of the events I was not converting to Date.

Thank you guys!

**Comment by GusMartins499** [comment]
Hello guys, i'm from Brazil, and i want change all react-big-calendar to portuguese-br (pt-BR/ptBR). With lib moment thats works, but, i need use date-fns, and thats not working, someone can help me, please ?

`
import { Calendar, momentLocalizer } from 'react-big-calendar';
import moment from 'moment';
import 'moment/locale/pt-br';
const localizer = momentLocalizer(moment);

const messages = {
        allDay: 'Dia Inteiro',
        previous: '<',
        next: '>',
        today: 'Hoje',
        month: 'Mês',
        week: 'Semana',
        day: 'Dia',
        agenda: 'Agenda',
        date: 'Data',
        time: 'Hora',
        event: 'Evento',
        showMore: (total) => `+ (${total}) Eventos`,

<Calendar
                            style={{ height: '95%' }}
                            eventPropGetter={(event) => {
                                return {
                                    style: {
                                        backgroundColor: '#3f51b5',
                                        borderRadius: '8px',
                                        minHeight: '10px',
                                    },
                                };
                            }}
                            messages={messages}
                            selectable
                            localizer={localizer}
                            events={events}
                            startAccessor="start"
                            endAccessor="end"
                            onSelectSlot={(slot) => handleOpenDialog(slot)}
                            onSelectEvent={(event) => handleOpenEvent(event)}
                        />
![Captura de tela 2021-03-09 100115](https://user-images.githubusercontent.com/43645525/110474428-69141f00-80be-11eb-92d7-0b10ae3aadaa.png)

    };

`

Using date-fns:

`
import { Calendar, dateFnsLocalizer
![Captura de tela 2021-03-09 100506-2](https://user-images.githubusercontent.com/43645525/110474874-f3f51980-80be-11eb-9a95-686081500886.png)
 } from 'react-big-calendar';
import {  parse, startOfWeek, getDay } from 'date-fns';
import 'date-fns/locale/pt-BR';
const locales = {
    'pt-BR': require('date-fns/locale/pt-BR'),
};
const localizer = dateFnsLocalizer({
    format,
    parse,
    startOfWeek,
    getDay,
    locales,
});
`

**Comment by igoramos77** [comment]
> Hello guys, i'm from Brazil, and i want change all react-big-calendar to portuguese-br (pt-BR/ptBR). With lib moment thats works, but, i need use date-fns, and thats not working, someone can help me, please ?
> 
> ```js
> import { Calendar, momentLocalizer } from 'react-big-calendar';
> import moment from 'moment';
> import 'moment/locale/pt-br';
> const localizer = momentLocalizer(moment);
> 
> const messages = {
>         allDay: 'Dia Inteiro',
>         previous: '<',
>         next: '>',
>         today: 'Hoje',
>         month: 'Mês',
>         week: 'Semana',
>         day: 'Dia',
>         agenda: 'Agenda',
>         date: 'Data',
>         time: 'Hora',
>         event: 'Evento',
>         showMore: (total) => `+ (${total}) Eventos`,
> 
> <Calendar
>     style={{ height: '95%' }}
>     eventPropGetter={(event) => {
>         return {
>             style: {
>                 backgroundColor: '#3f51b5',
>                 borderRadius: '8px',
>                 minHeight: '10px',
>             },
>         };
>     }}
>     messages={messages}
>     selectable
>     localizer={localizer}
>     events={events}
>     startAccessor="start"
>     endAccessor="end"
>     onSelectSlot={(slot) => handleOpenDialog(slot)}
>     onSelectEvent={(event) => handleOpenEvent(event)}
> />
> ```
> 
> ![Captura de tela 2021-03-09 100115](https://user-images.githubusercontent.com/43645525/110474428-69141f00-80be-11eb-92d7-0b10ae3aadaa.png)
> 
> Using date-fns:
> 
> ```js
>   import { Calendar, dateFnsLocalizer } from 'react-big-calendar';
>   
>   import {  parse, startOfWeek, getDay } from 'date-fns';
>   
>   import 'date-fns/locale/pt-BR';
>   
>   const locales = {
>       'pt-BR': require('date-fns/locale/pt-BR'),
>   };
>   
>   const localizer = dateFnsLocalizer({
>       format,
>       parse,
>       startOfWeek,
>       getDay,
>       locales,
>   });
> ```
> 
> ![Captura de tela 2021-03-09 100506-2](https://user-images.githubusercontent.com/43645525/110474874-f3f51980-80be-11eb-9a95-686081500886.png)

Conseguiu resolver, @GusMartins499?
Obrigado!

**Comment by GusMartins499** [comment]
> > Hello guys, i'm from Brazil, and i want change all react-big-calendar to portuguese-br (pt-BR/ptBR). With lib moment thats works, but, i need use date-fns, and thats not working, someone can help me, please ?
> > ```js
> > import { Calendar, momentLocalizer } from 'react-big-calendar';
> > import moment from 'moment';
> > import 'moment/locale/pt-br';
> > const localizer = momentLocalizer(moment);
> > 
> > const messages = {
> >         allDay: 'Dia Inteiro',
> >         previous: '<',
> >         next: '>',
> >         today: 'Hoje',
> >         month: 'Mês',
> >         week: 'Semana',
> >         day: 'Dia',
> >         agenda: 'Agenda',
> >         date: 'Data',
> >         time: 'Hora',
> >         event: 'Evento',
> >         showMore: (total) => `+ (${total}) Eventos`,
> > 
> > <Calendar
> >     style={{ height: '95%' }}
> >     eventPropGetter={(event) => {
> >         return {
> >             style: {
> >                 backgroundColor: '#3f51b5',
> >                 borderRadius: '8px',
> >                 minHeight: '10px',
> >             },
> >         };
> >     }}
> >     messages={messages}
> >     selectable
> >     localizer={localizer}
> >     events={events}
> >     startAccessor="start"
> >     endAccessor="end"
> >     onSelectSlot={(slot) => handleOpenDialog(slot)}
> >     onSelectEvent={(event) => handleOpenEvent(event)}
> > />
> > ```
> > 
> > 
> > ![Captura de tela 2021-03-09 100115](https://user-images.githubusercontent.com/43645525/110474428-69141f00-80be-11eb-92d7-0b10ae3aadaa.png)
> > Using date-fns:
> > ```js
> >   import { Calendar, dateFnsLocalizer } from 'react-big-calendar';
> >   
> >   import {  parse, startOfWeek, getDay } from 'date-fns';
> >   
> >   import 'date-fns/locale/pt-BR';
> >   
> >   const locales = {
> >       'pt-BR': require('date-fns/locale/pt-BR'),
> >   };
> >   
> >   const localizer = dateFnsLocalizer({
> >       format,
> >       parse,
> >       startOfWeek,
> >       getDay,
> >       locales,
> >   });
> > ```
> > 
> > 
> > ![Captura de tela 2021-03-09 100506-2](https://user-images.githubusercontent.com/43645525/110474874-f3f51980-80be-11eb-9a95-686081500886.png)
> 
> Conseguiu resolver, @GusMartins499?
> Obrigado!

Olá Igor, desculpe a demora para lhe responder, tive que dar uma pausa no desenvolvimento dessa tela, pois tinha outras prioridades, não consegui resolver ainda, você tem alguma sugestão ?
