### ISSUE TITLE
Where in the code are event widths calculated?

### ISSUE THREAD

**Issue by klinskyc** [intljusticemission/react-big-calendar#940]
#### Do you want to request a _feature_ or report a _bug_?
Clarification Question
#### What's the current behavior?
React Big Calendar is automatically assigning widths to events. What file (and lines of code) are responsible for calculating this? I'm working on adding a preventOverlap feature, similar to FullCalendar

Thanks!

**Comment by jquense** [comment]
its in the DayLayout mostly
