### ISSUE TITLE
Feature request: Keep selected slots in calendar

### ISSUE THREAD

**Issue by jancama2** [intljusticemission/react-big-calendar#941]
I haven't find an easy way to keep slots selected in the calendar when a user selects them.

#### Do you want to request a _feature_ or report a _bug_?
Feature

#### What's the current behavior?
After selecting the slots I store them externally and render them as events and style them to look like selected slots.

#### What's the expected behavior?
Controlled component:
```
class Calendar extends Component {
    static state = {
        slots = null,
    }

    handleSelectSlot = (slots) => {
        this.setState({
             slots,
        });
    }

    render() {
         return (
             <BigCalendar
                 selectedSlot={this.state.slots}
                 onSelectSlot={this.handleSelectSlot}
             />
         );
    }
}
```

**Comment by maltel** [comment]
I would like that as well.

**Comment by dmitrykrylov** [comment]
@jancama2  I'm not sure what you mean...
> render them as events
but you can use `slotPropGetter` to style your selected slots

**Comment by turkus** [comment]
I wrote a comment above, because I had the same issue, but with the events. I solved that issue today in the following way:

```
class Calendar extends Component {
    constructor () {
        super()
        this.state = {
            selectedEvent: null
        }
        this.onSelectEvent = this.onSelectEvent.bind(this)
        this.setEventProps = this.setEventProps.bind(this)
    }   
        
    onSelectEvent = (event, e) => {
        this.setState({
            selectedEvent: event,
        });
    }   

    setEventProps (event, start, end, isSelected) {
        if (!this.state.selectedEvent) return
        return {
            className: event.id === this.state.selectedEvent.id ? 'rbc-selected' : ''
        }
    }   

    render() {
         return (
             <BigCalendar
                 onSelectEvent={this.onSelectEvent}
                 eventPropGetter={this.setEventProps}
             />
         );      
    } 
} 
```
Maybe it would be helpful with the slots.
The good thing is, that you can set other attributes in `setEventProps` by passing them in the returning object, just like the `className`.

cc @jancama2 @maltel
