### ISSUE TITLE
Edit an existing Event

### ISSUE THREAD

**Issue by FlavianoMucedda** [intljusticemission/react-big-calendar#946]
So i set up the calendar in a way that when i select a time slot (long or short, whatever)

It open a modal where i have to fill the kind of info i need for an event then submit and BAM event done.

But i would like to edit the event if i made a mistake while creating it or if some infos change before the event...

i use firebase as database for the storage of the event and i kinda struggle to get the already existing info in the event cell and to edit them... any idea?

**Comment by schester44** [comment]
theres an onSelectEvent prop that you can use. It provides the calendar vent as the first argument which you can then use to show a modal or whatever you want to do.
