### ISSUE TITLE
Terrible docs

### ISSUE THREAD

**Issue by Stas-Buzunko** [intljusticemission/react-big-calendar#947]
It took me ~30 minutes to find an event format that is ridiculous.

I'm sorry if I somehow missed it in docs, despite the fact I've read them fully 3 times.

If it wasn't an example in /examples/events.js , I have no idea how much time it would take.

Please add event format to docs or at least link to examples

**Comment by jquense** [comment]
> least link to examples
there is a link to the example code on every example

there is no event format, use accessor functions to adapt the calendar to whatever your format is. We added a clearer not but it's not deployed. 

Also take your entitled attitude elsewhere.
