### ISSUE TITLE
how translate toolbar

### ISSUE THREAD

**Issue by Deboracgs** [intljusticemission/react-big-calendar#958]
How translate toolbar ( today, month, week ....) ???

any examples?

**Comment by jquense** [comment]
The messages prop

**Comment by jquense** [comment]
please read the documentation: http://intljusticemission.github.io/react-big-calendar/examples/index.html#prop-messages for things without examples the best bet is to browse the source to see how the props are used.

**Comment by Deboracgs** [comment]
@jquense  is posible translate the show more?

**Comment by jquense** [comment]
its possible to translate everything

**Comment by Deboracgs** [comment]
@jquense  is not possible in "show more", by type be function

**Comment by jquense** [comment]
yes it's possible. Please search past issues, and read the code. You'll have better luck getting the answers you need by doing a bit of preliminary work before opening issues. Small OSS projects don't often have  a lot of time for providing support via the issue tracker. Please be respectful of their time and try to find the answer before opening new issues

**Comment by Deboracgs** [comment]
My other solutions, I only open when I do not think so.

The document does not have enough examples. @jquense

**Comment by tfmertz** [comment]
As @jquense linked, pass an object with the month, day, year, etc values in the messages prop;

```
<BigCalendar
  localizer={localizer}
  events={[]}
  startAccessor="start"
  endAccessor="end"
  messages={{
    month: 'My month word',
    day: 'My day word',
    today: 'this day',
  }}
/>
```
You could also use an translation library to get the strings

```
import __ from 'i18next';

const messages = {
  month: __.t('Month');
  ...
}

<BigCalendar
  ...
  messages={messages}
/>
```

**Comment by mathieutu** [comment]
duplicate https://github.com/intljusticemission/react-big-calendar/issues/428

**Comment by FouMez** [comment]
Hello,
how can i change the << all day >> that appears in the agenda?

**Comment by LauLogisch** [comment]
These are the messages I found can be set: 

```
<Calendar
  localizer={localizer}
  events={[]}
  startAccessor="start"
  endAccessor="end"
  messages={{
                agenda: 'Agenda',
                allDay: 'Hele dag',
                month: 'Maand',
                day: 'Dag',
                today: 'Vandaag',
                previous: 'Terug',
                next: 'Volgende',
                date: 'Datum',
                noEventsInRange: 'Er zijn geen agenda-items in deze periode',
                time: 'Tijd',
                tomorrow: 'Morgen',
                week: 'Week',
                work_week: 'Werkweek',
                yesterday: 'Gisteren'
            }}
/>
```

**Comment by TimDaub** [comment]
> These are the messages I found can be set:

In case you're wondering about where these messages are defined in the code base and what their default values are: Check [here](https://github.com/jquense/react-big-calendar/blob/dbcc5785a0d2edd2c710706538389344dba737a8/src/utils/messages.js#L1).

**Comment by tonyabracadabra** [comment]
> These are the messages I found can be set:
> 
> ```
> <Calendar
>   localizer={localizer}
>   events={[]}
>   startAccessor="start"
>   endAccessor="end"
>   messages={{
>                 agenda: 'Agenda',
>                 allDay: 'Hele dag',
>                 month: 'Maand',
>                 day: 'Dag',
>                 today: 'Vandaag',
>                 previous: 'Terug',
>                 next: 'Volgende',
>                 date: 'Datum',
>                 noEventsInRange: 'Er zijn geen agenda-items in deze periode',
>                 time: 'Tijd',
>                 tomorrow: 'Morgen',
>                 week: 'Week',
>                 work_week: 'Werkweek',
>                 yesterday: 'Gisteren'
>             }}
> />
> ```

Thanks! Then where can we translate Monday, Tuesday, ... Sunday in there?

**Comment by msanli220** [comment]
> > These are the messages I found can be set:
> > ```
> > <Calendar
> >   localizer={localizer}
> >   events={[]}
> >   startAccessor="start"
> >   endAccessor="end"
> >   messages={{
> >                 agenda: 'Agenda',
> >                 allDay: 'Hele dag',
> >                 month: 'Maand',
> >                 day: 'Dag',
> >                 today: 'Vandaag',
> >                 previous: 'Terug',
> >                 next: 'Volgende',
> >                 date: 'Datum',
> >                 noEventsInRange: 'Er zijn geen agenda-items in deze periode',
> >                 time: 'Tijd',
> >                 tomorrow: 'Morgen',
> >                 week: 'Week',
> >                 work_week: 'Werkweek',
> >                 yesterday: 'Gisteren'
> >             }}
> > />
> > ```
> 
> Thanks! Then where can we translate Monday, Tuesday, ... Sunday in there?


Hello! its probably too late for answer, maybe it will help people who have the same problem. You can change the date names with this lines. Here is an example of change language to turkish.
   moment.locale('tr-TR');
   const localizer = momentLocalizer(moment);

**Comment by Vladyleal** [comment]
> > These are the messages I found can be set:
> > ```
> > <Calendar
> >   localizer={localizer}
> >   events={[]}
> >   startAccessor="start"
> >   endAccessor="end"
> >   messages={{
> >                 agenda: 'Agenda',
> >                 allDay: 'Hele dag',
> >                 month: 'Maand',
> >                 day: 'Dag',
> >                 today: 'Vandaag',
> >                 previous: 'Terug',
> >                 next: 'Volgende',
> >                 date: 'Datum',
> >                 noEventsInRange: 'Er zijn geen agenda-items in deze periode',
> >                 time: 'Tijd',
> >                 tomorrow: 'Morgen',
> >                 week: 'Week',
> >                 work_week: 'Werkweek',
> >                 yesterday: 'Gisteren'
> >             }}
> > />
> > ```
> 
> Thanks! Then where can we translate Monday, Tuesday, ... Sunday in there?

Hi! I had the same problem. I could translate the date with the import corresponding to the language you want to translate, in my case Spanish.
>> import 'moment/locale/es';

Also added in the Calendar component ...

>> <Calendar 
>> culture='es'
>> />

**Comment by cutterbl** [comment]
Actually, according to source code these are the `messages` you can set.

```js
{
  date: 'Date',
  time: 'Time',
  event: 'Event',
  allDay: 'All Day',
  week: 'Week',
  work_week: 'Work Week',
  day: 'Day',
  month: 'Month',
  previous: 'Back',
  next: 'Next',
  yesterday: 'Yesterday',
  tomorrow: 'Tomorrow',
  today: 'Today',
  agenda: 'Agenda',

  noEventsInRange: 'There are no events in this range.',

  showMore: total => `+${total} more`,
}
```

For reference, `culture` is only applied to the `formats` (date/time formatting).
