### ISSUE TITLE
Missing some documentation

### ISSUE THREAD

**Issue by JoelKlint** [intljusticemission/react-big-calendar#96]
Hi, 

The documentation is generally very good but forgets to mention things.
For example the Time gutter can be formatted with
```js
const formats = { timeGutterFormat: 'format goes here' }
<BigCalendar
    formats={formats}
/>
```

**Comment by Commander-lol** [comment]
+1 to this
I'll post some of the things here that aren't in the docs (yet) to help out:
- the `step` prop dictates the increments used when selecting time ranges, in minutes (e.g. default is 30 minute steps, settings `step` to `15` makes them 15 minute steps

**Comment by jquense** [comment]
PR's welcome :) I try to keep docs updated but don't always have time. If you'd like to help out you can  adjust/add a comment to the proptype in src/Calendar
