### ISSUE TITLE
Get date of day slot when dragging an event over it.

### ISSUE THREAD

**Issue by MinhNguyen41092** [intljusticemission/react-big-calendar#960]
Hi guys. Would it be possible to get the date of a day slot of Week view when I drag an event over it? I want to grey-out time slots in that day that are outside of event's available time.

**Comment by MinhNguyen41092** [comment]
@jquense Thanks for your response. What I want is when I drag an event (a custom component) over a day slot in Week view I want to get the date of that time slot. `onSelecting` won't be called when I do that because you need to drag the view, not the event, to make it invoked.

**Comment by jquense** [comment]
Gotcha, hmm yeah I'm not sure what an API for that would be, we do have the logic for settings dates at the mouse pointer by I'm not sure what the right API is for "exposing" that info to ouside the the calendar. Any suggestions?

**Comment by MinhNguyen41092** [comment]
Hmm I think we can use the `hover()` method of DropTarget to get the day slot component. Then based on the start date of the calendar and the index of that day slot in the parent component we can get the date. But seems like I cant access `component` param of `hover()` with the current API though.

**Comment by jquense** [comment]
I'd be wary tho, if your relying on react-dnd's API it's being removed in the next version
