### ISSUE TITLE
Selecting event doesn't work with react-modal

### ISSUE THREAD

**Issue by dkanas** [intljusticemission/react-big-calendar#964]
#### Do you want to request a _feature_ or report a _bug_?
Bug
#### What's the current behavior?

When calendar is used in a popup, and `onSelectEvent` updates the state of the popup, the event is deselected right after the click:
https://codesandbox.io/s/q9k66269mj

#### What's the expected behavior?

The event should stay selected and have the `.rbc-selected` class

**Comment by FernandoBoza** [comment]
I used the modal from [ReactStrap](https://reactstrap.github.io/components/modals/)
