### ISSUE TITLE
Week starting from saturday when moment timezone and browser timezones are different

### ISSUE THREAD

**Issue by KartikShankhavaram** [intljusticemission/react-big-calendar#967]
#### Do you want to request a _feature_ or report a _bug_?
Report a bug
#### What's the current behavior?
I am using moment as a localizer. I have the set the timezone as America/New York. When I open the calendar with the browser in that time zone(ET), it works fine. However, when I open it from my timezone(IST), it starts the day from Saturday. I have made some customisation to the calendar, one of which uses the dayOfWeek value to do something. And because of this localizer thing, it's breaking.  
![rbc-bug](https://user-images.githubusercontent.com/17466582/44564228-893d9600-a77f-11e8-85ea-0372027fa315.png)

It even adds this extra empty line on the calendar, because of the localizer problem.
![rbc-bug-2](https://user-images.githubusercontent.com/17466582/44564233-8cd11d00-a77f-11e8-964f-7c1d15047b62.png)

#### What's the expected behavior?
It should start from Sunday, no matter what the timezone is.

The week starts from Sunday if I change my browser timezone to ET. This works fine.
![rbc-expected](https://user-images.githubusercontent.com/17466582/44564364-200a5280-a780-11e8-9c64-929f93321e24.png)

Can anyone help me with this problem? I've sat at it for hours and even checked the issues section but I couldn't find a solution. Thank you so much!

PS: Btw, since I'm showing the events using my own layout using a custom DateCellWrapper and I only need to show the calendar for a single locale(en-US), is there any way I can skip adding the localizer to BigCalendar?

**Comment by KartikShankhavaram** [comment]
Btw, since I'm showing the events using my own layout using a custom DateCellWrapper and I only need to show the calendar for a single locale(en-US), is there any way I can skip adding the localizer to BigCalendar?

**Comment by arecvlohe** [comment]
Also check #118

**Comment by Apol0x** [comment]
Hi, I found this possible result for your question. It was useful to me, I don't know if it will help you
[Stackoverflow-- question 45671732 ](https://stackoverflow.com/questions/45671732/react-big-calendar-start-week-from-monday-instead-of-sunday)
