### ISSUE TITLE
Element ref was specified as a string (inner) but no owner was set. This could happen for one of the following reasons:

### ISSUE THREAD

**Issue by xeastcrast** [intljusticemission/react-big-calendar#968]
!!! Important info
I using Next.js 6 (React SSR Library)
Node.js version 10.x.x

#### Do you want to request a _feature_ or report a _bug_?
I'm report a bug
#### What's the current behavior?
When I write Calendar Component in to render method and save it, On the browser give me error below.
```
Invariant Violation: Element ref was specified as a string (inner) but no owner was set. This could happen for one of the following reasons:
1. You may be adding a ref to a functional component
2. You may be adding a ref to a component that was not created inside a component's render method
3. You have multiple copies of React loaded
See https://fb.me/react-refs-must-have-owner for more information.
```

![react error ref](https://user-images.githubusercontent.com/12433101/44591503-17e5fd80-a7e8-11e8-9543-e6f7ab3187b4.PNG)

#### What's the expected behavior?
I want it work on next.js

#### Solution that i tried already
1. ``npm ls react`` && ``yarn list react`` and it show only one react version
2. remove node_module folder and reinstall every module by ``npm install``

**Comment by jquense** [comment]
You have multiple copies of React or react-dom. There is no other way for the library to cause this issue, and isn't anything we can do about it unfortunately. yarn and npm often don't actually report multiple copies of react, you may have to do a manual inspection.

**Comment by xeastcrast** [comment]
@jquense But I have remove node_module and reinstall everything in my project. It isn't multiple copies react, I'm sure.

**Comment by telnet2** [comment]
It happened to me when I used react-big-calendar with `yarn link react-big-calendar`. With `yarn link`, it automatically created `node_modules/react`, which doesn't exist when `yarn add react-big-calendar`.
