### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by dbuchet-bandc** [intljusticemission/react-big-calendar#969]
Hi there,
When is planned the next release on npm?

I can see many fixes on master which are not deployed on 0.19.2

Thanks

**Comment by jquense** [comment]
when we get around to it and master has the bugs worked out

**Comment by kvas-damian** [comment]
@jquense is there a list of issues somewhere? I know there is a bug label, but not all of them are related to the next release.
Such a list will definitely help us what to focus on to get the new version out. Maybe we could introduce another label, like "regression"?
