### ISSUE TITLE
Show only work days for "week" view ?

### ISSUE THREAD

**Issue by jdeniau** [intljusticemission/react-big-calendar#97]
Hi, 

First of all thanks you for the job you have done here !

Is it possible to "hide" some days, or display only work days.

I saw in your constant file a `WORKWEEK` constant, but seems never used.
I saw the "range" method in the Week.jsx file is calling `endOf('week')` .

I tried hiding in in CSS but did not manage to do this.

Do you have a way to do it ? I can make you a PR if you point me on something, but as the localizers does not have the notion of working days, it is not really easy. The solution I may have is to force de Week view range. 

Thank you

**Comment by jquense** [comment]
The Views are meant to be pluggable and it would be really easy to make a weekday only version of the Week view, but there is currently a bug blocking that. If you wanted to PR a fix there, that would be the best way to help, more details here:  https://github.com/intljusticemission/react-big-calendar/pull/93#issuecomment-219718646

**Comment by jdeniau** [comment]
Ok I will give a look at it in the next days.

Thanks
