### ISSUE TITLE
Error: Module not found: Error: Can't resolve '@babel/runtime/helpers/builtin/extends'

### ISSUE THREAD

**Issue by jaganaath** [intljusticemission/react-big-calendar#971]
Module not found: Error: Can't resolve '@babel/runtime/helpers/builtin/extends'

Support required. Thanks.

**Comment by arecvlohe** [comment]
@jaganaath Please create a codesandbox example with a reproduction of your issue.

**Comment by apuntovanini** [comment]
@jaganaath I ran yarn install instead of npm, it worked for me

**Comment by karltaylor** [comment]
I have just done a fresh install `npm i --save react-big-calendar` and received this error.

**Comment by jquense** [comment]
@karltaylor v20 removed that API thats why it doesn't exist, check the getting started docs for the new setup

**Comment by karltaylor** [comment]
@jquense Quite a big change no? Does this repo not use semver?
