### ISSUE TITLE
onSelectSlot doesn't work in Mobile

### ISSUE THREAD

**Issue by Mostafasaffari** [intljusticemission/react-big-calendar#972]
Hello guys 
onSelectSlot work fine in desktop but in mobile or ipad doesn't work. can anybody help me?

**Comment by innovative-lab** [comment]
I am facing the same issue. Getting this error every time i try to select one date.

> **[Intervention] Ignored attempt to cancel a touchstart event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.**

**Comment by guilherme-guimaraes** [comment]
Same issue here too

**Comment by yaronism** [comment]
Did anyone got a solution for that issue?

**Comment by paradyo** [comment]
still waiting for solution

**Comment by silnose** [comment]
hello! any updates?
