### ISSUE TITLE
events don't match with hours

### ISSUE THREAD

**Issue by sanaAbdessattarManai** [intljusticemission/react-big-calendar#974]
Hi,
I'm using react big calendar to plannify some events for  my application. i can display my events but they don't match with hours taken in calender.
![image](https://user-images.githubusercontent.com/40690981/44990476-671ef180-af91-11e8-8ebc-2f311899c388.png)
For example, for shift 2, it starts at 9:00 pm and ends at 5 am, but here it starts at 1:00pm.
Any idea about this problem please? Thanks

**Comment by jquense** [comment]
Please provide a repro demonstrating the issue that we troubleshoot thanks!

**Comment by sanaAbdessattarManai** [comment]
Sorry, i forget my contact informations to upload my repo into a git. This is my code if you can help me.

* demoEvents.js
import moment from 'moment';
const events = [

  {
    allDay: false,
    id:3,
    start: '2018-08-29T06:00:00.000Z',
    end: '2018-08-29T14:00:00.000Z',
    status:"intialised"
  },{
    allDay: false,
    id:2,
    start: '2018-08-27T07:00:00.000Z',
    end: '2018-08-27T15:00:00.000Z',
    status:"intialised"
  },
  {
    allDay: false,
    id:1,
    start: '2018-08-28T08:00:00.000Z',
    end: '2018-08-28T16:00:08.000Z',
    status:"intialised"
  }
];
/*
const datediff = new moment(new Date()).diff(
  new moment('2018-06-01T18:23:07.322Z'),
  'days'
);
*/
events.forEach((event, index) => {
  events[index].id = `${index + 1}`;
  events[index].title = `shift ${index + 1}`;
  events[index].desc = `Desc of event ${index + 1}`;
  events[index].start = new moment(event.start).toDate();
  events[index].end = new moment(event.end).toDate();
  events[index].status = event.status;
});
export default events.splice(0, 10);
*modalEvents
import React, { Component } from 'react';
import moment from 'moment';
import Input from '../../../components/uielements/input';
import { DateRangepicker } from '../../../components/uielements/datePicker';
import Modal from '../../../components/feedback/modal';
import { CalendarModalBody } from './calendar.style';
import Button from '../../../components/uielements/button';
import DeleteButton from './deleteButton';
import calendarActions from "../../redux/calendar/actions";
import { connect } from "react-redux";
import { Icon } from 'antd';
import {rtl} from '../../../settings/withDirection';

const { acceptEvent, rejectEvent,resetEvent } = calendarActions;

const RangePicker = DateRangepicker;
const margin = {
  margin: rtl === 'rtl'
    ? '2px'
    : '2px'
};

const localeDatePicker = {
  lang: {
    placeholder: 'Select date',
    rangePlaceholder: ['Start date', 'End date'],
    today: 'Today',
    now: 'Now',
    backToToday: 'Back to today',
    ok: 'Ok',
    clear: 'Clear',
    month: 'Month',
    year: 'Year',
    timeSelect: 'Select time',
    dateSelect: 'Select date',
    monthSelect: 'Choose a month',
    yearSelect: 'Choose a year',
    decadeSelect: 'Choose a decade',
    yearFormat: 'YYYY',
    dateFormat: 'M/D/YYYY',
    dayFormat: 'D',
    dateTimeFormat: 'M/D/YYYY HH:mm:ss',
    monthFormat: 'MMMM',
    monthBeforeYear: true,
    previousMonth: 'Previous month (PageUp)',
    nextMonth: 'Next month (PageDown)',
    previousYear: 'Last year (Control + left)',
    nextYear: 'Next year (Control + right)',
    previousDecade: 'Last decade',
    nextDecade: 'Next decade',
    previousCentury: 'Last century',
    nextCentury: 'Next century'
  },
  timePickerLocale: {
    placeholder: 'Select time'
  }
};
class modalEvents extends Component {
  handleOk = () => {
    this.props.setModalData('ok', this.props.selectedData);
  };
  handleCancel = () => {
    this.props.setModalData('cancel');
  };

  handleDelete = () => {
    this.props.setModalData('delete', this.props.selectedData);
  };
  handleaccept = ()=>{
    console.log("status to accept "+this.props.selectedData.id);
    this.props.acceptEvent(this.props.selectedData.id);
  };
  handlereject = ()=> {
    console.log("status to reject "+this.props.selectedData.id);
    this.props.rejectEvent(this.props.selectedData.id);
  };
  handlereset = ()=> {
    console.log("status to reset "+this.props.selectedData.id);
    this.props.resetEvent(this.props.selectedData.id);
  }

  render() {
    const { modalVisible, selectedData, setModalData } = this.props;
    const visible = modalVisible ? true : false;
    if (!visible) {
      return <div />;
    }
    const title = selectedData && selectedData.title ? selectedData.title : '';
    const desc = selectedData && selectedData.desc ? selectedData.desc : '';
    const status = selectedData.status ;

    const start =
      selectedData && selectedData.start ? moment(selectedData.start) : '';
    const end =
      selectedData && selectedData.end ? moment(selectedData.end) : '';
    const onChangeTitle = event => {
      selectedData.title = event.target.value;
      setModalData('updateValue', selectedData);
    };
    const onChangeDesc = event => {
      selectedData.desc = event.target.value;
      setModalData('updateValue', selectedData);
    };
    const onChangeFromTimePicker = value => {
      try {
        selectedData.start = value[0].toDate();
        selectedData.end = value[1].toDate();
      } catch (e) {}
      setModalData('updateValue', selectedData);
    };

    return (
      <div>
        <Modal
          title={modalVisible === 'update' ? 'Select choice' : 'New Event'}
          visible={visible}
          onOk={this.handleOk}
          onCancel={this.handleCancel}
          okText="ok"
          cancelText="Cancel"
        >
          <CalendarModalBody>
            <div className="isoCalendarInputWrapper">
              <h2>{title}</h2>
            </div>

            <div className="isoCalendarInputWrapper">
              <h2>{status}</h2>
            </div>

            <div className="isoCalendarDatePicker">
              <RangePicker
                locale={localeDatePicker}
                ranges={{
                  Today: [moment(), moment()],
                  'This Month': [moment(), moment().endOf('month')]
                }}
                value={[start, end]}
                showTime
                format="YYYY/MM/DD HH:mm:ss"
                onChange={onChangeFromTimePicker}
              />
            </div>

            <div className="isobtn">
             <Button type="primary"
                     style={margin}
                     htmlType="submit"
                     onClick={this.handleaccept}>
                     <Icon type="check" />
              Accept
             </Button>
             &nbsp;&nbsp;
              <Button
                      type="primary"
                      htmlType="submit"
                      onClick={this.handlereject}>
                      <Icon type="close" />
              Refuse
             </Button>
             &nbsp;&nbsp;
             <Button
                     type="primary"
                     htmlType="submit"
                     onClick={this.handlereset}>
                     <Icon type="reload" />
             Reset
            </Button>
            </div>
          </CalendarModalBody>
        </Modal>
      </div>
    );
  }}

  function mapStateToProps(state) {
    console.log(state.Calendar);
    //console.log( state.Calendar.status);
    //const status  = state.Calendar.status;
    //console.log(events);
    return {avent:state.Calendar.events} ;
  }

export default connect(mapStateToProps, {acceptEvent,rejectEvent,resetEvent })(
  modalEvents
);
 * DnDCalendar.js:
import React, { Component } from 'react';
import BigCalendar from 'react-big-calendar';
import moment from 'moment';
import HTML5Backend from 'react-dnd-html5-backend';
import { DragDropContext } from 'react-dnd';
import withDragAndDrop from 'react-big-calendar/lib/addons/dragAndDrop';

BigCalendar.momentLocalizer(moment);
const Calendar = withDragAndDrop(BigCalendar);

function EventAgenda({ event }) {
  return (
    <span>
      <em style={{ color: 'magenta' }}>{event.title}</em>
      <p>{event.desc}</p>
    </span>
  );
}

class FullCalender extends Component {
  render() {
    const calendarOptions = {
      popup: true,
      selectable: true,
      className: 'isomorphicCalendar',
      agenda: {
        event: EventAgenda
      }
    };
    return <Calendar {...calendarOptions} {...this.props} />;
  }
}
const CalendarExample = DragDropContext(HTML5Backend)(FullCalender);
export default CalendarExample;

* Calendar.js:
import React, { Component } from "react";
import { connect } from "react-redux";
import clone from "clone";
import notification from "../../../components/notification";
import ModalEvents from "./modalEvents";
import calendarActions from "../../redux/calendar/actions";
import { CalendarStyleWrapper } from "./calendar.style";
import DnDCalendar from "./DnDCalendar";
const { changeView, changeEvents,acceptEvent, rejectEvent } = calendarActions;

const getIndex = (events, selectedEvent) =>
  events.findIndex(event => event.id === selectedEvent.id);

    const minTime = new Date();
       minTime.setHours(6,0,0);
    const maxTime = new Date();
       maxTime.setHours(24,0,0);

class FullCalender extends Component {
  state = {
    view: this.props.view,
    modalVisible: false,
    selectedData: undefined,
    minTime: minTime,
    maxTime: maxTime,
  };


  onSelectEvent = selectedData => {
    this.setState({ modalVisible: "update", selectedData });
  };
  onSelectSlot = selectedData => {
    this.setState({ modalVisible: "new", selectedData });
  };
  onView = view => {
    this.props.changeView(view);
  };
  onEventDrop = newOption => {
    const { event, start, end } = newOption;
    const events = clone(this.props.events);
    const allDay = new Date(end).getTime() !== new Date(start).getTime();
    const updatedEvent = { ...event, start, end, allDay };
    const index = getIndex(events, updatedEvent);
    events[index] = clone(updatedEvent);
    this.props.changeEvents(events);
    notification(
      "success",
      "Move event successfully",
      `${event.title} was dropped onto ${event.start}`
    );
  };
  setModalData = (type, selectedData) => {
    const { changeEvents } = this.props;
    const events = clone(this.props.events);
    const { modalVisible } = this.state;
    if (type === "cancel") {
      this.setState({
        modalVisible: false,
        selectedData: undefined
      });
    } else if (type === "delete") {
      const index = getIndex(events, selectedData);
      if (index > -1) {
        events.splice(index, 1);
      }
      changeEvents(events);
      this.setState({
        modalVisible: false,
        selectedData: undefined
      });
    } else if (type === "updateValue") {
      this.setState({ selectedData });
    } else {
      if (modalVisible === "new") {
        events.push(selectedData);
      } else {
        const index = getIndex(events, selectedData);
        if (index > -1) {
          events[index] = selectedData;
        }
      }
      changeEvents(events);
      this.setState({
        modalVisible: false,
        selectedData: undefined
      });
    }
  };

  propGetter = (event,start,end,isSelected) => {
    let clr = "blue";
    if(typeof event.status==='undefined'){
        console.log(event.status);
        clr = "grey";
    }
    if( event.status==='intialised'){
        console.log(event.status);
        clr = "blue";
    }
    else if( event.status==='pending'){
        console.log(event.status);
        clr = "blue";
    }else if(event.status==='accepted'){
        console.log(event.status);
        clr = "green";
    }
    else if(event.status==='refused')
    {
        console.log(event.status);
        clr = "red";
    }
    return { className:"toto",style:{backgroundColor:clr} };
  }

  render() {
    const { view, events } = this.props;
    const { modalVisible, selectedData } = this.state;
    const calendarOptions = {
      events,
      view,
      selectedData,
      onSelectEvent: this.onSelectEvent,
      onSelectSlot: this.onSelectSlot,
      onView: this.onView,
      onEventDrop: this.onEventDrop,
      eventPropGetter:this.propGetter,
      min:this.state.minTime,
      max:this.state.maxTime,
      step:30,
      timeslot:3,


    };
    return (
      <CalendarStyleWrapper className="isomorphicCalendarWrapper"
        >
        <ModalEvents
          modalVisible={modalVisible}
          selectedData={selectedData}
          setModalData={this.setModalData}
          />
        <DnDCalendar {...calendarOptions} />
      </CalendarStyleWrapper>
    );
  }
}

function mapStateToProps(state) {
  console.log(state);
  const { events, view } = state.Calendar;
  return { events, view };
}
export default connect(mapStateToProps, { changeView, changeEvents })(
  FullCalender
);

**Comment by jquense** [comment]
unfortunatelly that's not helpful, can you use something like codesandbox and reduce the code to just the broken calendar, thanks
