### ISSUE TITLE
Popup doesn't follow its day after resizing

### ISSUE THREAD

**Issue by RodrigoSantini** [intljusticemission/react-big-calendar#977]
#### Do you want to request a _feature_ or report a _bug_?
bug
 
#### What's the current behavior?
 
In month view, when I click the "+x more" link to see the inline popup of all the events, and resize the window, the popup does not follow the parent day, getting static on the screen.
 
see: http://recordit.co/iBtbNknMuI
 

react-big-calendar: 0.19.2
react: 15.5.0
browser: Chrome 68.0.3440.106 / 64 bits
 
#### What's the expected behavior?
When the window resizes, it should close the popup or align with your day.

**Comment by lucasmathioni** [comment]
up
