### ISSUE TITLE
Custom view

### ISSUE THREAD

**Issue by ZhoraKhachatryanArmweb** [intljusticemission/react-big-calendar#978]
Hello,in this package how create custom view

**Comment by pedroaliens** [comment]
Hi,
I think you can achieve this by passing a custom component to "views" prop.
See this link: http://intljusticemission.github.io/react-big-calendar/examples/index.html#prop-views for more details.

```javascript
views={{
  month: true,
  week: false,
  myCustomView: MyCustomViewComponent,
}}
```

**Comment by jquense** [comment]
yup

**Comment by ZhoraKhachatryanArmweb** [comment]
Yes its work,but not show title on the header

**Comment by ZhoraKhachatryanArmweb** [comment]
ok guys,i solve it,thanks
