### ISSUE TITLE
Text Overflow CSS fix causing overflow of entire calendar on mobile displays

### ISSUE THREAD

**Issue by eminx** [intljusticemission/react-big-calendar#979]
When there's minimum two events with long name within same row (same week in month view, and same day in week view), where CSS `text-overflow: ellipsis` fix is used; the layout on mobile displays break. The entire calendar enlarges to span outside of the viewport.

I have tried to find out a fix to implement it, but couldn't really come up with one. Any suggestions?

Attention to the events at the left and right handside:

<img width="484" alt="screen shot 2018-09-05 at 21 49 23" src="https://user-images.githubusercontent.com/22205310/45117338-9b430f80-b155-11e8-84dc-fc1c8f8b9f0e.png">

**Comment by design3d-blender** [comment]
Could this issue be reopened? I've been dealing with this exact problem myself. If one or more events on the same line have a long name, the calendar will extend from the containing element and overflow the page horizontally.
