### ISSUE TITLE
create event with double click

### ISSUE THREAD

**Issue by ZhoraKhachatryanArmweb** [intljusticemission/react-big-calendar#986]
How can i create event with double click on the slot? 
which props can i use?

**Comment by karltaylor** [comment]
I would advise to use the [Reactiflux Discord](https://discord.gg/uJsgpkC) to ask questions like this.

**Comment by vosho** [comment]
Hello, did you find any solutions?

**Comment by vosho** [comment]
> https://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/props--on-select-slot

Thanks
