### ISSUE TITLE
to customize the date range display

### ISSUE THREAD

**Issue by henriqueweiand** [intljusticemission/react-big-calendar#990]
#### Do you want to request a _feature_ or report a _bug_?

_feature_

#### What's the current behavior?

would it be possible to customize the date range display? like this example with am, pm?

![captura de tela 2018-09-17 as 12 44 36](https://user-images.githubusercontent.com/6539492/45633947-84ff5280-ba77-11e8-86d9-863abda05e39.png)

My expectation is to get something like this

![captura de tela 2018-09-17 as 12 42 41](https://user-images.githubusercontent.com/6539492/45633885-5bdec200-ba77-11e8-9c70-ec4e10cb43eb.png)

**Comment by jquense** [comment]
yes, you can provide the appropriate `format` to control that.

**Comment by alansutherland** [comment]
yet another detailed and informative answer from @jquense

**Comment by alansutherland** [comment]
The code you're looking for if you found this issue and don't want to spend 10 minutes picking through the sparse react-big-calnedar API documentation and Moment.js format codes:

```
formats={{
     timeGutterFormat: 'HH:mm'
}}
```
