### ISSUE TITLE
Access resourceId of selected column in onSelectSlot callback

### ISSUE THREAD

**Issue by tylergaugler16** [intljusticemission/react-big-calendar#991]
#### Do you want to request a _feature_ or report a _bug_?
feature
#### What's the current behavior?
Right now, i am passing the react-big-calendar component a resource prop, as well as passing a callback to the onSelectSlot function, that accesses slotInfo. Currently, slotInfo is not able to access the resourceId of it's current column. How can I access the resourceId in this setting?

#### What's the expected behavior?
That in the OnSelectSlot callback, we can access the resourceId of the current column. 

```
<Calendar 
          resources={this.state.currentView === "week" ? null : this.props.resources}
          resourceIdAccessor="resourceId"
          resourceTitleAccessor="resourceTitle"
          onSelectSlot={(slotInfo: any) => {
                slotInfo.resourceId // I would like to access resourceId here 
          } }
        />
```

**Comment by lilbumblebear** [comment]
It would also be nice to be able to access the resource id of the slot with slotPropGetter, if the calendar has resources set.

**Comment by AmitTurner** [comment]
Yes indeed its a missing feature...
select spot is pretty stale without it.

**Comment by jquense** [comment]
happy to take a PR!
