### ISSUE TITLE
Only in Agenda, events not showing up except if multi days

### ISSUE THREAD

**Issue by yohanology** [intljusticemission/react-big-calendar#992]
#### Do you want to request a _feature_ or report a _bug_?
bug (v0.19.2)

#### What's the current behavior?
Events are showing up fine on Month/Week/Day view, but not on Agenda view: only multidays events are showing up, others not.

#### What's the expected behavior?
All kinds of events should show up.

For the moment, I fall back to react-big-calendar v0.17 which solves the problem.

**Comment by dmitrykrylov** [comment]
Seems that agenda view behaves like month view and decrements/increments by month
<img width="741" alt="screen shot 2018-09-25 at 15 19 07" src="https://user-images.githubusercontent.com/14343880/46013955-65e76d00-c0d6-11e8-9b84-31628b8d03e4.png">

**Comment by jquense** [comment]
please provide a repro using the issue template thanks!

**Comment by dmitrykrylov** [comment]
@jquense you can check out a codesandbox from #1006: https://codesandbox.io/s/04x04zw91p

Switch to agenda and play with Back/Next, it look strange
