### ISSUE TITLE
Optional Sort

### ISSUE THREAD

**Issue by codesignist** [intljusticemission/react-big-calendar#993]
Please make this sort optional.
https://github.com/intljusticemission/react-big-calendar/blob/6a94e72ad27affc0d00bd298659bfa987ce33b0e/src/Month.js#L155

When I disable the sort I achieve this:

![calendar](https://user-images.githubusercontent.com/1472881/45747515-bc543780-bc0e-11e8-81d1-53dd69c02921.PNG)

**Comment by codesignist** [comment]
Is there anybody?

**Comment by jquense** [comment]
happy to take PR adding pluggable sorting. in general though we find the current sorting appropriate for the widest range of use cases so will leave it the default thanks!

**Comment by codesignist** [comment]
But when I want to colorize the events and I want to make green ones on top.
But automatic sort makes a sort for longest events on top.
At least this sort should be optional so we can make our special sort.

Thank you.

**Comment by jquense** [comment]
sure i understand there is a use case for controlling it just that it's not a high priority to support for us. If it's important to you, please do send over a PR!
