### ISSUE TITLE
Changing view in each date cell in Month View

### ISSUE THREAD

**Issue by s2c130050131527** [intljusticemission/react-big-calendar#995]
Feature 
#### What's the current behavior?
Current the events are rendered in a blue box from start to end Date.
 
#### What's the expected behavior?
I want to change how Events Are Rendered in each cell.
If anybody has seen how google calendar is rendering events in latest version.
They show each event in each date cell. 
I want to extend that functionality and I tried to overload eventWrapper which you can see in the below sandbox :

https://codesandbox.io/s/94rrr34r9r

It only adds event in the start position of the row or date cell.

if you need any clarification please ask . Please refer to the sandbox also. All ideas are welcome . Thanks in advance

**Comment by riyazbhanvadia** [comment]
@tobiasandersen @jquense @srajko @bkniffler 

Any updates?

**Comment by jquense** [comment]
I'm not really sure what the ask is here, the latest google calendar i can see renders events mostly the same way as us, rendering the event from the start to end, not on each day. You can control the style of events using css and the various class hooks to render multi-day or all-day events differently
