### ISSUE TITLE
Disable the show more

### ISSUE THREAD

**Issue by The-Code-Monkey** [intljusticemission/react-big-calendar#996]
#### Do you want to request a _feature_ or report a _bug_?

feature

#### What's the current behavior?

show more appears when over 3 events

#### What's the expected behavior?

there should be a show all boolean on the component that shows all event no matter what

**Comment by jquense** [comment]
please see the 40000 existing issues about this thanks

**Comment by The-Code-Monkey** [comment]
That was what I did first and non of them highlighted the issue i was facing that I could find. would you kindly link me to one.

**Comment by The-Code-Monkey** [comment]
This should be shown more clearly in the docs, in my opinion maybe add the docs to the .readme rather than the website you have

**Comment by alxvallejo** [comment]
@jquense None of your comments are helpful here. Adding truncateEvents={false} doesn't seem to do anything on the v0.33.2
