### ISSUE TITLE
New CSS breaks big calendar layout

### ISSUE THREAD

**Issue by karltaylor** [intljusticemission/react-big-calendar#998]
#### Do you want to request a _feature_ or report a _bug_?

Bug 
#### What's the current behavior?

Latest CSS breaks Big Calendar. Updated to latest release and updated latest css and this is what shows:

```js
                  <BigCalendar
                    localizer={localizer}
                    events={fixAvailability(this.props.availability, {
                      hideConfirmed: true,
                      hidePrevious: true
                    })}
                    startAccessor='start'
                    endAccessor='end'
                  />
```

![screen shot 2018-09-22 at 17 17 44](https://user-images.githubusercontent.com/6763109/45919322-840d5d00-be8b-11e8-9aa0-d1d870645482.png)
![screen shot 2018-09-22 at 17 17 48](https://user-images.githubusercontent.com/6763109/45919323-840d5d00-be8b-11e8-8209-f3a63469ad92.png)
![screen shot 2018-09-22 at 17 17 55](https://user-images.githubusercontent.com/6763109/45919324-840d5d00-be8b-11e8-83fe-8e6a5b29d60c.png)

**Comment by jquense** [comment]
Please use the codesandbox template to post a working repro. The docs site is working fine with the css, you like have some conflicting style or extension
